<Workspace Version="1.0.0.1180" X="94.6041153966303" Y="-4.3962725535219" zoom="0.878940113562795" Name="Home" Description="" RunType="Manual" RunPeriod="1000" HasRunWithoutCrash="True">
  <NamespaceResolutionMap />
  <Elements>
    <PythonNodeModels.PythonNode guid="83af5be1-cae5-424f-ad99-a4c4514d75b9" type="PythonNodeModels.PythonNode" nickname="Python Script" x="362.146329102386" y="246.749755858254" isVisible="true" isUpstreamVisible="true" lacing="Disabled" isSelectedInput="False" IsFrozen="false" isPinned="false" inputcount="2">
      <Script>#Put view on sheet
import clr
clr.AddReference('RevitAPI')
from Autodesk.Revit.DB import *

clr.AddReference("RevitNodes")
import Revit
clr.ImportExtensions(Revit.Elements)

clr.AddReference("RevitServices")
import RevitServices
from RevitServices.Persistence import DocumentManager
from RevitServices.Transactions import TransactionManager

import clr
clr.AddReference('ProtoGeometry')

from Autodesk.DesignScript.Geometry import *

doc = DocumentManager.Instance.CurrentDBDocument
#The inputs to this node will be stored as a list in the IN variables.
grids = UnwrapElement(IN[0])

a = UnwrapElement(IN[1])

if a == "0":
	b = DatumEnds.End0
else:
	b = DatumEnds.End1

	# "Start" the transaction
TransactionManager.Instance.EnsureInTransaction(doc)

view = doc.ActiveView	

for grid in grids:
	
	grid.HideBubbleInView(DatumEnds.End0, view);
	grid.HideBubbleInView(DatumEnds.End1, view);
	grid.ShowBubbleInView(b, view);

# "End" the transaction
TransactionManager.Instance.TransactionTaskDone()


#Assign your output to the OUT variable.
OUT = 0
</Script>
    </PythonNodeModels.PythonNode>
    <Dynamo.Nodes.DSModelElementsSelection guid="f8724d8d-89a2-4147-b4d5-5e1f3e025d2f" type="Dynamo.Nodes.DSModelElementsSelection" nickname="Select Model Elements" x="-52.2217869764133" y="196.648252838515" isVisible="true" isUpstreamVisible="true" lacing="Disabled" isSelectedInput="True" IsFrozen="false" isPinned="false">
      <instance id="e73b8783-23bd-4e35-865c-8d45e8f721fe-00160450" />
      <instance id="e73b8783-23bd-4e35-865c-8d45e8f721fe-00160467" />
      <instance id="e73b8783-23bd-4e35-865c-8d45e8f721fe-00160472" />
      <instance id="e73b8783-23bd-4e35-865c-8d45e8f721fe-00160474" />
      <instance id="e73b8783-23bd-4e35-865c-8d45e8f721fe-00160476" />
      <instance id="e73b8783-23bd-4e35-865c-8d45e8f721fe-00160478" />
    </Dynamo.Nodes.DSModelElementsSelection>
    <Dynamo.Graph.Nodes.CodeBlockNodeModel guid="e2476417-30aa-42bd-a505-72d2e4b3c21c" type="Dynamo.Graph.Nodes.CodeBlockNodeModel" nickname="Code Block" x="62.8370975420705" y="501.245198401363" isVisible="true" isUpstreamVisible="true" lacing="Disabled" isSelectedInput="False" IsFrozen="false" isPinned="false" CodeText="&quot;1&quot;;" ShouldFocus="false" />
    <Dynamo.Graph.Nodes.CodeBlockNodeModel guid="61fb4471-fd9e-4ed8-a82c-0609edb3c5b1" type="Dynamo.Graph.Nodes.CodeBlockNodeModel" nickname="Code Block" x="58.1376767143517" y="376.022596137437" isVisible="true" isUpstreamVisible="true" lacing="Disabled" isSelectedInput="False" IsFrozen="false" isPinned="false" CodeText="&quot;0&quot;;" ShouldFocus="false" />
  </Elements>
  <Connectors>
    <Dynamo.Graph.Connectors.ConnectorModel start="f8724d8d-89a2-4147-b4d5-5e1f3e025d2f" start_index="0" end="83af5be1-cae5-424f-ad99-a4c4514d75b9" end_index="0" portType="0" />
    <Dynamo.Graph.Connectors.ConnectorModel start="e2476417-30aa-42bd-a505-72d2e4b3c21c" start_index="0" end="83af5be1-cae5-424f-ad99-a4c4514d75b9" end_index="1" portType="0" />
  </Connectors>
  <Notes>
    <Dynamo.Graph.Notes.NoteModel guid="9e9f3043-44dc-41f1-8e01-5fccc9a2e946" text="Grid End 0" x="61.0873744382113" y="339.375388941171" />
    <Dynamo.Graph.Notes.NoteModel guid="8a852e8d-cdeb-41f3-9f15-78a2d30a4756" text="Grid End 1" x="60.4236092526241" y="470.238070090824" />
    <Dynamo.Graph.Notes.NoteModel guid="1232dd88-a00f-47bb-8451-8f92ad3f1022" text="Swap Bubble Grid Ends" x="358.796917922167" y="211.457093195893" />
    <Dynamo.Graph.Notes.NoteModel guid="1a742895-352b-4f26-9a5e-b062f2a9cf55" text="Select Grids" x="36.8523133081123" y="155.95600551027" />
  </Notes>
  <Annotations />
  <Presets />
  <Cameras>
    <Camera Name="Background Preview" eyeX="-17" eyeY="24" eyeZ="50" lookX="12" lookY="-13" lookZ="-58" upX="0" upY="1" upZ="0" />
  </Cameras>
</Workspace>