<Workspace Version="0.7.2.2114" X="30" Y="49.1524122807018" zoom="0.668859649122807" Description="Returns the location of an element as an XYZ (or if it's line-based the start and end point of the line), along with some booleans to help filtering the results. Use this for some element types (e.g. walls or lines) that do not work with the built-in Get Family Instance Location node. " Category="Clockwork.Revit.Elements.Element.Query" Name="Element.Location" ID="0b59c4d8-afe4-4063-bf7e-2195fa33e8a9">
  <Elements>
    <Dynamo.Nodes.Function type="Dynamo.Nodes.Function" guid="0172cd21-9f9a-4382-82cb-a6341dcc77da" nickname="Turn Into List" x="199" y="136" isVisible="true" isUpstreamVisible="true" lacing="Disabled">
      <ID value="cd09ad33-8c34-4850-ac26-24448d92c38f" />
      <Name value="Turn Into List" />
      <Description value="Turns an element (or a nested list) into a flat list" />
      <Inputs>
        <Input value="item" />
      </Inputs>
      <Outputs>
        <Output value="" />
      </Outputs>
    </Dynamo.Nodes.Function>
    <Dynamo.Nodes.Symbol type="Dynamo.Nodes.Symbol" guid="467e3f8f-3faf-49fc-94c3-76b1b0c59c5e" nickname="Input" x="0" y="136" isVisible="true" isUpstreamVisible="true" lacing="Disabled">
      <Symbol value="Element(s)" />
    </Dynamo.Nodes.Symbol>
    <Dynamo.Nodes.Output type="Dynamo.Nodes.Output" guid="3ebf8af8-90b7-44f8-afdf-742ff53b9f65" nickname="Output" x="846" y="0" isVisible="true" isUpstreamVisible="true" lacing="Disabled">
      <Symbol value="Points" />
    </Dynamo.Nodes.Output>
    <Dynamo.Nodes.Output type="Dynamo.Nodes.Output" guid="fe6d5941-e752-40bb-b243-e86bdd061ab9" nickname="Output" x="846" y="83" isVisible="true" isUpstreamVisible="true" lacing="Disabled">
      <Symbol value="Curve Endpoints" />
    </Dynamo.Nodes.Output>
    <Dynamo.Nodes.Output type="Dynamo.Nodes.Output" guid="fef50bd5-ee46-46bb-bc91-c1d356b52c80" nickname="Output" x="846" y="166" isVisible="true" isUpstreamVisible="true" lacing="Disabled">
      <Symbol value="Curves" />
    </Dynamo.Nodes.Output>
    <Dynamo.Nodes.Output type="Dynamo.Nodes.Output" guid="9c5fe234-6333-42d1-8497-fa4ae9ff0a2d" nickname="Output" x="846" y="250" isVisible="true" isUpstreamVisible="true" lacing="Disabled">
      <Symbol value="Is Point" />
    </Dynamo.Nodes.Output>
    <Dynamo.Nodes.Output type="Dynamo.Nodes.Output" guid="21d34519-3cea-4d3f-b917-cbe99953d0f1" nickname="Output" x="846" y="333" isVisible="true" isUpstreamVisible="true" lacing="Disabled">
      <Symbol value="Is Curve" />
    </Dynamo.Nodes.Output>
    <Dynamo.Nodes.CodeBlockNodeModel type="Dynamo.Nodes.CodeBlockNodeModel" guid="bd3f39ee-762e-4a88-a57d-373694197124" nickname="Code Block" x="628" y="136" isVisible="true" isUpstreamVisible="true" lacing="Disabled" CodeText="seq[0];&#xA;seq[1];&#xA;seq[2];&#xA;seq[3];&#xA;seq[4];&#xA;seq[5];" ShouldFocus="false" />
    <DSIronPythonNode.PythonNode type="DSIronPythonNode.PythonNode" guid="f9cf6ebe-4cb6-43a4-b682-f29bf6633963" nickname="Python Script" x="404" y="136" isVisible="true" isUpstreamVisible="true" lacing="Disabled" inputcount="1">
      <Script>import clr
clr.AddReference('RevitAPI')
from Autodesk.Revit.DB import *

clr.AddReference("RevitNodes")
import Revit
clr.ImportExtensions(Revit.GeometryConversion)

items = UnwrapElement(IN[0])
pointlist = list()
curvepointlist = list()
ispoint = list()
iscurve = list()
curves = list()
haslocation = list()

for item in items:
	try:
		loc = item.Location
		if loc.ToString() == 'Autodesk.Revit.DB.LocationCurve':
			# line-based elements (e.g. walls)
			curvepoints = (loc.Curve.GetEndPoint(0).ToPoint(),loc.Curve.GetEndPoint(1).ToPoint())
			curvepointlist.append(curvepoints)
			curves.append(loc.Curve.ToProtoType())
			ispoint.append(False)
			iscurve.append(True)
			haslocation.append(True)
		else:
			# other elements
			pointlist.append(loc.Point.ToPoint())
			ispoint.append(True)
			iscurve.append(False)
			haslocation.append(True)
	except:
		try:
			# curves
			curvepoints = (item.GetEndPoint(0).ToPoint(),item.GetEndPoint(1).ToPoint())
			curvepointlist.append(curvepoints)
			curves.append(item.ToProtoType())
			ispoint.append(False)
			iscurve.append(True)
			haslocation.append(True)
		except:
			ispoint.append(False)
			iscurve.append(False)
			haslocation.append(False)
OUT = (pointlist,curvepointlist,curves,ispoint,iscurve,haslocation)</Script>
    </DSIronPythonNode.PythonNode>
    <Dynamo.Nodes.Output type="Dynamo.Nodes.Output" guid="f049edbf-dc90-4d9d-8d55-aec33858083d" nickname="Output" x="846" y="416" isVisible="true" isUpstreamVisible="true" lacing="Disabled">
      <Symbol value="Has Location" />
    </Dynamo.Nodes.Output>
  </Elements>
  <Connectors>
    <Dynamo.Models.ConnectorModel start="0172cd21-9f9a-4382-82cb-a6341dcc77da" start_index="0" end="f9cf6ebe-4cb6-43a4-b682-f29bf6633963" end_index="0" portType="0" />
    <Dynamo.Models.ConnectorModel start="467e3f8f-3faf-49fc-94c3-76b1b0c59c5e" start_index="0" end="0172cd21-9f9a-4382-82cb-a6341dcc77da" end_index="0" portType="0" />
    <Dynamo.Models.ConnectorModel start="bd3f39ee-762e-4a88-a57d-373694197124" start_index="0" end="3ebf8af8-90b7-44f8-afdf-742ff53b9f65" end_index="0" portType="0" />
    <Dynamo.Models.ConnectorModel start="bd3f39ee-762e-4a88-a57d-373694197124" start_index="1" end="fe6d5941-e752-40bb-b243-e86bdd061ab9" end_index="0" portType="0" />
    <Dynamo.Models.ConnectorModel start="bd3f39ee-762e-4a88-a57d-373694197124" start_index="2" end="fef50bd5-ee46-46bb-bc91-c1d356b52c80" end_index="0" portType="0" />
    <Dynamo.Models.ConnectorModel start="bd3f39ee-762e-4a88-a57d-373694197124" start_index="3" end="9c5fe234-6333-42d1-8497-fa4ae9ff0a2d" end_index="0" portType="0" />
    <Dynamo.Models.ConnectorModel start="bd3f39ee-762e-4a88-a57d-373694197124" start_index="4" end="21d34519-3cea-4d3f-b917-cbe99953d0f1" end_index="0" portType="0" />
    <Dynamo.Models.ConnectorModel start="bd3f39ee-762e-4a88-a57d-373694197124" start_index="5" end="f049edbf-dc90-4d9d-8d55-aec33858083d" end_index="0" portType="0" />
    <Dynamo.Models.ConnectorModel start="f9cf6ebe-4cb6-43a4-b682-f29bf6633963" start_index="0" end="bd3f39ee-762e-4a88-a57d-373694197124" end_index="0" portType="0" />
  </Connectors>
  <Notes />
</Workspace>