<Workspace Version="0.7.2.2921" X="-31.0193391688133" Y="260.898996039685" zoom="1.16438980805626" Description="Returns the underlying Revit face of a given face" Category="Clockwork.Revit.Selection" Name="RevitFace.FromDynamoSurface" ID="a7de9fe1-e4e2-4dcf-929c-570fcf9947bf">
  <Elements>
    <DSIronPythonNode.PythonNode type="DSIronPythonNode.PythonNode" guid="9f09ad84-3ad1-445d-95e3-93d4287a50c8" nickname="Python Script" x="426" y="54" isVisible="true" isUpstreamVisible="true" lacing="Disabled" inputcount="1">
      <Script>import clr
clr.AddReference('RevitAPI')
from Autodesk.Revit.DB import *

clr.AddReference("RevitServices")
import RevitServices
from RevitServices.Persistence import DocumentManager

doc = DocumentManager.Instance.CurrentDBDocument
faces = UnwrapElement(IN[0])
elementlist = list()
for face in faces:
	try:
		ref = face.Tags.LookupTag("RevitFaceReference")
		face = doc.GetElement(ref).GetGeometryObjectFromReference(ref)
		elementlist.append(face)
	except:
		elementlist.append(list())
OUT = elementlist</Script>
    </DSIronPythonNode.PythonNode>
    <Dynamo.Nodes.Function type="Dynamo.Nodes.Function" guid="292286dd-3261-44f0-baa2-b628244bf078" nickname="ReturnListOrSingleValue" x="590" y="0" isVisible="true" isUpstreamVisible="true" lacing="Disabled">
      <ID value="44ac4888-4aa4-49a9-9344-23b729c11df9" />
      <Name value="ReturnListOrSingleValue" />
      <Description value="If the item in input #1 is not a list, only the first item of the list in input #2 will be returned." />
      <Inputs>
        <Input value="item #1 (unknown)" />
        <Input value="item #2 (list)" />
      </Inputs>
      <Outputs>
        <Output value="" />
      </Outputs>
    </Dynamo.Nodes.Function>
    <Dynamo.Nodes.Function type="Dynamo.Nodes.Function" guid="aed91cb7-181e-4d17-943a-6eef4d3feda0" nickname="Turn Into List" x="261.435275688884" y="51.5291353332603" isVisible="true" isUpstreamVisible="true" lacing="Disabled">
      <ID value="cd09ad33-8c34-4850-ac26-24448d92c38f" />
      <Name value="Turn Into List" />
      <Description value="Turns an element (or a nested list) into a flat list" />
      <Inputs>
        <Input value="item" />
      </Inputs>
      <Outputs>
        <Output value="" />
      </Outputs>
    </Dynamo.Nodes.Function>
    <Dynamo.Nodes.Symbol type="Dynamo.Nodes.Symbol" guid="cdbb4b23-c6c2-4433-a99d-0a1823143b9a" nickname="Input" x="77.1059837111379" y="-1" isVisible="true" isUpstreamVisible="true" lacing="Disabled">
      <Symbol value="Dynamo surface(s)" />
    </Dynamo.Nodes.Symbol>
    <Dynamo.Nodes.Output type="Dynamo.Nodes.Output" guid="54cd4ae3-ac87-4def-9e98-d631a43c0372" nickname="Output" x="807" y="0" isVisible="true" isUpstreamVisible="true" lacing="Disabled">
      <Symbol value="Revit face(s)" />
    </Dynamo.Nodes.Output>
  </Elements>
  <Connectors>
    <Dynamo.Models.ConnectorModel start="9f09ad84-3ad1-445d-95e3-93d4287a50c8" start_index="0" end="292286dd-3261-44f0-baa2-b628244bf078" end_index="1" portType="0" />
    <Dynamo.Models.ConnectorModel start="292286dd-3261-44f0-baa2-b628244bf078" start_index="0" end="54cd4ae3-ac87-4def-9e98-d631a43c0372" end_index="0" portType="0" />
    <Dynamo.Models.ConnectorModel start="aed91cb7-181e-4d17-943a-6eef4d3feda0" start_index="0" end="9f09ad84-3ad1-445d-95e3-93d4287a50c8" end_index="0" portType="0" />
    <Dynamo.Models.ConnectorModel start="cdbb4b23-c6c2-4433-a99d-0a1823143b9a" start_index="0" end="aed91cb7-181e-4d17-943a-6eef4d3feda0" end_index="0" portType="0" />
    <Dynamo.Models.ConnectorModel start="cdbb4b23-c6c2-4433-a99d-0a1823143b9a" start_index="0" end="292286dd-3261-44f0-baa2-b628244bf078" end_index="0" portType="0" />
  </Connectors>
  <Notes />
</Workspace>