<Workspace Version="0.8.2.2392" X="-732.729968004184" Y="-128.323545275078" zoom="0.989021718375062" Name="Home" Description="" RunType="Manual" RunPeriod="1000" HasRunWithoutCrash="True">
  <NamespaceResolutionMap />
  <Elements>
    <DSIronPythonNode.PythonNode guid="507a6ec9-df39-4668-89b5-0a94460155f2" type="DSIronPythonNode.PythonNode" nickname="Python Script" x="441.278063010011" y="467.192359744315" isVisible="true" isUpstreamVisible="true" lacing="Disabled" isSelectedInput="False" inputcount="1">
      <Script>import clr
# Import RevitAPI
clr.AddReference("RevitAPI")
from Autodesk.Revit.DB import *
clr.AddReference("RevitAPIUI")
from Autodesk.Revit.UI import TaskDialog
# Import DocumentManager and TransactionManager
clr.AddReference("RevitServices")
from RevitServices.Persistence import DocumentManager
from RevitServices.Transactions import TransactionManager
# Import ToProtoType, ToRevitType geometry conversion extension methods
clr.AddReference("RevitNodes")
import Revit
clr.ImportExtensions(Revit.Elements)
clr.ImportExtensions(Revit.GeometryConversion)
from System.Collections.Generic import *
import System

doc = DocumentManager.Instance.CurrentDBDocument
uiapp = DocumentManager.Instance.CurrentUIApplication
app = uiapp.Application


collector = FilteredElementCollector( doc ).WhereElementIsNotElementType()

instance = []

for c in collector:
	if (None != c.Category and c.Category.HasMaterialQuantities):
		instance.append(c)

"""
# Element Type Id of elements
id = [ e.GetTypeId() for e in cat]

#eid = []

# Unique Type Ids
uniqueTypesIds = list(set(id))

type = []

for i in uniqueTypesIds:
	try:
		eleType = doc.GetElement( i )
		if eleType != None:
			type.append(eleType)
#			eid.append(eleType.Name)
	except:
		continue
"""
OUT = instance
#OUT = model_cat, [c.Name for c in model_cat], elements
#OUT  = type, model_cat, builtInCats, elements, eid, uniqueTypesIds
</Script>
    </DSIronPythonNode.PythonNode>
    <Dynamo.Nodes.CodeBlockNodeModel guid="56b8dc7f-8b5e-452b-b390-5b92d59064f4" type="Dynamo.Nodes.CodeBlockNodeModel" nickname="Code Block" x="828.065722509278" y="628.007417288551" isVisible="true" isUpstreamVisible="true" lacing="Disabled" isSelectedInput="True" CodeText="&quot;1F4&quot;;" ShouldFocus="false" />
    <DSIronPythonNode.PythonNode guid="2cdd82ca-0044-447d-84d2-edb0b0a5b488" type="DSIronPythonNode.PythonNode" nickname="Python Script" x="1117.99287176165" y="602.23452692491" isVisible="true" isUpstreamVisible="true" lacing="Disabled" isSelectedInput="False" inputcount="4">
      <Script>import clr
# Import RevitAPI
clr.AddReference("RevitAPI")
from Autodesk.Revit.DB import *
clr.AddReference("RevitAPIUI")
from Autodesk.Revit.UI import TaskDialog
# Import DocumentManager and TransactionManager
clr.AddReference("RevitServices")
from RevitServices.Persistence import DocumentManager
from RevitServices.Transactions import TransactionManager
# Import ToProtoType, ToRevitType geometry conversion extension methods
clr.AddReference("RevitNodes")
import Revit
clr.ImportExtensions(Revit.Elements)
clr.ImportExtensions(Revit.GeometryConversion)
from System.Collections.Generic import *
import System

doc = DocumentManager.Instance.CurrentDBDocument
uiapp = DocumentManager.Instance.CurrentUIApplication
app = uiapp.Application



types = UnwrapElement(IN[0])

locCode = IN[1]
disCode = IN[2]

model_cat = []
error = []

count = 0

if IN[3] == True:
	TransactionManager.Instance.EnsureInTransaction(doc)	
	for t in types:
		try:
			#locationCode = t.get_Parameter("Location Code")
			locationCode = t.get_Parameter("Comments")
			locationCode.Set(locCode)
		except:
			error.append(t)
		try:
			discipline = t.get_Parameter("Discipline")
			if disCode == "":
				continue
			else:
				discipline.Set(disCode)
				count +=1
		except:
			error.append(t)
	
	TransactionManager.Instance.TransactionTaskDone()
	OUT  = str(count)+"/"+str(len(types))+" modified", error
else:
	OUT = "Set true to run"

#OUT = model_cat, [c.Name for c in model_cat], elements
</Script>
    </DSIronPythonNode.PythonNode>
    <Dynamo.Nodes.CodeBlockNodeModel guid="88d2678e-fe4c-4fd4-8104-25eca59c1433" type="Dynamo.Nodes.CodeBlockNodeModel" nickname="Code Block" x="835" y="740" isVisible="true" isUpstreamVisible="true" lacing="Disabled" isSelectedInput="True" CodeText="&quot;&quot;;" ShouldFocus="false" />
    <Dynamo.Nodes.DSFunction guid="4e366bfb-6fce-43df-b5c5-ab003252f616" type="Dynamo.Nodes.DSFunction" nickname="Element.Name" x="1626.80331451122" y="618.650176374789" isVisible="true" isUpstreamVisible="true" lacing="Shortest" isSelectedInput="False" assembly="RevitNodes.dll" function="Revit.Elements.Element.Name" />
    <Dynamo.Nodes.CodeBlockNodeModel guid="688a983e-b1df-4cc5-a49d-35a487c6146e" type="Dynamo.Nodes.CodeBlockNodeModel" nickname="Code Block" x="1408.13720160743" y="625.723339951943" isVisible="true" isUpstreamVisible="true" lacing="Disabled" isSelectedInput="False" CodeText="a[1];" ShouldFocus="false" />
    <DSCoreNodesUI.BoolSelector guid="92e8c49d-066a-424c-b36c-6b2bd13ce840" type="DSCoreNodesUI.BoolSelector" nickname="Boolean" x="843.913181323917" y="830.491739596579" isVisible="true" isUpstreamVisible="true" lacing="Disabled" isSelectedInput="True">
      <System.Boolean>True</System.Boolean>
    </DSCoreNodesUI.BoolSelector>
    <Dynamo.Nodes.DSModelElementSelection guid="4ab3f2d1-1272-41d4-8eee-aeb03b40fe23" type="Dynamo.Nodes.DSModelElementSelection" nickname="Select Model Element" x="-310.300075943881" y="1125.93234548058" isVisible="true" isUpstreamVisible="true" lacing="Disabled" isSelectedInput="True" />
    <DSIronPythonNode.PythonNode guid="05f73d1a-1c6f-481b-a2f9-dfcae4c4e666" type="DSIronPythonNode.PythonNode" nickname="Python Script" x="-25.1163956304001" y="1126.22280425128" isVisible="true" isUpstreamVisible="true" lacing="Disabled" isSelectedInput="False" inputcount="1">
      <Script>import clr
# Import RevitAPI
clr.AddReference("RevitAPI")
from Autodesk.Revit.DB import *
clr.AddReference("RevitAPIUI")
from Autodesk.Revit.UI import TaskDialog
# Import DocumentManager and TransactionManager
clr.AddReference("RevitServices")
from RevitServices.Persistence import DocumentManager
from RevitServices.Transactions import TransactionManager
# Import ToProtoType, ToRevitType geometry conversion extension methods
clr.AddReference("RevitNodes")
import Revit
clr.ImportExtensions(Revit.Elements)
clr.ImportExtensions(Revit.GeometryConversion)
from System.Collections.Generic import *
import System

doc = DocumentManager.Instance.CurrentDBDocument
uiapp = DocumentManager.Instance.CurrentUIApplication
app = uiapp.Application

categories = doc.Settings.Categories;

bics = System.Enum.GetValues(BuiltInCategory)

elements = [UnwrapElement(IN[0])]

# Element Type Id of elements
id = [ e.GetTypeId() for e in elements]

#eid = []

# Unique Type Ids
uniqueTypesIds = list(set(id))

type = []

for i in uniqueTypesIds:
	try:
		eleType = doc.GetElement( i )
		if eleType != None:
			type.append(eleType.Category.Name)
#			eid.append(eleType.Name)
	except:
		continue

OUT = type
#OUT = model_cat, [c.Name for c in model_cat], elements
#OUT  = type, model_cat, builtInCats, elements, eid, uniqueTypesIds
</Script>
    </DSIronPythonNode.PythonNode>
    <Dynamo.Nodes.DSModelElementSelection guid="bf349c9a-66a4-4506-a593-841a18a5be61" type="Dynamo.Nodes.DSModelElementSelection" nickname="Select Model Element" x="393.695673529019" y="1003.30590925824" isVisible="true" isUpstreamVisible="true" lacing="Disabled" isSelectedInput="True">
      <instance id="eaa3e4aa-af56-4649-9c85-0669038dca95-00975db5" />
    </Dynamo.Nodes.DSModelElementSelection>
    <DSIronPythonNode.PythonNode guid="e178d95e-3dd4-43e0-b6e7-1edfd394e710" type="DSIronPythonNode.PythonNode" nickname="Python Script" x="699.802106442505" y="998.187072587448" isVisible="true" isUpstreamVisible="true" lacing="Disabled" isSelectedInput="False" inputcount="1">
      <Script>import clr
# Import RevitAPI
clr.AddReference("RevitAPI")
from Autodesk.Revit.DB import *
clr.AddReference("RevitAPIUI")
from Autodesk.Revit.UI import TaskDialog
# Import DocumentManager and TransactionManager
clr.AddReference("RevitServices")
from RevitServices.Persistence import DocumentManager
from RevitServices.Transactions import TransactionManager
# Import ToProtoType, ToRevitType geometry conversion extension methods
clr.AddReference("RevitNodes")
import Revit
clr.ImportExtensions(Revit.Elements)
clr.ImportExtensions(Revit.GeometryConversion)
from System.Collections.Generic import *
import System

doc = DocumentManager.Instance.CurrentDBDocument
uiapp = DocumentManager.Instance.CurrentUIApplication
app = uiapp.Application

a = UnwrapElement(IN[0])

#Assign your output to the OUT variable.
OUT = a.Pinned</Script>
    </DSIronPythonNode.PythonNode>
    <Dynamo.Nodes.DSFunction guid="1e2f86d8-0d18-4539-a66d-3d61145d783d" type="Dynamo.Nodes.DSFunction" nickname="Element.GetParameterValueByName" x="2302.25814184734" y="565.72674053515" isVisible="true" isUpstreamVisible="true" lacing="Shortest" isSelectedInput="False" assembly="RevitNodes.dll" function="Revit.Elements.Element.GetParameterValueByName@string" />
    <Dynamo.Nodes.CodeBlockNodeModel guid="9f172ac3-8a89-4570-994e-bccfc59fd9d4" type="Dynamo.Nodes.CodeBlockNodeModel" nickname="Code Block" x="2064.01892051143" y="534.161151165951" isVisible="true" isUpstreamVisible="true" lacing="Disabled" isSelectedInput="True" CodeText="&quot;Location Code&quot;;" ShouldFocus="false" />
    <Dynamo.Nodes.DSFunction guid="83477574-41de-4883-b156-b53520102ff9" type="Dynamo.Nodes.DSFunction" nickname="Element.Parameters" x="1801.32721576485" y="272.478416453085" isVisible="true" isUpstreamVisible="true" lacing="Shortest" isSelectedInput="False" assembly="RevitNodes.dll" function="Revit.Elements.Element.Parameters" />
    <Dynamo.Nodes.DSFunction guid="83bbf8fa-2201-4c94-afa0-f758686644b9" type="Dynamo.Nodes.DSFunction" nickname="Parameter.Name" x="2243.23497390727" y="277.884784554845" isVisible="true" isUpstreamVisible="true" lacing="Shortest" isSelectedInput="False" assembly="RevitNodes.dll" function="Revit.Elements.Parameter.Name" />
    <Dynamo.Nodes.DSFunction guid="b0e0c1a9-e426-47ca-bda3-e0da374a18ee" type="Dynamo.Nodes.DSFunction" nickname="List.AllIndicesOf" x="2644.54318105332" y="317.780922107376" isVisible="true" isUpstreamVisible="true" lacing="Longest" isSelectedInput="False" assembly="DSCoreNodes.dll" function="DSCore.List.AllIndicesOf@var[]..[],var" />
  </Elements>
  <Connectors>
    <Dynamo.Models.ConnectorModel start="507a6ec9-df39-4668-89b5-0a94460155f2" start_index="0" end="2cdd82ca-0044-447d-84d2-edb0b0a5b488" end_index="0" portType="0" />
    <Dynamo.Models.ConnectorModel start="507a6ec9-df39-4668-89b5-0a94460155f2" start_index="0" end="83477574-41de-4883-b156-b53520102ff9" end_index="0" portType="0" />
    <Dynamo.Models.ConnectorModel start="56b8dc7f-8b5e-452b-b390-5b92d59064f4" start_index="0" end="2cdd82ca-0044-447d-84d2-edb0b0a5b488" end_index="1" portType="0" />
    <Dynamo.Models.ConnectorModel start="2cdd82ca-0044-447d-84d2-edb0b0a5b488" start_index="0" end="688a983e-b1df-4cc5-a49d-35a487c6146e" end_index="0" portType="0" />
    <Dynamo.Models.ConnectorModel start="88d2678e-fe4c-4fd4-8104-25eca59c1433" start_index="0" end="2cdd82ca-0044-447d-84d2-edb0b0a5b488" end_index="2" portType="0" />
    <Dynamo.Models.ConnectorModel start="688a983e-b1df-4cc5-a49d-35a487c6146e" start_index="0" end="4e366bfb-6fce-43df-b5c5-ab003252f616" end_index="0" portType="0" />
    <Dynamo.Models.ConnectorModel start="92e8c49d-066a-424c-b36c-6b2bd13ce840" start_index="0" end="2cdd82ca-0044-447d-84d2-edb0b0a5b488" end_index="3" portType="0" />
    <Dynamo.Models.ConnectorModel start="4ab3f2d1-1272-41d4-8eee-aeb03b40fe23" start_index="0" end="05f73d1a-1c6f-481b-a2f9-dfcae4c4e666" end_index="0" portType="0" />
    <Dynamo.Models.ConnectorModel start="bf349c9a-66a4-4506-a593-841a18a5be61" start_index="0" end="e178d95e-3dd4-43e0-b6e7-1edfd394e710" end_index="0" portType="0" />
    <Dynamo.Models.ConnectorModel start="9f172ac3-8a89-4570-994e-bccfc59fd9d4" start_index="0" end="1e2f86d8-0d18-4539-a66d-3d61145d783d" end_index="1" portType="0" />
    <Dynamo.Models.ConnectorModel start="9f172ac3-8a89-4570-994e-bccfc59fd9d4" start_index="0" end="b0e0c1a9-e426-47ca-bda3-e0da374a18ee" end_index="1" portType="0" />
    <Dynamo.Models.ConnectorModel start="83477574-41de-4883-b156-b53520102ff9" start_index="0" end="83bbf8fa-2201-4c94-afa0-f758686644b9" end_index="0" portType="0" />
    <Dynamo.Models.ConnectorModel start="83bbf8fa-2201-4c94-afa0-f758686644b9" start_index="0" end="b0e0c1a9-e426-47ca-bda3-e0da374a18ee" end_index="0" portType="0" />
  </Connectors>
  <Notes />
  <Annotations>
    <Dynamo.Models.AnnotationModel guid="cbd2988b-1278-4aee-8920-41ad6591946c" annotationText="Element Types not modified" left="1398.13720160743" top="522.650176374789" width="386.66611290379" height="196.073163577154" fontSize="36" InitialTop="618.650176374789" InitialHeight="130.073163577154" TextblockHeight="86" backgrouund="#FFC1D676">
      <Models ModelGuid="4e366bfb-6fce-43df-b5c5-ab003252f616" />
      <Models ModelGuid="688a983e-b1df-4cc5-a49d-35a487c6146e" />
    </Dynamo.Models.AnnotationModel>
    <Dynamo.Models.AnnotationModel guid="e737d7e6-5ea5-47f9-b69c-8538a8646b62" annotationText="Category Checker" left="-320.300075943881" top="1072.93234548058" width="429.183680313481" height="146.2904587707" fontSize="36" InitialTop="1125.93234548058" InitialHeight="123.290458770699" TextblockHeight="43" backgrouund="#FFC1D676">
      <Models ModelGuid="4ab3f2d1-1272-41d4-8eee-aeb03b40fe23" />
      <Models ModelGuid="05f73d1a-1c6f-481b-a2f9-dfcae4c4e666" />
    </Dynamo.Models.AnnotationModel>
  </Annotations>
  <Presets />
  <Cameras>
    <Camera Name="background_preview" eyeX="10" eyeY="15" eyeZ="10" lookX="-10" lookY="-10" lookZ="-10" />
  </Cameras>
</Workspace>