<Workspace Version="1.3.1.1736" X="-153.143720212877" Y="-1023.40788424426" zoom="1.09073781941956" ScaleFactor="1" Name="Home" Description="" RunType="Manual" RunPeriod="1000" HasRunWithoutCrash="True">
  <NamespaceResolutionMap>
    <ClassMap partialName="Element.Curve" resolvedName="Revit.Elements.Element" assemblyName="RevitNodes.dll" />
  </NamespaceResolutionMap>
  <Elements>
    <PythonNodeModels.PythonNode guid="d8989289-55b8-46ed-9111-d5faeb6e5fc4" type="PythonNodeModels.PythonNode" nickname="Python Script" x="-205.080588489281" y="276.656351085829" isVisible="true" isUpstreamVisible="true" lacing="Disabled" isSelectedInput="False" IsFrozen="false" isPinned="false" inputcount="1">
      <PortInfo index="0" default="False" />
      <Script>import clr
clr.AddReference('RevitAPI')
from Autodesk.Revit.DB import *

clr.AddReference("RevitNodes")
import Revit
clr.ImportExtensions(Revit.Elements)
clr.ImportExtensions(Revit.GeometryConversion)

clr.AddReference("RevitServices")
import RevitServices
from RevitServices.Persistence import DocumentManager
from RevitServices.Transactions import TransactionManager

doc = DocumentManager.Instance.CurrentDBDocument

if isinstance(IN[0], list):
	lines = []
	for i in IN[0]:
		lines.append(UnwrapElement(i))
else:
	lines = [UnwrapElement(IN[0])]


crvs = []

for line in lines:
	crvs.append(line.GeometryCurve)
	

#grids = UnwrapElement(IN[1])

"""gridRef = ReferenceArray()
opt = Options()
opt.ComputeReferences = True
opt.IncludeNonVisibleObjects = True
opt.View = doc.ActiveView
for grid in grids:
	for obj in grid.get_Geometry(opt):
		if isinstance(obj, Line):
			gline = obj
			gridRef.Append(gline.Reference)"""

TransactionManager.Instance.EnsureInTransaction(doc)


for crv in crvs:
	ref = ReferenceArray()
	ref.Append(crv.GetEndPointReference(0))
	ref.Append(crv.GetEndPointReference(1))
	dim = doc.Create.NewDimension(doc.ActiveView, crv, ref)

TransactionManager.Instance.TransactionTaskDone()

OUT = dim</Script>
    </PythonNodeModels.PythonNode>
    <Dynamo.Nodes.DSModelElementsSelection guid="d0ed651a-9486-4310-8ea3-07e3772b2331" type="Dynamo.Nodes.DSModelElementsSelection" nickname="Select Model Elements" x="-630.326060099057" y="-215.422474969739" isVisible="true" isUpstreamVisible="true" lacing="Disabled" isSelectedInput="True" IsFrozen="false" isPinned="false">
      <instance id="aad6741b-fd71-46f7-82d2-74ce6651fcc3-001f69f9" />
      <instance id="aad6741b-fd71-46f7-82d2-74ce6651fcc3-001f69fa" />
    </Dynamo.Nodes.DSModelElementsSelection>
    <Dynamo.Graph.Nodes.ZeroTouch.DSFunction guid="5612a7b4-db2c-4f35-89be-65e9aa60b653" type="Dynamo.Graph.Nodes.ZeroTouch.DSFunction" nickname="Grid.Curve" x="-346.27903333107" y="-33.1012327351737" isVisible="true" isUpstreamVisible="true" lacing="Shortest" isSelectedInput="False" IsFrozen="false" isPinned="false" assembly="RevitNodes.dll" function="Revit.Elements.Grid.Curve">
      <PortInfo index="0" default="False" />
    </Dynamo.Graph.Nodes.ZeroTouch.DSFunction>
    <Dynamo.Graph.Nodes.ZeroTouch.DSFunction guid="fc173657-8845-4f61-9c6c-fb8ad1d93ed4" type="Dynamo.Graph.Nodes.ZeroTouch.DSFunction" nickname="Curve.StartPoint" x="-91.7459457888425" y="-132.174941176572" isVisible="true" isUpstreamVisible="true" lacing="Shortest" isSelectedInput="False" IsFrozen="false" isPinned="false" assembly="ProtoGeometry.dll" function="Autodesk.DesignScript.Geometry.Curve.StartPoint">
      <PortInfo index="0" default="False" />
    </Dynamo.Graph.Nodes.ZeroTouch.DSFunction>
    <Dynamo.Graph.Nodes.ZeroTouch.DSFunction guid="61f2c02f-0d44-43ad-abf6-04dc03a98644" type="Dynamo.Graph.Nodes.ZeroTouch.DSFunction" nickname="List.FirstItem" x="116.43746880744" y="-130.935443114835" isVisible="true" isUpstreamVisible="true" lacing="Shortest" isSelectedInput="False" IsFrozen="false" isPinned="false" assembly="DSCoreNodes.dll" function="DSCore.List.FirstItem@var[]..[]">
      <PortInfo index="0" default="False" />
    </Dynamo.Graph.Nodes.ZeroTouch.DSFunction>
    <Dynamo.Graph.Nodes.ZeroTouch.DSFunction guid="7154d63d-2cf2-48b8-a6a7-c3ecb788dee5" type="Dynamo.Graph.Nodes.ZeroTouch.DSFunction" nickname="List.LastItem" x="133.013078664964" y="14.6275580988527" isVisible="true" isUpstreamVisible="true" lacing="Shortest" isSelectedInput="False" IsFrozen="false" isPinned="false" assembly="DSCoreNodes.dll" function="DSCore.List.LastItem@var[]..[]">
      <PortInfo index="0" default="False" />
    </Dynamo.Graph.Nodes.ZeroTouch.DSFunction>
    <Dynamo.Graph.Nodes.ZeroTouch.DSFunction guid="c1926bcd-c360-4b40-a461-00314e08a20b" type="Dynamo.Graph.Nodes.ZeroTouch.DSFunction" nickname="Line.ByStartPointEndPoint" x="308.613314055139" y="-39.396394498446" isVisible="true" isUpstreamVisible="true" lacing="Shortest" isSelectedInput="False" IsFrozen="false" isPinned="false" assembly="ProtoGeometry.dll" function="Autodesk.DesignScript.Geometry.Line.ByStartPointEndPoint@Autodesk.DesignScript.Geometry.Point,Autodesk.DesignScript.Geometry.Point">
      <PortInfo index="0" default="False" />
      <PortInfo index="1" default="False" />
    </Dynamo.Graph.Nodes.ZeroTouch.DSFunction>
    <Dynamo.Graph.Nodes.CodeBlockNodeModel guid="76571f32-747c-4359-84e1-0aeb73eda99d" type="Dynamo.Graph.Nodes.CodeBlockNodeModel" nickname="Code Block" x="561.204667511457" y="-2.88111638359412" isVisible="true" isUpstreamVisible="true" lacing="Disabled" isSelectedInput="False" IsFrozen="false" isPinned="false" CodeText="500;" ShouldFocus="false" />
    <Dynamo.Graph.Nodes.ZeroTouch.DSFunction guid="e02957a7-9730-4316-baf2-3798f30bb206" type="Dynamo.Graph.Nodes.ZeroTouch.DSFunction" nickname="Curve.Offset" x="673.199311010652" y="-165.383285687689" isVisible="true" isUpstreamVisible="true" lacing="Shortest" isSelectedInput="False" IsFrozen="false" isPinned="false" assembly="ProtoGeometry.dll" function="Autodesk.DesignScript.Geometry.Curve.Offset@double">
      <PortInfo index="0" default="False" />
      <PortInfo index="1" default="True" />
    </Dynamo.Graph.Nodes.ZeroTouch.DSFunction>
    <PythonNodeModels.PythonNode guid="5e4f1bcd-9347-4870-8a2a-d0085edb0819" type="PythonNodeModels.PythonNode" nickname="Python Script" x="901.242186281931" y="-239.79453198906" isVisible="true" isUpstreamVisible="true" lacing="Disabled" isSelectedInput="False" IsFrozen="false" isPinned="false" inputcount="2">
      <PortInfo index="0" default="False" />
      <PortInfo index="1" default="False" />
      <Script>import clr
clr.AddReference('RevitAPI')
from Autodesk.Revit.DB import *

clr.AddReference("RevitNodes")
import Revit
clr.ImportExtensions(Revit.Elements)
clr.ImportExtensions(Revit.GeometryConversion)

clr.AddReference("RevitServices")
import RevitServices
from RevitServices.Persistence import DocumentManager
from RevitServices.Transactions import TransactionManager

doc = DocumentManager.Instance.CurrentDBDocument

line = IN[0].ToRevitType()
grids = UnwrapElement(IN[1])

gridRef = ReferenceArray()
opt = Options()
opt.ComputeReferences = True
opt.IncludeNonVisibleObjects = True
opt.View = doc.ActiveView

for grid in grids:
	for obj in grid.get_Geometry(opt):
		if isinstance(obj, Line):
			gline = obj
			gridRef.Append(gline.Reference)

TransactionManager.Instance.EnsureInTransaction(doc)

dim = doc.Create.NewDimension(doc.ActiveView, line, gridRef)

TransactionManager.Instance.TransactionTaskDone()

OUT = dim</Script>
    </PythonNodeModels.PythonNode>
    <Dynamo.Nodes.DSModelElementsSelection guid="005eb9cd-9334-48e7-acf9-adcb6d6188d5" type="Dynamo.Nodes.DSModelElementsSelection" nickname="Select Model Elements" x="-631.99831129481" y="278.057929580218" isVisible="true" isUpstreamVisible="true" lacing="Disabled" isSelectedInput="True" IsFrozen="false" isPinned="false">
      <instance id="aad6741b-fd71-46f7-82d2-74ce6651fcc3-001f6a27" />
      <instance id="aad6741b-fd71-46f7-82d2-74ce6651fcc3-001f6a28" />
      <instance id="aad6741b-fd71-46f7-82d2-74ce6651fcc3-001f6a29" />
    </Dynamo.Nodes.DSModelElementsSelection>
    <Dynamo.Nodes.DSModelElementsSelection guid="f6d93744-f65b-4c37-ba2e-1b785dbd9a65" type="Dynamo.Nodes.DSModelElementsSelection" nickname="Select Model Elements" x="-611.338294084841" y="791.03570416297" isVisible="true" isUpstreamVisible="true" lacing="Disabled" isSelectedInput="True" IsFrozen="false" isPinned="true">
      <instance id="aad6741b-fd71-46f7-82d2-74ce6651fcc3-001f6a2a" />
      <instance id="aad6741b-fd71-46f7-82d2-74ce6651fcc3-001f6a2b" />
      <instance id="aad6741b-fd71-46f7-82d2-74ce6651fcc3-001f6a2c" />
    </Dynamo.Nodes.DSModelElementsSelection>
    <Dynamo.Graph.Nodes.ZeroTouch.DSFunction guid="87a1d073-393b-4d57-9459-6c154eaa1b48" type="Dynamo.Graph.Nodes.ZeroTouch.DSFunction" nickname="Element.Curves" x="-206.020413663147" y="706.213017872185" isVisible="true" isUpstreamVisible="true" lacing="Shortest" isSelectedInput="False" IsFrozen="false" isPinned="true" assembly="RevitNodes.dll" function="Revit.Elements.Element.Curves">
      <PortInfo index="0" default="False" />
    </Dynamo.Graph.Nodes.ZeroTouch.DSFunction>
    <Dynamo.Graph.Nodes.CodeBlockNodeModel guid="4fd04ce6-210d-4224-8859-cd621a68973a" type="Dynamo.Graph.Nodes.CodeBlockNodeModel" nickname="Code Block" x="96.8904354807308" y="870.474505355287" isVisible="true" isUpstreamVisible="true" lacing="Disabled" isSelectedInput="False" IsFrozen="false" isPinned="false" CodeText="-1000;" ShouldFocus="false" />
    <PythonNodeModels.PythonNode guid="3fe455d8-3b7c-4afa-aaaf-b750f7adf50e" type="PythonNodeModels.PythonNode" nickname="Python Script" x="834.881817989305" y="787.151758431444" isVisible="true" isUpstreamVisible="true" lacing="Disabled" isSelectedInput="False" IsFrozen="false" isPinned="true" inputcount="2">
      <PortInfo index="0" default="False" />
      <PortInfo index="1" default="False" />
      <Script>import clr
clr.AddReference('RevitAPI')
from Autodesk.Revit.DB import *

clr.AddReference("RevitNodes")
import Revit
clr.ImportExtensions(Revit.Elements)
clr.ImportExtensions(Revit.GeometryConversion)

clr.AddReference("RevitServices")
import RevitServices
from RevitServices.Persistence import DocumentManager
from RevitServices.Transactions import TransactionManager

doc = DocumentManager.Instance.CurrentDBDocument

if isinstance(IN[0], list):
	lines = []
	for i in IN[0]:
		lines.append(UnwrapElement(i))
else:
	lines = [UnwrapElement(IN[0])]


crvs = []

for line in lines:
	crvs.append(line.GeometryCurve)


if isinstance(IN[1], list):
	linea = []
	for i in IN[1]:
		linea.append(UnwrapElement(i).ToRevitType())
else:
	linea = [UnwrapElement(IN[1]).ToRevitType()]


TransactionManager.Instance.EnsureInTransaction(doc)


for i in range (0,len(linea)):
	ref = ReferenceArray()
	ref.Append(crvs[i].GetEndPointReference(0))
	ref.Append(crvs[i].GetEndPointReference(1))
	dim = doc.Create.NewDimension(doc.ActiveView, linea[i], ref)



TransactionManager.Instance.TransactionTaskDone()

OUT = linea</Script>
    </PythonNodeModels.PythonNode>
    <Dynamo.Graph.Nodes.ZeroTouch.DSFunction guid="2c7c46d0-2bd0-4264-be5e-42e69ef8db17" type="Dynamo.Graph.Nodes.ZeroTouch.DSFunction" nickname="Flatten" x="551.219240219978" y="712.611449758957" isVisible="true" isUpstreamVisible="true" lacing="Shortest" isSelectedInput="False" IsFrozen="false" isPinned="false" assembly="BuiltIn" function="Flatten@var[]..[]">
      <PortInfo index="0" default="False" />
    </Dynamo.Graph.Nodes.ZeroTouch.DSFunction>
    <Dynamo.Graph.Nodes.ZeroTouch.DSFunction guid="e1b5215b-af2e-48a6-b6f6-5a2e7feed3c7" type="Dynamo.Graph.Nodes.ZeroTouch.DSFunction" nickname="Curve.SmartOffset" x="259.154805972465" y="701.503659502662" isVisible="true" isUpstreamVisible="true" lacing="Shortest" isSelectedInput="False" IsFrozen="false" isPinned="false" assembly="..\AppData\Roaming\Dynamo\Dynamo Revit\1.3\packages\WombatDynamo\bin\WombatDynamo.dll" function="WombatDynamo.Curve.SmartOffset@Autodesk.DesignScript.Geometry.Curve,double">
      <PortInfo index="0" default="False" />
      <PortInfo index="1" default="False" />
    </Dynamo.Graph.Nodes.ZeroTouch.DSFunction>
    <Dynamo.Nodes.DSModelElementsSelection guid="7c5a5e3e-66a5-4b32-bab7-348ae4c14782" type="Dynamo.Nodes.DSModelElementsSelection" nickname="Select Model Elements" x="-603.101082765333" y="1490.83693054936" isVisible="true" isUpstreamVisible="true" lacing="Disabled" isSelectedInput="True" IsFrozen="false" isPinned="true">
      <instance id="aad6741b-fd71-46f7-82d2-74ce6651fcc3-001f6ac4" />
    </Dynamo.Nodes.DSModelElementsSelection>
    <Dynamo.Graph.Nodes.CodeBlockNodeModel guid="baa4df87-43ac-4086-90d1-aa00dbdf159c" type="Dynamo.Graph.Nodes.CodeBlockNodeModel" nickname="Code Block" x="-307.097113590756" y="1496.42617496886" isVisible="true" isUpstreamVisible="true" lacing="Disabled" isSelectedInput="False" IsFrozen="false" isPinned="true" CodeText="{a};" ShouldFocus="false">
      <PortInfo index="0" default="False" />
    </Dynamo.Graph.Nodes.CodeBlockNodeModel>
    <Dynamo.Graph.Nodes.ZeroTouch.DSFunction guid="4de05fd6-0b07-4896-a45f-506b64b8058c" type="Dynamo.Graph.Nodes.ZeroTouch.DSFunction" nickname="Curve.SmartOffset" x="355.412067171558" y="1523.7783978029" isVisible="true" isUpstreamVisible="true" lacing="Shortest" isSelectedInput="False" IsFrozen="false" isPinned="true" assembly="..\AppData\Roaming\Dynamo\Dynamo Revit\1.3\packages\WombatDynamo\bin\WombatDynamo.dll" function="WombatDynamo.Curve.SmartOffset@Autodesk.DesignScript.Geometry.Curve,double">
      <PortInfo index="0" default="False" />
      <PortInfo index="1" default="False" />
    </Dynamo.Graph.Nodes.ZeroTouch.DSFunction>
    <Dynamo.Graph.Nodes.CodeBlockNodeModel guid="05bae7c0-211a-4577-ab50-72e0e76403f9" type="Dynamo.Graph.Nodes.CodeBlockNodeModel" nickname="Code Block" x="218.067661291614" y="1674.11583886251" isVisible="true" isUpstreamVisible="true" lacing="Disabled" isSelectedInput="False" IsFrozen="false" isPinned="false" CodeText="-1000;" ShouldFocus="false" />
    <PythonNodeModels.PythonNode guid="a29b541c-520e-41ec-ab7e-117626fe0b23" type="PythonNodeModels.PythonNode" nickname="Python Script" x="731.067660701056" y="1526.56512199948" isVisible="true" isUpstreamVisible="true" lacing="Disabled" isSelectedInput="False" IsFrozen="false" isPinned="true" inputcount="1">
      <PortInfo index="0" default="False" />
      <Script>import clr
clr.AddReference('RevitAPI')
from Autodesk.Revit.DB import *

clr.AddReference("RevitNodes")
import Revit
clr.ImportExtensions(Revit.Elements)
clr.ImportExtensions(Revit.GeometryConversion)

clr.AddReference("RevitServices")
import RevitServices
from RevitServices.Persistence import DocumentManager
from RevitServices.Transactions import TransactionManager

doc = DocumentManager.Instance.CurrentDBDocument
uiapp = DocumentManager.Instance.CurrentUIApplication
app = uiapp.Application

lines = IN[0]

edges = []

for l in lines:
	edges.append(l.ToRevitType())



OUT = edges</Script>
    </PythonNodeModels.PythonNode>
    <PythonNodeModels.PythonNode guid="d0336890-978d-4fe6-8500-66423ab45a8d" type="PythonNodeModels.PythonNode" nickname="Python Script" x="-58.4825690774646" y="1494.55981521027" isVisible="true" isUpstreamVisible="true" lacing="Disabled" isSelectedInput="False" IsFrozen="false" isPinned="true" inputcount="1">
      <PortInfo index="0" default="False" />
      <Script>import clr
clr.AddReference('RevitAPI')
from Autodesk.Revit.DB import *

clr.AddReference("RevitNodes")
import Revit
clr.ImportExtensions(Revit.Elements)
clr.ImportExtensions(Revit.GeometryConversion)

clr.AddReference("RevitServices")
import RevitServices
from RevitServices.Persistence import DocumentManager
from RevitServices.Transactions import TransactionManager

doc = DocumentManager.Instance.CurrentDBDocument
uiapp = DocumentManager.Instance.CurrentUIApplication
app = uiapp.Application

if isinstance(IN[0], list):
	lines = []
	for i in IN[0]:
		lines.append(UnwrapElement(i))
else:
	lines = [UnwrapElement(IN[0])]


	
opt = app.Create.NewGeometryOptions()
opt.ComputeReferences = 1
opt.IncludeNonVisibleObjects = 1
opt.View = doc.ActiveView


lines = UnwrapElement(IN[0])

faceArray = []
edgeArray = []
edgeCurve = []


for r in lines:
	geomElem = r.get_Geometry(opt)
	enum1 = geomElem.GetEnumerator() ; enum1.MoveNext()
	geo2 = enum1.Current
	faceArray = geo2.Faces

for face in faceArray:
	edgeArray.append(face.EdgeLoops)

for edge in edgeArray[0][0]:
	edgeCurve.append(edge.AsCurve().ToProtoType())




OUT = edgeArray[0][0],edgeCurve</Script>
    </PythonNodeModels.PythonNode>
    <PythonNodeModels.PythonNode guid="2afb7097-69ec-454e-bd03-c4b131ed39c2" type="PythonNodeModels.PythonNode" nickname="Python Script" x="996.07019457884" y="1184.5943878531" isVisible="true" isUpstreamVisible="true" lacing="Disabled" isSelectedInput="False" IsFrozen="false" isPinned="true" inputcount="2">
      <PortInfo index="0" default="False" />
      <PortInfo index="1" default="False" />
      <Script>import clr
clr.AddReference('RevitAPI')
from Autodesk.Revit.DB import *

clr.AddReference("RevitNodes")
import Revit
clr.ImportExtensions(Revit.Elements)
clr.ImportExtensions(Revit.GeometryConversion)

clr.AddReference("RevitServices")
import RevitServices
from RevitServices.Persistence import DocumentManager
from RevitServices.Transactions import TransactionManager

doc = DocumentManager.Instance.CurrentDBDocument
uiapp = DocumentManager.Instance.CurrentUIApplication
app = uiapp.Application


edgeArray = [IN[0]]

edgeCurves = [IN[1]]
	

dimensions = []

TransactionManager.Instance.EnsureInTransaction(doc)


for i in range(0,len(edgeArray)):
	for edge,crvs in zip(edgeArray[i],edgeCurves[i]):
		ref = ReferenceArray()
		ref.Append(edge.GetEndPointReference(0))
		ref.Append(edge.GetEndPointReference(1))
		dim = doc.Create.NewDimension(doc.ActiveView, crvs, ref)
		dimensions.append(dim)


TransactionManager.Instance.TransactionTaskDone()



OUT = dim</Script>
    </PythonNodeModels.PythonNode>
    <Dynamo.Graph.Nodes.CodeBlockNodeModel guid="81a2965a-28ed-45d6-95ef-b91b9afce887" type="Dynamo.Graph.Nodes.CodeBlockNodeModel" nickname="Code Block" x="160.387383333018" y="1532.75704047853" isVisible="true" isUpstreamVisible="true" lacing="Disabled" isSelectedInput="False" IsFrozen="false" isPinned="false" CodeText="a[1];" ShouldFocus="false">
      <PortInfo index="0" default="False" />
    </Dynamo.Graph.Nodes.CodeBlockNodeModel>
    <Dynamo.Graph.Nodes.CodeBlockNodeModel guid="422f7de2-7a3e-49c9-a17f-2a44cdca9e3d" type="Dynamo.Graph.Nodes.CodeBlockNodeModel" nickname="Code Block" x="529.337660672347" y="1113.93324997767" isVisible="true" isUpstreamVisible="true" lacing="Disabled" isSelectedInput="False" IsFrozen="false" isPinned="true" CodeText="a[0];" ShouldFocus="false">
      <PortInfo index="0" default="False" />
    </Dynamo.Graph.Nodes.CodeBlockNodeModel>
  </Elements>
  <Connectors>
    <Dynamo.Graph.Connectors.ConnectorModel start="d0ed651a-9486-4310-8ea3-07e3772b2331" start_index="0" end="5612a7b4-db2c-4f35-89be-65e9aa60b653" end_index="0" portType="0" />
    <Dynamo.Graph.Connectors.ConnectorModel start="d0ed651a-9486-4310-8ea3-07e3772b2331" start_index="0" end="5e4f1bcd-9347-4870-8a2a-d0085edb0819" end_index="1" portType="0" />
    <Dynamo.Graph.Connectors.ConnectorModel start="5612a7b4-db2c-4f35-89be-65e9aa60b653" start_index="0" end="fc173657-8845-4f61-9c6c-fb8ad1d93ed4" end_index="0" portType="0" />
    <Dynamo.Graph.Connectors.ConnectorModel start="fc173657-8845-4f61-9c6c-fb8ad1d93ed4" start_index="0" end="61f2c02f-0d44-43ad-abf6-04dc03a98644" end_index="0" portType="0" />
    <Dynamo.Graph.Connectors.ConnectorModel start="fc173657-8845-4f61-9c6c-fb8ad1d93ed4" start_index="0" end="7154d63d-2cf2-48b8-a6a7-c3ecb788dee5" end_index="0" portType="0" />
    <Dynamo.Graph.Connectors.ConnectorModel start="61f2c02f-0d44-43ad-abf6-04dc03a98644" start_index="0" end="c1926bcd-c360-4b40-a461-00314e08a20b" end_index="0" portType="0" />
    <Dynamo.Graph.Connectors.ConnectorModel start="7154d63d-2cf2-48b8-a6a7-c3ecb788dee5" start_index="0" end="c1926bcd-c360-4b40-a461-00314e08a20b" end_index="1" portType="0" />
    <Dynamo.Graph.Connectors.ConnectorModel start="c1926bcd-c360-4b40-a461-00314e08a20b" start_index="0" end="e02957a7-9730-4316-baf2-3798f30bb206" end_index="0" portType="0" />
    <Dynamo.Graph.Connectors.ConnectorModel start="76571f32-747c-4359-84e1-0aeb73eda99d" start_index="0" end="e02957a7-9730-4316-baf2-3798f30bb206" end_index="1" portType="0" />
    <Dynamo.Graph.Connectors.ConnectorModel start="e02957a7-9730-4316-baf2-3798f30bb206" start_index="0" end="5e4f1bcd-9347-4870-8a2a-d0085edb0819" end_index="0" portType="0" />
    <Dynamo.Graph.Connectors.ConnectorModel start="005eb9cd-9334-48e7-acf9-adcb6d6188d5" start_index="0" end="d8989289-55b8-46ed-9111-d5faeb6e5fc4" end_index="0" portType="0" />
    <Dynamo.Graph.Connectors.ConnectorModel start="f6d93744-f65b-4c37-ba2e-1b785dbd9a65" start_index="0" end="3fe455d8-3b7c-4afa-aaaf-b750f7adf50e" end_index="0" portType="0" />
    <Dynamo.Graph.Connectors.ConnectorModel start="f6d93744-f65b-4c37-ba2e-1b785dbd9a65" start_index="0" end="87a1d073-393b-4d57-9459-6c154eaa1b48" end_index="0" portType="0" />
    <Dynamo.Graph.Connectors.ConnectorModel start="87a1d073-393b-4d57-9459-6c154eaa1b48" start_index="0" end="e1b5215b-af2e-48a6-b6f6-5a2e7feed3c7" end_index="0" portType="0" />
    <Dynamo.Graph.Connectors.ConnectorModel start="4fd04ce6-210d-4224-8859-cd621a68973a" start_index="0" end="e1b5215b-af2e-48a6-b6f6-5a2e7feed3c7" end_index="1" portType="0" />
    <Dynamo.Graph.Connectors.ConnectorModel start="2c7c46d0-2bd0-4264-be5e-42e69ef8db17" start_index="0" end="3fe455d8-3b7c-4afa-aaaf-b750f7adf50e" end_index="1" portType="0" />
    <Dynamo.Graph.Connectors.ConnectorModel start="e1b5215b-af2e-48a6-b6f6-5a2e7feed3c7" start_index="0" end="2c7c46d0-2bd0-4264-be5e-42e69ef8db17" end_index="0" portType="0" />
    <Dynamo.Graph.Connectors.ConnectorModel start="7c5a5e3e-66a5-4b32-bab7-348ae4c14782" start_index="0" end="baa4df87-43ac-4086-90d1-aa00dbdf159c" end_index="0" portType="0" />
    <Dynamo.Graph.Connectors.ConnectorModel start="baa4df87-43ac-4086-90d1-aa00dbdf159c" start_index="0" end="d0336890-978d-4fe6-8500-66423ab45a8d" end_index="0" portType="0" />
    <Dynamo.Graph.Connectors.ConnectorModel start="4de05fd6-0b07-4896-a45f-506b64b8058c" start_index="0" end="a29b541c-520e-41ec-ab7e-117626fe0b23" end_index="0" portType="0" />
    <Dynamo.Graph.Connectors.ConnectorModel start="05bae7c0-211a-4577-ab50-72e0e76403f9" start_index="0" end="4de05fd6-0b07-4896-a45f-506b64b8058c" end_index="1" portType="0" />
    <Dynamo.Graph.Connectors.ConnectorModel start="a29b541c-520e-41ec-ab7e-117626fe0b23" start_index="0" end="2afb7097-69ec-454e-bd03-c4b131ed39c2" end_index="1" portType="0" />
    <Dynamo.Graph.Connectors.ConnectorModel start="d0336890-978d-4fe6-8500-66423ab45a8d" start_index="0" end="81a2965a-28ed-45d6-95ef-b91b9afce887" end_index="0" portType="0" />
    <Dynamo.Graph.Connectors.ConnectorModel start="d0336890-978d-4fe6-8500-66423ab45a8d" start_index="0" end="422f7de2-7a3e-49c9-a17f-2a44cdca9e3d" end_index="0" portType="0" />
    <Dynamo.Graph.Connectors.ConnectorModel start="81a2965a-28ed-45d6-95ef-b91b9afce887" start_index="0" end="4de05fd6-0b07-4896-a45f-506b64b8058c" end_index="0" portType="0" />
    <Dynamo.Graph.Connectors.ConnectorModel start="422f7de2-7a3e-49c9-a17f-2a44cdca9e3d" start_index="0" end="2afb7097-69ec-454e-bd03-c4b131ed39c2" end_index="0" portType="0" />
  </Connectors>
  <Notes />
  <Annotations>
    <Dynamo.Graph.Annotations.AnnotationModel guid="a94eee78-8f08-4e54-aa3e-f7dc5eb0a677" annotationText="DIM. LINES" left="-641.99831129481" top="225.057929580218" width="258" height="189" fontSize="36" InitialTop="278.057929580218" InitialHeight="124" TextblockHeight="43" backgrouund="#FFC1D676">
      <Models ModelGuid="005eb9cd-9334-48e7-acf9-adcb6d6188d5" />
    </Dynamo.Graph.Annotations.AnnotationModel>
    <Dynamo.Graph.Annotations.AnnotationModel guid="1c880c67-e287-4103-9b76-cb1ead58f844" annotationText="DIM. MULTIPLE LINES W/ OFFSET" left="-621.338294084841" top="651.03570416297" width="258" height="276" fontSize="36" InitialTop="791.03570416297" InitialHeight="124" TextblockHeight="130" backgrouund="#FFC1D676">
      <Models ModelGuid="f6d93744-f65b-4c37-ba2e-1b785dbd9a65" />
    </Dynamo.Graph.Annotations.AnnotationModel>
    <Dynamo.Graph.Annotations.AnnotationModel guid="c1f4c811-f8e2-4c67-b281-16c355115c33" annotationText="DIM. GRIDLINES" left="-640.326060099057" top="-268.422474969739" width="258" height="172" fontSize="36" InitialTop="-215.422474969739" InitialHeight="157" TextblockHeight="43" backgrouund="#FFC1D676">
      <Models ModelGuid="d0ed651a-9486-4310-8ea3-07e3772b2331" />
    </Dynamo.Graph.Annotations.AnnotationModel>
    <Dynamo.Graph.Annotations.AnnotationModel guid="01173150-9f08-44c4-b6ab-f9577d6102a4" annotationText="from Wombat" left="249.154805972465" top="655.503659502662" width="232" height="165" fontSize="30" InitialTop="701.503659502662" InitialHeight="149" TextblockHeight="36" backgrouund="#FFC1D676">
      <Models ModelGuid="e1b5215b-af2e-48a6-b6f6-5a2e7feed3c7" />
    </Dynamo.Graph.Annotations.AnnotationModel>
    <Dynamo.Graph.Annotations.AnnotationModel guid="d482beb5-3092-4d31-b4a1-a61964163021" annotationText="from Wombat" left="345.412067171558" top="1477.7783978029" width="232" height="165" fontSize="30" InitialTop="1523.7783978029" InitialHeight="149" TextblockHeight="36" backgrouund="#FFC1D676">
      <Models ModelGuid="4de05fd6-0b07-4896-a45f-506b64b8058c" />
    </Dynamo.Graph.Annotations.AnnotationModel>
    <Dynamo.Graph.Annotations.AnnotationModel guid="65657bce-4c51-415a-9b34-916b6d4517ef" annotationText="reference" left="986.07019457884" top="1138.5943878531" width="144" height="165" fontSize="30" InitialTop="1184.5943878531" InitialHeight="149" TextblockHeight="36" backgrouund="#FFC1D676">
      <Models ModelGuid="2afb7097-69ec-454e-bd03-c4b131ed39c2" />
    </Dynamo.Graph.Annotations.AnnotationModel>
    <Dynamo.Graph.Annotations.AnnotationModel guid="5c23fb72-4938-42be-a729-0d229e4ca4ba" annotationText="DIM. SLABS" left="-613.101082765333" top="1444.83693054936" width="207" height="165" fontSize="30" InitialTop="1490.83693054936" InitialHeight="149" TextblockHeight="36" backgrouund="#FFC1D676">
      <Models ModelGuid="7c5a5e3e-66a5-4b32-bab7-348ae4c14782" />
    </Dynamo.Graph.Annotations.AnnotationModel>
  </Annotations>
  <Presets />
  <Cameras>
    <Camera Name="Background Preview" eyeX="228.886947631836" eyeY="7265.10400390625" eyeZ="-2281.46704101563" lookX="2302.09594726563" lookY="-5220.3427734375" lookZ="-4120.91064453125" upX="0.283207476139069" upY="0.814115524291992" upZ="-0.506960988044739" />
  </Cameras>
</Workspace>