<Workspace Version="1.3.2.2480" X="244.700223699881" Y="-243.213174501178" zoom="0.616126359279481" ScaleFactor="1" Name="Home" Description="" RunType="Manual" RunPeriod="1000" HasRunWithoutCrash="True">
  <NamespaceResolutionMap />
  <Elements>
    <Dynamo.Nodes.DSModelElementSelection guid="8b65b90f-b51e-4567-9915-65894f0d16a4" type="Dynamo.Nodes.DSModelElementSelection" nickname="Select Model Element" x="-292.767176002621" y="794.466461681387" isVisible="true" isUpstreamVisible="true" lacing="Disabled" isSelectedInput="True" IsFrozen="false" isPinned="false">
      <instance id="8e17cbba-d02c-45c5-92d1-3d3401234a78-00221faa" />
    </Dynamo.Nodes.DSModelElementSelection>
    <Dynamo.Graph.Nodes.ZeroTouch.DSFunction guid="f69bd1a7-2601-4a01-b3c1-6695117b463a" type="Dynamo.Graph.Nodes.ZeroTouch.DSFunction" nickname="Element.Faces" x="261" y="454" isVisible="false" isUpstreamVisible="true" lacing="Shortest" isSelectedInput="False" IsFrozen="false" isPinned="true" assembly="RevitNodes.dll" function="Revit.Elements.Element.Faces">
      <PortInfo index="0" default="False" />
    </Dynamo.Graph.Nodes.ZeroTouch.DSFunction>
    <Dynamo.Graph.Nodes.ZeroTouch.DSFunction guid="d823d3ec-37bb-4c36-9738-e930523e624b" type="Dynamo.Graph.Nodes.ZeroTouch.DSFunction" nickname="Surface.Area" x="591" y="452" isVisible="true" isUpstreamVisible="true" lacing="Shortest" isSelectedInput="False" IsFrozen="false" isPinned="true" assembly="ProtoGeometry.dll" function="Autodesk.DesignScript.Geometry.Surface.Area">
      <PortInfo index="0" default="False" />
    </Dynamo.Graph.Nodes.ZeroTouch.DSFunction>
    <Dynamo.Graph.Nodes.ZeroTouch.DSFunction guid="02cfc81a-e256-48ff-b59a-4d95c07b9792" type="Dynamo.Graph.Nodes.ZeroTouch.DSFunction" nickname="List.GetItemAtIndex" x="931.774018180431" y="263.326660565833" isVisible="true" isUpstreamVisible="true" lacing="Shortest" isSelectedInput="False" IsFrozen="false" isPinned="true" assembly="DSCoreNodes.dll" function="DSCore.List.GetItemAtIndex@var[]..[],int">
      <PortInfo index="0" default="False" />
      <PortInfo index="1" default="False" />
    </Dynamo.Graph.Nodes.ZeroTouch.DSFunction>
    <Dynamo.Graph.Nodes.CodeBlockNodeModel guid="675c7aff-805c-4775-96d4-e992dc468e58" type="Dynamo.Graph.Nodes.CodeBlockNodeModel" nickname="Code Block" x="820.834499520449" y="359.350727786863" isVisible="true" isUpstreamVisible="true" lacing="Disabled" isSelectedInput="False" IsFrozen="false" isPinned="false" CodeText="0..1;" ShouldFocus="false" />
    <Dynamo.Graph.Nodes.ZeroTouch.DSFunction guid="6115fb63-3b19-45b9-b1e6-0d8e2d510bcb" type="Dynamo.Graph.Nodes.ZeroTouch.DSFunction" nickname="Surfaces.DeconstructSurface" x="453.345985238227" y="102.330566470004" isVisible="true" isUpstreamVisible="true" lacing="Shortest" isSelectedInput="False" IsFrozen="false" isPinned="false" assembly="..\AppData\Roaming\Dynamo\Dynamo Revit\1.3\packages\LunchBox for Dynamo\bin\LunchBox.dll" function="Geometry.Surfaces.DeconstructSurface@Autodesk.DesignScript.Geometry.Surface">
      <PortInfo index="0" default="False" />
    </Dynamo.Graph.Nodes.ZeroTouch.DSFunction>
    <Dynamo.Graph.Nodes.ZeroTouch.DSFunction guid="a6fea02f-4b25-4529-8920-c127b88ee6d0" type="Dynamo.Graph.Nodes.ZeroTouch.DSFunction" nickname="Geometry.BoundingBox" x="1330.05788928764" y="470.768025266854" isVisible="true" isUpstreamVisible="true" lacing="Shortest" isSelectedInput="False" IsFrozen="false" isPinned="true" assembly="ProtoGeometry.dll" function="Autodesk.DesignScript.Geometry.Geometry.BoundingBox">
      <PortInfo index="0" default="False" />
    </Dynamo.Graph.Nodes.ZeroTouch.DSFunction>
    <Dynamo.Graph.Nodes.ZeroTouch.DSFunction guid="ed9abef2-c9a5-45f2-a4a2-17da4bed9479" type="Dynamo.Graph.Nodes.ZeroTouch.DSFunction" nickname="Polygon.Center" x="1336.32864677316" y="133.401272545927" isVisible="true" isUpstreamVisible="true" lacing="Shortest" isSelectedInput="False" IsFrozen="false" isPinned="false" assembly="ProtoGeometry.dll" function="Autodesk.DesignScript.Geometry.Polygon.Center">
      <PortInfo index="0" default="False" />
    </Dynamo.Graph.Nodes.ZeroTouch.DSFunction>
    <Dynamo.Graph.Nodes.CustomNodes.Function guid="c1d44042-270b-450e-bad3-6a7ef55c7fd6" type="Dynamo.Graph.Nodes.CustomNodes.Function" nickname="BoundingBox.Properties" x="1752.70694381162" y="429.317240642788" isVisible="true" isUpstreamVisible="true" lacing="Shortest" isSelectedInput="False" IsFrozen="false" isPinned="true">
      <PortInfo index="0" default="False" />
      <ID value="119fed50-cf6e-435e-9841-59ee18cb7d50" />
      <Name value="BoundingBox.Properties" />
      <Description value="Retrieves the centroid, width, depth and height of a given bounding box" />
      <Inputs>
        <Input value="boundingBox" />
      </Inputs>
      <Outputs>
        <Output value="Centroid" />
        <Output value="Width" />
        <Output value="Depth" />
        <Output value="Height" />
      </Outputs>
    </Dynamo.Graph.Nodes.CustomNodes.Function>
    <Dynamo.Graph.Nodes.ZeroTouch.DSFunction guid="fc794f23-e259-4817-a79b-cccd19ca8ffa" type="Dynamo.Graph.Nodes.ZeroTouch.DSFunction" nickname="Line.ByStartPointEndPoint" x="2279.2137808462" y="577.602588684612" isVisible="true" isUpstreamVisible="true" lacing="Shortest" isSelectedInput="False" IsFrozen="false" isPinned="false" assembly="ProtoGeometry.dll" function="Autodesk.DesignScript.Geometry.Line.ByStartPointEndPoint@Autodesk.DesignScript.Geometry.Point,Autodesk.DesignScript.Geometry.Point">
      <PortInfo index="0" default="False" />
      <PortInfo index="1" default="False" />
    </Dynamo.Graph.Nodes.ZeroTouch.DSFunction>
    <Dynamo.Graph.Nodes.ZeroTouch.DSFunction guid="a70f532f-92b3-452f-8fec-97a8e5b35d73" type="Dynamo.Graph.Nodes.ZeroTouch.DSFunction" nickname="List.Deconstruct" x="2074.61754114292" y="585.110707572806" isVisible="true" isUpstreamVisible="true" lacing="Shortest" isSelectedInput="False" IsFrozen="false" isPinned="false" assembly="DSCoreNodes.dll" function="DSCore.List.Deconstruct@var[]..[]">
      <PortInfo index="0" default="False" />
    </Dynamo.Graph.Nodes.ZeroTouch.DSFunction>
    <Dynamo.Graph.Nodes.ZeroTouch.DSFunction guid="fc2d3df9-d02b-4e4f-a8ee-e978f0d1dff4" type="Dynamo.Graph.Nodes.ZeroTouch.DSFunction" nickname="ModelCurve.ByCurve" x="2616.54971717775" y="589.09072989092" isVisible="true" isUpstreamVisible="true" lacing="Shortest" isSelectedInput="False" IsFrozen="false" isPinned="true" assembly="RevitNodes.dll" function="Revit.Elements.ModelCurve.ByCurve@Autodesk.DesignScript.Geometry.Curve">
      <PortInfo index="0" default="False" />
    </Dynamo.Graph.Nodes.ZeroTouch.DSFunction>
    <PythonNodeModels.PythonNode guid="fd1a69bb-10a3-48e5-a034-d8670b91180d" type="PythonNodeModels.PythonNode" nickname="Python Script" x="10.4986711792924" y="795.054551085407" isVisible="true" isUpstreamVisible="true" lacing="Disabled" isSelectedInput="False" IsFrozen="false" isPinned="true" inputcount="1">
      <PortInfo index="0" default="False" />
      <Script>import clr
import sys

# Import RevitAPI
clr.AddReference('RevitAPI')
from Autodesk.Revit.DB import *
# Import RevitAPIUI
clr.AddReference('RevitAPIUI')
# Import DocumentManager and TransactionManager
clr.AddReference('RevitServices')
import RevitServices
from RevitServices.Persistence import DocumentManager
from RevitServices.Transactions import TransactionManager


clr.AddReference("RevitNodes")
import Revit
# Import ToProtoType, ToRevitType geometry conversion extension methods
clr.ImportExtensions(Revit.GeometryConversion)



# Import Dynamo Python References
clr.AddReference('ProtoGeometry')
from Autodesk.DesignScript.Geometry import *

# Assign Labels to Revit Document and Application
doc = DocumentManager.Instance.CurrentDBDocument
app = DocumentManager.Instance.CurrentUIApplication.Application


doc = DocumentManager.Instance.CurrentDBDocument
uiapp = DocumentManager.Instance.CurrentUIApplication
app = uiapp.Application


beam = UnwrapElement(IN[0])

opt = Options()
opt.ComputeReferences = True
opt.IncludeNonVisibleObjects = True
opt.View = doc.ActiveView


solids = []

geo1 = beam.get_Geometry(opt)
enum1 = geo1.GetEnumerator() 

#; enum1.MoveNext()

#geo2 = enum1.Current.GetInstamceGeometry()

while enum1.MoveNext():
	item = enum1.Current
	try:
		#solids.append(item.GetSymbolGeometry())
		solids.append(item.GetInstanceGeometry())
	except:
		""

enum2 = solids.GetEnumerator()

faces = []

while enum2.MoveNext():
	item = enum2.Current
	try:
		faces.append(item.ComputeCentroid())
	except:
		""
new = []

"""
for solid in solids:
	for face in solid.Faces:
		new.append(face)




for g in geo2:
	s1 = g.Convert()
	if s1 !=None: solids.append(s1)

"""
noa = []
for solid in solids[0]:
	#for face in solid.Faces:
	#	new.append(face)
	noa.append(solid.Faces)
		
OUT = (noa[1][0].ToProtoType(), noa[1][1].ToProtoType())</Script>
    </PythonNodeModels.PythonNode>
    <Dynamo.Graph.Nodes.ZeroTouch.DSFunction guid="c84cd0b2-4451-49eb-b80e-9eda2d5111b1" type="Dynamo.Graph.Nodes.ZeroTouch.DSFunction" nickname="ModelCurve.ByCurve" x="895.814245378942" y="949.983357877106" isVisible="true" isUpstreamVisible="true" lacing="Shortest" isSelectedInput="False" IsFrozen="false" isPinned="true" assembly="RevitNodes.dll" function="Revit.Elements.ModelCurve.ByCurve@Autodesk.DesignScript.Geometry.Curve">
      <PortInfo index="0" default="False" />
    </Dynamo.Graph.Nodes.ZeroTouch.DSFunction>
    <PythonNodeModels.PythonNode guid="fbb92e91-d8bb-4213-8f67-b0c4e57bdbf8" type="PythonNodeModels.PythonNode" nickname="Python Script" x="563.488789911954" y="891.273451781517" isVisible="true" isUpstreamVisible="true" lacing="Disabled" isSelectedInput="False" IsFrozen="false" isPinned="true" inputcount="1">
      <PortInfo index="0" default="False" />
      <Script># Default imports
import clr

# Import RevitAPI
clr.AddReference("RevitAPI")
import Autodesk
from Autodesk.Revit.DB import *

# Import DocumentManager and TransactionManager
clr.AddReference("RevitServices")
import RevitServices
from RevitServices.Persistence import DocumentManager
from RevitServices.Transactions import TransactionManager

# Import ToDSType(bool) extension method
clr.AddReference("RevitNodes")
import Revit
clr.ImportExtensions(Revit.Elements)

#The input to this node will be stored in the IN[0] variable.

doc =  DocumentManager.Instance.CurrentDBDocument
app =  DocumentManager.Instance.CurrentUIApplication.Application

solids = IN[0]

faces = []
edges = []
vertices = []
if hasattr(solids, "__iter__"):
	for solid in solids:
		if hasattr(solid, "__iter__"):
			for sol in solid:
				fcs = []
				edgs = []
				verts = []
				for face in solid.Faces:
					fcs.append(face)
	
				for edge in solid.Edges:
					crv = edge.AsCurve()
					edgs.append(crv)
		
					pt = crv.Evaluate(0, True)
					verts.append(pt)
		
				faces.append(fcs)
				edges.append(edgs)
				vertices.append(verts)
		else:
			fcs = []
			edgs = []
			verts = []
			for face in solid.Faces:
				fcs.append(face)
	
			for edge in solid.Edges:
				crv = edge.AsCurve()
				edgs.append(crv)
		
				pt = crv.Evaluate(0, True)
				verts.append(pt)
		
			faces.append(fcs)
			edges.append(edgs)
			vertices.append(verts)
else:
	fcs = []
	edgs = []
	verts = []
	for face in solids.Faces:
		fcs.append(face)
	
	for edge in solids.Edges:
		crv = edge.AsCurve()
		edgs.append(crv)
		
		pt = crv.Evaluate(0, True)
		verts.append(pt)
		
	faces.append(fcs)
	edges.append(edgs)
	vertices.append(verts)

	
	
output = []
output.append(faces)
output.append(edges)
output.append(vertices)
	

#Assign your output to the OUT variable
OUT = output</Script>
    </PythonNodeModels.PythonNode>
    <Dynamo.Graph.Nodes.CodeBlockNodeModel guid="350a0a31-93a0-4811-af8f-5d94870012ab" type="Dynamo.Graph.Nodes.CodeBlockNodeModel" nickname="Code Block" x="250.166524155647" y="884.924064860677" isVisible="true" isUpstreamVisible="true" lacing="Disabled" isSelectedInput="False" IsFrozen="false" isPinned="true" CodeText="a[0];" ShouldFocus="false">
      <PortInfo index="0" default="False" />
    </Dynamo.Graph.Nodes.CodeBlockNodeModel>
    <PythonNodeModels.PythonNode guid="e5b0116a-b9c8-45a2-8759-12926a96590a" type="PythonNodeModels.PythonNode" nickname="Python Script" x="472.692050422975" y="1031.75089751509" isVisible="true" isUpstreamVisible="true" lacing="Disabled" isSelectedInput="False" IsFrozen="false" isPinned="true" inputcount="1">
      <PortInfo index="0" default="False" />
      <Script>import clr
import sys

# Import RevitAPI
clr.AddReference('RevitAPI')
from Autodesk.Revit.DB import *
# Import RevitAPIUI
clr.AddReference('RevitAPIUI')
# Import DocumentManager and TransactionManager
clr.AddReference('RevitServices')
import RevitServices
from RevitServices.Persistence import DocumentManager
from RevitServices.Transactions import TransactionManager


clr.AddReference("RevitNodes")
import Revit
# Import ToProtoType, ToRevitType geometry conversion extension methods
clr.ImportExtensions(Revit.GeometryConversion)



# Import Dynamo Python References
clr.AddReference('ProtoGeometry')
from Autodesk.DesignScript.Geometry import *

# Assign Labels to Revit Document and Application
doc = DocumentManager.Instance.CurrentDBDocument
app = DocumentManager.Instance.CurrentUIApplication.Application


doc = DocumentManager.Instance.CurrentDBDocument
uiapp = DocumentManager.Instance.CurrentUIApplication
app = uiapp.Application


solids = UnwrapElement(IN[0])

opt = Options()
opt.ComputeReferences = True
opt.IncludeNonVisibleObjects = True
opt.View = doc.ActiveView

faces = []
fcs = []

if hasattr(solids, "__iter__"):
	for solid in solids:
		fcs = []
		edgs = []
		verts = []
		for face in solid.Faces:
			fcs.append(face)
		faces.append(fcs)


else:
	""
	
new = []

#if hasattr(solids, "__iter__"):

for solid in solids:
	for face in solid.Faces:
		new.append(face)

OUT = new</Script>
    </PythonNodeModels.PythonNode>
  </Elements>
  <Connectors>
    <Dynamo.Graph.Connectors.ConnectorModel start="8b65b90f-b51e-4567-9915-65894f0d16a4" start_index="0" end="fd1a69bb-10a3-48e5-a034-d8670b91180d" end_index="0" portType="0" />
    <Dynamo.Graph.Connectors.ConnectorModel start="f69bd1a7-2601-4a01-b3c1-6695117b463a" start_index="0" end="d823d3ec-37bb-4c36-9738-e930523e624b" end_index="0" portType="0" />
    <Dynamo.Graph.Connectors.ConnectorModel start="f69bd1a7-2601-4a01-b3c1-6695117b463a" start_index="0" end="02cfc81a-e256-48ff-b59a-4d95c07b9792" end_index="0" portType="0" />
    <Dynamo.Graph.Connectors.ConnectorModel start="f69bd1a7-2601-4a01-b3c1-6695117b463a" start_index="0" end="6115fb63-3b19-45b9-b1e6-0d8e2d510bcb" end_index="0" portType="0" />
    <Dynamo.Graph.Connectors.ConnectorModel start="675c7aff-805c-4775-96d4-e992dc468e58" start_index="0" end="02cfc81a-e256-48ff-b59a-4d95c07b9792" end_index="1" portType="0" />
    <Dynamo.Graph.Connectors.ConnectorModel start="a6fea02f-4b25-4529-8920-c127b88ee6d0" start_index="0" end="c1d44042-270b-450e-bad3-6a7ef55c7fd6" end_index="0" portType="0" />
    <Dynamo.Graph.Connectors.ConnectorModel start="c1d44042-270b-450e-bad3-6a7ef55c7fd6" start_index="0" end="a70f532f-92b3-452f-8fec-97a8e5b35d73" end_index="0" portType="0" />
    <Dynamo.Graph.Connectors.ConnectorModel start="fc794f23-e259-4817-a79b-cccd19ca8ffa" start_index="0" end="fc2d3df9-d02b-4e4f-a8ee-e978f0d1dff4" end_index="0" portType="0" />
    <Dynamo.Graph.Connectors.ConnectorModel start="a70f532f-92b3-452f-8fec-97a8e5b35d73" start_index="0" end="fc794f23-e259-4817-a79b-cccd19ca8ffa" end_index="0" portType="0" />
    <Dynamo.Graph.Connectors.ConnectorModel start="a70f532f-92b3-452f-8fec-97a8e5b35d73" start_index="1" end="fc794f23-e259-4817-a79b-cccd19ca8ffa" end_index="1" portType="0" />
    <Dynamo.Graph.Connectors.ConnectorModel start="fd1a69bb-10a3-48e5-a034-d8670b91180d" start_index="0" end="c84cd0b2-4451-49eb-b80e-9eda2d5111b1" end_index="0" portType="0" />
    <Dynamo.Graph.Connectors.ConnectorModel start="fd1a69bb-10a3-48e5-a034-d8670b91180d" start_index="0" end="350a0a31-93a0-4811-af8f-5d94870012ab" end_index="0" portType="0" />
    <Dynamo.Graph.Connectors.ConnectorModel start="fd1a69bb-10a3-48e5-a034-d8670b91180d" start_index="0" end="a6fea02f-4b25-4529-8920-c127b88ee6d0" end_index="0" portType="0" />
    <Dynamo.Graph.Connectors.ConnectorModel start="350a0a31-93a0-4811-af8f-5d94870012ab" start_index="0" end="fbb92e91-d8bb-4213-8f67-b0c4e57bdbf8" end_index="0" portType="0" />
    <Dynamo.Graph.Connectors.ConnectorModel start="350a0a31-93a0-4811-af8f-5d94870012ab" start_index="0" end="e5b0116a-b9c8-45a2-8759-12926a96590a" end_index="0" portType="0" />
  </Connectors>
  <Notes />
  <Annotations />
  <Presets />
  <Cameras>
    <Camera Name="Background Preview" eyeX="14161.2236328125" eyeY="31798.2578125" eyeZ="7861.35595703125" lookX="-5060.07421875" lookY="-24906.2578125" lookZ="-27814.453125" upX="-0.0867735370993614" upY="0.874619722366333" upZ="-0.476980835199356" />
  </Cameras>
  <SessionTraceData>
    <NodeTraceData NodeId="fc2d3df9-d02b-4e4f-a8ee-e978f0d1dff4">
      <CallsiteTraceData CallSiteID="ByCurve_InClassDecl-1_InFunctionScope-1_Instance0_fc2d3df9-d02b-4e4f-a8ee-e978f0d1dff4">PFNPQVAtRU5WOkVudmVsb3BlIHhtbG5zOnhzaT0iaHR0cDovL3d3dy53My5vcmcvMjAwMS9YTUxTY2hlbWEtaW5zdGFuY2UiIHhtbG5zOnhzZD0iaHR0cDovL3d3dy53My5vcmcvMjAwMS9YTUxTY2hlbWEiIHhtbG5zOlNPQVAtRU5DPSJodHRwOi8vc2NoZW1hcy54bWxzb2FwLm9yZy9zb2FwL2VuY29kaW5nLyIgeG1sbnM6U09BUC1FTlY9Imh0dHA6Ly9zY2hlbWFzLnhtbHNvYXAub3JnL3NvYXAvZW52ZWxvcGUvIiB4bWxuczpjbHI9Imh0dHA6Ly9zY2hlbWFzLm1pY3Jvc29mdC5jb20vc29hcC9lbmNvZGluZy9jbHIvMS4wIiBTT0FQLUVOVjplbmNvZGluZ1N0eWxlPSJodHRwOi8vc2NoZW1hcy54bWxzb2FwLm9yZy9zb2FwL2VuY29kaW5nLyI+DQo8U09BUC1FTlY6Qm9keT4NCjxhMTpDYWxsU2l0ZV94MDAyQl9UcmFjZVNlcmlhbGlzZXJIZWxwZXIgaWQ9InJlZi0xIiB4bWxuczphMT0iaHR0cDovL3NjaGVtYXMubWljcm9zb2Z0LmNvbS9jbHIvbnNhc3NlbS9Qcm90b0NvcmUvUHJvdG9Db3JlJTJDJTIwVmVyc2lvbiUzRDEuMy4yLjI0ODAlMkMlMjBDdWx0dXJlJTNEbmV1dHJhbCUyQyUyMFB1YmxpY0tleVRva2VuJTNEbnVsbCI+DQo8TnVtYmVyT2ZFbGVtZW50cz4xPC9OdW1iZXJPZkVsZW1lbnRzPg0KPEJhc2UtMF9IYXNEYXRhPmZhbHNlPC9CYXNlLTBfSGFzRGF0YT4NCjxCYXNlLTBfSGFzTmVzdGVkRGF0YT50cnVlPC9CYXNlLTBfSGFzTmVzdGVkRGF0YT4NCjxCYXNlLTBfTmVzdGVkRGF0YUNvdW50PjE8L0Jhc2UtMF9OZXN0ZWREYXRhQ291bnQ+DQo8QmFzZS0wLTBfSGFzRGF0YT5mYWxzZTwvQmFzZS0wLTBfSGFzRGF0YT4NCjxCYXNlLTAtMF9IYXNOZXN0ZWREYXRhPnRydWU8L0Jhc2UtMC0wX0hhc05lc3RlZERhdGE+DQo8QmFzZS0wLTBfTmVzdGVkRGF0YUNvdW50PjE8L0Jhc2UtMC0wX05lc3RlZERhdGFDb3VudD4NCjxCYXNlLTAtMC0wX0hhc0RhdGE+dHJ1ZTwvQmFzZS0wLTAtMF9IYXNEYXRhPg0KPEJhc2UtMC0wLTBfRGF0YSBpZD0icmVmLTMiPlBGTlBRVkF0UlU1V09rVnVkbVZzYjNCbElIaHRiRzV6T25oemFUMGlhSFIwY0RvdkwzZDNkeTUzTXk1dmNtY3ZNakF3TVM5WVRVeFRZMmhsYldFdGFXNXpkR0Z1WTJVaUlIaHRiRzV6T25oelpEMGlhSFIwY0RvdkwzZDNkeTUzTXk1dmNtY3ZNakF3TVM5WVRVeFRZMmhsYldFaUlIaHRiRzV6T2xOUFFWQXRSVTVEUFNKb2RIUndPaTh2YzJOb1pXMWhjeTU0Yld4emIyRndMbTl5Wnk5emIyRndMMlZ1WTI5a2FXNW5MeUlnZUcxc2JuTTZVMDlCVUMxRlRsWTlJbWgwZEhBNkx5OXpZMmhsYldGekxuaHRiSE52WVhBdWIzSm5MM052WVhBdlpXNTJaV3h2Y0dVdklpQjRiV3h1Y3pwamJISTlJbWgwZEhBNkx5OXpZMmhsYldGekxtMXBZM0p2YzI5bWRDNWpiMjB2YzI5aGNDOWxibU52WkdsdVp5OWpiSEl2TVM0d0lpQlRUMEZRTFVWT1ZqcGxibU52WkdsdVoxTjBlV3hsUFNKb2RIUndPaTh2YzJOb1pXMWhjeTU0Yld4emIyRndMbTl5Wnk5emIyRndMMlZ1WTI5a2FXNW5MeUkrRFFvOFUwOUJVQzFGVGxZNlFtOWtlVDROQ2p4aE1UcFRaWEpwWVd4cGVtRmliR1ZKWkNCcFpEMGljbVZtTFRFaUlIaHRiRzV6T21FeFBTSm9kSFJ3T2k4dmMyTm9aVzFoY3k1dGFXTnliM052Wm5RdVkyOXRMMk5zY2k5dWMyRnpjMlZ0TDFKbGRtbDBVMlZ5ZG1salpYTXVVR1Z5YzJsemRHVnVZMlV2VW1WMmFYUlRaWEoyYVdObGN5VXlReVV5TUZabGNuTnBiMjRsTTBReExqTXVNaTR5TkRnd0pUSkRKVEl3UTNWc2RIVnlaU1V6Ukc1bGRYUnlZV3dsTWtNbE1qQlFkV0pzYVdOTFpYbFViMnRsYmlVelJHNTFiR3dpUGcwS1BITjBjbWx1WjBsRUlHbGtQU0p5WldZdE15SStNamd4WlRJeU56WXROR0UxT1MwME5UTXpMVGs0WTJNdFpERmhPVEZqTW1Nek5ERXdMVEF3TWpJeU1UTmhQQzl6ZEhKcGJtZEpSRDROQ2p4cGJuUkpSRDR5TWpNMk56TXdQQzlwYm5SSlJENE5Dand2WVRFNlUyVnlhV0ZzYVhwaFlteGxTV1ErRFFvOEwxTlBRVkF0UlU1V09rSnZaSGsrRFFvOEwxTlBRVkF0UlU1V09rVnVkbVZzYjNCbFBnMEs8L0Jhc2UtMC0wLTBfRGF0YT4NCjxCYXNlLTAtMC0wX0hhc05lc3RlZERhdGE+ZmFsc2U8L0Jhc2UtMC0wLTBfSGFzTmVzdGVkRGF0YT4NCjwvYTE6Q2FsbFNpdGVfeDAwMkJfVHJhY2VTZXJpYWxpc2VySGVscGVyPg0KPC9TT0FQLUVOVjpCb2R5Pg0KPC9TT0FQLUVOVjpFbnZlbG9wZT4NCg==</CallsiteTraceData>
    </NodeTraceData>
  </SessionTraceData>
</Workspace>