<Workspace Version="0.8.2.2392" X="606.013281225092" Y="159.231700962792" zoom="0.789161032924816" Name="Home" Description="" RunType="Manual" RunPeriod="1000" HasRunWithoutCrash="True">
  <NamespaceResolutionMap>
    <ClassMap partialName="Element" resolvedName="Revit.Elements.Element" assemblyName="RevitNodes.dll" />
  </NamespaceResolutionMap>
  <Elements>
    <DSIronPythonNode.PythonNode guid="af56be55-e1b9-4591-bdc0-7a834f466d02" type="DSIronPythonNode.PythonNode" nickname="Python Script" x="414.537525163956" y="176.199698773646" isVisible="true" isUpstreamVisible="true" lacing="Disabled" isSelectedInput="False" inputcount="2">
      <Script>import clr

clr.AddReference("RevitServices")
import RevitServices
from RevitServices.Persistence import DocumentManager
from RevitServices.Transactions import TransactionManager
doc = DocumentManager.Instance.CurrentDBDocument

clr.AddReference("RevitAPI")
import Autodesk
from Autodesk.Revit.DB import *

clr.AddReference("RevitNodes")
import Revit
clr.ImportExtensions(Revit.Elements)
clr.ImportExtensions(Revit.GeometryConversion)

clr.AddReference("System")
from System.Collections.Generic import List

beamElements = UnwrapElement(IN[0])
pts = UnwrapElement(IN[1])

beamLocations = []

for beam in beamElements:
	beamLocations.append(beam.Location)

newBeamLine = []

TransactionManager.Instance.EnsureInTransaction(doc)

for i in range(0,len(beamLocations)):
	newBeamLine = Line.CreateBound(pts[i][0].ToXyz(), pts[i][1].ToXyz())
	#Change the beam location line to a new line:
	beamLocations[i].Curve = newBeamLine;

            

TransactionManager.Instance.TransactionTaskDone()

OUT = beamElements</Script>
    </DSIronPythonNode.PythonNode>
    <Dynamo.Nodes.DSModelElementSelection guid="7140e0d7-136f-42de-a0aa-a49028ba35f5" type="Dynamo.Nodes.DSModelElementSelection" nickname="Select Model Element" x="-596.488323292556" y="94.960803949749" isVisible="true" isUpstreamVisible="true" lacing="Disabled" isSelectedInput="True">
      <instance id="e2cc3c8b-1268-4723-b0f8-179d4af5ba96-00b02ab8" />
    </Dynamo.Nodes.DSModelElementSelection>
    <DSIronPythonNode.PythonNode guid="ecd91049-3033-4233-975e-3481a06225c8" type="DSIronPythonNode.PythonNode" nickname="Python Script" x="15.3547006503891" y="367.541682127926" isVisible="true" isUpstreamVisible="true" lacing="Disabled" isSelectedInput="False" inputcount="1">
      <Script>import clr
clr.AddReference('RevitAPI')
from Autodesk.Revit.DB import *

clr.AddReference("RevitNodes")
import Revit
clr.ImportExtensions(Revit.GeometryConversion)

clr.AddReference('ProtoGeometry')
from Autodesk.DesignScript.Geometry import *

items = UnwrapElement(IN[0])

lines = []

for item in items:
	lines.append(item.Location.Curve.ToProtoType())

Pts = []


for line in lines:
	pt = []
	pt.append(Curve.PointAtParameter(line,0))
	stPt = Curve.PointAtParameter(line,0)
	endPt = Curve.PointAtParameter(line,1)
	pt.append(Point.ByCoordinates(stPt.X,stPt.Y,endPt.Z))
	Pts.append(pt)

OUT = Pts</Script>
    </DSIronPythonNode.PythonNode>
    <Dynamo.Nodes.CodeBlockNodeModel guid="20dba3a4-b9de-45a8-8e7b-d1d6352a6865" type="Dynamo.Nodes.CodeBlockNodeModel" nickname="Code Block" x="-311.877376360911" y="18.459620692727" isVisible="true" isUpstreamVisible="true" lacing="Disabled" isSelectedInput="False" CodeText="{a};" ShouldFocus="false" />
    <Dynamo.Nodes.CodeBlockNodeModel guid="0aa6f624-bc13-4cca-a476-c1c853ce8746" type="Dynamo.Nodes.CodeBlockNodeModel" nickname="Code Block" x="-541.83451854346" y="538.031284475788" isVisible="true" isUpstreamVisible="true" lacing="Disabled" isSelectedInput="False" CodeText="{a};" ShouldFocus="false" />
    <Dynamo.Nodes.DSModelElementsSelection guid="c780f945-c77d-47a0-886f-6ec9016be70c" type="Dynamo.Nodes.DSModelElementsSelection" nickname="Select Model Elements" x="-545.960245644308" y="364.852895418311" isVisible="true" isUpstreamVisible="true" lacing="Disabled" isSelectedInput="True">
      <instance id="e2cc3c8b-1268-4723-b0f8-179d4af5ba96-00b02ab8" />
      <instance id="bb719eff-80e3-421f-ae1a-90e8af3fbab1-00b41bf9" />
    </Dynamo.Nodes.DSModelElementsSelection>
    <Dynamo.Nodes.DSFunction guid="a067f451-2afa-4eed-aab8-c523ba2a310e" type="Dynamo.Nodes.DSFunction" nickname="Element.SetParameterByName" x="858.765645866463" y="340.19194121218" isVisible="true" isUpstreamVisible="true" lacing="Shortest" isSelectedInput="False" assembly="RevitNodes.dll" function="Revit.Elements.Element.SetParameterByName@string,var" />
    <Dynamo.Nodes.CodeBlockNodeModel guid="c5e0dc12-b732-4fb8-af49-99e621c04072" type="Dynamo.Nodes.CodeBlockNodeModel" nickname="Code Block" x="565.605123291186" y="441.721024658237" isVisible="true" isUpstreamVisible="true" lacing="Disabled" isSelectedInput="True" CodeText="&quot;Column Style&quot;;" ShouldFocus="false" />
    <Dynamo.Nodes.CodeBlockNodeModel guid="dfa4f23c-9fb3-4ab4-987c-3e5d237fb978" type="Dynamo.Nodes.CodeBlockNodeModel" nickname="Code Block" x="649" y="588" isVisible="true" isUpstreamVisible="true" lacing="Disabled" isSelectedInput="True" CodeText="0;" ShouldFocus="false" />
    <DSIronPythonNode.PythonNode guid="95297077-6a01-40a7-878b-48748eeff2c7" type="DSIronPythonNode.PythonNode" nickname="Python Script" x="226.562115409546" y="-24.8207517130771" isVisible="true" isUpstreamVisible="true" lacing="Disabled" isSelectedInput="False" inputcount="2">
      <Script>import clr

clr.AddReference("RevitServices")
import RevitServices
from RevitServices.Persistence import DocumentManager
from RevitServices.Transactions import TransactionManager
doc = DocumentManager.Instance.CurrentDBDocument

clr.AddReference("RevitAPI")
import Autodesk
from Autodesk.Revit.DB import *

clr.AddReference("RevitNodes")
import Revit
clr.ImportExtensions(Revit.Elements)
clr.ImportExtensions(Revit.GeometryConversion)

clr.AddReference("System")
from System.Collections.Generic import List

beamElements = UnwrapElement(IN[0])
pts = UnwrapElement(IN[1])

beamLocations = []

for beam in beamElements:
	beamLocations.append(beam.Location)

newBeamLine = []

TransactionManager.Instance.EnsureInTransaction(doc)

for i in range(0,len(beamLocations)):
	newBeamLine = Line.CreateBound(pts[i][0].ToXyz(), pts[i][1].ToXyz())
	#Change the beam location line to a new line:
	beamLocations[i].Curve = newBeamLine;

            

TransactionManager.Instance.TransactionTaskDone()

OUT = beamElements</Script>
    </DSIronPythonNode.PythonNode>
    <Dynamo.Nodes.DSFunction guid="f34de802-3dd7-4c14-afbb-2d1a904ec97d" type="Dynamo.Nodes.DSFunction" nickname="Element.OverrideColorInView" x="576.544836595163" y="846.174951850197" isVisible="true" isUpstreamVisible="true" lacing="Shortest" isSelectedInput="False" assembly="RevitNodes.dll" function="Revit.Elements.Element.OverrideColorInView@DSCore.Color" />
    <Dynamo.Nodes.DSFunction guid="c3463fe6-5e80-43c1-8bdb-d16c5f94b34c" type="Dynamo.Nodes.DSFunction" nickname="Element.GetParameterValueByName" x="-346.4811022209" y="998.97506700617" isVisible="true" isUpstreamVisible="true" lacing="Shortest" isSelectedInput="False" assembly="RevitNodes.dll" function="Revit.Elements.Element.GetParameterValueByName@string" />
    <Dynamo.Nodes.CodeBlockNodeModel guid="9ec09cf0-829e-433a-9375-b02f9382b7e4" type="Dynamo.Nodes.CodeBlockNodeModel" nickname="Code Block" x="-666" y="1033" isVisible="true" isUpstreamVisible="true" lacing="Disabled" isSelectedInput="True" CodeText="&quot;Column Style&quot;;" ShouldFocus="false" />
    <Dynamo.Nodes.CodeBlockNodeModel guid="b18bf84a-768e-4857-8f4e-01e396de279e" type="Dynamo.Nodes.CodeBlockNodeModel" nickname="Code Block" x="18.8015054910672" y="1119.03010982135" isVisible="true" isUpstreamVisible="true" lacing="Disabled" isSelectedInput="False" CodeText="a&gt;0;" ShouldFocus="false" />
    <Dynamo.Nodes.DSFunction guid="13829b28-d0dc-4ddb-a42b-67a797fd7e7c" type="Dynamo.Nodes.DSFunction" nickname="List.FilterByBoolMask" x="295.233430256185" y="1040.05173189463" isVisible="true" isUpstreamVisible="true" lacing="Shortest" isSelectedInput="False" assembly="DSCoreNodes.dll" function="DSCore.List.FilterByBoolMask@var[]..[],var[]..[]" />
    <Dynamo.Nodes.DSFunction guid="1dcea1f1-51bc-4f3b-90a8-c410e01bf34b" type="Dynamo.Nodes.DSFunction" nickname="Color.ByARGB" x="312.973789214499" y="861.380973814466" isVisible="true" isUpstreamVisible="true" lacing="Shortest" isSelectedInput="False" assembly="DSCoreNodes.dll" function="DSCore.Color.ByARGB@int,int,int,int">
      <PortInfo index="0" default="True" />
      <PortInfo index="1" default="True" />
      <PortInfo index="2" default="True" />
      <PortInfo index="3" default="True" />
    </Dynamo.Nodes.DSFunction>
    <Dynamo.Nodes.CodeBlockNodeModel guid="a8cfaaf1-b73b-4390-ba52-803c1b40c9b5" type="Dynamo.Nodes.CodeBlockNodeModel" nickname="Code Block" x="101" y="920" isVisible="true" isUpstreamVisible="true" lacing="Disabled" isSelectedInput="True" CodeText="255;" ShouldFocus="false" />
    <DSIronPythonNode.PythonNode guid="25e9e939-0b2e-4e44-af08-4793a778376b" type="DSIronPythonNode.PythonNode" nickname="Python Script" x="-136.153250636155" y="133.476864618879" isVisible="true" isUpstreamVisible="true" lacing="Disabled" isSelectedInput="False" inputcount="1">
      <Script>import clr
clr.AddReference('RevitAPI')
from Autodesk.Revit.DB import *

clr.AddReference("RevitNodes")
import Revit
clr.ImportExtensions(Revit.GeometryConversion)

clr.AddReference('ProtoGeometry')
from Autodesk.DesignScript.Geometry import *

items = UnwrapElement(IN[0])

lines = []

for item in items:
	lines.append(item.Location.Curve.ToProtoType())

Pts = []


for line in lines:
	pt = []
	pt.append(Curve.PointAtParameter(line,0))
	stPt = Curve.PointAtParameter(line,0)
	endPt = Curve.PointAtParameter(line,1)
	pt.append(Point.ByCoordinates(stPt.X,stPt.Y,endPt.Z))
	Pts.append(pt)

OUT = Pts</Script>
    </DSIronPythonNode.PythonNode>
  </Elements>
  <Connectors>
    <Dynamo.Models.ConnectorModel start="ecd91049-3033-4233-975e-3481a06225c8" start_index="0" end="af56be55-e1b9-4591-bdc0-7a834f466d02" end_index="1" portType="0" />
    <Dynamo.Models.ConnectorModel start="20dba3a4-b9de-45a8-8e7b-d1d6352a6865" start_index="0" end="95297077-6a01-40a7-878b-48748eeff2c7" end_index="0" portType="0" />
    <Dynamo.Models.ConnectorModel start="20dba3a4-b9de-45a8-8e7b-d1d6352a6865" start_index="0" end="25e9e939-0b2e-4e44-af08-4793a778376b" end_index="0" portType="0" />
    <Dynamo.Models.ConnectorModel start="c780f945-c77d-47a0-886f-6ec9016be70c" start_index="0" end="ecd91049-3033-4233-975e-3481a06225c8" end_index="0" portType="0" />
    <Dynamo.Models.ConnectorModel start="c780f945-c77d-47a0-886f-6ec9016be70c" start_index="0" end="13829b28-d0dc-4ddb-a42b-67a797fd7e7c" end_index="0" portType="0" />
    <Dynamo.Models.ConnectorModel start="c780f945-c77d-47a0-886f-6ec9016be70c" start_index="0" end="af56be55-e1b9-4591-bdc0-7a834f466d02" end_index="0" portType="0" />
    <Dynamo.Models.ConnectorModel start="c5e0dc12-b732-4fb8-af49-99e621c04072" start_index="0" end="a067f451-2afa-4eed-aab8-c523ba2a310e" end_index="1" portType="0" />
    <Dynamo.Models.ConnectorModel start="dfa4f23c-9fb3-4ab4-987c-3e5d237fb978" start_index="0" end="a067f451-2afa-4eed-aab8-c523ba2a310e" end_index="2" portType="0" />
    <Dynamo.Models.ConnectorModel start="c3463fe6-5e80-43c1-8bdb-d16c5f94b34c" start_index="0" end="b18bf84a-768e-4857-8f4e-01e396de279e" end_index="0" portType="0" />
    <Dynamo.Models.ConnectorModel start="9ec09cf0-829e-433a-9375-b02f9382b7e4" start_index="0" end="c3463fe6-5e80-43c1-8bdb-d16c5f94b34c" end_index="1" portType="0" />
    <Dynamo.Models.ConnectorModel start="b18bf84a-768e-4857-8f4e-01e396de279e" start_index="0" end="13829b28-d0dc-4ddb-a42b-67a797fd7e7c" end_index="1" portType="0" />
    <Dynamo.Models.ConnectorModel start="1dcea1f1-51bc-4f3b-90a8-c410e01bf34b" start_index="0" end="f34de802-3dd7-4c14-afbb-2d1a904ec97d" end_index="1" portType="0" />
    <Dynamo.Models.ConnectorModel start="a8cfaaf1-b73b-4390-ba52-803c1b40c9b5" start_index="0" end="1dcea1f1-51bc-4f3b-90a8-c410e01bf34b" end_index="1" portType="0" />
    <Dynamo.Models.ConnectorModel start="25e9e939-0b2e-4e44-af08-4793a778376b" start_index="0" end="95297077-6a01-40a7-878b-48748eeff2c7" end_index="1" portType="0" />
  </Connectors>
  <Notes />
  <Annotations />
  <Presets />
  <Cameras>
    <Camera Name="background_preview" eyeX="10" eyeY="15" eyeZ="10" lookX="-10" lookY="-10" lookZ="-10" />
  </Cameras>
</Workspace>