<Workspace Version="1.3.2.2480" X="-1347.64434499302" Y="-606.878980150201" zoom="0.989462991513227" ScaleFactor="1" Name="Home" Description="" RunType="Manual" RunPeriod="1000" HasRunWithoutCrash="True">
  <NamespaceResolutionMap />
  <Elements>
    <PythonNodeModels.PythonNode guid="428eeb38-e1dd-411b-91a6-96767397a4b2" type="PythonNodeModels.PythonNode" nickname="Python Script" x="1933.28161659076" y="608.000707953558" isVisible="true" isUpstreamVisible="true" lacing="Disabled" isSelectedInput="False" IsFrozen="false" isPinned="true" inputcount="1">
      <PortInfo index="0" default="False" />
      <Script>import clr
clr.AddReference('ProtoGeometry')
from Autodesk.DesignScript.Geometry import *

clr.AddReference('RevitServices')
import RevitServices
from RevitServices.Persistence import DocumentManager
from RevitServices.Transactions import TransactionManager
from System.Collections.Generic import *

clr.AddReference('RevitNodes')
import Revit
clr.ImportExtensions(Revit.Elements)

clr.AddReference('RevitAPI')
import Autodesk
from Autodesk.Revit.DB import *
from Autodesk.Revit.DB.Electrical import *
from Autodesk.Revit.DB import MEPSystem

clr.AddReference('DSCoreNodes')
import DSCore
from DSCore.List import *

import sys
pyt_path = r'C:\Program Files (x86)\IronPython 2.7\Lib'
sys.path.append(pyt_path)

# Import List ( ICollection(ElementId) = List[ElementId]() )
clr.AddReference("System")
from System.Collections.Generic import List 

#The inputs to this node will be stored as a list in the IN variables.
input = UnwrapElement(IN[0])

listElectComponents = []

electComponents = List[ElementId]()

for i in range(0, len(input)):
	electComponents.Add(input[i].Id)

doc = DocumentManager.Instance.CurrentDBDocument

TransactionManager.Instance.EnsureInTransaction(doc)

#newCircuits = doc.Create.NewElectricalSystem(electComponents, ElectricalSystemType.PowerCircuit)

TransactionManager.Instance.TransactionTaskDone()

OUT = electComponents
</Script>
    </PythonNodeModels.PythonNode>
    <Dynamo.Nodes.DSModelElementsSelection guid="3ff9780e-d3f5-428a-b814-96cc6c54fb54" type="Dynamo.Nodes.DSModelElementsSelection" nickname="Select Model Elements" x="1533.29635085812" y="781.555186262309" isVisible="true" isUpstreamVisible="true" lacing="Disabled" isSelectedInput="True" IsFrozen="false" isPinned="true">
      <instance id="e98b31c3-6b2f-4c48-aed1-f06d0515d99b-01110e3d" />
    </Dynamo.Nodes.DSModelElementsSelection>
    <Dynamo.Graph.Nodes.CodeBlockNodeModel guid="c3265bbf-3b2b-4d05-ad9d-b51568558b50" type="Dynamo.Graph.Nodes.CodeBlockNodeModel" nickname="Code Block" x="529.036256327884" y="804.640131606579" isVisible="true" isUpstreamVisible="true" lacing="Disabled" isSelectedInput="False" IsFrozen="false" isPinned="true" CodeText="Flatten(&quot;LV&quot;+{1..3});" ShouldFocus="false" />
    <Dynamo.Graph.Nodes.CodeBlockNodeModel guid="670cc299-b5c1-464f-b72d-577a70448fbb" type="Dynamo.Graph.Nodes.CodeBlockNodeModel" nickname="Code Block" x="525.294295483348" y="1067.41435230881" isVisible="true" isUpstreamVisible="true" lacing="Disabled" isSelectedInput="False" IsFrozen="false" isPinned="true" CodeText="{Flatten(&quot;DB&quot;+{1..2}),Flatten(&quot;DB&quot;+{3..5}),Flatten(&quot;DB&quot;+{6..7})};" ShouldFocus="false" />
    <PythonNodeModels.PythonNode guid="e747f195-2106-4fba-807f-49a565c6f5c9" type="PythonNodeModels.PythonNode" nickname="Python Script" x="1265.89353612405" y="797.798536229874" isVisible="true" isUpstreamVisible="true" lacing="Disabled" isSelectedInput="False" IsFrozen="false" isPinned="true" inputcount="2">
      <PortInfo index="0" default="False" />
      <PortInfo index="1" default="False" />
      <Script>import clr
clr.AddReference('ProtoGeometry')
from Autodesk.DesignScript.Geometry import *
#The inputs to this node will be stored as a list in the IN variables.
lv = IN[0]
db = IN[1]

combinedList = []

for i in range(0,len(lv)):
	subList = []
	combinedList.append(subList)
	for j in range(0,len(db[i])):
		subList.append(lv[i])
		subList.append(db[i][j])
		

#Assign your output to the OUT variable.
OUT = combinedList</Script>
    </PythonNodeModels.PythonNode>
    <Dynamo.Nodes.DSModelElementsSelection guid="99d80ff1-d86a-4c7e-aa7d-6220bfe7ecd8" type="Dynamo.Nodes.DSModelElementsSelection" nickname="Select Model Elements" x="1554.08470183996" y="1176.20018930513" isVisible="true" isUpstreamVisible="true" lacing="Disabled" isSelectedInput="True" IsFrozen="false" isPinned="true">
      <instance id="e98b31c3-6b2f-4c48-aed1-f06d0515d99b-0111127e" />
      <instance id="e98b31c3-6b2f-4c48-aed1-f06d0515d99b-01111690" />
      <instance id="e98b31c3-6b2f-4c48-aed1-f06d0515d99b-01111691" />
    </Dynamo.Nodes.DSModelElementsSelection>
    <Dynamo.Graph.Nodes.CodeBlockNodeModel guid="793a5259-97b3-404f-bc09-6870fb3bb726" type="Dynamo.Graph.Nodes.CodeBlockNodeModel" nickname="Code Block" x="1900.9824739304" y="1165.1125526396" isVisible="true" isUpstreamVisible="true" lacing="Disabled" isSelectedInput="False" IsFrozen="false" isPinned="true" CodeText="{a[0..1],a[2..4],a[5..6]};" ShouldFocus="false">
      <PortInfo index="0" default="False" />
    </Dynamo.Graph.Nodes.CodeBlockNodeModel>
    <PythonNodeModels.PythonNode guid="f252c58a-38b7-4513-aefa-cb417cefbfbf" type="PythonNodeModels.PythonNode" nickname="Python Script" x="2255.92189001996" y="920.795184324781" isVisible="true" isUpstreamVisible="true" lacing="Disabled" isSelectedInput="False" IsFrozen="false" isPinned="true" inputcount="2">
      <PortInfo index="0" default="False" />
      <PortInfo index="1" default="False" />
      <Script>import clr
clr.AddReference('ProtoGeometry')
from Autodesk.DesignScript.Geometry import *

clr.AddReference('RevitServices')
import RevitServices
from RevitServices.Persistence import DocumentManager
from RevitServices.Transactions import TransactionManager
from System.Collections.Generic import *

clr.AddReference('RevitNodes')
import Revit
clr.ImportExtensions(Revit.Elements)

clr.AddReference('RevitAPI')
import Autodesk
from Autodesk.Revit.DB import *
from Autodesk.Revit.DB.Electrical import *
from Autodesk.Revit.DB import MEPSystem

clr.AddReference('DSCoreNodes')
import DSCore
from DSCore.List import *

# Import List ( ICollection(ElementId) = List[ElementId]() )
clr.AddReference("System")
from System.Collections.Generic import List 

doc = DocumentManager.Instance.CurrentDBDocument


#The inputs to this node will be stored as a list in the IN variables.
lv = UnwrapElement(IN[0])
db = UnwrapElement(IN[1])

newCircuits = []


TransactionManager.Instance.EnsureInTransaction(doc)

for i in range(0,len(lv)):
	subList = []
	#newCircuits.append(subList)
	for j in range(0,len(db[i])):
		elements = List[ElementId]()
		elements = [lv[i], db[i][j]]
		newCircuits.append(elements)
		#newCircuits.append(doc.Create.NewElectricalSystem(elements, ElectricalSystemType.PowerCircuit))

TransactionManager.Instance.TransactionTaskDone()

#Assign your output to the OUT variable.
OUT = newCircuits</Script>
    </PythonNodeModels.PythonNode>
    <Dynamo.Nodes.DSModelElementsSelection guid="3fd599ca-7db7-430a-927a-c13926288f2f" type="Dynamo.Nodes.DSModelElementsSelection" nickname="Select Model Elements" x="652.307879845585" y="492.413208963726" isVisible="true" isUpstreamVisible="true" lacing="Disabled" isSelectedInput="True" IsFrozen="false" isPinned="true" />
    <Dynamo.Graph.Nodes.CodeBlockNodeModel guid="8b5d9ceb-1899-4f1b-ac21-e9197283a5d2" type="Dynamo.Graph.Nodes.CodeBlockNodeModel" nickname="Code Block" x="1047.50653374039" y="490.304160828982" isVisible="true" isUpstreamVisible="true" lacing="Disabled" isSelectedInput="False" IsFrozen="false" isPinned="false" CodeText="{a};" ShouldFocus="false">
      <PortInfo index="0" default="False" />
    </Dynamo.Graph.Nodes.CodeBlockNodeModel>
    <PythonNodeModels.PythonNode guid="c83d9335-e0ba-47af-940d-fdc95f0d57f9" type="PythonNodeModels.PythonNode" nickname="Python Script" x="2507.44622829202" y="921.964299791747" isVisible="true" isUpstreamVisible="true" lacing="Disabled" isSelectedInput="False" IsFrozen="false" isPinned="true" inputcount="1">
      <PortInfo index="0" default="False" />
      <Script>import clr
clr.AddReference('ProtoGeometry')
from Autodesk.DesignScript.Geometry import *

clr.AddReference('RevitServices')
import RevitServices
from RevitServices.Persistence import DocumentManager
from RevitServices.Transactions import TransactionManager
from System.Collections.Generic import *

clr.AddReference('RevitNodes')
import Revit
clr.ImportExtensions(Revit.Elements)

clr.AddReference('RevitAPI')
import Autodesk
from Autodesk.Revit.DB import *
from Autodesk.Revit.DB.Electrical import *
from Autodesk.Revit.DB import MEPSystem

clr.AddReference('DSCoreNodes')
import DSCore
from DSCore.List import *

import sys
pyt_path = r'C:\Program Files (x86)\IronPython 2.7\Lib'
sys.path.append(pyt_path)

# Import List ( ICollection(ElementId) = List[ElementId]() )
clr.AddReference("System")
from System.Collections.Generic import List 

#The inputs to this node will be stored as a list in the IN variables.
input = UnwrapElement(IN[0])


doc = DocumentManager.Instance.CurrentDBDocument
uiapp = DocumentManager.Instance.CurrentUIApplication
app = uiapp.Application
uidoc = DocumentManager.Instance.CurrentUIApplication.ActiveUIDocument

TransactionManager.Instance.EnsureInTransaction(doc)

newCircuits = []

for e in input:
	ele = List[ElementId]()
	ele.Add(e[0].Id)
	ele.Add(e[1].Id)
#	newCircuits.append(doc.Create.NewElectricalSystem(ele, ElectricalSystemType.PowerCircuit))
	newCircuits.append(ele)


TransactionManager.Instance.TransactionTaskDone()

OUT = newCircuits
</Script>
    </PythonNodeModels.PythonNode>
    <Dynamo.Graph.Nodes.CodeBlockNodeModel guid="e31f78e9-5b28-4a7b-9184-082e84b9ae52" type="Dynamo.Graph.Nodes.CodeBlockNodeModel" nickname="Code Block" x="1761" y="619" isVisible="true" isUpstreamVisible="true" lacing="Disabled" isSelectedInput="False" IsFrozen="false" isPinned="false" CodeText="{a};" ShouldFocus="false">
      <PortInfo index="0" default="False" />
    </Dynamo.Graph.Nodes.CodeBlockNodeModel>
  </Elements>
  <Connectors>
    <Dynamo.Graph.Connectors.ConnectorModel start="3ff9780e-d3f5-428a-b814-96cc6c54fb54" start_index="0" end="f252c58a-38b7-4513-aefa-cb417cefbfbf" end_index="0" portType="0" />
    <Dynamo.Graph.Connectors.ConnectorModel start="3ff9780e-d3f5-428a-b814-96cc6c54fb54" start_index="0" end="e31f78e9-5b28-4a7b-9184-082e84b9ae52" end_index="0" portType="0" />
    <Dynamo.Graph.Connectors.ConnectorModel start="3ff9780e-d3f5-428a-b814-96cc6c54fb54" start_index="0" end="428eeb38-e1dd-411b-91a6-96767397a4b2" end_index="0" portType="0" />
    <Dynamo.Graph.Connectors.ConnectorModel start="c3265bbf-3b2b-4d05-ad9d-b51568558b50" start_index="0" end="e747f195-2106-4fba-807f-49a565c6f5c9" end_index="0" portType="0" />
    <Dynamo.Graph.Connectors.ConnectorModel start="670cc299-b5c1-464f-b72d-577a70448fbb" start_index="0" end="e747f195-2106-4fba-807f-49a565c6f5c9" end_index="1" portType="0" />
    <Dynamo.Graph.Connectors.ConnectorModel start="99d80ff1-d86a-4c7e-aa7d-6220bfe7ecd8" start_index="0" end="793a5259-97b3-404f-bc09-6870fb3bb726" end_index="0" portType="0" />
    <Dynamo.Graph.Connectors.ConnectorModel start="793a5259-97b3-404f-bc09-6870fb3bb726" start_index="0" end="f252c58a-38b7-4513-aefa-cb417cefbfbf" end_index="1" portType="0" />
    <Dynamo.Graph.Connectors.ConnectorModel start="f252c58a-38b7-4513-aefa-cb417cefbfbf" start_index="0" end="c83d9335-e0ba-47af-940d-fdc95f0d57f9" end_index="0" portType="0" />
    <Dynamo.Graph.Connectors.ConnectorModel start="3fd599ca-7db7-430a-927a-c13926288f2f" start_index="0" end="8b5d9ceb-1899-4f1b-ac21-e9197283a5d2" end_index="0" portType="0" />
  </Connectors>
  <Notes />
  <Annotations />
  <Presets />
  <Cameras>
    <Camera Name="Background Preview" eyeX="-17" eyeY="24" eyeZ="50" lookX="12" lookY="-13" lookZ="-58" upX="0" upY="1" upZ="0" />
  </Cameras>
</Workspace>