<Workspace Version="1.3.2.2480" X="-1503.17189230157" Y="-47.145875993229" zoom="0.602118762475656" ScaleFactor="1" Name="Home" Description="" RunType="Manual" RunPeriod="1000" HasRunWithoutCrash="True">
  <NamespaceResolutionMap>
    <ClassMap partialName="Autodesk.Point" resolvedName="Autodesk.DesignScript.Geometry.Point" assemblyName="ProtoGeometry.dll" />
    <ClassMap partialName="Autodesk.DesignScript.Geometry.Point" resolvedName="Autodesk.DesignScript.Geometry.Point" assemblyName="ProtoGeometry.dll" />
  </NamespaceResolutionMap>
  <Elements>
    <Dynamo.Nodes.DSModelElementsSelection guid="74909603-d31f-454e-a5c1-60f50c5e7c17" type="Dynamo.Nodes.DSModelElementsSelection" nickname="Select Model Elements" x="2024.24715647574" y="-75.2433054388928" isVisible="true" isUpstreamVisible="true" lacing="Disabled" isSelectedInput="True" IsFrozen="false" isPinned="true" />
    <Dynamo.Nodes.DSModelElementsSelection guid="b45993f0-0ea7-421f-bc55-7540531e4b3c" type="Dynamo.Nodes.DSModelElementsSelection" nickname="Select Model Elements" x="1832.18149389624" y="274.815645499112" isVisible="true" isUpstreamVisible="true" lacing="Disabled" isSelectedInput="True" IsFrozen="false" isPinned="true" />
    <Dynamo.Nodes.DSModelElementsSelection guid="b5998032-2c50-4da2-8bf4-23d225873212" type="Dynamo.Nodes.DSModelElementsSelection" nickname="Select Model Elements" x="2047.08013734183" y="62.8146626503214" isVisible="true" isUpstreamVisible="true" lacing="Disabled" isSelectedInput="True" IsFrozen="false" isPinned="true" />
    <Dynamo.Nodes.DSModelElementsSelection guid="0441048c-b4f8-4b4c-b50f-48b608ee108d" type="Dynamo.Nodes.DSModelElementsSelection" nickname="Select Model Elements" x="1900.68043649452" y="532.111578291935" isVisible="true" isUpstreamVisible="true" lacing="Disabled" isSelectedInput="True" IsFrozen="false" isPinned="true" />
    <Dynamo.Graph.Nodes.CodeBlockNodeModel guid="bea7452d-1c0e-468f-b959-92dfd128d2db" type="Dynamo.Graph.Nodes.CodeBlockNodeModel" nickname="Code Block" x="2462.17263139583" y="14.0643846370327" isVisible="true" isUpstreamVisible="true" lacing="Disabled" isSelectedInput="False" IsFrozen="false" isPinned="true" CodeText="{a,b};" ShouldFocus="false">
      <PortInfo index="0" default="False" />
      <PortInfo index="1" default="False" />
    </Dynamo.Graph.Nodes.CodeBlockNodeModel>
    <Dynamo.Graph.Nodes.CodeBlockNodeModel guid="b88378c8-ffce-4819-9584-16f96ecceb27" type="Dynamo.Graph.Nodes.CodeBlockNodeModel" nickname="Code Block" x="2447.16903795191" y="253.003755018465" isVisible="true" isUpstreamVisible="true" lacing="Disabled" isSelectedInput="False" IsFrozen="false" isPinned="true" CodeText="{a,b};" ShouldFocus="false">
      <PortInfo index="0" default="False" />
      <PortInfo index="1" default="False" />
    </Dynamo.Graph.Nodes.CodeBlockNodeModel>
    <PythonNodeModels.PythonNode guid="f85789a3-7418-40a9-9dd7-7c6318f7ccbb" type="PythonNodeModels.PythonNode" nickname="Python Script" x="2628.13528352121" y="136.546483495434" isVisible="true" isUpstreamVisible="true" lacing="Disabled" isSelectedInput="False" IsFrozen="false" isPinned="true" inputcount="2">
      <PortInfo index="0" default="False" />
      <PortInfo index="1" default="False" />
      <Script>import clr
clr.AddReference("ProtoGeometry")
from Autodesk.DesignScript.Geometry import *

LineBestFit = Line.ByBestFitThroughPoints

# Import RevitAPI
clr.AddReference("RevitAPI")
from Autodesk.Revit.DB import *
clr.AddReference("RevitAPIUI")
from Autodesk.Revit.UI import TaskDialog
# Import DocumentManager and TransactionManager
clr.AddReference("RevitServices")
from RevitServices.Persistence import DocumentManager
from RevitServices.Transactions import TransactionManager
# Import ToProtoType, ToRevitType geometry conversion extension methods
clr.AddReference("RevitNodes")
import Revit
clr.ImportExtensions(Revit.GeometryConversion)

import math

doc = DocumentManager.Instance.CurrentDBDocument
uiapp = DocumentManager.Instance.CurrentUIApplication
app = uiapp.Application


beam = UnwrapElement(IN[0])
duct = UnwrapElement(IN[1])
dynamoBeams = IN[0]


def GetElemType(e):
	try:
		elemType = doc.GetElement(e.GetTypeId())
		return elemType
	except:
		pass
		return None

def GetParamValue(eType, pName):
	paramValue = None
	for i in eType.Parameters:
		if i.Definition.Name == pName:
			paramValue = i.AsValueString()
			break
		else:
			continue
	return paramValue


def GetParam(element, name):
	p = element.get_Parameter(name)	
	if p.StorageType == StorageType.String:
		return p.AsString()
	elif p.StorageType == StorageType.ElementId:
		elem = doc.GetElement(p.AsElementId())
		return elem
	elif p.StorageType == StorageType.Double:
		ProjectUnits = p.DisplayUnitType
		newval = UnitUtils.ConvertFromInternalUnits(p.AsDouble(),ProjectUnits)
		return newval
	else:
		return p.AsInteger()

def GetEndPoints(beam):
	return [beam.Location.Curve.GetEndPoint(0).ToPoint(), beam.Location.Curve.GetEndPoint(1).ToPoint()]


def PointXYDistance(Pt0, Pt1):
	distance = math.pow((math.pow((Pt0.X-Pt1.X),2) + math.pow((Pt0.Y-Pt1.Y),2)),0.5)
	return round(distance,0)

def beamRealCurve(element):
	vertex = element.Geometry()[0].Vertices
	pGeom = []
	for v in vertex:
		pGeom.append(v.PointGeometry)
	crv = LineBestFit(pGeom)	
	return crv
	

values = []
checks = []

for i in range(0,len(beam)):
	val = []
	values.append(val)
	che = []
	checks.append(che)
	for j in range(0,len(duct[i])):
		# BEAM PARAMETERS
		
		zOffset = GetParam(beam[i], BuiltInParameter.Z_OFFSET_VALUE) # NEGATIVE VALUE!
		
		beamZTop = GetEndPoints(beam[i])[0].Z + zOffset
		
		#beamEndPoint = GetEndPoints(beam)[1] NOT ACCURATE!
		
		beamStPoint = beamRealCurve(dynamoBeams[i]).StartPoint
		beamEndPoint = beamRealCurve(dynamoBeams[i]).EndPoint
		
		#length = round(GetParam(beam, BuiltInParameter.INSTANCE_LENGTH_PARAM),0) NOT NEEDED ANYMORE!
		
		#cutLength = round(GetParam(beam, BuiltInParameter.STRUCTURAL_FRAME_CUT_LENGTH),0) NOT NEEDED ANYMORE!
		
		#remainLength = length - cutLength NOT NEEDED ANYMORE!
		
		beamDepth = int(GetParamValue(GetElemType(beam[i]), "d"))
		
		
		# DUCT PARAMETERS
		
		ductWidth = int(GetParamValue(duct[i][j], "y"))
		
		ductHeight = int(GetParamValue(duct[i][j], "z"))
	
		ductCentroid = duct[i][j].Location.Point.ToPoint()
		
		
		# CHECKS 
		
		# 1. BEAM START POINT TO OPENING EDGE DISTANCE
		
		beamStOpeningEdgeDist = PointXYDistance(ductCentroid, beamStPoint) - ductWidth/2
		
		val.append(beamStOpeningEdgeDist)
		
		beamEndOpeningEdgeDist = PointXYDistance(ductCentroid, beamEndPoint) - ductWidth/2
		
		val.append(beamEndOpeningEdgeDist)
		
		# 2. DISTANCE FROM FLANGES
		
		distTopFlange = round(beamZTop - ductCentroid.Z - ductHeight/2,0)
		
		val.append(distTopFlange)
		
		distBotFlange = round(beamDepth - ductHeight - distTopFlange,0)
		
		val.append(distBotFlange)
		
		val.append(ductWidth)
		
		val.append(ductHeight)
		
		# 3. CHECKS
		
		checkA = beamStOpeningEdgeDist &gt; (2 * beamDepth or ductWidth)
		
		checkB = beamEndOpeningEdgeDist &gt; (2 * beamDepth or ductWidth)
		
		checkC = distTopFlange &gt; (0.25 * beamDepth)
		
		checkD = distBotFlange &gt; (0.25 * beamDepth)
		
		checkE = ductWidth &lt; beamDepth
		
		checkF = ductHeight &lt; (0.5 * beamDepth)
		
		che.append(checkA)
		che.append(checkB)
		che.append(checkC)
		che.append(checkD)
		che.append(checkE)
		che.append(checkF)
		
		


#names = ["beamStOpeningEdgeDist", "beamEndOpeningEdgeDist", "distTopFlange", "distBotFlange", "ductWidth", "ductHeight"]
#values = [beamStOpeningEdgeDist, beamEndOpeningEdgeDist, distTopFlange, distBotFlange, ductWidth, ductHeight]
#checks = [checkA, checkB, checkC, checkD, checkE, checkF]

#dict = [names, values, checks]

#OUT = map(list, zip(*dict))

OUT = values, checks
</Script>
    </PythonNodeModels.PythonNode>
    <Dynamo.Graph.Nodes.ZeroTouch.DSFunction guid="447ec7f8-8f19-4c8f-899c-a8363a1f4482" type="Dynamo.Graph.Nodes.ZeroTouch.DSFunction" nickname="List.Chop" x="3111.76596637689" y="93.1888781641344" isVisible="true" isUpstreamVisible="true" lacing="Longest" isSelectedInput="False" IsFrozen="false" isPinned="true" assembly="DSCoreNodes.dll" function="DSCore.List.Chop@var[]..[],int[]">
      <PortInfo index="0" default="False" useLevels="True" level="2" shouldKeepListStructure="False" />
      <PortInfo index="1" default="False" />
    </Dynamo.Graph.Nodes.ZeroTouch.DSFunction>
    <Dynamo.Graph.Nodes.CodeBlockNodeModel guid="0e14dc84-39a5-4405-9f3a-07155a5d33b0" type="Dynamo.Graph.Nodes.CodeBlockNodeModel" nickname="Code Block" x="2963.79729630798" y="164.778878555277" isVisible="true" isUpstreamVisible="true" lacing="Disabled" isSelectedInput="False" IsFrozen="false" isPinned="false" CodeText="6;" ShouldFocus="false" />
    <Dynamo.Graph.Nodes.CustomNodes.Function guid="543c4ce4-65bf-4252-8730-33419c99591c" type="Dynamo.Graph.Nodes.CustomNodes.Function" nickname="Duct Clash Check" x="2435.22761005515" y="1033.74174613215" isVisible="true" isUpstreamVisible="true" lacing="Longest" isSelectedInput="False" IsFrozen="false" isPinned="true">
      <PortInfo index="0" default="False" />
      <PortInfo index="1" default="False" />
      <ID value="0b22c6e1-1550-4023-8180-bec2378903cf" />
      <Name value="Duct Clash Check" />
      <Description value="Check Clash" />
      <Inputs>
        <Input value="Beams" />
        <Input value="Ducts" />
      </Inputs>
      <Outputs>
        <Output value="OUT" />
      </Outputs>
    </Dynamo.Graph.Nodes.CustomNodes.Function>
    <Dynamo.Nodes.DSModelElementsSelection guid="9fa38eff-7571-40c0-9a8c-8321554bbc0d" type="Dynamo.Nodes.DSModelElementsSelection" nickname="Select Model Elements" x="1949.75579231187" y="744.140882947266" isVisible="true" isUpstreamVisible="true" lacing="Disabled" isSelectedInput="True" IsFrozen="false" isPinned="true">
      <instance id="9e9a6a43-04ae-45dd-b6c5-16884893d438-0022e5ca" />
    </Dynamo.Nodes.DSModelElementsSelection>
    <Dynamo.Nodes.DSModelElementsSelection guid="5b39453d-d73b-488d-8e4d-307b6d12a33a" type="Dynamo.Nodes.DSModelElementsSelection" nickname="Select Model Elements" x="1991.7671004636" y="1024.98959068213" isVisible="true" isUpstreamVisible="true" lacing="Disabled" isSelectedInput="True" IsFrozen="false" isPinned="true">
      <instance id="96120126-4b6e-46e6-9a74-7ce695fcf789-0041823b" />
      <instance id="96120126-4b6e-46e6-9a74-7ce695fcf789-0041823c" />
    </Dynamo.Nodes.DSModelElementsSelection>
    <PythonNodeModels.PythonNode guid="379fb9b0-b5c0-4d20-8d1d-6a19ec4302c9" type="PythonNodeModels.PythonNode" nickname="Python Script" x="3495.17269977447" y="853.228142559854" isVisible="true" isUpstreamVisible="true" lacing="Disabled" isSelectedInput="False" IsFrozen="false" isPinned="true" inputcount="2">
      <PortInfo index="0" default="False" />
      <PortInfo index="1" default="False" />
      <Script>import clr
clr.AddReference("ProtoGeometry")
from Autodesk.DesignScript.Geometry import *

pt = Point.ByCoordinates

LineBestFit = Line.ByBestFitThroughPoints

# Import RevitAPI
clr.AddReference("RevitAPI")
from Autodesk.Revit.DB import *
clr.AddReference("RevitAPIUI")
from Autodesk.Revit.UI import TaskDialog
# Import DocumentManager and TransactionManager
clr.AddReference("RevitServices")
from RevitServices.Persistence import DocumentManager
from RevitServices.Transactions import TransactionManager
# Import ToProtoType, ToRevitType geometry conversion extension methods
clr.AddReference("RevitNodes")
import Revit
clr.ImportExtensions(Revit.GeometryConversion)

import math

doc = DocumentManager.Instance.CurrentDBDocument
uiapp = DocumentManager.Instance.CurrentUIApplication
app = uiapp.Application


beamList = UnwrapElement(IN[0])
ductList = UnwrapElement(IN[1])
dynamoBeams = IN[0]


def GetElemType(e):
	try:
		elemType = doc.GetElement(e.GetTypeId())
		return elemType
	except:
		pass
		return None

def GetParamValue(eType, pName):
	paramValue = None
	for i in eType.Parameters:
		if i.Definition.Name == pName:
			paramValue = i.AsValueString()
			break
		else:
			continue
	return paramValue


def GetParam(element, name):
	p = element.get_Parameter(name)	
	if p.StorageType == StorageType.String:
		return p.AsString()
	elif p.StorageType == StorageType.ElementId:
		elem = doc.GetElement(p.AsElementId())
		return elem
	elif p.StorageType == StorageType.Double:
		ProjectUnits = p.DisplayUnitType
		newval = UnitUtils.ConvertFromInternalUnits(p.AsDouble(),ProjectUnits)
		return newval
	else:
		return p.AsInteger()

def GetEndPoints(beam):
	return [beam.Location.Curve.GetEndPoint(0).ToPoint(), beam.Location.Curve.GetEndPoint(1).ToPoint()]


def PointXYDistance(Pt0, Pt1):
	distance = math.pow((math.pow((Pt0.X-Pt1.X),2) + math.pow((Pt0.Y-Pt1.Y),2)),0.5)
	return round(distance,0)

def beamRealCurve(element):
	vertex = element.Geometry()[0].Vertices
	pGeom = []
	for v in vertex:
		pGeom.append(v.PointGeometry)
	crv = LineBestFit(pGeom)	
	return crv
	

values = []
checks = []


class RectDuct:

	def __init__(self, Shape, Width, Height, Centroid, HostedBeam, Distance0, Distance1):
		self.Shape = "Rectangle"
		self.Width = Width
		self.Height = Height
		self.Centroid = Centroid
		self.HostedBeam = HostedBeam
		self.Distance0 = Distance0
		self.Distance1 = Distance1
	
	def printOut(self):
		return [self.Shape, self.Width, self.Height, self.Centroid, self.HostedBeam, self.Distance0, self.Distance1]
		
	def distance(self, point):
		return Geometry.DistanceTo(self.Centroid, point)
	
	def XYDistance(self, Pt1):
		distance = math.pow((math.pow((self.Centroid.X-Pt1.X),2) + math.pow((self.Centroid.Y-Pt1.Y),2)),0.5)
		return round(distance,0)
		
	def __getitem__(self, item):
		return getattr(self, item)
		

objDuct = []
keys = []

for i in range(0,len(beamList)):
	for j in range(0,len(ductList[i])):
		#if ductList[i][j].Name == "RectDuct":
			centroid = ductList[i][j].Location.Point.ToPoint()
			instance = RectDuct ( 	"Rectangle", 
									int(GetParamValue(ductList[i][j], "y")),
									int(GetParamValue(ductList[i][j], "z")),
									centroid, 
									beamList[i].Id, 
									int(PointXYDistance(centroid, GetEndPoints(beamList[i])[0])),
									int(PointXYDistance(centroid, GetEndPoints(beamList[i])[1]))
								)
			keys.append(instance.Distance0)
#			instance.Width = GetParamValue(ductList[i][j], "y")
			objDuct.append(instance)
		#else:
		#	objDuct.append("another duct")

sortedDucts = sorted(objDuct, key=lambda instance: instance["Distance0"]) 

OUT = [d.printOut() for d in sortedDucts]</Script>
    </PythonNodeModels.PythonNode>
    <PythonNodeModels.PythonNode guid="ee55b356-a8c3-405d-9742-b6f962988995" type="PythonNodeModels.PythonNode" nickname="Python Script" x="3181.14918275592" y="1180.53517025494" isVisible="true" isUpstreamVisible="true" lacing="Disabled" isSelectedInput="False" IsFrozen="false" isPinned="true" inputcount="1">
      <PortInfo index="0" default="False" />
      <Script>import clr
clr.AddReference('ProtoGeometry')
from Autodesk.DesignScript.Geometry import *

clr.AddReference('RevitServices')
import RevitServices
from RevitServices.Persistence import DocumentManager
from RevitServices.Transactions import TransactionManager
from System.Collections.Generic import *

clr.AddReference('RevitNodes')
import Revit
clr.ImportExtensions(Revit.Elements)

clr.AddReference('RevitAPI')
import Autodesk
from Autodesk.Revit.DB import *
from Autodesk.Revit.DB.Electrical import *
from Autodesk.Revit.DB import MEPSystem

clr.AddReference('DSCoreNodes')
import DSCore
from DSCore.List import *

#The inputs to this node will be stored as a list in the IN variables.

input = UnwrapElement(IN[0])

listElectComponents = []


for i in range(0, len(input)):
	electComponents = List[ElementId]()
	listElectComponents.append(electComponents)
	for j in range (0,len(input[i])):
		electComponents.Add(input[i][j].Id)


#Assign your output to the OUT variable.
OUT = listElectComponents
</Script>
    </PythonNodeModels.PythonNode>
    <Dynamo.Graph.Nodes.ZeroTouch.DSFunction guid="f5c23599-1536-441f-91b3-98d5d81ccb18" type="Dynamo.Graph.Nodes.ZeroTouch.DSFunction" nickname="Object.Type" x="3475.42500779193" y="1234.61283106264" isVisible="true" isUpstreamVisible="true" lacing="Shortest" isSelectedInput="False" IsFrozen="false" isPinned="true" assembly="DSCoreNodes.dll" function="DSCore.Object.Type@var">
      <PortInfo index="0" default="False" />
    </Dynamo.Graph.Nodes.ZeroTouch.DSFunction>
    <Dynamo.Graph.Nodes.CodeBlockNodeModel guid="bf49876e-910f-4c37-8227-79912153a776" type="Dynamo.Graph.Nodes.CodeBlockNodeModel" nickname="Code Block" x="2852.59607960626" y="712.325293422242" isVisible="true" isUpstreamVisible="true" lacing="Disabled" isSelectedInput="False" IsFrozen="false" isPinned="true" CodeText="{a};" ShouldFocus="false">
      <PortInfo index="0" default="False" />
    </Dynamo.Graph.Nodes.CodeBlockNodeModel>
    <Dynamo.Graph.Nodes.CodeBlockNodeModel guid="22b352ae-65b8-4b6d-89b4-dddf69d812ba" type="Dynamo.Graph.Nodes.CodeBlockNodeModel" nickname="Code Block" x="2803.44573905243" y="912.680019953493" isVisible="true" isUpstreamVisible="true" lacing="Disabled" isSelectedInput="False" IsFrozen="false" isPinned="true" CodeText="{b};" ShouldFocus="false">
      <PortInfo index="0" default="False" />
    </Dynamo.Graph.Nodes.CodeBlockNodeModel>
    <PythonNodeModels.PythonNode guid="ffb5a005-577c-4de4-8222-c4ec12e469cb" type="PythonNodeModels.PythonNode" nickname="Python Script" x="2889.47728883164" y="1320.91467240055" isVisible="true" isUpstreamVisible="true" lacing="Disabled" isSelectedInput="False" IsFrozen="false" isPinned="true" inputcount="1">
      <PortInfo index="0" default="False" />
      <Script>import clr
clr.AddReference('ProtoGeometry')
from Autodesk.DesignScript.Geometry import *

clr.AddReference('RevitServices')
import RevitServices
from RevitServices.Persistence import DocumentManager
from RevitServices.Transactions import TransactionManager
from System.Collections.Generic import *

clr.AddReference('RevitNodes')
import Revit
clr.ImportExtensions(Revit.Elements)

clr.AddReference('RevitAPI')
import Autodesk
from Autodesk.Revit.DB import *
from Autodesk.Revit.DB.Electrical import *
from Autodesk.Revit.DB import MEPSystem

clr.AddReference('DSCoreNodes')
import DSCore
from DSCore.List import *

#The inputs to this node will be stored as a list in the IN variables.

input = UnwrapElement(IN[0])

list = []

class me():
	pass


class Rev():
    def __init__(self, initval=0, name='var'):
        self.val = initval
        self.name = name


io = me()

io.age = 34
io.name = "giovann"


tu = me()

tu.age = 45
tu.Name = "serg"

ei = Rev()


#Assign your output to the OUT variable.
OUT = io.name, tu.Name</Script>
    </PythonNodeModels.PythonNode>
    <PythonNodeModels.PythonNode guid="0d7138be-2051-4580-ba6f-22e29c75f867" type="PythonNodeModels.PythonNode" nickname="Python Script" x="3163.06568115624" y="1323.39581386629" isVisible="true" isUpstreamVisible="true" lacing="Disabled" isSelectedInput="False" IsFrozen="false" isPinned="true" inputcount="1">
      <PortInfo index="0" default="False" />
      <Script>import clr
clr.AddReference('ProtoGeometry')
from Autodesk.DesignScript.Geometry import *
#The inputs to this node will be stored as a list in the IN variables.

list = IN[0]


class Shape:

    def __init__(self, x, y):
        self.x = x
        self.y = y
        self.description = "This shape has not been described yet"
        self.author = "Nobody has claimed to make this shape yet"

    def area(self):
        return self.x * self.y

    def perimeter(self):
        return 2 * self.x + 2 * self.y

    def describe(self, text):
        self.description = text

    def authorName(self, text):
        self.author = text

    def scaleSize(self, scale):
        self.x = self.x * scale
        self.y = self.y * scale


rect = Shape(10,45)

#Assign your output to the OUT variable.
OUT = rect</Script>
    </PythonNodeModels.PythonNode>
    <Dynamo.Graph.Nodes.ZeroTouch.DSFunction guid="714ab8a1-ba16-4231-84f3-42ac40e874e8" type="Dynamo.Graph.Nodes.ZeroTouch.DSFunction" nickname="StructuralFraming.Location" x="3101.13074525232" y="533.563851197968" isVisible="true" isUpstreamVisible="true" lacing="Shortest" isSelectedInput="False" IsFrozen="false" isPinned="false" assembly="RevitNodes.dll" function="Revit.Elements.StructuralFraming.Location">
      <PortInfo index="0" default="False" />
    </Dynamo.Graph.Nodes.ZeroTouch.DSFunction>
    <Dynamo.Graph.Nodes.ZeroTouch.DSFunction guid="45041672-8020-43c9-b884-55eb1928207b" type="Dynamo.Graph.Nodes.ZeroTouch.DSFunction" nickname="Curves.EndPoints" x="3491.06075008786" y="456.471672591516" isVisible="true" isUpstreamVisible="true" lacing="Shortest" isSelectedInput="False" IsFrozen="false" isPinned="true" assembly="..\AppData\Roaming\Dynamo\Dynamo Revit\1.3\packages\LunchBox for Dynamo\bin\LunchBox.dll" function="Geometry.Curves.EndPoints@Autodesk.DesignScript.Geometry.Curve">
      <PortInfo index="0" default="False" />
    </Dynamo.Graph.Nodes.ZeroTouch.DSFunction>
    <PythonNodeModels.PythonNode guid="92501503-9565-44eb-9cd0-28f7d1f20d15" type="PythonNodeModels.PythonNode" nickname="Python Script" x="3951.37926582493" y="596.131416443783" isVisible="true" isUpstreamVisible="true" lacing="Disabled" isSelectedInput="False" IsFrozen="false" isPinned="true" inputcount="1">
      <PortInfo index="0" default="False" />
      <Script>import clr
clr.AddReference('ProtoGeometry')
from Autodesk.DesignScript.Geometry import *
#The inputs to this node will be stored as a list in the IN variables.
dataEnteringNode = IN


a = [3941,1104,2602]

b = IN[0]

# vowels list
vowels = ['e', 'a', 'u', 'o', 'i']

# sort the vowels
student_tuples = [
    ('john', 'A', 15),
    ('jane', 'B', 12),
    ('dave', 'C', 10),
]

#Assign your output to the OUT variable.
OUT = sorted(student_tuples, key=lambda mar: mar[1]) </Script>
    </PythonNodeModels.PythonNode>
    <Dynamo.Graph.Nodes.ZeroTouch.DSFunction guid="37987469-345a-4513-9e39-82c6d142494f" type="Dynamo.Graph.Nodes.ZeroTouch.DSFunction" nickname="Object.Type" x="3857.5279179562" y="1021.81431570549" isVisible="true" isUpstreamVisible="true" lacing="Shortest" isSelectedInput="False" IsFrozen="false" isPinned="true" assembly="DSCoreNodes.dll" function="DSCore.Object.Type@var">
      <PortInfo index="0" default="False" />
    </Dynamo.Graph.Nodes.ZeroTouch.DSFunction>
    <Dynamo.Graph.Nodes.CodeBlockNodeModel guid="ead0ea18-aea3-473f-a2c2-c9287e03795f" type="Dynamo.Graph.Nodes.CodeBlockNodeModel" nickname="Code Block" x="3847.41263827845" y="885.691118032726" isVisible="true" isUpstreamVisible="true" lacing="Disabled" isSelectedInput="False" IsFrozen="false" isPinned="true" CodeText="a[1];" ShouldFocus="false">
      <PortInfo index="0" default="False" />
    </Dynamo.Graph.Nodes.CodeBlockNodeModel>
  </Elements>
  <Connectors>
    <Dynamo.Graph.Connectors.ConnectorModel start="74909603-d31f-454e-a5c1-60f50c5e7c17" start_index="0" end="bea7452d-1c0e-468f-b959-92dfd128d2db" end_index="0" portType="0" />
    <Dynamo.Graph.Connectors.ConnectorModel start="b45993f0-0ea7-421f-bc55-7540531e4b3c" start_index="0" end="b88378c8-ffce-4819-9584-16f96ecceb27" end_index="0" portType="0" />
    <Dynamo.Graph.Connectors.ConnectorModel start="b5998032-2c50-4da2-8bf4-23d225873212" start_index="0" end="bea7452d-1c0e-468f-b959-92dfd128d2db" end_index="1" portType="0" />
    <Dynamo.Graph.Connectors.ConnectorModel start="0441048c-b4f8-4b4c-b50f-48b608ee108d" start_index="0" end="b88378c8-ffce-4819-9584-16f96ecceb27" end_index="1" portType="0" />
    <Dynamo.Graph.Connectors.ConnectorModel start="bea7452d-1c0e-468f-b959-92dfd128d2db" start_index="0" end="f85789a3-7418-40a9-9dd7-7c6318f7ccbb" end_index="0" portType="0" />
    <Dynamo.Graph.Connectors.ConnectorModel start="b88378c8-ffce-4819-9584-16f96ecceb27" start_index="0" end="f85789a3-7418-40a9-9dd7-7c6318f7ccbb" end_index="1" portType="0" />
    <Dynamo.Graph.Connectors.ConnectorModel start="f85789a3-7418-40a9-9dd7-7c6318f7ccbb" start_index="0" end="447ec7f8-8f19-4c8f-899c-a8363a1f4482" end_index="0" portType="0" />
    <Dynamo.Graph.Connectors.ConnectorModel start="0e14dc84-39a5-4405-9f3a-07155a5d33b0" start_index="0" end="447ec7f8-8f19-4c8f-899c-a8363a1f4482" end_index="1" portType="0" />
    <Dynamo.Graph.Connectors.ConnectorModel start="9fa38eff-7571-40c0-9a8c-8321554bbc0d" start_index="0" end="543c4ce4-65bf-4252-8730-33419c99591c" end_index="0" portType="0" />
    <Dynamo.Graph.Connectors.ConnectorModel start="9fa38eff-7571-40c0-9a8c-8321554bbc0d" start_index="0" end="bf49876e-910f-4c37-8227-79912153a776" end_index="0" portType="0" />
    <Dynamo.Graph.Connectors.ConnectorModel start="5b39453d-d73b-488d-8e4d-307b6d12a33a" start_index="0" end="543c4ce4-65bf-4252-8730-33419c99591c" end_index="1" portType="0" />
    <Dynamo.Graph.Connectors.ConnectorModel start="5b39453d-d73b-488d-8e4d-307b6d12a33a" start_index="0" end="22b352ae-65b8-4b6d-89b4-dddf69d812ba" end_index="0" portType="0" />
    <Dynamo.Graph.Connectors.ConnectorModel start="379fb9b0-b5c0-4d20-8d1d-6a19ec4302c9" start_index="0" end="ead0ea18-aea3-473f-a2c2-c9287e03795f" end_index="0" portType="0" />
    <Dynamo.Graph.Connectors.ConnectorModel start="ee55b356-a8c3-405d-9742-b6f962988995" start_index="0" end="f5c23599-1536-441f-91b3-98d5d81ccb18" end_index="0" portType="0" />
    <Dynamo.Graph.Connectors.ConnectorModel start="bf49876e-910f-4c37-8227-79912153a776" start_index="0" end="379fb9b0-b5c0-4d20-8d1d-6a19ec4302c9" end_index="0" portType="0" />
    <Dynamo.Graph.Connectors.ConnectorModel start="bf49876e-910f-4c37-8227-79912153a776" start_index="0" end="714ab8a1-ba16-4231-84f3-42ac40e874e8" end_index="0" portType="0" />
    <Dynamo.Graph.Connectors.ConnectorModel start="22b352ae-65b8-4b6d-89b4-dddf69d812ba" start_index="0" end="ee55b356-a8c3-405d-9742-b6f962988995" end_index="0" portType="0" />
    <Dynamo.Graph.Connectors.ConnectorModel start="22b352ae-65b8-4b6d-89b4-dddf69d812ba" start_index="0" end="ffb5a005-577c-4de4-8222-c4ec12e469cb" end_index="0" portType="0" />
    <Dynamo.Graph.Connectors.ConnectorModel start="22b352ae-65b8-4b6d-89b4-dddf69d812ba" start_index="0" end="0d7138be-2051-4580-ba6f-22e29c75f867" end_index="0" portType="0" />
    <Dynamo.Graph.Connectors.ConnectorModel start="22b352ae-65b8-4b6d-89b4-dddf69d812ba" start_index="0" end="379fb9b0-b5c0-4d20-8d1d-6a19ec4302c9" end_index="1" portType="0" />
    <Dynamo.Graph.Connectors.ConnectorModel start="714ab8a1-ba16-4231-84f3-42ac40e874e8" start_index="0" end="45041672-8020-43c9-b884-55eb1928207b" end_index="0" portType="0" />
    <Dynamo.Graph.Connectors.ConnectorModel start="ead0ea18-aea3-473f-a2c2-c9287e03795f" start_index="0" end="92501503-9565-44eb-9cd0-28f7d1f20d15" end_index="0" portType="0" />
    <Dynamo.Graph.Connectors.ConnectorModel start="ead0ea18-aea3-473f-a2c2-c9287e03795f" start_index="0" end="37987469-345a-4513-9e39-82c6d142494f" end_index="0" portType="0" />
  </Connectors>
  <Notes />
  <Annotations>
    <Dynamo.Graph.Annotations.AnnotationModel guid="0dc8ad73-27d4-4484-b6ba-8ae0cd29527c" annotationText="this!" left="3485.17269977447" top="807.228142559854" width="144" height="165" fontSize="30" InitialTop="853.228142559854" InitialHeight="149" TextblockHeight="36" backgrouund="#FFC1D676">
      <Models ModelGuid="379fb9b0-b5c0-4d20-8d1d-6a19ec4302c9" />
    </Dynamo.Graph.Annotations.AnnotationModel>
  </Annotations>
  <Presets />
  <Cameras>
    <Camera Name="Background Preview" eyeX="-5430.921875" eyeY="1586.27380371094" eyeZ="-10344.62109375" lookX="8681.87890625" lookY="-1923.77368164063" lookZ="6829.35693359375" upX="-0.0342836007475853" upY="0.999048233032227" upZ="-0.0269682351499796" />
  </Cameras>
</Workspace>