<Workspace Version="1.3.0.875" X="-2029.69006546152" Y="-732.758859520137" zoom="0.617597914449308" ScaleFactor="1" Name="Home" Description="" RunType="Manual" RunPeriod="1000" HasRunWithoutCrash="True">
  <NamespaceResolutionMap />
  <Elements>
    <DSRevitNodesUI.ElementTypes guid="e26b377b-737d-4f79-a7bc-ffdcb53d8e1f" type="DSRevitNodesUI.ElementTypes" nickname="Element Types" x="434.221555434289" y="625.922533777415" isVisible="true" isUpstreamVisible="true" lacing="Disabled" isSelectedInput="True" IsFrozen="false" isPinned="false" index="119:FilledRegionType" />
    <DSRevitNodesUI.ElementsOfType guid="fbdb5907-9046-48c7-b886-c70f59a8cedc" type="DSRevitNodesUI.ElementsOfType" nickname="All Elements of Type" x="671.88199320237" y="626.395120688619" isVisible="true" isUpstreamVisible="true" lacing="Disabled" isSelectedInput="False" IsFrozen="false" isPinned="true">
      <PortInfo index="0" default="False" />
    </DSRevitNodesUI.ElementsOfType>
    <PythonNodeModels.PythonNode guid="6f43b4d0-2e1d-4249-a88c-d3d8ca650037" type="PythonNodeModels.PythonNode" nickname="Python Script" x="2749.35373775246" y="597.368709790098" isVisible="true" isUpstreamVisible="true" lacing="Disabled" isSelectedInput="False" IsFrozen="false" isPinned="true" inputcount="3">
      <PortInfo index="0" default="False" />
      <PortInfo index="1" default="False" />
      <PortInfo index="2" default="False" />
      <Script>import clr
clr.AddReference('ProtoGeometry')
from Autodesk.DesignScript.Geometry import *

# Import DocumentManager and TransactionManager
clr.AddReference("RevitServices")
import RevitServices
from RevitServices.Persistence import DocumentManager
from RevitServices.Transactions import TransactionManager

# Import RevitAPI
clr.AddReference("RevitAPI")
import Autodesk
from Autodesk.Revit.DB import *

doc = DocumentManager.Instance.CurrentDBDocument
uiapp = DocumentManager.Instance.CurrentUIApplication
app = uiapp.Application

def lineFromCrv(crv):
	start = crv.StartPoint
	end = crv.EndPoint
	a = XYZ(start.X,start.Y,start.Z)
	b = XYZ(end.X,end.Y,end.Z)
	return Autodesk.Revit.DB.Line.CreateBound(a,b)
	
regions = []
activeViewId = doc.ActiveView.Id;

TransactionManager.Instance.EnsureInTransaction(doc)

frt = UnwrapElement( IN[2] )
"""
for bound in IN[0]:
	profileLoops = []
	profileLoop = CurveLoop()
	#create filled region
	for crv in bound:
		profileLoop.Append(lineFromCrv(crv))
	profileLoops.Add(profileLoop)
	region = FilledRegion.Create(doc,frt[0].Id,activeViewId,profileLoops)
	regions.Add(region)
	"""
#End Transaction

stPts = UnwrapElement(IN[0])
endPts = UnwrapElement(IN[1])
profileLoops = []
profileLoop = CurveLoop()
	#create filled region
for i in range(0,len(stPts)):
	for j in range(0,len(stPts[i])):
		profileLoop.Append(Autodesk.Revit.DB.Line.CreateBound(XYZ(stPts[i][j].X,stPts[i][j].Y,stPts[i][j].Z),XYZ(endPts[i][j].X,endPts[i][j].Y,endPts[i][j].Z)))

TransactionManager.Instance.TransactionTaskDone()

#Assign your outputs to the OUT variable
OUT = profileLoop
</Script>
    </PythonNodeModels.PythonNode>
    <Dynamo.Graph.Nodes.CodeBlockNodeModel guid="cc1ec3e5-fd8e-496a-9998-8b705232276d" type="Dynamo.Graph.Nodes.CodeBlockNodeModel" nickname="Code Block" x="1150" y="613" isVisible="true" isUpstreamVisible="true" lacing="Disabled" isSelectedInput="False" IsFrozen="false" isPinned="true" CodeText="{a[0]};" ShouldFocus="false">
      <PortInfo index="0" default="False" />
    </Dynamo.Graph.Nodes.CodeBlockNodeModel>
    <Dynamo.Graph.Nodes.CodeBlockNodeModel guid="cf77df06-a25e-4d80-8b19-bb900ba47c74" type="Dynamo.Graph.Nodes.CodeBlockNodeModel" nickname="Code Block" x="1923.74005754794" y="550.89664633507" isVisible="true" isUpstreamVisible="true" lacing="Disabled" isSelectedInput="False" IsFrozen="false" isPinned="true" CodeText="{a};" ShouldFocus="false">
      <PortInfo index="0" default="False" />
    </Dynamo.Graph.Nodes.CodeBlockNodeModel>
    <Dynamo.Graph.Nodes.ZeroTouch.DSFunction guid="e6b8e1e6-6b17-4c7c-a922-fe26c12e147e" type="Dynamo.Graph.Nodes.ZeroTouch.DSFunction" nickname="Curve.StartPoint" x="2238.59277451377" y="684.846032825129" isVisible="true" isUpstreamVisible="true" lacing="Shortest" isSelectedInput="False" IsFrozen="false" isPinned="false" assembly="ProtoGeometry.dll" function="Autodesk.DesignScript.Geometry.Curve.StartPoint">
      <PortInfo index="0" default="False" />
    </Dynamo.Graph.Nodes.ZeroTouch.DSFunction>
    <Dynamo.Graph.Nodes.CustomNodes.Function guid="f77865f1-7702-4bb8-8f79-67b1bbb53f38" type="Dynamo.Graph.Nodes.CustomNodes.Function" nickname="Get Revit ActiveView" x="2768.19602410285" y="787.739284829046" isVisible="true" isUpstreamVisible="true" lacing="Shortest" isSelectedInput="True" IsFrozen="false" isPinned="false">
      <ID value="92960965-5bfc-41ab-9ceb-d61917dfe6c5" />
      <Name value="Get Revit ActiveView" />
      <Description value="Active View" />
      <Inputs />
      <Outputs>
        <Output value="Active.View" />
      </Outputs>
    </Dynamo.Graph.Nodes.CustomNodes.Function>
    <Dynamo.Nodes.DSModelElementsSelection guid="23ea1b5f-ba8a-4767-aca7-d08affc5bb06" type="Dynamo.Nodes.DSModelElementsSelection" nickname="Select Model Elements" x="2826.65783428909" y="1107.23891179491" isVisible="true" isUpstreamVisible="true" lacing="Disabled" isSelectedInput="True" IsFrozen="false" isPinned="false">
      <instance id="a38fb025-cca7-43ba-8e1f-625e277e4272-00000a39" />
      <instance id="a38fb025-cca7-43ba-8e1f-625e277e4272-00000a56" />
      <instance id="a38fb025-cca7-43ba-8e1f-625e277e4272-00000a7b" />
      <instance id="a38fb025-cca7-43ba-8e1f-625e277e4272-00000aa3" />
    </Dynamo.Nodes.DSModelElementsSelection>
    <Dynamo.Graph.Nodes.ZeroTouch.DSFunction guid="3ef720fe-ee96-4536-9add-1fd7e891849c" type="Dynamo.Graph.Nodes.ZeroTouch.DSFunction" nickname="Element.Curves" x="3339.00812613753" y="979.677678513313" isVisible="true" isUpstreamVisible="true" lacing="Shortest" isSelectedInput="False" IsFrozen="false" isPinned="true" assembly="RevitNodes.dll" function="Revit.Elements.Element.Curves">
      <PortInfo index="0" default="False" />
    </Dynamo.Graph.Nodes.ZeroTouch.DSFunction>
    <Dynamo.Graph.Nodes.ZeroTouch.DSFunction guid="1b693efa-2bf0-47cb-aef5-680f02eb9f5d" type="Dynamo.Graph.Nodes.ZeroTouch.DSFunction" nickname="Flatten" x="3602.42093942013" y="924.418436846684" isVisible="true" isUpstreamVisible="true" lacing="Shortest" isSelectedInput="False" IsFrozen="false" isPinned="false" assembly="BuiltIn" function="Flatten@var[]..[]">
      <PortInfo index="0" default="False" />
    </Dynamo.Graph.Nodes.ZeroTouch.DSFunction>
    <Dynamo.Graph.Nodes.CodeBlockNodeModel guid="4d4895ad-75a4-4a8f-9ccd-b86b564836c2" type="Dynamo.Graph.Nodes.CodeBlockNodeModel" nickname="Code Block" x="4270.77312365112" y="1139.78391095276" isVisible="true" isUpstreamVisible="true" lacing="Disabled" isSelectedInput="False" IsFrozen="false" isPinned="true" CodeText="a;" ShouldFocus="false">
      <PortInfo index="0" default="False" />
    </Dynamo.Graph.Nodes.CodeBlockNodeModel>
    <Dynamo.Graph.Nodes.ZeroTouch.DSFunction guid="d2b48462-38ab-4d04-a238-1e7dbb77aef0" type="Dynamo.Graph.Nodes.ZeroTouch.DSFunction" nickname="Curve.EndPoint" x="3631.64054937186" y="1019.3487781649" isVisible="true" isUpstreamVisible="true" lacing="Shortest" isSelectedInput="False" IsFrozen="false" isPinned="true" assembly="ProtoGeometry.dll" function="Autodesk.DesignScript.Geometry.Curve.EndPoint">
      <PortInfo index="0" default="False" />
    </Dynamo.Graph.Nodes.ZeroTouch.DSFunction>
    <Dynamo.Graph.Nodes.CustomNodes.Function guid="29ba664b-03c7-4feb-8a12-adf3dd185bde" type="Dynamo.Graph.Nodes.CustomNodes.Function" nickname="Get Revit ActiveView" x="3486.20985912476" y="644.091229119388" isVisible="true" isUpstreamVisible="true" lacing="Shortest" isSelectedInput="True" IsFrozen="false" isPinned="false">
      <ID value="92960965-5bfc-41ab-9ceb-d61917dfe6c5" />
      <Name value="Get Revit ActiveView" />
      <Description value="Active View" />
      <Inputs />
      <Outputs>
        <Output value="Active.View" />
      </Outputs>
    </Dynamo.Graph.Nodes.CustomNodes.Function>
    <PythonNodeModels.PythonNode guid="aab236aa-74cb-4221-b9ce-f98a6d16ce22" type="PythonNodeModels.PythonNode" nickname="Python Script" x="4605.47153658032" y="1443.03570718067" isVisible="true" isUpstreamVisible="true" lacing="Disabled" isSelectedInput="False" IsFrozen="false" isPinned="true" inputcount="2">
      <PortInfo index="0" default="False" />
      <PortInfo index="1" default="False" />
      <Script>import clr
clr.AddReference('ProtoGeometry')
from Autodesk.DesignScript.Geometry import *

# Import DocumentManager and TransactionManager
clr.AddReference("RevitServices")
import RevitServices
from RevitServices.Persistence import DocumentManager
from RevitServices.Transactions import TransactionManager

# Import RevitAPI
clr.AddReference("RevitAPI")
import Autodesk
from Autodesk.Revit.DB import *

doc = DocumentManager.Instance.CurrentDBDocument
uiapp = DocumentManager.Instance.CurrentUIApplication
app = uiapp.Application

def lineFromCrv(crv):
	start = crv.StartPoint
	end = crv.EndPoint
	a = XYZ(start.X,start.Y,start.Z)
	b = XYZ(end.X,end.Y,end.Z)
	return Autodesk.Revit.DB.Line.CreateBound(a,b)
	
regions = []
activeViewId = doc.ActiveView.Id;

TransactionManager.Instance.EnsureInTransaction(doc)

"""
for bound in IN[0]:
	profileLoops = []
	profileLoop = CurveLoop()
	#create filled region
	for crv in bound:
		profileLoop.Append(lineFromCrv(crv))
	profileLoops.Add(profileLoop)
	region = FilledRegion.Create(doc,frt[0].Id,activeViewId,profileLoops)
	regions.Add(region)
	"""
#End Transaction

pts = UnwrapElement(IN[0])
frt = UnwrapElement(IN[1])

profileLoops = []
profileLoop = CurveLoop()
profileLoops.Add(profileLoop)
	#create filled region
for i in range(0,len(pts)-1):
	profileLoop.Append(Autodesk.Revit.DB.Line.CreateBound(XYZ(pts[i].X,pts[i].Y,pts[i].Z),XYZ(pts[i+1].X,pts[i+1].Y,pts[i+1].Z)))

region = FilledRegion.Create(doc,frt[0].Id,activeViewId,profileLoops)
regions.Add(region)

TransactionManager.Instance.TransactionTaskDone()

#Assign your outputs to the OUT variable
OUT = regions
</Script>
    </PythonNodeModels.PythonNode>
    <PythonNodeModels.PythonNode guid="9bd3e8c0-d7dd-4d94-8d9c-34edec10be50" type="PythonNodeModels.PythonNode" nickname="Python Script" x="3947.63900473964" y="994.708151868931" isVisible="true" isUpstreamVisible="true" lacing="Disabled" isSelectedInput="False" IsFrozen="false" isPinned="true" inputcount="1">
      <PortInfo index="0" default="False" />
      <Script>list = IN[0]

list.append(list[0])

OUT = list</Script>
    </PythonNodeModels.PythonNode>
    <PythonNodeModels.PythonNode guid="90209eed-961b-4786-8a0e-a36938fb4daf" type="PythonNodeModels.PythonNode" nickname="Python Script" x="4413.18283208225" y="846.263504826093" isVisible="true" isUpstreamVisible="true" lacing="Disabled" isSelectedInput="False" IsFrozen="false" isPinned="true" inputcount="3">
      <PortInfo index="0" default="False" />
      <PortInfo index="1" default="False" />
      <PortInfo index="2" default="False" />
      <Script>import clr
clr.AddReference('ProtoGeometry')
from Autodesk.DesignScript.Geometry import *

# Import DocumentManager and TransactionManager
clr.AddReference("RevitServices")
import RevitServices
from RevitServices.Persistence import DocumentManager
from RevitServices.Transactions import TransactionManager

# Import RevitAPI
clr.AddReference("RevitAPI")
import Autodesk
from Autodesk.Revit.DB import *

doc = DocumentManager.Instance.CurrentDBDocument
uiapp = DocumentManager.Instance.CurrentUIApplication
app = uiapp.Application
	
regions = []
activeViewId = doc.ActiveView.Id;

TransactionManager.Instance.EnsureInTransaction(doc)

frt = UnwrapElement( IN[2] )

for bound in IN[0]:
	profileLoops = []
	profileLoop = CurveLoop()
	#create filled region
	for crv in bound:
		profileLoop.Append(lineFromCrv(crv))
	profileLoops.Add(profileLoop)
	region = FilledRegion.Create(doc,frt[0].Id,activeViewId,profileLoops)
	regions.Add(region)
	
#End Transaction

TransactionManager.Instance.TransactionTaskDone()

#Assign your outputs to the OUT variable
OUT = profileLoop
</Script>
    </PythonNodeModels.PythonNode>
    <PythonNodeModels.PythonNode guid="337262c5-b7c9-493b-8d6f-b44321e45769" type="PythonNodeModels.PythonNode" nickname="Python Script" x="4847.67428859888" y="1182.61027554632" isVisible="true" isUpstreamVisible="true" lacing="Disabled" isSelectedInput="False" IsFrozen="false" isPinned="true" inputcount="3">
      <PortInfo index="0" default="False" />
      <PortInfo index="1" default="False" />
      <PortInfo index="2" default="False" />
      <Script>import clr
clr.AddReference('ProtoGeometry')
from Autodesk.DesignScript.Geometry import *

# Import DocumentManager and TransactionManager
clr.AddReference("RevitServices")
import RevitServices
from RevitServices.Persistence import DocumentManager
from RevitServices.Transactions import TransactionManager

# Import RevitAPI
clr.AddReference("RevitAPI")
import Autodesk
from Autodesk.Revit.DB import *

doc = DocumentManager.Instance.CurrentDBDocument
uiapp = DocumentManager.Instance.CurrentUIApplication
app = uiapp.Application

def lineFromCrv(crv):
	start = crv.StartPoint
	end = crv.EndPoint
	a = XYZ(start.X,start.Y,start.Z)
	b = XYZ(end.X,end.Y,end.Z)
	return Autodesk.Revit.DB.Line.CreateBound(a,b)
	
regions = []
activeViewId = doc.ActiveView.Id;

TransactionManager.Instance.EnsureInTransaction(doc)

pts = UnwrapElement(IN[0])
innerPts = UnwrapElement(IN[1])

frt = UnwrapElement(IN[2])

profileLoops = []
outerProfileLoop = CurveLoop()
innerProfileLoop = CurveLoop()

profileLoops.Add(outerProfileLoop)
profileLoops.Add(innerProfileLoop)


#create filled region
for i in range(0,len(pts)-1):
	outerProfileLoop.Append(Autodesk.Revit.DB.Line.CreateBound(XYZ(pts[i].X,pts[i].Y,pts[i].Z),XYZ(pts[i+1].X,pts[i+1].Y,pts[i+1].Z)))

for i in range(0,len(innerPts)-1):
	innerProfileLoop.Append(Autodesk.Revit.DB.Line.CreateBound(XYZ(innerPts[i].X,innerPts[i].Y,innerPts[i].Z),XYZ(innerPts[i+1].X,innerPts[i+1].Y,innerPts[i+1].Z)))


region = FilledRegion.Create(doc,frt[0].Id,activeViewId,profileLoops)
regions.Add(region)

TransactionManager.Instance.TransactionTaskDone()

#Assign your outputs to the OUT variable
OUT = regions, profileLoops
</Script>
    </PythonNodeModels.PythonNode>
    <Dynamo.Nodes.DSModelElementsSelection guid="3182cd0d-21b4-4289-9777-5355cec0ade2" type="Dynamo.Nodes.DSModelElementsSelection" nickname="Select Model Elements" x="2944.42092728774" y="1528.29136505214" isVisible="true" isUpstreamVisible="true" lacing="Disabled" isSelectedInput="True" IsFrozen="false" isPinned="false">
      <instance id="a38fb025-cca7-43ba-8e1f-625e277e4272-000013c2" />
      <instance id="a38fb025-cca7-43ba-8e1f-625e277e4272-000013d6" />
      <instance id="a38fb025-cca7-43ba-8e1f-625e277e4272-000013f9" />
      <instance id="a38fb025-cca7-43ba-8e1f-625e277e4272-00001418" />
    </Dynamo.Nodes.DSModelElementsSelection>
    <Dynamo.Graph.Nodes.ZeroTouch.DSFunction guid="55d1683d-7d2a-4944-98de-4c9e602a962b" type="Dynamo.Graph.Nodes.ZeroTouch.DSFunction" nickname="Flatten" x="3743.0035436218" y="1473.99479044684" isVisible="true" isUpstreamVisible="true" lacing="Shortest" isSelectedInput="False" IsFrozen="false" isPinned="false" assembly="BuiltIn" function="Flatten@var[]..[]">
      <PortInfo index="0" default="False" />
    </Dynamo.Graph.Nodes.ZeroTouch.DSFunction>
    <Dynamo.Graph.Nodes.ZeroTouch.DSFunction guid="b582a5ac-87b2-4d6f-a10e-69cb944ec873" type="Dynamo.Graph.Nodes.ZeroTouch.DSFunction" nickname="Element.Curves" x="3474.00994382109" y="1527.24173564786" isVisible="true" isUpstreamVisible="true" lacing="Shortest" isSelectedInput="False" IsFrozen="false" isPinned="true" assembly="RevitNodes.dll" function="Revit.Elements.Element.Curves">
      <PortInfo index="0" default="False" />
    </Dynamo.Graph.Nodes.ZeroTouch.DSFunction>
    <Dynamo.Graph.Nodes.ZeroTouch.DSFunction guid="491647ff-295f-4ec7-b1a5-af2f08c049d0" type="Dynamo.Graph.Nodes.ZeroTouch.DSFunction" nickname="Curve.EndPoint" x="3977.88041361372" y="1474.15527502561" isVisible="true" isUpstreamVisible="true" lacing="Shortest" isSelectedInput="False" IsFrozen="false" isPinned="true" assembly="ProtoGeometry.dll" function="Autodesk.DesignScript.Geometry.Curve.EndPoint">
      <PortInfo index="0" default="False" />
    </Dynamo.Graph.Nodes.ZeroTouch.DSFunction>
    <PythonNodeModels.PythonNode guid="2b0b6e0b-0cc4-446a-b6f1-b76d19ec7783" type="PythonNodeModels.PythonNode" nickname="Python Script" x="4259.14783800516" y="1465.10968844626" isVisible="true" isUpstreamVisible="true" lacing="Disabled" isSelectedInput="False" IsFrozen="false" isPinned="true" inputcount="1">
      <PortInfo index="0" default="False" />
      <Script>list = IN[0]

list.append(list[0])

OUT = list</Script>
    </PythonNodeModels.PythonNode>
    <Dynamo.Graph.Nodes.CustomNodes.Function guid="6998596f-ffa3-41af-b3ff-d67f806df3c3" type="Dynamo.Graph.Nodes.CustomNodes.Function" nickname="Group Curves" x="3713.92553371525" y="1900.74739742227" isVisible="true" isUpstreamVisible="true" lacing="Shortest" isSelectedInput="False" IsFrozen="false" isPinned="false">
      <PortInfo index="0" default="False" />
      <ID value="c84855d4-eb7e-4574-86a5-04867486df63" />
      <Name value="Group Curves" />
      <Description value="This node will take any input of flat list of curves and group them into sublists containing &quot;joinable&quot; curves that is continous curves. They might form closed curves or open curves. Use PolyCurve.ByJoinedCurves to convert output groups of curves into single PolyCurves" />
      <Inputs>
        <Input value="Curves" />
      </Inputs>
      <Outputs>
        <Output value="Grouped Curves" />
      </Outputs>
    </Dynamo.Graph.Nodes.CustomNodes.Function>
    <Dynamo.Nodes.DSModelElementsSelection guid="8ae6a0d2-3dd8-41ed-bc8d-554dfacc98ef" type="Dynamo.Nodes.DSModelElementsSelection" nickname="Select Model Elements" x="3005.16049048656" y="1912.40122084052" isVisible="true" isUpstreamVisible="true" lacing="Disabled" isSelectedInput="True" IsFrozen="false" isPinned="false">
      <instance id="a38fb025-cca7-43ba-8e1f-625e277e4272-000013c2" />
      <instance id="a38fb025-cca7-43ba-8e1f-625e277e4272-000013d6" />
      <instance id="a38fb025-cca7-43ba-8e1f-625e277e4272-000013f9" />
      <instance id="a38fb025-cca7-43ba-8e1f-625e277e4272-00001418" />
      <instance id="a38fb025-cca7-43ba-8e1f-625e277e4272-00001531" />
      <instance id="a38fb025-cca7-43ba-8e1f-625e277e4272-00001547" />
      <instance id="a38fb025-cca7-43ba-8e1f-625e277e4272-0000155c" />
      <instance id="a38fb025-cca7-43ba-8e1f-625e277e4272-00001577" />
      <instance id="a38fb025-cca7-43ba-8e1f-625e277e4272-000017d1" />
      <instance id="a38fb025-cca7-43ba-8e1f-625e277e4272-000017f0" />
      <instance id="a38fb025-cca7-43ba-8e1f-625e277e4272-0000180e" />
      <instance id="a38fb025-cca7-43ba-8e1f-625e277e4272-0000182b" />
      <instance id="a38fb025-cca7-43ba-8e1f-625e277e4272-00001843" />
      <instance id="a38fb025-cca7-43ba-8e1f-625e277e4272-00001863" />
      <instance id="a38fb025-cca7-43ba-8e1f-625e277e4272-00001876" />
    </Dynamo.Nodes.DSModelElementsSelection>
    <Dynamo.Graph.Nodes.ZeroTouch.DSFunction guid="cf3e24a7-a286-40df-8b63-5a94342128ae" type="Dynamo.Graph.Nodes.ZeroTouch.DSFunction" nickname="Flatten" x="3627.03682008501" y="2046.6452607265" isVisible="true" isUpstreamVisible="true" lacing="Shortest" isSelectedInput="False" IsFrozen="false" isPinned="false" assembly="BuiltIn" function="Flatten@var[]..[]">
      <PortInfo index="0" default="False" />
    </Dynamo.Graph.Nodes.ZeroTouch.DSFunction>
    <Dynamo.Graph.Nodes.ZeroTouch.DSFunction guid="58ae538d-d6b9-470e-bb74-af1514764648" type="Dynamo.Graph.Nodes.ZeroTouch.DSFunction" nickname="Element.Curves" x="3358.0432202843" y="2099.89220592752" isVisible="true" isUpstreamVisible="true" lacing="Shortest" isSelectedInput="False" IsFrozen="false" isPinned="true" assembly="RevitNodes.dll" function="Revit.Elements.Element.Curves">
      <PortInfo index="0" default="False" />
    </Dynamo.Graph.Nodes.ZeroTouch.DSFunction>
    <Dynamo.Graph.Nodes.ZeroTouch.DSFunction guid="c7153c51-0b60-4c42-8008-6bb703b1934b" type="Dynamo.Graph.Nodes.ZeroTouch.DSFunction" nickname="Curve.EndPoint" x="4122.14250619788" y="1883.62387542123" isVisible="true" isUpstreamVisible="true" lacing="Shortest" isSelectedInput="False" IsFrozen="false" isPinned="true" assembly="ProtoGeometry.dll" function="Autodesk.DesignScript.Geometry.Curve.EndPoint">
      <PortInfo index="0" default="False" />
    </Dynamo.Graph.Nodes.ZeroTouch.DSFunction>
    <PythonNodeModels.PythonNode guid="3dbdceeb-5f8f-4fde-9eca-d7d10fcf6604" type="PythonNodeModels.PythonNode" nickname="Python Script" x="4487.66391905218" y="1880.8658999212" isVisible="true" isUpstreamVisible="true" lacing="Disabled" isSelectedInput="False" IsFrozen="false" isPinned="true" inputcount="1">
      <PortInfo index="0" default="False" />
      <Script>list = IN[0]

for i in range(0,len(list)):
	list[i].append(list[i][0])
	
OUT = list</Script>
    </PythonNodeModels.PythonNode>
    <PythonNodeModels.PythonNode guid="4ad064a2-30e9-40c8-9ec8-a90db058e3e7" type="PythonNodeModels.PythonNode" nickname="Python Script" x="4993.72036018849" y="1850.64604888163" isVisible="true" isUpstreamVisible="true" lacing="Disabled" isSelectedInput="False" IsFrozen="false" isPinned="true" inputcount="3">
      <PortInfo index="0" default="False" />
      <PortInfo index="1" default="False" />
      <PortInfo index="2" default="False" />
      <Script>import clr
clr.AddReference('ProtoGeometry')
from Autodesk.DesignScript.Geometry import *

# Import DocumentManager and TransactionManager
clr.AddReference("RevitServices")
import RevitServices
from RevitServices.Persistence import DocumentManager
from RevitServices.Transactions import TransactionManager

# Import RevitAPI
clr.AddReference("RevitAPI")
import Autodesk
from Autodesk.Revit.DB import *

doc = DocumentManager.Instance.CurrentDBDocument
uiapp = DocumentManager.Instance.CurrentUIApplication
app = uiapp.Application


regions = []
activeViewId = doc.ActiveView.Id;

TransactionManager.Instance.EnsureInTransaction(doc)

pts = UnwrapElement(IN[0])
innerPts = UnwrapElement(IN[1])

frt = UnwrapElement(IN[2])

profileLoops = []
outerProfileLoop = CurveLoop()
#innerProfileLoop = CurveLoop()

profileLoops.Add(outerProfileLoop)
#profileLoops.Add(innerProfileLoop)


#create filled region
for i in range(0,len(pts)-1):
	outerProfileLoop.Append(Autodesk.Revit.DB.Line.CreateBound(XYZ(pts[i].X,pts[i].Y,pts[i].Z),XYZ(pts[i+1].X,pts[i+1].Y,pts[i+1].Z)))

for j in range(0,len(innerPts)):
	innerProfileLoop = CurveLoop()
	profileLoops.Add(innerProfileLoop)
	for i in range(0,len(innerPts[j])-1):
		innerProfileLoop.Append(Autodesk.Revit.DB.Line.CreateBound(XYZ(innerPts[j][i].X,innerPts[j][i].Y,innerPts[j][i].Z),XYZ(innerPts[j][i+1].X,innerPts[j][i+1].Y,innerPts[j][i+1].Z)))


region = FilledRegion.Create(doc,frt[0].Id,activeViewId,profileLoops)
regions.Add(region)

TransactionManager.Instance.TransactionTaskDone()

#Assign your outputs to the OUT variable
OUT = regions
</Script>
    </PythonNodeModels.PythonNode>
  </Elements>
  <Connectors>
    <Dynamo.Graph.Connectors.ConnectorModel start="e26b377b-737d-4f79-a7bc-ffdcb53d8e1f" start_index="0" end="fbdb5907-9046-48c7-b886-c70f59a8cedc" end_index="0" portType="0" />
    <Dynamo.Graph.Connectors.ConnectorModel start="fbdb5907-9046-48c7-b886-c70f59a8cedc" start_index="0" end="cc1ec3e5-fd8e-496a-9998-8b705232276d" end_index="0" portType="0" />
    <Dynamo.Graph.Connectors.ConnectorModel start="cc1ec3e5-fd8e-496a-9998-8b705232276d" start_index="0" end="4d4895ad-75a4-4a8f-9ccd-b86b564836c2" end_index="0" portType="0" />
    <Dynamo.Graph.Connectors.ConnectorModel start="cf77df06-a25e-4d80-8b19-bb900ba47c74" start_index="0" end="e6b8e1e6-6b17-4c7c-a922-fe26c12e147e" end_index="0" portType="0" />
    <Dynamo.Graph.Connectors.ConnectorModel start="e6b8e1e6-6b17-4c7c-a922-fe26c12e147e" start_index="0" end="6f43b4d0-2e1d-4249-a88c-d3d8ca650037" end_index="0" portType="0" />
    <Dynamo.Graph.Connectors.ConnectorModel start="e6b8e1e6-6b17-4c7c-a922-fe26c12e147e" start_index="0" end="90209eed-961b-4786-8a0e-a36938fb4daf" end_index="0" portType="0" />
    <Dynamo.Graph.Connectors.ConnectorModel start="23ea1b5f-ba8a-4767-aca7-d08affc5bb06" start_index="0" end="3ef720fe-ee96-4536-9add-1fd7e891849c" end_index="0" portType="0" />
    <Dynamo.Graph.Connectors.ConnectorModel start="3ef720fe-ee96-4536-9add-1fd7e891849c" start_index="0" end="1b693efa-2bf0-47cb-aef5-680f02eb9f5d" end_index="0" portType="0" />
    <Dynamo.Graph.Connectors.ConnectorModel start="1b693efa-2bf0-47cb-aef5-680f02eb9f5d" start_index="0" end="d2b48462-38ab-4d04-a238-1e7dbb77aef0" end_index="0" portType="0" />
    <Dynamo.Graph.Connectors.ConnectorModel start="4d4895ad-75a4-4a8f-9ccd-b86b564836c2" start_index="0" end="90209eed-961b-4786-8a0e-a36938fb4daf" end_index="2" portType="0" />
    <Dynamo.Graph.Connectors.ConnectorModel start="4d4895ad-75a4-4a8f-9ccd-b86b564836c2" start_index="0" end="4ad064a2-30e9-40c8-9ec8-a90db058e3e7" end_index="2" portType="0" />
    <Dynamo.Graph.Connectors.ConnectorModel start="d2b48462-38ab-4d04-a238-1e7dbb77aef0" start_index="0" end="9bd3e8c0-d7dd-4d94-8d9c-34edec10be50" end_index="0" portType="0" />
    <Dynamo.Graph.Connectors.ConnectorModel start="9bd3e8c0-d7dd-4d94-8d9c-34edec10be50" start_index="0" end="337262c5-b7c9-493b-8d6f-b44321e45769" end_index="0" portType="0" />
    <Dynamo.Graph.Connectors.ConnectorModel start="9bd3e8c0-d7dd-4d94-8d9c-34edec10be50" start_index="0" end="4ad064a2-30e9-40c8-9ec8-a90db058e3e7" end_index="0" portType="0" />
    <Dynamo.Graph.Connectors.ConnectorModel start="3182cd0d-21b4-4289-9777-5355cec0ade2" start_index="0" end="b582a5ac-87b2-4d6f-a10e-69cb944ec873" end_index="0" portType="0" />
    <Dynamo.Graph.Connectors.ConnectorModel start="55d1683d-7d2a-4944-98de-4c9e602a962b" start_index="0" end="491647ff-295f-4ec7-b1a5-af2f08c049d0" end_index="0" portType="0" />
    <Dynamo.Graph.Connectors.ConnectorModel start="b582a5ac-87b2-4d6f-a10e-69cb944ec873" start_index="0" end="55d1683d-7d2a-4944-98de-4c9e602a962b" end_index="0" portType="0" />
    <Dynamo.Graph.Connectors.ConnectorModel start="491647ff-295f-4ec7-b1a5-af2f08c049d0" start_index="0" end="2b0b6e0b-0cc4-446a-b6f1-b76d19ec7783" end_index="0" portType="0" />
    <Dynamo.Graph.Connectors.ConnectorModel start="2b0b6e0b-0cc4-446a-b6f1-b76d19ec7783" start_index="0" end="337262c5-b7c9-493b-8d6f-b44321e45769" end_index="1" portType="0" />
    <Dynamo.Graph.Connectors.ConnectorModel start="2b0b6e0b-0cc4-446a-b6f1-b76d19ec7783" start_index="0" end="aab236aa-74cb-4221-b9ce-f98a6d16ce22" end_index="0" portType="0" />
    <Dynamo.Graph.Connectors.ConnectorModel start="6998596f-ffa3-41af-b3ff-d67f806df3c3" start_index="0" end="c7153c51-0b60-4c42-8008-6bb703b1934b" end_index="0" portType="0" />
    <Dynamo.Graph.Connectors.ConnectorModel start="8ae6a0d2-3dd8-41ed-bc8d-554dfacc98ef" start_index="0" end="58ae538d-d6b9-470e-bb74-af1514764648" end_index="0" portType="0" />
    <Dynamo.Graph.Connectors.ConnectorModel start="cf3e24a7-a286-40df-8b63-5a94342128ae" start_index="0" end="6998596f-ffa3-41af-b3ff-d67f806df3c3" end_index="0" portType="0" />
    <Dynamo.Graph.Connectors.ConnectorModel start="58ae538d-d6b9-470e-bb74-af1514764648" start_index="0" end="cf3e24a7-a286-40df-8b63-5a94342128ae" end_index="0" portType="0" />
    <Dynamo.Graph.Connectors.ConnectorModel start="c7153c51-0b60-4c42-8008-6bb703b1934b" start_index="0" end="3dbdceeb-5f8f-4fde-9eca-d7d10fcf6604" end_index="0" portType="0" />
    <Dynamo.Graph.Connectors.ConnectorModel start="3dbdceeb-5f8f-4fde-9eca-d7d10fcf6604" start_index="0" end="4ad064a2-30e9-40c8-9ec8-a90db058e3e7" end_index="1" portType="0" />
  </Connectors>
  <Notes>
    <Dynamo.Graph.Notes.NoteModel guid="24012bba-9339-4b8c-9c67-af476dcf889c" text="Append Pt[0] to the end" x="4473.71368480048" y="1839.21739839723" />
  </Notes>
  <Annotations />
  <Presets />
  <Cameras>
    <Camera Name="Background Preview" eyeX="-888.807556152344" eyeY="11164.5205078125" eyeZ="745.253967285156" lookX="3438.81396484375" lookY="-7325.95263671875" lookZ="-4787.490234375" upX="0.365554720163345" upY="0.77933794260025" upZ="-0.508922457695007" />
  </Cameras>
</Workspace>