<Workspace Version="1.2.3.592" X="-297.799928757872" Y="84.0638814990572" zoom="0.695616441301115" ScaleFactor="1" Name="Home" Description="" RunType="Manual" RunPeriod="1000" HasRunWithoutCrash="True">
  <NamespaceResolutionMap />
  <Elements>
    <Dynamo.Graph.Nodes.CustomNodes.Function guid="89468c89-e64f-48a4-b049-2029832b5373" type="Dynamo.Graph.Nodes.CustomNodes.Function" nickname="CurvesFromCADLayers" x="710" y="351.5" isVisible="true" isUpstreamVisible="true" lacing="Shortest" isSelectedInput="False" IsFrozen="false" isPinned="false">
      <PortInfo index="0" default="False" />
      <PortInfo index="1" default="True" />
      <PortInfo index="2" default="True" />
      <ID value="0eeb8f98-a56a-4c60-af50-994a0f209a37" />
      <Name value="CurvesFromCADLayers" />
      <Description value="Extract curves from a CAD link or import by layer name. Curves are organised into layer sublists. To create Revit Model Lines set the createModelLines input to true&#xD;&#xA;&#xD;&#xA;This node is also optimised to convert curve types that typically fail when using Revit.Elements.Element.Curves or Full Explode" />
      <Inputs>
        <Input value="importInstance" />
        <Input value="layerNames" />
        <Input value="createModelLines" />
      </Inputs>
      <Outputs>
        <Output value="curves" />
        <Output value="layerKeys" />
      </Outputs>
    </Dynamo.Graph.Nodes.CustomNodes.Function>
    <Dynamo.Graph.Nodes.CustomNodes.Function guid="bb0c535f-85ef-401d-8a3e-e655e259f46d" type="Dynamo.Graph.Nodes.CustomNodes.Function" nickname="CurvesFromCADLayers" x="693" y="606.5" isVisible="true" isUpstreamVisible="true" lacing="Shortest" isSelectedInput="False" IsFrozen="false" isPinned="true">
      <PortInfo index="0" default="False" />
      <PortInfo index="1" default="True" />
      <PortInfo index="2" default="True" />
      <ID value="0eeb8f98-a56a-4c60-af50-994a0f209a37" />
      <Name value="CurvesFromCADLayers" />
      <Description value="Extract curves from a CAD link or import by layer name. Curves are organised into layer sublists. To create Revit Model Lines set the createModelLines input to true&#xD;&#xA;&#xD;&#xA;This node is also optimised to convert curve types that typically fail when using Revit.Elements.Element.Curves or Full Explode" />
      <Inputs>
        <Input value="importInstance" />
        <Input value="layerNames" />
        <Input value="createModelLines" />
      </Inputs>
      <Outputs>
        <Output value="curves" />
        <Output value="layerKeys" />
      </Outputs>
    </Dynamo.Graph.Nodes.CustomNodes.Function>
    <Dynamo.Nodes.DSModelElementSelection guid="abf34152-4e46-465d-a910-e603297b39bc" type="Dynamo.Nodes.DSModelElementSelection" nickname="Select Model Element" x="280" y="374.5" isVisible="true" isUpstreamVisible="true" lacing="Disabled" isSelectedInput="True" IsFrozen="false" isPinned="false">
      <instance id="2183c0af-b511-434d-8f00-48fd1c9ac2e8-00000915" />
    </Dynamo.Nodes.DSModelElementSelection>
    <Dynamo.Graph.Nodes.CodeBlockNodeModel guid="e37c3f85-3190-45d7-84c2-b3eef73c03c0" type="Dynamo.Graph.Nodes.CodeBlockNodeModel" nickname="Code Block" x="512" y="452" isVisible="true" isUpstreamVisible="true" lacing="Disabled" isSelectedInput="False" IsFrozen="false" isPinned="false" CodeText="&quot;Layer 01&quot;;" ShouldFocus="false" />
    <Dynamo.Graph.Nodes.CodeBlockNodeModel guid="a5c03205-9444-4bd0-a78f-124812a9957c" type="Dynamo.Graph.Nodes.CodeBlockNodeModel" nickname="Code Block" x="492" y="660" isVisible="true" isUpstreamVisible="true" lacing="Disabled" isSelectedInput="False" IsFrozen="false" isPinned="false" CodeText="&quot;Layer 02&quot;;" ShouldFocus="false" />
    <Dynamo.Graph.Nodes.ZeroTouch.DSFunction guid="2449e30e-2da6-4139-b58b-c8d2115db625" type="Dynamo.Graph.Nodes.ZeroTouch.DSFunction" nickname="Geometry.Intersect" x="1694.36889112363" y="447.69480416835" isVisible="true" isUpstreamVisible="true" lacing="Longest" isSelectedInput="False" IsFrozen="false" isPinned="true" assembly="ProtoGeometry.dll" function="Autodesk.DesignScript.Geometry.Geometry.Intersect@Autodesk.DesignScript.Geometry.Geometry">
      <PortInfo index="0" default="False" />
      <PortInfo index="1" default="False" />
    </Dynamo.Graph.Nodes.ZeroTouch.DSFunction>
    <CoreNodeModels.Watch guid="a4ea6427-31d5-42bb-9fe8-f9dccf5afb1f" type="CoreNodeModels.Watch" nickname="Watch" x="1053.73073747405" y="151.444418413322" isVisible="true" isUpstreamVisible="true" lacing="Disabled" isSelectedInput="False" IsFrozen="false" isPinned="false">
      <PortInfo index="0" default="False" />
    </CoreNodeModels.Watch>
    <CoreNodeModels.Watch guid="d450d220-3eed-4c18-abc5-f6f12f1d558c" type="CoreNodeModels.Watch" nickname="Watch" x="1040.10939127561" y="617.869074219599" isVisible="true" isUpstreamVisible="true" lacing="Disabled" isSelectedInput="False" IsFrozen="false" isPinned="false">
      <PortInfo index="0" default="False" />
    </CoreNodeModels.Watch>
    <Dynamo.Graph.Nodes.ZeroTouch.DSFunction guid="e4db6311-45d0-47f2-9927-2fcb1391a078" type="Dynamo.Graph.Nodes.ZeroTouch.DSFunction" nickname="Flatten" x="1350.91638307338" y="332.834056656773" isVisible="true" isUpstreamVisible="true" lacing="Shortest" isSelectedInput="False" IsFrozen="false" isPinned="false" assembly="BuiltIn" function="Flatten@var[]..[]">
      <PortInfo index="0" default="False" />
    </Dynamo.Graph.Nodes.ZeroTouch.DSFunction>
    <Dynamo.Graph.Nodes.ZeroTouch.DSFunction guid="d64fec41-7eae-4448-85f2-86bf46e03832" type="Dynamo.Graph.Nodes.ZeroTouch.DSFunction" nickname="Flatten" x="1388.15031434624" y="548.355293913997" isVisible="true" isUpstreamVisible="true" lacing="Shortest" isSelectedInput="False" IsFrozen="false" isPinned="false" assembly="BuiltIn" function="Flatten@var[]..[]">
      <PortInfo index="0" default="False" />
    </Dynamo.Graph.Nodes.ZeroTouch.DSFunction>
  </Elements>
  <Connectors>
    <Dynamo.Graph.Connectors.ConnectorModel start="89468c89-e64f-48a4-b049-2029832b5373" start_index="0" end="a4ea6427-31d5-42bb-9fe8-f9dccf5afb1f" end_index="0" portType="0" />
    <Dynamo.Graph.Connectors.ConnectorModel start="bb0c535f-85ef-401d-8a3e-e655e259f46d" start_index="0" end="d450d220-3eed-4c18-abc5-f6f12f1d558c" end_index="0" portType="0" />
    <Dynamo.Graph.Connectors.ConnectorModel start="abf34152-4e46-465d-a910-e603297b39bc" start_index="0" end="89468c89-e64f-48a4-b049-2029832b5373" end_index="0" portType="0" />
    <Dynamo.Graph.Connectors.ConnectorModel start="abf34152-4e46-465d-a910-e603297b39bc" start_index="0" end="bb0c535f-85ef-401d-8a3e-e655e259f46d" end_index="0" portType="0" />
    <Dynamo.Graph.Connectors.ConnectorModel start="e37c3f85-3190-45d7-84c2-b3eef73c03c0" start_index="0" end="89468c89-e64f-48a4-b049-2029832b5373" end_index="1" portType="0" />
    <Dynamo.Graph.Connectors.ConnectorModel start="a5c03205-9444-4bd0-a78f-124812a9957c" start_index="0" end="bb0c535f-85ef-401d-8a3e-e655e259f46d" end_index="1" portType="0" />
    <Dynamo.Graph.Connectors.ConnectorModel start="a4ea6427-31d5-42bb-9fe8-f9dccf5afb1f" start_index="0" end="e4db6311-45d0-47f2-9927-2fcb1391a078" end_index="0" portType="0" />
    <Dynamo.Graph.Connectors.ConnectorModel start="d450d220-3eed-4c18-abc5-f6f12f1d558c" start_index="0" end="d64fec41-7eae-4448-85f2-86bf46e03832" end_index="0" portType="0" />
    <Dynamo.Graph.Connectors.ConnectorModel start="e4db6311-45d0-47f2-9927-2fcb1391a078" start_index="0" end="2449e30e-2da6-4139-b58b-c8d2115db625" end_index="0" portType="0" />
    <Dynamo.Graph.Connectors.ConnectorModel start="d64fec41-7eae-4448-85f2-86bf46e03832" start_index="0" end="2449e30e-2da6-4139-b58b-c8d2115db625" end_index="1" portType="0" />
  </Connectors>
  <Notes />
  <Annotations />
  <Presets />
  <Cameras>
    <Camera Name="Background Preview" eyeX="-26128.1144804105" eyeY="17105.5929932038" eyeZ="-737.256673747002" lookX="14392.5407006248" lookY="-20314.8248059281" lookZ="-9821.83917371658" upX="0.497095430943629" upY="0.798635510047293" upZ="-0.339230680550078" />
  </Cameras>
</Workspace>