<Workspace Version="1.3.1.1736" X="-270" Y="-99" zoom="1" ScaleFactor="1" Name="Home" Description="" RunType="Manual" RunPeriod="1000" HasRunWithoutCrash="True">
  <NamespaceResolutionMap />
  <Elements>
    <Dynamo.Graph.Nodes.CodeBlockNodeModel guid="df8a96c8-5c7c-4322-98bc-49e11af20f43" type="Dynamo.Graph.Nodes.CodeBlockNodeModel" nickname="Code Block" x="625" y="614" isVisible="true" isUpstreamVisible="true" lacing="Disabled" isSelectedInput="False" IsFrozen="false" isPinned="true" CodeText="1..16;" ShouldFocus="false" />
    <PythonNodeModels.PythonNode guid="d96028a1-e761-4442-808d-303bc540e046" type="PythonNodeModels.PythonNode" nickname="Python Script" x="839" y="610" isVisible="true" isUpstreamVisible="true" lacing="Disabled" isSelectedInput="False" IsFrozen="false" isPinned="true" inputcount="1">
      <PortInfo index="0" default="False" />
      <Script>import clr
clr.AddReference('ProtoGeometry')
from Autodesk.DesignScript.Geometry import *
#The inputs to this node will be stored as a list in the IN variables.
pts = IN[0]

subPt = []

for j in range(0,len(pts)/4):
	pt = []
	subPt.append(pt)
	for i in range(0,4):
		try:
			pt.append(pts.pop(0))
		except:
			"done"
	
#subPt.append(pts.pop(0))

#Assign your output to the OUT variable.
OUT = subPt</Script>
    </PythonNodeModels.PythonNode>
    <PythonNodeModels.PythonNode guid="2ca7b8fc-5335-4f47-b576-20fbdbce3df1" type="PythonNodeModels.PythonNode" nickname="Python Script" x="1085" y="611" isVisible="true" isUpstreamVisible="true" lacing="Disabled" isSelectedInput="False" IsFrozen="false" isPinned="true" inputcount="1">
      <PortInfo index="0" default="False" />
      <Script>import clr
clr.AddReference('ProtoGeometry')
from Autodesk.DesignScript.Geometry import *
#The inputs to this node will be stored as a list in the IN variables.
pts = IN[0]

subPt = []

for i in range(0,len(pts)):
	pt = []
	subPt.append(pt)
	for j in range(0,2):
		try:
			pt.append(pts[i].pop(0))
			pt.append(pts[i+1].pop(0))
		except:
			"done"
	
#subPt.append(pts.pop(0))

#Assign your output to the OUT variable.
OUT = subPt</Script>
    </PythonNodeModels.PythonNode>
  </Elements>
  <Connectors>
    <Dynamo.Graph.Connectors.ConnectorModel start="df8a96c8-5c7c-4322-98bc-49e11af20f43" start_index="0" end="d96028a1-e761-4442-808d-303bc540e046" end_index="0" portType="0" />
    <Dynamo.Graph.Connectors.ConnectorModel start="d96028a1-e761-4442-808d-303bc540e046" start_index="0" end="2ca7b8fc-5335-4f47-b576-20fbdbce3df1" end_index="0" portType="0" />
  </Connectors>
  <Notes />
  <Annotations />
  <Presets />
  <Cameras>
    <Camera Name="Background Preview" eyeX="-17" eyeY="24" eyeZ="50" lookX="12" lookY="-13" lookZ="-58" upX="0" upY="1" upZ="0" />
  </Cameras>
</Workspace>