<Workspace Version="1.3.1.1736" X="-156.39530905363" Y="-56.5679804559821" zoom="1.07925372895183" ScaleFactor="1" Name="Home" Description="" RunType="Manual" RunPeriod="1000" HasRunWithoutCrash="True">
  <NamespaceResolutionMap>
    <ClassMap partialName="Point" resolvedName="Autodesk.DesignScript.Geometry.Point" assemblyName="ProtoGeometry.dll" />
  </NamespaceResolutionMap>
  <Elements>
    <PythonNodeModels.PythonNode guid="e58c6665-d5c1-4b5c-8ed2-0976ba977670" type="PythonNodeModels.PythonNode" nickname="Python Script" x="314.617757198333" y="350.414742462527" isVisible="true" isUpstreamVisible="true" lacing="Disabled" isSelectedInput="False" IsFrozen="false" isPinned="true" inputcount="1">
      <PortInfo index="0" default="False" />
      <Script>import clr
import sys
sys.path.append(r'C:\Users\giovanni.brogiolo\Dropbox')

import dypy
  
OUT = dypy.summary</Script>
    </PythonNodeModels.PythonNode>
    <Dynamo.Graph.Nodes.CodeBlockNodeModel guid="6be2a7fd-c25e-49f9-ab0f-91db1962d1ed" type="Dynamo.Graph.Nodes.CodeBlockNodeModel" nickname="Code Block" x="501.51624983043" y="261.073433824527" isVisible="true" isUpstreamVisible="true" lacing="Disabled" isSelectedInput="False" IsFrozen="false" isPinned="false" CodeText="Point.ByCoordinates(x);" ShouldFocus="false">
      <PortInfo index="0" default="False" />
    </Dynamo.Graph.Nodes.CodeBlockNodeModel>
    <Dynamo.Graph.Nodes.CodeBlockNodeModel guid="0512ee98-494c-45ef-baaa-89ad24d3bd8d" type="Dynamo.Graph.Nodes.CodeBlockNodeModel" nickname="Code Block" x="760.51624983043" y="281.073433824527" isVisible="true" isUpstreamVisible="true" lacing="Disabled" isSelectedInput="False" IsFrozen="false" isPinned="false" CodeText="Point.ByCoordinates(x);" ShouldFocus="false">
      <PortInfo index="0" default="False" />
    </Dynamo.Graph.Nodes.CodeBlockNodeModel>
    <Dynamo.Graph.Nodes.CodeBlockNodeModel guid="59de7226-a630-4dbd-82ad-ae94c80e05f4" type="Dynamo.Graph.Nodes.CodeBlockNodeModel" nickname="Code Block" x="770.51624983043" y="291.073433824527" isVisible="true" isUpstreamVisible="true" lacing="Disabled" isSelectedInput="False" IsFrozen="false" isPinned="false" CodeText="Point.ByCoordinates(x);" ShouldFocus="false">
      <PortInfo index="0" default="False" />
    </Dynamo.Graph.Nodes.CodeBlockNodeModel>
  </Elements>
  <Connectors />
  <Notes />
  <Annotations />
  <Presets />
  <Cameras>
    <Camera Name="Background Preview" eyeX="-17" eyeY="24" eyeZ="50" lookX="12" lookY="-13" lookZ="-58" upX="0" upY="1" upZ="0" />
  </Cameras>
</Workspace>