<Workspace Version="1.3.0.875" X="-2589.99707328173" Y="64.8863540841533" zoom="0.667220486815514" ScaleFactor="1" Name="Home" Description="" RunType="Manual" RunPeriod="1000" HasRunWithoutCrash="True">
  <NamespaceResolutionMap />
  <Elements>
    <Dynamo.Graph.Nodes.ZeroTouch.DSFunction guid="2012bbb3-5949-47fd-8115-5757701a33fa" type="Dynamo.Graph.Nodes.ZeroTouch.DSFunction" nickname="Element.GetParameterValueByName" x="637.935007437518" y="162.212800854745" isVisible="true" isUpstreamVisible="true" lacing="Shortest" isSelectedInput="False" IsFrozen="false" isPinned="false" assembly="RevitNodes.dll" function="Revit.Elements.Element.GetParameterValueByName@string">
      <PortInfo index="0" default="False" />
      <PortInfo index="1" default="False" />
    </Dynamo.Graph.Nodes.ZeroTouch.DSFunction>
    <Dynamo.Graph.Nodes.CodeBlockNodeModel guid="78c5313b-68a1-47ac-8cd2-867212b668dc" type="Dynamo.Graph.Nodes.CodeBlockNodeModel" nickname="Code Block" x="334.935007437518" y="238.426134188078" isVisible="true" isUpstreamVisible="true" lacing="Disabled" isSelectedInput="False" IsFrozen="false" isPinned="false" CodeText="&quot;Ar_Espace de vente&quot;;" ShouldFocus="false" />
    <Dynamo.Graph.Nodes.ZeroTouch.DSFunction guid="69b444c5-f067-46ea-88e2-3a3c1ab2f74e" type="Dynamo.Graph.Nodes.ZeroTouch.DSFunction" nickname="==" x="1000.93500743752" y="214.212800854745" isVisible="true" isUpstreamVisible="true" lacing="Shortest" isSelectedInput="False" IsFrozen="false" isPinned="false" assembly="Operators" function="==@var[]..[],var[]..[]">
      <PortInfo index="0" default="False" />
      <PortInfo index="1" default="False" />
    </Dynamo.Graph.Nodes.ZeroTouch.DSFunction>
    <Dynamo.Graph.Nodes.CodeBlockNodeModel guid="736f40e2-60e7-4d30-a6d3-905c3c89d286" type="Dynamo.Graph.Nodes.CodeBlockNodeModel" nickname="Code Block" x="637.935007437518" y="296.426134188078" isVisible="true" isUpstreamVisible="true" lacing="Disabled" isSelectedInput="False" IsFrozen="false" isPinned="false" CodeText="1;" ShouldFocus="false" />
    <Dynamo.Graph.Nodes.ZeroTouch.DSFunction guid="57355397-5ef2-46c1-8896-624d235ba89d" type="Dynamo.Graph.Nodes.ZeroTouch.DSFunction" nickname="List.FilterByBoolMask" x="1269.93500743752" y="188.212800854745" isVisible="true" isUpstreamVisible="true" lacing="Shortest" isSelectedInput="False" IsFrozen="false" isPinned="false" assembly="DSCoreNodes.dll" function="DSCore.List.FilterByBoolMask@var[]..[],var[]..[]">
      <PortInfo index="0" default="False" />
      <PortInfo index="1" default="False" />
    </Dynamo.Graph.Nodes.ZeroTouch.DSFunction>
    <Dynamo.Graph.Nodes.CustomNodes.Function guid="ff375865-5b6c-49a7-8c84-f36963eac019" type="Dynamo.Graph.Nodes.CustomNodes.Function" nickname="Collector.PlacedRooms" x="334.935007437518" y="129.212800854745" isVisible="true" isUpstreamVisible="true" lacing="Shortest" isSelectedInput="False" IsFrozen="false" isPinned="false">
      <PortInfo index="0" default="True" />
      <ID value="e620b7b6-640d-435e-982a-15fc1eeb8bdb" />
      <Name value="Collector.PlacedRooms" />
      <Description value="This will collect placed rooms in current file." />
      <Inputs>
        <Input value="toggle" />
      </Inputs>
      <Outputs>
        <Output value="rooms" />
      </Outputs>
    </Dynamo.Graph.Nodes.CustomNodes.Function>
    <CoreNodeModels.Input.BoolSelector guid="7f2bd5f6-89ab-44bc-8f08-48fbf726a9de" type="CoreNodeModels.Input.BoolSelector" nickname="Boolean" x="105.935007437518" y="129.212800854745" isVisible="true" isUpstreamVisible="true" lacing="Disabled" isSelectedInput="True" IsFrozen="false" isPinned="false">
      <System.Boolean>True</System.Boolean>
    </CoreNodeModels.Input.BoolSelector>
    <Dynamo.Graph.Nodes.ZeroTouch.DSFunction guid="86d5b35b-93ab-41e1-85a5-8d9607ecdbd9" type="Dynamo.Graph.Nodes.ZeroTouch.DSFunction" nickname="Room.FinishBoundary" x="1756.57457614121" y="227.882969891264" isVisible="true" isUpstreamVisible="true" lacing="Shortest" isSelectedInput="False" IsFrozen="false" isPinned="true" assembly="RevitNodes.dll" function="Revit.Elements.Room.FinishBoundary">
      <PortInfo index="0" default="False" />
    </Dynamo.Graph.Nodes.ZeroTouch.DSFunction>
    <Dynamo.Graph.Nodes.CodeBlockNodeModel guid="61e8360f-75bc-4335-a2b7-c140b01ca510" type="Dynamo.Graph.Nodes.CodeBlockNodeModel" nickname="Code Block" x="4736.52792099631" y="209.893042867086" isVisible="true" isUpstreamVisible="true" lacing="Disabled" isSelectedInput="False" IsFrozen="false" isPinned="true" CodeText="a;" ShouldFocus="false">
      <PortInfo index="0" default="False" />
    </Dynamo.Graph.Nodes.CodeBlockNodeModel>
    <Dynamo.Graph.Nodes.CodeBlockNodeModel guid="5ae8f09b-3964-49ee-bc36-a27be54b3de3" type="Dynamo.Graph.Nodes.CodeBlockNodeModel" nickname="Code Block" x="4457.81865355997" y="210.682019250123" isVisible="true" isUpstreamVisible="true" lacing="Disabled" isSelectedInput="False" IsFrozen="false" isPinned="true" CodeText="{a[0]};" ShouldFocus="false">
      <PortInfo index="0" default="False" />
    </Dynamo.Graph.Nodes.CodeBlockNodeModel>
    <Dynamo.Graph.Nodes.CustomNodes.Function guid="da4cf1ad-bec2-4fca-8109-e755b58d5e13" type="Dynamo.Graph.Nodes.CustomNodes.Function" nickname="Group Curves" x="3774.52940392925" y="-686.315127173922" isVisible="true" isUpstreamVisible="true" lacing="Shortest" isSelectedInput="False" IsFrozen="false" isPinned="false">
      <PortInfo index="0" default="False" useLevels="True" level="2" shouldKeepListStructure="False" />
      <ID value="c84855d4-eb7e-4574-86a5-04867486df63" />
      <Name value="Group Curves" />
      <Description value="This node will take any input of flat list of curves and group them into sublists containing &quot;joinable&quot; curves that is continous curves. They might form closed curves or open curves. Use PolyCurve.ByJoinedCurves to convert output groups of curves into single PolyCurves" />
      <Inputs>
        <Input value="Curves" />
      </Inputs>
      <Outputs>
        <Output value="Grouped Curves" />
      </Outputs>
    </Dynamo.Graph.Nodes.CustomNodes.Function>
    <Dynamo.Graph.Nodes.ZeroTouch.DSFunction guid="816d1ea1-c3ce-4248-a6a2-89a0f71f15b1" type="Dynamo.Graph.Nodes.ZeroTouch.DSFunction" nickname="Flatten" x="4314.46852128113" y="-798.683974879463" isVisible="true" isUpstreamVisible="true" lacing="Shortest" isSelectedInput="False" IsFrozen="false" isPinned="false" assembly="BuiltIn" function="Flatten@var[]..[]">
      <PortInfo index="0" default="False" useLevels="True" level="2" shouldKeepListStructure="False" />
    </Dynamo.Graph.Nodes.ZeroTouch.DSFunction>
    <Dynamo.Graph.Nodes.ZeroTouch.DSFunction guid="1186684a-3b54-40ac-bafe-bbc8b97202d0" type="Dynamo.Graph.Nodes.ZeroTouch.DSFunction" nickname="Curve.EndPoint" x="4091.34229707037" y="-685.847770652417" isVisible="true" isUpstreamVisible="true" lacing="Shortest" isSelectedInput="False" IsFrozen="false" isPinned="false" assembly="ProtoGeometry.dll" function="Autodesk.DesignScript.Geometry.Curve.EndPoint">
      <PortInfo index="0" default="False" />
    </Dynamo.Graph.Nodes.ZeroTouch.DSFunction>
    <PythonNodeModels.PythonNode guid="cd0a305b-36c3-416b-bf16-8eb6aa38654c" type="PythonNodeModels.PythonNode" nickname="Python Script" x="4593.52143953404" y="-695.239616521834" isVisible="true" isUpstreamVisible="true" lacing="Disabled" isSelectedInput="False" IsFrozen="false" isPinned="false" inputcount="1">
      <PortInfo index="0" default="False" />
      <Script>list = IN[0]

for i in range(0,len(list)):
	list[i].append(list[i][0])
	
OUT = list</Script>
    </PythonNodeModels.PythonNode>
    <DSRevitNodesUI.ElementTypes guid="daf54c81-21e1-4270-a08c-642b5025e604" type="DSRevitNodesUI.ElementTypes" nickname="Element Types" x="3905.7554838848" y="213.911872749446" isVisible="true" isUpstreamVisible="true" lacing="Disabled" isSelectedInput="True" IsFrozen="false" isPinned="false" index="125:FilledRegionType" />
    <DSRevitNodesUI.ElementsOfType guid="3389c3d3-4554-4a95-9462-92f64b206cbf" type="DSRevitNodesUI.ElementsOfType" nickname="All Elements of Type" x="4143.41592165288" y="214.384459660656" isVisible="true" isUpstreamVisible="true" lacing="Disabled" isSelectedInput="False" IsFrozen="false" isPinned="true">
      <PortInfo index="0" default="False" />
    </DSRevitNodesUI.ElementsOfType>
    <PythonNodeModels.PythonNode guid="f543fd0e-4ec7-4cae-ab66-9f645e0ee72f" type="PythonNodeModels.PythonNode" nickname="Python Script" x="6306.24375310367" y="-185.826851064941" isVisible="true" isUpstreamVisible="true" lacing="Disabled" isSelectedInput="False" IsFrozen="true" isPinned="true" inputcount="3">
      <PortInfo index="0" default="False" />
      <PortInfo index="1" default="False" />
      <PortInfo index="2" default="False" />
      <Script>import clr
clr.AddReference('ProtoGeometry')
from Autodesk.DesignScript.Geometry import *

# Import DocumentManager and TransactionManager
clr.AddReference("RevitServices")
import RevitServices
from RevitServices.Persistence import DocumentManager
from RevitServices.Transactions import TransactionManager

# Import RevitAPI
clr.AddReference("RevitAPI")
import Autodesk
from Autodesk.Revit.DB import *

doc = DocumentManager.Instance.CurrentDBDocument
uiapp = DocumentManager.Instance.CurrentUIApplication
app = uiapp.Application


regions = []
activeViewId = doc.ActiveView.Id;

TransactionManager.Instance.EnsureInTransaction(doc)

pts = UnwrapElement(IN[0])
innerPts = UnwrapElement(IN[1])

frt = UnwrapElement(IN[2])


profileLoops = []
outerProfileLoop = CurveLoop()
#innerProfileLoop = CurveLoop()

profileLoops.Add(outerProfileLoop)
#profileLoops.Add(innerProfileLoop)


#create filled region
for i in range(0,len(pts)-1):
	outerProfileLoop.Append(Autodesk.Revit.DB.Line.CreateBound(XYZ(pts[i].X,pts[i].Y,pts[i].Z),XYZ(pts[i+1].X,pts[i+1].Y,pts[i+1].Z)))

for j in range(0,len(innerPts)):
	innerProfileLoop = CurveLoop()
	profileLoops.Add(innerProfileLoop)
	for i in range(0,len(innerPts[j])-1):
		innerProfileLoop.Append(Autodesk.Revit.DB.Line.CreateBound(XYZ(innerPts[j][i].X,innerPts[j][i].Y,innerPts[j][i].Z),XYZ(innerPts[j][i+1].X,innerPts[j][i+1].Y,innerPts[j][i+1].Z)))


region = FilledRegion.Create(doc,frt[0].Id,activeViewId,profileLoops)
regions.Add(region)

TransactionManager.Instance.TransactionTaskDone()

#Assign your outputs to the OUT variable
OUT = regions
</Script>
    </PythonNodeModels.PythonNode>
    <Dynamo.Graph.Nodes.ZeroTouch.DSFunction guid="f08f368e-effc-43e8-a2a5-7b896fc1c01e" type="Dynamo.Graph.Nodes.ZeroTouch.DSFunction" nickname="Curve.EndPoint" x="4217.46024348483" y="-11.6872542935741" isVisible="true" isUpstreamVisible="true" lacing="Shortest" isSelectedInput="False" IsFrozen="false" isPinned="false" assembly="ProtoGeometry.dll" function="Autodesk.DesignScript.Geometry.Curve.EndPoint">
      <PortInfo index="0" default="False" />
    </Dynamo.Graph.Nodes.ZeroTouch.DSFunction>
    <PythonNodeModels.PythonNode guid="b0b2367f-16f0-4be1-9495-bc9c9d40b503" type="PythonNodeModels.PythonNode" nickname="Python Script" x="4876.52566754416" y="-179.503593691772" isVisible="true" isUpstreamVisible="true" lacing="Disabled" isSelectedInput="False" IsFrozen="false" isPinned="false" inputcount="1">
      <PortInfo index="0" default="False" />
      <Script>list = IN[0]

newList = []

for i in range(0,len(list)):
	newList.append(list[i])
	newList[i].append(list[i][0])

OUT = newList</Script>
    </PythonNodeModels.PythonNode>
    <Dynamo.Graph.Nodes.CustomNodes.Function guid="e73ed720-d78f-4a4d-97b0-c4439e81f3db" type="Dynamo.Graph.Nodes.CustomNodes.Function" nickname="Group Curves" x="3921.28353484849" y="-185.451968396899" isVisible="true" isUpstreamVisible="true" lacing="Shortest" isSelectedInput="False" IsFrozen="false" isPinned="false">
      <PortInfo index="0" default="False" useLevels="True" level="2" shouldKeepListStructure="False" />
      <ID value="c84855d4-eb7e-4574-86a5-04867486df63" />
      <Name value="Group Curves" />
      <Description value="This node will take any input of flat list of curves and group them into sublists containing &quot;joinable&quot; curves that is continous curves. They might form closed curves or open curves. Use PolyCurve.ByJoinedCurves to convert output groups of curves into single PolyCurves" />
      <Inputs>
        <Input value="Curves" />
      </Inputs>
      <Outputs>
        <Output value="Grouped Curves" />
      </Outputs>
    </Dynamo.Graph.Nodes.CustomNodes.Function>
    <Dynamo.Graph.Nodes.ZeroTouch.DSFunction guid="af8b45a7-2836-4e06-be75-2f5f06c6ea36" type="Dynamo.Graph.Nodes.ZeroTouch.DSFunction" nickname="Flatten" x="4493.19868617827" y="-179.771142785602" isVisible="true" isUpstreamVisible="true" lacing="Shortest" isSelectedInput="False" IsFrozen="false" isPinned="false" assembly="BuiltIn" function="Flatten@var[]..[]">
      <PortInfo index="0" default="False" useLevels="True" level="2" shouldKeepListStructure="False" />
    </Dynamo.Graph.Nodes.ZeroTouch.DSFunction>
    <Dynamo.Graph.Nodes.ZeroTouch.DSFunction guid="c76a46e3-e238-4391-810e-f693988d08e5" type="Dynamo.Graph.Nodes.ZeroTouch.DSFunction" nickname="Rectangle.ByWidthLength" x="2416.65057682049" y="-418.877653699575" isVisible="true" isUpstreamVisible="true" lacing="Shortest" isSelectedInput="False" IsFrozen="false" isPinned="false" assembly="ProtoGeometry.dll" function="Autodesk.DesignScript.Geometry.Rectangle.ByWidthLength@Autodesk.DesignScript.Geometry.CoordinateSystem,double,double">
      <PortInfo index="0" default="True" />
      <PortInfo index="1" default="True" />
      <PortInfo index="2" default="True" />
    </Dynamo.Graph.Nodes.ZeroTouch.DSFunction>
    <Dynamo.Graph.Nodes.ZeroTouch.DSFunction guid="6c4bce9d-c244-48db-889f-61915a1b31ab" type="Dynamo.Graph.Nodes.ZeroTouch.DSFunction" nickname="Room.Location" x="1743.07818060637" y="-507.044384414479" isVisible="true" isUpstreamVisible="true" lacing="Shortest" isSelectedInput="False" IsFrozen="false" isPinned="false" assembly="RevitNodes.dll" function="Revit.Elements.Room.Location">
      <PortInfo index="0" default="False" />
    </Dynamo.Graph.Nodes.ZeroTouch.DSFunction>
    <Dynamo.Graph.Nodes.ZeroTouch.DSFunction guid="0d82099e-db17-4a1d-aaa7-6a00ceaf66e2" type="Dynamo.Graph.Nodes.ZeroTouch.DSFunction" nickname="CoordinateSystem.ByOrigin" x="1989.01972081372" y="-544.150294162041" isVisible="true" isUpstreamVisible="true" lacing="Shortest" isSelectedInput="False" IsFrozen="false" isPinned="false" assembly="ProtoGeometry.dll" function="Autodesk.DesignScript.Geometry.CoordinateSystem.ByOrigin@Autodesk.DesignScript.Geometry.Point">
      <PortInfo index="0" default="True" />
    </Dynamo.Graph.Nodes.ZeroTouch.DSFunction>
    <Dynamo.Graph.Nodes.CodeBlockNodeModel guid="f0ff4d48-cc3b-464f-8615-74a1c899d0eb" type="Dynamo.Graph.Nodes.CodeBlockNodeModel" nickname="Code Block" x="2141.41541360894" y="-414.859772764479" isVisible="true" isUpstreamVisible="true" lacing="Disabled" isSelectedInput="False" IsFrozen="false" isPinned="false" CodeText="120;" ShouldFocus="false" />
    <Dynamo.Graph.Nodes.ZeroTouch.DSFunction guid="af5e87fa-e834-4ac2-a8b4-03b3ce9d1e1a" type="Dynamo.Graph.Nodes.ZeroTouch.DSFunction" nickname="Geometry.Explode" x="2688.41373647037" y="-342.828186119689" isVisible="true" isUpstreamVisible="true" lacing="Shortest" isSelectedInput="False" IsFrozen="false" isPinned="false" assembly="ProtoGeometry.dll" function="Autodesk.DesignScript.Geometry.Geometry.Explode">
      <PortInfo index="0" default="False" />
    </Dynamo.Graph.Nodes.ZeroTouch.DSFunction>
    <DSRevitNodesUI.Categories guid="23211f07-1341-412f-814f-39b185f97819" type="DSRevitNodesUI.Categories" nickname="Categories" x="1270.73755695053" y="535.876824251275" isVisible="true" isUpstreamVisible="true" lacing="Disabled" isSelectedInput="True" IsFrozen="false" isPinned="false" index="403:Rooms" />
    <DSRevitNodesUI.ElementsOfCategory guid="13c0cc56-38c2-4f51-b1ba-c1f4aeafb363" type="DSRevitNodesUI.ElementsOfCategory" nickname="All Elements of Category" x="1527.21161067375" y="414.059910553571" isVisible="true" isUpstreamVisible="true" lacing="Disabled" isSelectedInput="False" IsFrozen="false" isPinned="true">
      <PortInfo index="0" default="False" />
    </DSRevitNodesUI.ElementsOfCategory>
    <Dynamo.Graph.Nodes.CodeBlockNodeModel guid="6803a4cd-5639-443b-ac71-006fdd549d87" type="Dynamo.Graph.Nodes.CodeBlockNodeModel" nickname="Code Block" x="5472.28390405758" y="-366.303753116461" isVisible="true" isUpstreamVisible="true" lacing="Disabled" isSelectedInput="False" IsFrozen="false" isPinned="false" CodeText="a[0];" ShouldFocus="false">
      <PortInfo index="0" default="False" />
    </Dynamo.Graph.Nodes.CodeBlockNodeModel>
    <Dynamo.Graph.Nodes.CodeBlockNodeModel guid="00bed3ba-1d08-4898-9d26-a2c74f0c9805" type="Dynamo.Graph.Nodes.CodeBlockNodeModel" nickname="Code Block" x="5484.13917797485" y="-65.2841900533696" isVisible="true" isUpstreamVisible="true" lacing="Disabled" isSelectedInput="False" IsFrozen="false" isPinned="true" CodeText="{a[0]};" ShouldFocus="false">
      <PortInfo index="0" default="False" />
    </Dynamo.Graph.Nodes.CodeBlockNodeModel>
    <PythonNodeModels.PythonNode guid="d083a7ce-6980-4811-874f-b65b9158a5ad" type="PythonNodeModels.PythonNode" nickname="Python Script" x="5835.02275625196" y="-356.249816761184" isVisible="true" isUpstreamVisible="true" lacing="Disabled" isSelectedInput="False" IsFrozen="false" isPinned="true" inputcount="1">
      <PortInfo index="0" default="False" />
      <Script>import clr

clr.AddReference('RevitAPI')
from Autodesk.Revit.DB import *

clr.AddReference("RevitNodes")
import Revit
# Import ToProtoType, ToRevitType geometry conversion extension methods
clr.ImportExtensions(Revit.GeometryConversion)


pts = IN[0]
elementlist = []

for pt in pts:
	elementlist.append(pt.ToRevitType())

OUT = elementlist</Script>
    </PythonNodeModels.PythonNode>
    <PythonNodeModels.PythonNode guid="c6e34404-a007-494f-9fd3-8ca174d568ef" type="PythonNodeModels.PythonNode" nickname="Python Script" x="5855.29665207749" y="-111.460242894218" isVisible="true" isUpstreamVisible="true" lacing="Disabled" isSelectedInput="False" IsFrozen="false" isPinned="true" inputcount="1">
      <PortInfo index="0" default="False" />
      <Script>import clr

clr.AddReference('RevitAPI')
from Autodesk.Revit.DB import *

clr.AddReference("RevitNodes")
import Revit
# Import ToProtoType, ToRevitType geometry conversion extension methods
clr.ImportExtensions(Revit.GeometryConversion)


pts = IN[0]
elementlist = []

for i in range(0,len(pts)):
	p = []
	elementlist.append(p)
	for j in range(0,len(pts[i])):
		p.append(pts[i][j].ToRevitType())

OUT = elementlist</Script>
    </PythonNodeModels.PythonNode>
    <PythonNodeModels.PythonNode guid="42a6b14b-bd02-4918-915a-7b2aad52ea2b" type="PythonNodeModels.PythonNode" nickname="Python Script" x="5375.16437396045" y="-851.579511292843" isVisible="true" isUpstreamVisible="true" lacing="Disabled" isSelectedInput="False" IsFrozen="false" isPinned="true" inputcount="1">
      <PortInfo index="0" default="False" />
      <Script>import clr

clr.AddReference('RevitAPI')
from Autodesk.Revit.DB import *

clr.AddReference("RevitNodes")
import Revit
# Import ToProtoType, ToRevitType geometry conversion extension methods
clr.ImportExtensions(Revit.GeometryConversion)


pts = IN[0]
elementlist = []

for i in range(0,len(pts)):
	p = []
	elementlist.append(p)
	for j in range(0,len(pts[i])):
		p.append(pts[i][j].ToRevitType())

OUT = elementlist</Script>
    </PythonNodeModels.PythonNode>
    <PythonNodeModels.PythonNode guid="f8d95a88-0140-44fa-94e2-20836f562c92" type="PythonNodeModels.PythonNode" nickname="Python Script" x="5676.76867467559" y="-845.61088083157" isVisible="true" isUpstreamVisible="true" lacing="Disabled" isSelectedInput="False" IsFrozen="false" isPinned="true" inputcount="1">
      <PortInfo index="0" default="False" />
      <Script>import clr

clr.AddReference('RevitAPI')
from Autodesk.Revit.DB import *

clr.AddReference("RevitNodes")
import Revit
# Import ToProtoType, ToRevitType geometry conversion extension methods
clr.ImportExtensions(Revit.GeometryConversion)


pts = IN[0]
elementlist = []

for i in range(0,len(pts)):
	p = []
	elementlist.append(p)
	for j in range(0,len(pts[i])):
		p.append(pts[i][j].ToRevitType())

newList = []

for el in elementlist:
	newList.append([el])


OUT = newList</Script>
    </PythonNodeModels.PythonNode>
    <PythonNodeModels.PythonNode guid="696d3adf-9be5-416f-8746-19d366c7e8fe" type="PythonNodeModels.PythonNode" nickname="Python Script" x="5974.47966844741" y="-873.667728451565" isVisible="true" isUpstreamVisible="true" lacing="Disabled" isSelectedInput="False" IsFrozen="true" isPinned="true" inputcount="3">
      <PortInfo index="0" default="False" />
      <PortInfo index="1" default="False" />
      <PortInfo index="2" default="False" />
      <Script>import clr
clr.AddReference('ProtoGeometry')
from Autodesk.DesignScript.Geometry import *

# Import DocumentManager and TransactionManager
clr.AddReference("RevitServices")
import RevitServices
from RevitServices.Persistence import DocumentManager
from RevitServices.Transactions import TransactionManager

# Import RevitAPI
clr.AddReference("RevitAPI")
import Autodesk
from Autodesk.Revit.DB import *

doc = DocumentManager.Instance.CurrentDBDocument
uiapp = DocumentManager.Instance.CurrentUIApplication
app = uiapp.Application


regions = []
activeViewId = doc.ActiveView.Id;

outerCurves = UnwrapElement(IN[0])
innerCurves = UnwrapElement(IN[1])

filledRegionType = UnwrapElement(IN[2])

TransactionManager.Instance.EnsureInTransaction(doc)

for pts,innerPts in zip(outerCurves,innerCurves):
	profileLoops = []
	outerProfileLoop = CurveLoop()
	profileLoops.Add(outerProfileLoop)
	#create filled region
	for i in range(0,len(pts)-1):
		outerProfileLoop.Append(Autodesk.Revit.DB.Line.CreateBound(XYZ(pts[i].X,pts[i].Y,pts[i].Z),XYZ(pts[i+1].X,pts[i+1].Y,pts[i+1].Z)))

	for j in range(0,len(innerPts)):
		innerProfileLoop = CurveLoop()
		profileLoops.Add(innerProfileLoop)
		for i in range(0,len(innerPts[j])-1):
			innerProfileLoop.Append(Autodesk.Revit.DB.Line.CreateBound(XYZ(innerPts[j][i].X,innerPts[j][i].Y,innerPts[j][i].Z),XYZ(innerPts[j][i+1].X,innerPts[j][i+1].Y,innerPts[j][i+1].Z)))
			
	region = FilledRegion.Create(doc,filledRegionType[0].Id,activeViewId,profileLoops)
	regions.Add(region)

TransactionManager.Instance.TransactionTaskDone()

#Assign your outputs to the OUT variable
OUT = regions
</Script>
    </PythonNodeModels.PythonNode>
    <PythonNodeModels.PythonNode guid="69f300be-9a9f-47e4-9c62-99cb0bf32ca1" type="PythonNodeModels.PythonNode" nickname="Python Script" x="5136.86353861517" y="440.919497026744" isVisible="true" isUpstreamVisible="true" lacing="Disabled" isSelectedInput="False" IsFrozen="false" isPinned="true" inputcount="2">
      <PortInfo index="0" default="False" />
      <PortInfo index="1" default="False" />
      <Script>import clr
clr.AddReference('ProtoGeometry')
from Autodesk.DesignScript.Geometry import *

# Import DocumentManager and TransactionManager
clr.AddReference("RevitServices")
import RevitServices
from RevitServices.Persistence import DocumentManager
from RevitServices.Transactions import TransactionManager

# Import RevitAPI
clr.AddReference("RevitAPI")
import Autodesk
from Autodesk.Revit.DB import *

doc = DocumentManager.Instance.CurrentDBDocument
uiapp = DocumentManager.Instance.CurrentUIApplication
app = uiapp.Application
activeViewId = doc.ActiveView.Id;

area = UnwrapElement(IN[0])

filledRegionType = UnwrapElement(IN[1])

opt = SpatialElementBoundaryOptions()
opt.StoreFreeBoundaryFaces = False
opt.SpatialElementBoundaryLocation.Center

listRegions = []

TransactionManager.Instance.EnsureInTransaction(doc)

for i in range(0,len(area)):
	profileLoops = []
	segs = area[i].GetBoundarySegments(opt)
	for i in range(0,len(segs)):
		pL = CurveLoop()
		profileLoops.Add(pL)	
		for j in range(0,len(segs[i])):
			pL.Append(segs[i][j].GetCurve())
	listRegions.append(FilledRegion.Create(doc,filledRegionType[0].Id,activeViewId,profileLoops))

TransactionManager.Instance.TransactionTaskDone()

OUT = listRegions</Script>
    </PythonNodeModels.PythonNode>
    <DSRevitNodesUI.ElementsOfCategory guid="1ca7a69e-9968-4ec7-b6ab-0b758b4ddcfb" type="DSRevitNodesUI.ElementsOfCategory" nickname="All Elements of Category" x="4681.04956921215" y="414.647646402264" isVisible="true" isUpstreamVisible="true" lacing="Disabled" isSelectedInput="False" IsFrozen="false" isPinned="true">
      <PortInfo index="0" default="False" />
    </DSRevitNodesUI.ElementsOfCategory>
  </Elements>
  <Connectors>
    <Dynamo.Graph.Connectors.ConnectorModel start="2012bbb3-5949-47fd-8115-5757701a33fa" start_index="0" end="69b444c5-f067-46ea-88e2-3a3c1ab2f74e" end_index="0" portType="0" />
    <Dynamo.Graph.Connectors.ConnectorModel start="78c5313b-68a1-47ac-8cd2-867212b668dc" start_index="0" end="2012bbb3-5949-47fd-8115-5757701a33fa" end_index="1" portType="0" />
    <Dynamo.Graph.Connectors.ConnectorModel start="69b444c5-f067-46ea-88e2-3a3c1ab2f74e" start_index="0" end="57355397-5ef2-46c1-8896-624d235ba89d" end_index="1" portType="0" />
    <Dynamo.Graph.Connectors.ConnectorModel start="736f40e2-60e7-4d30-a6d3-905c3c89d286" start_index="0" end="69b444c5-f067-46ea-88e2-3a3c1ab2f74e" end_index="1" portType="0" />
    <Dynamo.Graph.Connectors.ConnectorModel start="ff375865-5b6c-49a7-8c84-f36963eac019" start_index="0" end="2012bbb3-5949-47fd-8115-5757701a33fa" end_index="0" portType="0" />
    <Dynamo.Graph.Connectors.ConnectorModel start="ff375865-5b6c-49a7-8c84-f36963eac019" start_index="0" end="57355397-5ef2-46c1-8896-624d235ba89d" end_index="0" portType="0" />
    <Dynamo.Graph.Connectors.ConnectorModel start="7f2bd5f6-89ab-44bc-8f08-48fbf726a9de" start_index="0" end="ff375865-5b6c-49a7-8c84-f36963eac019" end_index="0" portType="0" />
    <Dynamo.Graph.Connectors.ConnectorModel start="86d5b35b-93ab-41e1-85a5-8d9607ecdbd9" start_index="0" end="da4cf1ad-bec2-4fca-8109-e755b58d5e13" end_index="0" portType="0" />
    <Dynamo.Graph.Connectors.ConnectorModel start="61e8360f-75bc-4335-a2b7-c140b01ca510" start_index="0" end="f543fd0e-4ec7-4cae-ab66-9f645e0ee72f" end_index="2" portType="0" />
    <Dynamo.Graph.Connectors.ConnectorModel start="61e8360f-75bc-4335-a2b7-c140b01ca510" start_index="0" end="696d3adf-9be5-416f-8746-19d366c7e8fe" end_index="2" portType="0" />
    <Dynamo.Graph.Connectors.ConnectorModel start="61e8360f-75bc-4335-a2b7-c140b01ca510" start_index="0" end="69f300be-9a9f-47e4-9c62-99cb0bf32ca1" end_index="1" portType="0" />
    <Dynamo.Graph.Connectors.ConnectorModel start="5ae8f09b-3964-49ee-bc36-a27be54b3de3" start_index="0" end="61e8360f-75bc-4335-a2b7-c140b01ca510" end_index="0" portType="0" />
    <Dynamo.Graph.Connectors.ConnectorModel start="da4cf1ad-bec2-4fca-8109-e755b58d5e13" start_index="0" end="1186684a-3b54-40ac-bafe-bbc8b97202d0" end_index="0" portType="0" />
    <Dynamo.Graph.Connectors.ConnectorModel start="816d1ea1-c3ce-4248-a6a2-89a0f71f15b1" start_index="0" end="cd0a305b-36c3-416b-bf16-8eb6aa38654c" end_index="0" portType="0" />
    <Dynamo.Graph.Connectors.ConnectorModel start="1186684a-3b54-40ac-bafe-bbc8b97202d0" start_index="0" end="816d1ea1-c3ce-4248-a6a2-89a0f71f15b1" end_index="0" portType="0" />
    <Dynamo.Graph.Connectors.ConnectorModel start="cd0a305b-36c3-416b-bf16-8eb6aa38654c" start_index="0" end="6803a4cd-5639-443b-ac71-006fdd549d87" end_index="0" portType="0" />
    <Dynamo.Graph.Connectors.ConnectorModel start="cd0a305b-36c3-416b-bf16-8eb6aa38654c" start_index="0" end="42a6b14b-bd02-4918-915a-7b2aad52ea2b" end_index="0" portType="0" />
    <Dynamo.Graph.Connectors.ConnectorModel start="daf54c81-21e1-4270-a08c-642b5025e604" start_index="0" end="3389c3d3-4554-4a95-9462-92f64b206cbf" end_index="0" portType="0" />
    <Dynamo.Graph.Connectors.ConnectorModel start="3389c3d3-4554-4a95-9462-92f64b206cbf" start_index="0" end="5ae8f09b-3964-49ee-bc36-a27be54b3de3" end_index="0" portType="0" />
    <Dynamo.Graph.Connectors.ConnectorModel start="f08f368e-effc-43e8-a2a5-7b896fc1c01e" start_index="0" end="af8b45a7-2836-4e06-be75-2f5f06c6ea36" end_index="0" portType="0" />
    <Dynamo.Graph.Connectors.ConnectorModel start="b0b2367f-16f0-4be1-9495-bc9c9d40b503" start_index="0" end="00bed3ba-1d08-4898-9d26-a2c74f0c9805" end_index="0" portType="0" />
    <Dynamo.Graph.Connectors.ConnectorModel start="b0b2367f-16f0-4be1-9495-bc9c9d40b503" start_index="0" end="f8d95a88-0140-44fa-94e2-20836f562c92" end_index="0" portType="0" />
    <Dynamo.Graph.Connectors.ConnectorModel start="e73ed720-d78f-4a4d-97b0-c4439e81f3db" start_index="0" end="f08f368e-effc-43e8-a2a5-7b896fc1c01e" end_index="0" portType="0" />
    <Dynamo.Graph.Connectors.ConnectorModel start="af8b45a7-2836-4e06-be75-2f5f06c6ea36" start_index="0" end="b0b2367f-16f0-4be1-9495-bc9c9d40b503" end_index="0" portType="0" />
    <Dynamo.Graph.Connectors.ConnectorModel start="c76a46e3-e238-4391-810e-f693988d08e5" start_index="0" end="af5e87fa-e834-4ac2-a8b4-03b3ce9d1e1a" end_index="0" portType="0" />
    <Dynamo.Graph.Connectors.ConnectorModel start="6c4bce9d-c244-48db-889f-61915a1b31ab" start_index="0" end="0d82099e-db17-4a1d-aaa7-6a00ceaf66e2" end_index="0" portType="0" />
    <Dynamo.Graph.Connectors.ConnectorModel start="0d82099e-db17-4a1d-aaa7-6a00ceaf66e2" start_index="0" end="c76a46e3-e238-4391-810e-f693988d08e5" end_index="0" portType="0" />
    <Dynamo.Graph.Connectors.ConnectorModel start="f0ff4d48-cc3b-464f-8615-74a1c899d0eb" start_index="0" end="c76a46e3-e238-4391-810e-f693988d08e5" end_index="1" portType="0" />
    <Dynamo.Graph.Connectors.ConnectorModel start="f0ff4d48-cc3b-464f-8615-74a1c899d0eb" start_index="0" end="c76a46e3-e238-4391-810e-f693988d08e5" end_index="2" portType="0" />
    <Dynamo.Graph.Connectors.ConnectorModel start="af5e87fa-e834-4ac2-a8b4-03b3ce9d1e1a" start_index="0" end="e73ed720-d78f-4a4d-97b0-c4439e81f3db" end_index="0" portType="0" />
    <Dynamo.Graph.Connectors.ConnectorModel start="23211f07-1341-412f-814f-39b185f97819" start_index="0" end="13c0cc56-38c2-4f51-b1ba-c1f4aeafb363" end_index="0" portType="0" />
    <Dynamo.Graph.Connectors.ConnectorModel start="23211f07-1341-412f-814f-39b185f97819" start_index="0" end="1ca7a69e-9968-4ec7-b6ab-0b758b4ddcfb" end_index="0" portType="0" />
    <Dynamo.Graph.Connectors.ConnectorModel start="13c0cc56-38c2-4f51-b1ba-c1f4aeafb363" start_index="0" end="86d5b35b-93ab-41e1-85a5-8d9607ecdbd9" end_index="0" portType="0" />
    <Dynamo.Graph.Connectors.ConnectorModel start="13c0cc56-38c2-4f51-b1ba-c1f4aeafb363" start_index="0" end="6c4bce9d-c244-48db-889f-61915a1b31ab" end_index="0" portType="0" />
    <Dynamo.Graph.Connectors.ConnectorModel start="6803a4cd-5639-443b-ac71-006fdd549d87" start_index="0" end="d083a7ce-6980-4811-874f-b65b9158a5ad" end_index="0" portType="0" />
    <Dynamo.Graph.Connectors.ConnectorModel start="00bed3ba-1d08-4898-9d26-a2c74f0c9805" start_index="0" end="c6e34404-a007-494f-9fd3-8ca174d568ef" end_index="0" portType="0" />
    <Dynamo.Graph.Connectors.ConnectorModel start="d083a7ce-6980-4811-874f-b65b9158a5ad" start_index="0" end="f543fd0e-4ec7-4cae-ab66-9f645e0ee72f" end_index="0" portType="0" />
    <Dynamo.Graph.Connectors.ConnectorModel start="c6e34404-a007-494f-9fd3-8ca174d568ef" start_index="0" end="f543fd0e-4ec7-4cae-ab66-9f645e0ee72f" end_index="1" portType="0" />
    <Dynamo.Graph.Connectors.ConnectorModel start="42a6b14b-bd02-4918-915a-7b2aad52ea2b" start_index="0" end="696d3adf-9be5-416f-8746-19d366c7e8fe" end_index="0" portType="0" />
    <Dynamo.Graph.Connectors.ConnectorModel start="f8d95a88-0140-44fa-94e2-20836f562c92" start_index="0" end="696d3adf-9be5-416f-8746-19d366c7e8fe" end_index="1" portType="0" />
    <Dynamo.Graph.Connectors.ConnectorModel start="1ca7a69e-9968-4ec7-b6ab-0b758b4ddcfb" start_index="0" end="69f300be-9a9f-47e4-9c62-99cb0bf32ca1" end_index="0" portType="0" />
  </Connectors>
  <Notes>
    <Dynamo.Graph.Notes.NoteModel guid="e5b8cb7e-0ac0-4f26-b384-f8af9b8f79eb" text="Append Pt[0] to the end" x="4579.57120528234" y="-736.888118045803" />
  </Notes>
  <Annotations>
    <Dynamo.Graph.Annotations.AnnotationModel guid="dfffeca4-a71e-44dd-9919-5a7660d95e98" annotationText="Prend les Pièces et les filtre par &quot;Ar_Espace de vente&quot; Oui/Non" left="95.935007437518" top="83.212800854745" width="1355.2" height="305.813333333333" fontSize="30" InitialTop="129.212800854745" InitialHeight="290.213333333333" TextblockHeight="36" backgrouund="#FFFFAA45">
      <Models ModelGuid="2012bbb3-5949-47fd-8115-5757701a33fa" />
      <Models ModelGuid="78c5313b-68a1-47ac-8cd2-867212b668dc" />
      <Models ModelGuid="69b444c5-f067-46ea-88e2-3a3c1ab2f74e" />
      <Models ModelGuid="736f40e2-60e7-4d30-a6d3-905c3c89d286" />
      <Models ModelGuid="57355397-5ef2-46c1-8896-624d235ba89d" />
      <Models ModelGuid="ff375865-5b6c-49a7-8c84-f36963eac019" />
      <Models ModelGuid="7f2bd5f6-89ab-44bc-8f08-48fbf726a9de" />
    </Dynamo.Graph.Annotations.AnnotationModel>
    <Dynamo.Graph.Annotations.AnnotationModel guid="3123bb5c-251e-4864-96ec-f706a359658b" annotationText="Récupère la limite exterieure des pièces" left="1746.57457614121" top="109.882969891264" width="223.2" height="210.6" fontSize="30" InitialTop="227.882969891264" InitialHeight="123" TextblockHeight="108" backgrouund="#FFFFAA45">
      <Models ModelGuid="86d5b35b-93ab-41e1-85a5-8d9607ecdbd9" />
    </Dynamo.Graph.Annotations.AnnotationModel>
    <Dynamo.Graph.Annotations.AnnotationModel guid="affeb242-4c7e-4b9f-9a98-af3a39c985bc" annotationText="FILLED REGION TYPE" left="3895.7554838848" top="163.893042867086" width="929.97243711151" height="143.09141679357" fontSize="30" InitialTop="209.893042867086" InitialHeight="129.84629819743" TextblockHeight="36" backgrouund="#FFC1D676">
      <Models ModelGuid="daf54c81-21e1-4270-a08c-642b5025e604" />
      <Models ModelGuid="3389c3d3-4554-4a95-9462-92f64b206cbf" />
      <Models ModelGuid="5ae8f09b-3964-49ee-bc36-a27be54b3de3" />
      <Models ModelGuid="61e8360f-75bc-4335-a2b7-c140b01ca510" />
    </Dynamo.Graph.Annotations.AnnotationModel>
    <Dynamo.Graph.Annotations.AnnotationModel guid="94112e32-c0d1-4f56-b6f9-8bcef75ed943" annotationText="OUTER CURVES" left="3764.52940392925" top="-844.683974879463" width="963.792035604793" height="251.436204227046" fontSize="30" InitialTop="-798.683974879463" InitialHeight="222.18382244329" TextblockHeight="36" backgrouund="#FFC1D676">
      <Models ModelGuid="da4cf1ad-bec2-4fca-8109-e755b58d5e13" />
      <Models ModelGuid="816d1ea1-c3ce-4248-a6a2-89a0f71f15b1" />
      <Models ModelGuid="1186684a-3b54-40ac-bafe-bbc8b97202d0" />
      <Models ModelGuid="cd0a305b-36c3-416b-bf16-8eb6aa38654c" />
      <Models ModelGuid="e5b8cb7e-0ac0-4f26-b384-f8af9b8f79eb" />
    </Dynamo.Graph.Annotations.AnnotationModel>
    <Dynamo.Graph.Annotations.AnnotationModel guid="42f6dae4-2bc9-4ecb-87a9-5b5566f8831e" annotationText="INNER CURVES" left="3911.28353484849" top="-231.451968396899" width="1100.04213269567" height="312.364714103325" fontSize="30" InitialTop="-185.451968396899" InitialHeight="175.114775673744" TextblockHeight="36" backgrouund="#FFC1D676">
      <Models ModelGuid="f08f368e-effc-43e8-a2a5-7b896fc1c01e" />
      <Models ModelGuid="b0b2367f-16f0-4be1-9495-bc9c9d40b503" />
      <Models ModelGuid="e73ed720-d78f-4a4d-97b0-c4439e81f3db" />
    </Dynamo.Graph.Annotations.AnnotationModel>
    <Dynamo.Graph.Annotations.AnnotationModel guid="ea272cf0-7038-4091-95c0-f1e4bad5743c" annotationText="Create 1 filled region " left="5462.28390405758" top="-412.303753116461" width="978.759849046091" height="439.619563063091" fontSize="30" InitialTop="-366.303753116461" InitialHeight="423.619563063091" TextblockHeight="36" backgrouund="#FFFFAA45">
      <Models ModelGuid="f543fd0e-4ec7-4cae-ab66-9f645e0ee72f" />
      <Models ModelGuid="6803a4cd-5639-443b-ac71-006fdd549d87" />
      <Models ModelGuid="00bed3ba-1d08-4898-9d26-a2c74f0c9805" />
      <Models ModelGuid="d083a7ce-6980-4811-874f-b65b9158a5ad" />
      <Models ModelGuid="c6e34404-a007-494f-9fd3-8ca174d568ef" />
    </Dynamo.Graph.Annotations.AnnotationModel>
    <Dynamo.Graph.Annotations.AnnotationModel guid="862006e5-954d-4d5a-b110-e1a93457a083" annotationText="Create multiple filled regions" left="5964.47966844741" top="-1027.66772845157" width="144.8" height="297.8" fontSize="30" InitialTop="-873.667728451565" InitialHeight="262.838510190712" TextblockHeight="144" backgrouund="#FFA4E1FF">
      <Models ModelGuid="696d3adf-9be5-416f-8746-19d366c7e8fe" />
    </Dynamo.Graph.Annotations.AnnotationModel>
    <Dynamo.Graph.Annotations.AnnotationModel guid="292bf5bc-a8fb-484f-9af7-a5b0a63d33c6" annotationText="convert dynamo points to revit points" left="5365.16437396045" top="-933.579511292843" width="446.404300715138" height="180.568630461273" fontSize="30" InitialTop="-851.579511292843" InitialHeight="232.967038513295" TextblockHeight="72" backgrouund="#FFC1D676">
      <Models ModelGuid="42a6b14b-bd02-4918-915a-7b2aad52ea2b" />
      <Models ModelGuid="f8d95a88-0140-44fa-94e2-20836f562c92" />
    </Dynamo.Graph.Annotations.AnnotationModel>
    <Dynamo.Graph.Annotations.AnnotationModel guid="e0525a30-0601-4a74-8825-da2544d3b554" annotationText="Create multiple filled region from rooms" left="5126.86353861517" top="214.919497026744" width="144.8" height="344.2" fontSize="30" InitialTop="440.919497026744" InitialHeight="148.2" TextblockHeight="216" backgrouund="#FFBB87C6">
      <Models ModelGuid="69f300be-9a9f-47e4-9c62-99cb0bf32ca1" />
    </Dynamo.Graph.Annotations.AnnotationModel>
  </Annotations>
  <Presets />
  <Cameras>
    <Camera Name="Background Preview" eyeX="1618.09497682424" eyeY="14412.4190221497" eyeZ="4939.29232443999" lookX="1728.31456907419" lookY="-14412.4190221497" lookZ="-8353.52096213531" upX="0.148176357150078" upY="0.681998372077942" upZ="-0.716185748577118" />
  </Cameras>
</Workspace>