{
  "Uuid": "27fbfec8-bae7-46e5-9561-e59393c10c8e",
  "IsCustomNode": false,
  "Description": null,
  "Name": "Cast in plate place holder01",
  "ElementResolver": {
    "ResolutionMap": {}
  },
  "Inputs": [],
  "Outputs": [],
  "Nodes": [
    {
      "ConcreteType": "PythonNodeModels.PythonNode, PythonNodeModels",
      "NodeType": "PythonScriptNode",
      "Code": "#Copyright(c) 2016, Dimitar Venkov\n# @5devene, dimitar.ven@gmail.com\n\nimport clr\n\nclr.AddReference(\"RevitAPIUI\")\nfrom  Autodesk.Revit.UI import *\n\nclr.AddReference(\"RevitServices\")\nimport RevitServices\nfrom RevitServices.Persistence import DocumentManager\ndoc = DocumentManager.Instance.CurrentDBDocument\nuidoc=DocumentManager.Instance.CurrentUIApplication.ActiveUIDocument\n\nclr.AddReference(\"RevitNodes\")\nimport Revit\nclr.ImportExtensions(Revit.Elements)\nclr.ImportExtensions(Revit.GeometryConversion)\n\nclr.AddReference('RevitAPI')\nfrom Autodesk.Revit.DB import *\n\ndef output1(x):\n\tif len(x) == 1: return x[0]\n\telse : return x\n\nsurfaces = []\nsel1 = uidoc.Selection\not1 = Selection.ObjectType.Face\nref_list = sel1.PickObjects(ot1, \"Select the faces and press Finish.\")\nfor ref in ref_list:\n\tel1 = doc.GetElement(ref.ElementId)\n\tsf0 = el1.GetGeometryObjectFromReference(ref)\n\tif isinstance(el1, FamilyInstance):\n\t\ttf1 = el1.GetTransform().ToCoordinateSystem()\n\t\tsf1 = sf0.Convert(ref, tf1)\n\telse:\n\t\tsf1 = sf0\n\tsurfaces.append(sf1)\n\nOUT = surfaces",
      "VariableInputPorts": true,
      "Id": "97245ad738674c72a92335cc38a8c69b",
      "Inputs": [
        {
          "Id": "e353ede55f5b4f87b723ebf1c6486885",
          "Name": "IN[0]",
          "Description": "Input #0",
          "UsingDefaultValue": false,
          "Level": 2,
          "UseLevels": false,
          "KeepListStructure": false
        }
      ],
      "Outputs": [
        {
          "Id": "53199e0ff10b41e687107b915c66d858",
          "Name": "OUT",
          "Description": "Result of the python script",
          "UsingDefaultValue": false,
          "Level": 2,
          "UseLevels": false,
          "KeepListStructure": false
        }
      ],
      "Replication": "Disabled",
      "Description": "Runs an embedded IronPython script."
    },
    {
      "ConcreteType": "Dynamo.Nodes.DSModelElementSelection, DSRevitNodesUI",
      "NodeType": "ExtensionNode",
      "InstanceId": [
        "b080b4e6-c5ac-4999-9287-8fda53078c3c-00201159"
      ],
      "Id": "511769dae45944b99186730c712882d7",
      "Inputs": [],
      "Outputs": [
        {
          "Id": "f02807ffbac447f4a92a63e9c9e45d1d",
          "Name": "Element",
          "Description": "The selected elements.",
          "UsingDefaultValue": false,
          "Level": 2,
          "UseLevels": false,
          "KeepListStructure": false
        }
      ],
      "Replication": "Disabled"
    },
    {
      "ConcreteType": "DSRevitNodesUI.FamilyTypes, DSRevitNodesUI",
      "SelectedIndex": 908,
      "NodeType": "ExtensionNode",
      "Id": "276a1592b51f4568aebdd614d993d7a4",
      "Inputs": [],
      "Outputs": [
        {
          "Id": "7ec6713c7e5248ea865c0478c076b7db",
          "Name": "Family Type",
          "Description": "The selected Family Type",
          "UsingDefaultValue": false,
          "Level": 2,
          "UseLevels": false,
          "KeepListStructure": false
        }
      ],
      "Replication": "Disabled",
      "Description": "All family types available in the document."
    },
    {
      "ConcreteType": "PythonNodeModels.PythonNode, PythonNodeModels",
      "NodeType": "PythonScriptNode",
      "Code": "import clr\r\n\r\nclr.AddReference('RevitAPI')\r\nfrom Autodesk.Revit.DB import *\r\nfrom Autodesk.Revit.DB.Structure import *\r\n\r\nclr.AddReference('RevitAPIUI')\r\nfrom Autodesk.Revit.UI import *\r\n\r\nclr.AddReference('System')\r\nfrom System.Collections.Generic import List\r\n\r\nclr.AddReference('RevitNodes')\r\nimport Revit\r\nclr.ImportExtensions(Revit.GeometryConversion)\r\nclr.ImportExtensions(Revit.Elements)\r\n\r\nclr.AddReference('RevitServices')\r\nimport RevitServices\r\nfrom RevitServices.Persistence import DocumentManager\r\nfrom RevitServices.Transactions import TransactionManager\r\n\r\ndoc = DocumentManager.Instance.CurrentDBDocument\r\nuidoc=DocumentManager.Instance.CurrentUIApplication.ActiveUIDocument\r\n\r\n\r\ndef BeamMidPoint(beam):\r\n\t#stPt = beam.Location.Curve.GetEndPoint(0)\r\n\t#endPt = beam.Location.Curve.GetEndPoint(0)\r\n\treturn beam.Location.Curve.Evaluate(0.5,True)\r\n\t\r\ndef BeamDirection(beam):\r\n\treturn beam.HandOrientation\r\n\r\ndef SignedDistanceTo(plane, p ):\r\n\tv = p - plane.Origin\r\n\treturn plane.FaceNormal.DotProduct( v )\r\n  \r\n  \r\ndef ProjectOnto(plane, p):\r\n\td = SignedDistanceTo(plane, p );\r\n\tq = p - d * plane.FaceNormal;\r\n\treturn q;\r\n\r\ndef ProjectInto(plane, p ):\r\n\tq = ProjectOnto(plane, p);\r\n\to = plane.Origin;\r\n\td = q - o;\r\n\tu = d.DotProduct( plane.XVector );\r\n\tv = d.DotProduct( plane.YVector );\r\n\treturn UV( u, v )\r\n  \r\n\r\nif isinstance(IN[0], list):\r\n\telements = UnwrapElement(IN[0])\r\nelse:\r\n\telements = [UnwrapElement(IN[0])]\r\n\r\n\r\nwallFace = IN[1][0]\r\nbeams = []\r\npoints = []\r\nfs = UnwrapElement(IN[2]) #VOID FAMILY TYPE\r\n\r\n#TransactionManager.Instance.EnsureInTransaction(doc)\r\n\r\nfor e in elements:\r\n\tif e.Category.Name == \"Structural Framing\":\r\n\t\tcheck = BeamDirection(e).CrossProduct(wallFace.FaceNormal)\r\n\t\tupVector = XYZ(0,0,1)\r\n\t\tdownVector = XYZ(0,0,-1)\r\n\t\tif not check.IsAlmostEqualTo(upVector) and not check.IsAlmostEqualTo(downVector):\r\n\t\t\tpoint = ProjectOnto(wallFace, BeamMidPoint(e))\r\n\t\t\tif wallFace.IsInside(ProjectInto(wallFace, point)):\r\n\t\t\t\tbeams.append(e)\r\n\t\t\t#void = doc.Create.NewFamilyInstance.Overloads[Reference, XYZ, XYZ, FamilySymbol](wallFace.Reference, transformedPoint, direction, fs);\r\n\r\n#TransactionManager.Instance.TransactionTaskDone()\r\np = [p.ToPoint() for p in points]\r\n\r\nOUT = beams",
      "VariableInputPorts": true,
      "Id": "a993533024724d8086ea06b40be7cddf",
      "Inputs": [
        {
          "Id": "e467fcfa18b147b9bff9b55574dfc0fd",
          "Name": "IN[0]",
          "Description": "Input #0",
          "UsingDefaultValue": false,
          "Level": 2,
          "UseLevels": false,
          "KeepListStructure": false
        },
        {
          "Id": "6b8e9d0817a94d39abd9d3cd22cc0025",
          "Name": "IN[1]",
          "Description": "Input #1",
          "UsingDefaultValue": false,
          "Level": 2,
          "UseLevels": false,
          "KeepListStructure": false
        },
        {
          "Id": "cedd5e67efde48548ae26c846341b02b",
          "Name": "IN[2]",
          "Description": "Input #2",
          "UsingDefaultValue": false,
          "Level": 2,
          "UseLevels": false,
          "KeepListStructure": false
        }
      ],
      "Outputs": [
        {
          "Id": "64817d007e7d4c4c93c2e46c37f042df",
          "Name": "OUT",
          "Description": "Result of the python script",
          "UsingDefaultValue": false,
          "Level": 2,
          "UseLevels": false,
          "KeepListStructure": false
        }
      ],
      "Replication": "Disabled",
      "Description": "Runs an embedded IronPython script."
    },
    {
      "ConcreteType": "Dynamo.Graph.Nodes.ZeroTouch.DSFunction, DynamoCore",
      "NodeType": "FunctionNode",
      "FunctionSignature": "Revit.Elements.FamilyInstance.ByFace@Revit.Elements.FamilyType,Autodesk.DesignScript.Geometry.Surface,Autodesk.DesignScript.Geometry.Point,Autodesk.DesignScript.Geometry.Vector",
      "Id": "30da03c8e6394d5f9c597d9cc4862462",
      "Inputs": [
        {
          "Id": "e7eeb4d364dd4690996ab8299031744b",
          "Name": "familyType",
          "Description": "Family Type. Also called Family Symbol.\n\nFamilyType",
          "UsingDefaultValue": false,
          "Level": 2,
          "UseLevels": false,
          "KeepListStructure": false
        },
        {
          "Id": "6aa6c12d864c4320b55b9ddb9ad41cec",
          "Name": "face",
          "Description": "Surface geometry derived from a Revit face as reference element\n\nSurface",
          "UsingDefaultValue": false,
          "Level": 2,
          "UseLevels": false,
          "KeepListStructure": false
        },
        {
          "Id": "13e79f241a7e44709c7120a5ec989b2b",
          "Name": "location",
          "Description": "Point on the face where the instance is to be placed\n\nPoint",
          "UsingDefaultValue": false,
          "Level": 2,
          "UseLevels": false,
          "KeepListStructure": false
        },
        {
          "Id": "2ac8ada5f8ef4ded81d63e59ef80606b",
          "Name": "referenceDirection",
          "Description": "A vector that defines the direction of placement of the family instance\n\nVector",
          "UsingDefaultValue": false,
          "Level": 2,
          "UseLevels": false,
          "KeepListStructure": false
        }
      ],
      "Outputs": [
        {
          "Id": "10067449cfe04f5292382a1d559b2f53",
          "Name": "FamilyInstance",
          "Description": "FamilyInstance",
          "UsingDefaultValue": false,
          "Level": 2,
          "UseLevels": false,
          "KeepListStructure": false
        }
      ],
      "Replication": "Auto",
      "Description": "Place a Revit family instance given the FamilyType (also known as the FamilySymbol in the Revit API) on a surface derived from a backing Revit face as reference, a reference direction and a point location where to place the family. Note: The FamilyType should be workplane based and the input surface must be created from a Revit Face. The reference direction defines the rotation of the instance on the reference, and thus cannot be perpendicular to the face.\n\nFamilyInstance.ByFace (familyType: FamilyType, face: Surface, location: Point, referenceDirection: Vector): FamilyInstance"
    },
    {
      "ConcreteType": "Dynamo.Graph.Nodes.ZeroTouch.DSFunction, DynamoCore",
      "NodeType": "FunctionNode",
      "FunctionSignature": "Autodesk.DesignScript.Geometry.Vector.Reverse",
      "Id": "a98b5394ade84fa2a63985dc044bac90",
      "Inputs": [
        {
          "Id": "aacb6554805e439dbc93c2ef4f5a9032",
          "Name": "vector",
          "Description": "Autodesk.DesignScript.Geometry.Vector",
          "UsingDefaultValue": false,
          "Level": 2,
          "UseLevels": false,
          "KeepListStructure": false
        }
      ],
      "Outputs": [
        {
          "Id": "2c729aceb9e240b3bf63fe0d942f3ef4",
          "Name": "Vector",
          "Description": "Vector",
          "UsingDefaultValue": false,
          "Level": 2,
          "UseLevels": false,
          "KeepListStructure": false
        }
      ],
      "Replication": "Auto",
      "Description": "Get the reverse of the vector. Essentially this negates the X, Y, and Z components of the Vector.\n\nVector.Reverse ( ): Vector"
    },
    {
      "ConcreteType": "Dynamo.Graph.Nodes.ZeroTouch.DSFunction, DynamoCore",
      "NodeType": "FunctionNode",
      "FunctionSignature": "Autodesk.DesignScript.Geometry.Vector.XAxis",
      "Id": "320c3df8436f473cb9a58a761639f62d",
      "Inputs": [],
      "Outputs": [
        {
          "Id": "3c22198329194da6b3f76611cf97b21a",
          "Name": "Vector",
          "Description": "Vector",
          "UsingDefaultValue": false,
          "Level": 2,
          "UseLevels": false,
          "KeepListStructure": false
        }
      ],
      "Replication": "Auto",
      "Description": "Get the canonical X axis Vector (1,0,0)\n\nVector.XAxis ( ): Vector"
    },
    {
      "ConcreteType": "Dynamo.Nodes.DSFaceSelection, DSRevitNodesUI",
      "NodeType": "ExtensionNode",
      "InstanceId": [
        "a4fff56f-a538-485e-b333-be0c5995d6b8-0024d3fc:6:SURFACE"
      ],
      "Id": "1f6e74b70a6f46769e8af46ba9594d9d",
      "Inputs": [],
      "Outputs": [
        {
          "Id": "a1bbf6605810427c819d18467eee7928",
          "Name": "Surface",
          "Description": "The selected elements.",
          "UsingDefaultValue": false,
          "Level": 2,
          "UseLevels": false,
          "KeepListStructure": false
        }
      ],
      "Replication": "Disabled"
    },
    {
      "ConcreteType": "DSRevitNodesUI.ElementsInView, DSRevitNodesUI",
      "NodeType": "ExtensionNode",
      "Id": "307120ed71da403eb3606e947da00ba1",
      "Inputs": [],
      "Outputs": [
        {
          "Id": "865d25c95fca4b268d711665076bc4eb",
          "Name": "elements",
          "Description": "All visible elements in the active view.",
          "UsingDefaultValue": false,
          "Level": 2,
          "UseLevels": false,
          "KeepListStructure": false
        }
      ],
      "Replication": "Disabled",
      "Description": "Get all the elements which are visible in the active view."
    },
    {
      "ConcreteType": "Dynamo.Graph.Nodes.ZeroTouch.DSFunction, DynamoCore",
      "NodeType": "FunctionNode",
      "FunctionSignature": "Revit.References.RayBounce.ByOriginDirection@Autodesk.DesignScript.Geometry.Point,Autodesk.DesignScript.Geometry.Vector,int,Revit.Elements.Views.View3D",
      "Id": "b0ff550d0c9c4519a55a6a35268addc4",
      "Inputs": [
        {
          "Id": "0d1445eebe854cdd82dd1fe405938128",
          "Name": "origin",
          "Description": "Point",
          "UsingDefaultValue": false,
          "Level": 2,
          "UseLevels": false,
          "KeepListStructure": false
        },
        {
          "Id": "3d48c92d07d342d3be16f445e8a9c300",
          "Name": "direction",
          "Description": "Vector",
          "UsingDefaultValue": false,
          "Level": 2,
          "UseLevels": false,
          "KeepListStructure": false
        },
        {
          "Id": "1952120ca0f84fa0b056ae15ed3beb21",
          "Name": "maxBounces",
          "Description": "int",
          "UsingDefaultValue": false,
          "Level": 2,
          "UseLevels": false,
          "KeepListStructure": false
        },
        {
          "Id": "257d52fa05e14bb79fea29a814f86c0f",
          "Name": "view",
          "Description": "View3D",
          "UsingDefaultValue": false,
          "Level": 2,
          "UseLevels": false,
          "KeepListStructure": false
        }
      ],
      "Outputs": [
        {
          "Id": "2864e1b5f1b345c687e31dd25c092ba1",
          "Name": "points",
          "Description": "var",
          "UsingDefaultValue": false,
          "Level": 2,
          "UseLevels": false,
          "KeepListStructure": false
        },
        {
          "Id": "19f476f1bc32498099d9a4a008ff54fa",
          "Name": "elements",
          "Description": "var",
          "UsingDefaultValue": false,
          "Level": 2,
          "UseLevels": false,
          "KeepListStructure": false
        }
      ],
      "Replication": "Auto",
      "Description": "Returns positions and elements hit by ray bounce from the specified origin point and direction\n\nRayBounce.ByOriginDirection (origin: Point, direction: Vector, maxBounces: int, view: View3D): var[]..[]"
    },
    {
      "ConcreteType": "Dynamo.Graph.Nodes.ZeroTouch.DSFunction, DynamoCore",
      "NodeType": "FunctionNode",
      "FunctionSignature": "Revit.Elements.StructuralFraming.Location",
      "Id": "92622abc89544f38ac78598ab21019e5",
      "Inputs": [
        {
          "Id": "339ba8cad3f348a78c9bd46f45b8ceda",
          "Name": "structuralFraming",
          "Description": "Revit.Elements.StructuralFraming",
          "UsingDefaultValue": false,
          "Level": 2,
          "UseLevels": false,
          "KeepListStructure": false
        }
      ],
      "Outputs": [
        {
          "Id": "2c1e3783e46d4ad48bd5075b68633c51",
          "Name": "Curve",
          "Description": "Curve",
          "UsingDefaultValue": false,
          "Level": 2,
          "UseLevels": false,
          "KeepListStructure": false
        }
      ],
      "Replication": "Auto",
      "Description": "Gets curve geometry from location of the specified structural element\n\nStructuralFraming.Location: Curve"
    },
    {
      "ConcreteType": "Dynamo.Graph.Nodes.ZeroTouch.DSFunction, DynamoCore",
      "NodeType": "FunctionNode",
      "FunctionSignature": "Autodesk.DesignScript.Geometry.Curve.PointAtParameter@double",
      "Id": "256a8d331e2140008e82fd85f452fa67",
      "Inputs": [
        {
          "Id": "d55b4074dd2242bc83df6eb762f3fe81",
          "Name": "curve",
          "Description": "Autodesk.DesignScript.Geometry.Curve",
          "UsingDefaultValue": false,
          "Level": 2,
          "UseLevels": false,
          "KeepListStructure": false
        },
        {
          "Id": "23e7e24bc4134e18867ae7517e47a073",
          "Name": "param",
          "Description": "The parameter at which to evaluate\n\ndouble\nDefault value : 0",
          "UsingDefaultValue": true,
          "Level": 2,
          "UseLevels": false,
          "KeepListStructure": false
        }
      ],
      "Outputs": [
        {
          "Id": "77ce6872273746ed85cd0efa5e9e6ac6",
          "Name": "Point",
          "Description": "Point",
          "UsingDefaultValue": false,
          "Level": 2,
          "UseLevels": false,
          "KeepListStructure": false
        }
      ],
      "Replication": "Auto",
      "Description": "Get a Point on the Curve at a specified parameter between StartParameter() and EndParameter()\n\nCurve.PointAtParameter (param: double = 0): Point"
    },
    {
      "ConcreteType": "Dynamo.Graph.Nodes.CodeBlockNodeModel, DynamoCore",
      "NodeType": "CodeBlockNode",
      "Code": "0.5;",
      "Id": "8a86fd1fda454e1a995a4ebccaa70cb2",
      "Inputs": [],
      "Outputs": [
        {
          "Id": "86362c6120bf494285ac8cd1b1d78ebf",
          "Name": "",
          "Description": "Value of expression at line 1",
          "UsingDefaultValue": false,
          "Level": 2,
          "UseLevels": false,
          "KeepListStructure": false
        }
      ],
      "Replication": "Disabled",
      "Description": "Allows for DesignScript code to be authored directly"
    },
    {
      "ConcreteType": "Dynamo.Graph.Nodes.ZeroTouch.DSFunction, DynamoCore",
      "NodeType": "FunctionNode",
      "FunctionSignature": "Autodesk.DesignScript.Geometry.Line.Direction",
      "Id": "0ebfe70cfd8a402cb13fd129f6f21ed3",
      "Inputs": [
        {
          "Id": "e44fc90f9e7e4077a4d14025e6cf6b1c",
          "Name": "line",
          "Description": "Autodesk.DesignScript.Geometry.Line",
          "UsingDefaultValue": false,
          "Level": 2,
          "UseLevels": false,
          "KeepListStructure": false
        }
      ],
      "Outputs": [
        {
          "Id": "2e90131e9e8b4ca6ae9066cbdbfc718d",
          "Name": "Vector",
          "Description": "Vector",
          "UsingDefaultValue": false,
          "Level": 2,
          "UseLevels": false,
          "KeepListStructure": false
        }
      ],
      "Replication": "Auto",
      "Description": "The direction of the Curve\n\nLine.Direction: Vector"
    },
    {
      "ConcreteType": "Dynamo.Graph.Nodes.CodeBlockNodeModel, DynamoCore",
      "NodeType": "CodeBlockNode",
      "Code": "1;",
      "Id": "af50e92ed99f4c11a997cf44d5074ea7",
      "Inputs": [],
      "Outputs": [
        {
          "Id": "27deb3c26f4544cc8100c8d0ba278717",
          "Name": "",
          "Description": "Value of expression at line 1",
          "UsingDefaultValue": false,
          "Level": 2,
          "UseLevels": false,
          "KeepListStructure": false
        }
      ],
      "Replication": "Disabled",
      "Description": "Allows for DesignScript code to be authored directly"
    },
    {
      "ConcreteType": "Dynamo.Graph.Nodes.ZeroTouch.DSFunction, DynamoCore",
      "NodeType": "FunctionNode",
      "FunctionSignature": "Revit.Application.Document.ActiveView",
      "Id": "0863bada00fc4fd8b27e9592e3669e04",
      "Inputs": [
        {
          "Id": "7caa912e478c4b8da74a879200549c95",
          "Name": "document",
          "Description": "Revit.Application.Document",
          "UsingDefaultValue": false,
          "Level": 2,
          "UseLevels": false,
          "KeepListStructure": false
        }
      ],
      "Outputs": [
        {
          "Id": "71e3638c7f964e6991ab907d9f015a3f",
          "Name": "View",
          "Description": "View",
          "UsingDefaultValue": false,
          "Level": 2,
          "UseLevels": false,
          "KeepListStructure": false
        }
      ],
      "Replication": "Auto",
      "Description": "Get the active view for the document\n\nDocument.ActiveView: View"
    },
    {
      "ConcreteType": "Dynamo.Graph.Nodes.ZeroTouch.DSFunction, DynamoCore",
      "NodeType": "FunctionNode",
      "FunctionSignature": "Revit.Application.Document.Current",
      "Id": "46fbded2deac42d8a795f6247760435d",
      "Inputs": [],
      "Outputs": [
        {
          "Id": "f33fa3a4b4e24f389cb5b13fbbd4198f",
          "Name": "Document",
          "Description": "Document",
          "UsingDefaultValue": false,
          "Level": 2,
          "UseLevels": false,
          "KeepListStructure": false
        }
      ],
      "Replication": "Auto",
      "Description": "Get the current document\n\nDocument.Current: Document"
    },
    {
      "ConcreteType": "Dynamo.Graph.Nodes.CodeBlockNodeModel, DynamoCore",
      "NodeType": "CodeBlockNode",
      "Code": "a;",
      "Id": "590cc0d0a4b8422daca21c1de01ba522",
      "Inputs": [
        {
          "Id": "50fa67dfa984483ca36a9d4f2529c3a7",
          "Name": "a",
          "Description": "a",
          "UsingDefaultValue": false,
          "Level": 2,
          "UseLevels": false,
          "KeepListStructure": false
        }
      ],
      "Outputs": [
        {
          "Id": "563600dfc21949c6921a889f7526dd09",
          "Name": "",
          "Description": "Value of expression at line 1",
          "UsingDefaultValue": false,
          "Level": 2,
          "UseLevels": false,
          "KeepListStructure": false
        }
      ],
      "Replication": "Disabled",
      "Description": "Allows for DesignScript code to be authored directly"
    },
    {
      "ConcreteType": "Dynamo.Graph.Nodes.CodeBlockNodeModel, DynamoCore",
      "NodeType": "CodeBlockNode",
      "Code": "b;",
      "Id": "4de8a283b1394dc5a1de7840bce8528a",
      "Inputs": [
        {
          "Id": "b6c7d15051c64ff8b56aca9d2027fe4a",
          "Name": "b",
          "Description": "b",
          "UsingDefaultValue": false,
          "Level": 2,
          "UseLevels": false,
          "KeepListStructure": false
        }
      ],
      "Outputs": [
        {
          "Id": "9214b4c9d96a48a082e4805984d9300e",
          "Name": "",
          "Description": "Value of expression at line 1",
          "UsingDefaultValue": false,
          "Level": 2,
          "UseLevels": false,
          "KeepListStructure": false
        }
      ],
      "Replication": "Disabled",
      "Description": "Allows for DesignScript code to be authored directly"
    },
    {
      "ConcreteType": "Dynamo.Graph.Nodes.CustomNodes.Function, DynamoCore",
      "FunctionSignature": "8fe565e9-1f46-4933-b75c-2ee2947e342e",
      "FunctionType": "Graph",
      "NodeType": "FunctionNode",
      "Id": "72a7d3ba4d324f1490cdc52b2376840a",
      "Inputs": [
        {
          "Id": "3e5543beff6d4ead88e7a3ee8739593b",
          "Name": "element",
          "Description": "var[]",
          "UsingDefaultValue": false,
          "Level": 2,
          "UseLevels": false,
          "KeepListStructure": false
        },
        {
          "Id": "11c990eabdb34068ad6879319abf20d1",
          "Name": "reset",
          "Description": "bool\nDefault value : true",
          "UsingDefaultValue": true,
          "Level": 2,
          "UseLevels": false,
          "KeepListStructure": false
        }
      ],
      "Outputs": [
        {
          "Id": "ddcce5acdc4b4db08a2f05ef64e99cbb",
          "Name": "success?",
          "Description": "return value",
          "UsingDefaultValue": false,
          "Level": 2,
          "UseLevels": false,
          "KeepListStructure": false
        }
      ],
      "Replication": "Auto",
      "Description": "Selects the input elements inside the Revit UI."
    },
    {
      "ConcreteType": "CoreNodeModels.Input.BoolSelector, CoreNodeModels",
      "NodeType": "BooleanInputNode",
      "InputValue": true,
      "Id": "ee9f7b496ab34663952b3ebc37ec13cb",
      "Inputs": [],
      "Outputs": [
        {
          "Id": "69bf02bd745c429f98f96009ea398787",
          "Name": "",
          "Description": "Boolean",
          "UsingDefaultValue": false,
          "Level": 2,
          "UseLevels": false,
          "KeepListStructure": false
        }
      ],
      "Replication": "Disabled",
      "Description": "Selection between a true and false."
    },
    {
      "ConcreteType": "Dynamo.Graph.Nodes.CodeBlockNodeModel, DynamoCore",
      "NodeType": "CodeBlockNode",
      "Code": "1;",
      "Id": "58e2924da2e549039a24951d55ab0c66",
      "Inputs": [],
      "Outputs": [
        {
          "Id": "a1e1b80fe0924343bb476dd6ff5369db",
          "Name": "",
          "Description": "Value of expression at line 1",
          "UsingDefaultValue": false,
          "Level": 2,
          "UseLevels": false,
          "KeepListStructure": false
        }
      ],
      "Replication": "Disabled",
      "Description": "Allows for DesignScript code to be authored directly"
    }
  ],
  "Connectors": [
    {
      "Start": "53199e0ff10b41e687107b915c66d858",
      "End": "6b8e9d0817a94d39abd9d3cd22cc0025",
      "Id": "a85f82f08284468894cda2ae40486396"
    },
    {
      "Start": "7ec6713c7e5248ea865c0478c076b7db",
      "End": "e7eeb4d364dd4690996ab8299031744b",
      "Id": "9a41515c2a8d45f8a5ee42539cd769d4"
    },
    {
      "Start": "7ec6713c7e5248ea865c0478c076b7db",
      "End": "cedd5e67efde48548ae26c846341b02b",
      "Id": "def1063655904c5391e320ee7e15f90c"
    },
    {
      "Start": "64817d007e7d4c4c93c2e46c37f042df",
      "End": "13e79f241a7e44709c7120a5ec989b2b",
      "Id": "abe3db8b71d043c7847523ce28eb1f2b"
    },
    {
      "Start": "64817d007e7d4c4c93c2e46c37f042df",
      "End": "339ba8cad3f348a78c9bd46f45b8ceda",
      "Id": "ea4ac8a3eec44c1e939c5103dd95c519"
    },
    {
      "Start": "64817d007e7d4c4c93c2e46c37f042df",
      "End": "3e5543beff6d4ead88e7a3ee8739593b",
      "Id": "9e41eb2019be4727a35705e9521cde29"
    },
    {
      "Start": "2c729aceb9e240b3bf63fe0d942f3ef4",
      "End": "2ac8ada5f8ef4ded81d63e59ef80606b",
      "Id": "4f17a30eec3d4ee5af40eda83c295d1d"
    },
    {
      "Start": "3c22198329194da6b3f76611cf97b21a",
      "End": "aacb6554805e439dbc93c2ef4f5a9032",
      "Id": "471b671f55de4746ad7220f432b4fd4d"
    },
    {
      "Start": "a1bbf6605810427c819d18467eee7928",
      "End": "6aa6c12d864c4320b55b9ddb9ad41cec",
      "Id": "e5ce5771c274440d86f25d438422d69f"
    },
    {
      "Start": "865d25c95fca4b268d711665076bc4eb",
      "End": "e467fcfa18b147b9bff9b55574dfc0fd",
      "Id": "314517582ce34b86adbcb10e53bd3212"
    },
    {
      "Start": "2864e1b5f1b345c687e31dd25c092ba1",
      "End": "50fa67dfa984483ca36a9d4f2529c3a7",
      "Id": "9a7bee91bba14a889a293ebc1db884b0"
    },
    {
      "Start": "19f476f1bc32498099d9a4a008ff54fa",
      "End": "b6c7d15051c64ff8b56aca9d2027fe4a",
      "Id": "564431623e0e4d11a7a71bdd9f3d4196"
    },
    {
      "Start": "2c1e3783e46d4ad48bd5075b68633c51",
      "End": "d55b4074dd2242bc83df6eb762f3fe81",
      "Id": "0563a4ec92d84196ae1af181e6e1aa19"
    },
    {
      "Start": "2c1e3783e46d4ad48bd5075b68633c51",
      "End": "e44fc90f9e7e4077a4d14025e6cf6b1c",
      "Id": "3735a9d97fea47c08e068129a91d066c"
    },
    {
      "Start": "77ce6872273746ed85cd0efa5e9e6ac6",
      "End": "0d1445eebe854cdd82dd1fe405938128",
      "Id": "26116a752bc24778a85657e108322d1f"
    },
    {
      "Start": "86362c6120bf494285ac8cd1b1d78ebf",
      "End": "23e7e24bc4134e18867ae7517e47a073",
      "Id": "173db62502714fd79b54d30078f840ba"
    },
    {
      "Start": "2e90131e9e8b4ca6ae9066cbdbfc718d",
      "End": "3d48c92d07d342d3be16f445e8a9c300",
      "Id": "18c34f8750f748b2aa791bfb21a16dc6"
    },
    {
      "Start": "27deb3c26f4544cc8100c8d0ba278717",
      "End": "1952120ca0f84fa0b056ae15ed3beb21",
      "Id": "6d85cb0fbbad400ca7fb54ec264f6d5b"
    },
    {
      "Start": "71e3638c7f964e6991ab907d9f015a3f",
      "End": "257d52fa05e14bb79fea29a814f86c0f",
      "Id": "4df28020359c4de0b82b7d9fe7742d73"
    },
    {
      "Start": "f33fa3a4b4e24f389cb5b13fbbd4198f",
      "End": "7caa912e478c4b8da74a879200549c95",
      "Id": "98f350a50355419087c1ae8088f7e5e9"
    },
    {
      "Start": "69bf02bd745c429f98f96009ea398787",
      "End": "e353ede55f5b4f87b723ebf1c6486885",
      "Id": "1b32b36eeb7d4f9bbf51477563aefb2a"
    },
    {
      "Start": "a1e1b80fe0924343bb476dd6ff5369db",
      "End": "11c990eabdb34068ad6879319abf20d1",
      "Id": "78ac32dc2aea4b8db707fe3409eb2c50"
    }
  ],
  "Dependencies": [
    "8fe565e9-1f46-4933-b75c-2ee2947e342e"
  ],
  "Bindings": [],
  "View": {
    "Dynamo": {
      "ScaleFactor": 1.0,
      "HasRunWithoutCrash": true,
      "IsVisibleInDynamoLibrary": true,
      "Version": "2.1.0.5696",
      "RunType": "Manual",
      "RunPeriod": "1000"
    },
    "Camera": {
      "Name": "Background Preview",
      "EyeX": -17.0,
      "EyeY": 24.0,
      "EyeZ": 50.0,
      "LookX": 12.0,
      "LookY": -13.0,
      "LookZ": -58.0,
      "UpX": 0.0,
      "UpY": 1.0,
      "UpZ": 0.0
    },
    "NodeViews": [
      {
        "ShowGeometry": true,
        "Name": "Python Script",
        "Id": "97245ad738674c72a92335cc38a8c69b",
        "IsSetAsInput": false,
        "IsSetAsOutput": false,
        "Excluded": false,
        "X": 550.060086442102,
        "Y": 340.901114041302
      },
      {
        "ShowGeometry": true,
        "Name": "Select Model Element",
        "Id": "511769dae45944b99186730c712882d7",
        "IsSetAsInput": false,
        "IsSetAsOutput": false,
        "Excluded": false,
        "X": 240.00000000000003,
        "Y": 407.427410855409
      },
      {
        "ShowGeometry": true,
        "Name": "Family Types",
        "Id": "276a1592b51f4568aebdd614d993d7a4",
        "IsSetAsInput": false,
        "IsSetAsOutput": false,
        "Excluded": false,
        "X": 337.01384909354761,
        "Y": 606.49248358075124
      },
      {
        "ShowGeometry": true,
        "Name": "Python Script",
        "Id": "a993533024724d8086ea06b40be7cddf",
        "IsSetAsInput": false,
        "IsSetAsOutput": false,
        "Excluded": false,
        "X": 877.09394793836429,
        "Y": 242.84618541532728
      },
      {
        "ShowGeometry": true,
        "Name": "FamilyInstance.ByFace",
        "Id": "30da03c8e6394d5f9c597d9cc4862462",
        "IsSetAsInput": false,
        "IsSetAsOutput": false,
        "Excluded": true,
        "X": 1419.502640755675,
        "Y": 618.18323155607368
      },
      {
        "ShowGeometry": true,
        "Name": "Vector.Reverse",
        "Id": "a98b5394ade84fa2a63985dc044bac90",
        "IsSetAsInput": false,
        "IsSetAsOutput": false,
        "Excluded": false,
        "X": 892.79454079940717,
        "Y": 928.03211573356566
      },
      {
        "ShowGeometry": true,
        "Name": "Vector.XAxis",
        "Id": "320c3df8436f473cb9a58a761639f62d",
        "IsSetAsInput": false,
        "IsSetAsOutput": false,
        "Excluded": false,
        "X": 676.53452419591349,
        "Y": 931.05177367736076
      },
      {
        "ShowGeometry": true,
        "Name": "Select Face",
        "Id": "1f6e74b70a6f46769e8af46ba9594d9d",
        "IsSetAsInput": false,
        "IsSetAsOutput": false,
        "Excluded": false,
        "X": 844.776704649742,
        "Y": 795.14981264509163
      },
      {
        "ShowGeometry": true,
        "Name": "All Elements In Active View",
        "Id": "307120ed71da403eb3606e947da00ba1",
        "IsSetAsInput": false,
        "IsSetAsOutput": false,
        "Excluded": false,
        "X": 530.52902627952847,
        "Y": 242.35985613157533
      },
      {
        "ShowGeometry": true,
        "Name": "RayBounce.ByOriginDirection",
        "Id": "b0ff550d0c9c4519a55a6a35268addc4",
        "IsSetAsInput": false,
        "IsSetAsOutput": false,
        "Excluded": false,
        "X": 1709.4819657299124,
        "Y": 1175.257026445965
      },
      {
        "ShowGeometry": true,
        "Name": "StructuralFraming.Location",
        "Id": "92622abc89544f38ac78598ab21019e5",
        "IsSetAsInput": false,
        "IsSetAsOutput": false,
        "Excluded": false,
        "X": 566.75405911470682,
        "Y": 1125.8703344312712
      },
      {
        "ShowGeometry": true,
        "Name": "Curve.PointAtParameter",
        "Id": "256a8d331e2140008e82fd85f452fa67",
        "IsSetAsInput": false,
        "IsSetAsOutput": false,
        "Excluded": false,
        "X": 1176.2154455598752,
        "Y": 876.10130668183649
      },
      {
        "ShowGeometry": true,
        "Name": "Code Block",
        "Id": "8a86fd1fda454e1a995a4ebccaa70cb2",
        "IsSetAsInput": false,
        "IsSetAsOutput": false,
        "Excluded": false,
        "X": 707.0,
        "Y": 1223.0
      },
      {
        "ShowGeometry": true,
        "Name": "Line.Direction",
        "Id": "0ebfe70cfd8a402cb13fd129f6f21ed3",
        "IsSetAsInput": false,
        "IsSetAsOutput": false,
        "Excluded": false,
        "X": 989.38751601453259,
        "Y": 1349.2240917169388
      },
      {
        "ShowGeometry": true,
        "Name": "Code Block",
        "Id": "af50e92ed99f4c11a997cf44d5074ea7",
        "IsSetAsInput": false,
        "IsSetAsOutput": false,
        "Excluded": false,
        "X": 1259.0,
        "Y": 1374.0
      },
      {
        "ShowGeometry": true,
        "Name": "Document.ActiveView",
        "Id": "0863bada00fc4fd8b27e9592e3669e04",
        "IsSetAsInput": false,
        "IsSetAsOutput": false,
        "Excluded": false,
        "X": 1084.3462990521516,
        "Y": 1466.9194847776496
      },
      {
        "ShowGeometry": true,
        "Name": "Document.Current",
        "Id": "46fbded2deac42d8a795f6247760435d",
        "IsSetAsInput": false,
        "IsSetAsOutput": false,
        "Excluded": false,
        "X": 723.23543397951585,
        "Y": 1481.6314089102384
      },
      {
        "ShowGeometry": true,
        "Name": "Code Block",
        "Id": "590cc0d0a4b8422daca21c1de01ba522",
        "IsSetAsInput": false,
        "IsSetAsOutput": false,
        "Excluded": false,
        "X": 2288.0887487144714,
        "Y": 1165.9224318883016
      },
      {
        "ShowGeometry": true,
        "Name": "Code Block",
        "Id": "4de8a283b1394dc5a1de7840bce8528a",
        "IsSetAsInput": false,
        "IsSetAsOutput": false,
        "Excluded": false,
        "X": 2301.3706498457364,
        "Y": 1553.0143955620622
      },
      {
        "ShowGeometry": true,
        "Name": "Springs.SelectInRevit",
        "Id": "72a7d3ba4d324f1490cdc52b2376840a",
        "IsSetAsInput": false,
        "IsSetAsOutput": false,
        "Excluded": false,
        "X": 1399.560181146953,
        "Y": 225.39160978652265
      },
      {
        "ShowGeometry": true,
        "Name": "Boolean",
        "Id": "ee9f7b496ab34663952b3ebc37ec13cb",
        "IsSetAsInput": false,
        "IsSetAsOutput": false,
        "Excluded": false,
        "X": 322.38746289760036,
        "Y": 249.847543534186
      },
      {
        "ShowGeometry": true,
        "Name": "Code Block",
        "Id": "58e2924da2e549039a24951d55ab0c66",
        "IsSetAsInput": false,
        "IsSetAsOutput": false,
        "Excluded": false,
        "X": 1196.0,
        "Y": 286.0
      }
    ],
    "Annotations": [],
    "X": -266.01240586141466,
    "Y": 28.242850489105649,
    "Zoom": 0.89957718347605586
  }
}