<Workspace Version="1.3.2.2480" X="0" Y="0" zoom="1" ScaleFactor="1" Name="Home" Description="" RunType="Manual" RunPeriod="1000" HasRunWithoutCrash="True">
  <NamespaceResolutionMap />
  <Elements>
    <PythonNodeModels.PythonNode guid="0fcf046a-b061-40c1-9ab0-ab2af9388920" type="PythonNodeModels.PythonNode" nickname="Python Script" x="476" y="223" isVisible="true" isUpstreamVisible="true" lacing="Disabled" isSelectedInput="False" IsFrozen="false" isPinned="true" inputcount="1">
      <PortInfo index="0" default="False" />
      <Script>import clr
clr.AddReference('ProtoGeometry')
from Autodesk.DesignScript.Geometry import *
#The inputs to this node will be stored as a list in the IN variables.


items = ["v0", "v1", "v2", "v3"]
outer = []
for i in range(len(items)): 
	for j in range(i+1, len(items)):
		outer.append([items[i],items[j]])
		
		
#Assign your output to the OUT variable.
#OUT = [(items[i],items[j]) for i in range(len(items)) for j in range(i+1, len(items))]

OUT = outer

</Script>
    </PythonNodeModels.PythonNode>
  </Elements>
  <Connectors />
  <Notes />
  <Annotations />
  <Presets />
  <Cameras>
    <Camera Name="Background Preview" eyeX="-0.204873562063205" eyeY="1.26361302556847" eyeZ="2.90688888330549" lookX="0.704873562063205" lookY="-0.763613025568472" lookZ="-3.40688888330549" upX="0" upY="1" upZ="0" />
  </Cameras>
</Workspace>