<Workspace Version="1.3.2.2480" X="-3541.86510802269" Y="264.026143050818" zoom="1.15121239841854" ScaleFactor="1" Name="Home" Description="" RunType="Manual" RunPeriod="1000" HasRunWithoutCrash="True">
  <NamespaceResolutionMap />
  <Elements>
    <Dynamo.Nodes.DSModelElementsSelection guid="8c5d3dbe-79cb-43d5-a541-dd1131aad748" type="Dynamo.Nodes.DSModelElementsSelection" nickname="Select Model Elements" x="572.594711603141" y="130.358863001185" isVisible="true" isUpstreamVisible="true" lacing="Disabled" isSelectedInput="True" IsFrozen="false" isPinned="false">
      <instance id="9e9a6a43-04ae-45dd-b6c5-16884893d438-0022e5ca" />
      <instance id="96b73755-ffbe-41a5-862c-6a2d7b51e734-004166a2" />
      <instance id="96b73755-ffbe-41a5-862c-6a2d7b51e734-004166a3" />
      <instance id="96b73755-ffbe-41a5-862c-6a2d7b51e734-004166a4" />
    </Dynamo.Nodes.DSModelElementsSelection>
    <Dynamo.Graph.Nodes.CustomNodes.Function guid="5e070691-832f-4346-9943-42662a0724a9" type="Dynamo.Graph.Nodes.CustomNodes.Function" nickname="Surface.FilterByOrientation" x="1317.23026671802" y="129.209748618394" isVisible="false" isUpstreamVisible="true" lacing="Shortest" isSelectedInput="False" IsFrozen="false" isPinned="true">
      <PortInfo index="0" default="False" />
      <ID value="3325a597-4c74-4292-9152-66b7177b27f1" />
      <Name value="Surface.FilterByOrientation" />
      <Description value="Sorts surfaces in three lists based on their orientation (vertical, horizontal up &amp; horizontal down) and also returns three corresponding lists of booleans." />
      <Inputs>
        <Input value="surfaces" />
      </Inputs>
      <Outputs>
        <Output value="vertical" />
        <Output value="isVertical" />
        <Output value="horizontalUp" />
        <Output value="isHorizontalUp" />
        <Output value="horizontalDown" />
        <Output value="isHorizontalDown" />
      </Outputs>
    </Dynamo.Graph.Nodes.CustomNodes.Function>
    <Dynamo.Graph.Nodes.ZeroTouch.DSFunction guid="802f3d5f-9c7d-45c2-9f97-b2e48c4d3328" type="Dynamo.Graph.Nodes.ZeroTouch.DSFunction" nickname="Surface.NormalAtParameter" x="1902.32821671715" y="222.565360673299" isVisible="true" isUpstreamVisible="true" lacing="Shortest" isSelectedInput="False" IsFrozen="false" isPinned="false" assembly="ProtoGeometry.dll" function="Autodesk.DesignScript.Geometry.Surface.NormalAtParameter@double,double">
      <PortInfo index="0" default="False" />
      <PortInfo index="1" default="True" />
      <PortInfo index="2" default="True" />
    </Dynamo.Graph.Nodes.ZeroTouch.DSFunction>
    <Dynamo.Graph.Nodes.ZeroTouch.DSFunction guid="02df0134-fd87-4fa6-9bb8-5aa86da75a35" type="Dynamo.Graph.Nodes.ZeroTouch.DSFunction" nickname="Vector.IsParallel" x="2148.24476625134" y="385.422511123426" isVisible="true" isUpstreamVisible="true" lacing="Shortest" isSelectedInput="False" IsFrozen="false" isPinned="false" assembly="ProtoGeometry.dll" function="Autodesk.DesignScript.Geometry.Vector.IsParallel@Autodesk.DesignScript.Geometry.Vector">
      <PortInfo index="0" default="False" />
      <PortInfo index="1" default="False" />
    </Dynamo.Graph.Nodes.ZeroTouch.DSFunction>
    <Dynamo.Graph.Nodes.ZeroTouch.DSFunction guid="e62bb2c2-85c6-409e-ad32-ab82ee352e35" type="Dynamo.Graph.Nodes.ZeroTouch.DSFunction" nickname="List.FilterByBoolMask" x="2417.0879659783" y="136.051409462929" isVisible="false" isUpstreamVisible="true" lacing="Shortest" isSelectedInput="False" IsFrozen="false" isPinned="true" assembly="DSCoreNodes.dll" function="DSCore.List.FilterByBoolMask@var[]..[],var[]..[]">
      <PortInfo index="0" default="False" />
      <PortInfo index="1" default="False" />
    </Dynamo.Graph.Nodes.ZeroTouch.DSFunction>
    <Dynamo.Graph.Nodes.ZeroTouch.DSFunction guid="b6add728-3858-4992-a87e-76b1b6c900ff" type="Dynamo.Graph.Nodes.ZeroTouch.DSFunction" nickname="Flatten" x="3330.70709606091" y="235.246206280359" isVisible="false" isUpstreamVisible="true" lacing="Shortest" isSelectedInput="False" IsFrozen="false" isPinned="true" assembly="BuiltIn" function="Flatten@var[]..[]">
      <PortInfo index="0" default="False" />
    </Dynamo.Graph.Nodes.ZeroTouch.DSFunction>
    <Dynamo.Graph.Nodes.ZeroTouch.DSFunction guid="c4cc4f7a-b680-4b5b-97b1-7b015088be29" type="Dynamo.Graph.Nodes.ZeroTouch.DSFunction" nickname="Topology.Faces" x="1039.39089085148" y="125.600240797843" isVisible="false" isUpstreamVisible="true" lacing="Shortest" isSelectedInput="False" IsFrozen="false" isPinned="true" assembly="ProtoGeometry.dll" function="Autodesk.DesignScript.Geometry.Topology.Faces">
      <PortInfo index="0" default="False" />
    </Dynamo.Graph.Nodes.ZeroTouch.DSFunction>
    <Dynamo.Graph.Nodes.CustomNodes.Function guid="f5ace91e-b6b3-4728-b41f-ae357f62a07c" type="Dynamo.Graph.Nodes.CustomNodes.Function" nickname="RevitFaceReference.FromDynamoSurface" x="3662.15581023863" y="385.820806254776" isVisible="false" isUpstreamVisible="true" lacing="Shortest" isSelectedInput="False" IsFrozen="false" isPinned="true">
      <PortInfo index="0" default="False" />
      <ID value="3204925d-0493-4b8b-b42b-fb0d8041837b" />
      <Name value="RevitFaceReference.FromDynamoSurface" />
      <Description value="Returns the underlying Revit face reference of a given surface" />
      <Inputs>
        <Input value="DynamoSurface" />
      </Inputs>
      <Outputs>
        <Output value="RevitFaceReference" />
      </Outputs>
    </Dynamo.Graph.Nodes.CustomNodes.Function>
    <Dynamo.Graph.Nodes.ZeroTouch.DSFunction guid="67ac024f-25fb-4426-b20d-eb8731085157" type="Dynamo.Graph.Nodes.ZeroTouch.DSFunction" nickname="Vector.XAxis" x="1717.79979054467" y="461.09657671697" isVisible="true" isUpstreamVisible="true" lacing="Shortest" isSelectedInput="False" IsFrozen="false" isPinned="false" assembly="ProtoGeometry.dll" function="Autodesk.DesignScript.Geometry.Vector.XAxis" />
    <Dynamo.Nodes.DSModelElementsSelection guid="2333f04a-7930-4e7c-a0a1-4f2e3bc739ef" type="Dynamo.Nodes.DSModelElementsSelection" nickname="Select Model Elements" x="3693.74860723538" y="86.7832524973703" isVisible="true" isUpstreamVisible="true" lacing="Disabled" isSelectedInput="True" IsFrozen="false" isPinned="false">
      <instance id="96b73755-ffbe-41a5-862c-6a2d7b51e734-004173bc" />
    </Dynamo.Nodes.DSModelElementsSelection>
    <Dynamo.Graph.Nodes.ZeroTouch.DSFunction guid="48b175f0-168b-4f74-8fe7-f963571cd7fb" type="Dynamo.Graph.Nodes.ZeroTouch.DSFunction" nickname="Vector.YAxis" x="1691.93382877097" y="562.098313270408" isVisible="true" isUpstreamVisible="true" lacing="Shortest" isSelectedInput="False" IsFrozen="false" isPinned="false" assembly="ProtoGeometry.dll" function="Autodesk.DesignScript.Geometry.Vector.YAxis" />
    <Dynamo.Graph.Nodes.ZeroTouch.DSFunction guid="50f74da4-ccea-4f3c-9539-6ac5205fc768" type="Dynamo.Graph.Nodes.ZeroTouch.DSFunction" nickname="Surface.Area" x="3996.22903553314" y="-230.592382427983" isVisible="true" isUpstreamVisible="true" lacing="Shortest" isSelectedInput="False" IsFrozen="false" isPinned="true" assembly="ProtoGeometry.dll" function="Autodesk.DesignScript.Geometry.Surface.Area">
      <PortInfo index="0" default="False" />
    </Dynamo.Graph.Nodes.ZeroTouch.DSFunction>
    <Dynamo.Graph.Nodes.ZeroTouch.DSFunction guid="ccbb5765-ebc8-4f8b-bbd2-ba1c3e4c51e3" type="Dynamo.Graph.Nodes.ZeroTouch.DSFunction" nickname="List.GetItemAtIndex" x="3024.29701403957" y="202.24397202195" isVisible="true" isUpstreamVisible="true" lacing="Shortest" isSelectedInput="False" IsFrozen="false" isPinned="true" assembly="DSCoreNodes.dll" function="DSCore.List.GetItemAtIndex@var[]..[],int">
      <PortInfo index="0" default="False" useLevels="True" level="2" shouldKeepListStructure="False" />
      <PortInfo index="1" default="False" />
    </Dynamo.Graph.Nodes.ZeroTouch.DSFunction>
    <Dynamo.Graph.Nodes.CodeBlockNodeModel guid="9d9b082e-4509-41a2-86c1-d441523ed1e9" type="Dynamo.Graph.Nodes.CodeBlockNodeModel" nickname="Code Block" x="2843.07358974669" y="287.089828277593" isVisible="true" isUpstreamVisible="true" lacing="Disabled" isSelectedInput="False" IsFrozen="false" isPinned="false" CodeText="{0,1};" ShouldFocus="false" />
    <PythonNodeModels.PythonNode guid="60145d63-ba5a-4ef3-a58e-63e767b688ad" type="PythonNodeModels.PythonNode" nickname="Python Script" x="3761.47431095679" y="260.812219790205" isVisible="true" isUpstreamVisible="true" lacing="Disabled" isSelectedInput="False" IsFrozen="false" isPinned="false" inputcount="1">
      <PortInfo index="0" default="False" />
      <Script>import clr
clr.AddReference('RevitAPI')
from Autodesk.Revit.DB import *

faces = UnwrapElement(IN[0])
elementlist = list()
for face in faces:
	try:
		ref = face.Tags.LookupTag("RevitFaceReference")
		elementlist.append(ref)
	except:
		elementlist.append(list())
OUT = elementlist</Script>
    </PythonNodeModels.PythonNode>
    <Dynamo.Graph.Nodes.ZeroTouch.DSFunction guid="eff9bc6c-bb74-48b4-b5dd-b2e6ea05f0ea" type="Dynamo.Graph.Nodes.ZeroTouch.DSFunction" nickname="Vector.ZAxis" x="1732.23143389743" y="675.510961117785" isVisible="true" isUpstreamVisible="true" lacing="Shortest" isSelectedInput="False" IsFrozen="false" isPinned="false" assembly="ProtoGeometry.dll" function="Autodesk.DesignScript.Geometry.Vector.ZAxis" />
    <PythonNodeModels.PythonNode guid="2bc92fa9-ec51-4801-b35f-3855408c84f7" type="PythonNodeModels.PythonNode" nickname="Python Script" x="4007.57102911734" y="203.61191011252" isVisible="true" isUpstreamVisible="true" lacing="Disabled" isSelectedInput="False" IsFrozen="false" isPinned="true" inputcount="2">
      <PortInfo index="0" default="False" />
      <PortInfo index="1" default="False" />
      <Script>import clr
clr.AddReference('ProtoGeometry')
from Autodesk.DesignScript.Geometry import *

clr.AddReference("RevitNodes")
import Revit

from Revit.Elements import *

clr.AddReference('RevitAPI')
from Autodesk.Revit.DB import *

clr.AddReference("RevitServices")
import RevitServices
from RevitServices.Persistence import DocumentManager
from RevitServices.Transactions import TransactionManager

dataEnteringNode = IN

doc = DocumentManager.Instance.CurrentDBDocument

line = UnwrapElement(IN[0]).GeometryCurve
elements=(IN[1])
dim = 0

elementsRef = ReferenceArray()
opt=Options()
opt.ComputeReferences=True
opt.IncludeNonVisibleObjects=True
opt.View=doc.ActiveView
for element in elements:
	elementsRef.Append(element)
TransactionManager.Instance.EnsureInTransaction(doc)

dim=doc.Create.NewDimension(doc.ActiveView, line, elementsRef)
(True)

TransactionManager.Instance.TransactionTaskDone()

OUT = dim
</Script>
    </PythonNodeModels.PythonNode>
  </Elements>
  <Connectors>
    <Dynamo.Graph.Connectors.ConnectorModel start="8c5d3dbe-79cb-43d5-a541-dd1131aad748" start_index="0" end="c4cc4f7a-b680-4b5b-97b1-7b015088be29" end_index="0" portType="0" />
    <Dynamo.Graph.Connectors.ConnectorModel start="5e070691-832f-4346-9943-42662a0724a9" start_index="0" end="802f3d5f-9c7d-45c2-9f97-b2e48c4d3328" end_index="0" portType="0" />
    <Dynamo.Graph.Connectors.ConnectorModel start="5e070691-832f-4346-9943-42662a0724a9" start_index="0" end="e62bb2c2-85c6-409e-ad32-ab82ee352e35" end_index="0" portType="0" />
    <Dynamo.Graph.Connectors.ConnectorModel start="802f3d5f-9c7d-45c2-9f97-b2e48c4d3328" start_index="0" end="02df0134-fd87-4fa6-9bb8-5aa86da75a35" end_index="0" portType="0" />
    <Dynamo.Graph.Connectors.ConnectorModel start="02df0134-fd87-4fa6-9bb8-5aa86da75a35" start_index="0" end="e62bb2c2-85c6-409e-ad32-ab82ee352e35" end_index="1" portType="0" />
    <Dynamo.Graph.Connectors.ConnectorModel start="e62bb2c2-85c6-409e-ad32-ab82ee352e35" start_index="0" end="50f74da4-ccea-4f3c-9539-6ac5205fc768" end_index="0" portType="0" />
    <Dynamo.Graph.Connectors.ConnectorModel start="e62bb2c2-85c6-409e-ad32-ab82ee352e35" start_index="0" end="ccbb5765-ebc8-4f8b-bbd2-ba1c3e4c51e3" end_index="0" portType="0" />
    <Dynamo.Graph.Connectors.ConnectorModel start="b6add728-3858-4992-a87e-76b1b6c900ff" start_index="0" end="f5ace91e-b6b3-4728-b41f-ae357f62a07c" end_index="0" portType="0" />
    <Dynamo.Graph.Connectors.ConnectorModel start="b6add728-3858-4992-a87e-76b1b6c900ff" start_index="0" end="60145d63-ba5a-4ef3-a58e-63e767b688ad" end_index="0" portType="0" />
    <Dynamo.Graph.Connectors.ConnectorModel start="c4cc4f7a-b680-4b5b-97b1-7b015088be29" start_index="0" end="5e070691-832f-4346-9943-42662a0724a9" end_index="0" portType="0" />
    <Dynamo.Graph.Connectors.ConnectorModel start="2333f04a-7930-4e7c-a0a1-4f2e3bc739ef" start_index="0" end="2bc92fa9-ec51-4801-b35f-3855408c84f7" end_index="0" portType="0" />
    <Dynamo.Graph.Connectors.ConnectorModel start="48b175f0-168b-4f74-8fe7-f963571cd7fb" start_index="0" end="02df0134-fd87-4fa6-9bb8-5aa86da75a35" end_index="1" portType="0" />
    <Dynamo.Graph.Connectors.ConnectorModel start="ccbb5765-ebc8-4f8b-bbd2-ba1c3e4c51e3" start_index="0" end="b6add728-3858-4992-a87e-76b1b6c900ff" end_index="0" portType="0" />
    <Dynamo.Graph.Connectors.ConnectorModel start="9d9b082e-4509-41a2-86c1-d441523ed1e9" start_index="0" end="ccbb5765-ebc8-4f8b-bbd2-ba1c3e4c51e3" end_index="1" portType="0" />
    <Dynamo.Graph.Connectors.ConnectorModel start="60145d63-ba5a-4ef3-a58e-63e767b688ad" start_index="0" end="2bc92fa9-ec51-4801-b35f-3855408c84f7" end_index="1" portType="0" />
  </Connectors>
  <Notes />
  <Annotations>
    <Dynamo.Graph.Annotations.AnnotationModel guid="1655ffcf-0b45-4660-b4c3-96e262003944" annotationText="Select Line" left="3683.74860723538" top="40.7832524973703" width="207" height="165" fontSize="30" InitialTop="86.7832524973703" InitialHeight="149" TextblockHeight="36" backgrouund="#FFC1D676">
      <Models ModelGuid="2333f04a-7930-4e7c-a0a1-4f2e3bc739ef" />
    </Dynamo.Graph.Annotations.AnnotationModel>
    <Dynamo.Graph.Annotations.AnnotationModel guid="3804e93e-3c71-4691-9c5b-f4bd5897fd70" annotationText="Select beams" left="562.594711603141" top="84.3588630011848" width="258" height="182" fontSize="30" InitialTop="130.358863001185" InitialHeight="182" TextblockHeight="36" backgrouund="#FFC1D676">
      <Models ModelGuid="8c5d3dbe-79cb-43d5-a541-dd1131aad748" />
    </Dynamo.Graph.Annotations.AnnotationModel>
    <Dynamo.Graph.Annotations.AnnotationModel guid="860c9ab1-7b84-473f-aa36-1c092b97bbe2" annotationText=" Swap if beams are horizontal or verticals" left="1681.93382877097" top="271.09657671697" width="143.063333333333" height="384.001736553438" fontSize="30" InitialTop="461.09657671697" InitialHeight="220.203065344066" TextblockHeight="180" backgrouund="#FFC1D676">
      <Models ModelGuid="67ac024f-25fb-4426-b20d-eb8731085157" />
      <Models ModelGuid="48b175f0-168b-4f74-8fe7-f963571cd7fb" />
    </Dynamo.Graph.Annotations.AnnotationModel>
  </Annotations>
  <Presets />
  <Cameras>
    <Camera Name="Background Preview" eyeX="-2393.55541992188" eyeY="6409.75341796875" eyeZ="12603.458984375" lookX="1214.50964355469" lookY="-9359.6982421875" lookZ="-12190.705078125" upX="0.0418963097035885" upY="0.906307816505432" upZ="-0.420536428689957" />
  </Cameras>
</Workspace>