<Workspace Version="1.3.3.4651" X="227" Y="32" zoom="1" ScaleFactor="1" Name="Home" Description="" RunType="Manual" RunPeriod="1000" HasRunWithoutCrash="True">
  <NamespaceResolutionMap />
  <Elements>
    <CoreNodeModels.Input.Filename guid="5c8b438e-7adc-4fc5-9832-dd85f435e52b" type="CoreNodeModels.Input.Filename" nickname="File Path" x="-18" y="265" isVisible="true" isUpstreamVisible="true" lacing="Disabled" isSelectedInput="True" IsFrozen="false" isPinned="false">
      <System.String>..\Documents\GioBro\Arup_Beam_Steel Asymmetric I Section.rfa</System.String>
      <HintPath>C:\Users\giovanni.brogiolo\Documents\GioBro\Arup_Beam_Steel Asymmetric I Section.rfa</HintPath>
    </CoreNodeModels.Input.Filename>
    <PythonNodeModels.PythonNode guid="c79d2ac7-adc0-41b5-84eb-017cdb4a902e" type="PythonNodeModels.PythonNode" nickname="Python Script" x="564.357678976246" y="265.110873506085" isVisible="true" isUpstreamVisible="true" lacing="Disabled" isSelectedInput="False" IsFrozen="false" isPinned="true" inputcount="2">
      <PortInfo index="0" default="False" />
      <PortInfo index="1" default="False" />
      <Script>import clr

clr.AddReference("RevitServices")
import RevitServices
from RevitServices.Persistence import DocumentManager
from RevitServices.Transactions import TransactionManager

clr.AddReference('RevitAPI')
clr.AddReference('RevitAPIUI')
from Autodesk.Revit.DB import *
from Autodesk.Revit.UI import *

doc = DocumentManager.Instance.CurrentDBDocument
uidoc=DocumentManager.Instance.CurrentUIApplication.ActiveUIDocument

app = DocumentManager.Instance.CurrentUIApplication.Application

filePath = IN[0]

open_file = app.OpenDocumentFile(filePath)

fm = open_file.FamilyManager

deleted = 0
error = []

y = Transaction(open_file, "Put in parameter")

y.Start()

subTr = SubTransaction(open_file)
subTr.Start()

familyTypes = fm.Types

count = familyTypes.Size

while count &gt; 1:
	fm.DeleteCurrentType()
	count -=1

try:
	fm.RenameCurrentType("Default")
except:
	error.append("Default Type already present")

#run the purge command

familyApp = open_file.Application;
uiapp = UIApplication( familyApp )


pCmd = RevitCommandId.LookupPostableCommandId(PostableCommand.PurgeUnused)
uiapp.PostCommand(pCmd)



subTr.Commit()

y.Commit()

open_file.Close()

OUT = count</Script>
    </PythonNodeModels.PythonNode>
    <CoreNodeModels.Input.BoolSelector guid="028cbfff-40a2-415c-85f3-2a4961bf31f8" type="CoreNodeModels.Input.BoolSelector" nickname="Boolean" x="352" y="450" isVisible="true" isUpstreamVisible="true" lacing="Disabled" isSelectedInput="True" IsFrozen="false" isPinned="false">
      <System.Boolean>False</System.Boolean>
    </CoreNodeModels.Input.BoolSelector>
  </Elements>
  <Connectors>
    <Dynamo.Graph.Connectors.ConnectorModel start="5c8b438e-7adc-4fc5-9832-dd85f435e52b" start_index="0" end="c79d2ac7-adc0-41b5-84eb-017cdb4a902e" end_index="0" portType="0" />
    <Dynamo.Graph.Connectors.ConnectorModel start="028cbfff-40a2-415c-85f3-2a4961bf31f8" start_index="0" end="c79d2ac7-adc0-41b5-84eb-017cdb4a902e" end_index="1" portType="0" />
  </Connectors>
  <Notes />
  <Annotations />
  <Presets />
  <Cameras>
    <Camera Name="Background Preview" eyeX="-17" eyeY="24" eyeZ="50" lookX="12" lookY="-13" lookZ="-58" upX="0" upY="1" upZ="0" />
  </Cameras>
</Workspace>