<Workspace Version="1.3.2.2480" X="175.880672774301" Y="161.927633498945" zoom="1.36270155887617" ScaleFactor="1" Name="Home" Description="" RunType="Manual" RunPeriod="1000" HasRunWithoutCrash="True">
  <NamespaceResolutionMap />
  <Elements>
    <Dynamo.Nodes.DSModelElementsSelection guid="f8724d8d-89a2-4147-b4d5-5e1f3e025d2f" type="Dynamo.Nodes.DSModelElementsSelection" nickname="Select Model Elements" x="-52.2217869764133" y="-85.5097647250807" isVisible="true" isUpstreamVisible="true" lacing="Disabled" isSelectedInput="True" IsFrozen="false" isPinned="true">
      <instance id="e59d1039-a974-4b33-a8d4-4e2ad3b2efd9-002152ea" />
      <instance id="571f9654-45d3-44a0-b221-0c5b980c8095-002abcbf" />
    </Dynamo.Nodes.DSModelElementsSelection>
    <Dynamo.Graph.Nodes.CodeBlockNodeModel guid="6c4fb897-0f68-4625-a33f-63ad6718c6a0" type="Dynamo.Graph.Nodes.CodeBlockNodeModel" nickname="Code Block" x="63.4734952640686" y="374.413201825366" isVisible="true" isUpstreamVisible="true" lacing="Disabled" isSelectedInput="False" IsFrozen="false" isPinned="false" CodeText="&quot;0&quot;;" ShouldFocus="false" />
    <Dynamo.Graph.Nodes.CodeBlockNodeModel guid="303a3d34-b9fd-4e67-a042-30428a6002a6" type="Dynamo.Graph.Nodes.CodeBlockNodeModel" nickname="Code Block" x="57.9885686237442" y="512" isVisible="true" isUpstreamVisible="true" lacing="Disabled" isSelectedInput="False" IsFrozen="false" isPinned="false" CodeText="&quot;1&quot;;" ShouldFocus="false" />
    <PythonNodeModels.PythonNode guid="690e08c3-558d-490d-86c0-c0b5e4a57c5a" type="PythonNodeModels.PythonNode" nickname="Python Script" x="361.232657774706" y="246.890838008998" isVisible="true" isUpstreamVisible="true" lacing="Disabled" isSelectedInput="False" IsFrozen="false" isPinned="false" inputcount="2">
      <PortInfo index="0" default="False" />
      <PortInfo index="1" default="False" />
      <Script>#Put view on sheet
import clr
clr.AddReference('RevitAPI')
from Autodesk.Revit.DB import *

clr.AddReference("RevitNodes")
import Revit
clr.ImportExtensions(Revit.Elements)

clr.AddReference("RevitServices")
import RevitServices
from RevitServices.Persistence import DocumentManager
from RevitServices.Transactions import TransactionManager

import clr
clr.AddReference('ProtoGeometry')

from Autodesk.DesignScript.Geometry import *

doc = DocumentManager.Instance.CurrentDBDocument
#The inputs to this node will be stored as a list in the IN variables.
grids = UnwrapElement(IN[0])

a = UnwrapElement(IN[1])

if a == "0":
	b = DatumEnds.End0
else:
	b = DatumEnds.End1

	# "Start" the transaction
TransactionManager.Instance.EnsureInTransaction(doc)

view = doc.ActiveView	

for grid in grids:
	
	grid.HideBubbleInView(DatumEnds.End0, view);
	grid.HideBubbleInView(DatumEnds.End1, view);
	grid.ShowBubbleInView(b, view);

# "End" the transaction
TransactionManager.Instance.TransactionTaskDone()


#Assign your output to the OUT variable.
OUT = 0
</Script>
    </PythonNodeModels.PythonNode>
    <PythonNodeModels.PythonNode guid="770c6298-211b-43fb-9664-84021c41de2c" type="PythonNodeModels.PythonNode" nickname="End 0" x="440.38182309275" y="-115.387766432003" isVisible="true" isUpstreamVisible="true" lacing="Disabled" isSelectedInput="False" IsFrozen="false" isPinned="false" inputcount="1">
      <PortInfo index="0" default="False" />
      <Script>#Put view on sheet
import clr
clr.AddReference('RevitAPI')
from Autodesk.Revit.DB import *

clr.AddReference("RevitNodes")
import Revit
clr.ImportExtensions(Revit.Elements)

clr.AddReference("RevitServices")
import RevitServices
from RevitServices.Persistence import DocumentManager
from RevitServices.Transactions import TransactionManager

import clr
clr.AddReference('ProtoGeometry')

from Autodesk.DesignScript.Geometry import *

doc = DocumentManager.Instance.CurrentDBDocument
#The inputs to this node will be stored as a list in the IN variables.
grids = UnwrapElement(IN[0])

b = DatumEnds.End0
c = DatumEnds.End1

	# "Start" the transaction
TransactionManager.Instance.EnsureInTransaction(doc)

view = doc.ActiveView	

for grid in grids:
	
	grid.HideBubbleInView(DatumEnds.End0, view);
	grid.HideBubbleInView(DatumEnds.End1, view);
	grid.ShowBubbleInView(b, view);
	grid.Pinned = False
	grid.Pinned = True

# "End" the transaction
TransactionManager.Instance.TransactionTaskDone()


#Assign your output to the OUT variable.
OUT = 0
</Script>
    </PythonNodeModels.PythonNode>
    <PythonNodeModels.PythonNode guid="564786ef-286d-4849-9e82-a00e8631c6e7" type="PythonNodeModels.PythonNode" nickname="End 1" x="552.285667246568" y="47.7271047572742" isVisible="true" isUpstreamVisible="true" lacing="Disabled" isSelectedInput="False" IsFrozen="false" isPinned="true" inputcount="1">
      <PortInfo index="0" default="False" />
      <Script>#Put view on sheet
import clr
clr.AddReference('RevitAPI')
from Autodesk.Revit.DB import *

clr.AddReference("RevitNodes")
import Revit
clr.ImportExtensions(Revit.Elements)

clr.AddReference("RevitServices")
import RevitServices
from RevitServices.Persistence import DocumentManager
from RevitServices.Transactions import TransactionManager

import clr
clr.AddReference('ProtoGeometry')

from Autodesk.DesignScript.Geometry import *

doc = DocumentManager.Instance.CurrentDBDocument
#The inputs to this node will be stored as a list in the IN variables.
grids = UnwrapElement(IN[0])



b = DatumEnds.End0
c = DatumEnds.End1

	# "Start" the transaction
TransactionManager.Instance.EnsureInTransaction(doc)

view = doc.ActiveView	

for grid in grids:
	
	grid.HideBubbleInView(DatumEnds.End0, view);
	grid.HideBubbleInView(DatumEnds.End1, view);
	grid.ShowBubbleInView(c, view);
	grid.Pinned = False
	grid.Pinned = True
# "End" the transaction
TransactionManager.Instance.TransactionTaskDone()


#Assign your output to the OUT variable.
OUT = 0
</Script>
    </PythonNodeModels.PythonNode>
    <Dynamo.Graph.Nodes.CustomNodes.Function guid="afd5f212-d5bb-45d3-805d-d1db25401325" type="Dynamo.Graph.Nodes.CustomNodes.Function" nickname="Element.SetPinnedStatus" x="791.175500893427" y="-2.96234909102492" isVisible="true" isUpstreamVisible="true" lacing="Shortest" isSelectedInput="False" IsFrozen="false" isPinned="false">
      <PortInfo index="0" default="False" />
      <PortInfo index="1" default="True" />
      <ID value="648bd8c3-5856-475f-9e00-ce20ec7e5e02" />
      <Name value="Element.SetPinnedStatus" />
      <Description value="Will set the element to either pinned or not pinned. True is pinned, false is unpinned. For multiple elements use List.Map" />
      <Inputs>
        <Input value="element" />
        <Input value="Bool" />
      </Inputs>
      <Outputs>
        <Output value="element" />
      </Outputs>
    </Dynamo.Graph.Nodes.CustomNodes.Function>
    <Dynamo.Nodes.DSModelElementsSelection guid="c57d6097-f06a-4e28-a5ef-7091f9ca0031" type="Dynamo.Nodes.DSModelElementsSelection" nickname="Select Model Elements" x="-52.8182445874542" y="184.525527892284" isVisible="true" isUpstreamVisible="true" lacing="Disabled" isSelectedInput="True" IsFrozen="false" isPinned="true">
      <instance id="e59d1039-a974-4b33-a8d4-4e2ad3b2efd9-002152e8" />
      <instance id="e59d1039-a974-4b33-a8d4-4e2ad3b2efd9-002152e9" />
      <instance id="e59d1039-a974-4b33-a8d4-4e2ad3b2efd9-002152f4" />
    </Dynamo.Nodes.DSModelElementsSelection>
    <Dynamo.Graph.Nodes.CodeBlockNodeModel guid="bf89d557-b172-46da-bb85-2dcadc149e92" type="Dynamo.Graph.Nodes.CodeBlockNodeModel" nickname="Code Block" x="293.809256586349" y="59.0300399342522" isVisible="true" isUpstreamVisible="true" lacing="Disabled" isSelectedInput="False" IsFrozen="false" isPinned="false" CodeText="Flatten({A,B});" ShouldFocus="false">
      <PortInfo index="0" default="False" />
      <PortInfo index="1" default="False" />
    </Dynamo.Graph.Nodes.CodeBlockNodeModel>
  </Elements>
  <Connectors>
    <Dynamo.Graph.Connectors.ConnectorModel start="f8724d8d-89a2-4147-b4d5-5e1f3e025d2f" start_index="0" end="bf89d557-b172-46da-bb85-2dcadc149e92" end_index="0" portType="0" />
    <Dynamo.Graph.Connectors.ConnectorModel start="6c4fb897-0f68-4625-a33f-63ad6718c6a0" start_index="0" end="690e08c3-558d-490d-86c0-c0b5e4a57c5a" end_index="1" portType="0" />
    <Dynamo.Graph.Connectors.ConnectorModel start="c57d6097-f06a-4e28-a5ef-7091f9ca0031" start_index="0" end="bf89d557-b172-46da-bb85-2dcadc149e92" end_index="1" portType="0" />
    <Dynamo.Graph.Connectors.ConnectorModel start="bf89d557-b172-46da-bb85-2dcadc149e92" start_index="0" end="564786ef-286d-4849-9e82-a00e8631c6e7" end_index="0" portType="0" />
  </Connectors>
  <Notes>
    <Dynamo.Graph.Notes.NoteModel guid="9e9f3043-44dc-41f1-8e01-5fccc9a2e946" text="Grid End 0" x="61.0873744382113" y="339.375388941171" />
    <Dynamo.Graph.Notes.NoteModel guid="8a852e8d-cdeb-41f3-9f15-78a2d30a4756" text="Grid End 1" x="60.4236092526241" y="470.238070090824" />
    <Dynamo.Graph.Notes.NoteModel guid="1232dd88-a00f-47bb-8451-8f92ad3f1022" text="Swap Bubble Grid Ends" x="358.796917922167" y="211.457093195893" />
    <Dynamo.Graph.Notes.NoteModel guid="1a742895-352b-4f26-9a5e-b062f2a9cf55" text="Select Grids" x="36.8523133081123" y="-126.202012053326" />
    <Dynamo.Graph.Notes.NoteModel guid="b235e23b-e113-4808-a336-f36a93350744" text="Select Grids" x="36.2558556970715" y="143.833280564039" />
  </Notes>
  <Annotations />
  <Presets />
  <Cameras>
    <Camera Name="Background Preview" eyeX="-17" eyeY="24" eyeZ="50" lookX="12" lookY="-13" lookZ="-58" upX="0" upY="1" upZ="0" />
  </Cameras>
</Workspace>