{
  "Uuid": "45727224-4e7b-414a-9654-eff05c16dc2c",
  "IsCustomNode": false,
  "Description": null,
  "Name": "lineBeamsIntersection",
  "ElementResolver": {
    "ResolutionMap": {}
  },
  "Inputs": [],
  "Outputs": [],
  "Nodes": [
    {
      "ConcreteType": "CoreNodeModels.Input.BoolSelector, CoreNodeModels",
      "NodeType": "BooleanInputNode",
      "InputValue": false,
      "Id": "7dea9c494327401bb364b32bc77aa152",
      "Inputs": [],
      "Outputs": [
        {
          "Id": "c6059c4c936048ae909068d3225d3c78",
          "Name": "",
          "Description": "Boolean",
          "UsingDefaultValue": false,
          "Level": 2,
          "UseLevels": false,
          "KeepListStructure": false
        }
      ],
      "Replication": "Disabled",
      "Description": "Selection between a true and false."
    },
    {
      "ConcreteType": "PythonNodeModels.PythonNode, PythonNodeModels",
      "NodeType": "PythonScriptNode",
      "Code": "import clr\r\n\r\nclr.AddReference(\"RevitAPIUI\")\r\nfrom Autodesk.Revit.UI import IExternalEventHandler, ExternalEvent, TaskDialog\r\nfrom Autodesk.Revit.UI.Selection import *\r\n\r\nclr.AddReference(\"RevitAPI\")\r\nfrom Autodesk.Revit.DB import Transaction, OverrideGraphicSettings, ElementId, Color\r\n# noinspection PyUnresolvedReferences\r\nfrom Autodesk.Revit.Exceptions import InvalidOperationException\r\n\r\n\r\nclr.AddReference('RevitServices')\r\nfrom RevitServices.Persistence import DocumentManager\r\n\r\n\r\nglobal result\r\n\r\n\r\n\r\ndoc = DocumentManager.Instance.CurrentDBDocument\r\nuidoc = DocumentManager.Instance.CurrentUIApplication.ActiveUIDocument\r\n\r\n\r\nclass CustomISelectionFilter(ISelectionFilter):\r\n\tdef __init__(self, category_name):\r\n\t\tself.category_name = category_name\r\n\tdef AllowElement(self, e):\r\n\t\tif e.Category.Name == self.category_name:\r\n\t\t\treturn True\r\n\t\telse:\r\n\t\t\treturn False\r\n\tdef AllowReference(self, ref, point):\r\n\t\treturn false\r\n\r\nref = uidoc.Selection.PickObjects(ObjectType.Element, CustomISelectionFilter(\"Lines\"), \"Select Lines\")\r\n\r\nOUT = [doc.GetElement(r) for r in ref]\r\n",
      "VariableInputPorts": true,
      "Id": "75f0571f15124fc98394235784b7ed5f",
      "Inputs": [
        {
          "Id": "02811cb1995341cb8d9bdfd7518fb790",
          "Name": "IN[0]",
          "Description": "Input #0",
          "UsingDefaultValue": false,
          "Level": 2,
          "UseLevels": false,
          "KeepListStructure": false
        }
      ],
      "Outputs": [
        {
          "Id": "0fe3cd8284af4f34b9741b2c6100a64a",
          "Name": "OUT",
          "Description": "Result of the python script",
          "UsingDefaultValue": false,
          "Level": 2,
          "UseLevels": false,
          "KeepListStructure": false
        }
      ],
      "Replication": "Disabled",
      "Description": "Runs an embedded IronPython script."
    },
    {
      "ConcreteType": "CoreNodeModels.Input.BoolSelector, CoreNodeModels",
      "NodeType": "BooleanInputNode",
      "InputValue": false,
      "Id": "eba6b5906d934fda8cdbf604f94cb5d2",
      "Inputs": [],
      "Outputs": [
        {
          "Id": "d9a5022485f24809b48bd90c05970ee4",
          "Name": "",
          "Description": "Boolean",
          "UsingDefaultValue": false,
          "Level": 2,
          "UseLevels": false,
          "KeepListStructure": false
        }
      ],
      "Replication": "Disabled",
      "Description": "Selection between a true and false."
    },
    {
      "ConcreteType": "PythonNodeModels.PythonNode, PythonNodeModels",
      "NodeType": "PythonScriptNode",
      "Code": "import clr\r\n\r\nclr.AddReference(\"RevitAPIUI\")\r\nfrom Autodesk.Revit.UI import IExternalEventHandler, ExternalEvent, TaskDialog\r\nfrom Autodesk.Revit.UI.Selection import *\r\n\r\nclr.AddReference(\"RevitAPI\")\r\nfrom Autodesk.Revit.DB import Transaction, OverrideGraphicSettings, ElementId, Color\r\n# noinspection PyUnresolvedReferences\r\nfrom Autodesk.Revit.Exceptions import InvalidOperationException\r\n\r\n\r\nclr.AddReference('RevitServices')\r\nfrom RevitServices.Persistence import DocumentManager\r\n\r\n\r\nglobal result\r\n\r\n\r\n\r\ndoc = DocumentManager.Instance.CurrentDBDocument\r\nuidoc = DocumentManager.Instance.CurrentUIApplication.ActiveUIDocument\r\n\r\n\r\nclass CustomISelectionFilter(ISelectionFilter):\r\n\tdef __init__(self, category_name):\r\n\t\tself.category_name = category_name\r\n\tdef AllowElement(self, e):\r\n\t\tif e.Category.Name == self.category_name:\r\n\t\t\treturn True\r\n\t\telse:\r\n\t\t\treturn False\r\n\tdef AllowReference(self, ref, point):\r\n\t\treturn false\r\n\r\nref = uidoc.Selection.PickObjects(ObjectType.Element, CustomISelectionFilter(\"Structural Framing\"), \"Select Multiple Beams\")\r\n\r\nOUT = [doc.GetElement(r) for r in ref]\r\n",
      "VariableInputPorts": true,
      "Id": "dfa187821f2743d89067f9222be72fa7",
      "Inputs": [
        {
          "Id": "d4555bd38e1a408c8afcdc32f8fdcbd1",
          "Name": "IN[0]",
          "Description": "Input #0",
          "UsingDefaultValue": false,
          "Level": 2,
          "UseLevels": false,
          "KeepListStructure": false
        }
      ],
      "Outputs": [
        {
          "Id": "ef60c9bb08df403eaf67e7c105aea928",
          "Name": "OUT",
          "Description": "Result of the python script",
          "UsingDefaultValue": false,
          "Level": 2,
          "UseLevels": false,
          "KeepListStructure": false
        }
      ],
      "Replication": "Disabled",
      "Description": "Runs an embedded IronPython script."
    },
    {
      "ConcreteType": "PythonNodeModels.PythonNode, PythonNodeModels",
      "NodeType": "PythonScriptNode",
      "Code": "# Enable Python support and load DesignScript library\r\nimport clr\r\nclr.AddReference('ProtoGeometry')\r\nfrom Autodesk.DesignScript.Geometry import *\r\n\r\nimport clr\r\nclr.AddReference(\"RevitNodes\")\r\nimport Revit\r\n# Import ToProtoType, ToRevitType geometry conversion extension methods\r\nclr.ImportExtensions(Revit.GeometryConversion)\r\n\r\n\r\ndef distance(st, end):\r\n\treturn ((end.X-st.X)**2+(end.Y-st.Y)**2)**0.5\r\n\r\nbeams = UnwrapElement(IN[0])\r\npenoLine = UnwrapElement(IN[1])\r\n\r\nresult = []\r\n\r\nfor b in beams:\r\n\tsubList = [b]\r\n\tresult.append(subList)\r\n\tbeamCrv = b.Location.Curve.ToProtoType()\r\n\tbeamStPt = beamCrv.PointAtParameter(0)\r\n\tfor p in penoLine:\r\n\t\tcrv = p.Location.Curve.ToProtoType()\t\t\r\n\t\tintPt = Geometry.Intersect(beamCrv, crv)\t\t\r\n\t\tif intPt:\t\t\t\r\n\t\t\tdist = distance(intPt[0], beamStPt)\r\n\t\t\tsubList.append(p.LineStyle.Name)\r\n\t\t\tsubList.append(intPt[0])\r\n\t\t\t#subList.append(beamStPt)\r\n\t\t\tsubList.append(dist)\r\n\t\telse:\r\n\t\t\tcontinue\r\n\r\n# Assign your output to the OUT variable.\r\nOUT = result\r\n",
      "VariableInputPorts": true,
      "Id": "5720835d3b5f48c094387833f1fa3ef2",
      "Inputs": [
        {
          "Id": "6c8a5ddbb98e435e9a077940675398a5",
          "Name": "IN[0]",
          "Description": "Input #0",
          "UsingDefaultValue": false,
          "Level": 2,
          "UseLevels": false,
          "KeepListStructure": false
        },
        {
          "Id": "f7c4854f80514dad9c209c63d7b7fceb",
          "Name": "IN[1]",
          "Description": "Input #1",
          "UsingDefaultValue": false,
          "Level": 2,
          "UseLevels": false,
          "KeepListStructure": false
        }
      ],
      "Outputs": [
        {
          "Id": "08f9987575aa47f19a5aec244848fd52",
          "Name": "OUT",
          "Description": "Result of the python script",
          "UsingDefaultValue": false,
          "Level": 2,
          "UseLevels": false,
          "KeepListStructure": false
        }
      ],
      "Replication": "Disabled",
      "Description": "Runs an embedded IronPython script."
    }
  ],
  "Connectors": [
    {
      "Start": "c6059c4c936048ae909068d3225d3c78",
      "End": "02811cb1995341cb8d9bdfd7518fb790",
      "Id": "41cdfb57630241cfa5f24df9289bd740"
    },
    {
      "Start": "0fe3cd8284af4f34b9741b2c6100a64a",
      "End": "f7c4854f80514dad9c209c63d7b7fceb",
      "Id": "32dcedc7a3544fc095dad23f947fa801"
    },
    {
      "Start": "d9a5022485f24809b48bd90c05970ee4",
      "End": "d4555bd38e1a408c8afcdc32f8fdcbd1",
      "Id": "82e9aa01baf14999963e84ae8aba7ef0"
    },
    {
      "Start": "ef60c9bb08df403eaf67e7c105aea928",
      "End": "6c8a5ddbb98e435e9a077940675398a5",
      "Id": "7a89f828b86844a8a24aebdcc130f516"
    }
  ],
  "Dependencies": [],
  "Bindings": [],
  "View": {
    "Dynamo": {
      "ScaleFactor": 1.0,
      "HasRunWithoutCrash": true,
      "IsVisibleInDynamoLibrary": true,
      "Version": "2.0.1.5055",
      "RunType": "Manual",
      "RunPeriod": "1000"
    },
    "Camera": {
      "Name": "Background Preview",
      "EyeX": -17.0,
      "EyeY": 24.0,
      "EyeZ": 50.0,
      "LookX": 12.0,
      "LookY": -13.0,
      "LookZ": -58.0,
      "UpX": 0.0,
      "UpY": 1.0,
      "UpZ": 0.0
    },
    "NodeViews": [
      {
        "ShowGeometry": true,
        "Name": "Boolean",
        "Id": "7dea9c494327401bb364b32bc77aa152",
        "IsSetAsInput": false,
        "IsSetAsOutput": false,
        "Excluded": false,
        "X": 438.02401048827073,
        "Y": 153.72797625454575
      },
      {
        "ShowGeometry": true,
        "Name": "Python Script",
        "Id": "75f0571f15124fc98394235784b7ed5f",
        "IsSetAsInput": false,
        "IsSetAsOutput": false,
        "Excluded": false,
        "X": 667.4897697750007,
        "Y": 147.8201611979656
      },
      {
        "ShowGeometry": true,
        "Name": "Boolean",
        "Id": "eba6b5906d934fda8cdbf604f94cb5d2",
        "IsSetAsInput": false,
        "IsSetAsOutput": false,
        "Excluded": false,
        "X": 398.14435754473277,
        "Y": -56.956215887969961
      },
      {
        "ShowGeometry": true,
        "Name": "Python Script",
        "Id": "dfa187821f2743d89067f9222be72fa7",
        "IsSetAsInput": false,
        "IsSetAsOutput": false,
        "Excluded": false,
        "X": 629.61095751956179,
        "Y": -73.730032814219726
      },
      {
        "ShowGeometry": true,
        "Name": "Python Script",
        "Id": "5720835d3b5f48c094387833f1fa3ef2",
        "IsSetAsInput": false,
        "IsSetAsOutput": false,
        "Excluded": false,
        "X": 1093.481861777248,
        "Y": -53.129381510223311
      }
    ],
    "Annotations": [
      {
        "Id": "e052f81cbff6451a91180aa72798f2e9",
        "Title": "beams",
        "Nodes": [
          "eba6b5906d934fda8cdbf604f94cb5d2",
          "dfa187821f2743d89067f9222be72fa7"
        ],
        "Left": 388.14435754473277,
        "Top": -126.73003281421973,
        "Width": 375.466599974829,
        "Height": 137.77381692624976,
        "FontSize": 36.0,
        "InitialTop": -73.730032814219726,
        "InitialHeight": 114.77381692624976,
        "TextblockHeight": 43.0,
        "Background": "#FFC1D676"
      }
    ],
    "X": -671.73352857102759,
    "Y": 258.21285713781128,
    "Zoom": 1.4103679023699154
  }
}