<Workspace Version="2.0.0.3911" X="-0.323631419169203" Y="39.9566583501194" zoom="0.959788699581266" ScaleFactor="1" Name="Home" Description="" RunType="Manual" RunPeriod="1000" HasRunWithoutCrash="True">
  <NamespaceResolutionMap />
  <Elements>
    <Dynamo.Graph.Nodes.CodeBlockNodeModel guid="0fea94cf-31e9-4a8e-b1b5-72f8e27a885e" type="Dynamo.Graph.Nodes.CodeBlockNodeModel" nickname="Code Block" x="-71.8989557820673" y="38.195596938809" isVisible="true" isUpstreamVisible="true" lacing="Disabled" isSelectedInput="False" IsFrozen="false" isPinned="true" CodeText="{{1..5,6..8,5..9},{4..8}};" ShouldFocus="false">
      <OutPortInfo LineIndex="0" />
    </Dynamo.Graph.Nodes.CodeBlockNodeModel>
    <PythonNodeModels.PythonNode guid="485120c9-0a71-45e3-a0ee-3788a9614f53" type="PythonNodeModels.PythonNode" nickname="Python Script" x="289.966977041068" y="55.0818373725872" isVisible="true" isUpstreamVisible="true" lacing="Disabled" isSelectedInput="False" IsFrozen="false" isPinned="true" inputcount="1">
      <PortInfo index="0" default="False" />
      <Script>import clr
clr.AddReference('ProtoGeometry')
from Autodesk.DesignScript.Geometry import *
#The inputs to this node will be stored as a list in the IN variables.
lista = IN[0]
newLista = lista

for i in range(0,len(lista)):
	for j in range(0,len(lista[i])):
		newLista[i][j].append(lista[i][j][0])
		
#Assign your output to the OUT variable.
OUT = newLista</Script>
    </PythonNodeModels.PythonNode>
    <PythonNodeModels.PythonNode guid="4633b651-29e7-466c-801f-d137b265d9f7" type="PythonNodeModels.PythonNode" nickname="Python Script" x="276" y="464.8" isVisible="true" isUpstreamVisible="true" lacing="Disabled" isSelectedInput="False" IsFrozen="false" isPinned="true" inputcount="1">
      <PortInfo index="0" default="False" />
      <Script>import clr
clr.AddReference('ProtoGeometry')
from Autodesk.DesignScript.Geometry import *
a = IN[0]

if len(a)&gt;1:
	OUT = "ciao"
else:
	OUT = "beta"

</Script>
    </PythonNodeModels.PythonNode>
    <Dynamo.Graph.Nodes.CodeBlockNodeModel guid="b984aced-b122-4cba-8ff7-676fcc19402a" type="Dynamo.Graph.Nodes.CodeBlockNodeModel" nickname="Code Block" x="112" y="469" isVisible="true" isUpstreamVisible="true" lacing="Disabled" isSelectedInput="False" IsFrozen="false" isPinned="false" CodeText="{1..5};" ShouldFocus="false">
      <OutPortInfo LineIndex="0" />
    </Dynamo.Graph.Nodes.CodeBlockNodeModel>
    <PythonNodeModels.PythonNode guid="62d1598a-b8c5-4e17-b598-f0813812940b" type="PythonNodeModels.PythonNode" nickname="Python Script" x="558.127462585079" y="-13.2709428143397" isVisible="true" isUpstreamVisible="true" lacing="Disabled" isSelectedInput="False" IsFrozen="false" isPinned="true" inputcount="1">
      <PortInfo index="0" default="False" />
      <Script>import clr
clr.AddReference('ProtoGeometry')
from Autodesk.DesignScript.Geometry import *
#The inputs to this node will be stored as a list in the IN variables.
lista = IN[0]

oP = []
iP = []

for i in range(0,len(lista)):
		if len(lista[i])&gt;1:
			oP.append(lista[i][0])
			for j in range(1,len(lista[i])):
				iP.append(lista[i][j])
		else:
			oP.append(lista[i][0])

#Assign your output to the OUT variable.
OUT = oP, iP</Script>
    </PythonNodeModels.PythonNode>
    <PythonNodeModels.PythonNode guid="e792c9e7-7f1b-418b-9342-ca62c572305b" type="PythonNodeModels.PythonNode" nickname="Python Script" x="505.025004584945" y="337.196096160034" isVisible="true" isUpstreamVisible="true" lacing="Disabled" isSelectedInput="False" IsFrozen="false" isPinned="true" inputcount="1">
      <PortInfo index="0" default="False" />
      <Script>import clr
clr.AddReference('ProtoGeometry')
from Autodesk.DesignScript.Geometry import *
#The inputs to this node will be stored as a list in the IN variables.
lista = IN[0]

oP = []
iP = []

for i in range(0,len(lista)):
	oP.append(len(lista[i]))
#Assign your output to the OUT variable.
OUT = oP</Script>
    </PythonNodeModels.PythonNode>
  </Elements>
  <Connectors>
    <Dynamo.Graph.Connectors.ConnectorModel start="0fea94cf-31e9-4a8e-b1b5-72f8e27a885e" start_index="0" end="485120c9-0a71-45e3-a0ee-3788a9614f53" end_index="0" portType="0" />
    <Dynamo.Graph.Connectors.ConnectorModel start="485120c9-0a71-45e3-a0ee-3788a9614f53" start_index="0" end="62d1598a-b8c5-4e17-b598-f0813812940b" end_index="0" portType="0" />
    <Dynamo.Graph.Connectors.ConnectorModel start="485120c9-0a71-45e3-a0ee-3788a9614f53" start_index="0" end="e792c9e7-7f1b-418b-9342-ca62c572305b" end_index="0" portType="0" />
    <Dynamo.Graph.Connectors.ConnectorModel start="b984aced-b122-4cba-8ff7-676fcc19402a" start_index="0" end="4633b651-29e7-466c-801f-d137b265d9f7" end_index="0" portType="0" />
  </Connectors>
  <Notes />
  <Annotations />
  <Presets />
  <Cameras>
    <Camera Name="Background Preview" eyeX="-17" eyeY="24" eyeZ="50" lookX="12" lookY="-13" lookZ="-58" upX="0" upY="1" upZ="0" />
  </Cameras>
</Workspace>