<Workspace Version="1.3.1.1736" X="-3022.94207757609" Y="482.923702254252" zoom="0.95448494563359" ScaleFactor="1" Name="Home" Description="" RunType="Manual" RunPeriod="1000" HasRunWithoutCrash="True">
  <NamespaceResolutionMap />
  <Elements>
    <Dynamo.Graph.Nodes.CustomNodes.Function guid="1a95dc78-1c8d-424a-98e5-b0fac301ad71" type="Dynamo.Graph.Nodes.CustomNodes.Function" nickname="Pipe.ByLines" x="3711.89878819615" y="-259.928265661648" isVisible="true" isUpstreamVisible="true" lacing="Longest" isSelectedInput="False" IsFrozen="false" isPinned="true">
      <PortInfo index="0" default="False" />
      <PortInfo index="1" default="False" />
      <PortInfo index="2" default="False" />
      <PortInfo index="3" default="False" />
      <PortInfo index="4" default="False" />
      <ID value="410c1c30-be13-4789-99f3-e39e074d127e" />
      <Name value="Pipe.ByLines" />
      <Description value="Creates a pipe by Line, PipeType, SystemType, Level and Diameter" />
      <Inputs>
        <Input value="Lines" />
        <Input value="PipeType" />
        <Input value="SystemType" />
        <Input value="Level" />
        <Input value="Diameter" />
      </Inputs>
      <Outputs>
        <Output value="Pipes" />
      </Outputs>
    </Dynamo.Graph.Nodes.CustomNodes.Function>
    <Dynamo.Nodes.DSModelElementsSelection guid="904ac920-b49c-4f30-b909-cad21175b544" type="Dynamo.Nodes.DSModelElementsSelection" nickname="Select Model Elements" x="2823.97398384639" y="-424.142072034" isVisible="true" isUpstreamVisible="true" lacing="Disabled" isSelectedInput="True" IsFrozen="false" isPinned="false">
      <instance id="cc72a23b-f587-4818-8882-e1b2158e3ac9-00ed2e51" />
      <instance id="cc72a23b-f587-4818-8882-e1b2158e3ac9-00ed2e6a" />
      <instance id="cc72a23b-f587-4818-8882-e1b2158e3ac9-00ed2e93" />
    </Dynamo.Nodes.DSModelElementsSelection>
    <Dynamo.Nodes.DSModelElementsSelection guid="8daf3a6d-f42f-4963-b42a-331403deb96e" type="Dynamo.Nodes.DSModelElementsSelection" nickname="Select Model Elements" x="2817.98879921705" y="-137.142491842596" isVisible="true" isUpstreamVisible="true" lacing="Disabled" isSelectedInput="True" IsFrozen="false" isPinned="false">
      <instance id="cc72a23b-f587-4818-8882-e1b2158e3ac9-00ed2ea4" />
    </Dynamo.Nodes.DSModelElementsSelection>
    <Dynamo.Graph.Nodes.ZeroTouch.DSFunction guid="975132eb-3d2b-43f1-845c-4905173c24df" type="Dynamo.Graph.Nodes.ZeroTouch.DSFunction" nickname="Element.GetType" x="3112.05520825592" y="-180.380104568346" isVisible="true" isUpstreamVisible="true" lacing="Shortest" isSelectedInput="False" IsFrozen="false" isPinned="true" assembly="..\AppData\Roaming\Dynamo\Dynamo Revit\1.3\packages\WombatDynamo\bin\WombatDynamo.dll" function="WombatDynamo.Element.GetType@Revit.Elements.Element">
      <PortInfo index="0" default="False" />
    </Dynamo.Graph.Nodes.ZeroTouch.DSFunction>
    <Dynamo.Graph.Nodes.ZeroTouch.DSFunction guid="27bbdaaf-551d-47fa-92b0-74d7aa0d6666" type="Dynamo.Graph.Nodes.ZeroTouch.DSFunction" nickname="Element.GetParameterValueByName" x="3142.33389442789" y="-6.83153748507027" isVisible="true" isUpstreamVisible="true" lacing="Shortest" isSelectedInput="False" IsFrozen="false" isPinned="true" assembly="RevitNodes.dll" function="Revit.Elements.Element.GetParameterValueByName@string">
      <PortInfo index="0" default="False" />
      <PortInfo index="1" default="False" />
    </Dynamo.Graph.Nodes.ZeroTouch.DSFunction>
    <Dynamo.Graph.Nodes.CodeBlockNodeModel guid="e6a1c671-ed21-4a52-9b1a-84981afb3d52" type="Dynamo.Graph.Nodes.CodeBlockNodeModel" nickname="Code Block" x="2774" y="58" isVisible="true" isUpstreamVisible="true" lacing="Disabled" isSelectedInput="False" IsFrozen="false" isPinned="false" CodeText="&quot;System Type&quot;;" ShouldFocus="false" />
    <DSRevitNodesUI.Levels guid="c99575f1-6fc9-4659-8beb-9a62fea4915d" type="DSRevitNodesUI.Levels" nickname="Levels" x="3430.02383607695" y="-143.129746096899" isVisible="true" isUpstreamVisible="true" lacing="Disabled" isSelectedInput="True" IsFrozen="false" isPinned="false" index="0:00" />
    <Dynamo.Graph.Nodes.CodeBlockNodeModel guid="3bb10c74-4c84-4daa-b696-0d74f4b2fecc" type="Dynamo.Graph.Nodes.CodeBlockNodeModel" nickname="Code Block" x="3247.69185538121" y="221.097353037846" isVisible="true" isUpstreamVisible="true" lacing="Disabled" isSelectedInput="False" IsFrozen="false" isPinned="true" CodeText="{40,50,200};" ShouldFocus="false" />
    <Dynamo.Graph.Nodes.ZeroTouch.DSFunction guid="6a533f71-57f7-4d16-b86a-ca345723ef2c" type="Dynamo.Graph.Nodes.ZeroTouch.DSFunction" nickname="Element.Curves" x="3258.27910733033" y="-326.604003642765" isVisible="true" isUpstreamVisible="true" lacing="Shortest" isSelectedInput="False" IsFrozen="false" isPinned="false" assembly="RevitNodes.dll" function="Revit.Elements.Element.Curves">
      <PortInfo index="0" default="False" />
    </Dynamo.Graph.Nodes.ZeroTouch.DSFunction>
    <Dynamo.Graph.Nodes.ZeroTouch.DSFunction guid="32042079-a762-49a5-a2b7-a8bc5051a0df" type="Dynamo.Graph.Nodes.ZeroTouch.DSFunction" nickname="Element.SetParameterByName" x="4363.0695861093" y="13.2969150915404" isVisible="true" isUpstreamVisible="true" lacing="Shortest" isSelectedInput="False" IsFrozen="false" isPinned="true" assembly="RevitNodes.dll" function="Revit.Elements.Element.SetParameterByName@string,var">
      <PortInfo index="0" default="False" />
      <PortInfo index="1" default="False" />
      <PortInfo index="2" default="False" />
    </Dynamo.Graph.Nodes.ZeroTouch.DSFunction>
    <Dynamo.Graph.Nodes.CodeBlockNodeModel guid="32a2d9c2-6300-4baf-b15d-a38387536fd4" type="Dynamo.Graph.Nodes.CodeBlockNodeModel" nickname="Code Block" x="4099.90553932633" y="39.9014272015411" isVisible="true" isUpstreamVisible="true" lacing="Disabled" isSelectedInput="False" IsFrozen="false" isPinned="false" CodeText="&quot;Diameter&quot;;" ShouldFocus="false" />
    <Dynamo.Graph.Nodes.CustomNodes.Function guid="5f7af183-69ea-4188-bf17-3e9e85b0f6c7" type="Dynamo.Graph.Nodes.CustomNodes.Function" nickname="DisplayUnit.ToInternalUnit" x="3802.34989728097" y="267.9289149074" isVisible="true" isUpstreamVisible="true" lacing="Shortest" isSelectedInput="False" IsFrozen="false" isPinned="false">
      <PortInfo index="0" default="False" />
      <PortInfo index="1" default="False" />
      <ID value="7f19e4a8-c7e0-4041-b57b-0b8d04a99b2c" />
      <Name value="DisplayUnit.ToInternalUnit" />
      <Description value="Converts a value from a given display unit to Revit's internal unit" />
      <Inputs>
        <Input value="val" />
        <Input value="displayUnitType" />
      </Inputs>
      <Outputs>
        <Output value="val" />
      </Outputs>
    </Dynamo.Graph.Nodes.CustomNodes.Function>
    <PythonNodeModels.PythonNode guid="9c829e1d-0d8a-4d99-9a98-563b190a539a" type="PythonNodeModels.PythonNode" nickname="Python Script" x="3595.39064578207" y="210.420074210164" isVisible="true" isUpstreamVisible="true" lacing="Disabled" isSelectedInput="False" IsFrozen="false" isPinned="true" inputcount="1">
      <PortInfo index="0" default="False" />
      <Script>import clr
clr.AddReference('RevitAPI')
from Autodesk.Revit.DB import *

import clr
clr.AddReference('ProtoGeometry')
from Autodesk.DesignScript.Geometry import *
# Import DocumentManager and TransactionManager
clr.AddReference("RevitServices")
import RevitServices
from RevitServices.Persistence import DocumentManager
doc = DocumentManager.Instance.CurrentDBDocument
# Import RevitAPI
clr.AddReference("RevitAPI")
import Autodesk
from Autodesk.Revit.DB import *


vals = IN[0]

getDocUnits = doc.GetUnits()
getDisplayUnits = getDocUnits.GetFormatOptions(UnitType.UT_Length).DisplayUnits

elementlist = []
for val in vals:
	elementlist.append(UnitUtils.ConvertToInternalUnits(val,getDisplayUnits))
OUT = elementlist</Script>
    </PythonNodeModels.PythonNode>
  </Elements>
  <Connectors>
    <Dynamo.Graph.Connectors.ConnectorModel start="1a95dc78-1c8d-424a-98e5-b0fac301ad71" start_index="0" end="32042079-a762-49a5-a2b7-a8bc5051a0df" end_index="0" portType="0" />
    <Dynamo.Graph.Connectors.ConnectorModel start="904ac920-b49c-4f30-b909-cad21175b544" start_index="0" end="6a533f71-57f7-4d16-b86a-ca345723ef2c" end_index="0" portType="0" />
    <Dynamo.Graph.Connectors.ConnectorModel start="8daf3a6d-f42f-4963-b42a-331403deb96e" start_index="0" end="975132eb-3d2b-43f1-845c-4905173c24df" end_index="0" portType="0" />
    <Dynamo.Graph.Connectors.ConnectorModel start="8daf3a6d-f42f-4963-b42a-331403deb96e" start_index="0" end="27bbdaaf-551d-47fa-92b0-74d7aa0d6666" end_index="0" portType="0" />
    <Dynamo.Graph.Connectors.ConnectorModel start="975132eb-3d2b-43f1-845c-4905173c24df" start_index="0" end="1a95dc78-1c8d-424a-98e5-b0fac301ad71" end_index="1" portType="0" />
    <Dynamo.Graph.Connectors.ConnectorModel start="27bbdaaf-551d-47fa-92b0-74d7aa0d6666" start_index="0" end="1a95dc78-1c8d-424a-98e5-b0fac301ad71" end_index="2" portType="0" />
    <Dynamo.Graph.Connectors.ConnectorModel start="e6a1c671-ed21-4a52-9b1a-84981afb3d52" start_index="0" end="27bbdaaf-551d-47fa-92b0-74d7aa0d6666" end_index="1" portType="0" />
    <Dynamo.Graph.Connectors.ConnectorModel start="c99575f1-6fc9-4659-8beb-9a62fea4915d" start_index="0" end="1a95dc78-1c8d-424a-98e5-b0fac301ad71" end_index="3" portType="0" />
    <Dynamo.Graph.Connectors.ConnectorModel start="3bb10c74-4c84-4daa-b696-0d74f4b2fecc" start_index="0" end="9c829e1d-0d8a-4d99-9a98-563b190a539a" end_index="0" portType="0" />
    <Dynamo.Graph.Connectors.ConnectorModel start="3bb10c74-4c84-4daa-b696-0d74f4b2fecc" start_index="0" end="1a95dc78-1c8d-424a-98e5-b0fac301ad71" end_index="4" portType="0" />
    <Dynamo.Graph.Connectors.ConnectorModel start="6a533f71-57f7-4d16-b86a-ca345723ef2c" start_index="0" end="1a95dc78-1c8d-424a-98e5-b0fac301ad71" end_index="0" portType="0" />
    <Dynamo.Graph.Connectors.ConnectorModel start="32a2d9c2-6300-4baf-b15d-a38387536fd4" start_index="0" end="32042079-a762-49a5-a2b7-a8bc5051a0df" end_index="1" portType="0" />
    <Dynamo.Graph.Connectors.ConnectorModel start="9c829e1d-0d8a-4d99-9a98-563b190a539a" start_index="0" end="32042079-a762-49a5-a2b7-a8bc5051a0df" end_index="2" portType="0" />
  </Connectors>
  <Notes />
  <Annotations />
  <Presets />
  <Cameras>
    <Camera Name="Background Preview" eyeX="-17" eyeY="24" eyeZ="50" lookX="12" lookY="-13" lookZ="-58" upX="0" upY="1" upZ="0" />
  </Cameras>
</Workspace>