<Workspace Version="1.3.2.2480" X="-142.881275880352" Y="247.6647472622" zoom="0.492332772935556" ScaleFactor="1" Name="Home" Description="" RunType="Manual" RunPeriod="1000" HasRunWithoutCrash="True">
  <NamespaceResolutionMap />
  <Elements>
    <PythonNodeModels.PythonNode guid="954f072a-101a-4d75-9fa7-bfb55e5979c5" type="PythonNodeModels.PythonNode" nickname="Python Script" x="787.516384410328" y="114.535459879622" isVisible="true" isUpstreamVisible="true" lacing="Disabled" isSelectedInput="False" IsFrozen="false" isPinned="true" inputcount="1">
      <PortInfo index="0" default="False" />
      <Script># Copyright(c) 2016, Konrad K Sobon
# @arch_laboratory, http://archi-lab.net

# Import Element wrapper extension methods
import clr
clr.AddReference("RevitNodes")
import Revit
clr.ImportExtensions(Revit.Elements)

# Import DocumentManager and TransactionManager
clr.AddReference("RevitServices")
import RevitServices
from RevitServices.Persistence import DocumentManager
from RevitServices.Transactions import TransactionManager
doc = DocumentManager.Instance.CurrentDBDocument

# Import RevitAPI
clr.AddReference("RevitAPI")
import Autodesk
from Autodesk.Revit.DB import *

import sys
pyt_path = r'C:\Program Files (x86)\IronPython 2.7\Lib'
sys.path.append(pyt_path)

#The inputs to this node will be stored as a list in the IN variable.
dataEnteringNode = IN

def Unwrap(item):
	return UnwrapElement(item)

def ProcessList(_func, _list):
    return map( lambda x: ProcessList(_func, x) if type(x)==list else _func(x), _list )

def GetFamilyType(famInst):
	try:
		id = famInst.GetTypeId()
		if id == ElementId.InvalidElementId:
			return None
		else:
			return doc.GetElement(id)
	except:
		return None
		pass

if isinstance(IN[0], list):
	elements = ProcessList(Unwrap, IN[0])
else:
	elements = [Unwrap(IN[0])]

try:
	errorReport = None
	output = ProcessList(GetFamilyType, elements)
except:
	# if error accurs anywhere in the process catch it
	import traceback
	errorReport = traceback.format_exc()

#Assign your output to the OUT variable
if errorReport == None:
	OUT = output
else:
	OUT = errorReport</Script>
    </PythonNodeModels.PythonNode>
    <PythonNodeModels.PythonNode guid="98d7e777-2494-48bc-87d1-ff4ace380125" type="PythonNodeModels.PythonNode" nickname="Python Script" x="1533.90945407014" y="213.189273032383" isVisible="true" isUpstreamVisible="true" lacing="Disabled" isSelectedInput="False" IsFrozen="false" isPinned="true" inputcount="3">
      <PortInfo index="0" default="False" />
      <PortInfo index="1" default="False" />
      <PortInfo index="2" default="False" />
      <Script>import clr
clr.AddReference("ProtoGeometry")
from Autodesk.DesignScript.Geometry import *
# Import RevitAPI
clr.AddReference("RevitAPI")
from Autodesk.Revit.DB import *
clr.AddReference("RevitAPIUI")
from Autodesk.Revit.UI import TaskDialog
# Import DocumentManager and TransactionManager
clr.AddReference("RevitServices")
from RevitServices.Persistence import DocumentManager
from RevitServices.Transactions import TransactionManager
# Import ToProtoType, ToRevitType geometry conversion extension methods
clr.AddReference("RevitNodes")
import Revit
clr.ImportExtensions(Revit.GeometryConversion)

doc = DocumentManager.Instance.CurrentDBDocument
uiapp = DocumentManager.Instance.CurrentUIApplication
app = uiapp.Application


ebbox = UnwrapElement(IN[0])

viewFamily = UnwrapElement(IN[1])

convBoxMax = ebbox.MaxPoint.ToXyz()
convBoxMin = ebbox.MinPoint.ToXyz()

w = (convBoxMax.X - convBoxMin.X)
d = (convBoxMax.Y - convBoxMin.Y)
h = (convBoxMax.Z - convBoxMin.Z)

maxPt = XYZ(w, h, 0.0)
minPt = XYZ(-w, -h, -d)
  
bbox = BoundingBoxXYZ()

bbox.Enabled = True
bbox.Max = maxPt
bbox.Min = minPt

trans = Transform.Identity

midPt = UnwrapElement(IN[2]).ToXyz()

trans.Origin = midPt
 
 
trans.BasisX = XYZ.BasisX
trans.BasisY = XYZ.BasisZ
trans.BasisZ = -XYZ.BasisY
 
bbox.Transform = trans

TransactionManager.Instance.EnsureInTransaction(doc)

viewSection = ViewSection.CreateSection(doc, viewFamily[0].Id, bbox)


TransactionManager.Instance.TransactionTaskDone()


OUT = w,d,h, viewSection</Script>
    </PythonNodeModels.PythonNode>
    <Dynamo.Graph.Nodes.CustomNodes.Function guid="0b6eafab-2753-4cd1-a7a0-5477acce0b51" type="Dynamo.Graph.Nodes.CustomNodes.Function" nickname="BoundingBox.Properties" x="1144.07598400468" y="328.824774012752" isVisible="true" isUpstreamVisible="true" lacing="Shortest" isSelectedInput="False" IsFrozen="false" isPinned="true">
      <PortInfo index="0" default="False" />
      <ID value="119fed50-cf6e-435e-9841-59ee18cb7d50" />
      <Name value="BoundingBox.Properties" />
      <Description value="Retrieves the centroid, width, depth and height of a given bounding box" />
      <Inputs>
        <Input value="boundingBox" />
      </Inputs>
      <Outputs>
        <Output value="Centroid" />
        <Output value="Width" />
        <Output value="Depth" />
        <Output value="Height" />
      </Outputs>
    </Dynamo.Graph.Nodes.CustomNodes.Function>
    <Dynamo.Graph.Nodes.ZeroTouch.DSFunction guid="1c142951-358a-498b-b38d-4958d744d662" type="Dynamo.Graph.Nodes.ZeroTouch.DSFunction" nickname="Element.BoundingBox" x="829.866416478698" y="263.382261880838" isVisible="true" isUpstreamVisible="true" lacing="Shortest" isSelectedInput="False" IsFrozen="false" isPinned="true" assembly="RevitNodes.dll" function="Revit.Elements.Element.BoundingBox">
      <PortInfo index="0" default="False" />
    </Dynamo.Graph.Nodes.ZeroTouch.DSFunction>
    <Dynamo.Nodes.DSModelElementSelection guid="8d147b41-bbb6-4bc7-8612-d363c6689b6c" type="Dynamo.Nodes.DSModelElementSelection" nickname="Select Model Element" x="517.993311191306" y="828.095372034416" isVisible="true" isUpstreamVisible="true" lacing="Disabled" isSelectedInput="True" IsFrozen="false" isPinned="true">
      <instance id="b9e43037-37e5-488a-8873-b4c655eb6298-002205c6" />
    </Dynamo.Nodes.DSModelElementSelection>
    <Dynamo.Graph.Nodes.CustomNodes.Function guid="05b26f54-f95d-4979-be3b-18f8883f66d4" type="Dynamo.Graph.Nodes.CustomNodes.Function" nickname="Element.LocalCoordinateSystem" x="744.68126423794" y="949.999075124874" isVisible="true" isUpstreamVisible="true" lacing="Shortest" isSelectedInput="False" IsFrozen="false" isPinned="true">
      <PortInfo index="0" default="False" />
      <ID value="98f07818-2169-443a-8e91-de302bc56b98" />
      <Name value="Element.LocalCoordinateSystem" />
      <Description value="Get the insertion point and local axes of an element. " />
      <Inputs>
        <Input value="element" />
      </Inputs>
      <Outputs>
        <Output value="Xvector" />
        <Output value="Yvector" />
        <Output value="Zvector" />
        <Output value="InsertionPoint" />
        <Output value="Invalid Elements" />
      </Outputs>
    </Dynamo.Graph.Nodes.CustomNodes.Function>
    <Dynamo.Graph.Nodes.ZeroTouch.DSFunction guid="7accce7d-0023-4cb0-be89-45c2809cc983" type="Dynamo.Graph.Nodes.ZeroTouch.DSFunction" nickname="BoundingBox.ToCuboid" x="1748.18091128576" y="-348.075451058315" isVisible="true" isUpstreamVisible="true" lacing="Shortest" isSelectedInput="False" IsFrozen="false" isPinned="true" assembly="ProtoGeometry.dll" function="Autodesk.DesignScript.Geometry.BoundingBox.ToCuboid">
      <PortInfo index="0" default="False" />
    </Dynamo.Graph.Nodes.ZeroTouch.DSFunction>
    <Dynamo.Graph.Nodes.ZeroTouch.DSFunction guid="55df0f9e-d910-4217-835e-7597fbccd5c0" type="Dynamo.Graph.Nodes.ZeroTouch.DSFunction" nickname="ImportInstance.ByGeometry" x="2071.68143842851" y="-351.191962425625" isVisible="true" isUpstreamVisible="true" lacing="Shortest" isSelectedInput="False" IsFrozen="false" isPinned="true" assembly="RevitNodes.dll" function="Revit.Elements.ImportInstance.ByGeometry@Autodesk.DesignScript.Geometry.Geometry">
      <PortInfo index="0" default="False" />
    </Dynamo.Graph.Nodes.ZeroTouch.DSFunction>
    <PythonNodeModels.PythonNode guid="3d41a116-6a27-4674-bd5e-f7ec0ca4e9b2" type="PythonNodeModels.PythonNode" nickname="Python Script" x="1479.29674222604" y="-84.4146318504415" isVisible="true" isUpstreamVisible="true" lacing="Disabled" isSelectedInput="False" IsFrozen="false" isPinned="true" inputcount="2">
      <PortInfo index="0" default="False" />
      <PortInfo index="1" default="False" />
      <Script>import clr
clr.AddReference("ProtoGeometry")
from Autodesk.DesignScript.Geometry import *
# Import RevitAPI
clr.AddReference("RevitAPI")
from Autodesk.Revit.DB import *
clr.AddReference("RevitAPIUI")
from Autodesk.Revit.UI import TaskDialog
# Import DocumentManager and TransactionManager
clr.AddReference("RevitServices")
from RevitServices.Persistence import DocumentManager
from RevitServices.Transactions import TransactionManager
# Import ToProtoType, ToRevitType geometry conversion extension methods
clr.AddReference("RevitNodes")
import Revit
clr.ImportExtensions(Revit.GeometryConversion)

doc = DocumentManager.Instance.CurrentDBDocument
uiapp = DocumentManager.Instance.CurrentUIApplication
app = uiapp.Application


wall = UnwrapElement(IN[0])

vft = UnwrapElement(IN[1])

lc = wall.Location

line = lc.Curve

'start point'
p = line.GetEndPoint(0)

'end point'
q = line.GetEndPoint(1)

'wall length'
v = q - p

bb = wall.get_BoundingBox( None )

minZ = bb.Min.Z;
maxZ = bb.Max.Z;

'bb Width - x direction'
w = v.GetLength();

'bb Height'
h = maxZ - minZ;



'section extent in x direction'
offset = 0.1
"""
min = XYZ(-w, minZ - offset, -offset)
max = XYZ(w, maxZ + offset, 0)
(width in plan, height view in section, position in plan)

"""
min = XYZ(-w/2-2, -10, 0)
max = XYZ(w/2+2, 40, 0.1)


midpoint = p + 0.5 * v;

walldir = -v.Normalize(); #+- change view direction
up = XYZ.BasisZ;
viewdir = walldir.CrossProduct( up );
 
t = Transform.Identity;
t.Origin = XYZ(midpoint.X, midpoint.Y, 0) ;
t.BasisX = walldir;
t.BasisY = up;
t.BasisZ = viewdir;


sectionBox = BoundingBoxXYZ();
sectionBox.Transform = t;
sectionBox.Min = min;
sectionBox.Max = max;

	

TransactionManager.Instance.EnsureInTransaction(doc)

section=ViewSection.CreateSection( doc, vft[0].Id, sectionBox )

TransactionManager.Instance.TransactionTaskDone()


OUT = section, q,p</Script>
    </PythonNodeModels.PythonNode>
    <Dynamo.Nodes.DSModelElementSelection guid="a129e65a-6273-40ab-b3b5-a52703d8a79c" type="Dynamo.Nodes.DSModelElementSelection" nickname="Select Model Element" x="1136.45614851634" y="-347.824636682746" isVisible="true" isUpstreamVisible="true" lacing="Disabled" isSelectedInput="True" IsFrozen="false" isPinned="true" />
    <Dynamo.Graph.Nodes.ZeroTouch.DSFunction guid="1c1ce5aa-9f16-47e5-8f19-683bcf44bcc6" type="Dynamo.Graph.Nodes.ZeroTouch.DSFunction" nickname="Element.BoundingBox" x="1419.10829652735" y="-597.100926516224" isVisible="true" isUpstreamVisible="true" lacing="Shortest" isSelectedInput="False" IsFrozen="false" isPinned="true" assembly="RevitNodes.dll" function="Revit.Elements.Element.BoundingBox">
      <PortInfo index="0" default="False" />
    </Dynamo.Graph.Nodes.ZeroTouch.DSFunction>
    <DSRevitNodesUI.Views guid="ad2513a7-c3c0-4047-80d4-cfe751745a49" type="DSRevitNodesUI.Views" nickname="Views" x="377.694282397741" y="117.990125259973" isVisible="true" isUpstreamVisible="true" lacing="Disabled" isSelectedInput="True" IsFrozen="false" isPinned="true" index="12:70 - Sh - G.A. Section" />
    <PythonNodeModels.PythonNode guid="3d0be72e-7a7c-4693-84ba-9fccf237deb0" type="PythonNodeModels.PythonNode" nickname="Python Script" x="1719.78303865927" y="809.547813977541" isVisible="true" isUpstreamVisible="true" lacing="Disabled" isSelectedInput="False" IsFrozen="false" isPinned="true" inputcount="4">
      <PortInfo index="0" default="False" />
      <PortInfo index="1" default="False" />
      <PortInfo index="2" default="False" />
      <PortInfo index="3" default="False" />
      <Script>import clr
clr.AddReference("ProtoGeometry")
from Autodesk.DesignScript.Geometry import *
# Import RevitAPI
clr.AddReference("RevitAPI")
from Autodesk.Revit.DB import *
clr.AddReference("RevitAPIUI")
from Autodesk.Revit.UI import TaskDialog
# Import DocumentManager and TransactionManager
clr.AddReference("RevitServices")
from RevitServices.Persistence import DocumentManager
from RevitServices.Transactions import TransactionManager
# Import ToProtoType, ToRevitType geometry conversion extension methods
clr.AddReference("RevitNodes")
import Revit
clr.ImportExtensions(Revit.GeometryConversion)

doc = DocumentManager.Instance.CurrentDBDocument
uiapp = DocumentManager.Instance.CurrentUIApplication
app = uiapp.Application


wall = UnwrapElement(IN[0])

vft = UnwrapElement(IN[1])

midpoint = UnwrapElement(IN[2])[0].ToXyz()




'start point'
p = UnwrapElement(IN[3])[0].ToXyz()
'end point'
q = UnwrapElement(IN[3])[1].ToXyz()

'wall length'
v = q - p

bb = wall.get_BoundingBox( None )

minZ = bb.Min.Z;
maxZ = bb.Max.Z;


'bb Height'
h = maxZ - minZ;



'section extent in x direction'
offset = 0.1
"""
min = XYZ(-w, minZ - offset, -offset)
max = XYZ(w, maxZ + offset, 0)
(width in plan, height view in section, position in plan)

"""
min = XYZ(-2, -10, 0)
max = XYZ(2, 40, 0.1)



walldir = -v.Normalize() #+- change view direction
up = XYZ.BasisZ;
viewdir = walldir.CrossProduct( up );
 
 
t = Transform.Identity;
t.Origin = XYZ(midpoint.X, midpoint.Y, 0) ;
t.BasisX = walldir;
t.BasisY = up;
t.BasisZ = viewdir


sectionBox = BoundingBoxXYZ();
sectionBox.Transform = t;
sectionBox.Min = min;
sectionBox.Max = max;

	

TransactionManager.Instance.EnsureInTransaction(doc)

section=ViewSection.CreateSection( doc, vft.Id, sectionBox )

TransactionManager.Instance.TransactionTaskDone()


OUT = section, midpoint</Script>
    </PythonNodeModels.PythonNode>
    <Dynamo.Graph.Nodes.CodeBlockNodeModel guid="d460f884-c087-4782-9251-f88e7c71d61e" type="Dynamo.Graph.Nodes.CodeBlockNodeModel" nickname="Code Block" x="1089.72477769451" y="1175.85391601715" isVisible="true" isUpstreamVisible="true" lacing="Disabled" isSelectedInput="False" IsFrozen="false" isPinned="false" CodeText="{-500,500};" ShouldFocus="false" />
    <Dynamo.Graph.Nodes.ZeroTouch.DSFunction guid="ecbbcdba-dc90-483a-85ec-618d4bb6ddd9" type="Dynamo.Graph.Nodes.ZeroTouch.DSFunction" nickname="Geometry.Translate" x="1291.60978111785" y="1010.55196449368" isVisible="true" isUpstreamVisible="true" lacing="Longest" isSelectedInput="False" IsFrozen="false" isPinned="true" assembly="ProtoGeometry.dll" function="Autodesk.DesignScript.Geometry.Geometry.Translate@Autodesk.DesignScript.Geometry.Vector,double">
      <PortInfo index="0" default="False" />
      <PortInfo index="1" default="False" />
      <PortInfo index="2" default="False" />
    </Dynamo.Graph.Nodes.ZeroTouch.DSFunction>
    <RhythmUI.ViewFamilyTypes guid="13b14221-8c99-4146-983a-5ef3d90e38d0" type="RhythmUI.ViewFamilyTypes" nickname="ViewFamilyTypes" x="1099.11169980688" y="851.684100322387" isVisible="true" isUpstreamVisible="true" lacing="Disabled" isSelectedInput="True" IsFrozen="false" isPinned="true" index="70:70 - Sh - GA Section" />
    <Dynamo.Nodes.DSModelElementSelection guid="eb67e0d0-3ec1-4d28-8874-a8a7214bc02b" type="Dynamo.Nodes.DSModelElementSelection" nickname="Select Model Element" x="533.004091288275" y="1492.4561874057" isVisible="true" isUpstreamVisible="true" lacing="Disabled" isSelectedInput="True" IsFrozen="false" isPinned="true">
      <instance id="b9e43037-37e5-488a-8873-b4c655eb6298-00220554" />
    </Dynamo.Nodes.DSModelElementSelection>
    <Dynamo.Graph.Nodes.CustomNodes.Function guid="9a89db79-5469-4479-bc52-3116d30e5e2b" type="Dynamo.Graph.Nodes.CustomNodes.Function" nickname="Element.LocalCoordinateSystem" x="759.692044334909" y="1614.35989049616" isVisible="true" isUpstreamVisible="true" lacing="Shortest" isSelectedInput="False" IsFrozen="false" isPinned="true">
      <PortInfo index="0" default="False" />
      <ID value="98f07818-2169-443a-8e91-de302bc56b98" />
      <Name value="Element.LocalCoordinateSystem" />
      <Description value="Get the insertion point and local axes of an element. " />
      <Inputs>
        <Input value="element" />
      </Inputs>
      <Outputs>
        <Output value="Xvector" />
        <Output value="Yvector" />
        <Output value="Zvector" />
        <Output value="InsertionPoint" />
        <Output value="Invalid Elements" />
      </Outputs>
    </Dynamo.Graph.Nodes.CustomNodes.Function>
    <PythonNodeModels.PythonNode guid="a81e3f42-fd8d-41ba-b20b-07d65fb1301f" type="PythonNodeModels.PythonNode" nickname="Python Script" x="1734.79381875624" y="1473.90862934883" isVisible="true" isUpstreamVisible="true" lacing="Disabled" isSelectedInput="False" IsFrozen="false" isPinned="true" inputcount="4">
      <PortInfo index="0" default="False" />
      <PortInfo index="1" default="False" />
      <PortInfo index="2" default="False" />
      <PortInfo index="3" default="False" />
      <Script>import clr
clr.AddReference("ProtoGeometry")
from Autodesk.DesignScript.Geometry import *
# Import RevitAPI
clr.AddReference("RevitAPI")
from Autodesk.Revit.DB import *
clr.AddReference("RevitAPIUI")
from Autodesk.Revit.UI import TaskDialog
# Import DocumentManager and TransactionManager
clr.AddReference("RevitServices")
from RevitServices.Persistence import DocumentManager
from RevitServices.Transactions import TransactionManager
# Import ToProtoType, ToRevitType geometry conversion extension methods
clr.AddReference("RevitNodes")
import Revit
clr.ImportExtensions(Revit.GeometryConversion)

doc = DocumentManager.Instance.CurrentDBDocument
uiapp = DocumentManager.Instance.CurrentUIApplication
app = uiapp.Application


wall = UnwrapElement(IN[0])

vft = UnwrapElement(IN[1])

midpoint = UnwrapElement(IN[2])[0].ToXyz()




'start point'
p = UnwrapElement(IN[3])[0].ToXyz()
'end point'
q = UnwrapElement(IN[3])[1].ToXyz()

'wall length'
v = q - p

bb = wall.get_BoundingBox( None )

minZ = bb.Min.Z;
maxZ = bb.Max.Z;


'bb Height'
h = maxZ - minZ;



'section extent in x direction'
offset = 0.1
"""
min = XYZ(-w, minZ - offset, -offset)
max = XYZ(w, maxZ + offset, 0)
(width in plan, height view in section, position in plan)

"""
min = XYZ(-2, -10, 0)
max = XYZ(2, 40, 0.1)



walldir = -v.Normalize() #+- change view direction
up = XYZ.BasisZ;
viewdir = walldir.CrossProduct( up );
 
 
t = Transform.Identity;
t.Origin = XYZ(midpoint.X, midpoint.Y, 0) ;
t.BasisX = walldir;
t.BasisY = up;
t.BasisZ = viewdir


sectionBox = BoundingBoxXYZ();
sectionBox.Transform = t;
sectionBox.Min = min;
sectionBox.Max = max;

	

TransactionManager.Instance.EnsureInTransaction(doc)

section=ViewSection.CreateSection( doc, vft.Id, sectionBox )

TransactionManager.Instance.TransactionTaskDone()


OUT = section, midpoint</Script>
    </PythonNodeModels.PythonNode>
    <Dynamo.Graph.Nodes.CodeBlockNodeModel guid="284066fb-42f4-458e-a38c-de6ab8056740" type="Dynamo.Graph.Nodes.CodeBlockNodeModel" nickname="Code Block" x="1104.73555779148" y="1840.21473138844" isVisible="true" isUpstreamVisible="true" lacing="Disabled" isSelectedInput="False" IsFrozen="false" isPinned="false" CodeText="{-500,500};" ShouldFocus="false" />
    <Dynamo.Graph.Nodes.ZeroTouch.DSFunction guid="82044f23-1830-4b07-975a-5ac2789ccfef" type="Dynamo.Graph.Nodes.ZeroTouch.DSFunction" nickname="Geometry.Translate" x="1306.62056121482" y="1674.91277986497" isVisible="true" isUpstreamVisible="true" lacing="Longest" isSelectedInput="False" IsFrozen="false" isPinned="true" assembly="ProtoGeometry.dll" function="Autodesk.DesignScript.Geometry.Geometry.Translate@Autodesk.DesignScript.Geometry.Vector,double">
      <PortInfo index="0" default="False" />
      <PortInfo index="1" default="False" />
      <PortInfo index="2" default="False" />
    </Dynamo.Graph.Nodes.ZeroTouch.DSFunction>
    <RhythmUI.ViewFamilyTypes guid="8f738eaf-6b49-4943-ac9d-70d3d3b3b984" type="RhythmUI.ViewFamilyTypes" nickname="ViewFamilyTypes" x="1114.12247990385" y="1516.04491569367" isVisible="true" isUpstreamVisible="true" lacing="Disabled" isSelectedInput="True" IsFrozen="false" isPinned="true" index="70:70 - Sh - GA Section" />
  </Elements>
  <Connectors>
    <Dynamo.Graph.Connectors.ConnectorModel start="954f072a-101a-4d75-9fa7-bfb55e5979c5" start_index="0" end="98d7e777-2494-48bc-87d1-ff4ace380125" end_index="1" portType="0" />
    <Dynamo.Graph.Connectors.ConnectorModel start="954f072a-101a-4d75-9fa7-bfb55e5979c5" start_index="0" end="3d41a116-6a27-4674-bd5e-f7ec0ca4e9b2" end_index="1" portType="0" />
    <Dynamo.Graph.Connectors.ConnectorModel start="0b6eafab-2753-4cd1-a7a0-5477acce0b51" start_index="0" end="98d7e777-2494-48bc-87d1-ff4ace380125" end_index="2" portType="0" />
    <Dynamo.Graph.Connectors.ConnectorModel start="1c142951-358a-498b-b38d-4958d744d662" start_index="0" end="0b6eafab-2753-4cd1-a7a0-5477acce0b51" end_index="0" portType="0" />
    <Dynamo.Graph.Connectors.ConnectorModel start="1c142951-358a-498b-b38d-4958d744d662" start_index="0" end="98d7e777-2494-48bc-87d1-ff4ace380125" end_index="0" portType="0" />
    <Dynamo.Graph.Connectors.ConnectorModel start="8d147b41-bbb6-4bc7-8612-d363c6689b6c" start_index="0" end="05b26f54-f95d-4979-be3b-18f8883f66d4" end_index="0" portType="0" />
    <Dynamo.Graph.Connectors.ConnectorModel start="8d147b41-bbb6-4bc7-8612-d363c6689b6c" start_index="0" end="3d0be72e-7a7c-4693-84ba-9fccf237deb0" end_index="0" portType="0" />
    <Dynamo.Graph.Connectors.ConnectorModel start="05b26f54-f95d-4979-be3b-18f8883f66d4" start_index="0" end="ecbbcdba-dc90-483a-85ec-618d4bb6ddd9" end_index="1" portType="0" />
    <Dynamo.Graph.Connectors.ConnectorModel start="05b26f54-f95d-4979-be3b-18f8883f66d4" start_index="3" end="3d0be72e-7a7c-4693-84ba-9fccf237deb0" end_index="2" portType="0" />
    <Dynamo.Graph.Connectors.ConnectorModel start="05b26f54-f95d-4979-be3b-18f8883f66d4" start_index="3" end="ecbbcdba-dc90-483a-85ec-618d4bb6ddd9" end_index="0" portType="0" />
    <Dynamo.Graph.Connectors.ConnectorModel start="7accce7d-0023-4cb0-be89-45c2809cc983" start_index="0" end="55df0f9e-d910-4217-835e-7597fbccd5c0" end_index="0" portType="0" />
    <Dynamo.Graph.Connectors.ConnectorModel start="3d41a116-6a27-4674-bd5e-f7ec0ca4e9b2" start_index="0" end="7accce7d-0023-4cb0-be89-45c2809cc983" end_index="0" portType="0" />
    <Dynamo.Graph.Connectors.ConnectorModel start="a129e65a-6273-40ab-b3b5-a52703d8a79c" start_index="0" end="3d41a116-6a27-4674-bd5e-f7ec0ca4e9b2" end_index="0" portType="0" />
    <Dynamo.Graph.Connectors.ConnectorModel start="a129e65a-6273-40ab-b3b5-a52703d8a79c" start_index="0" end="1c1ce5aa-9f16-47e5-8f19-683bcf44bcc6" end_index="0" portType="0" />
    <Dynamo.Graph.Connectors.ConnectorModel start="ad2513a7-c3c0-4047-80d4-cfe751745a49" start_index="0" end="954f072a-101a-4d75-9fa7-bfb55e5979c5" end_index="0" portType="0" />
    <Dynamo.Graph.Connectors.ConnectorModel start="d460f884-c087-4782-9251-f88e7c71d61e" start_index="0" end="ecbbcdba-dc90-483a-85ec-618d4bb6ddd9" end_index="2" portType="0" />
    <Dynamo.Graph.Connectors.ConnectorModel start="ecbbcdba-dc90-483a-85ec-618d4bb6ddd9" start_index="0" end="3d0be72e-7a7c-4693-84ba-9fccf237deb0" end_index="3" portType="0" />
    <Dynamo.Graph.Connectors.ConnectorModel start="13b14221-8c99-4146-983a-5ef3d90e38d0" start_index="0" end="3d0be72e-7a7c-4693-84ba-9fccf237deb0" end_index="1" portType="0" />
    <Dynamo.Graph.Connectors.ConnectorModel start="eb67e0d0-3ec1-4d28-8874-a8a7214bc02b" start_index="0" end="9a89db79-5469-4479-bc52-3116d30e5e2b" end_index="0" portType="0" />
    <Dynamo.Graph.Connectors.ConnectorModel start="eb67e0d0-3ec1-4d28-8874-a8a7214bc02b" start_index="0" end="a81e3f42-fd8d-41ba-b20b-07d65fb1301f" end_index="0" portType="0" />
    <Dynamo.Graph.Connectors.ConnectorModel start="9a89db79-5469-4479-bc52-3116d30e5e2b" start_index="1" end="82044f23-1830-4b07-975a-5ac2789ccfef" end_index="1" portType="0" />
    <Dynamo.Graph.Connectors.ConnectorModel start="9a89db79-5469-4479-bc52-3116d30e5e2b" start_index="3" end="a81e3f42-fd8d-41ba-b20b-07d65fb1301f" end_index="2" portType="0" />
    <Dynamo.Graph.Connectors.ConnectorModel start="9a89db79-5469-4479-bc52-3116d30e5e2b" start_index="3" end="82044f23-1830-4b07-975a-5ac2789ccfef" end_index="0" portType="0" />
    <Dynamo.Graph.Connectors.ConnectorModel start="284066fb-42f4-458e-a38c-de6ab8056740" start_index="0" end="82044f23-1830-4b07-975a-5ac2789ccfef" end_index="2" portType="0" />
    <Dynamo.Graph.Connectors.ConnectorModel start="82044f23-1830-4b07-975a-5ac2789ccfef" start_index="0" end="a81e3f42-fd8d-41ba-b20b-07d65fb1301f" end_index="3" portType="0" />
    <Dynamo.Graph.Connectors.ConnectorModel start="8f738eaf-6b49-4943-ac9d-70d3d3b3b984" start_index="0" end="a81e3f42-fd8d-41ba-b20b-07d65fb1301f" end_index="1" portType="0" />
  </Connectors>
  <Notes />
  <Annotations>
    <Dynamo.Graph.Annotations.AnnotationModel guid="cf38ff8f-15df-4c83-a656-dc897f590eba" annotationText="Cross Section (X-Vector)" left="507.993311191306" top="763.547813977541" width="1345.78972746797" height="505.306102039606" fontSize="30" InitialTop="809.547813977541" InitialHeight="489.306102039606" TextblockHeight="36" backgrouund="#FFC1D676">
      <Models ModelGuid="8d147b41-bbb6-4bc7-8612-d363c6689b6c" />
      <Models ModelGuid="05b26f54-f95d-4979-be3b-18f8883f66d4" />
      <Models ModelGuid="3d0be72e-7a7c-4693-84ba-9fccf237deb0" />
      <Models ModelGuid="d460f884-c087-4782-9251-f88e7c71d61e" />
      <Models ModelGuid="ecbbcdba-dc90-483a-85ec-618d4bb6ddd9" />
      <Models ModelGuid="13b14221-8c99-4146-983a-5ef3d90e38d0" />
    </Dynamo.Graph.Annotations.AnnotationModel>
    <Dynamo.Graph.Annotations.AnnotationModel guid="35b45854-9779-415a-816b-5b1f38d58690" annotationText="Cross Section (Y-Vector)" left="523.004091288275" top="1427.90862934883" width="1345.78972746796" height="505.306102039609" fontSize="30" InitialTop="1473.90862934883" InitialHeight="489.306102039609" TextblockHeight="36" backgrouund="#FFC1D676">
      <Models ModelGuid="eb67e0d0-3ec1-4d28-8874-a8a7214bc02b" />
      <Models ModelGuid="9a89db79-5469-4479-bc52-3116d30e5e2b" />
      <Models ModelGuid="a81e3f42-fd8d-41ba-b20b-07d65fb1301f" />
      <Models ModelGuid="284066fb-42f4-458e-a38c-de6ab8056740" />
      <Models ModelGuid="82044f23-1830-4b07-975a-5ac2789ccfef" />
      <Models ModelGuid="8f738eaf-6b49-4943-ac9d-70d3d3b3b984" />
    </Dynamo.Graph.Annotations.AnnotationModel>
  </Annotations>
  <Presets />
  <Cameras>
    <Camera Name="Background Preview" eyeX="-36.5403900146484" eyeY="39.5854225158691" eyeZ="176.611892700195" lookX="36.5403900146484" lookY="-39.5854225158691" lookZ="-176.611892700195" upX="0" upY="1" upZ="0" />
  </Cameras>
</Workspace>