{
  "Uuid": "3c9d0464-8643-5ffe-96e5-ab1769818209",
  "IsCustomNode": false,
  "Description": "",
  "Name": "setLocation",
  "ElementResolver": {
    "ResolutionMap": {}
  },
  "Inputs": [],
  "Outputs": [],
  "Nodes": [
    {
      "ConcreteType": "Dynamo.Graph.Nodes.ZeroTouch.DSFunction, DynamoCore",
      "NodeType": "FunctionNode",
      "FunctionSignature": "Revit.Elements.Element.SetLocation@Autodesk.DesignScript.Geometry.Geometry",
      "Id": "bed1c3f3838146af85e4a09d05462e93",
      "Inputs": [
        {
          "Id": "1860c1861e3b47a6810353f5f2efbffd",
          "Name": "element",
          "Description": "Revit.Elements.Element",
          "UsingDefaultValue": false,
          "Level": 2,
          "UseLevels": false,
          "KeepListStructure": false
        },
        {
          "Id": "95b70c59d68b436ba1b5f67517dbb663",
          "Name": "geometry",
          "Description": "New Location Point or Curve\n\nGeometry",
          "UsingDefaultValue": false,
          "Level": 2,
          "UseLevels": false,
          "KeepListStructure": false
        }
      ],
      "Outputs": [
        {
          "Id": "e0766b0cff724ab087b4079c7451d598",
          "Name": "void",
          "Description": "void",
          "UsingDefaultValue": false,
          "Level": 2,
          "UseLevels": false,
          "KeepListStructure": false
        }
      ],
      "Replication": "Longest",
      "Description": "Update an existing element's location\n\nElement.SetLocation (geometry: Geometry): void"
    },
    {
      "ConcreteType": "Dynamo.Nodes.DSModelElementSelection, DSRevitNodesUI",
      "NodeType": "ExtensionNode",
      "InstanceId": [],
      "Id": "f920a397279d4cd99f3da43c86efd8fc",
      "Inputs": [],
      "Outputs": [
        {
          "Id": "203a5a835c8b4eb8a4aed66bc8ffe2a2",
          "Name": "Element",
          "Description": "The selected elements.",
          "UsingDefaultValue": false,
          "Level": 2,
          "UseLevels": false,
          "KeepListStructure": false
        }
      ],
      "Replication": "Disabled"
    },
    {
      "ConcreteType": "Dynamo.Nodes.DSModelElementSelection, DSRevitNodesUI",
      "NodeType": "ExtensionNode",
      "InstanceId": [],
      "Id": "c218efdeb4eb4a8fbced3231382eb0e4",
      "Inputs": [],
      "Outputs": [
        {
          "Id": "f3361bfe68c944f1b828f2a72bc1a6be",
          "Name": "Element",
          "Description": "The selected elements.",
          "UsingDefaultValue": false,
          "Level": 2,
          "UseLevels": false,
          "KeepListStructure": false
        }
      ],
      "Replication": "Disabled"
    },
    {
      "ConcreteType": "Dynamo.Graph.Nodes.ZeroTouch.DSFunction, DynamoCore",
      "NodeType": "FunctionNode",
      "FunctionSignature": "Revit.Elements.StructuralFraming.Location",
      "Id": "e61b2a9d4d76453bb24f3a72ace814e5",
      "Inputs": [
        {
          "Id": "b41c0e03bc0746358a41c8036e77c5b3",
          "Name": "structuralFraming",
          "Description": "Revit.Elements.StructuralFraming",
          "UsingDefaultValue": false,
          "Level": 2,
          "UseLevels": false,
          "KeepListStructure": false
        }
      ],
      "Outputs": [
        {
          "Id": "969054f5c608484a9a8c9ee17eade5e6",
          "Name": "Curve",
          "Description": "Curve",
          "UsingDefaultValue": false,
          "Level": 2,
          "UseLevels": false,
          "KeepListStructure": false
        }
      ],
      "Replication": "Auto",
      "Description": "Gets curve geometry from location of the specified structural element\n\nStructuralFraming.Location: Curve"
    },
    {
      "ConcreteType": "Dynamo.Graph.Nodes.ZeroTouch.DSFunction, DynamoCore",
      "NodeType": "FunctionNode",
      "FunctionSignature": "Revit.Elements.StructuralFraming.Location",
      "Id": "02d0af545ca84272a7ba52ab300f2a8f",
      "Inputs": [
        {
          "Id": "34307c1ee6a94acebb72ed939cd520d9",
          "Name": "structuralFraming",
          "Description": "Revit.Elements.StructuralFraming",
          "UsingDefaultValue": false,
          "Level": 2,
          "UseLevels": false,
          "KeepListStructure": false
        }
      ],
      "Outputs": [
        {
          "Id": "2803f173c29d4f0f97bed9738d6a6c74",
          "Name": "Curve",
          "Description": "Curve",
          "UsingDefaultValue": false,
          "Level": 2,
          "UseLevels": false,
          "KeepListStructure": false
        }
      ],
      "Replication": "Auto",
      "Description": "Gets curve geometry from location of the specified structural element\n\nStructuralFraming.Location: Curve"
    },
    {
      "ConcreteType": "Dynamo.Graph.Nodes.ZeroTouch.DSFunction, DynamoCore",
      "NodeType": "FunctionNode",
      "FunctionSignature": "Autodesk.DesignScript.Geometry.Geometry.IntersectAll@Autodesk.DesignScript.Geometry.Geometry[]",
      "Id": "561bcceb898140c38f8e40a41071a725",
      "Inputs": [
        {
          "Id": "fb45a55decdf4aa8b994e873fbf5fc33",
          "Name": "geometry",
          "Description": "Autodesk.DesignScript.Geometry.Geometry",
          "UsingDefaultValue": false,
          "Level": 2,
          "UseLevels": false,
          "KeepListStructure": false
        },
        {
          "Id": "66bcbdb1dfc6411eb2f367c048ab8464",
          "Name": "others",
          "Description": "Geometry[]",
          "UsingDefaultValue": false,
          "Level": 2,
          "UseLevels": false,
          "KeepListStructure": false
        }
      ],
      "Outputs": [
        {
          "Id": "9499463832e84d5f97e4e20cd66b1615",
          "Name": "Geometry[]",
          "Description": "Geometry[]",
          "UsingDefaultValue": false,
          "Level": 2,
          "UseLevels": false,
          "KeepListStructure": false
        }
      ],
      "Replication": "Auto",
      "Description": "Get the intersection of Geometry for this object and a collection of other Geometries. Finds common geometry of all participants.\n\nGeometry.IntersectAll (others: Geometry[]): Geometry[]"
    },
    {
      "ConcreteType": "Dynamo.Graph.Nodes.ZeroTouch.DSFunction, DynamoCore",
      "NodeType": "FunctionNode",
      "FunctionSignature": "Autodesk.DesignScript.Geometry.Curve.EndPoint",
      "Id": "ad8af835d72a4e899bde97222f7b36bc",
      "Inputs": [
        {
          "Id": "69974e4140944289a5e88d2ef711cb5f",
          "Name": "curve",
          "Description": "Autodesk.DesignScript.Geometry.Curve",
          "UsingDefaultValue": false,
          "Level": 2,
          "UseLevels": false,
          "KeepListStructure": false
        }
      ],
      "Outputs": [
        {
          "Id": "82af70e43f644657b0553a93af996110",
          "Name": "Point",
          "Description": "Point",
          "UsingDefaultValue": false,
          "Level": 2,
          "UseLevels": false,
          "KeepListStructure": false
        }
      ],
      "Replication": "Auto",
      "Description": "Get the end Point along the Curve\n\nCurve.EndPoint: Point"
    },
    {
      "ConcreteType": "Dynamo.Graph.Nodes.ZeroTouch.DSFunction, DynamoCore",
      "NodeType": "FunctionNode",
      "FunctionSignature": "Autodesk.DesignScript.Geometry.Curve.StartPoint",
      "Id": "8309d7ded7104d5f854a926647a2e38b",
      "Inputs": [
        {
          "Id": "8c246c0d54cd404082620f072e5df2bc",
          "Name": "curve",
          "Description": "Autodesk.DesignScript.Geometry.Curve",
          "UsingDefaultValue": false,
          "Level": 2,
          "UseLevels": false,
          "KeepListStructure": false
        }
      ],
      "Outputs": [
        {
          "Id": "f2839f50be0e4067b6025ff133557ab2",
          "Name": "Point",
          "Description": "Point",
          "UsingDefaultValue": false,
          "Level": 2,
          "UseLevels": false,
          "KeepListStructure": false
        }
      ],
      "Replication": "Auto",
      "Description": "Get the start Point along the Curve\n\nCurve.StartPoint: Point"
    },
    {
      "ConcreteType": "Dynamo.Graph.Nodes.ZeroTouch.DSFunction, DynamoCore",
      "NodeType": "FunctionNode",
      "FunctionSignature": "Autodesk.DesignScript.Geometry.Line.ByStartPointEndPoint@Autodesk.DesignScript.Geometry.Point,Autodesk.DesignScript.Geometry.Point",
      "Id": "30082ff0ed70468da129dc407f5e45b4",
      "Inputs": [
        {
          "Id": "038b03c4ee1e4ee786228db74ec9e7b0",
          "Name": "startPoint",
          "Description": "Point",
          "UsingDefaultValue": false,
          "Level": 2,
          "UseLevels": false,
          "KeepListStructure": false
        },
        {
          "Id": "0c2cd6090c73449dbbfccc804b05c02b",
          "Name": "endPoint",
          "Description": "Point",
          "UsingDefaultValue": false,
          "Level": 2,
          "UseLevels": false,
          "KeepListStructure": false
        }
      ],
      "Outputs": [
        {
          "Id": "cd11e1ac4e8342af9b5fc9762ec0c2a7",
          "Name": "Line",
          "Description": "Line",
          "UsingDefaultValue": false,
          "Level": 2,
          "UseLevels": false,
          "KeepListStructure": false
        }
      ],
      "Replication": "Auto",
      "Description": "Creates a straight Line between two input Points.\n\nLine.ByStartPointEndPoint (startPoint: Point, endPoint: Point): Line"
    },
    {
      "ConcreteType": "Dynamo.Graph.Nodes.ZeroTouch.DSFunction, DynamoCore",
      "NodeType": "FunctionNode",
      "FunctionSignature": "Autodesk.DesignScript.Geometry.Line.ByStartPointEndPoint@Autodesk.DesignScript.Geometry.Point,Autodesk.DesignScript.Geometry.Point",
      "Id": "b640a6ff376c4e4e966ae4749e114b21",
      "Inputs": [
        {
          "Id": "b9e8ba03b8634523a0f846a1c1df8718",
          "Name": "startPoint",
          "Description": "Point",
          "UsingDefaultValue": false,
          "Level": 2,
          "UseLevels": false,
          "KeepListStructure": false
        },
        {
          "Id": "e407ef0c37bf4ea88a3b626a2172621b",
          "Name": "endPoint",
          "Description": "Point",
          "UsingDefaultValue": false,
          "Level": 2,
          "UseLevels": false,
          "KeepListStructure": false
        }
      ],
      "Outputs": [
        {
          "Id": "ed9f948d3d6341098857aa9b34fcb46e",
          "Name": "Line",
          "Description": "Line",
          "UsingDefaultValue": false,
          "Level": 2,
          "UseLevels": false,
          "KeepListStructure": false
        }
      ],
      "Replication": "Auto",
      "Description": "Creates a straight Line between two input Points.\n\nLine.ByStartPointEndPoint (startPoint: Point, endPoint: Point): Line"
    },
    {
      "ConcreteType": "Dynamo.Graph.Nodes.CodeBlockNodeModel, DynamoCore",
      "NodeType": "CodeBlockNode",
      "Code": "[a,b];",
      "Id": "9bf21168a2944f2e93428aea7d4d9b5e",
      "Inputs": [
        {
          "Id": "7face402775748c1a3d1ba3709be67aa",
          "Name": "a",
          "Description": "a",
          "UsingDefaultValue": false,
          "Level": 2,
          "UseLevels": false,
          "KeepListStructure": false
        },
        {
          "Id": "89be394ee7504f9aa72fb00486758167",
          "Name": "b",
          "Description": "b",
          "UsingDefaultValue": false,
          "Level": 2,
          "UseLevels": false,
          "KeepListStructure": false
        }
      ],
      "Outputs": [
        {
          "Id": "7928c8575e4d4dc9837e20cff8af6ce3",
          "Name": "",
          "Description": "Value of expression at line 1",
          "UsingDefaultValue": false,
          "Level": 2,
          "UseLevels": false,
          "KeepListStructure": false
        }
      ],
      "Replication": "Disabled",
      "Description": "Allows for DesignScript code to be authored directly"
    },
    {
      "ConcreteType": "PythonNodeModels.PythonNode, PythonNodeModels",
      "NodeType": "PythonScriptNode",
      "Code": "import clr\n# Import RevitAPI\nclr.AddReference(\"RevitAPI\")\nimport Autodesk\nfrom Autodesk.Revit.DB import *\n# Import DocumentManager and TransactionManager\nclr.AddReference(\"RevitServices\")\nimport RevitServices\nfrom RevitServices.Persistence import DocumentManager\nfrom RevitServices.Transactions import TransactionManager\n# Import ToDSType(bool) extension method\nclr.AddReference(\"RevitNodes\")\nimport Revit\nclr.ImportExtensions(Revit.Elements)\nclr.ImportExtensions(Revit.GeometryConversion)\n\ndef GetEndPoints(line):\n\treturn [Curve.GetEndPoint(0).ToPoint(), \n\t\tCurve.GetEndPoint(1).ToPoint()]\n\t\t\n# Unwrap\nbeam = UnwrapElement( IN[0] )\n#lines = UnwrapElement( IN[1] )\n\n# Start Transaction\ndoc = DocumentManager.Instance.CurrentDBDocument\n\nTransactionManager.Instance.EnsureInTransaction(doc)\n\ntry:\n\tnewBeamId = ElementTransformUtils.CopyElement(doc, beam.Id, XYZ(0,0,0))\n\tnewBeam = doc.GetElement(newBeamId[0])\n\t#newBeam.Location.Curve = lines[1].ToRevitType()\n\t\n\t#beam.Location.Curve\t= lines[0].ToRevitType()\n\t\n\tOUT = beam, newBeam\nexcept:\n\tOUT = \"error\"\n# End Transaction\nTransactionManager.Instance.TransactionTaskDone()\n# Wrap\n",
      "VariableInputPorts": true,
      "Id": "cef107679517476fbbab5fea7196eeed",
      "Inputs": [
        {
          "Id": "2d18316d92874d95912706f043b823ea",
          "Name": "IN[0]",
          "Description": "Input #0",
          "UsingDefaultValue": false,
          "Level": 2,
          "UseLevels": false,
          "KeepListStructure": false
        }
      ],
      "Outputs": [
        {
          "Id": "80c3c1a8f951430492f96ee781352304",
          "Name": "OUT",
          "Description": "Result of the python script",
          "UsingDefaultValue": false,
          "Level": 2,
          "UseLevels": false,
          "KeepListStructure": false
        }
      ],
      "Replication": "Disabled",
      "Description": "Runs an embedded IronPython script."
    }
  ],
  "Connectors": [
    {
      "Start": "203a5a835c8b4eb8a4aed66bc8ffe2a2",
      "End": "b41c0e03bc0746358a41c8036e77c5b3",
      "Id": "25e729efb83f4861813a5526159f8588"
    },
    {
      "Start": "f3361bfe68c944f1b828f2a72bc1a6be",
      "End": "34307c1ee6a94acebb72ed939cd520d9",
      "Id": "8f38bf9944544bdf81ec231338957cf3"
    },
    {
      "Start": "f3361bfe68c944f1b828f2a72bc1a6be",
      "End": "2d18316d92874d95912706f043b823ea",
      "Id": "c100991e024148b59ea923023a56d4a9"
    },
    {
      "Start": "969054f5c608484a9a8c9ee17eade5e6",
      "End": "fb45a55decdf4aa8b994e873fbf5fc33",
      "Id": "b37d1440151f4fdea3f59e38159c45c7"
    },
    {
      "Start": "2803f173c29d4f0f97bed9738d6a6c74",
      "End": "66bcbdb1dfc6411eb2f367c048ab8464",
      "Id": "e95506a465be4b038e1009041e97701d"
    },
    {
      "Start": "2803f173c29d4f0f97bed9738d6a6c74",
      "End": "8c246c0d54cd404082620f072e5df2bc",
      "Id": "ad3dfa7fa96443caa168595e43e32b86"
    },
    {
      "Start": "2803f173c29d4f0f97bed9738d6a6c74",
      "End": "69974e4140944289a5e88d2ef711cb5f",
      "Id": "cac9228a26ac42c68c099b4593f019f4"
    },
    {
      "Start": "9499463832e84d5f97e4e20cd66b1615",
      "End": "0c2cd6090c73449dbbfccc804b05c02b",
      "Id": "e42f132dce02410f8ccc67a43bdbda9f"
    },
    {
      "Start": "9499463832e84d5f97e4e20cd66b1615",
      "End": "b9e8ba03b8634523a0f846a1c1df8718",
      "Id": "d38cf0d0e4df48f19066b5b45d853803"
    },
    {
      "Start": "82af70e43f644657b0553a93af996110",
      "End": "e407ef0c37bf4ea88a3b626a2172621b",
      "Id": "4c129af4f3044ef7b2529de1b70dfea1"
    },
    {
      "Start": "f2839f50be0e4067b6025ff133557ab2",
      "End": "038b03c4ee1e4ee786228db74ec9e7b0",
      "Id": "1818e53308864b68a8e22b516a902082"
    },
    {
      "Start": "cd11e1ac4e8342af9b5fc9762ec0c2a7",
      "End": "7face402775748c1a3d1ba3709be67aa",
      "Id": "48ee8e00d10644a789daf071eaf2ac67"
    },
    {
      "Start": "ed9f948d3d6341098857aa9b34fcb46e",
      "End": "89be394ee7504f9aa72fb00486758167",
      "Id": "9c861e39ee9249fcbea1cac1b5230bf4"
    },
    {
      "Start": "7928c8575e4d4dc9837e20cff8af6ce3",
      "End": "95b70c59d68b436ba1b5f67517dbb663",
      "Id": "8b02637cdf7248c1a737f4270c001e85"
    },
    {
      "Start": "80c3c1a8f951430492f96ee781352304",
      "End": "1860c1861e3b47a6810353f5f2efbffd",
      "Id": "056f3b920b7742fab4495bd9dcc34476"
    }
  ],
  "Dependencies": [],
  "Bindings": [],
  "View": {
    "Dynamo": {
      "ScaleFactor": 1.0,
      "HasRunWithoutCrash": false,
      "IsVisibleInDynamoLibrary": true,
      "Version": "2.0.1.5055",
      "RunType": "Manual",
      "RunPeriod": "1000"
    },
    "Camera": {
      "Name": "Background Preview",
      "EyeX": -2427.8857421875,
      "EyeY": 8.54290771484375,
      "EyeZ": 38.1145133972168,
      "LookX": 7.8857612609863281,
      "LookY": -8.54290771484375,
      "LookZ": -38.1145133972168,
      "UpX": 0.0,
      "UpY": 1.0,
      "UpZ": 0.0
    },
    "NodeViews": [
      {
        "ShowGeometry": true,
        "Name": "Element.SetLocation",
        "Id": "bed1c3f3838146af85e4a09d05462e93",
        "IsSetAsInput": false,
        "IsSetAsOutput": false,
        "Excluded": false,
        "X": 2852.49904850239,
        "Y": 1306.27239572881
      },
      {
        "ShowGeometry": true,
        "Name": "Select Model Element",
        "Id": "f920a397279d4cd99f3da43c86efd8fc",
        "IsSetAsInput": true,
        "IsSetAsOutput": false,
        "Excluded": false,
        "X": 866.540605617814,
        "Y": 1268.91020663866
      },
      {
        "ShowGeometry": true,
        "Name": "Select Model Element",
        "Id": "c218efdeb4eb4a8fbced3231382eb0e4",
        "IsSetAsInput": true,
        "IsSetAsOutput": false,
        "Excluded": false,
        "X": 1092.47459316238,
        "Y": 1115.0476572308
      },
      {
        "ShowGeometry": true,
        "Name": "StructuralFraming.Location",
        "Id": "e61b2a9d4d76453bb24f3a72ace814e5",
        "IsSetAsInput": false,
        "IsSetAsOutput": false,
        "Excluded": false,
        "X": 1378.54275684212,
        "Y": 1270.27813030514
      },
      {
        "ShowGeometry": true,
        "Name": "StructuralFraming.Location",
        "Id": "02d0af545ca84272a7ba52ab300f2a8f",
        "IsSetAsInput": false,
        "IsSetAsOutput": false,
        "Excluded": false,
        "X": 1380.91019797329,
        "Y": 1550.84705047118
      },
      {
        "ShowGeometry": true,
        "Name": "Geometry.IntersectAll",
        "Id": "561bcceb898140c38f8e40a41071a725",
        "IsSetAsInput": false,
        "IsSetAsOutput": false,
        "Excluded": false,
        "X": 1763.03285658972,
        "Y": 1362.89009064019
      },
      {
        "ShowGeometry": true,
        "Name": "Curve.EndPoint",
        "Id": "ad8af835d72a4e899bde97222f7b36bc",
        "IsSetAsInput": false,
        "IsSetAsOutput": false,
        "Excluded": false,
        "X": 1861.69643968278,
        "Y": 1744.87203619315
      },
      {
        "ShowGeometry": true,
        "Name": "Curve.StartPoint",
        "Id": "8309d7ded7104d5f854a926647a2e38b",
        "IsSetAsInput": false,
        "IsSetAsOutput": false,
        "Excluded": false,
        "X": 1886.13604283428,
        "Y": 1577.41549608107
      },
      {
        "ShowGeometry": true,
        "Name": "Line.ByStartPointEndPoint",
        "Id": "30082ff0ed70468da129dc407f5e45b4",
        "IsSetAsInput": false,
        "IsSetAsOutput": false,
        "Excluded": false,
        "X": 2150.44582506523,
        "Y": 1438.92441155595
      },
      {
        "ShowGeometry": true,
        "Name": "Line.ByStartPointEndPoint",
        "Id": "b640a6ff376c4e4e966ae4749e114b21",
        "IsSetAsInput": false,
        "IsSetAsOutput": false,
        "Excluded": false,
        "X": 2189.78246546946,
        "Y": 1698.88083991938
      },
      {
        "ShowGeometry": true,
        "Name": "Code Block",
        "Id": "9bf21168a2944f2e93428aea7d4d9b5e",
        "IsSetAsInput": false,
        "IsSetAsOutput": false,
        "Excluded": false,
        "X": 2495.0,
        "Y": 1519.0
      },
      {
        "ShowGeometry": true,
        "Name": "Python Script",
        "Id": "cef107679517476fbbab5fea7196eeed",
        "IsSetAsInput": false,
        "IsSetAsOutput": false,
        "Excluded": false,
        "X": 2479.4424469406,
        "Y": 1101.88774588389
      }
    ],
    "Annotations": [
      {
        "Id": "afdca808b1b8496480d80d7fdc9d3768",
        "Title": "PB beam",
        "Nodes": [
          "f920a397279d4cd99f3da43c86efd8fc"
        ],
        "Left": 856.540605617814,
        "Top": 1222.91020663866,
        "Width": 189.0,
        "Height": 165.0,
        "FontSize": 30.0,
        "InitialTop": 1268.91020663866,
        "InitialHeight": 149.0,
        "TextblockHeight": 36.0,
        "Background": "#FFC1D676"
      }
    ],
    "X": -894.080242382995,
    "Y": -670.450025312954,
    "Zoom": 0.775230660981312
  }
}