<Workspace Version="1.3.1.1736" X="-624.028969406656" Y="112.179180826493" zoom="0.874053649550263" ScaleFactor="1" Name="Home" Description="" RunType="Manual" RunPeriod="1000" HasRunWithoutCrash="True">
  <NamespaceResolutionMap>
    <ClassMap partialName="Autodesk.Point" resolvedName="Autodesk.DesignScript.Geometry.Point" assemblyName="ProtoGeometry.dll" />
    <ClassMap partialName="Autodesk.DesignScript.Geometry.Point" resolvedName="Autodesk.DesignScript.Geometry.Point" assemblyName="ProtoGeometry.dll" />
    <ClassMap partialName="DesignScript.Curve" resolvedName="Autodesk.DesignScript.Geometry.Curve" assemblyName="ProtoGeometry.dll" />
    <ClassMap partialName="Autodesk.DesignScript.Geometry.Curve" resolvedName="Autodesk.DesignScript.Geometry.Curve" assemblyName="ProtoGeometry.dll" />
    <ClassMap partialName="PolyCurve" resolvedName="Autodesk.DesignScript.Geometry.PolyCurve" assemblyName="ProtoGeometry.dll" />
    <ClassMap partialName="Curves.EndPoints" resolvedName="Geometry.Curves" assemblyName="LunchBox.dll" />
    <ClassMap partialName="Curves" resolvedName="Geometry.Curves" assemblyName="LunchBox.dll" />
    <ClassMap partialName="DesignScript.Curve.Length" resolvedName="Autodesk.DesignScript.Geometry.Curve" assemblyName="ProtoGeometry.dll" />
    <ClassMap partialName="Autodesk.DesignScript.Geometry.Curve.Length" resolvedName="Autodesk.DesignScript.Geometry.Curve" assemblyName="ProtoGeometry.dll" />
    <ClassMap partialName="DSCore" resolvedName="DSCore.List" assemblyName="DSCoreNodes.dll" />
    <ClassMap partialName="DSCore.List" resolvedName="DSCore.List" assemblyName="DSCoreNodes.dll" />
  </NamespaceResolutionMap>
  <Elements>
    <Dynamo.Graph.Nodes.CustomNodes.Function guid="8af93ef7-08b7-46f7-bc15-fa3f0352dc78" type="Dynamo.Graph.Nodes.CustomNodes.Function" nickname="CurveToLine" x="11583.2132412356" y="-837.598252866148" isVisible="true" isUpstreamVisible="true" lacing="Shortest" isSelectedInput="False" IsFrozen="false" isPinned="true">
      <PortInfo index="0" default="False" useLevels="True" level="1" shouldKeepListStructure="True" />
      <PortInfo index="1" default="False" />
      <ID value="a40ce386-e489-4fbb-9570-20512d6f3ad1" />
      <Name value="CurveToLine" />
      <Description value="Turn any none line curve into a list of individual lines." />
      <Inputs>
        <Input value="Crv" />
        <Input value="length" />
      </Inputs>
      <Outputs>
        <Output value="LineList" />
      </Outputs>
    </Dynamo.Graph.Nodes.CustomNodes.Function>
    <PythonNodeModels.PythonNode guid="62d64856-a3ac-4926-9806-3fbe966003c8" type="PythonNodeModels.PythonNode" nickname="Python Script" x="178.520878322906" y="434.803293314467" isVisible="false" isUpstreamVisible="true" lacing="Disabled" isSelectedInput="False" IsFrozen="false" isPinned="false" inputcount="1">
      <PortInfo index="0" default="False" />
      <Script>#Copyright(c) 2014, Nathan Miller
# The Proving Ground, http://theprovingground.org

import clr

# Import RevitAPI
clr.AddReference("RevitAPI")
import Autodesk
from Autodesk.Revit.DB import *

# Import DocumentManager and TransactionManager
clr.AddReference("RevitServices")
import RevitServices
from RevitServices.Persistence import DocumentManager
from RevitServices.Transactions import TransactionManager

# Import ToDSType(bool) extension method
clr.AddReference("RevitNodes")
import Revit
clr.ImportExtensions(Revit.Elements)
clr.ImportExtensions(Revit.GeometryConversion)

import clr
clr.AddReference('ProtoGeometry')
from Autodesk.DesignScript.Geometry import *

#The input to this node will be stored in the IN[0] variable.

doc =  DocumentManager.Instance.CurrentDBDocument
app =  DocumentManager.Instance.CurrentUIApplication.Application

toggle = IN[0]

output = []
rooms = []
names = []
numbers = []
areas = []
levels = []
boundaries = []
locations = []
areaschemes = []
elementids = []
uniqueids = []

if toggle == True:

	collector = FilteredElementCollector(doc)
	collector.OfCategory(BuiltInCategory.OST_Areas)
 
	famtypeitr = collector.GetElementIdIterator()
	famtypeitr.Reset()


	for item in famtypeitr:
		famtypeID = item
		faminst = doc.GetElement(famtypeID)
    
		#print faminst
		if faminst.Area &gt; 0:
			room = faminst
			for p in room.Parameters:
				if p.Definition.Name == 'LoadDescription':		
					roomname = p.AsString()
				if p.Definition.Name == 'Level':			
					level = p.AsValueString()
					if (level is None):
						level = p.AsString()

			number = faminst.Number
			area = faminst.Area
			location = faminst.Location.Point.ToPoint()
			areascheme = faminst.AreaScheme.Name
			elementid = faminst.Id.ToString()
			uniqueid = faminst.UniqueId
    	
			boptions = Autodesk.Revit.DB.SpatialElementBoundaryOptions()
			boundsegs = room.GetBoundarySegments(boptions)
			boundcurves = []
			for bound in boundsegs:
				crvs = []
				for seg in bound:
					crv = seg.GetCurve()
					crvs.append(Revit.GeometryConversion.RevitToProtoCurve.ToProtoType( crv, True ))
				boundcurves.append(crvs)
    	
			rooms.append(room)
			names.append(roomname)
			numbers.append(number)
			areas.append(area)
			levels.append(level)
			boundaries.append(boundcurves)
			areaschemes.append(areascheme)
			locations.append(location)
			elementids.append(elementid)
			uniqueids.append(uniqueid)
        
	output.append(rooms)
	output.append(names)
	output.append(numbers)
	output.append(areas)
	output.append(levels)
	output.append(locations)
	output.append(boundaries)
	output.append(areaschemes)
	output.append(elementids)
	output.append(uniqueids)
        
#Assign your output to the OUT variable
OUT = output</Script>
    </PythonNodeModels.PythonNode>
    <Dynamo.Graph.Nodes.CodeBlockNodeModel guid="84ac121e-8312-43d7-853f-926c77269688" type="Dynamo.Graph.Nodes.CodeBlockNodeModel" nickname="Code Block" x="-132" y="437" isVisible="true" isUpstreamVisible="true" lacing="Disabled" isSelectedInput="False" IsFrozen="false" isPinned="false" CodeText="1;" ShouldFocus="false" />
    <Dynamo.Graph.Nodes.CodeBlockNodeModel guid="d2810dfe-6143-4c89-9152-48a9c9035015" type="Dynamo.Graph.Nodes.CodeBlockNodeModel" nickname="Code Block" x="1111.2978653752" y="45.5052314884488" isVisible="true" isUpstreamVisible="true" lacing="Disabled" isSelectedInput="False" IsFrozen="false" isPinned="true" CodeText="A[6];" ShouldFocus="false">
      <PortInfo index="0" default="False" />
    </Dynamo.Graph.Nodes.CodeBlockNodeModel>
    <Dynamo.Graph.Nodes.CodeBlockNodeModel guid="f32ca865-b8c8-42ab-80d4-2fdd840b060c" type="Dynamo.Graph.Nodes.CodeBlockNodeModel" nickname="Code Block" x="1543.39940411343" y="23.9012548328779" isVisible="false" isUpstreamVisible="true" lacing="Disabled" isSelectedInput="False" IsFrozen="false" isPinned="true" CodeText="def ToLines(Crv, Len:double)&#xA;{&#xA;	output = 0;&#xA;	return = [Imperative]&#xA;	{&#xA;		if (Crv.Length != CrvLine(Crv))&#xA;		{&#xA;			output = SplitCurve(Crv,Len);&#xA;		}&#xA;		else&#xA;		{&#xA;			output = Crv;&#xA;		}&#xA;		return = output;&#xA;	}&#xA;};&#xA;&#xA;def CrvLine(Crv)&#xA;{&#xA;	return = [Imperative]&#xA;	{&#xA;		return = Crv.StartPoint.DistanceTo(Crv.EndPoint);&#xA;	}&#xA;};&#xA;&#xA;def SplitCurve(Crv, Len:double)&#xA;{&#xA;	output = 0;&#xA;	return = [Imperative]&#xA;	{&#xA;		counter = Math.Ceiling(Crv.Length/Len)+1;&#xA;		counter = Math.Max(counter,11);&#xA;		params = 0..1..#counter;&#xA;		PointList = Crv.PointAtParameter(params);&#xA;		Poly = PolyCurve.ByPoints(PointList);&#xA;		return = Poly.Curves();&#xA;	}&#xA;};&#xA;ToLines(Curv,length);" ShouldFocus="false">
      <PortInfo index="0" default="False" />
      <PortInfo index="1" default="False" />
    </Dynamo.Graph.Nodes.CodeBlockNodeModel>
    <Dynamo.Graph.Nodes.CodeBlockNodeModel guid="7494d69a-2e9b-4954-8b0f-a16dcaeb3796" type="Dynamo.Graph.Nodes.CodeBlockNodeModel" nickname="Code Block" x="1350.45424497243" y="84.9863735372691" isVisible="true" isUpstreamVisible="true" lacing="Disabled" isSelectedInput="False" IsFrozen="false" isPinned="false" CodeText="100.0;" ShouldFocus="false" />
    <Dynamo.Graph.Nodes.ZeroTouch.DSFunction guid="65ff534f-9991-463e-b281-9f6a265d1f9d" type="Dynamo.Graph.Nodes.ZeroTouch.DSFunction" nickname="Curve.Offset" x="1144.12767445249" y="480.314703095768" isVisible="true" isUpstreamVisible="true" lacing="Shortest" isSelectedInput="False" IsFrozen="false" isPinned="true" assembly="ProtoGeometry.dll" function="Autodesk.DesignScript.Geometry.Curve.Offset@double">
      <PortInfo index="0" default="False" />
      <PortInfo index="1" default="True" />
    </Dynamo.Graph.Nodes.ZeroTouch.DSFunction>
    <Dynamo.Graph.Nodes.CodeBlockNodeModel guid="74f1ed97-4113-4e73-ba3d-45e61ed23102" type="Dynamo.Graph.Nodes.CodeBlockNodeModel" nickname="Code Block" x="997" y="525" isVisible="true" isUpstreamVisible="true" lacing="Disabled" isSelectedInput="False" IsFrozen="false" isPinned="false" CodeText="0;" ShouldFocus="false" />
  </Elements>
  <Connectors>
    <Dynamo.Graph.Connectors.ConnectorModel start="62d64856-a3ac-4926-9806-3fbe966003c8" start_index="0" end="d2810dfe-6143-4c89-9152-48a9c9035015" end_index="0" portType="0" />
    <Dynamo.Graph.Connectors.ConnectorModel start="84ac121e-8312-43d7-853f-926c77269688" start_index="0" end="62d64856-a3ac-4926-9806-3fbe966003c8" end_index="0" portType="0" />
    <Dynamo.Graph.Connectors.ConnectorModel start="d2810dfe-6143-4c89-9152-48a9c9035015" start_index="0" end="65ff534f-9991-463e-b281-9f6a265d1f9d" end_index="0" portType="0" />
    <Dynamo.Graph.Connectors.ConnectorModel start="7494d69a-2e9b-4954-8b0f-a16dcaeb3796" start_index="0" end="f32ca865-b8c8-42ab-80d4-2fdd840b060c" end_index="1" portType="0" />
    <Dynamo.Graph.Connectors.ConnectorModel start="65ff534f-9991-463e-b281-9f6a265d1f9d" start_index="0" end="f32ca865-b8c8-42ab-80d4-2fdd840b060c" end_index="0" portType="0" />
    <Dynamo.Graph.Connectors.ConnectorModel start="74f1ed97-4113-4e73-ba3d-45e61ed23102" start_index="0" end="65ff534f-9991-463e-b281-9f6a265d1f9d" end_index="1" portType="0" />
  </Connectors>
  <Notes />
  <Annotations />
  <Presets />
  <Cameras>
    <Camera Name="Background Preview" eyeX="6272.4833984375" eyeY="44082.7734375" eyeZ="32249.408203125" lookX="3175.46875" lookY="-46018.0625" lookZ="-29281.287109375" upX="0.0762366428971291" upY="0.70710676908493" upZ="-0.702985048294067" />
  </Cameras>
</Workspace>