<Workspace Version="1.3.0.875" X="-920.006362406316" Y="609.268811790509" zoom="0.868831880699774" ScaleFactor="1" Name="Home" Description="" RunType="Manual" RunPeriod="1000" HasRunWithoutCrash="True">
  <NamespaceResolutionMap>
    <ClassMap partialName="DSCore.List" resolvedName="DSCore.List" assemblyName="DSCoreNodes.dll" />
  </NamespaceResolutionMap>
  <Elements>
    <Dynamo.Graph.Nodes.ZeroTouch.DSFunction guid="2399b948-53fe-463a-a385-965aa4a4bb71" type="Dynamo.Graph.Nodes.ZeroTouch.DSFunction" nickname="Curve.EndPoint" x="-402.334503796541" y="-1206.48350326521" isVisible="true" isUpstreamVisible="true" lacing="Shortest" isSelectedInput="False" IsFrozen="false" isPinned="true" assembly="ProtoGeometry.dll" function="Autodesk.DesignScript.Geometry.Curve.EndPoint">
      <PortInfo index="0" default="False" />
    </Dynamo.Graph.Nodes.ZeroTouch.DSFunction>
    <PythonNodeModels.PythonNode guid="80bdc9c3-00ee-42ed-bfda-f95c2bd05555" type="PythonNodeModels.PythonNode" nickname="Python Script" x="-48.5717842999538" y="-1210.07586996548" isVisible="true" isUpstreamVisible="true" lacing="Disabled" isSelectedInput="False" IsFrozen="false" isPinned="true" inputcount="1">
      <PortInfo index="0" default="False" />
      <Script>lista = IN[0]
newLista = lista

for i in range(0,len(lista)):
	for j in range(0,len(lista[i])):
		newLista[i][j].append(lista[i][j][0])
		
#Assign your output to the OUT variable.
OUT = newLista</Script>
    </PythonNodeModels.PythonNode>
    <Dynamo.Graph.Nodes.CustomNodes.Function guid="aaf39cec-5e92-4850-b85c-db7b5ce09e47" type="Dynamo.Graph.Nodes.CustomNodes.Function" nickname="LunchBox Area Element Collector" x="-1396.07815295546" y="-1375.64768220497" isVisible="true" isUpstreamVisible="true" lacing="Shortest" isSelectedInput="False" IsFrozen="false" isPinned="true">
      <PortInfo index="0" default="False" />
      <ID value="af9e36c4-c0f5-451f-b5d2-afcf16bee759" />
      <Name value="LunchBox Area Element Collector" />
      <Description value="Collects rooms from the Revit document" />
      <Inputs>
        <Input value="Toggle" />
      </Inputs>
      <Outputs>
        <Output value="Element" />
        <Output value="Name" />
        <Output value="Number" />
        <Output value="Area" />
        <Output value="Level Name" />
        <Output value="Location" />
        <Output value="Boundaries" />
        <Output value="AreaScheme" />
        <Output value="Element ID" />
        <Output value="Unique ID" />
      </Outputs>
    </Dynamo.Graph.Nodes.CustomNodes.Function>
    <Dynamo.Graph.Nodes.CodeBlockNodeModel guid="3fb6ae81-1c68-4386-83ca-838f9cecd02f" type="Dynamo.Graph.Nodes.CodeBlockNodeModel" nickname="Code Block" x="-1562.89230773682" y="-1372.63405464995" isVisible="true" isUpstreamVisible="true" lacing="Disabled" isSelectedInput="False" IsFrozen="false" isPinned="false" CodeText="0;" ShouldFocus="false" />
    <Dynamo.Graph.Nodes.CodeBlockNodeModel guid="f6d223bf-9358-4fd8-aa7d-23b9f55e4dbb" type="Dynamo.Graph.Nodes.CodeBlockNodeModel" nickname="Code Block" x="-1016.57996314682" y="-1215.40702878037" isVisible="true" isUpstreamVisible="true" lacing="Disabled" isSelectedInput="False" IsFrozen="false" isPinned="true" CodeText="A;" ShouldFocus="false">
      <PortInfo index="0" default="False" />
    </Dynamo.Graph.Nodes.CodeBlockNodeModel>
    <Dynamo.Graph.Nodes.CustomNodes.Function guid="5ca508d6-e2cb-4fe0-9ff6-477b13e3567f" type="Dynamo.Graph.Nodes.CustomNodes.Function" nickname="GetParameterAsProjectUnits" x="-936.885220412029" y="-225.571911911741" isVisible="true" isUpstreamVisible="true" lacing="Shortest" isSelectedInput="False" IsFrozen="false" isPinned="true">
      <PortInfo index="0" default="False" />
      <PortInfo index="1" default="False" />
      <ID value="e7c15610-058b-42f7-a65a-066f1db31e1a" />
      <Name value="GetParameterAsProjectUnits" />
      <Description value="Returns the parameter value in the same unit type as the project settings" />
      <Inputs>
        <Input value="Elements" />
        <Input value="ParameterName" />
      </Inputs>
      <Outputs>
        <Output value="Values" />
      </Outputs>
    </Dynamo.Graph.Nodes.CustomNodes.Function>
    <Dynamo.Graph.Nodes.CodeBlockNodeModel guid="906efb27-e359-4053-8608-e9c44f34f38e" type="Dynamo.Graph.Nodes.CodeBlockNodeModel" nickname="Code Block" x="189.400712860687" y="-381.600501419586" isVisible="true" isUpstreamVisible="true" lacing="Disabled" isSelectedInput="False" IsFrozen="false" isPinned="true" CodeText="a*1000;" ShouldFocus="false">
      <PortInfo index="0" default="False" />
    </Dynamo.Graph.Nodes.CodeBlockNodeModel>
    <Dynamo.Graph.Nodes.ZeroTouch.DSFunction guid="a8dcb07b-ee16-4b46-b8fe-0d2f766c1db3" type="Dynamo.Graph.Nodes.ZeroTouch.DSFunction" nickname="Element.Name" x="333.947056759796" y="190.619105392745" isVisible="true" isUpstreamVisible="true" lacing="Shortest" isSelectedInput="False" IsFrozen="false" isPinned="true" assembly="RevitNodes.dll" function="Revit.Elements.Element.Name">
      <PortInfo index="0" default="False" />
    </Dynamo.Graph.Nodes.ZeroTouch.DSFunction>
    <Dynamo.Graph.Nodes.CodeBlockNodeModel guid="1901f20d-8df0-4dff-a719-f373a2226399" type="Dynamo.Graph.Nodes.CodeBlockNodeModel" nickname="Code Block" x="-1260.48834159726" y="-99.6291193189205" isVisible="true" isUpstreamVisible="true" lacing="Disabled" isSelectedInput="False" IsFrozen="false" isPinned="false" CodeText="{&quot;DL&quot;,&quot;SDL&quot;,&quot;LL&quot;};" ShouldFocus="false" />
    <CoreNodeModels.DynamoConvert guid="1e606c0b-9cbb-4a30-8dac-06d363ebb675" type="CoreNodeModels.DynamoConvert" nickname="Convert Between Units" x="-344.432506859147" y="-459.460393374355" isVisible="true" isUpstreamVisible="true" lacing="Disabled" isSelectedInput="False" IsFrozen="false" isPinned="false" conversionMetric="Length" conversionFrom="Feet" conversionTo="Meters">
      <PortInfo index="0" default="True" />
    </CoreNodeModels.DynamoConvert>
    <DSRevitNodesUI.Categories guid="aba9e559-8252-441b-98a2-33c767a3cb85" type="DSRevitNodesUI.Categories" nickname="Categories" x="1140.80396782427" y="67.6308917983201" isVisible="true" isUpstreamVisible="true" lacing="Disabled" isSelectedInput="True" IsFrozen="false" isPinned="false" index="524:LoadCases" />
    <DSRevitNodesUI.ElementsOfCategory guid="dcfc3c93-9c91-4e51-afbc-df7e36367c15" type="DSRevitNodesUI.ElementsOfCategory" nickname="All Elements of Category" x="1452.06788817835" y="60.2639703916814" isVisible="true" isUpstreamVisible="true" lacing="Disabled" isSelectedInput="False" IsFrozen="false" isPinned="true">
      <PortInfo index="0" default="False" />
    </DSRevitNodesUI.ElementsOfCategory>
    <PythonNodeModels.PythonNode guid="b21d70ae-ea62-4479-bfde-275780c2e6cd" type="PythonNodeModels.PythonNode" nickname="Assign Area Load - Python Script" x="861.893748502281" y="-539.131196903098" isVisible="true" isUpstreamVisible="true" lacing="Disabled" isSelectedInput="False" IsFrozen="false" isPinned="true" inputcount="3">
      <PortInfo index="0" default="False" />
      <PortInfo index="1" default="False" />
      <PortInfo index="2" default="False" />
      <Script>import clr
clr.AddReference('ProtoGeometry')
from Autodesk.DesignScript.Geometry import *
#Import ToDSType(bool) extension method
clr.AddReference('RevitNodes')
import Revit
clr.ImportExtensions(Revit.GeometryConversion)
#Import DocumentManager and TransactionManager
clr.AddReference('RevitServices')
import RevitServices
from RevitServices.Persistence import DocumentManager
from RevitServices.Transactions import TransactionManager
from System.Collections.Generic import *
#import RevitAPI
clr.AddReference('RevitAPI')
import Autodesk
from Autodesk.Revit.DB import *
from Autodesk.Revit.DB.Structure import *
from System.Collections.Generic import *

doc = DocumentManager.Instance.CurrentDBDocument

#The inputs to this node will be stored as a list in the IN variables.
#Host=UnwrapElement(IN[0])

pts = UnwrapElement(IN[0])
F=IN[1]
loadtype=UnwrapElement(IN[2])

TransactionManager.Instance.EnsureInTransaction(doc)

#Profile Loop Container
pl = []

if len(pts)&gt;1:
	#create filled region
	for j in range(0,len(pts[0])):
		outerProfileLoop = CurveLoop()
		pl.Add([outerProfileLoop])
		for i in range(0,len(pts[0][j])-1):
			outerProfileLoop.Append(Autodesk.Revit.DB.Line.CreateBound(XYZ(pts[0][j][i].X,pts[0][j][i].Y,pts[0][j][i].Z),XYZ(pts[0][j][i+1].X,pts[0][j][i+1].Y,pts[0][j][i+1].Z)))
else:
	for j in range(0,len(pts[0])):
		outerProfileLoop = CurveLoop()
		pl.Add([outerProfileLoop])
		for i in range(0,len(pts[0][j])-1):
			outerProfileLoop.Append(Autodesk.Revit.DB.Line.CreateBound(XYZ(pts[0][j][i].X,pts[0][j][i].Y,pts[0][j][i].Z),XYZ(pts[0][j][i+1].X,pts[0][j][i+1].Y,pts[0][j][i+1].Z)))

loads=[]
	
for j in range(0,len(loadtype)):
	listLoad = []
	loads.append(listLoad)
	for i in range(0,len(pl)):
		a= AreaLoad.Create(doc,pl[i],F[j][i].ToXyz(False),loadtype[j])	
		listLoad.append(a)
			
TransactionManager.Instance.TransactionTaskDone()

#Assign your output to the OUT variable.
OUT = loads</Script>
    </PythonNodeModels.PythonNode>
    <Dynamo.Graph.Nodes.ZeroTouch.DSFunction guid="d1b40fc9-39e0-4ce6-8ee3-4386e867f9cf" type="Dynamo.Graph.Nodes.ZeroTouch.DSFunction" nickname="Geometry.Scale" x="353.697422742557" y="-813.453761907174" isVisible="true" isUpstreamVisible="true" lacing="Shortest" isSelectedInput="False" IsFrozen="false" isPinned="true" assembly="ProtoGeometry.dll" function="Autodesk.DesignScript.Geometry.Geometry.Scale@double">
      <PortInfo index="0" default="False" />
      <PortInfo index="1" default="True" />
    </Dynamo.Graph.Nodes.ZeroTouch.DSFunction>
    <Dynamo.Graph.Nodes.CodeBlockNodeModel guid="b1d9577b-6a1d-45d0-9afa-3df07afc1c71" type="Dynamo.Graph.Nodes.CodeBlockNodeModel" nickname="Code Block" x="147.313299803521" y="-583.970150164952" isVisible="true" isUpstreamVisible="true" lacing="Disabled" isSelectedInput="False" IsFrozen="false" isPinned="false" CodeText="0.003281;" ShouldFocus="false" />
    <DSRevitNodesUI.ElementTypes guid="5cf3dbc1-2780-4e50-9c2c-3067ebe3050b" type="DSRevitNodesUI.ElementTypes" nickname="Element Types" x="-91.7383902953291" y="134.381457303679" isVisible="true" isUpstreamVisible="true" lacing="Disabled" isSelectedInput="True" IsFrozen="false" isPinned="false" index="14:AreaLoadType" />
    <DSRevitNodesUI.ElementsOfType guid="212e785f-69a4-4c1a-85a5-e8ec1ec2ebb3" type="DSRevitNodesUI.ElementsOfType" nickname="All Elements of Type" x="75.7616097046706" y="135.881457303679" isVisible="true" isUpstreamVisible="true" lacing="Disabled" isSelectedInput="False" IsFrozen="false" isPinned="true">
      <PortInfo index="0" default="False" />
    </DSRevitNodesUI.ElementsOfType>
    <Dynamo.Graph.Nodes.ZeroTouch.DSFunction guid="d6723f5d-17fc-4ddd-8636-9ea5d46f1e1a" type="Dynamo.Graph.Nodes.ZeroTouch.DSFunction" nickname="Point.ByCoordinates" x="542.416891999082" y="-432.732302742134" isVisible="true" isUpstreamVisible="true" lacing="Shortest" isSelectedInput="False" IsFrozen="false" isPinned="true" assembly="ProtoGeometry.dll" function="Autodesk.DesignScript.Geometry.Point.ByCoordinates@double,double,double">
      <PortInfo index="0" default="True" />
      <PortInfo index="1" default="True" />
      <PortInfo index="2" default="True" />
    </Dynamo.Graph.Nodes.ZeroTouch.DSFunction>
    <Dynamo.Graph.Nodes.ZeroTouch.DSFunction guid="348b0729-0ab1-445f-906d-7f3756532b1f" type="Dynamo.Graph.Nodes.ZeroTouch.DSFunction" nickname="Element.SetParameterByName" x="2002.63672098242" y="-73.1058860853025" isVisible="true" isUpstreamVisible="true" lacing="Shortest" isSelectedInput="False" IsFrozen="false" isPinned="true" assembly="RevitNodes.dll" function="Revit.Elements.Element.SetParameterByName@string,var">
      <PortInfo index="0" default="False" />
      <PortInfo index="1" default="False" />
      <PortInfo index="2" default="False" />
    </Dynamo.Graph.Nodes.ZeroTouch.DSFunction>
    <Dynamo.Graph.Nodes.ZeroTouch.DSFunction guid="ab0ffd34-5a5c-4920-89a8-4c6d05911587" type="Dynamo.Graph.Nodes.ZeroTouch.DSFunction" nickname="Element.SetParameterByName" x="1996.85472786335" y="-605.043576594562" isVisible="true" isUpstreamVisible="true" lacing="Shortest" isSelectedInput="False" IsFrozen="false" isPinned="true" assembly="RevitNodes.dll" function="Revit.Elements.Element.SetParameterByName@string,var">
      <PortInfo index="0" default="False" />
      <PortInfo index="1" default="False" />
      <PortInfo index="2" default="False" />
    </Dynamo.Graph.Nodes.ZeroTouch.DSFunction>
    <Dynamo.Graph.Nodes.CodeBlockNodeModel guid="0cedf692-65fc-415f-af4f-931000eb1f84" type="Dynamo.Graph.Nodes.CodeBlockNodeModel" nickname="Code Block" x="1716.51266514392" y="-37.1429504333843" isVisible="true" isUpstreamVisible="true" lacing="Disabled" isSelectedInput="False" IsFrozen="false" isPinned="false" CodeText="&quot;Load Case&quot;;" ShouldFocus="false" />
    <Dynamo.Graph.Nodes.CodeBlockNodeModel guid="97b8343e-316f-48fa-9303-c14064da4495" type="Dynamo.Graph.Nodes.CodeBlockNodeModel" nickname="Code Block" x="1788.88566881538" y="-622.558534346855" isVisible="true" isUpstreamVisible="true" lacing="Disabled" isSelectedInput="False" IsFrozen="false" isPinned="false" CodeText="&quot;Description&quot;;" ShouldFocus="false" />
    <Dynamo.Graph.Nodes.ZeroTouch.DSFunction guid="f983e5f8-62a9-4e67-8a5a-075b40f96c78" type="Dynamo.Graph.Nodes.ZeroTouch.DSFunction" nickname="List.Transpose" x="1742.23534904984" y="-714.20274198452" isVisible="true" isUpstreamVisible="true" lacing="Shortest" isSelectedInput="False" IsFrozen="false" isPinned="false" assembly="DSCoreNodes.dll" function="DSCore.List.Transpose@var[]..[]">
      <PortInfo index="0" default="False" />
    </Dynamo.Graph.Nodes.ZeroTouch.DSFunction>
    <Dynamo.Graph.Nodes.CodeBlockNodeModel guid="94058e18-802c-4373-b9fc-ba3b0ad29f44" type="Dynamo.Graph.Nodes.CodeBlockNodeModel" nickname="Code Block" x="1716.60955921147" y="65.5733415318334" isVisible="true" isUpstreamVisible="true" lacing="Disabled" isSelectedInput="False" IsFrozen="false" isPinned="false" CodeText="{a[0], a[5], a[1]};" ShouldFocus="false">
      <PortInfo index="0" default="False" />
    </Dynamo.Graph.Nodes.CodeBlockNodeModel>
    <Dynamo.Graph.Nodes.ZeroTouch.DSFunction guid="c166a411-04ef-493a-be1a-57e1c9eb0cda" type="Dynamo.Graph.Nodes.ZeroTouch.DSFunction" nickname="Element.Name" x="1719.47102850679" y="199.32483694901" isVisible="true" isUpstreamVisible="true" lacing="Shortest" isSelectedInput="False" IsFrozen="false" isPinned="true" assembly="RevitNodes.dll" function="Revit.Elements.Element.Name">
      <PortInfo index="0" default="False" />
    </Dynamo.Graph.Nodes.ZeroTouch.DSFunction>
    <Dynamo.Graph.Nodes.CustomNodes.Function guid="62452231-6668-443f-8317-542f5ab400a7" type="Dynamo.Graph.Nodes.CustomNodes.Function" nickname="AreaSeparator.FromCurve" x="625.443120089804" y="-2311.20749108139" isVisible="true" isUpstreamVisible="true" lacing="Shortest" isSelectedInput="False" IsFrozen="false" isPinned="true">
      <PortInfo index="0" default="False" />
      <PortInfo index="1" default="False" />
      <PortInfo index="2" default="False" />
      <ID value="fdc98eeb-e9be-4c20-b9ae-1fa686636067" />
      <Name value="AreaSeparator.FromCurve" />
      <Description value="Creates area separation lines from geometry curves. " />
      <Inputs>
        <Input value="curve" />
        <Input value="sketchPlane" />
        <Input value="areaPlanView" />
      </Inputs>
      <Outputs>
        <Output value="areaSeparator" />
      </Outputs>
    </Dynamo.Graph.Nodes.CustomNodes.Function>
    <DSRevitNodesUI.Categories guid="a973a276-0850-4c75-a061-8212dc0ababe" type="DSRevitNodesUI.Categories" nickname="Categories" x="-2085.42536845378" y="-2689.00491062008" isVisible="true" isUpstreamVisible="true" lacing="Disabled" isSelectedInput="True" IsFrozen="false" isPinned="true" index="403:Rooms" />
    <Dynamo.Graph.Nodes.CustomNodes.Function guid="174374a2-8dee-4daf-88f7-72ff9134072b" type="Dynamo.Graph.Nodes.CustomNodes.Function" nickname="Get All Elements From Linked Model" x="-1782.49549513858" y="-2796.5944172244" isVisible="true" isUpstreamVisible="true" lacing="Shortest" isSelectedInput="False" IsFrozen="false" isPinned="true">
      <PortInfo index="0" default="False" />
      <PortInfo index="1" default="False" />
      <ID value="ce86e653-fcd4-4809-b0c0-584a1d34e006" />
      <Name value="Get All Elements From Linked Model" />
      <Description value="This node is based on code posted by Julien Benoit. Big thanks to Julien for sharing his work. This node will retrieve all elements of a given category from a given linked model. " />
      <Inputs>
        <Input value="LinkDoc" />
        <Input value="Category" />
      </Inputs>
      <Outputs>
        <Output value="Elements" />
      </Outputs>
    </Dynamo.Graph.Nodes.CustomNodes.Function>
    <Dynamo.Graph.Nodes.CustomNodes.Function guid="7931003d-382d-4210-87a2-bf341858409a" type="Dynamo.Graph.Nodes.CustomNodes.Function" nickname="Get Loaded RVT Links" x="-2434.66204560346" y="-2907.73632173714" isVisible="true" isUpstreamVisible="true" lacing="Shortest" isSelectedInput="True" IsFrozen="false" isPinned="true">
      <ID value="8e3c2714-7168-4346-bbf0-aff16a267efe" />
      <Name value="Get Loaded RVT Links" />
      <Description value="" />
      <Inputs />
      <Outputs>
        <Output value="loaded Link Names" />
        <Output value="loaded Link Docs" />
        <Output value="cleaned Loaded names only" />
        <Output value="cleaned and sorted" />
      </Outputs>
    </Dynamo.Graph.Nodes.CustomNodes.Function>
    <Dynamo.Graph.Nodes.CodeBlockNodeModel guid="8f7a1041-89b2-438d-b65e-9e99657c9905" type="Dynamo.Graph.Nodes.CodeBlockNodeModel" nickname="Code Block" x="-1875.98693765608" y="-2914.02201965631" isVisible="true" isUpstreamVisible="true" lacing="Disabled" isSelectedInput="False" IsFrozen="false" isPinned="false" CodeText="A[0];" ShouldFocus="false">
      <PortInfo index="0" default="False" />
    </Dynamo.Graph.Nodes.CodeBlockNodeModel>
    <Dynamo.Graph.Nodes.ZeroTouch.DSFunction guid="39473050-3053-466f-a991-44b9e073f24a" type="Dynamo.Graph.Nodes.ZeroTouch.DSFunction" nickname="List.GetItemAtIndex" x="-191.647019307046" y="-2728.48884492154" isVisible="false" isUpstreamVisible="true" lacing="Longest" isSelectedInput="False" IsFrozen="false" isPinned="true" assembly="DSCoreNodes.dll" function="DSCore.List.GetItemAtIndex@var[]..[],int">
      <PortInfo index="0" default="False" />
      <PortInfo index="1" default="False" />
    </Dynamo.Graph.Nodes.ZeroTouch.DSFunction>
    <Dynamo.Graph.Nodes.CodeBlockNodeModel guid="c7a05bf0-9072-4b34-86ce-da1ce4d37db3" type="Dynamo.Graph.Nodes.CodeBlockNodeModel" nickname="Code Block" x="-393.622296350646" y="-2652.82784924037" isVisible="true" isUpstreamVisible="true" lacing="Disabled" isSelectedInput="False" IsFrozen="false" isPinned="false" CodeText="0;" ShouldFocus="false" />
    <Dynamo.Graph.Nodes.CustomNodes.Function guid="be7b5428-0052-4569-9be2-042944981f7c" type="Dynamo.Graph.Nodes.CustomNodes.Function" nickname="Group Curves" x="162.422984646504" y="-2778.68737281305" isVisible="true" isUpstreamVisible="true" lacing="Longest" isSelectedInput="False" IsFrozen="false" isPinned="true">
      <PortInfo index="0" default="False" />
      <ID value="c84855d4-eb7e-4574-86a5-04867486df63" />
      <Name value="Group Curves" />
      <Description value="This node will take any input of flat list of curves and group them into sublists containing &quot;joinable&quot; curves that is continous curves. They might form closed curves or open curves. Use PolyCurve.ByJoinedCurves to convert output groups of curves into single PolyCurves" />
      <Inputs>
        <Input value="Curves" />
      </Inputs>
      <Outputs>
        <Output value="Grouped Curves" />
      </Outputs>
    </Dynamo.Graph.Nodes.CustomNodes.Function>
    <Dynamo.Graph.Nodes.ZeroTouch.DSFunction guid="713e9981-c4b6-4c12-913b-21f512969251" type="Dynamo.Graph.Nodes.ZeroTouch.DSFunction" nickname="Room.CenterBoundary" x="-759.359683875655" y="-2708.76015657436" isVisible="false" isUpstreamVisible="true" lacing="Shortest" isSelectedInput="False" IsFrozen="false" isPinned="true" assembly="RevitNodes.dll" function="Revit.Elements.Room.CenterBoundary">
      <PortInfo index="0" default="False" />
    </Dynamo.Graph.Nodes.ZeroTouch.DSFunction>
    <DSRevitNodesUI.Levels guid="8b2f1d01-1a44-4509-9ce7-562c484c1778" type="DSRevitNodesUI.Levels" nickname="Levels" x="-92.2603456325096" y="-2266.36668469156" isVisible="true" isUpstreamVisible="true" lacing="Disabled" isSelectedInput="True" IsFrozen="false" isPinned="false" index="0:ROOM PLAN - LEVEL 00" />
    <Dynamo.Graph.Nodes.ZeroTouch.DSFunction guid="c04bdbd4-4be9-47ab-b584-796550bfba85" type="Dynamo.Graph.Nodes.ZeroTouch.DSFunction" nickname="SketchPlane.ByPlane" x="326.775805256029" y="-2289.63491553342" isVisible="true" isUpstreamVisible="true" lacing="Shortest" isSelectedInput="False" IsFrozen="false" isPinned="false" assembly="RevitNodes.dll" function="Revit.Elements.SketchPlane.ByPlane@Autodesk.DesignScript.Geometry.Plane">
      <PortInfo index="0" default="False" />
    </Dynamo.Graph.Nodes.ZeroTouch.DSFunction>
    <Dynamo.Graph.Nodes.CustomNodes.Function guid="5c394160-4c2c-4efe-bdba-4bcdfa9afeeb" type="Dynamo.Graph.Nodes.CustomNodes.Function" nickname="Level.Plane" x="134.213465738314" y="-2270.82650097588" isVisible="true" isUpstreamVisible="true" lacing="Shortest" isSelectedInput="False" IsFrozen="false" isPinned="false">
      <PortInfo index="0" default="False" />
      <ID value="cbe6db5e-3248-46ff-87e4-b620a1abf252" />
      <Name value="Level.Plane" />
      <Description value="Retrieves the plane of a given level" />
      <Inputs>
        <Input value="level" />
      </Inputs>
      <Outputs>
        <Output value="plane" />
      </Outputs>
    </Dynamo.Graph.Nodes.CustomNodes.Function>
    <Dynamo.Graph.Nodes.CustomNodes.Function guid="f56d03c3-bee8-43a9-b237-b21f0c144835" type="Dynamo.Graph.Nodes.CustomNodes.Function" nickname="Get Revit ActiveView" x="397.531269543933" y="-2154.39345847679" isVisible="true" isUpstreamVisible="true" lacing="Shortest" isSelectedInput="True" IsFrozen="false" isPinned="true">
      <ID value="92960965-5bfc-41ab-9ceb-d61917dfe6c5" />
      <Name value="Get Revit ActiveView" />
      <Description value="Active View" />
      <Inputs />
      <Outputs>
        <Output value="Active.View" />
      </Outputs>
    </Dynamo.Graph.Nodes.CustomNodes.Function>
    <Dynamo.Graph.Nodes.ZeroTouch.DSFunction guid="b90b4cec-8e3f-484e-ba22-d6c7123c26a0" type="Dynamo.Graph.Nodes.ZeroTouch.DSFunction" nickname="Element.GetParameterValueByName" x="-1287.77039648773" y="-3024.36843379937" isVisible="true" isUpstreamVisible="true" lacing="Shortest" isSelectedInput="False" IsFrozen="false" isPinned="false" assembly="RevitNodes.dll" function="Revit.Elements.Element.GetParameterValueByName@string">
      <PortInfo index="0" default="False" />
      <PortInfo index="1" default="False" />
    </Dynamo.Graph.Nodes.ZeroTouch.DSFunction>
    <Dynamo.Graph.Nodes.CodeBlockNodeModel guid="2c51bd16-3db8-483a-9eab-1e8291c3159e" type="Dynamo.Graph.Nodes.CodeBlockNodeModel" nickname="Code Block" x="-1538.95450592568" y="-2996.25213786153" isVisible="true" isUpstreamVisible="true" lacing="Disabled" isSelectedInput="False" IsFrozen="false" isPinned="false" CodeText="&quot;Level&quot;;" ShouldFocus="false" />
    <Dynamo.Graph.Nodes.ZeroTouch.DSFunction guid="fd355568-0f27-41ef-a6dc-3a9539160854" type="Dynamo.Graph.Nodes.ZeroTouch.DSFunction" nickname="String.Contains" x="-1168.58427717097" y="-2835.6046340682" isVisible="true" isUpstreamVisible="true" lacing="Shortest" isSelectedInput="False" IsFrozen="false" isPinned="false" assembly="DSCoreNodes.dll" function="DSCore.String.Contains@string,string,bool">
      <PortInfo index="0" default="False" />
      <PortInfo index="1" default="False" />
      <PortInfo index="2" default="True" />
    </Dynamo.Graph.Nodes.ZeroTouch.DSFunction>
    <Dynamo.Graph.Nodes.CodeBlockNodeModel guid="54cad408-c11f-46b1-9ef1-da5220851c5a" type="Dynamo.Graph.Nodes.CodeBlockNodeModel" nickname="Code Block" x="-1356.23120847176" y="-2780.07326273535" isVisible="true" isUpstreamVisible="true" lacing="Disabled" isSelectedInput="False" IsFrozen="false" isPinned="false" CodeText="&quot;01&quot;;" ShouldFocus="false" />
    <Dynamo.Graph.Nodes.ZeroTouch.DSFunction guid="310929fb-c1fd-4552-85bc-8f8092ef8df0" type="Dynamo.Graph.Nodes.ZeroTouch.DSFunction" nickname="List.FilterByBoolMask" x="-957.178621587101" y="-2631.36220101006" isVisible="true" isUpstreamVisible="true" lacing="Shortest" isSelectedInput="False" IsFrozen="false" isPinned="false" assembly="DSCoreNodes.dll" function="DSCore.List.FilterByBoolMask@var[]..[],var[]..[]">
      <PortInfo index="0" default="False" />
      <PortInfo index="1" default="False" />
    </Dynamo.Graph.Nodes.ZeroTouch.DSFunction>
    <Dynamo.Nodes.DSModelElementSelection guid="cdfa44a2-1988-4cc5-8754-b3313c0f690c" type="Dynamo.Nodes.DSModelElementSelection" nickname="Select Model Element" x="-1555.94523024644" y="-648.590398759802" isVisible="true" isUpstreamVisible="true" lacing="Disabled" isSelectedInput="True" IsFrozen="false" isPinned="false">
      <instance id="fdc24f85-5bf9-405b-9054-86a455717808-002047a6" />
    </Dynamo.Nodes.DSModelElementSelection>
    <PythonNodeModels.PythonNode guid="5bc852fa-fd73-4853-abed-a12e6607598a" type="PythonNodeModels.PythonNode" nickname="Python Script" x="-972.284131265016" y="-626.991032922903" isVisible="true" isUpstreamVisible="true" lacing="Disabled" isSelectedInput="False" IsFrozen="false" isPinned="true" inputcount="1">
      <PortInfo index="0" default="False" />
      <Script>#Copyright(c) 2014, Nathan Miller
# The Proving Ground, http://theprovingground.org

import clr

# Import RevitAPI
clr.AddReference("RevitAPI")
import Autodesk
from Autodesk.Revit.DB import *

# Import DocumentManager and TransactionManager
clr.AddReference("RevitServices")
import RevitServices
from RevitServices.Persistence import DocumentManager
from RevitServices.Transactions import TransactionManager

# Import ToDSType(bool) extension method
clr.AddReference("RevitNodes")
import Revit
clr.ImportExtensions(Revit.Elements)
clr.ImportExtensions(Revit.GeometryConversion)

import clr
clr.AddReference('ProtoGeometry')
from Autodesk.DesignScript.Geometry import *

#The input to this node will be stored in the IN[0] variable.

doc =  DocumentManager.Instance.CurrentDBDocument
app =  DocumentManager.Instance.CurrentUIApplication.Application

room = UnwrapElement(IN[0])

boundaries = []


boptions = Autodesk.Revit.DB.SpatialElementBoundaryOptions()
boundsegs = room.GetBoundarySegments(boptions)
boundcurves = []


for bound in boundsegs:
	crvs = []
	boundcurves.append(crvs)
	for seg in bound:
		crv = seg.GetCurve()
		crvs.append(Revit.GeometryConversion.RevitToProtoCurve.ToProtoType( crv, True ))
  	
        
#Assign your output to the OUT variable
OUT = boundcurves</Script>
    </PythonNodeModels.PythonNode>
    <Dynamo.Graph.Nodes.CodeBlockNodeModel guid="8c46bffc-e79b-4afb-bca5-6383f9a59e7c" type="Dynamo.Graph.Nodes.CodeBlockNodeModel" nickname="Code Block" x="241" y="-886" isVisible="true" isUpstreamVisible="true" lacing="Disabled" isSelectedInput="False" IsFrozen="false" isPinned="false" CodeText="a;" ShouldFocus="false">
      <PortInfo index="0" default="False" />
    </Dynamo.Graph.Nodes.CodeBlockNodeModel>
    <CoreNodeModels.Input.BoolSelector guid="56fecdde-c972-4e5a-b373-8b439e704ed4" type="CoreNodeModels.Input.BoolSelector" nickname="Boolean" x="-1594.01905877473" y="-1260.48284851003" isVisible="true" isUpstreamVisible="true" lacing="Disabled" isSelectedInput="True" IsFrozen="false" isPinned="false">
      <System.Boolean>True</System.Boolean>
    </CoreNodeModels.Input.BoolSelector>
    <Dynamo.Graph.Nodes.CodeBlockNodeModel guid="e0cf734e-ba29-4f0f-8daa-b80f708adf12" type="Dynamo.Graph.Nodes.CodeBlockNodeModel" nickname="Code Block" x="-1329.69833853594" y="-740.83317351239" isVisible="true" isUpstreamVisible="true" lacing="Disabled" isSelectedInput="False" IsFrozen="false" isPinned="false" CodeText="{a};" ShouldFocus="false">
      <PortInfo index="0" default="False" />
    </Dynamo.Graph.Nodes.CodeBlockNodeModel>
    <PythonNodeModels.PythonNode guid="2396e693-cc19-489b-b51b-f81bf013e00a" type="PythonNodeModels.PythonNode" nickname="Python Script" x="-734.209989892252" y="-512.461518320314" isVisible="true" isUpstreamVisible="true" lacing="Disabled" isSelectedInput="False" IsFrozen="false" isPinned="false" inputcount="1">
      <PortInfo index="0" default="False" />
      <Script>#Copyright(c) 2014, Nathan Miller
# The Proving Ground, http://theprovingground.org

import clr

# Import RevitAPI
clr.AddReference("RevitAPI")
import Autodesk
from Autodesk.Revit.DB import *

# Import DocumentManager and TransactionManager
clr.AddReference("RevitServices")
import RevitServices
from RevitServices.Persistence import DocumentManager
from RevitServices.Transactions import TransactionManager

# Import ToDSType(bool) extension method
clr.AddReference("RevitNodes")
import Revit
clr.ImportExtensions(Revit.Elements)
clr.ImportExtensions(Revit.GeometryConversion)

import clr
clr.AddReference('ProtoGeometry')
from Autodesk.DesignScript.Geometry import *

#The input to this node will be stored in the IN[0] variable.

doc =  DocumentManager.Instance.CurrentDBDocument
app =  DocumentManager.Instance.CurrentUIApplication.Application

toggle = IN[0]

output = []
rooms = []
names = []
numbers = []
areas = []
levels = []
boundaries = []
locations = []
areaschemes = []
elementids = []
uniqueids = []

if toggle == True:

	collector = FilteredElementCollector(doc)
	collector.OfCategory(BuiltInCategory.OST_Areas)
 
	famtypeitr = collector.GetElementIdIterator()
	famtypeitr.Reset()


	for item in famtypeitr:
		famtypeID = item
		faminst = doc.GetElement(famtypeID)
    
		#print faminst
		if faminst.Area &gt; 0:
			room = faminst
			for p in room.Parameters:
				if p.Definition.Name == 'Name':		
					roomname = p.AsString()
				if p.Definition.Name == 'Level':			
					level = p.AsValueString()
					if (level is None):
						level = p.AsString()

			number = faminst.Number
			area = faminst.Area
			location = faminst.Location.Point.ToPoint()
			areascheme = faminst.AreaScheme.Name
			elementid = faminst.Id.ToString()
			uniqueid = faminst.UniqueId
    	
			boptions = Autodesk.Revit.DB.SpatialElementBoundaryOptions()
			boundsegs = room.GetBoundarySegments(boptions)
			boundcurves = []
			for bound in boundsegs:
				crvs = []
				for seg in bound:
					crv = seg.GetCurve()
					crvs.append(Revit.GeometryConversion.RevitToProtoCurve.ToProtoType( crv, True ))
				boundcurves.append(crvs)
    	
			rooms.append(room)
			names.append(roomname)
			numbers.append(number)
			areas.append(area)
			levels.append(level)
			boundaries.append(boundcurves)
			areaschemes.append(areascheme)
			locations.append(location)
			elementids.append(elementid)
			uniqueids.append(uniqueid)
        
	output.append(rooms)
	output.append(names)
	output.append(numbers)
	output.append(areas)
	output.append(levels)
	output.append(locations)
	output.append(boundaries)
	output.append(areaschemes)
	output.append(elementids)
	output.append(uniqueids)
        
#Assign your output to the OUT variable
OUT = output</Script>
    </PythonNodeModels.PythonNode>
    <PythonNodeModels.PythonNode guid="ba9478c3-13c2-409e-8de3-6cbebb8b17ac" type="PythonNodeModels.PythonNode" nickname="Python Script" x="-947.012219857353" y="-756.347301811802" isVisible="true" isUpstreamVisible="true" lacing="Disabled" isSelectedInput="False" IsFrozen="false" isPinned="true" inputcount="2">
      <PortInfo index="0" default="False" />
      <PortInfo index="1" default="False" />
      <Script>#Copyright(c) 2014, Nathan Miller
# The Proving Ground, http://theprovingground.org

import clr

# Import RevitAPI
clr.AddReference("RevitAPI")
import Autodesk
from Autodesk.Revit.DB import *

# Import DocumentManager and TransactionManager
clr.AddReference("RevitServices")
import RevitServices
from RevitServices.Persistence import DocumentManager
from RevitServices.Transactions import TransactionManager

# Import ToDSType(bool) extension method
clr.AddReference("RevitNodes")
import Revit
clr.ImportExtensions(Revit.Elements)
clr.ImportExtensions(Revit.GeometryConversion)

import clr
clr.AddReference('ProtoGeometry')
from Autodesk.DesignScript.Geometry import *

#The input to this node will be stored in the IN[0] variable.

doc =  DocumentManager.Instance.CurrentDBDocument
app =  DocumentManager.Instance.CurrentUIApplication.Application

toggle = IN[0]

output = []
rooms = []
names = []
numbers = []
areas = []
levels = []
boundaries = []
locations = []
areaschemes = []
elementids = []
uniqueids = []

if toggle == True:

	collector = FilteredElementCollector(doc)
	collector.OfCategory(BuiltInCategory.OST_Areas)
 
	#famtypeitr = collector.GetElementIdIterator()
	#famtypeitr.Reset()
	famtypeitr = UnwrapElement(IN[1])

	for item in famtypeitr:
		#famtypeID = item
		#faminst = doc.GetElement(famtypeID)
		faminst = item
    
		#print faminst
		if faminst.Area &gt; 0:
			room = faminst
			for p in room.Parameters:
				if p.Definition.Name == 'Name':		
					roomname = p.AsString()
				if p.Definition.Name == 'Level':			
					level = p.AsValueString()
					if (level is None):
						level = p.AsString()

			number = faminst.Number
			area = faminst.Area
			location = faminst.Location.Point.ToPoint()
			areascheme = faminst.AreaScheme.Name
			elementid = faminst.Id.ToString()
			uniqueid = faminst.UniqueId
    	
			boptions = Autodesk.Revit.DB.SpatialElementBoundaryOptions()
			boundsegs = room.GetBoundarySegments(boptions)
			boundcurves = []
			for bound in boundsegs:
				crvs = []
				for seg in bound:
					crv = seg.GetCurve()
					crvs.append(Revit.GeometryConversion.RevitToProtoCurve.ToProtoType( crv, True ))
				boundcurves.append(crvs)
    	
			rooms.append(room)
			names.append(roomname)
			numbers.append(number)
			areas.append(area)
			levels.append(level)
			boundaries.append(boundcurves)
			areaschemes.append(areascheme)
			locations.append(location)
			elementids.append(elementid)
			uniqueids.append(uniqueid)
        
	#output.append(rooms)
	output.append(names)
	#output.append(numbers)
	#output.append(areas)
	#output.append(levels)
	#output.append(locations)
	output.append(boundaries)
	#output.append(areaschemes)
	#output.append(elementids)
	#output.append(uniqueids)
        
#Assign your output to the OUT variable
OUT = output</Script>
    </PythonNodeModels.PythonNode>
    <Dynamo.Graph.Nodes.CodeBlockNodeModel guid="5ea96270-d221-45b5-b22c-07db07577f66" type="Dynamo.Graph.Nodes.CodeBlockNodeModel" nickname="Code Block" x="-587.825686079163" y="-749.900132283192" isVisible="true" isUpstreamVisible="true" lacing="Disabled" isSelectedInput="False" IsFrozen="false" isPinned="true" CodeText="a[1];" ShouldFocus="false">
      <PortInfo index="0" default="False" />
    </Dynamo.Graph.Nodes.CodeBlockNodeModel>
    <PythonNodeModels.PythonNode guid="92892510-8667-451c-af25-e50d4cdbb919" type="PythonNodeModels.PythonNode" nickname="Python Script" x="733.209763447515" y="-1091.13521884071" isVisible="true" isUpstreamVisible="true" lacing="Disabled" isSelectedInput="False" IsFrozen="false" isPinned="false" inputcount="1">
      <PortInfo index="0" default="False" />
      <Script>import clr
clr.AddReference('ProtoGeometry')
from Autodesk.DesignScript.Geometry import *
#The inputs to this node will be stored as a list in the IN variables.

lista = IN[0]

oP = []
iP = []

for i in range(0,len(lista)):
		if len(lista[i])&gt;1:
			oP.append(lista[i][0])
			for j in range(1,len(lista[i])):
				iP.append(lista[i][j])
		else:
			oP.append(lista[i][0])


#Assign your output to the OUT variable.
OUT = oP,iP</Script>
    </PythonNodeModels.PythonNode>
    <Dynamo.Graph.Nodes.CodeBlockNodeModel guid="43bbaf7d-2595-4698-bbdc-476a95593a5a" type="Dynamo.Graph.Nodes.CodeBlockNodeModel" nickname="Code Block" x="1075.3902304985" y="-1276.4641874488" isVisible="true" isUpstreamVisible="true" lacing="Disabled" isSelectedInput="False" IsFrozen="false" isPinned="true" CodeText="a[0];" ShouldFocus="false">
      <PortInfo index="0" default="False" />
    </Dynamo.Graph.Nodes.CodeBlockNodeModel>
    <Dynamo.Graph.Nodes.CodeBlockNodeModel guid="774b1f1b-f577-4ac7-8309-595142ab2037" type="Dynamo.Graph.Nodes.CodeBlockNodeModel" nickname="Code Block" x="-448.418587946808" y="-246.452982084644" isVisible="true" isUpstreamVisible="true" lacing="Disabled" isSelectedInput="False" IsFrozen="false" isPinned="false" CodeText="{-1,-2,-3};" ShouldFocus="false" />
    <Dynamo.Graph.Nodes.CodeBlockNodeModel guid="33af07d1-9e68-4e5c-a7ea-6dc1e1dd41bb" type="Dynamo.Graph.Nodes.CodeBlockNodeModel" nickname="Code Block" x="1185.9999465149" y="-675.101379014551" isVisible="true" isUpstreamVisible="true" lacing="Disabled" isSelectedInput="False" IsFrozen="false" isPinned="true" CodeText="a[0];" ShouldFocus="false">
      <PortInfo index="0" default="False" />
    </Dynamo.Graph.Nodes.CodeBlockNodeModel>
    <PythonNodeModels.PythonNode guid="b76e5f77-d11c-46ca-9c56-32de24c1d35a" type="PythonNodeModels.PythonNode" nickname="Python Script" x="1311.49926270923" y="-1202.94835735139" isVisible="true" isUpstreamVisible="true" lacing="Disabled" isSelectedInput="False" IsFrozen="false" isPinned="true" inputcount="1">
      <PortInfo index="0" default="False" />
      <Script>import clr
clr.AddReference('ProtoGeometry')
from Autodesk.DesignScript.Geometry import *
#The inputs to this node will be stored as a list in the IN variables.
dataEnteringNode = IN

pts = UnwrapElement(IN[0])

#Assign your output to the OUT variable.
OUT = len(pts)</Script>
    </PythonNodeModels.PythonNode>
    <Dynamo.Nodes.DSModelElementsSelection guid="c5091233-78a1-4715-98cd-b8908445bf03" type="Dynamo.Nodes.DSModelElementsSelection" nickname="Select Model Elements" x="-1562.13536961991" y="-803.559569097654" isVisible="true" isUpstreamVisible="true" lacing="Disabled" isSelectedInput="True" IsFrozen="false" isPinned="false">
      <instance id="fdc24f85-5bf9-405b-9054-86a455717808-002045b1" />
      <instance id="fdc24f85-5bf9-405b-9054-86a455717808-002047a6" />
      <instance id="fdc24f85-5bf9-405b-9054-86a455717808-00205872" />
    </Dynamo.Nodes.DSModelElementsSelection>
    <PythonNodeModels.PythonNode guid="091f35f1-aee4-465b-b21a-b2547346f50e" type="PythonNodeModels.PythonNode" nickname="Python Script" x="2325.50481832618" y="-355.115174530907" isVisible="true" isUpstreamVisible="true" lacing="Disabled" isSelectedInput="False" IsFrozen="false" isPinned="true" inputcount="3">
      <PortInfo index="0" default="False" />
      <PortInfo index="1" default="False" />
      <PortInfo index="2" default="False" />
      <Script>import clr
clr.AddReference('ProtoGeometry')
from Autodesk.DesignScript.Geometry import *
#Import ToDSType(bool) extension method
clr.AddReference('RevitNodes')
import Revit
clr.ImportExtensions(Revit.GeometryConversion)
#Import DocumentManager and TransactionManager
clr.AddReference('RevitServices')
import RevitServices
from RevitServices.Persistence import DocumentManager
from RevitServices.Transactions import TransactionManager
from System.Collections.Generic import *
#import RevitAPI
clr.AddReference('RevitAPI')
import Autodesk
from Autodesk.Revit.DB import *
from Autodesk.Revit.DB.Structure import *
from System.Collections.Generic import *


doc = DocumentManager.Instance.CurrentDBDocument
uiapp = DocumentManager.Instance.CurrentUIApplication
app = uiapp.Application

"""
lista = IN[0]

profileLoops = []
pl = []

pl.Add(profileLoops)

for l in lista:
	if len(l)&gt;1:
		oP = l[0]
		iP = l[1:]
		outerProfileLoop = CurveLoop()
		ip = []
		loops = [outerProfileLoop,ip]
		profileLoops.Add(loops)
		for i in range(0,len(oP)-1):
			outerProfileLoop.Append(Autodesk.Revit.DB.Line.CreateBound(XYZ(oP[i].X,oP[i].Y,oP[i].Z),XYZ(oP[i+1].X,oP[i+1].Y,oP[i+1].Z)))
		for j in range(0,len(iP)):
			innerProfileLoop = CurveLoop()
			ip.append(innerProfileLoop)
			for i in range(0,len(iP[j])-1):
				innerProfileLoop.Append(Autodesk.Revit.DB.Line.CreateBound(XYZ(iP[j][i].X,iP[j][i].Y,iP[j][i].Z),XYZ(iP[j][i+1].X,iP[j][i+1].Y,iP[j][i+1].Z)))
				
	else:
		oP = l[0]
		outerProfileLoop = CurveLoop()
		profileLoops.Add(outerProfileLoop)
		for i in range(0,len(oP)-1):
			outerProfileLoop.Append(Autodesk.Revit.DB.Line.CreateBound(XYZ(oP[i].X,oP[i].Y,oP[i].Z),XYZ(oP[i+1].X,oP[i+1].Y,oP[i+1].Z)))
"""	
profileLoops = UnwrapElement(IN[0])
F=IN[1]
loadtype=UnwrapElement(IN[2])


TransactionManager.Instance.EnsureInTransaction(doc)

loads=[]


for j in range(0,len(loadtype)):
	listLoad = []
	loads.append(listLoad)
	for i in range(0,len(profileLoops)):
		a= AreaLoad.Create(doc,profileLoops[i],F[j][i].ToXyz(False),loadtype[j])	
		listLoad.append(a)


TransactionManager.Instance.TransactionTaskDone()

#Assign your outputs to the OUT variable
OUT = profileLoops
</Script>
    </PythonNodeModels.PythonNode>
    <Dynamo.Graph.Nodes.CodeBlockNodeModel guid="1535183b-08b6-4415-8c22-83a7bf605ce8" type="Dynamo.Graph.Nodes.CodeBlockNodeModel" nickname="Code Block" x="1045" y="-893" isVisible="true" isUpstreamVisible="true" lacing="Disabled" isSelectedInput="False" IsFrozen="false" isPinned="false" CodeText="&quot;a&quot;;" ShouldFocus="false" />
    <PythonNodeModels.PythonNode guid="386ac324-31ae-49e7-b622-02242dc33971" type="PythonNodeModels.PythonNode" nickname="Python Script" x="554.537907373984" y="-1149.9011085869" isVisible="true" isUpstreamVisible="true" lacing="Disabled" isSelectedInput="False" IsFrozen="false" isPinned="true" inputcount="1">
      <PortInfo index="0" default="False" />
      <Script>import clr
clr.AddReference('ProtoGeometry')
from Autodesk.DesignScript.Geometry import *
#The inputs to this node will be stored as a list in the IN variables.

lista = IN[0]
ot = []
nl = []
for l in lista:
	if len(l)&gt;1:
		ot.append("vero")
	else:
		ot.append("falso")
#Assign your output to the OUT variable.
OUT = ot,nl</Script>
    </PythonNodeModels.PythonNode>
    <Dynamo.Graph.Nodes.CodeBlockNodeModel guid="83c4d067-0435-4ec7-8e40-0833e88fe754" type="Dynamo.Graph.Nodes.CodeBlockNodeModel" nickname="Code Block" x="127.726216008951" y="-111.153398043288" isVisible="true" isUpstreamVisible="true" lacing="Disabled" isSelectedInput="False" IsFrozen="false" isPinned="false" CodeText="a[0..2];" ShouldFocus="false">
      <PortInfo index="0" default="False" />
    </Dynamo.Graph.Nodes.CodeBlockNodeModel>
    <Dynamo.Graph.Nodes.ZeroTouch.DSFunction guid="16de9914-cee2-4cc8-affe-0ffb71358543" type="Dynamo.Graph.Nodes.ZeroTouch.DSFunction" nickname="Flatten" x="-364.788111192172" y="-572.597814403357" isVisible="true" isUpstreamVisible="true" lacing="Shortest" isSelectedInput="False" IsFrozen="false" isPinned="false" assembly="BuiltIn" function="Flatten@var[]..[]">
      <PortInfo index="0" default="False" useLevels="True" level="3" shouldKeepListStructure="False" />
    </Dynamo.Graph.Nodes.ZeroTouch.DSFunction>
    <PythonNodeModels.PythonNode guid="6742db99-c7e3-468f-826e-b444526bc097" type="PythonNodeModels.PythonNode" nickname="Python Script" x="1357.10286958408" y="-509.121256137558" isVisible="true" isUpstreamVisible="true" lacing="Disabled" isSelectedInput="False" IsFrozen="false" isPinned="true" inputcount="3">
      <PortInfo index="0" default="False" />
      <PortInfo index="1" default="False" />
      <PortInfo index="2" default="False" />
      <Script>import clr
clr.AddReference('ProtoGeometry')
from Autodesk.DesignScript.Geometry import *
#Import ToDSType(bool) extension method
clr.AddReference('RevitNodes')
import Revit
clr.ImportExtensions(Revit.GeometryConversion)
#Import DocumentManager and TransactionManager
clr.AddReference('RevitServices')
import RevitServices
from RevitServices.Persistence import DocumentManager
from RevitServices.Transactions import TransactionManager
from System.Collections.Generic import *
#import RevitAPI
clr.AddReference('RevitAPI')
import Autodesk
from Autodesk.Revit.DB import *
from Autodesk.Revit.DB.Structure import *
from System.Collections.Generic import *


doc = DocumentManager.Instance.CurrentDBDocument
uiapp = DocumentManager.Instance.CurrentUIApplication
app = uiapp.Application


lista = IN[0]

profileLoops = []
pl = []

pl.Add(profileLoops)

for l in lista:
	if len(l)&gt;1:
		oP = l[0]
		iP = l[1:]
		outerProfileLoop = CurveLoop()
		ip = []
		loops = [outerProfileLoop,ip]
		profileLoops.Add(loops)
		for i in range(0,len(oP)-1):
			outerProfileLoop.Append(Autodesk.Revit.DB.Line.CreateBound(XYZ(oP[i].X,oP[i].Y,oP[i].Z),XYZ(oP[i+1].X,oP[i+1].Y,oP[i+1].Z)))
		for j in range(0,len(iP)):
			innerProfileLoop = CurveLoop()
			ip.append(innerProfileLoop)
			for i in range(0,len(iP[j])-1):
				innerProfileLoop.Append(Autodesk.Revit.DB.Line.CreateBound(XYZ(iP[j][i].X,iP[j][i].Y,iP[j][i].Z),XYZ(iP[j][i+1].X,iP[j][i+1].Y,iP[j][i+1].Z)))
				
	else:
		oP = l[0]
		outerProfileLoop = CurveLoop()
		profileLoops.Add(outerProfileLoop)
		for i in range(0,len(oP)-1):
			outerProfileLoop.Append(Autodesk.Revit.DB.Line.CreateBound(XYZ(oP[i].X,oP[i].Y,oP[i].Z),XYZ(oP[i+1].X,oP[i+1].Y,oP[i+1].Z)))
	

F=IN[1]
loadtype=UnwrapElement(IN[2])


#Assign your outputs to the OUT variable
OUT = pl
</Script>
    </PythonNodeModels.PythonNode>
    <Dynamo.Graph.Nodes.ZeroTouch.DSFunction guid="89b707a2-db67-4e9e-a15d-8d6455bc68c0" type="Dynamo.Graph.Nodes.ZeroTouch.DSFunction" nickname="Flatten" x="1631.82341322905" y="-465.956368986488" isVisible="true" isUpstreamVisible="true" lacing="Shortest" isSelectedInput="False" IsFrozen="false" isPinned="true" assembly="BuiltIn" function="Flatten@var[]..[]">
      <PortInfo index="0" default="False" useLevels="True" level="3" shouldKeepListStructure="True" />
    </Dynamo.Graph.Nodes.ZeroTouch.DSFunction>
    <Dynamo.Graph.Nodes.CodeBlockNodeModel guid="d67c0574-0264-4d84-8e32-354510126940" type="Dynamo.Graph.Nodes.CodeBlockNodeModel" nickname="Code Block" x="1933.51529408465" y="-470.410499030744" isVisible="true" isUpstreamVisible="true" lacing="Disabled" isSelectedInput="False" IsFrozen="false" isPinned="true" CodeText="a[0];" ShouldFocus="false">
      <PortInfo index="0" default="False" />
    </Dynamo.Graph.Nodes.CodeBlockNodeModel>
    <Dynamo.Graph.Nodes.CodeBlockNodeModel guid="ca5f4f6f-40c4-467e-8904-a25a5508bfd9" type="Dynamo.Graph.Nodes.CodeBlockNodeModel" nickname="Code Block" x="2048.2007136694" y="-449.776030108804" isVisible="true" isUpstreamVisible="true" lacing="Disabled" isSelectedInput="False" IsFrozen="false" isPinned="true" CodeText="{a[0],{a[1]},a[2]};" ShouldFocus="false">
      <PortInfo index="0" default="False" />
    </Dynamo.Graph.Nodes.CodeBlockNodeModel>
  </Elements>
  <Connectors>
    <Dynamo.Graph.Connectors.ConnectorModel start="2399b948-53fe-463a-a385-965aa4a4bb71" start_index="0" end="80bdc9c3-00ee-42ed-bfda-f95c2bd05555" end_index="0" portType="0" />
    <Dynamo.Graph.Connectors.ConnectorModel start="80bdc9c3-00ee-42ed-bfda-f95c2bd05555" start_index="0" end="d1b40fc9-39e0-4ce6-8ee3-4386e867f9cf" end_index="0" portType="0" />
    <Dynamo.Graph.Connectors.ConnectorModel start="aaf39cec-5e92-4850-b85c-db7b5ce09e47" start_index="1" end="ab0ffd34-5a5c-4920-89a8-4c6d05911587" end_index="2" portType="0" />
    <Dynamo.Graph.Connectors.ConnectorModel start="aaf39cec-5e92-4850-b85c-db7b5ce09e47" start_index="6" end="f6d223bf-9358-4fd8-aa7d-23b9f55e4dbb" end_index="0" portType="0" />
    <Dynamo.Graph.Connectors.ConnectorModel start="5ca508d6-e2cb-4fe0-9ff6-477b13e3567f" start_index="0" end="16de9914-cee2-4cc8-affe-0ffb71358543" end_index="0" portType="0" />
    <Dynamo.Graph.Connectors.ConnectorModel start="5ca508d6-e2cb-4fe0-9ff6-477b13e3567f" start_index="0" end="1e606c0b-9cbb-4a30-8dac-06d363ebb675" end_index="0" portType="0" />
    <Dynamo.Graph.Connectors.ConnectorModel start="906efb27-e359-4053-8608-e9c44f34f38e" start_index="0" end="d6723f5d-17fc-4ddd-8636-9ea5d46f1e1a" end_index="2" portType="0" />
    <Dynamo.Graph.Connectors.ConnectorModel start="1901f20d-8df0-4dff-a719-f373a2226399" start_index="0" end="5ca508d6-e2cb-4fe0-9ff6-477b13e3567f" end_index="1" portType="0" />
    <Dynamo.Graph.Connectors.ConnectorModel start="1e606c0b-9cbb-4a30-8dac-06d363ebb675" start_index="0" end="906efb27-e359-4053-8608-e9c44f34f38e" end_index="0" portType="0" />
    <Dynamo.Graph.Connectors.ConnectorModel start="aba9e559-8252-441b-98a2-33c767a3cb85" start_index="0" end="dcfc3c93-9c91-4e51-afbc-df7e36367c15" end_index="0" portType="0" />
    <Dynamo.Graph.Connectors.ConnectorModel start="dcfc3c93-9c91-4e51-afbc-df7e36367c15" start_index="0" end="c166a411-04ef-493a-be1a-57e1c9eb0cda" end_index="0" portType="0" />
    <Dynamo.Graph.Connectors.ConnectorModel start="dcfc3c93-9c91-4e51-afbc-df7e36367c15" start_index="0" end="94058e18-802c-4373-b9fc-ba3b0ad29f44" end_index="0" portType="0" />
    <Dynamo.Graph.Connectors.ConnectorModel start="b21d70ae-ea62-4479-bfde-275780c2e6cd" start_index="0" end="348b0729-0ab1-445f-906d-7f3756532b1f" end_index="0" portType="0" />
    <Dynamo.Graph.Connectors.ConnectorModel start="b21d70ae-ea62-4479-bfde-275780c2e6cd" start_index="0" end="f983e5f8-62a9-4e67-8a5a-075b40f96c78" end_index="0" portType="0" />
    <Dynamo.Graph.Connectors.ConnectorModel start="d1b40fc9-39e0-4ce6-8ee3-4386e867f9cf" start_index="0" end="92892510-8667-451c-af25-e50d4cdbb919" end_index="0" portType="0" />
    <Dynamo.Graph.Connectors.ConnectorModel start="d1b40fc9-39e0-4ce6-8ee3-4386e867f9cf" start_index="0" end="386ac324-31ae-49e7-b622-02242dc33971" end_index="0" portType="0" />
    <Dynamo.Graph.Connectors.ConnectorModel start="d1b40fc9-39e0-4ce6-8ee3-4386e867f9cf" start_index="0" end="6742db99-c7e3-468f-826e-b444526bc097" end_index="0" portType="0" />
    <Dynamo.Graph.Connectors.ConnectorModel start="b1d9577b-6a1d-45d0-9afa-3df07afc1c71" start_index="0" end="d1b40fc9-39e0-4ce6-8ee3-4386e867f9cf" end_index="1" portType="0" />
    <Dynamo.Graph.Connectors.ConnectorModel start="5cf3dbc1-2780-4e50-9c2c-3067ebe3050b" start_index="0" end="212e785f-69a4-4c1a-85a5-e8ec1ec2ebb3" end_index="0" portType="0" />
    <Dynamo.Graph.Connectors.ConnectorModel start="212e785f-69a4-4c1a-85a5-e8ec1ec2ebb3" start_index="0" end="a8dcb07b-ee16-4b46-b8fe-0d2f766c1db3" end_index="0" portType="0" />
    <Dynamo.Graph.Connectors.ConnectorModel start="212e785f-69a4-4c1a-85a5-e8ec1ec2ebb3" start_index="0" end="091f35f1-aee4-465b-b21a-b2547346f50e" end_index="2" portType="0" />
    <Dynamo.Graph.Connectors.ConnectorModel start="212e785f-69a4-4c1a-85a5-e8ec1ec2ebb3" start_index="0" end="6742db99-c7e3-468f-826e-b444526bc097" end_index="2" portType="0" />
    <Dynamo.Graph.Connectors.ConnectorModel start="d6723f5d-17fc-4ddd-8636-9ea5d46f1e1a" start_index="0" end="091f35f1-aee4-465b-b21a-b2547346f50e" end_index="1" portType="0" />
    <Dynamo.Graph.Connectors.ConnectorModel start="d6723f5d-17fc-4ddd-8636-9ea5d46f1e1a" start_index="0" end="6742db99-c7e3-468f-826e-b444526bc097" end_index="1" portType="0" />
    <Dynamo.Graph.Connectors.ConnectorModel start="0cedf692-65fc-415f-af4f-931000eb1f84" start_index="0" end="348b0729-0ab1-445f-906d-7f3756532b1f" end_index="1" portType="0" />
    <Dynamo.Graph.Connectors.ConnectorModel start="97b8343e-316f-48fa-9303-c14064da4495" start_index="0" end="ab0ffd34-5a5c-4920-89a8-4c6d05911587" end_index="1" portType="0" />
    <Dynamo.Graph.Connectors.ConnectorModel start="f983e5f8-62a9-4e67-8a5a-075b40f96c78" start_index="0" end="ab0ffd34-5a5c-4920-89a8-4c6d05911587" end_index="0" portType="0" />
    <Dynamo.Graph.Connectors.ConnectorModel start="94058e18-802c-4373-b9fc-ba3b0ad29f44" start_index="0" end="348b0729-0ab1-445f-906d-7f3756532b1f" end_index="2" portType="0" />
    <Dynamo.Graph.Connectors.ConnectorModel start="a973a276-0850-4c75-a061-8212dc0ababe" start_index="0" end="174374a2-8dee-4daf-88f7-72ff9134072b" end_index="1" portType="0" />
    <Dynamo.Graph.Connectors.ConnectorModel start="174374a2-8dee-4daf-88f7-72ff9134072b" start_index="0" end="b90b4cec-8e3f-484e-ba22-d6c7123c26a0" end_index="0" portType="0" />
    <Dynamo.Graph.Connectors.ConnectorModel start="174374a2-8dee-4daf-88f7-72ff9134072b" start_index="0" end="310929fb-c1fd-4552-85bc-8f8092ef8df0" end_index="0" portType="0" />
    <Dynamo.Graph.Connectors.ConnectorModel start="7931003d-382d-4210-87a2-bf341858409a" start_index="1" end="8f7a1041-89b2-438d-b65e-9e99657c9905" end_index="0" portType="0" />
    <Dynamo.Graph.Connectors.ConnectorModel start="8f7a1041-89b2-438d-b65e-9e99657c9905" start_index="0" end="174374a2-8dee-4daf-88f7-72ff9134072b" end_index="0" portType="0" />
    <Dynamo.Graph.Connectors.ConnectorModel start="39473050-3053-466f-a991-44b9e073f24a" start_index="0" end="be7b5428-0052-4569-9be2-042944981f7c" end_index="0" portType="0" />
    <Dynamo.Graph.Connectors.ConnectorModel start="c7a05bf0-9072-4b34-86ce-da1ce4d37db3" start_index="0" end="39473050-3053-466f-a991-44b9e073f24a" end_index="1" portType="0" />
    <Dynamo.Graph.Connectors.ConnectorModel start="be7b5428-0052-4569-9be2-042944981f7c" start_index="0" end="62452231-6668-443f-8317-542f5ab400a7" end_index="0" portType="0" />
    <Dynamo.Graph.Connectors.ConnectorModel start="713e9981-c4b6-4c12-913b-21f512969251" start_index="0" end="39473050-3053-466f-a991-44b9e073f24a" end_index="0" portType="0" />
    <Dynamo.Graph.Connectors.ConnectorModel start="8b2f1d01-1a44-4509-9ce7-562c484c1778" start_index="0" end="5c394160-4c2c-4efe-bdba-4bcdfa9afeeb" end_index="0" portType="0" />
    <Dynamo.Graph.Connectors.ConnectorModel start="c04bdbd4-4be9-47ab-b584-796550bfba85" start_index="0" end="62452231-6668-443f-8317-542f5ab400a7" end_index="1" portType="0" />
    <Dynamo.Graph.Connectors.ConnectorModel start="5c394160-4c2c-4efe-bdba-4bcdfa9afeeb" start_index="0" end="c04bdbd4-4be9-47ab-b584-796550bfba85" end_index="0" portType="0" />
    <Dynamo.Graph.Connectors.ConnectorModel start="f56d03c3-bee8-43a9-b237-b21f0c144835" start_index="0" end="62452231-6668-443f-8317-542f5ab400a7" end_index="2" portType="0" />
    <Dynamo.Graph.Connectors.ConnectorModel start="b90b4cec-8e3f-484e-ba22-d6c7123c26a0" start_index="0" end="fd355568-0f27-41ef-a6dc-3a9539160854" end_index="0" portType="0" />
    <Dynamo.Graph.Connectors.ConnectorModel start="2c51bd16-3db8-483a-9eab-1e8291c3159e" start_index="0" end="b90b4cec-8e3f-484e-ba22-d6c7123c26a0" end_index="1" portType="0" />
    <Dynamo.Graph.Connectors.ConnectorModel start="fd355568-0f27-41ef-a6dc-3a9539160854" start_index="0" end="310929fb-c1fd-4552-85bc-8f8092ef8df0" end_index="1" portType="0" />
    <Dynamo.Graph.Connectors.ConnectorModel start="54cad408-c11f-46b1-9ef1-da5220851c5a" start_index="0" end="fd355568-0f27-41ef-a6dc-3a9539160854" end_index="1" portType="0" />
    <Dynamo.Graph.Connectors.ConnectorModel start="310929fb-c1fd-4552-85bc-8f8092ef8df0" start_index="0" end="713e9981-c4b6-4c12-913b-21f512969251" end_index="0" portType="0" />
    <Dynamo.Graph.Connectors.ConnectorModel start="cdfa44a2-1988-4cc5-8754-b3313c0f690c" start_index="0" end="e0cf734e-ba29-4f0f-8daa-b80f708adf12" end_index="0" portType="0" />
    <Dynamo.Graph.Connectors.ConnectorModel start="cdfa44a2-1988-4cc5-8754-b3313c0f690c" start_index="0" end="5bc852fa-fd73-4853-abed-a12e6607598a" end_index="0" portType="0" />
    <Dynamo.Graph.Connectors.ConnectorModel start="56fecdde-c972-4e5a-b373-8b439e704ed4" start_index="0" end="aaf39cec-5e92-4850-b85c-db7b5ce09e47" end_index="0" portType="0" />
    <Dynamo.Graph.Connectors.ConnectorModel start="56fecdde-c972-4e5a-b373-8b439e704ed4" start_index="0" end="ba9478c3-13c2-409e-8de3-6cbebb8b17ac" end_index="0" portType="0" />
    <Dynamo.Graph.Connectors.ConnectorModel start="ba9478c3-13c2-409e-8de3-6cbebb8b17ac" start_index="0" end="5ea96270-d221-45b5-b22c-07db07577f66" end_index="0" portType="0" />
    <Dynamo.Graph.Connectors.ConnectorModel start="5ea96270-d221-45b5-b22c-07db07577f66" start_index="0" end="2399b948-53fe-463a-a385-965aa4a4bb71" end_index="0" portType="0" />
    <Dynamo.Graph.Connectors.ConnectorModel start="92892510-8667-451c-af25-e50d4cdbb919" start_index="0" end="43bbaf7d-2595-4698-bbdc-476a95593a5a" end_index="0" portType="0" />
    <Dynamo.Graph.Connectors.ConnectorModel start="43bbaf7d-2595-4698-bbdc-476a95593a5a" start_index="0" end="b76e5f77-d11c-46ca-9c56-32de24c1d35a" end_index="0" portType="0" />
    <Dynamo.Graph.Connectors.ConnectorModel start="c5091233-78a1-4715-98cd-b8908445bf03" start_index="0" end="ba9478c3-13c2-409e-8de3-6cbebb8b17ac" end_index="1" portType="0" />
    <Dynamo.Graph.Connectors.ConnectorModel start="c5091233-78a1-4715-98cd-b8908445bf03" start_index="0" end="5ca508d6-e2cb-4fe0-9ff6-477b13e3567f" end_index="0" portType="0" />
    <Dynamo.Graph.Connectors.ConnectorModel start="6742db99-c7e3-468f-826e-b444526bc097" start_index="0" end="89b707a2-db67-4e9e-a15d-8d6455bc68c0" end_index="0" portType="0" />
    <Dynamo.Graph.Connectors.ConnectorModel start="89b707a2-db67-4e9e-a15d-8d6455bc68c0" start_index="0" end="d67c0574-0264-4d84-8e32-354510126940" end_index="0" portType="0" />
    <Dynamo.Graph.Connectors.ConnectorModel start="d67c0574-0264-4d84-8e32-354510126940" start_index="0" end="ca5f4f6f-40c4-467e-8904-a25a5508bfd9" end_index="0" portType="0" />
    <Dynamo.Graph.Connectors.ConnectorModel start="ca5f4f6f-40c4-467e-8904-a25a5508bfd9" start_index="0" end="091f35f1-aee4-465b-b21a-b2547346f50e" end_index="0" portType="0" />
  </Connectors>
  <Notes />
  <Annotations>
    <Dynamo.Graph.Annotations.AnnotationModel guid="46c37a80-2152-480c-b8c8-336d8ccd7dfe" annotationText="GET THE BOUNDARY LINES END POINTS AND COPY THE FIRST POINT TO THE END OF THE LIST. (NEEDED FOR THE CREATE BOUND METHOD)" left="-412.334503796541" top="-1364.07586996548" width="498.562719496587" height="250.19236670027" fontSize="30" InitialTop="-1210.07586996548" InitialHeight="123" TextblockHeight="144" backgrouund="#FFB5B5B5">
      <Models ModelGuid="80bdc9c3-00ee-42ed-bfda-f95c2bd05555" />
      <Models ModelGuid="2399b948-53fe-463a-a385-965aa4a4bb71" />
    </Dynamo.Graph.Annotations.AnnotationModel>
    <Dynamo.Graph.Annotations.AnnotationModel guid="3257dfd2-780a-4cb7-a707-2570e8180235" annotationText="CREATE A AREA LOADS" left="-101.738390295329" top="-859.453761907174" width="1185.63213879761" height="1087.93521921085" fontSize="30" InitialTop="-813.453761907174" InitialHeight="1047.14489914774" TextblockHeight="36" backgrouund="#FFFFAA45">
      <Models ModelGuid="d6723f5d-17fc-4ddd-8636-9ea5d46f1e1a" />
      <Models ModelGuid="212e785f-69a4-4c1a-85a5-e8ec1ec2ebb3" />
      <Models ModelGuid="5cf3dbc1-2780-4e50-9c2c-3067ebe3050b" />
      <Models ModelGuid="b1d9577b-6a1d-45d0-9afa-3df07afc1c71" />
      <Models ModelGuid="d1b40fc9-39e0-4ce6-8ee3-4386e867f9cf" />
      <Models ModelGuid="b21d70ae-ea62-4479-bfde-275780c2e6cd" />
    </Dynamo.Graph.Annotations.AnnotationModel>
    <Dynamo.Graph.Annotations.AnnotationModel guid="7a0cc4f1-6444-44c3-b7ba-0fb36434dbca" annotationText="ASSIGN LOAD TYPE (DL,SDL,LL) AND DESCRIPTION" left="1130.80396782427" top="-760.20274198452" width="1150.63275315815" height="920.43363378284" fontSize="30" InitialTop="-714.20274198452" InitialHeight="904.83363378284" TextblockHeight="36" backgrouund="#FFFFAA45">
      <Models ModelGuid="aba9e559-8252-441b-98a2-33c767a3cb85" />
      <Models ModelGuid="dcfc3c93-9c91-4e51-afbc-df7e36367c15" />
      <Models ModelGuid="348b0729-0ab1-445f-906d-7f3756532b1f" />
      <Models ModelGuid="ab0ffd34-5a5c-4920-89a8-4c6d05911587" />
      <Models ModelGuid="0cedf692-65fc-415f-af4f-931000eb1f84" />
      <Models ModelGuid="97b8343e-316f-48fa-9303-c14064da4495" />
      <Models ModelGuid="f983e5f8-62a9-4e67-8a5a-075b40f96c78" />
      <Models ModelGuid="94058e18-802c-4373-b9fc-ba3b0ad29f44" />
    </Dynamo.Graph.Annotations.AnnotationModel>
    <Dynamo.Graph.Annotations.AnnotationModel guid="f2e253ff-8f69-4709-bfe7-4ffab3e6f9be" annotationText="THESE ARE THE DL, SDL AND LL PARAMETERS" left="-1270.48834159726" top="-253.629119318921" width="199.2" height="246.6" fontSize="30" InitialTop="-99.6291193189205" InitialHeight="123" TextblockHeight="144" backgrouund="#FFC1D676">
      <Models ModelGuid="1901f20d-8df0-4dff-a719-f373a2226399" />
    </Dynamo.Graph.Annotations.AnnotationModel>
    <Dynamo.Graph.Annotations.AnnotationModel guid="0b33709d-9aad-47a9-9018-b8674feaf52f" annotationText="FROM MEPOVER" left="-946.885220412029" top="-271.571911911741" width="279.2" height="164.2" fontSize="30" InitialTop="-225.571911911741" InitialHeight="149" TextblockHeight="36" backgrouund="#FFC1D676">
      <Models ModelGuid="5ca508d6-e2cb-4fe0-9ff6-477b13e3567f" />
    </Dynamo.Graph.Annotations.AnnotationModel>
    <Dynamo.Graph.Annotations.AnnotationModel guid="c6f00373-8fc4-4e1a-8e78-4c070c38ec36" annotationText="OPTION 1 - SELECT LINKED ROOMS" left="-2444.66204560346" top="-2960.02201965631" width="908.96655046488" height="363.61710903623" fontSize="30" InitialTop="-2914.02201965631" InitialHeight="348.017109036235" TextblockHeight="36" backgrouund="#FFB5B5B5">
      <Models ModelGuid="a973a276-0850-4c75-a061-8212dc0ababe" />
      <Models ModelGuid="174374a2-8dee-4daf-88f7-72ff9134072b" />
      <Models ModelGuid="7931003d-382d-4210-87a2-bf341858409a" />
      <Models ModelGuid="8f7a1041-89b2-438d-b65e-9e99657c9905" />
    </Dynamo.Graph.Annotations.AnnotationModel>
    <Dynamo.Graph.Annotations.AnnotationModel guid="0259d908-f93c-4592-8039-87741e24b59f" annotationText="EXTRACT THE ROOM CENTER BOUNDARIES, KEEP ONLY THE OUTER LINES (AT INDEX 0) AND GROUP THEM" left="-769.359683875655" top="-2860.68737281305" width="1200.18266852216" height="300.45952357268" fontSize="30" InitialTop="-2778.68737281305" InitialHeight="248.859523572688" TextblockHeight="72" backgrouund="#FFB5B5B5">
      <Models ModelGuid="39473050-3053-466f-a991-44b9e073f24a" />
      <Models ModelGuid="c7a05bf0-9072-4b34-86ce-da1ce4d37db3" />
      <Models ModelGuid="be7b5428-0052-4569-9be2-042944981f7c" />
      <Models ModelGuid="713e9981-c4b6-4c12-913b-21f512969251" />
    </Dynamo.Graph.Annotations.AnnotationModel>
  </Annotations>
  <Presets />
  <Cameras>
    <Camera Name="Background Preview" eyeX="4788.80126953125" eyeY="117704.5" eyeZ="-5951.55126953125" lookX="-840.754333496094" lookY="-117859.3984375" lookZ="1602.12133789063" upX="0.455349266529083" upY="0.19936791062355" upZ="-0.86770361661911" />
  </Cameras>
  <SessionTraceData>
    <NodeTraceData NodeId="c04bdbd4-4be9-47ab-b584-796550bfba85">
      <CallsiteTraceData CallSiteID="ByPlane_InClassDecl-1_InFunctionScope-1_Instance0_c04bdbd4-4be9-47ab-b584-796550bfba85">PFNPQVAtRU5WOkVudmVsb3BlIHhtbG5zOnhzaT0iaHR0cDovL3d3dy53My5vcmcvMjAwMS9YTUxTY2hlbWEtaW5zdGFuY2UiIHhtbG5zOnhzZD0iaHR0cDovL3d3dy53My5vcmcvMjAwMS9YTUxTY2hlbWEiIHhtbG5zOlNPQVAtRU5DPSJodHRwOi8vc2NoZW1hcy54bWxzb2FwLm9yZy9zb2FwL2VuY29kaW5nLyIgeG1sbnM6U09BUC1FTlY9Imh0dHA6Ly9zY2hlbWFzLnhtbHNvYXAub3JnL3NvYXAvZW52ZWxvcGUvIiB4bWxuczpjbHI9Imh0dHA6Ly9zY2hlbWFzLm1pY3Jvc29mdC5jb20vc29hcC9lbmNvZGluZy9jbHIvMS4wIiBTT0FQLUVOVjplbmNvZGluZ1N0eWxlPSJodHRwOi8vc2NoZW1hcy54bWxzb2FwLm9yZy9zb2FwL2VuY29kaW5nLyI+DQo8U09BUC1FTlY6Qm9keT4NCjxhMTpDYWxsU2l0ZV94MDAyQl9UcmFjZVNlcmlhbGlzZXJIZWxwZXIgaWQ9InJlZi0xIiB4bWxuczphMT0iaHR0cDovL3NjaGVtYXMubWljcm9zb2Z0LmNvbS9jbHIvbnNhc3NlbS9Qcm90b0NvcmUvUHJvdG9Db3JlJTJDJTIwVmVyc2lvbiUzRDEuMy4wLjg3NSUyQyUyMEN1bHR1cmUlM0RuZXV0cmFsJTJDJTIwUHVibGljS2V5VG9rZW4lM0RudWxsIj4NCjxOdW1iZXJPZkVsZW1lbnRzPjE8L051bWJlck9mRWxlbWVudHM+DQo8QmFzZS0wX0hhc0RhdGE+dHJ1ZTwvQmFzZS0wX0hhc0RhdGE+DQo8QmFzZS0wX0RhdGEgaWQ9InJlZi0zIj5QRk5QUVZBdFJVNVdPa1Z1ZG1Wc2IzQmxJSGh0Ykc1ek9uaHphVDBpYUhSMGNEb3ZMM2QzZHk1M015NXZjbWN2TWpBd01TOVlUVXhUWTJobGJXRXRhVzV6ZEdGdVkyVWlJSGh0Ykc1ek9uaHpaRDBpYUhSMGNEb3ZMM2QzZHk1M015NXZjbWN2TWpBd01TOVlUVXhUWTJobGJXRWlJSGh0Ykc1ek9sTlBRVkF0UlU1RFBTSm9kSFJ3T2k4dmMyTm9aVzFoY3k1NGJXeHpiMkZ3TG05eVp5OXpiMkZ3TDJWdVkyOWthVzVuTHlJZ2VHMXNibk02VTA5QlVDMUZUbFk5SW1oMGRIQTZMeTl6WTJobGJXRnpMbmh0YkhOdllYQXViM0puTDNOdllYQXZaVzUyWld4dmNHVXZJaUI0Yld4dWN6cGpiSEk5SW1oMGRIQTZMeTl6WTJobGJXRnpMbTFwWTNKdmMyOW1kQzVqYjIwdmMyOWhjQzlsYm1OdlpHbHVaeTlqYkhJdk1TNHdJaUJUVDBGUUxVVk9WanBsYm1OdlpHbHVaMU4wZVd4bFBTSm9kSFJ3T2k4dmMyTm9aVzFoY3k1NGJXeHpiMkZ3TG05eVp5OXpiMkZ3TDJWdVkyOWthVzVuTHlJK0RRbzhVMDlCVUMxRlRsWTZRbTlrZVQ0TkNqeGhNVHBUWlhKcFlXeHBlbUZpYkdWSlpDQnBaRDBpY21WbUxURWlJSGh0Ykc1ek9tRXhQU0pvZEhSd09pOHZjMk5vWlcxaGN5NXRhV055YjNOdlpuUXVZMjl0TDJOc2NpOXVjMkZ6YzJWdEwxSmxkbWwwVTJWeWRtbGpaWE11VUdWeWMybHpkR1Z1WTJVdlVtVjJhWFJUWlhKMmFXTmxjeVV5UXlVeU1GWmxjbk5wYjI0bE0wUXhMak11TUM0NE56VWxNa01sTWpCRGRXeDBkWEpsSlRORWJtVjFkSEpoYkNVeVF5VXlNRkIxWW14cFkwdGxlVlJ2YTJWdUpUTkViblZzYkNJK0RRbzhjM1J5YVc1blNVUWdhV1E5SW5KbFppMHpJajVtWkdNeU5HWTROUzAxWW1ZNUxUUXdOV0l0T1RBMU5DMDRObUUwTlRVM01UYzRNRGd0TURBeU1EUTFPVEk4TDNOMGNtbHVaMGxFUGcwS1BHbHVkRWxFUGpJeE1UUTVOakk4TDJsdWRFbEVQZzBLUEM5aE1UcFRaWEpwWVd4cGVtRmliR1ZKWkQ0TkNqd3ZVMDlCVUMxRlRsWTZRbTlrZVQ0TkNqd3ZVMDlCVUMxRlRsWTZSVzUyWld4dmNHVStEUW89PC9CYXNlLTBfRGF0YT4NCjxCYXNlLTBfSGFzTmVzdGVkRGF0YT5mYWxzZTwvQmFzZS0wX0hhc05lc3RlZERhdGE+DQo8L2ExOkNhbGxTaXRlX3gwMDJCX1RyYWNlU2VyaWFsaXNlckhlbHBlcj4NCjwvU09BUC1FTlY6Qm9keT4NCjwvU09BUC1FTlY6RW52ZWxvcGU+DQo=</CallsiteTraceData>
    </NodeTraceData>
  </SessionTraceData>
</Workspace>