<Workspace Version="1.3.1.1736" X="95.0640677184799" Y="263.280670404379" zoom="0.721395744756139" ScaleFactor="1" Name="Home" Description="" RunType="Manual" RunPeriod="1000" HasRunWithoutCrash="True">
  <NamespaceResolutionMap />
  <Elements>
    <Dynamo.Nodes.DSModelElementsSelection guid="d855c1e4-4926-4ef1-9192-c1a5dc127772" type="Dynamo.Nodes.DSModelElementsSelection" nickname="Select Model Elements" x="244.037211164653" y="473.903794681363" isVisible="true" isUpstreamVisible="true" lacing="Disabled" isSelectedInput="True" IsFrozen="false" isPinned="true" />
    <Dynamo.Graph.Nodes.CustomNodes.Function guid="2f3b5e74-335f-419a-b5d0-2a5063efd3f5" type="Dynamo.Graph.Nodes.CustomNodes.Function" nickname="Elements in Space" x="1048.50200630895" y="476.545995547432" isVisible="true" isUpstreamVisible="true" lacing="Shortest" isSelectedInput="False" IsFrozen="false" isPinned="true">
      <PortInfo index="0" default="False" />
      <PortInfo index="1" default="False" />
      <ID value="1d764a3b-6501-419f-a78f-8a8ccc8a6946" />
      <Name value="Elements in Space" />
      <Description value="This node will take an input of Spaces and Elements and attempt to group all elements by Room that it is located in. For elements that are placed by Line and not a Point, a mid point of line will be used to determine location. " />
      <Inputs>
        <Input value="Element" />
        <Input value="Space" />
      </Inputs>
      <Outputs>
        <Output value="Element" />
      </Outputs>
    </Dynamo.Graph.Nodes.CustomNodes.Function>
    <DSRevitNodesUI.Categories guid="4c10b848-bbb5-4dc1-96be-2f8b642f96df" type="DSRevitNodesUI.Categories" nickname="Categories" x="543.903427919802" y="684.699886248638" isVisible="true" isUpstreamVisible="true" lacing="Disabled" isSelectedInput="True" IsFrozen="false" isPinned="false" index="432:MEPSpaces" />
    <DSRevitNodesUI.ElementsOfCategory guid="9e8bf50a-98f8-49e5-ab82-96000df972bf" type="DSRevitNodesUI.ElementsOfCategory" nickname="All Elements of Category" x="750.6949348531" y="683.660221116932" isVisible="true" isUpstreamVisible="true" lacing="Disabled" isSelectedInput="False" IsFrozen="false" isPinned="true">
      <PortInfo index="0" default="False" />
    </DSRevitNodesUI.ElementsOfCategory>
    <PythonNodeModels.PythonNode guid="d1c5f5cf-ffc3-4b08-b9d8-37f7de41b295" type="PythonNodeModels.PythonNode" nickname="Python Script" x="1108.53696370933" y="339.212629740572" isVisible="true" isUpstreamVisible="true" lacing="Disabled" isSelectedInput="False" IsFrozen="false" isPinned="false" inputcount="2">
      <PortInfo index="0" default="False" />
      <PortInfo index="1" default="False" />
      <Script>#Copyright(c) 2015, Konrad Sobon
# @arch_laboratory, http://archi-lab.net

# This code is based on Family.InRoom node originally created
# by Peter Kompolschek and published on Dynamo blog. Big thanks 
# to Peter for sharing his work so graciously.

import clr
import sys
clr.AddReference('ProtoGeometry')
from Autodesk.DesignScript.Geometry import *

pyt_path = r'C:\Program Files (x86)\IronPython 2.7\Lib'
sys.path.append(pyt_path)

# Import ToDSType(bool) extension method
clr.AddReference("RevitNodes")
import Revit
clr.ImportExtensions(Revit.Elements)

# Import DocumentManager and TransactionManager
clr.AddReference("RevitServices")
import RevitServices
from RevitServices.Persistence import DocumentManager
from RevitServices.Transactions import TransactionManager

# Import RevitAPI
clr.AddReference("RevitAPI")
import Autodesk
from Autodesk.Revit.DB import *

doc = DocumentManager.Instance.CurrentDBDocument
uiapp = DocumentManager.Instance.CurrentUIApplication
app = uiapp.Application

#The inputs to this node will be stored as a list in the IN variable.
dataEnteringNode = IN

def TryGetSpace(family, phase):
	try:
		inSpace = family.Space[phase]
	except:
		inSpace = None
		pass
	return inSpace

def FamiliesInSpace(_space, _families, _doc):
	outList = []
	for family in _families:
		location = family.Location
		if type(location) == LocationPoint:
			pt = location.Point
		else:
			pt = location.Curve.Evaluate(0.5, True)
		if _space.IsPointInSpace(pt):
			outList.append(family)
		else:
			for phase in _doc.Phases:
				inSpace = TryGetSpace(family, phase)
				if inSpace != None and inSpace.ToDSType(True).Name == _space.ToDSType(True).Name:
					outList.append(family)
	return outList

try:
	errorReport = None
	families = []
	for i in IN[0]:
		families.append(UnwrapElement(i))
	
	spaces = []
	for i in IN[1]:
		if UnwrapElement(i).Area &gt; 0:
			spaces.append(UnwrapElement(i))
	
	outData = [[] for i in range(len(spaces))]
	for index, space in enumerate(spaces):
		outData[index].extend(FamiliesInSpace(space, families, doc))
except:
	# if error accurs anywhere in the process catch it
	import traceback
	errorReport = traceback.format_exc()

#Assign your output to the OUT variable
if errorReport == None:
	OUT = outData
else:
	OUT = errorReport</Script>
    </PythonNodeModels.PythonNode>
    <DSRevitNodesUI.Categories guid="d4b3b2cd-67bf-41eb-a6d8-df43d8cd2e20" type="DSRevitNodesUI.Categories" nickname="Categories" x="523.886396173091" y="306.445659200332" isVisible="true" isUpstreamVisible="true" lacing="Disabled" isSelectedInput="True" IsFrozen="false" isPinned="false" index="237:LightingFixtures" />
    <DSRevitNodesUI.ElementsOfCategory guid="5119655f-72db-4d56-bc5f-6131630eef17" type="DSRevitNodesUI.ElementsOfCategory" nickname="All Elements of Category" x="730.677903106389" y="305.405994068626" isVisible="true" isUpstreamVisible="true" lacing="Disabled" isSelectedInput="False" IsFrozen="false" isPinned="true">
      <PortInfo index="0" default="False" />
    </DSRevitNodesUI.ElementsOfCategory>
    <Dynamo.Graph.Nodes.ZeroTouch.DSFunction guid="b17e0f9b-34c4-42b8-85e4-0914488a5a88" type="Dynamo.Graph.Nodes.ZeroTouch.DSFunction" nickname="List.GroupByKey" x="1326.21845005226" y="12.1291361217561" isVisible="true" isUpstreamVisible="true" lacing="Shortest" isSelectedInput="False" IsFrozen="false" isPinned="true" assembly="DSCoreNodes.dll" function="DSCore.List.GroupByKey@var[]..[],var[]..[]">
      <PortInfo index="0" default="False" />
      <PortInfo index="1" default="False" />
    </Dynamo.Graph.Nodes.ZeroTouch.DSFunction>
    <Dynamo.Graph.Nodes.ZeroTouch.DSFunction guid="5c475849-4227-406b-a271-1e25113c706c" type="Dynamo.Graph.Nodes.ZeroTouch.DSFunction" nickname="FamilyInstance.Space" x="1007.09339319819" y="192.456967626423" isVisible="true" isUpstreamVisible="true" lacing="Shortest" isSelectedInput="False" IsFrozen="false" isPinned="false" assembly="..\AppData\Roaming\Dynamo\Dynamo Revit\1.3\packages\Rhythm\bin\Rhythm.dll" function="RevitElements.FamilyInstance.Space@Revit.Elements.Element">
      <PortInfo index="0" default="False" />
    </Dynamo.Graph.Nodes.ZeroTouch.DSFunction>
  </Elements>
  <Connectors>
    <Dynamo.Graph.Connectors.ConnectorModel start="4c10b848-bbb5-4dc1-96be-2f8b642f96df" start_index="0" end="9e8bf50a-98f8-49e5-ab82-96000df972bf" end_index="0" portType="0" />
    <Dynamo.Graph.Connectors.ConnectorModel start="9e8bf50a-98f8-49e5-ab82-96000df972bf" start_index="0" end="2f3b5e74-335f-419a-b5d0-2a5063efd3f5" end_index="1" portType="0" />
    <Dynamo.Graph.Connectors.ConnectorModel start="d4b3b2cd-67bf-41eb-a6d8-df43d8cd2e20" start_index="0" end="5119655f-72db-4d56-bc5f-6131630eef17" end_index="0" portType="0" />
    <Dynamo.Graph.Connectors.ConnectorModel start="5119655f-72db-4d56-bc5f-6131630eef17" start_index="0" end="2f3b5e74-335f-419a-b5d0-2a5063efd3f5" end_index="0" portType="0" />
    <Dynamo.Graph.Connectors.ConnectorModel start="5119655f-72db-4d56-bc5f-6131630eef17" start_index="0" end="b17e0f9b-34c4-42b8-85e4-0914488a5a88" end_index="0" portType="0" />
    <Dynamo.Graph.Connectors.ConnectorModel start="5119655f-72db-4d56-bc5f-6131630eef17" start_index="0" end="5c475849-4227-406b-a271-1e25113c706c" end_index="0" portType="0" />
    <Dynamo.Graph.Connectors.ConnectorModel start="5c475849-4227-406b-a271-1e25113c706c" start_index="0" end="b17e0f9b-34c4-42b8-85e4-0914488a5a88" end_index="1" portType="0" />
  </Connectors>
  <Notes />
  <Annotations />
  <Presets />
  <Cameras>
    <Camera Name="Background Preview" eyeX="-17" eyeY="24" eyeZ="50" lookX="12" lookY="-13" lookZ="-58" upX="0" upY="1" upZ="0" />
  </Cameras>
</Workspace>