<Workspace Version="1.2.1.3083" X="2817.78136162725" Y="-86.6602952044889" zoom="1.39965482476641" Name="Home" Description="" RunType="Manual" RunPeriod="1000" HasRunWithoutCrash="False">
  <NamespaceResolutionMap />
  <Elements>
    <Dynamo.Nodes.DSModelElementSelection guid="0509eed7-e5b9-43a9-aaf4-53d8da7ee443" type="Dynamo.Nodes.DSModelElementSelection" nickname="Select Model Element" x="-1044.22494039608" y="649.986423232223" isVisible="true" isUpstreamVisible="true" lacing="Disabled" isSelectedInput="True" IsFrozen="false" isPinned="false" />
    <Dynamo.Graph.Nodes.ZeroTouch.DSFunction guid="1c522a25-6af4-46aa-b350-60727ce727a5" type="Dynamo.Graph.Nodes.ZeroTouch.DSFunction" nickname="StructuralFraming.BeamByCurve" x="2878.88586834234" y="229.470549957683" isVisible="true" isUpstreamVisible="true" lacing="Longest" isSelectedInput="False" IsFrozen="false" isPinned="false" assembly="RevitNodes.dll" function="Revit.Elements.StructuralFraming.BeamByCurve@Autodesk.DesignScript.Geometry.Curve,Revit.Elements.Level,Revit.Elements.FamilyType">
      <PortInfo index="0" default="False" />
      <PortInfo index="1" default="False" />
      <PortInfo index="2" default="False" />
    </Dynamo.Graph.Nodes.ZeroTouch.DSFunction>
    <PythonNodeModels.PythonNode guid="c2364a2a-d433-4b4e-b442-8871f4319553" type="PythonNodeModels.PythonNode" nickname="Python Script" x="-10.7799553094165" y="734.537301401345" isVisible="true" isUpstreamVisible="true" lacing="Disabled" isSelectedInput="False" IsFrozen="false" isPinned="false" inputcount="1">
      <PortInfo index="0" default="False" />
      <Script>#Copyright 2016. All rights reserved. Bimorph Consultancy LTD, 5 St Johns Lane, London EC1M 4BH www.bimorph.co.uk
#Written by Thomas Mahon @Thomas__Mahon info@bimorph.co.uk package: bimorphNodes
#GitHub: https://github.com/ThomasMahon/bimorphNodes/

import clr

# Import RevitAPI
clr.AddReference("RevitAPI")
import Autodesk
from Autodesk.Revit.DB import *

dwgImport = UnwrapElement(IN[0])

catSub = dwgImport.Category.SubCategories
enum = catSub.GetEnumerator()

nameList = []
while enum.MoveNext():
	layerName = enum.Current.Name
	nameList.Add( layerName )
	
OUT  = nameList
</Script>
    </PythonNodeModels.PythonNode>
    <Dynamo.Graph.Nodes.CodeBlockNodeModel guid="5f71bf5c-ce48-4c57-b912-8a28cf6497cc" type="Dynamo.Graph.Nodes.CodeBlockNodeModel" nickname="Code Block" x="544.422278274733" y="243.710384147195" isVisible="true" isUpstreamVisible="true" lacing="Disabled" isSelectedInput="False" IsFrozen="false" isPinned="false" CodeText="a[17];" ShouldFocus="false">
      <PortInfo index="0" default="False" />
    </Dynamo.Graph.Nodes.CodeBlockNodeModel>
    <CoreNodeModels.Input.BoolSelector guid="789a48f6-aa1d-42e8-b96e-4e1887c6125d" type="CoreNodeModels.Input.BoolSelector" nickname="Boolean" x="1461.23759612635" y="301.336926066492" isVisible="true" isUpstreamVisible="true" lacing="Disabled" isSelectedInput="True" IsFrozen="false" isPinned="false">
      <System.Boolean>False</System.Boolean>
    </CoreNodeModels.Input.BoolSelector>
    <PythonNodeModels.PythonNode guid="82ae8341-4028-4330-91cf-58a2361cd83b" type="PythonNodeModels.PythonNode" nickname="Python Script" x="1847.57269717383" y="215.009969841238" isVisible="true" isUpstreamVisible="true" lacing="Disabled" isSelectedInput="False" IsFrozen="false" isPinned="false" inputcount="4">
      <PortInfo index="0" default="False" />
      <PortInfo index="1" default="False" />
      <PortInfo index="2" default="False" />
      <PortInfo index="3" default="False" />
      <Script>#Copyright 2016. All rights reserved. Bimorph Consultancy LTD, 5 St Johns Lane, London EC1M 4BH www.bimorph.co.uk
#Written by Thomas Mahon @Thomas__Mahon info@bimorph.co.uk package: bimorphNodes
#GitHub: https://github.com/ThomasMahon/bimorphNodes/

import clr

# Import DocumentManager and TransactionManager
clr.AddReference("RevitServices")
import RevitServices
from RevitServices.Persistence import DocumentManager
from RevitServices.Transactions import TransactionManager
from System.Collections.Generic import *

clr.AddReference("RevitNodes")
import Revit
# Import ToProtoType, ToRevitType geometry conversion extension methods
clr.ImportExtensions(Revit.GeometryConversion)

# Import RevitAPI
clr.AddReference("RevitAPI")
import Autodesk
from Autodesk.Revit.DB import *

doc = DocumentManager.Instance.CurrentDBDocument
uiapp = DocumentManager.Instance.CurrentUIApplication
app = uiapp.Application

importDWG = UnwrapElement(IN[0])
nameOfLayersToImport = IN[1]
revitModelLines = IN[2]

if nameOfLayersToImport == None or nameOfLayersToImport == []: 
	catSub = importDWG.Category.SubCategories
	enum = catSub.GetEnumerator()
	
	nameOfLayersToImport = []
	while enum.MoveNext():
		layerName = enum.Current.Name
		nameOfLayersToImport.Add( layerName )

if isinstance(nameOfLayersToImport, list):
	layerList = nameOfLayersToImport
else:
	layerList = [nameOfLayersToImport]

def storageDictionary(crvListDict, eleGraphicStyleName, e):
	if eleGraphicStyleName in crvListDict.keys(): 
		crvListDict[eleGraphicStyleName].append( e )
	else:
		crvListDict[eleGraphicStyleName] = []
		crvListDict[eleGraphicStyleName].append( e )
		
	
def curveConversion (crv, revitModelLines, crvObject, refPlane):
	if revitModelLines == True:
		crv.Add( doc.Create.NewModelCurve( crvObject, refPlane) )
	else:
		crv.Add( crvObject.ToProtoType() )
	
TransactionManager.Instance.EnsureInTransaction(doc)

geomEnum = importDWG.Geometry[ Options() ].GetEnumerator()

crvListDict = dict()
failedFilter = []
while geomEnum.MoveNext(): 
	instGeom = geomEnum.Current.GetInstanceGeometry()
	
	instGeomEnum = instGeom.GetEnumerator()
	while instGeomEnum.MoveNext():
		e = instGeomEnum.Current
		try:
			graphicStyleId = e.GraphicsStyleId
					
			eleGraphicStyle = doc.GetElement(graphicStyleId)
			eleGraphicStyleName = eleGraphicStyle.GraphicsStyleCategory.Name
			
			
			if eleGraphicStyleName in layerList: 
				storageDictionary(crvListDict, eleGraphicStyleName, e)

		except:
			try: 
				vol = e.Volume
				
				if vol == 0.0: 
					edgesList = e.Edges
					edgesEnum = edgesList.GetEnumerator()

					while edgesEnum.MoveNext():
						edge = edgesEnum.Current
						eleGraphicStyle = doc.GetElement(edge.GraphicsStyleId)
						eleGraphicStyleName = eleGraphicStyle.GraphicsStyleCategory.Name
						
						if eleGraphicStyleName in layerList:
							storageDictionary(crvListDict, eleGraphicStyleName, edge.AsCurve() )
							
			except: 
				failedFilter.Add(e)

if "2015" in app.VersionName:
	levelParam = "Base Level"
else:
	levelParam = BuiltInParameter.IMPORT_BASE_LEVEL

levelId = UnwrapElement(IN[3]).Id

pln = SketchPlane.Create(doc, levelId )
	
crvList = [ crv for crv in crvListDict.values() ] 

failedConversion = []
modelLines =  []
for subList in crvList: 
	crv = []
	for i in subList: 
		try:
			crvType = i.GetType()
			if crvType != Autodesk.Revit.DB.PolyLine:
				curveConversion(crv, revitModelLines, i, pln)
			else: 
				pt = i.GetCoordinates()
				count = i.NumberOfCoordinates
					
				for j in range(count-1): 
					ln = Line.CreateBound(pt[j], pt[j+1])
					curveConversion(crv, revitModelLines, ln, pln)
						
		except: 
			failedConversion.Add( i )
				
	modelLines.Add(crv)

TransactionManager.Instance.TransactionTaskDone()

OUT = modelLines, crvListDict.keys()</Script>
    </PythonNodeModels.PythonNode>
    <DSRevitNodesUI.Levels guid="7478bc31-c70e-4d79-ac7f-9a6d7c30c98f" type="DSRevitNodesUI.Levels" nickname="Levels" x="1473.48563153221" y="378.803644382868" isVisible="true" isUpstreamVisible="true" lacing="Disabled" isSelectedInput="True" IsFrozen="false" isPinned="false" index="0:00" />
    <Dynamo.Graph.Nodes.CodeBlockNodeModel guid="8a2817fd-301b-40ab-9d2e-f35a92bbfb85" type="Dynamo.Graph.Nodes.CodeBlockNodeModel" nickname="Code Block" x="2077.3930674444" y="217.992730986667" isVisible="true" isUpstreamVisible="true" lacing="Disabled" isSelectedInput="False" IsFrozen="false" isPinned="false" CodeText="Flatten(a[0]);" ShouldFocus="false">
      <PortInfo index="0" default="False" />
    </Dynamo.Graph.Nodes.CodeBlockNodeModel>
    <PythonNodeModels.PythonNode guid="18de7573-ca20-46ca-8b51-c6a2f4e3c68a" type="PythonNodeModels.PythonNode" nickname="Python Script" x="1461.92250307193" y="874.103743777929" isVisible="true" isUpstreamVisible="true" lacing="Disabled" isSelectedInput="False" IsFrozen="false" isPinned="false" inputcount="1">
      <PortInfo index="0" default="False" />
      <Script>import clr
clr.AddReference('ProtoGeometry')
from Autodesk.DesignScript.Geometry import *

# Import RevitAPI
clr.AddReference("RevitAPI")
import Autodesk
from Autodesk.Revit.DB import *

# Import RevitAPI
clr.AddReference("RevitServices")
import RevitServices
from RevitServices.Persistence import DocumentManager

#The inputs to this node will be stored as a list in the IN variables.
doc = DocumentManager.Instance.CurrentDBDocument
cat = doc.Settings.Categories

collector = FilteredElementCollector(doc).OfCategory(BuiltInCategory.OST_StructuralFraming)

#Assign your output to the OUT variable.
OUT = [i for i in collector]</Script>
    </PythonNodeModels.PythonNode>
    <Dynamo.Graph.Nodes.ZeroTouch.DSFunction guid="6d4e7ada-0520-4b82-94f5-1aa76132d53a" type="Dynamo.Graph.Nodes.ZeroTouch.DSFunction" nickname="String.Contains" x="2201.2266541282" y="931.297528100726" isVisible="true" isUpstreamVisible="true" lacing="Shortest" isSelectedInput="False" IsFrozen="false" isPinned="false" assembly="DSCoreNodes.dll" function="DSCore.String.Contains@string,string,bool">
      <PortInfo index="0" default="False" />
      <PortInfo index="1" default="False" />
      <PortInfo index="2" default="True" />
    </Dynamo.Graph.Nodes.ZeroTouch.DSFunction>
    <CoreNodeModels.Input.StringInput guid="33713f69-9823-4171-beb6-5861f0d8f442" type="CoreNodeModels.Input.StringInput" nickname="String" x="742.983873479951" y="965.089625939562" isVisible="true" isUpstreamVisible="true" lacing="Disabled" isSelectedInput="True" IsFrozen="false" isPinned="false">
      <System.String>305x127x42</System.String>
      <System.String value="305x127x42" />
    </CoreNodeModels.Input.StringInput>
    <Dynamo.Graph.Nodes.CodeBlockNodeModel guid="ad82c5f5-5d85-495c-bf5b-6ebcb6d6e061" type="Dynamo.Graph.Nodes.CodeBlockNodeModel" nickname="Code Block" x="1933.23517307418" y="1105.01240380969" isVisible="true" isUpstreamVisible="true" lacing="Disabled" isSelectedInput="False" IsFrozen="false" isPinned="false" CodeText="1;" ShouldFocus="false" />
    <Dynamo.Graph.Nodes.ZeroTouch.DSFunction guid="2055fd68-2ee3-491a-96d0-23d9a6e001d7" type="Dynamo.Graph.Nodes.ZeroTouch.DSFunction" nickname="Family.Name" x="1683.54863726463" y="729.802959542988" isVisible="true" isUpstreamVisible="true" lacing="Shortest" isSelectedInput="False" IsFrozen="false" isPinned="false" assembly="RevitNodes.dll" function="Revit.Elements.Family.Name">
      <PortInfo index="0" default="False" />
    </Dynamo.Graph.Nodes.ZeroTouch.DSFunction>
    <Dynamo.Graph.Nodes.ZeroTouch.DSFunction guid="8df92d03-7b04-4e9e-ba43-2a3b6663d227" type="Dynamo.Graph.Nodes.ZeroTouch.DSFunction" nickname="List.FilterByBoolMask" x="2524.62838783156" y="872.057277757854" isVisible="true" isUpstreamVisible="true" lacing="Shortest" isSelectedInput="False" IsFrozen="false" isPinned="false" assembly="DSCoreNodes.dll" function="DSCore.List.FilterByBoolMask@var[]..[],var[]..[]">
      <PortInfo index="0" default="False" />
      <PortInfo index="1" default="False" />
    </Dynamo.Graph.Nodes.ZeroTouch.DSFunction>
    <Dynamo.Graph.Nodes.CustomNodes.Function guid="e9a48d91-ace3-4dbf-b8bf-25d393245e76" type="Dynamo.Graph.Nodes.CustomNodes.Function" nickname="bv Remove Nulls" x="1973.644260682" y="812.587013114573" isVisible="true" isUpstreamVisible="true" lacing="Shortest" isSelectedInput="False" IsFrozen="false" isPinned="false">
      <PortInfo index="0" default="False" />
      <ID value="a8b0f382-e8bc-4198-93af-a93c1afcf265" />
      <Name value="bv Remove Nulls" />
      <Description value="forked from Lunchbox" />
      <Inputs>
        <Input value="List" />
      </Inputs>
      <Outputs>
        <Output value="Cleaned" />
      </Outputs>
    </Dynamo.Graph.Nodes.CustomNodes.Function>
    <Dynamo.Graph.Nodes.ZeroTouch.DSFunction guid="6a380aca-da6f-437d-82fc-158ac34ba5e6" type="Dynamo.Graph.Nodes.ZeroTouch.DSFunction" nickname="StructuralFraming.ColumnByCurve" x="2981.03716399964" y="1519.11195528174" isVisible="true" isUpstreamVisible="true" lacing="Shortest" isSelectedInput="False" IsFrozen="false" isPinned="false" assembly="RevitNodes.dll" function="Revit.Elements.StructuralFraming.ColumnByCurve@Autodesk.DesignScript.Geometry.Curve,Revit.Elements.Level,Revit.Elements.FamilyType">
      <PortInfo index="0" default="False" />
      <PortInfo index="1" default="False" />
      <PortInfo index="2" default="False" />
    </Dynamo.Graph.Nodes.ZeroTouch.DSFunction>
    <Dynamo.Graph.Nodes.CodeBlockNodeModel guid="fac5a40a-77b2-4de4-af8c-7a082d6891c2" type="Dynamo.Graph.Nodes.CodeBlockNodeModel" nickname="Code Block" x="635.501744929904" y="1621.2023406663" isVisible="true" isUpstreamVisible="true" lacing="Disabled" isSelectedInput="False" IsFrozen="false" isPinned="false" CodeText="a[11];" ShouldFocus="false">
      <PortInfo index="0" default="False" />
    </Dynamo.Graph.Nodes.CodeBlockNodeModel>
    <DSRevitNodesUI.Levels guid="d20b35ce-6759-44bf-8ade-c2623522ae44" type="DSRevitNodesUI.Levels" nickname="Levels" x="1453.18448614553" y="1714.91437231668" isVisible="true" isUpstreamVisible="true" lacing="Disabled" isSelectedInput="True" IsFrozen="false" isPinned="false" index="0:00" />
    <DSRevitNodesUI.StructuralColumnTypes guid="72b61969-6842-4421-a30d-1ca0678bde5f" type="DSRevitNodesUI.StructuralColumnTypes" nickname="Structural Column Types" x="825.189992704915" y="2011.38592946399" isVisible="true" isUpstreamVisible="true" lacing="Disabled" isSelectedInput="True" IsFrozen="false" isPinned="false" index="1108:UKC254x254x89" />
    <PythonNodeModels.PythonNode guid="c880adb7-3613-4b3b-92a9-67177d6133e8" type="PythonNodeModels.PythonNode" nickname="Python Script" x="1846.56606772995" y="1474.52552141915" isVisible="true" isUpstreamVisible="true" lacing="Disabled" isSelectedInput="False" IsFrozen="false" isPinned="false" inputcount="4">
      <PortInfo index="0" default="False" />
      <PortInfo index="1" default="False" />
      <PortInfo index="2" default="False" />
      <PortInfo index="3" default="False" />
      <Script>#Copyright 2016. All rights reserved. Bimorph Consultancy LTD, 5 St Johns Lane, London EC1M 4BH www.bimorph.co.uk
#Written by Thomas Mahon @Thomas__Mahon info@bimorph.co.uk package: bimorphNodes
#GitHub: https://github.com/ThomasMahon/bimorphNodes/

import clr

# Import DocumentManager and TransactionManager
clr.AddReference("RevitServices")
import RevitServices
from RevitServices.Persistence import DocumentManager
from RevitServices.Transactions import TransactionManager
from System.Collections.Generic import *

clr.AddReference("RevitNodes")
import Revit
# Import ToProtoType, ToRevitType geometry conversion extension methods
clr.ImportExtensions(Revit.GeometryConversion)

# Import RevitAPI
clr.AddReference("RevitAPI")
import Autodesk
from Autodesk.Revit.DB import *

doc = DocumentManager.Instance.CurrentDBDocument
uiapp = DocumentManager.Instance.CurrentUIApplication
app = uiapp.Application

importDWG = UnwrapElement(IN[0])
nameOfLayersToImport = IN[1]
revitModelLines = IN[2]

if nameOfLayersToImport == None or nameOfLayersToImport == []: 
	catSub = importDWG.Category.SubCategories
	enum = catSub.GetEnumerator()
	
	nameOfLayersToImport = []
	while enum.MoveNext():
		layerName = enum.Current.Name
		nameOfLayersToImport.Add( layerName )

if isinstance(nameOfLayersToImport, list):
	layerList = nameOfLayersToImport
else:
	layerList = [nameOfLayersToImport]

def storageDictionary(crvListDict, eleGraphicStyleName, e):
	if eleGraphicStyleName in crvListDict.keys(): 
		crvListDict[eleGraphicStyleName].append( e )
	else:
		crvListDict[eleGraphicStyleName] = []
		crvListDict[eleGraphicStyleName].append( e )
		
	
def curveConversion (crv, revitModelLines, crvObject, refPlane):
	if revitModelLines == True:
		crv.Add( doc.Create.NewModelCurve( crvObject, refPlane) )
	else:
		crv.Add( crvObject.ToProtoType() )
	
TransactionManager.Instance.EnsureInTransaction(doc)

geomEnum = importDWG.Geometry[ Options() ].GetEnumerator()

crvListDict = dict()
failedFilter = []
while geomEnum.MoveNext(): 
	instGeom = geomEnum.Current.GetInstanceGeometry()
	
	instGeomEnum = instGeom.GetEnumerator()
	while instGeomEnum.MoveNext():
		e = instGeomEnum.Current
		try:
			graphicStyleId = e.GraphicsStyleId
					
			eleGraphicStyle = doc.GetElement(graphicStyleId)
			eleGraphicStyleName = eleGraphicStyle.GraphicsStyleCategory.Name
			
			
			if eleGraphicStyleName in layerList: 
				storageDictionary(crvListDict, eleGraphicStyleName, e)

		except:
			try: 
				vol = e.Volume
				
				if vol == 0.0: 
					edgesList = e.Edges
					edgesEnum = edgesList.GetEnumerator()

					while edgesEnum.MoveNext():
						edge = edgesEnum.Current
						eleGraphicStyle = doc.GetElement(edge.GraphicsStyleId)
						eleGraphicStyleName = eleGraphicStyle.GraphicsStyleCategory.Name
						
						if eleGraphicStyleName in layerList:
							storageDictionary(crvListDict, eleGraphicStyleName, edge.AsCurve() )
							
			except: 
				failedFilter.Add(e)

if "2015" in app.VersionName:
	levelParam = "Base Level"
else:
	levelParam = BuiltInParameter.IMPORT_BASE_LEVEL

levelId = UnwrapElement(IN[3]).Id

pln = SketchPlane.Create(doc, levelId )
	
crvList = [ crv for crv in crvListDict.values() ] 

failedConversion = []
modelLines =  []
for subList in crvList: 
	crv = []
	for i in subList: 
		try:
			crvType = i.GetType()
			if crvType != Autodesk.Revit.DB.PolyLine:
				curveConversion(crv, revitModelLines, i, pln)
			else: 
				pt = i.GetCoordinates()
				count = i.NumberOfCoordinates
					
				for j in range(count-1): 
					ln = Line.CreateBound(pt[j], pt[j+1])
					curveConversion(crv, revitModelLines, ln, pln)
						
		except: 
			failedConversion.Add( i )
				
	modelLines.Add(crv)

TransactionManager.Instance.TransactionTaskDone()

OUT = modelLines, crvListDict.keys()</Script>
    </PythonNodeModels.PythonNode>
    <CoreNodeModels.Input.BoolSelector guid="47ba6003-24aa-4123-a5a0-6e6c1afdea18" type="CoreNodeModels.Input.BoolSelector" nickname="Boolean" x="1563.96305294087" y="1578.82260314688" isVisible="true" isUpstreamVisible="true" lacing="Disabled" isSelectedInput="True" IsFrozen="false" isPinned="false">
      <System.Boolean>False</System.Boolean>
    </CoreNodeModels.Input.BoolSelector>
    <Dynamo.Graph.Nodes.CodeBlockNodeModel guid="55c8668b-cf50-4a8f-9193-863ac422c7b3" type="Dynamo.Graph.Nodes.CodeBlockNodeModel" nickname="Code Block" x="2123.52331665985" y="1557.5936284761" isVisible="true" isUpstreamVisible="true" lacing="Disabled" isSelectedInput="False" IsFrozen="false" isPinned="false" CodeText="Flatten(a[0]);" ShouldFocus="false">
      <PortInfo index="0" default="False" />
    </Dynamo.Graph.Nodes.CodeBlockNodeModel>
    <Dynamo.Graph.Nodes.ZeroTouch.DSFunction guid="7bdc3303-f025-4ef3-a2c5-5c17e931c498" type="Dynamo.Graph.Nodes.ZeroTouch.DSFunction" nickname="List.GetItemAtIndex" x="879.662366134588" y="315.025574789224" isVisible="true" isUpstreamVisible="true" lacing="Shortest" isSelectedInput="False" IsFrozen="false" isPinned="false" assembly="DSCoreNodes.dll" function="DSCore.List.GetItemAtIndex@var[]..[],int">
      <PortInfo index="0" default="False" />
      <PortInfo index="1" default="False" />
    </Dynamo.Graph.Nodes.ZeroTouch.DSFunction>
  </Elements>
  <Connectors>
    <Dynamo.Graph.Connectors.ConnectorModel start="0509eed7-e5b9-43a9-aaf4-53d8da7ee443" start_index="0" end="c2364a2a-d433-4b4e-b442-8871f4319553" end_index="0" portType="0" />
    <Dynamo.Graph.Connectors.ConnectorModel start="0509eed7-e5b9-43a9-aaf4-53d8da7ee443" start_index="0" end="82ae8341-4028-4330-91cf-58a2361cd83b" end_index="0" portType="0" />
    <Dynamo.Graph.Connectors.ConnectorModel start="0509eed7-e5b9-43a9-aaf4-53d8da7ee443" start_index="0" end="c880adb7-3613-4b3b-92a9-67177d6133e8" end_index="0" portType="0" />
    <Dynamo.Graph.Connectors.ConnectorModel start="c2364a2a-d433-4b4e-b442-8871f4319553" start_index="0" end="fac5a40a-77b2-4de4-af8c-7a082d6891c2" end_index="0" portType="0" />
    <Dynamo.Graph.Connectors.ConnectorModel start="c2364a2a-d433-4b4e-b442-8871f4319553" start_index="0" end="5f71bf5c-ce48-4c57-b912-8a28cf6497cc" end_index="0" portType="0" />
    <Dynamo.Graph.Connectors.ConnectorModel start="5f71bf5c-ce48-4c57-b912-8a28cf6497cc" start_index="0" end="82ae8341-4028-4330-91cf-58a2361cd83b" end_index="1" portType="0" />
    <Dynamo.Graph.Connectors.ConnectorModel start="789a48f6-aa1d-42e8-b96e-4e1887c6125d" start_index="0" end="82ae8341-4028-4330-91cf-58a2361cd83b" end_index="2" portType="0" />
    <Dynamo.Graph.Connectors.ConnectorModel start="82ae8341-4028-4330-91cf-58a2361cd83b" start_index="0" end="8a2817fd-301b-40ab-9d2e-f35a92bbfb85" end_index="0" portType="0" />
    <Dynamo.Graph.Connectors.ConnectorModel start="7478bc31-c70e-4d79-ac7f-9a6d7c30c98f" start_index="0" end="82ae8341-4028-4330-91cf-58a2361cd83b" end_index="3" portType="0" />
    <Dynamo.Graph.Connectors.ConnectorModel start="7478bc31-c70e-4d79-ac7f-9a6d7c30c98f" start_index="0" end="1c522a25-6af4-46aa-b350-60727ce727a5" end_index="1" portType="0" />
    <Dynamo.Graph.Connectors.ConnectorModel start="8a2817fd-301b-40ab-9d2e-f35a92bbfb85" start_index="0" end="1c522a25-6af4-46aa-b350-60727ce727a5" end_index="0" portType="0" />
    <Dynamo.Graph.Connectors.ConnectorModel start="18de7573-ca20-46ca-8b51-c6a2f4e3c68a" start_index="0" end="2055fd68-2ee3-491a-96d0-23d9a6e001d7" end_index="0" portType="0" />
    <Dynamo.Graph.Connectors.ConnectorModel start="18de7573-ca20-46ca-8b51-c6a2f4e3c68a" start_index="0" end="8df92d03-7b04-4e9e-ba43-2a3b6663d227" end_index="0" portType="0" />
    <Dynamo.Graph.Connectors.ConnectorModel start="6d4e7ada-0520-4b82-94f5-1aa76132d53a" start_index="0" end="8df92d03-7b04-4e9e-ba43-2a3b6663d227" end_index="1" portType="0" />
    <Dynamo.Graph.Connectors.ConnectorModel start="33713f69-9823-4171-beb6-5861f0d8f442" start_index="0" end="6d4e7ada-0520-4b82-94f5-1aa76132d53a" end_index="1" portType="0" />
    <Dynamo.Graph.Connectors.ConnectorModel start="ad82c5f5-5d85-495c-bf5b-6ebcb6d6e061" start_index="0" end="6d4e7ada-0520-4b82-94f5-1aa76132d53a" end_index="2" portType="0" />
    <Dynamo.Graph.Connectors.ConnectorModel start="2055fd68-2ee3-491a-96d0-23d9a6e001d7" start_index="0" end="e9a48d91-ace3-4dbf-b8bf-25d393245e76" end_index="0" portType="0" />
    <Dynamo.Graph.Connectors.ConnectorModel start="8df92d03-7b04-4e9e-ba43-2a3b6663d227" start_index="0" end="1c522a25-6af4-46aa-b350-60727ce727a5" end_index="2" portType="0" />
    <Dynamo.Graph.Connectors.ConnectorModel start="e9a48d91-ace3-4dbf-b8bf-25d393245e76" start_index="0" end="6d4e7ada-0520-4b82-94f5-1aa76132d53a" end_index="0" portType="0" />
    <Dynamo.Graph.Connectors.ConnectorModel start="fac5a40a-77b2-4de4-af8c-7a082d6891c2" start_index="0" end="c880adb7-3613-4b3b-92a9-67177d6133e8" end_index="1" portType="0" />
    <Dynamo.Graph.Connectors.ConnectorModel start="d20b35ce-6759-44bf-8ade-c2623522ae44" start_index="0" end="6a380aca-da6f-437d-82fc-158ac34ba5e6" end_index="1" portType="0" />
    <Dynamo.Graph.Connectors.ConnectorModel start="d20b35ce-6759-44bf-8ade-c2623522ae44" start_index="0" end="c880adb7-3613-4b3b-92a9-67177d6133e8" end_index="3" portType="0" />
    <Dynamo.Graph.Connectors.ConnectorModel start="72b61969-6842-4421-a30d-1ca0678bde5f" start_index="0" end="6a380aca-da6f-437d-82fc-158ac34ba5e6" end_index="2" portType="0" />
    <Dynamo.Graph.Connectors.ConnectorModel start="c880adb7-3613-4b3b-92a9-67177d6133e8" start_index="0" end="55c8668b-cf50-4a8f-9193-863ac422c7b3" end_index="0" portType="0" />
    <Dynamo.Graph.Connectors.ConnectorModel start="47ba6003-24aa-4123-a5a0-6e6c1afdea18" start_index="0" end="c880adb7-3613-4b3b-92a9-67177d6133e8" end_index="2" portType="0" />
    <Dynamo.Graph.Connectors.ConnectorModel start="55c8668b-cf50-4a8f-9193-863ac422c7b3" start_index="0" end="6a380aca-da6f-437d-82fc-158ac34ba5e6" end_index="0" portType="0" />
  </Connectors>
  <Notes>
    <Dynamo.Graph.Notes.NoteModel guid="d42a9f14-4e0a-4d4a-8228-9cbd63964a26" text=" " x="489.825886537728" y="784.905083571063" />
    <Dynamo.Graph.Notes.NoteModel guid="ec29f5f6-b12d-4bf1-92cb-f0ec0053d016" text=" " x="-587.289472108837" y="707.382851819467" />
    <Dynamo.Graph.Notes.NoteModel guid="8c5fb7db-bf68-4efc-bf9f-48dbdb3564e0" text="This codeblock is the same as List Get Item at Index. The number in the square bracket is the index to pick." x="551.592876179746" y="343.301752030754" />
    <Dynamo.Graph.Notes.NoteModel guid="ae782c3e-1aad-44fb-a596-9b403f1fbd17" text=" " x="940.698796361949" y="1015.17399308521" />
    <Dynamo.Graph.Notes.NoteModel guid="765821cd-ffbe-47d8-9ebb-d075f3fbdf6a" text="Collects all the structural framing&#xD;&#xA;types in the Revit model" x="1464.09494207104" y="965.244486309311" />
    <Dynamo.Graph.Notes.NoteModel guid="b9a3dc3d-cca3-4ddf-88f1-4569811610ff" text=" " x="1105.39580001944" y="2076.37069757377" />
    <Dynamo.Graph.Notes.NoteModel guid="9faf936b-564c-462a-bcb7-8114a99fdc53" text=" " x="3326.33642364623" y="336.937795513548" />
    <Dynamo.Graph.Notes.NoteModel guid="5eabbb64-3d2d-4016-8f9f-e5f18f28cd24" text="New Note" x="3399.84886177551" y="1629.23839259567" />
    <Dynamo.Graph.Notes.NoteModel guid="6da327e5-5327-4ad1-b19e-0278fe3b0a88" text=" " x="1088.52979194212" y="1680.0665556713" />
    <Dynamo.Graph.Notes.NoteModel guid="5a5e9eb6-0651-4e66-afc1-5fde6341b688" text="Giovanni Brogiolo&#xD;&#xA;January 2017&#xD;&#xA;Dynamo 1.2.1&#xD;&#xA;&#xD;&#xA;PACKAGES&#xD;&#xA;Bimorph (rearranged a bit)" x="-1680.77531597949" y="401.663059659895" />
    <Dynamo.Graph.Notes.NoteModel guid="777a5d01-c1fb-44e5-a0db-a19b1b7d0099" text="Allows to select all the lines on a layer from an imported dwg. Those lines can be used to place structural framing and structural columns." x="-1683.33844957013" y="326.137334864138" />
  </Notes>
  <Annotations>
    <Dynamo.Graph.Annotations.AnnotationModel guid="dd2873f5-3a76-4f52-9dd6-8e5eb265cb80" annotationText="CAD LAYER NAMES&#xD;&#xA;FROM Bimorph PACKAGE" left="-20.7799553094165" top="609.537301401345" width="570.605841847145" height="219.367782169719" fontSize="48" InitialTop="734.537301401345" InitialHeight="123" TextblockHeight="115" backgrouund="#FFD8D8D8">
      <Models ModelGuid="c2364a2a-d433-4b4e-b442-8871f4319553" />
      <Models ModelGuid="d42a9f14-4e0a-4d4a-8228-9cbd63964a26" />
    </Dynamo.Graph.Annotations.AnnotationModel>
    <Dynamo.Graph.Annotations.AnnotationModel guid="3f56c149-f6ac-4f32-bfcc-392d33ae839d" annotationText="SELECT IMPORTED DWG" left="-1054.22494039608" top="581.986423232223" width="526.935468287239" height="169.396428587244" fontSize="48" InitialTop="649.986423232223" InitialHeight="136" TextblockHeight="58" backgrouund="#FFD4B6DB">
      <Models ModelGuid="0509eed7-e5b9-43a9-aaf4-53d8da7ee443" />
      <Models ModelGuid="ec29f5f6-b12d-4bf1-92cb-f0ec0053d016" />
    </Dynamo.Graph.Annotations.AnnotationModel>
    <Dynamo.Graph.Annotations.AnnotationModel guid="281cd144-8bc6-43d4-9758-68873d441868" annotationText="SELECT THE CAD LAYER(BEAMS)" left="534.422278274733" top="118.710384147195" width="531.240087859856" height="315.315190642029" fontSize="48" InitialTop="243.710384147195" InitialHeight="123" TextblockHeight="115" backgrouund="#FFD4B6DB">
      <Models ModelGuid="5f71bf5c-ce48-4c57-b912-8a28cf6497cc" />
      <Models ModelGuid="8c5fb7db-bf68-4efc-bf9f-48dbdb3564e0" />
      <Models ModelGuid="7bdc3303-f025-4ef3-a2c5-5c17e931c498" />
    </Dynamo.Graph.Annotations.AnnotationModel>
    <Dynamo.Graph.Annotations.AnnotationModel guid="a1e9bba7-32fc-49e4-b813-b2598d188859" annotationText="CURVES FROM CAD LAYERS&#xD;&#xA;FROM Bimorph PACKAGE" left="1451.23759612635" top="90.0099698412383" width="802.155471318045" height="381.79367454163" fontSize="48" InitialTop="215.009969841238" InitialHeight="201" TextblockHeight="115" backgrouund="#FFD8D8D8">
      <Models ModelGuid="82ae8341-4028-4330-91cf-58a2361cd83b" />
      <Models ModelGuid="789a48f6-aa1d-42e8-b96e-4e1887c6125d" />
      <Models ModelGuid="7478bc31-c70e-4d79-ac7f-9a6d7c30c98f" />
      <Models ModelGuid="8a2817fd-301b-40ab-9d2e-f35a92bbfb85" />
    </Dynamo.Graph.Annotations.AnnotationModel>
    <Dynamo.Graph.Annotations.AnnotationModel guid="3e5fd67c-de51-4c11-bf81-c6d35b24acb0" annotationText="GET THE REVIT BEAMS" left="1451.92250307193" top="661.802959542988" width="1250.70588475963" height="536.209444266702" fontSize="48" InitialTop="729.802959542988" InitialHeight="398.195402692476" TextblockHeight="58" backgrouund="#FFD8D8D8">
      <Models ModelGuid="18de7573-ca20-46ca-8b51-c6a2f4e3c68a" />
      <Models ModelGuid="6d4e7ada-0520-4b82-94f5-1aa76132d53a" />
      <Models ModelGuid="ad82c5f5-5d85-495c-bf5b-6ebcb6d6e061" />
      <Models ModelGuid="2055fd68-2ee3-491a-96d0-23d9a6e001d7" />
      <Models ModelGuid="e9a48d91-ace3-4dbf-b8bf-25d393245e76" />
      <Models ModelGuid="8df92d03-7b04-4e9e-ba43-2a3b6663d227" />
      <Models ModelGuid="765821cd-ffbe-47d8-9ebb-d075f3fbdf6a" />
    </Dynamo.Graph.Annotations.AnnotationModel>
    <Dynamo.Graph.Annotations.AnnotationModel guid="ae7a4d0a-a3ac-4fc1-92c0-beeedc27d746" annotationText="TYPE THE BEAM SIZE" left="732.983873479951" top="840.089625939562" width="267.714922881998" height="219.084367145644" fontSize="48" InitialTop="965.089625939562" InitialHeight="98" TextblockHeight="115" backgrouund="#FFD4B6DB">
      <Models ModelGuid="33713f69-9823-4171-beb6-5861f0d8f442" />
      <Models ModelGuid="ae782c3e-1aad-44fb-a596-9b403f1fbd17" />
    </Dynamo.Graph.Annotations.AnnotationModel>
    <Dynamo.Graph.Annotations.AnnotationModel guid="560e4b44-16dc-4f34-a735-76f0a0c04c4d" annotationText="CREATE STRUCTURAL FRAMING IN REVIT" left="2868.88586834234" top="104.470549957683" width="517.450555303896" height="276.467245555865" fontSize="48" InitialTop="229.470549957683" InitialHeight="179.402247043093" TextblockHeight="115" backgrouund="#FFFFAA45">
      <Models ModelGuid="1c522a25-6af4-46aa-b350-60727ce727a5" />
      <Models ModelGuid="9faf936b-564c-462a-bcb7-8114a99fdc53" />
    </Dynamo.Graph.Annotations.AnnotationModel>
    <Dynamo.Graph.Annotations.AnnotationModel guid="e391cc46-35a8-4ff7-a908-d8d087d920af" annotationText="CURVES FROM CAD LAYERS&#xD;&#xA;FROM Bimorph PACKAGE" left="1443.18448614553" top="1349.52552141915" width="856.338830514319" height="458.388850897533" fontSize="48" InitialTop="1474.52552141915" InitialHeight="363.388850897533" TextblockHeight="115" backgrouund="#FFD8D8D8">
      <Models ModelGuid="d20b35ce-6759-44bf-8ade-c2623522ae44" />
      <Models ModelGuid="c880adb7-3613-4b3b-92a9-67177d6133e8" />
      <Models ModelGuid="47ba6003-24aa-4123-a5a0-6e6c1afdea18" />
      <Models ModelGuid="55c8668b-cf50-4a8f-9193-863ac422c7b3" />
    </Dynamo.Graph.Annotations.AnnotationModel>
    <Dynamo.Graph.Annotations.AnnotationModel guid="5a92bf2c-251a-47dd-986e-c3ad40143ba7" annotationText="SELECT COLUMN SIZE" left="815.189992704915" top="1886.38592946399" width="350.205807314526" height="233.984768109782" fontSize="48" InitialTop="2011.38592946399" InitialHeight="123" TextblockHeight="115" backgrouund="#FFD4B6DB">
      <Models ModelGuid="72b61969-6842-4421-a30d-1ca0678bde5f" />
      <Models ModelGuid="b9a3dc3d-cca3-4ddf-88f1-4569811610ff" />
    </Dynamo.Graph.Annotations.AnnotationModel>
    <Dynamo.Graph.Annotations.AnnotationModel guid="e63a8821-7a90-4ec7-af39-0fa54b5c0734" annotationText="CREATE STRUCTURAL COLUMNS IN REVIT" left="2971.03716399964" top="1394.11195528174" width="512.811697775865" height="279.126437313936" fontSize="48" InitialTop="1519.11195528174" InitialHeight="175" TextblockHeight="115" backgrouund="#FFFFAA45">
      <Models ModelGuid="6a380aca-da6f-437d-82fc-158ac34ba5e6" />
      <Models ModelGuid="5eabbb64-3d2d-4016-8f9f-e5f18f28cd24" />
    </Dynamo.Graph.Annotations.AnnotationModel>
    <Dynamo.Graph.Annotations.AnnotationModel guid="5352b550-5983-43f4-b708-68951a7d2bc7" annotationText="SELECT THE CAD LAYER &#xD;&#xA;(COLUMNS)" left="625.501744929904" top="1496.2023406663" width="523.028047012214" height="227.864215005" fontSize="48" InitialTop="1621.2023406663" InitialHeight="123" TextblockHeight="115" backgrouund="#FFD4B6DB">
      <Models ModelGuid="fac5a40a-77b2-4de4-af8c-7a082d6891c2" />
      <Models ModelGuid="6da327e5-5327-4ad1-b19e-0278fe3b0a88" />
    </Dynamo.Graph.Annotations.AnnotationModel>
    <Dynamo.Graph.Annotations.AnnotationModel guid="7a34feb3-3de2-48d6-b8f8-476bed8e010b" annotationText="GUIDLINES" left="-1693.33844957013" top="258.137334864138" width="292" height="259.525724795756" fontSize="48" InitialTop="326.137334864138" InitialHeight="178.525724795756" TextblockHeight="58" backgrouund="#FFA4E1FF">
      <Models ModelGuid="5a5e9eb6-0651-4e66-afc1-5fde6341b688" />
      <Models ModelGuid="777a5d01-c1fb-44e5-a0db-a19b1b7d0099" />
    </Dynamo.Graph.Annotations.AnnotationModel>
  </Annotations>
  <Presets />
  <Cameras>
    <Camera Name="Background Preview" eyeX="-17" eyeY="24" eyeZ="50" lookX="12" lookY="-13" lookZ="-58" upX="0" upY="1" upZ="0" />
  </Cameras>
</Workspace>