<Workspace Version="0.8.2.2392" X="457.183477722409" Y="-25.9787957071237" zoom="0.482283383972273" Name="Home" Description="" RunType="Manual" RunPeriod="1000" HasRunWithoutCrash="False">
  <NamespaceResolutionMap />
  <Elements>
    <Dynamo.Nodes.DSModelElementSelection guid="0509eed7-e5b9-43a9-aaf4-53d8da7ee443" type="Dynamo.Nodes.DSModelElementSelection" nickname="Select Model Element" x="-700.561298211667" y="262.462584415606" isVisible="true" isUpstreamVisible="true" lacing="Disabled" isSelectedInput="True">
      <instance id="3e8af29c-7788-4f63-86e8-400f4baea680-002b3908" />
    </Dynamo.Nodes.DSModelElementSelection>
    <Dynamo.Nodes.DSFunction guid="1c522a25-6af4-46aa-b350-60727ce727a5" type="Dynamo.Nodes.DSFunction" nickname="StructuralFraming.BeamByCurve" x="2115.56822575914" y="321.858651099039" isVisible="true" isUpstreamVisible="true" lacing="Longest" isSelectedInput="False" assembly="RevitNodes.dll" function="Revit.Elements.StructuralFraming.BeamByCurve@Autodesk.DesignScript.Geometry.Curve,Revit.Elements.Level,Revit.Elements.FamilySymbol" />
    <DSIronPythonNode.PythonNode guid="c2364a2a-d433-4b4e-b442-8871f4319553" type="DSIronPythonNode.PythonNode" nickname="Python Script" x="-44.26218995068" y="394.949180912708" isVisible="true" isUpstreamVisible="true" lacing="Disabled" isSelectedInput="False" inputcount="1">
      <Script>#Copyright 2016. All rights reserved. Bimorph Consultancy LTD, 5 St Johns Lane, London EC1M 4BH www.bimorph.co.uk
#Written by Thomas Mahon @Thomas__Mahon info@bimorph.co.uk package: bimorphNodes
#GitHub: https://github.com/ThomasMahon/bimorphNodes/

import clr

# Import RevitAPI
clr.AddReference("RevitAPI")
import Autodesk
from Autodesk.Revit.DB import *

dwgImport = UnwrapElement(IN[0])

catSub = dwgImport.Category.SubCategories
enum = catSub.GetEnumerator()

nameList = []
while enum.MoveNext():
	layerName = enum.Current.Name
	nameList.Add( layerName )
	
OUT  = nameList
</Script>
    </DSIronPythonNode.PythonNode>
    <Dynamo.Nodes.CodeBlockNodeModel guid="5f71bf5c-ce48-4c57-b912-8a28cf6497cc" type="Dynamo.Nodes.CodeBlockNodeModel" nickname="Code Block" x="152.691975834109" y="398.331977690245" isVisible="true" isUpstreamVisible="true" lacing="Disabled" isSelectedInput="False" CodeText="a[6];" ShouldFocus="false" />
    <DSCoreNodesUI.BoolSelector guid="789a48f6-aa1d-42e8-b96e-4e1887c6125d" type="DSCoreNodesUI.BoolSelector" nickname="Boolean" x="892.924184637375" y="512.881604069621" isVisible="true" isUpstreamVisible="true" lacing="Disabled" isSelectedInput="True">
      <System.Boolean>False</System.Boolean>
    </DSCoreNodesUI.BoolSelector>
    <DSIronPythonNode.PythonNode guid="82ae8341-4028-4330-91cf-58a2361cd83b" type="DSIronPythonNode.PythonNode" nickname="Python Script" x="1170.13769659692" y="318.901882723442" isVisible="true" isUpstreamVisible="true" lacing="Disabled" isSelectedInput="False" inputcount="4">
      <Script>#Copyright 2016. All rights reserved. Bimorph Consultancy LTD, 5 St Johns Lane, London EC1M 4BH www.bimorph.co.uk
#Written by Thomas Mahon @Thomas__Mahon info@bimorph.co.uk package: bimorphNodes
#GitHub: https://github.com/ThomasMahon/bimorphNodes/

import clr

# Import DocumentManager and TransactionManager
clr.AddReference("RevitServices")
import RevitServices
from RevitServices.Persistence import DocumentManager
from RevitServices.Transactions import TransactionManager
from System.Collections.Generic import *

clr.AddReference("RevitNodes")
import Revit
# Import ToProtoType, ToRevitType geometry conversion extension methods
clr.ImportExtensions(Revit.GeometryConversion)

# Import RevitAPI
clr.AddReference("RevitAPI")
import Autodesk
from Autodesk.Revit.DB import *

doc = DocumentManager.Instance.CurrentDBDocument
uiapp = DocumentManager.Instance.CurrentUIApplication
app = uiapp.Application

importDWG = UnwrapElement(IN[0])
nameOfLayersToImport = IN[1]
revitModelLines = IN[2]

if nameOfLayersToImport == None or nameOfLayersToImport == []: 
	catSub = importDWG.Category.SubCategories
	enum = catSub.GetEnumerator()
	
	nameOfLayersToImport = []
	while enum.MoveNext():
		layerName = enum.Current.Name
		nameOfLayersToImport.Add( layerName )

if isinstance(nameOfLayersToImport, list):
	layerList = nameOfLayersToImport
else:
	layerList = [nameOfLayersToImport]

def storageDictionary(crvListDict, eleGraphicStyleName, e):
	if eleGraphicStyleName in crvListDict.keys(): 
		crvListDict[eleGraphicStyleName].append( e )
	else:
		crvListDict[eleGraphicStyleName] = []
		crvListDict[eleGraphicStyleName].append( e )
		
	
def curveConversion (crv, revitModelLines, crvObject, refPlane):
	if revitModelLines == True:
		crv.Add( doc.Create.NewModelCurve( crvObject, refPlane) )
	else:
		crv.Add( crvObject.ToProtoType() )
	
TransactionManager.Instance.EnsureInTransaction(doc)

geomEnum = importDWG.Geometry[ Options() ].GetEnumerator()

crvListDict = dict()
failedFilter = []
while geomEnum.MoveNext(): 
	instGeom = geomEnum.Current.GetInstanceGeometry()
	
	instGeomEnum = instGeom.GetEnumerator()
	while instGeomEnum.MoveNext():
		e = instGeomEnum.Current
		try:
			graphicStyleId = e.GraphicsStyleId
					
			eleGraphicStyle = doc.GetElement(graphicStyleId)
			eleGraphicStyleName = eleGraphicStyle.GraphicsStyleCategory.Name
			
			
			if eleGraphicStyleName in layerList: 
				storageDictionary(crvListDict, eleGraphicStyleName, e)

		except:
			try: 
				vol = e.Volume
				
				if vol == 0.0: 
					edgesList = e.Edges
					edgesEnum = edgesList.GetEnumerator()

					while edgesEnum.MoveNext():
						edge = edgesEnum.Current
						eleGraphicStyle = doc.GetElement(edge.GraphicsStyleId)
						eleGraphicStyleName = eleGraphicStyle.GraphicsStyleCategory.Name
						
						if eleGraphicStyleName in layerList:
							storageDictionary(crvListDict, eleGraphicStyleName, edge.AsCurve() )
							
			except: 
				failedFilter.Add(e)

if "2015" in app.VersionName:
	levelParam = "Base Level"
else:
	levelParam = BuiltInParameter.IMPORT_BASE_LEVEL

levelId = UnwrapElement(IN[3]).Id

pln = SketchPlane.Create(doc, levelId )
	
crvList = [ crv for crv in crvListDict.values() ] 

failedConversion = []
modelLines =  []
for subList in crvList: 
	crv = []
	for i in subList: 
		try:
			crvType = i.GetType()
			if crvType != Autodesk.Revit.DB.PolyLine:
				curveConversion(crv, revitModelLines, i, pln)
			else: 
				pt = i.GetCoordinates()
				count = i.NumberOfCoordinates
					
				for j in range(count-1): 
					ln = Line.CreateBound(pt[j], pt[j+1])
					curveConversion(crv, revitModelLines, ln, pln)
						
		except: 
			failedConversion.Add( i )
				
	modelLines.Add(crv)

TransactionManager.Instance.TransactionTaskDone()

OUT = modelLines, crvListDict.keys()</Script>
    </DSIronPythonNode.PythonNode>
    <DSRevitNodesUI.Levels guid="7478bc31-c70e-4d79-ac7f-9a6d7c30c98f" type="DSRevitNodesUI.Levels" nickname="Levels" x="-44.2621899506797" y="622.130305937832" isVisible="true" isUpstreamVisible="true" lacing="Disabled" isSelectedInput="True" index="4:G00 - ENTRANCE" />
    <Dynamo.Nodes.CodeBlockNodeModel guid="8a2817fd-301b-40ab-9d2e-f35a92bbfb85" type="Dynamo.Nodes.CodeBlockNodeModel" nickname="Code Block" x="1602.62075658451" y="322.171613766405" isVisible="true" isUpstreamVisible="true" lacing="Disabled" isSelectedInput="False" CodeText="Flatten(a[0]);" ShouldFocus="false" />
    <DSIronPythonNode.PythonNode guid="18de7573-ca20-46ca-8b51-c6a2f4e3c68a" type="DSIronPythonNode.PythonNode" nickname="Python Script" x="485.310163274404" y="728.860757459399" isVisible="true" isUpstreamVisible="true" lacing="Disabled" isSelectedInput="False" inputcount="1">
      <Script>import clr
clr.AddReference('ProtoGeometry')
from Autodesk.DesignScript.Geometry import *

# Import RevitAPI
clr.AddReference("RevitAPI")
import Autodesk
from Autodesk.Revit.DB import *

# Import RevitAPI
clr.AddReference("RevitServices")
import RevitServices
from RevitServices.Persistence import DocumentManager

#The inputs to this node will be stored as a list in the IN variables.
doc = DocumentManager.Instance.CurrentDBDocument
cat = doc.Settings.Categories

collector = FilteredElementCollector(doc).OfCategory(BuiltInCategory.OST_StructuralFraming)

#Assign your output to the OUT variable.
OUT = [i for i in collector]</Script>
    </DSIronPythonNode.PythonNode>
    <Dynamo.Nodes.DSFunction guid="6d4e7ada-0520-4b82-94f5-1aa76132d53a" type="Dynamo.Nodes.DSFunction" nickname="String.Contains" x="1389.66270901856" y="848.976474310346" isVisible="true" isUpstreamVisible="true" lacing="Shortest" isSelectedInput="False" assembly="DSCoreNodes.dll" function="DSCore.String.Contains@string,string,bool">
      <PortInfo index="2" default="True" />
    </Dynamo.Nodes.DSFunction>
    <Dynamo.Nodes.StringInput guid="33713f69-9823-4171-beb6-5861f0d8f442" type="Dynamo.Nodes.StringInput" nickname="String" x="-44.2621899506797" y="887.696335575537" isVisible="true" isUpstreamVisible="true" lacing="Disabled" isSelectedInput="True">
      <System.String>uc203x203x71</System.String>
      <System.String value="uc203x203x71" />
    </Dynamo.Nodes.StringInput>
    <Dynamo.Nodes.CodeBlockNodeModel guid="ad82c5f5-5d85-495c-bf5b-6ebcb6d6e061" type="Dynamo.Nodes.CodeBlockNodeModel" nickname="Code Block" x="1197.57261773535" y="899.327162138177" isVisible="true" isUpstreamVisible="true" lacing="Disabled" isSelectedInput="True" CodeText="1;" ShouldFocus="false" />
    <Dynamo.Nodes.DSFunction guid="2055fd68-2ee3-491a-96d0-23d9a6e001d7" type="Dynamo.Nodes.DSFunction" nickname="Family.Name" x="693.809654695746" y="818.719205929291" isVisible="true" isUpstreamVisible="true" lacing="Shortest" isSelectedInput="False" assembly="RevitNodes.dll" function="Revit.Elements.Family.Name" />
    <Dynamo.Nodes.DSFunction guid="8df92d03-7b04-4e9e-ba43-2a3b6663d227" type="Dynamo.Nodes.DSFunction" nickname="List.FilterByBoolMask" x="1787.59746497359" y="745.106456931408" isVisible="true" isUpstreamVisible="true" lacing="Shortest" isSelectedInput="False" assembly="DSCoreNodes.dll" function="DSCore.List.FilterByBoolMask@var[]..[],var[]..[]" />
    <Dynamo.Nodes.Function guid="e9a48d91-ace3-4dbf-b8bf-25d393245e76" type="Dynamo.Nodes.Function" nickname="bv Remove Nulls" x="975.660723516239" y="794.535798900024" isVisible="true" isUpstreamVisible="true" lacing="Shortest" isSelectedInput="False">
      <ID value="a8b0f382-e8bc-4198-93af-a93c1afcf265" />
      <Name value="bv Remove Nulls" />
      <Description value="forked from Lunchbox" />
      <Inputs>
        <Input value="List" />
      </Inputs>
      <Outputs>
        <Output value="Cleaned" />
      </Outputs>
    </Dynamo.Nodes.Function>
    <Dynamo.Nodes.DSFunction guid="6a380aca-da6f-437d-82fc-158ac34ba5e6" type="Dynamo.Nodes.DSFunction" nickname="StructuralFraming.ColumnByCurve" x="1172.2715054608" y="1499.23836475712" isVisible="true" isUpstreamVisible="true" lacing="Shortest" isSelectedInput="False" assembly="RevitNodes.dll" function="Revit.Elements.StructuralFraming.ColumnByCurve@Autodesk.DesignScript.Geometry.Curve,Revit.Elements.Level,Revit.Elements.FamilySymbol" />
    <Dynamo.Nodes.CodeBlockNodeModel guid="fac5a40a-77b2-4de4-af8c-7a082d6891c2" type="Dynamo.Nodes.CodeBlockNodeModel" nickname="Code Block" x="-44.2621899506797" y="1358.18003351894" isVisible="true" isUpstreamVisible="true" lacing="Disabled" isSelectedInput="False" CodeText="a[8];" ShouldFocus="false" />
    <DSRevitNodesUI.Levels guid="d20b35ce-6759-44bf-8ade-c2623522ae44" type="DSRevitNodesUI.Levels" nickname="Levels" x="-44.2621899506797" y="1638.60580318237" isVisible="true" isUpstreamVisible="true" lacing="Disabled" isSelectedInput="True" index="4:G00 - ENTRANCE" />
    <DSRevitNodesUI.StructuralColumnTypes guid="72b61969-6842-4421-a30d-1ca0678bde5f" type="DSRevitNodesUI.StructuralColumnTypes" nickname="Structural Column Types" x="-44.2621899506797" y="1937.54581487819" isVisible="true" isUpstreamVisible="true" lacing="Disabled" isSelectedInput="True" index="0:1000 x 1000mm" />
    <DSIronPythonNode.PythonNode guid="c880adb7-3613-4b3b-92a9-67177d6133e8" type="DSIronPythonNode.PythonNode" nickname="Python Script" x="536.202065468705" y="1324.9899589237" isVisible="true" isUpstreamVisible="true" lacing="Disabled" isSelectedInput="False" inputcount="4">
      <Script>#Copyright 2016. All rights reserved. Bimorph Consultancy LTD, 5 St Johns Lane, London EC1M 4BH www.bimorph.co.uk
#Written by Thomas Mahon @Thomas__Mahon info@bimorph.co.uk package: bimorphNodes
#GitHub: https://github.com/ThomasMahon/bimorphNodes/

import clr

# Import DocumentManager and TransactionManager
clr.AddReference("RevitServices")
import RevitServices
from RevitServices.Persistence import DocumentManager
from RevitServices.Transactions import TransactionManager
from System.Collections.Generic import *

clr.AddReference("RevitNodes")
import Revit
# Import ToProtoType, ToRevitType geometry conversion extension methods
clr.ImportExtensions(Revit.GeometryConversion)

# Import RevitAPI
clr.AddReference("RevitAPI")
import Autodesk
from Autodesk.Revit.DB import *

doc = DocumentManager.Instance.CurrentDBDocument
uiapp = DocumentManager.Instance.CurrentUIApplication
app = uiapp.Application

importDWG = UnwrapElement(IN[0])
nameOfLayersToImport = IN[1]
revitModelLines = IN[2]

if nameOfLayersToImport == None or nameOfLayersToImport == []: 
	catSub = importDWG.Category.SubCategories
	enum = catSub.GetEnumerator()
	
	nameOfLayersToImport = []
	while enum.MoveNext():
		layerName = enum.Current.Name
		nameOfLayersToImport.Add( layerName )

if isinstance(nameOfLayersToImport, list):
	layerList = nameOfLayersToImport
else:
	layerList = [nameOfLayersToImport]

def storageDictionary(crvListDict, eleGraphicStyleName, e):
	if eleGraphicStyleName in crvListDict.keys(): 
		crvListDict[eleGraphicStyleName].append( e )
	else:
		crvListDict[eleGraphicStyleName] = []
		crvListDict[eleGraphicStyleName].append( e )
		
	
def curveConversion (crv, revitModelLines, crvObject, refPlane):
	if revitModelLines == True:
		crv.Add( doc.Create.NewModelCurve( crvObject, refPlane) )
	else:
		crv.Add( crvObject.ToProtoType() )
	
TransactionManager.Instance.EnsureInTransaction(doc)

geomEnum = importDWG.Geometry[ Options() ].GetEnumerator()

crvListDict = dict()
failedFilter = []
while geomEnum.MoveNext(): 
	instGeom = geomEnum.Current.GetInstanceGeometry()
	
	instGeomEnum = instGeom.GetEnumerator()
	while instGeomEnum.MoveNext():
		e = instGeomEnum.Current
		try:
			graphicStyleId = e.GraphicsStyleId
					
			eleGraphicStyle = doc.GetElement(graphicStyleId)
			eleGraphicStyleName = eleGraphicStyle.GraphicsStyleCategory.Name
			
			
			if eleGraphicStyleName in layerList: 
				storageDictionary(crvListDict, eleGraphicStyleName, e)

		except:
			try: 
				vol = e.Volume
				
				if vol == 0.0: 
					edgesList = e.Edges
					edgesEnum = edgesList.GetEnumerator()

					while edgesEnum.MoveNext():
						edge = edgesEnum.Current
						eleGraphicStyle = doc.GetElement(edge.GraphicsStyleId)
						eleGraphicStyleName = eleGraphicStyle.GraphicsStyleCategory.Name
						
						if eleGraphicStyleName in layerList:
							storageDictionary(crvListDict, eleGraphicStyleName, edge.AsCurve() )
							
			except: 
				failedFilter.Add(e)

if "2015" in app.VersionName:
	levelParam = "Base Level"
else:
	levelParam = BuiltInParameter.IMPORT_BASE_LEVEL

levelId = UnwrapElement(IN[3]).Id

pln = SketchPlane.Create(doc, levelId )
	
crvList = [ crv for crv in crvListDict.values() ] 

failedConversion = []
modelLines =  []
for subList in crvList: 
	crv = []
	for i in subList: 
		try:
			crvType = i.GetType()
			if crvType != Autodesk.Revit.DB.PolyLine:
				curveConversion(crv, revitModelLines, i, pln)
			else: 
				pt = i.GetCoordinates()
				count = i.NumberOfCoordinates
					
				for j in range(count-1): 
					ln = Line.CreateBound(pt[j], pt[j+1])
					curveConversion(crv, revitModelLines, ln, pln)
						
		except: 
			failedConversion.Add( i )
				
	modelLines.Add(crv)

TransactionManager.Instance.TransactionTaskDone()

OUT = modelLines, crvListDict.keys()</Script>
    </DSIronPythonNode.PythonNode>
    <DSCoreNodesUI.BoolSelector guid="47ba6003-24aa-4123-a5a0-6e6c1afdea18" type="DSCoreNodesUI.BoolSelector" nickname="Boolean" x="244.338046002004" y="1455.32851647683" isVisible="true" isUpstreamVisible="true" lacing="Disabled" isSelectedInput="True">
      <System.Boolean>False</System.Boolean>
    </DSCoreNodesUI.BoolSelector>
    <Dynamo.Nodes.CodeBlockNodeModel guid="55c8668b-cf50-4a8f-9193-863ac422c7b3" type="Dynamo.Nodes.CodeBlockNodeModel" nickname="Code Block" x="941.947373191861" y="1463.36058005354" isVisible="true" isUpstreamVisible="true" lacing="Disabled" isSelectedInput="False" CodeText="Flatten(a[0]);" ShouldFocus="false" />
    <Dynamo.Nodes.DSFunction guid="403e05b7-f4f4-4207-8a31-f9af67ced0de" type="Dynamo.Nodes.DSFunction" nickname="Element.SetParameterByName" x="2572.76681161447" y="411.03790852129" isVisible="true" isUpstreamVisible="true" lacing="Shortest" isSelectedInput="False" assembly="RevitNodes.dll" function="Revit.Elements.Element.SetParameterByName@string,var" />
    <Dynamo.Nodes.CodeBlockNodeModel guid="ec19179a-c78b-42b2-b0f0-3f37a39b17ec" type="Dynamo.Nodes.CodeBlockNodeModel" nickname="Code Block" x="2196.30789704874" y="544.965931919856" isVisible="true" isUpstreamVisible="true" lacing="Disabled" isSelectedInput="True" CodeText="&quot;Comments&quot;;" ShouldFocus="false" />
  </Elements>
  <Connectors>
    <Dynamo.Models.ConnectorModel start="0509eed7-e5b9-43a9-aaf4-53d8da7ee443" start_index="0" end="c2364a2a-d433-4b4e-b442-8871f4319553" end_index="0" portType="0" />
    <Dynamo.Models.ConnectorModel start="0509eed7-e5b9-43a9-aaf4-53d8da7ee443" start_index="0" end="82ae8341-4028-4330-91cf-58a2361cd83b" end_index="0" portType="0" />
    <Dynamo.Models.ConnectorModel start="0509eed7-e5b9-43a9-aaf4-53d8da7ee443" start_index="0" end="c880adb7-3613-4b3b-92a9-67177d6133e8" end_index="0" portType="0" />
    <Dynamo.Models.ConnectorModel start="1c522a25-6af4-46aa-b350-60727ce727a5" start_index="0" end="403e05b7-f4f4-4207-8a31-f9af67ced0de" end_index="0" portType="0" />
    <Dynamo.Models.ConnectorModel start="c2364a2a-d433-4b4e-b442-8871f4319553" start_index="0" end="5f71bf5c-ce48-4c57-b912-8a28cf6497cc" end_index="0" portType="0" />
    <Dynamo.Models.ConnectorModel start="5f71bf5c-ce48-4c57-b912-8a28cf6497cc" start_index="0" end="82ae8341-4028-4330-91cf-58a2361cd83b" end_index="1" portType="0" />
    <Dynamo.Models.ConnectorModel start="5f71bf5c-ce48-4c57-b912-8a28cf6497cc" start_index="0" end="403e05b7-f4f4-4207-8a31-f9af67ced0de" end_index="2" portType="0" />
    <Dynamo.Models.ConnectorModel start="789a48f6-aa1d-42e8-b96e-4e1887c6125d" start_index="0" end="82ae8341-4028-4330-91cf-58a2361cd83b" end_index="2" portType="0" />
    <Dynamo.Models.ConnectorModel start="82ae8341-4028-4330-91cf-58a2361cd83b" start_index="0" end="8a2817fd-301b-40ab-9d2e-f35a92bbfb85" end_index="0" portType="0" />
    <Dynamo.Models.ConnectorModel start="7478bc31-c70e-4d79-ac7f-9a6d7c30c98f" start_index="0" end="82ae8341-4028-4330-91cf-58a2361cd83b" end_index="3" portType="0" />
    <Dynamo.Models.ConnectorModel start="7478bc31-c70e-4d79-ac7f-9a6d7c30c98f" start_index="0" end="1c522a25-6af4-46aa-b350-60727ce727a5" end_index="1" portType="0" />
    <Dynamo.Models.ConnectorModel start="8a2817fd-301b-40ab-9d2e-f35a92bbfb85" start_index="0" end="1c522a25-6af4-46aa-b350-60727ce727a5" end_index="0" portType="0" />
    <Dynamo.Models.ConnectorModel start="18de7573-ca20-46ca-8b51-c6a2f4e3c68a" start_index="0" end="2055fd68-2ee3-491a-96d0-23d9a6e001d7" end_index="0" portType="0" />
    <Dynamo.Models.ConnectorModel start="18de7573-ca20-46ca-8b51-c6a2f4e3c68a" start_index="0" end="8df92d03-7b04-4e9e-ba43-2a3b6663d227" end_index="0" portType="0" />
    <Dynamo.Models.ConnectorModel start="6d4e7ada-0520-4b82-94f5-1aa76132d53a" start_index="0" end="8df92d03-7b04-4e9e-ba43-2a3b6663d227" end_index="1" portType="0" />
    <Dynamo.Models.ConnectorModel start="33713f69-9823-4171-beb6-5861f0d8f442" start_index="0" end="6d4e7ada-0520-4b82-94f5-1aa76132d53a" end_index="1" portType="0" />
    <Dynamo.Models.ConnectorModel start="ad82c5f5-5d85-495c-bf5b-6ebcb6d6e061" start_index="0" end="6d4e7ada-0520-4b82-94f5-1aa76132d53a" end_index="2" portType="0" />
    <Dynamo.Models.ConnectorModel start="2055fd68-2ee3-491a-96d0-23d9a6e001d7" start_index="0" end="e9a48d91-ace3-4dbf-b8bf-25d393245e76" end_index="0" portType="0" />
    <Dynamo.Models.ConnectorModel start="8df92d03-7b04-4e9e-ba43-2a3b6663d227" start_index="0" end="1c522a25-6af4-46aa-b350-60727ce727a5" end_index="2" portType="0" />
    <Dynamo.Models.ConnectorModel start="e9a48d91-ace3-4dbf-b8bf-25d393245e76" start_index="0" end="6d4e7ada-0520-4b82-94f5-1aa76132d53a" end_index="0" portType="0" />
    <Dynamo.Models.ConnectorModel start="fac5a40a-77b2-4de4-af8c-7a082d6891c2" start_index="0" end="c880adb7-3613-4b3b-92a9-67177d6133e8" end_index="1" portType="0" />
    <Dynamo.Models.ConnectorModel start="d20b35ce-6759-44bf-8ade-c2623522ae44" start_index="0" end="6a380aca-da6f-437d-82fc-158ac34ba5e6" end_index="1" portType="0" />
    <Dynamo.Models.ConnectorModel start="d20b35ce-6759-44bf-8ade-c2623522ae44" start_index="0" end="c880adb7-3613-4b3b-92a9-67177d6133e8" end_index="3" portType="0" />
    <Dynamo.Models.ConnectorModel start="72b61969-6842-4421-a30d-1ca0678bde5f" start_index="0" end="6a380aca-da6f-437d-82fc-158ac34ba5e6" end_index="2" portType="0" />
    <Dynamo.Models.ConnectorModel start="47ba6003-24aa-4123-a5a0-6e6c1afdea18" start_index="0" end="c880adb7-3613-4b3b-92a9-67177d6133e8" end_index="2" portType="0" />
    <Dynamo.Models.ConnectorModel start="55c8668b-cf50-4a8f-9193-863ac422c7b3" start_index="0" end="6a380aca-da6f-437d-82fc-158ac34ba5e6" end_index="0" portType="0" />
    <Dynamo.Models.ConnectorModel start="ec19179a-c78b-42b2-b0f0-3f37a39b17ec" start_index="0" end="403e05b7-f4f4-4207-8a31-f9af67ced0de" end_index="1" portType="0" />
  </Connectors>
  <Notes>
    <Dynamo.Models.NoteModel guid="b3076939-e8b1-4d67-83ba-d8e884991f57" text=" " x="-497.26479442008" y="310.363372692117" />
    <Dynamo.Models.NoteModel guid="ccfd37d5-de67-4636-9376-2cfe6ce12f4f" text=" " x="753.896811225889" y="1441.27397609356" />
    <Dynamo.Models.NoteModel guid="e4b712d8-749a-4c94-a11a-8a74ae602d09" text=" " x="1409.10553103242" y="440.094899313593" />
  </Notes>
  <Annotations>
    <Dynamo.Models.AnnotationModel guid="896d81bb-4ff0-4cdd-a6b4-d9b55f516f5c" annotationText="SELECT IMPORTED DWG" left="-710.561298211667" top="166.462584415606" width="273.296503791587" height="187.900788276511" fontSize="36" InitialTop="262.462584415606" InitialHeight="124" TextblockHeight="86" backgrouund="#FFD4B6DB">
      <Models ModelGuid="0509eed7-e5b9-43a9-aaf4-53d8da7ee443" />
      <Models ModelGuid="b3076939-e8b1-4d67-83ba-d8e884991f57" />
    </Dynamo.Models.AnnotationModel>
    <Dynamo.Models.AnnotationModel guid="fae2a2da-c7d8-450f-959f-6a7f30554cb4" annotationText="FROM biMORPH PACKAGE" left="526.202065468705" top="1228.9899589237" width="287.694745757185" height="256.284017169861" fontSize="36" InitialTop="1324.9899589237" InitialHeight="201" TextblockHeight="86" backgrouund="#FFD8D8D8">
      <Models ModelGuid="c880adb7-3613-4b3b-92a9-67177d6133e8" />
      <Models ModelGuid="ccfd37d5-de67-4636-9376-2cfe6ce12f4f" />
    </Dynamo.Models.AnnotationModel>
    <Dynamo.Models.AnnotationModel guid="1f9020e0-188c-4165-9459-7dd0352c1511" annotationText="SELECT LAYER" left="-54.2621899506797" top="1262.18003351894" width="124" height="189" fontSize="36" InitialTop="1358.18003351894" InitialHeight="123" TextblockHeight="86" backgrouund="#FFD4B6DB">
      <Models ModelGuid="fac5a40a-77b2-4de4-af8c-7a082d6891c2" />
    </Dynamo.Models.AnnotationModel>
    <Dynamo.Models.AnnotationModel guid="0f10f4c4-8c4a-4da4-97b3-8bbd10cf64b8" annotationText="SELECT COLUMN TYPE" left="-54.2621899506797" top="1797.54581487819" width="233" height="233" fontSize="36" InitialTop="1937.54581487819" InitialHeight="123" TextblockHeight="130" backgrouund="#FFD4B6DB">
      <Models ModelGuid="72b61969-6842-4421-a30d-1ca0678bde5f" />
    </Dynamo.Models.AnnotationModel>
    <Dynamo.Models.AnnotationModel guid="4384ffa9-6116-4d7c-8cb1-b03264adf170" annotationText="SELECT LEVEL" left="-54.2621899506797" top="1542.60580318237" width="187" height="189" fontSize="36" InitialTop="1638.60580318237" InitialHeight="123" TextblockHeight="86" backgrouund="#FFD4B6DB">
      <Models ModelGuid="d20b35ce-6759-44bf-8ade-c2623522ae44" />
    </Dynamo.Models.AnnotationModel>
    <Dynamo.Models.AnnotationModel guid="93690a18-18f4-4e84-a134-caa48fe5cf6b" annotationText="PLACE COLUMNS" left="931.947373191861" top="1410.36058005354" width="558.324132268935" height="233.877784703577" fontSize="36" InitialTop="1463.36058005354" InitialHeight="210.877784703577" TextblockHeight="43" backgrouund="#FFFFC999">
      <Models ModelGuid="6a380aca-da6f-437d-82fc-158ac34ba5e6" />
      <Models ModelGuid="55c8668b-cf50-4a8f-9193-863ac422c7b3" />
    </Dynamo.Models.AnnotationModel>
    <Dynamo.Models.AnnotationModel guid="2e630b93-1457-4e18-880d-ae94f88fa0ae" annotationText="TYPE BEAM SIZE" left="-54.2621899506797" top="747.696335575537" width="141" height="208" fontSize="36" InitialTop="887.696335575537" InitialHeight="98" TextblockHeight="130" backgrouund="#FFD4B6DB">
      <Models ModelGuid="33713f69-9823-4171-beb6-5861f0d8f442" />
    </Dynamo.Models.AnnotationModel>
    <Dynamo.Models.AnnotationModel guid="b00cb10e-e4e6-407d-ae9f-cf45eebb3952" annotationText="RETRIEVE THE SELECTED BEAM " left="475.310163274404" top="675.860757459399" width="1467.28730169919" height="316.466404678778" fontSize="36" InitialTop="728.860757459399" InitialHeight="293.466404678778" TextblockHeight="43" backgrouund="#FFD8D8D8">
      <Models ModelGuid="18de7573-ca20-46ca-8b51-c6a2f4e3c68a" />
      <Models ModelGuid="6d4e7ada-0520-4b82-94f5-1aa76132d53a" />
      <Models ModelGuid="ad82c5f5-5d85-495c-bf5b-6ebcb6d6e061" />
      <Models ModelGuid="2055fd68-2ee3-491a-96d0-23d9a6e001d7" />
      <Models ModelGuid="8df92d03-7b04-4e9e-ba43-2a3b6663d227" />
      <Models ModelGuid="e9a48d91-ace3-4dbf-b8bf-25d393245e76" />
    </Dynamo.Models.AnnotationModel>
    <Dynamo.Models.AnnotationModel guid="01505e4d-4e87-42f7-8451-18aedc9177cc" annotationText="SELECT LEVEL" left="-54.2621899506797" top="526.130305937832" width="187" height="189" fontSize="36" InitialTop="622.130305937832" InitialHeight="123" TextblockHeight="86" backgrouund="#FFD4B6DB">
      <Models ModelGuid="7478bc31-c70e-4d79-ac7f-9a6d7c30c98f" />
    </Dynamo.Models.AnnotationModel>
    <Dynamo.Models.AnnotationModel guid="20901649-1360-4fa0-9c49-e98012e57799" annotationText="SELECT LAYER" left="-54.26218995068" top="341.949180912708" width="320.954165784789" height="149.382796777537" fontSize="36" InitialTop="394.949180912708" InitialHeight="129.099405960775" TextblockHeight="43" backgrouund="#FFD4B6DB">
      <Models ModelGuid="c2364a2a-d433-4b4e-b442-8871f4319553" />
      <Models ModelGuid="5f71bf5c-ce48-4c57-b912-8a28cf6497cc" />
    </Dynamo.Models.AnnotationModel>
    <Dynamo.Models.AnnotationModel guid="43ed501d-20b2-4bc8-95d8-3230881baba3" annotationText="PLACE BEAMS" left="2105.56822575914" top="268.858651099039" width="692.198585855331" height="369.107280820817" fontSize="36" InitialTop="321.858651099039" InitialHeight="346.107280820817" TextblockHeight="43" backgrouund="#FFFFC999">
      <Models ModelGuid="1c522a25-6af4-46aa-b350-60727ce727a5" />
      <Models ModelGuid="403e05b7-f4f4-4207-8a31-f9af67ced0de" />
      <Models ModelGuid="ec19179a-c78b-42b2-b0f0-3f37a39b17ec" />
    </Dynamo.Models.AnnotationModel>
    <Dynamo.Models.AnnotationModel guid="98347488-b935-4c1f-93a2-2a5f12b729f7" annotationText="FROM biMORPH PACKAGE" left="1160.13769659692" top="222.901882723442" width="308.967834435509" height="261.193016590151" fontSize="36" InitialTop="318.901882723442" InitialHeight="201" TextblockHeight="86" backgrouund="#FFD8D8D8">
      <Models ModelGuid="82ae8341-4028-4330-91cf-58a2361cd83b" />
      <Models ModelGuid="e4b712d8-749a-4c94-a11a-8a74ae602d09" />
    </Dynamo.Models.AnnotationModel>
  </Annotations>
  <Presets />
  <Cameras>
    <Camera Name="background_preview" eyeX="101.315123267083" eyeY="52.0459351614688" eyeZ="-56.0992484475935" lookX="-12.2086184950471" lookY="-14.3191487215304" lookZ="-20.7261228004114" />
  </Cameras>
</Workspace>