<Workspace Version="1.0.0.1180" X="-3042.55622734279" Y="495.651819700609" zoom="0.719651525494462" Name="Home" Description="" RunType="Manual" RunPeriod="1000" HasRunWithoutCrash="True">
  <NamespaceResolutionMap>
    <ClassMap partialName="Vector" resolvedName="Autodesk.DesignScript.Geometry.Vector" assemblyName="ProtoGeometry.dll" />
    <ClassMap partialName="Plane.z" resolvedName="Autodesk.DesignScript.Geometry.Plane" assemblyName="ProtoGeometry.dll" />
    <ClassMap partialName="Plane.s" resolvedName="Autodesk.DesignScript.Geometry.Plane" assemblyName="ProtoGeometry.dll" />
    <ClassMap partialName="BoundingBox.ToCuboid" resolvedName="Autodesk.DesignScript.Geometry.BoundingBox" assemblyName="ProtoGeometry.dll" />
    <ClassMap partialName="Autodesk" resolvedName="Autodesk.DesignScript.Geometry.Point" assemblyName="ProtoGeometry.dll" />
  </NamespaceResolutionMap>
  <Elements>
    <Dynamo.Nodes.DSModelElementSelection guid="ec49b068-41ce-4b74-9a67-8d56f8099d1e" type="Dynamo.Nodes.DSModelElementSelection" nickname="Select Ref Plane Destination" x="4475.46292909284" y="455.155621970688" isVisible="true" isUpstreamVisible="true" lacing="Disabled" isSelectedInput="True" IsFrozen="false" isPinned="false">
      <instance id="8c1f7f2e-006f-4b2f-9450-ebf586fb170a-00003915" />
    </Dynamo.Nodes.DSModelElementSelection>
    <Dynamo.Graph.Nodes.ZeroTouch.DSFunction guid="9c24cfb9-665a-4bd4-b1c6-5fee992c5da0" type="Dynamo.Graph.Nodes.ZeroTouch.DSFunction" nickname="ReferencePlane.Plane" x="4706.48992024357" y="452.714831621331" isVisible="true" isUpstreamVisible="true" lacing="Shortest" isSelectedInput="False" IsFrozen="false" isPinned="false" assembly="RevitNodes.dll" function="Revit.Elements.ReferencePlane.Plane" />
    <Dynamo.Nodes.DSModelElementSelection guid="a81e15ff-d81e-4ed8-bee1-f3db314a072d" type="Dynamo.Nodes.DSModelElementSelection" nickname="Select MEP Element" x="4449.18092080988" y="127.44348105888" isVisible="true" isUpstreamVisible="true" lacing="Disabled" isSelectedInput="True" IsFrozen="false" isPinned="false">
      <instance id="627a6546-5ccb-47d6-a494-f3b651327776-00003879" />
    </Dynamo.Nodes.DSModelElementSelection>
    <Dynamo.Graph.Nodes.ZeroTouch.DSFunction guid="c840f614-dc19-4249-a807-a7ff65db3901" type="Dynamo.Graph.Nodes.ZeroTouch.DSFunction" nickname="FamilyInstance.Location" x="4716.26664187846" y="-16.1213535463026" isVisible="true" isUpstreamVisible="true" lacing="Shortest" isSelectedInput="False" IsFrozen="false" isPinned="false" assembly="RevitNodes.dll" function="Revit.Elements.FamilyInstance.Location" />
    <Dynamo.Graph.Nodes.CustomNodes.Function guid="0fee2bc3-6c67-4a0a-8efa-34013a26a514" type="Dynamo.Graph.Nodes.CustomNodes.Function" nickname="Element.SetLocation" x="5443.51124825583" y="180.928305528321" isVisible="true" isUpstreamVisible="true" lacing="Shortest" isSelectedInput="False" IsFrozen="false" isPinned="false">
      <ID value="bac5c146-7610-4c0b-a9b1-7a7aeb13bb2b" />
      <Name value="Element.SetLocation" />
      <Description value="Attempts to modify the location of the input element. This can effectively add as a move comand in Revit. Works for both line based and point based elements." />
      <Inputs>
        <Input value="element(s)" />
        <Input value="location(s)" />
      </Inputs>
      <Outputs>
        <Output value="element(s)" />
      </Outputs>
    </Dynamo.Graph.Nodes.CustomNodes.Function>
    <Dynamo.Graph.Nodes.ZeroTouch.DSFunction guid="9219e84c-6104-428d-8c8e-b5b7a69f154c" type="Dynamo.Graph.Nodes.ZeroTouch.DSFunction" nickname="Point.Add" x="5297.99947629201" y="-9.62282442429756" isVisible="true" isUpstreamVisible="true" lacing="Shortest" isSelectedInput="False" IsFrozen="false" isPinned="false" assembly="ProtoGeometry.dll" function="Autodesk.DesignScript.Geometry.Point.Add@Autodesk.DesignScript.Geometry.Vector" />
    <Dynamo.Graph.Nodes.ZeroTouch.DSFunction guid="ce6f114e-c5d8-4198-acab-4aaa98717d2a" type="Dynamo.Graph.Nodes.ZeroTouch.DSFunction" nickname="Vector.ByCoordinates" x="5113.069976552" y="-10.7593242559066" isVisible="true" isUpstreamVisible="true" lacing="Shortest" isSelectedInput="False" IsFrozen="false" isPinned="false" assembly="ProtoGeometry.dll" function="Autodesk.DesignScript.Geometry.Vector.ByCoordinates@double,double,double">
      <PortInfo index="0" default="True" />
      <PortInfo index="1" default="True" />
      <PortInfo index="2" default="True" />
    </Dynamo.Graph.Nodes.ZeroTouch.DSFunction>
    <Dynamo.Graph.Nodes.CodeBlockNodeModel guid="ddb412d3-1cfb-42d9-ad2c-8a802db1a28b" type="Dynamo.Graph.Nodes.CodeBlockNodeModel" nickname="Code Block" x="4979.03741754666" y="45.3105705805122" isVisible="true" isUpstreamVisible="true" lacing="Disabled" isSelectedInput="False" IsFrozen="false" isPinned="false" CodeText="0;" ShouldFocus="false" />
    <Dynamo.Graph.Nodes.CodeBlockNodeModel guid="604dcd8c-ec20-4c19-b188-d1874971c8cb" type="Dynamo.Graph.Nodes.CodeBlockNodeModel" nickname="Code Block" x="5007.34014983155" y="347.620780614714" isVisible="true" isUpstreamVisible="true" lacing="Disabled" isSelectedInput="False" IsFrozen="false" isPinned="false" CodeText="sfCr1=sf.Location;&#xA;sfCr2=Flatten(sfCr1&lt;1&gt;.Project(Pln,Vector.ZAxis()));&#xA;ofSt1=(sfCr2.Z)-(sfCr1.Z);&#xA;sf.SetParameterByName(&quot;Offset&quot;,ofSt1);" ShouldFocus="false" />
    <Dynamo.Nodes.DSModelElementSelection guid="7beb044a-24b8-4ad7-883d-c0140f4b0bf3" type="Dynamo.Nodes.DSModelElementSelection" nickname="Select MEP Element" x="4664.04312725282" y="332.617503448736" isVisible="true" isUpstreamVisible="true" lacing="Disabled" isSelectedInput="True" IsFrozen="false" isPinned="false">
      <instance id="8c1f7f2e-006f-4b2f-9450-ebf586fb170a-0000399e" />
    </Dynamo.Nodes.DSModelElementSelection>
    <Dynamo.Graph.Nodes.ZeroTouch.DSFunction guid="e23084e2-4138-439d-a462-1d170119cd78" type="Dynamo.Graph.Nodes.ZeroTouch.DSFunction" nickname="Element.SetParameterByName" x="4965.83846749721" y="-364.250048543391" isVisible="true" isUpstreamVisible="true" lacing="Shortest" isSelectedInput="False" IsFrozen="false" isPinned="false" assembly="RevitNodes.dll" function="Revit.Elements.Element.SetParameterByName@string,var" />
    <Dynamo.Nodes.DSModelElementSelection guid="235f5c07-ad09-4a64-970e-126d798e0a27" type="Dynamo.Nodes.DSModelElementSelection" nickname="Select MEP Element" x="4548.70818505703" y="-439.660832327551" isVisible="true" isUpstreamVisible="true" lacing="Disabled" isSelectedInput="True" IsFrozen="false" isPinned="false">
      <instance id="8c1f7f2e-006f-4b2f-9450-ebf586fb170a-000040f4" />
    </Dynamo.Nodes.DSModelElementSelection>
    <Dynamo.Graph.Nodes.CodeBlockNodeModel guid="5b9ee77d-d551-4cb8-8a94-d4d90c5d82a1" type="Dynamo.Graph.Nodes.CodeBlockNodeModel" nickname="Code Block" x="4596.68611528936" y="-311.142249561577" isVisible="true" isUpstreamVisible="true" lacing="Disabled" isSelectedInput="False" IsFrozen="false" isPinned="false" CodeText="&quot;Level&quot;;" ShouldFocus="false" />
    <Dynamo.Graph.Nodes.CodeBlockNodeModel guid="b6e0f624-3629-413b-af7a-700c796f02d5" type="Dynamo.Graph.Nodes.CodeBlockNodeModel" nickname="Code Block" x="4799" y="-117" isVisible="true" isUpstreamVisible="true" lacing="Disabled" isSelectedInput="False" IsFrozen="false" isPinned="false" CodeText="0;" ShouldFocus="false" />
    <DSRevitNodesUI.Levels guid="4970ad80-5929-4b19-96b6-8b77e78b0856" type="DSRevitNodesUI.Levels" nickname="Levels" x="4502.82820075822" y="-181.363912545983" isVisible="true" isUpstreamVisible="true" lacing="Disabled" isSelectedInput="True" IsFrozen="false" isPinned="false" index="0:Level 3" />
  </Elements>
  <Connectors>
    <Dynamo.Graph.Connectors.ConnectorModel start="ec49b068-41ce-4b74-9a67-8d56f8099d1e" start_index="0" end="9c24cfb9-665a-4bd4-b1c6-5fee992c5da0" end_index="0" portType="0" />
    <Dynamo.Graph.Connectors.ConnectorModel start="9c24cfb9-665a-4bd4-b1c6-5fee992c5da0" start_index="0" end="604dcd8c-ec20-4c19-b188-d1874971c8cb" end_index="1" portType="0" />
    <Dynamo.Graph.Connectors.ConnectorModel start="a81e15ff-d81e-4ed8-bee1-f3db314a072d" start_index="0" end="0fee2bc3-6c67-4a0a-8efa-34013a26a514" end_index="0" portType="0" />
    <Dynamo.Graph.Connectors.ConnectorModel start="a81e15ff-d81e-4ed8-bee1-f3db314a072d" start_index="0" end="c840f614-dc19-4249-a807-a7ff65db3901" end_index="0" portType="0" />
    <Dynamo.Graph.Connectors.ConnectorModel start="c840f614-dc19-4249-a807-a7ff65db3901" start_index="0" end="9219e84c-6104-428d-8c8e-b5b7a69f154c" end_index="0" portType="0" />
    <Dynamo.Graph.Connectors.ConnectorModel start="9219e84c-6104-428d-8c8e-b5b7a69f154c" start_index="0" end="0fee2bc3-6c67-4a0a-8efa-34013a26a514" end_index="1" portType="0" />
    <Dynamo.Graph.Connectors.ConnectorModel start="ce6f114e-c5d8-4198-acab-4aaa98717d2a" start_index="0" end="9219e84c-6104-428d-8c8e-b5b7a69f154c" end_index="1" portType="0" />
    <Dynamo.Graph.Connectors.ConnectorModel start="ddb412d3-1cfb-42d9-ad2c-8a802db1a28b" start_index="0" end="ce6f114e-c5d8-4198-acab-4aaa98717d2a" end_index="2" portType="0" />
    <Dynamo.Graph.Connectors.ConnectorModel start="7beb044a-24b8-4ad7-883d-c0140f4b0bf3" start_index="0" end="604dcd8c-ec20-4c19-b188-d1874971c8cb" end_index="0" portType="0" />
    <Dynamo.Graph.Connectors.ConnectorModel start="235f5c07-ad09-4a64-970e-126d798e0a27" start_index="0" end="e23084e2-4138-439d-a462-1d170119cd78" end_index="0" portType="0" />
    <Dynamo.Graph.Connectors.ConnectorModel start="5b9ee77d-d551-4cb8-8a94-d4d90c5d82a1" start_index="0" end="e23084e2-4138-439d-a462-1d170119cd78" end_index="1" portType="0" />
    <Dynamo.Graph.Connectors.ConnectorModel start="4970ad80-5929-4b19-96b6-8b77e78b0856" start_index="0" end="e23084e2-4138-439d-a462-1d170119cd78" end_index="2" portType="0" />
  </Connectors>
  <Notes />
  <Annotations />
  <Presets />
  <Cameras>
    <Camera Name="Background Preview" eyeX="1238.77697753906" eyeY="486.272064208984" eyeZ="-2036.86462402344" lookX="346.74853515625" lookY="-375.644256591797" lookZ="-1675.95129394531" upX="0" upY="1" upZ="0" />
  </Cameras>
</Workspace>