<Workspace Version="0.8.2.2392" X="742.811500985347" Y="-629.75597023369" zoom="0.949648495888348" Name="Home" Description="" RunType="Manual" RunPeriod="1000" HasRunWithoutCrash="True">
  <NamespaceResolutionMap />
  <Elements>
    <DSIronPythonNode.PythonNode guid="e70ca3f9-32e0-4313-910f-2db54d410f27" type="DSIronPythonNode.PythonNode" nickname="Python Script" x="411.2327836678" y="480.154667618189" isVisible="true" isUpstreamVisible="true" lacing="Disabled" isSelectedInput="False" inputcount="1">
      <Script>import clr
clr.AddReference("ProtoGeometry")
from Autodesk.DesignScript.Geometry import *
# Import RevitAPI
clr.AddReference("RevitAPI")
from Autodesk.Revit.DB import *
clr.AddReference("RevitAPIUI")
from Autodesk.Revit.UI import TaskDialog
# Import DocumentManager and TransactionManager
clr.AddReference("RevitServices")
from RevitServices.Persistence import DocumentManager
from RevitServices.Transactions import TransactionManager
# Import ToProtoType, ToRevitType geometry conversion extension methods
clr.AddReference("RevitNodes")
import Revit
clr.ImportExtensions(Revit.GeometryConversion)


list = UnwrapElement(IN[0])

family = []

for l in list:
	try:
		a = l.Symbol.Family.IsInPlace
		family.append(a)
	except:
		family.append(False)

#Assign your output to the OUT variable.
OUT = family</Script>
    </DSIronPythonNode.PythonNode>
    <DSRevitNodesUI.ElementsInView guid="1369a21d-7068-4048-8a56-872bc56972f2" type="DSRevitNodesUI.ElementsInView" nickname="All Elements In Active View" x="114.478389413026" y="338.839162958897" isVisible="true" isUpstreamVisible="true" lacing="Disabled" isSelectedInput="True" />
    <Dynamo.Nodes.DSFunction guid="28f261cc-ce01-4cf0-9919-f8f9afda21fd" type="Dynamo.Nodes.DSFunction" nickname="Element.OverrideColorInView" x="954.185257299109" y="414.634475487851" isVisible="true" isUpstreamVisible="true" lacing="Shortest" isSelectedInput="False" assembly="RevitNodes.dll" function="Revit.Elements.Element.OverrideColorInView@DSCore.Color" />
    <Dynamo.Nodes.DSFunction guid="7d87339f-a6a6-444d-a1d6-e888ddf9836b" type="Dynamo.Nodes.DSFunction" nickname="List.FilterByBoolMask" x="650.953144123181" y="337.694984085004" isVisible="true" isUpstreamVisible="true" lacing="Shortest" isSelectedInput="False" assembly="DSCoreNodes.dll" function="DSCore.List.FilterByBoolMask@var[]..[],var[]..[]" />
    <Dynamo.Nodes.DSFunction guid="8c403be7-068f-406e-a8d7-bb95f6c6b9a8" type="Dynamo.Nodes.DSFunction" nickname="Color.ByARGB" x="800.327613317116" y="533.233148120648" isVisible="true" isUpstreamVisible="true" lacing="Shortest" isSelectedInput="False" assembly="DSCoreNodes.dll" function="DSCore.Color.ByARGB@int,int,int,int">
      <PortInfo index="0" default="True" />
      <PortInfo index="1" default="True" />
      <PortInfo index="2" default="True" />
      <PortInfo index="3" default="True" />
    </Dynamo.Nodes.DSFunction>
    <Dynamo.Nodes.CodeBlockNodeModel guid="238d76b9-9521-4f58-b7ea-b15ef8c95426" type="Dynamo.Nodes.CodeBlockNodeModel" nickname="Code Block" x="631" y="609" isVisible="true" isUpstreamVisible="true" lacing="Disabled" isSelectedInput="True" CodeText="255;" ShouldFocus="false" />
    <DSIronPythonNode.PythonNode guid="b573d996-bd7c-4f7a-abe0-47a275aba1e8" type="DSIronPythonNode.PythonNode" nickname="Python Script" x="452.807056733931" y="924.331709004799" isVisible="true" isUpstreamVisible="true" lacing="Disabled" isSelectedInput="False" inputcount="1">
      <Script>import clr
clr.AddReference("ProtoGeometry")
from Autodesk.DesignScript.Geometry import *
# Import RevitAPI
clr.AddReference("RevitAPI")
from Autodesk.Revit.DB import *
clr.AddReference("RevitAPIUI")
from Autodesk.Revit.UI import TaskDialog
# Import DocumentManager and TransactionManager
clr.AddReference("RevitServices")
from RevitServices.Persistence import DocumentManager
from RevitServices.Transactions import TransactionManager
# Import ToProtoType, ToRevitType geometry conversion extension methods
clr.AddReference("RevitNodes")
import Revit
clr.ImportExtensions(Revit.GeometryConversion)


list = UnwrapElement(IN[0])

a = list.Symbol.Family.IsInPlace
	
#Assign your output to the OUT variable.
OUT = list.Symbol, list.Symbol.Family, a</Script>
    </DSIronPythonNode.PythonNode>
    <Dynamo.Nodes.DSModelElementSelection guid="7db77701-edf6-454b-8a13-4401bf262b10" type="Dynamo.Nodes.DSModelElementSelection" nickname="Select Model Element" x="-166.539218749132" y="933.807159477105" isVisible="true" isUpstreamVisible="true" lacing="Disabled" isSelectedInput="True" />
    <DSIronPythonNode.PythonNode guid="c2857710-bd1a-4a4a-aeb2-506b112d2875" type="DSIronPythonNode.PythonNode" nickname="Python Script" x="889.093866635471" y="838.632820175593" isVisible="true" isUpstreamVisible="true" lacing="Disabled" isSelectedInput="False" inputcount="1">
      <Script>import clr
clr.AddReference("ProtoGeometry")
from Autodesk.DesignScript.Geometry import *
# Import RevitAPI
clr.AddReference("RevitAPI")
from Autodesk.Revit.DB import *
clr.AddReference("RevitAPIUI")
from Autodesk.Revit.UI import TaskDialog
# Import DocumentManager and TransactionManager
clr.AddReference("RevitServices")
from RevitServices.Persistence import DocumentManager
from RevitServices.Transactions import TransactionManager
# Import ToProtoType, ToRevitType geometry conversion extension methods
clr.AddReference("RevitNodes")
import Revit
clr.ImportExtensions(Revit.GeometryConversion)


list = UnwrapElement(IN[0])

family = []

for l in list:
	try:
		a = l.Symbol.Family
		family.append(a)
	except:
		family.append(False)

#Assign your output to the OUT variable.
OUT = family</Script>
    </DSIronPythonNode.PythonNode>
    <Dynamo.Nodes.DSFunction guid="36e0e51f-2d41-437f-af56-5032474321ca" type="Dynamo.Nodes.DSFunction" nickname="FamilySymbol.Family" x="407.113038758113" y="1209.17383195705" isVisible="true" isUpstreamVisible="true" lacing="Shortest" isSelectedInput="False" assembly="RevitNodes.dll" function="Revit.Elements.FamilySymbol.Family" />
    <Dynamo.Nodes.DSFunction guid="ab2f1121-285b-4337-adf9-542894dd79b1" type="Dynamo.Nodes.DSFunction" nickname="FamilyInstance.Symbol" x="98.340891820182" y="1208.2028503629" isVisible="true" isUpstreamVisible="true" lacing="Shortest" isSelectedInput="False" assembly="RevitNodes.dll" function="Revit.Elements.FamilyInstance.Symbol" />
    <DSIronPythonNode.PythonNode guid="7abf7c89-265d-4547-bcda-020166200360" type="DSIronPythonNode.PythonNode" nickname="Python Script" x="845.959888017271" y="1220.75228902918" isVisible="true" isUpstreamVisible="true" lacing="Disabled" isSelectedInput="False" inputcount="1">
      <Script>import clr
clr.AddReference("ProtoGeometry")
from Autodesk.DesignScript.Geometry import *
# Import RevitAPI
clr.AddReference("RevitAPI")
from Autodesk.Revit.DB import *
clr.AddReference("RevitAPIUI")
from Autodesk.Revit.UI import TaskDialog
# Import DocumentManager and TransactionManager
clr.AddReference("RevitServices")
from RevitServices.Persistence import DocumentManager
from RevitServices.Transactions import TransactionManager
# Import ToProtoType, ToRevitType geometry conversion extension methods
clr.AddReference("RevitNodes")
import Revit
clr.ImportExtensions(Revit.GeometryConversion)

doc = DocumentManager.Instance.CurrentDBDocument
uiapp = DocumentManager.Instance.CurrentUIApplication
app = uiapp.Application

list = UnwrapElement(IN[0])

a = list.IsInPlace

names = []

ids = [i.Id for i in doc.Settings.Categories]

result = doc.Settings.Categories

#Assign your output to the OUT variable.
OUT = a, result</Script>
    </DSIronPythonNode.PythonNode>
    <Dynamo.Nodes.DSFunction guid="280f5139-9083-4b35-932d-045419072a1d" type="Dynamo.Nodes.DSFunction" nickname="FamilySymbol.ByName" x="260.37473930394" y="1553.97472914482" isVisible="true" isUpstreamVisible="true" lacing="Shortest" isSelectedInput="False" assembly="RevitNodes.dll" function="Revit.Elements.FamilySymbol.ByName@string" />
    <Dynamo.Nodes.DSFunction guid="d4c27272-46e3-4dbc-a414-970772fa4a39" type="Dynamo.Nodes.DSFunction" nickname="FamilySymbol.Name" x="319.552388506107" y="1368.85490343547" isVisible="true" isUpstreamVisible="true" lacing="Shortest" isSelectedInput="False" assembly="RevitNodes.dll" function="Revit.Elements.FamilySymbol.Name" />
    <Dynamo.Nodes.CodeBlockNodeModel guid="acca4ac4-04b6-4403-8088-68c348acfba8" type="Dynamo.Nodes.CodeBlockNodeModel" nickname="Code Block" x="84.9073300236352" y="1565.47493362887" isVisible="true" isUpstreamVisible="true" lacing="Disabled" isSelectedInput="True" CodeText="&quot;a&quot;;" ShouldFocus="false" />
    <Dynamo.Nodes.DSFunction guid="04b5c803-f6e1-4b62-8502-635198fd1c61" type="Dynamo.Nodes.DSFunction" nickname="FamilyInstance.Symbol" x="-144.094483585885" y="1361.68743307175" isVisible="true" isUpstreamVisible="true" lacing="Shortest" isSelectedInput="False" assembly="RevitNodes.dll" function="Revit.Elements.FamilyInstance.Symbol" />
    <Dynamo.Nodes.CodeBlockNodeModel guid="d44fa42e-66a2-4151-867e-ecfaa11f6a0c" type="Dynamo.Nodes.CodeBlockNodeModel" nickname="Code Block" x="-390" y="1362" isVisible="true" isUpstreamVisible="true" lacing="Disabled" isSelectedInput="False" CodeText="a[0];" ShouldFocus="false" />
    <DSIronPythonNode.PythonNode guid="717f0427-05e7-4396-ac29-1639112625c1" type="DSIronPythonNode.PythonNode" nickname="Python Script" x="344.324053773521" y="1867.53114272609" isVisible="true" isUpstreamVisible="true" lacing="Disabled" isSelectedInput="False" inputcount="0">
      <Script>import clr
clr.AddReference("ProtoGeometry")
from Autodesk.DesignScript.Geometry import *
# Import RevitAPI
clr.AddReference("RevitAPI")
from Autodesk.Revit.DB import *
clr.AddReference("RevitAPIUI")
from Autodesk.Revit.UI import TaskDialog
# Import DocumentManager and TransactionManager
clr.AddReference("RevitServices")
from RevitServices.Persistence import DocumentManager
from RevitServices.Transactions import TransactionManager
# Import ToProtoType, ToRevitType geometry conversion extension methods
clr.AddReference("RevitNodes")
import Revit
clr.ImportExtensions(Revit.GeometryConversion)

doc = DocumentManager.Instance.CurrentDBDocument
uiapp = DocumentManager.Instance.CurrentUIApplication
app = uiapp.Application


names = []

ids = [i.Id for i in doc.Settings.Categories]

result = doc.Settings.Categories

collector = FilteredElementCollector(doc)

collector.OfClass(FamilySymbol)

#Assign your output to the OUT variable.
OUT = collector.ToElements()</Script>
    </DSIronPythonNode.PythonNode>
    <DSIronPythonNode.PythonNode guid="c64d51b6-516a-418a-b80e-a69a653a8049" type="DSIronPythonNode.PythonNode" nickname="Python Script" x="7.39426257751052" y="2149.55055084467" isVisible="true" isUpstreamVisible="true" lacing="Disabled" isSelectedInput="False" inputcount="2">
      <Script>import System
import clr
clr.AddReference('RevitAPI')
from Autodesk.Revit.DB import *

clr.AddReference("RevitServices")
import RevitServices
from RevitServices.Persistence import DocumentManager

doc = DocumentManager.Instance.CurrentDBDocument
famtypes = UnwrapElement(IN[0])

elementlist = list()
for ft in famtypes:
	collector = FilteredElementCollector(doc)
	bic = System.Enum.ToObject(BuiltInCategory, ft.Category.Id.IntegerValue)
	collector.OfCategory(bic)
	# This is a workaround
	# because I was to lazy to learn
	# how to implement LINQ in Python
	ftlist =  list()
	for item in collector.ToElements():
		if item.GetTypeId().IntegerValue == ft.Id.IntegerValue:
			ftlist.append(item)
	elementlist.append(ftlist)
OUT = elementlist</Script>
    </DSIronPythonNode.PythonNode>
    <DSIronPythonNode.PythonNode guid="08032575-1888-458f-9c54-ee37c84e330f" type="DSIronPythonNode.PythonNode" nickname="Python Script" x="673.824446644443" y="1981.27232977588" isVisible="true" isUpstreamVisible="true" lacing="Disabled" isSelectedInput="False" inputcount="1">
      <Script>import clr
clr.AddReference("ProtoGeometry")
from Autodesk.DesignScript.Geometry import *
# Import RevitAPI
clr.AddReference("RevitAPI")
from Autodesk.Revit.DB import *
clr.AddReference("RevitAPIUI")
from Autodesk.Revit.UI import TaskDialog
# Import DocumentManager and TransactionManager
clr.AddReference("RevitServices")
from RevitServices.Persistence import DocumentManager
from RevitServices.Transactions import TransactionManager
# Import ToProtoType, ToRevitType geometry conversion extension methods
clr.AddReference("RevitNodes")
import Revit
clr.ImportExtensions(Revit.GeometryConversion)


list = UnwrapElement(IN[0])

family = []

for l in list:
	try:
		a = l.Family.IsInPlace
		family.append(a)
	except:
		family.append(False)

#Assign your output to the OUT variable.
OUT = family</Script>
    </DSIronPythonNode.PythonNode>
    <Dynamo.Nodes.DSFunction guid="2ed7311a-8b65-4bfb-8468-4b0d0da0f83f" type="Dynamo.Nodes.DSFunction" nickname="List.FilterByBoolMask" x="1052.4743906433" y="1867.47330671646" isVisible="true" isUpstreamVisible="true" lacing="Shortest" isSelectedInput="False" assembly="DSCoreNodes.dll" function="DSCore.List.FilterByBoolMask@var[]..[],var[]..[]" />
    <Dynamo.Nodes.DSFunction guid="9e3ad522-baaa-4581-b119-3dc60efdcdce" type="Dynamo.Nodes.DSFunction" nickname="Element.OverrideColorInView" x="1741.29640637645" y="1990.61093237591" isVisible="true" isUpstreamVisible="true" lacing="Shortest" isSelectedInput="False" assembly="RevitNodes.dll" function="Revit.Elements.Element.OverrideColorInView@DSCore.Color" />
    <Dynamo.Nodes.DSFunction guid="5948d6b3-f884-4b35-aa26-912d1474c2ac" type="Dynamo.Nodes.DSFunction" nickname="Color.ByARGB" x="1234.38138004323" y="2053.00146453488" isVisible="true" isUpstreamVisible="true" lacing="Shortest" isSelectedInput="False" assembly="DSCoreNodes.dll" function="DSCore.Color.ByARGB@int,int,int,int">
      <PortInfo index="0" default="True" />
      <PortInfo index="1" default="True" />
      <PortInfo index="2" default="True" />
      <PortInfo index="3" default="True" />
    </Dynamo.Nodes.DSFunction>
    <Dynamo.Nodes.CodeBlockNodeModel guid="fd9be71e-7b7e-4f82-978b-4f16669300ff" type="Dynamo.Nodes.CodeBlockNodeModel" nickname="Code Block" x="1065.05376672612" y="2128.76831641423" isVisible="true" isUpstreamVisible="true" lacing="Disabled" isSelectedInput="True" CodeText="255;" ShouldFocus="false" />
    <DSIronPythonNode.PythonNode guid="9f518cc1-39a5-405a-90fe-404756ce02ba" type="DSIronPythonNode.PythonNode" nickname="Python Script" x="1329.93544608513" y="1727.37055191535" isVisible="true" isUpstreamVisible="true" lacing="Disabled" isSelectedInput="False" inputcount="2">
      <Script>import System
import clr
clr.AddReference('RevitAPI')
from Autodesk.Revit.DB import *

clr.AddReference("RevitServices")
import RevitServices
from RevitServices.Persistence import DocumentManager

doc = DocumentManager.Instance.CurrentDBDocument
famtypes = UnwrapElement(IN[0])

elementlist = list()

for ft in famtypes:
	collector = FilteredElementCollector(doc)
	bic = System.Enum.ToObject(BuiltInCategory, ft.Category.Id.IntegerValue)
	collector.OfCategory(bic)
	# This is a workaround
	# because I was to lazy to learn
	# how to implement LINQ in Python
	#ftlist =  list()
	for item in collector.ToElements():
		if item.GetTypeId().IntegerValue == ft.Id.IntegerValue:
			elementlist.append(item)
	#elementlist.append(ftlist)
OUT = elementlist</Script>
    </DSIronPythonNode.PythonNode>
  </Elements>
  <Connectors>
    <Dynamo.Models.ConnectorModel start="e70ca3f9-32e0-4313-910f-2db54d410f27" start_index="0" end="7d87339f-a6a6-444d-a1d6-e888ddf9836b" end_index="1" portType="0" />
    <Dynamo.Models.ConnectorModel start="1369a21d-7068-4048-8a56-872bc56972f2" start_index="0" end="e70ca3f9-32e0-4313-910f-2db54d410f27" end_index="0" portType="0" />
    <Dynamo.Models.ConnectorModel start="1369a21d-7068-4048-8a56-872bc56972f2" start_index="0" end="7d87339f-a6a6-444d-a1d6-e888ddf9836b" end_index="0" portType="0" />
    <Dynamo.Models.ConnectorModel start="1369a21d-7068-4048-8a56-872bc56972f2" start_index="0" end="c2857710-bd1a-4a4a-aeb2-506b112d2875" end_index="0" portType="0" />
    <Dynamo.Models.ConnectorModel start="1369a21d-7068-4048-8a56-872bc56972f2" start_index="0" end="d44fa42e-66a2-4151-867e-ecfaa11f6a0c" end_index="0" portType="0" />
    <Dynamo.Models.ConnectorModel start="7d87339f-a6a6-444d-a1d6-e888ddf9836b" start_index="0" end="28f261cc-ce01-4cf0-9919-f8f9afda21fd" end_index="0" portType="0" />
    <Dynamo.Models.ConnectorModel start="8c403be7-068f-406e-a8d7-bb95f6c6b9a8" start_index="0" end="28f261cc-ce01-4cf0-9919-f8f9afda21fd" end_index="1" portType="0" />
    <Dynamo.Models.ConnectorModel start="238d76b9-9521-4f58-b7ea-b15ef8c95426" start_index="0" end="8c403be7-068f-406e-a8d7-bb95f6c6b9a8" end_index="1" portType="0" />
    <Dynamo.Models.ConnectorModel start="7db77701-edf6-454b-8a13-4401bf262b10" start_index="0" end="b573d996-bd7c-4f7a-abe0-47a275aba1e8" end_index="0" portType="0" />
    <Dynamo.Models.ConnectorModel start="7db77701-edf6-454b-8a13-4401bf262b10" start_index="0" end="ab2f1121-285b-4337-adf9-542894dd79b1" end_index="0" portType="0" />
    <Dynamo.Models.ConnectorModel start="36e0e51f-2d41-437f-af56-5032474321ca" start_index="0" end="7abf7c89-265d-4547-bcda-020166200360" end_index="0" portType="0" />
    <Dynamo.Models.ConnectorModel start="ab2f1121-285b-4337-adf9-542894dd79b1" start_index="0" end="36e0e51f-2d41-437f-af56-5032474321ca" end_index="0" portType="0" />
    <Dynamo.Models.ConnectorModel start="acca4ac4-04b6-4403-8088-68c348acfba8" start_index="0" end="280f5139-9083-4b35-932d-045419072a1d" end_index="0" portType="0" />
    <Dynamo.Models.ConnectorModel start="04b5c803-f6e1-4b62-8502-635198fd1c61" start_index="0" end="d4c27272-46e3-4dbc-a414-970772fa4a39" end_index="0" portType="0" />
    <Dynamo.Models.ConnectorModel start="d44fa42e-66a2-4151-867e-ecfaa11f6a0c" start_index="0" end="04b5c803-f6e1-4b62-8502-635198fd1c61" end_index="0" portType="0" />
    <Dynamo.Models.ConnectorModel start="717f0427-05e7-4396-ac29-1639112625c1" start_index="0" end="08032575-1888-458f-9c54-ee37c84e330f" end_index="0" portType="0" />
    <Dynamo.Models.ConnectorModel start="717f0427-05e7-4396-ac29-1639112625c1" start_index="0" end="2ed7311a-8b65-4bfb-8468-4b0d0da0f83f" end_index="0" portType="0" />
    <Dynamo.Models.ConnectorModel start="08032575-1888-458f-9c54-ee37c84e330f" start_index="0" end="2ed7311a-8b65-4bfb-8468-4b0d0da0f83f" end_index="1" portType="0" />
    <Dynamo.Models.ConnectorModel start="2ed7311a-8b65-4bfb-8468-4b0d0da0f83f" start_index="0" end="9f518cc1-39a5-405a-90fe-404756ce02ba" end_index="0" portType="0" />
    <Dynamo.Models.ConnectorModel start="5948d6b3-f884-4b35-aa26-912d1474c2ac" start_index="0" end="9e3ad522-baaa-4581-b119-3dc60efdcdce" end_index="1" portType="0" />
    <Dynamo.Models.ConnectorModel start="fd9be71e-7b7e-4f82-978b-4f16669300ff" start_index="0" end="5948d6b3-f884-4b35-aa26-912d1474c2ac" end_index="1" portType="0" />
    <Dynamo.Models.ConnectorModel start="9f518cc1-39a5-405a-90fe-404756ce02ba" start_index="0" end="9e3ad522-baaa-4581-b119-3dc60efdcdce" end_index="0" portType="0" />
  </Connectors>
  <Notes />
  <Annotations>
    <Dynamo.Models.AnnotationModel guid="bbeb4b5a-e854-4d7a-a206-694152496ba9" annotationText="Is in Place?" left="401.2327836678" top="450.154667618189" width="144" height="123" fontSize="14" InitialTop="480.154667618189" InitialHeight="123" TextblockHeight="20" backgrouund="#FFC1D676">
      <Models ModelGuid="e70ca3f9-32e0-4313-910f-2db54d410f27" />
    </Dynamo.Models.AnnotationModel>
  </Annotations>
  <Presets />
  <Cameras>
    <Camera Name="background_preview" eyeX="10" eyeY="15" eyeZ="10" lookX="-10" lookY="-10" lookZ="-10" />
  </Cameras>
</Workspace>