<Workspace Version="0.8.2.2392" X="302.822052863683" Y="-1358.97874036266" zoom="0.895416984832867" Name="Home" Description="" RunType="Manual" RunPeriod="1000" HasRunWithoutCrash="True">
  <NamespaceResolutionMap />
  <Elements>
    <DSIronPythonNode.PythonNode guid="717f0427-05e7-4396-ac29-1639112625c1" type="DSIronPythonNode.PythonNode" nickname="Python Script" x="-34.7009250568309" y="1765.53554031638" isVisible="true" isUpstreamVisible="true" lacing="Disabled" isSelectedInput="False" inputcount="0">
      <Script>import clr
clr.AddReference("ProtoGeometry")
from Autodesk.DesignScript.Geometry import *
# Import RevitAPI
clr.AddReference("RevitAPI")
from Autodesk.Revit.DB import *
clr.AddReference("RevitAPIUI")
from Autodesk.Revit.UI import TaskDialog
# Import DocumentManager and TransactionManager
clr.AddReference("RevitServices")
from RevitServices.Persistence import DocumentManager
from RevitServices.Transactions import TransactionManager
# Import ToProtoType, ToRevitType geometry conversion extension methods
clr.AddReference("RevitNodes")
import Revit
clr.ImportExtensions(Revit.GeometryConversion)

doc = DocumentManager.Instance.CurrentDBDocument
uiapp = DocumentManager.Instance.CurrentUIApplication
app = uiapp.Application


names = []

collector = FilteredElementCollector(doc).OfClass(FamilySymbol)

#Assign your output to the OUT variable.
OUT = collector.ToElements()

"""
import System

import sys
pyt_path = r'C:\Program Files (x86)\IronPython 2.7\Lib'
sys.path.append(pyt_path)
"""


</Script>
    </DSIronPythonNode.PythonNode>
    <DSIronPythonNode.PythonNode guid="08032575-1888-458f-9c54-ee37c84e330f" type="DSIronPythonNode.PythonNode" nickname="Python Script" x="385.756532447482" y="1873.31717872266" isVisible="true" isUpstreamVisible="true" lacing="Disabled" isSelectedInput="False" inputcount="1">
      <Script>import clr
clr.AddReference("ProtoGeometry")
from Autodesk.DesignScript.Geometry import *
# Import RevitAPI
clr.AddReference("RevitAPI")
from Autodesk.Revit.DB import *
clr.AddReference("RevitAPIUI")
from Autodesk.Revit.UI import TaskDialog
# Import DocumentManager and TransactionManager
clr.AddReference("RevitServices")
from RevitServices.Persistence import DocumentManager
from RevitServices.Transactions import TransactionManager
# Import ToProtoType, ToRevitType geometry conversion extension methods
clr.AddReference("RevitNodes")
import Revit
clr.ImportExtensions(Revit.GeometryConversion)


list = UnwrapElement(IN[0])

family = []

for l in list:
	try:
		a = l.Family.IsInPlace
		family.append(a)
	except:
		family.append(False)

#Assign your output to the OUT variable.
OUT = family</Script>
    </DSIronPythonNode.PythonNode>
    <Dynamo.Nodes.DSFunction guid="2ed7311a-8b65-4bfb-8468-4b0d0da0f83f" type="Dynamo.Nodes.DSFunction" nickname="List.FilterByBoolMask" x="678.347022417725" y="1756.91029341995" isVisible="true" isUpstreamVisible="true" lacing="Shortest" isSelectedInput="False" assembly="DSCoreNodes.dll" function="DSCore.List.FilterByBoolMask@var[]..[],var[]..[]" />
    <Dynamo.Nodes.DSFunction guid="9e3ad522-baaa-4581-b119-3dc60efdcdce" type="Dynamo.Nodes.DSFunction" nickname="Element.OverrideColorInView" x="1867.57121224151" y="2225.04481693493" isVisible="true" isUpstreamVisible="true" lacing="Shortest" isSelectedInput="False" assembly="RevitNodes.dll" function="Revit.Elements.Element.OverrideColorInView@DSCore.Color" />
    <Dynamo.Nodes.DSFunction guid="5948d6b3-f884-4b35-aa26-912d1474c2ac" type="Dynamo.Nodes.DSFunction" nickname="Color.ByARGB" x="1471.97247938931" y="2290.65305664025" isVisible="true" isUpstreamVisible="true" lacing="Shortest" isSelectedInput="False" assembly="DSCoreNodes.dll" function="DSCore.Color.ByARGB@int,int,int,int">
      <PortInfo index="0" default="True" />
      <PortInfo index="1" default="True" />
      <PortInfo index="2" default="True" />
      <PortInfo index="3" default="True" />
    </Dynamo.Nodes.DSFunction>
    <Dynamo.Nodes.CodeBlockNodeModel guid="fd9be71e-7b7e-4f82-978b-4f16669300ff" type="Dynamo.Nodes.CodeBlockNodeModel" nickname="Code Block" x="1302.64486607219" y="2366.4199085196" isVisible="true" isUpstreamVisible="true" lacing="Disabled" isSelectedInput="True" CodeText="255;" ShouldFocus="false" />
    <DSIronPythonNode.PythonNode guid="9f518cc1-39a5-405a-90fe-404756ce02ba" type="DSIronPythonNode.PythonNode" nickname="Python Script" x="1021.75941330609" y="1755.6442458468" isVisible="true" isUpstreamVisible="true" lacing="Disabled" isSelectedInput="False" inputcount="2">
      <Script>import System
import clr
clr.AddReference('RevitAPI')
from Autodesk.Revit.DB import *

clr.AddReference("RevitServices")
import RevitServices
from RevitServices.Persistence import DocumentManager

doc = DocumentManager.Instance.CurrentDBDocument
famtypes = UnwrapElement(IN[0])

elementlist = list()

for ft in famtypes:
	collector = FilteredElementCollector(doc)
	bic = System.Enum.ToObject(BuiltInCategory, ft.Category.Id.IntegerValue)
	collector.OfCategory(bic)
	# This is a workaround
	# because I was to lazy to learn
	# how to implement LINQ in Python
	#ftlist =  list()
	for item in collector.ToElements():
		if item.GetTypeId().IntegerValue == ft.Id.IntegerValue:
			elementlist.append(item)
	#elementlist.append(ftlist)
OUT = elementlist</Script>
    </DSIronPythonNode.PythonNode>
    <DSIronPythonNode.PythonNode guid="1063c632-3a61-4f26-8df7-7f4d0d124e59" type="DSIronPythonNode.PythonNode" nickname="Python Script" x="434.708804736824" y="1577.12217391433" isVisible="true" isUpstreamVisible="true" lacing="Disabled" isSelectedInput="False" inputcount="1">
      <Script>import clr
clr.AddReference("ProtoGeometry")
from Autodesk.DesignScript.Geometry import *
# Import RevitAPI
clr.AddReference("RevitAPI")
from Autodesk.Revit.DB import *
clr.AddReference("RevitAPIUI")
from Autodesk.Revit.UI import TaskDialog
# Import DocumentManager and TransactionManager
clr.AddReference("RevitServices")
from RevitServices.Persistence import DocumentManager
from RevitServices.Transactions import TransactionManager
# Import ToProtoType, ToRevitType geometry conversion extension methods
clr.AddReference("RevitNodes")
import Revit
clr.ImportExtensions(Revit.GeometryConversion)

doc = DocumentManager.Instance.CurrentDBDocument
uiapp = DocumentManager.Instance.CurrentUIApplication
app = uiapp.Application

_linkDoc = IN[0]


names = []


collector = FilteredElementCollector(_linkDoc[0][0])

collector.OfClass(FamilySymbol)

#Assign your output to the OUT variable.
OUT = collector.ToElements()

"""
import System

import sys
pyt_path = r'C:\Program Files (x86)\IronPython 2.7\Lib'
sys.path.append(pyt_path)
"""


</Script>
    </DSIronPythonNode.PythonNode>
    <DSIronPythonNode.PythonNode guid="2efde688-f77a-4891-b141-bfa3c90072d2" type="DSIronPythonNode.PythonNode" nickname="Python Script" x="133.843875138747" y="1576.77498068192" isVisible="true" isUpstreamVisible="true" lacing="Disabled" isSelectedInput="False" inputcount="1">
      <Script>#Copyright(c) 2015, Konrad K Sobon
# @arch_laboratory, http://archi-lab.net

import clr
clr.AddReference('ProtoGeometry')
from Autodesk.DesignScript.Geometry import *

# Import DocumentManager and TransactionManager
clr.AddReference("RevitServices")
import RevitServices
from RevitServices.Persistence import DocumentManager
from RevitServices.Transactions import TransactionManager

from System.Collections.Generic import *

# Import RevitAPI
clr.AddReference("RevitAPI")
import Autodesk
from Autodesk.Revit.DB import *
from Autodesk.Revit.DB.Analysis import *

doc = DocumentManager.Instance.CurrentDBDocument
uiapp = DocumentManager.Instance.CurrentUIApplication
app = uiapp.Application

# Import ToDSType(bool) extension method
clr.AddReference("RevitNodes")
import Revit
clr.ImportExtensions(Revit.Elements)

#The inputs to this node will be stored as a list in the IN variable.
dataEnteringNode = IN

collector = Autodesk.Revit.DB.FilteredElementCollector(doc)
linkInstances = collector.OfClass(Autodesk.Revit.DB.RevitLinkInstance)

linkDoc, linkName = [], []
for i in linkInstances:
	linkDoc.append(i.GetLinkDocument())
	linkName.append(i.Name)


OUT = linkDoc, linkName, linkInstances</Script>
    </DSIronPythonNode.PythonNode>
    <Dynamo.Nodes.DSFunction guid="10d8a177-4c04-4c0b-9b1c-1aa8965421c5" type="Dynamo.Nodes.DSFunction" nickname="List.Empty" x="-6.97470222471401" y="1577.39813701273" isVisible="true" isUpstreamVisible="true" lacing="Shortest" isSelectedInput="False" assembly="DSCoreNodes.dll" function="DSCore.List.Empty" />
    <DSIronPythonNode.PythonNode guid="ea6c12fa-d20a-45de-92a6-131cab637406" type="DSIronPythonNode.PythonNode" nickname="Python Script" x="850.380836259208" y="2354.77372570975" isVisible="true" isUpstreamVisible="true" lacing="Disabled" isSelectedInput="False" inputcount="1">
      <Script>import System
import clr
clr.AddReference("ProtoGeometry")
from Autodesk.DesignScript.Geometry import *
# Import RevitAPI
clr.AddReference("RevitAPI")
from Autodesk.Revit.DB import *
clr.AddReference("RevitAPIUI")
from Autodesk.Revit.UI import TaskDialog
# Import DocumentManager and TransactionManager
clr.AddReference("RevitServices")
from RevitServices.Persistence import DocumentManager
from RevitServices.Transactions import TransactionManager
# Import ToProtoType, ToRevitType geometry conversion extension methods
clr.AddReference("RevitNodes")
import Revit
clr.ImportExtensions(Revit.GeometryConversion)

doc = DocumentManager.Instance.CurrentDBDocument
uiapp = DocumentManager.Instance.CurrentUIApplication
app = uiapp.Application

famtypes = UnwrapElement(IN[0])

elementlist = list()

collector = FilteredElementCollector(doc)

bic = System.Enum.ToObject(BuiltInCategory, -2000151)

collector.OfCategory(bic)

# Equivalent to:
#result = FilteredElementCollector(doc).OfCategory(BuiltInCategory.OST_GenericModel).ToElements()

resultIds = []

for item in collector:
	resultIds.append(item.GetTypeId())

#Assign your output to the OUT variable.
OUT = famtypes.Category.Id, collector.ToElements(), resultIds, famtypes.Id, </Script>
    </DSIronPythonNode.PythonNode>
    <DSIronPythonNode.PythonNode guid="f721d288-d7e7-4024-95d8-0a7a0b697c8c" type="DSIronPythonNode.PythonNode" nickname="Python Script" x="1036.84684214732" y="1985.49264660302" isVisible="true" isUpstreamVisible="true" lacing="Disabled" isSelectedInput="False" inputcount="2">
      <Script>import System
import clr
clr.AddReference('RevitAPI')
from Autodesk.Revit.DB import *

clr.AddReference("RevitServices")
import RevitServices
from RevitServices.Persistence import DocumentManager

doc = DocumentManager.Instance.CurrentDBDocument
famtypes = UnwrapElement(IN[0])

elementlist = list()

for ft in famtypes:
	collector = FilteredElementCollector(doc)
	bic = System.Enum.ToObject(BuiltInCategory, ft.Category.Id.IntegerValue)
	collector.OfCategory(bic)
	# This is a workaround
	# because I was to lazy to learn
	# how to implement LINQ in Python
	#ftlist =  list()
	for item in collector.ToElements():
		if item.GetTypeId().IntegerValue == ft.Id.IntegerValue:
			elementlist.append(item)
	#elementlist.append(ftlist)
OUT = elementlist</Script>
    </DSIronPythonNode.PythonNode>
    <DSIronPythonNode.PythonNode guid="f57248dd-eb31-478f-9dcb-551527e99025" type="DSIronPythonNode.PythonNode" nickname="Python Script" x="377.743128678935" y="1985.24361490337" isVisible="true" isUpstreamVisible="true" lacing="Disabled" isSelectedInput="False" inputcount="2">
      <Script>import System
import clr
clr.AddReference('RevitAPI')
from Autodesk.Revit.DB import *

clr.AddReference("RevitServices")
import RevitServices
from RevitServices.Persistence import DocumentManager

doc = DocumentManager.Instance.CurrentDBDocument
famtypes = UnwrapElement(IN[0])

elementlist = list()

for ft in famtypes:
	collector = FilteredElementCollector(doc)
	bic = System.Enum.ToObject(BuiltInCategory, ft.Category.Id.IntegerValue)
	collector.OfCategory(bic)
	# This is a workaround
	# because I was to lazy to learn
	# how to implement LINQ in Python
	#ftlist =  list()
	for item in collector.ToElements():
		if item.GetTypeId().IntegerValue == ft.Id.IntegerValue:
			elementlist.append(item)
	#elementlist.append(ftlist)
OUT = famtypes[0].Id</Script>
    </DSIronPythonNode.PythonNode>
    <Dynamo.Nodes.CodeBlockNodeModel guid="23fb59e9-9785-48d5-820b-969fa16a71a7" type="Dynamo.Nodes.CodeBlockNodeModel" nickname="Code Block" x="546.423373057864" y="2359.22755440402" isVisible="true" isUpstreamVisible="true" lacing="Disabled" isSelectedInput="False" CodeText="a[0];" ShouldFocus="false" />
    <Dynamo.Nodes.DSModelElementSelection guid="df8b01b8-d142-495e-b087-3f46e9f14029" type="Dynamo.Nodes.DSModelElementSelection" nickname="Select Model Element" x="-190.773746485909" y="2307.28116102051" isVisible="true" isUpstreamVisible="true" lacing="Disabled" isSelectedInput="True">
      <instance id="9f77675c-c23b-4c07-b5c5-3cd3a00d1fb1-000f8681" />
    </Dynamo.Nodes.DSModelElementSelection>
    <DSIronPythonNode.PythonNode guid="14959377-ef35-433b-a084-f0d30b23a3c6" type="DSIronPythonNode.PythonNode" nickname="Python Script" x="196.550467001117" y="2317.12761193964" isVisible="true" isUpstreamVisible="true" lacing="Disabled" isSelectedInput="False" inputcount="2">
      <Script>import System
import clr
clr.AddReference('RevitAPI')
from Autodesk.Revit.DB import *

clr.AddReference("RevitServices")
import RevitServices
from RevitServices.Persistence import DocumentManager

doc = DocumentManager.Instance.CurrentDBDocument
famtypes = UnwrapElement(IN[0])

elementlist = list()

for ft in famtypes:
	collector = FilteredElementCollector(doc)
	bic = System.Enum.ToObject(BuiltInCategory, ft.Category.Id.IntegerValue)
	collector.OfCategory(bic)
	# This is a workaround
	# because I was to lazy to learn
	# how to implement LINQ in Python
	#ftlist =  list()
	for item in collector.ToElements():
		if item.GetTypeId().IntegerValue == ft.Id.IntegerValue:
			elementlist.append(item)
	#elementlist.append(ftlist)
OUT = famtypes[0].Symbol</Script>
    </DSIronPythonNode.PythonNode>
    <Dynamo.Nodes.CodeBlockNodeModel guid="aba85b99-dd8d-4fc6-b0cf-2f15a4d66357" type="Dynamo.Nodes.CodeBlockNodeModel" nickname="Code Block" x="35" y="2308" isVisible="true" isUpstreamVisible="true" lacing="Disabled" isSelectedInput="False" CodeText="{a};" ShouldFocus="false" />
    <Dynamo.Nodes.CodeBlockNodeModel guid="48c397a9-2209-4c49-8d20-911274a88999" type="Dynamo.Nodes.CodeBlockNodeModel" nickname="Code Block" x="379.654174687577" y="2196.46223258922" isVisible="true" isUpstreamVisible="true" lacing="Disabled" isSelectedInput="False" CodeText="{a};" ShouldFocus="false" />
  </Elements>
  <Connectors>
    <Dynamo.Models.ConnectorModel start="717f0427-05e7-4396-ac29-1639112625c1" start_index="0" end="08032575-1888-458f-9c54-ee37c84e330f" end_index="0" portType="0" />
    <Dynamo.Models.ConnectorModel start="717f0427-05e7-4396-ac29-1639112625c1" start_index="0" end="2ed7311a-8b65-4bfb-8468-4b0d0da0f83f" end_index="0" portType="0" />
    <Dynamo.Models.ConnectorModel start="717f0427-05e7-4396-ac29-1639112625c1" start_index="0" end="f57248dd-eb31-478f-9dcb-551527e99025" end_index="0" portType="0" />
    <Dynamo.Models.ConnectorModel start="08032575-1888-458f-9c54-ee37c84e330f" start_index="0" end="2ed7311a-8b65-4bfb-8468-4b0d0da0f83f" end_index="1" portType="0" />
    <Dynamo.Models.ConnectorModel start="2ed7311a-8b65-4bfb-8468-4b0d0da0f83f" start_index="0" end="23fb59e9-9785-48d5-820b-969fa16a71a7" end_index="0" portType="0" />
    <Dynamo.Models.ConnectorModel start="5948d6b3-f884-4b35-aa26-912d1474c2ac" start_index="0" end="9e3ad522-baaa-4581-b119-3dc60efdcdce" end_index="1" portType="0" />
    <Dynamo.Models.ConnectorModel start="fd9be71e-7b7e-4f82-978b-4f16669300ff" start_index="0" end="5948d6b3-f884-4b35-aa26-912d1474c2ac" end_index="1" portType="0" />
    <Dynamo.Models.ConnectorModel start="9f518cc1-39a5-405a-90fe-404756ce02ba" start_index="0" end="9e3ad522-baaa-4581-b119-3dc60efdcdce" end_index="0" portType="0" />
    <Dynamo.Models.ConnectorModel start="2efde688-f77a-4891-b141-bfa3c90072d2" start_index="0" end="1063c632-3a61-4f26-8df7-7f4d0d124e59" end_index="0" portType="0" />
    <Dynamo.Models.ConnectorModel start="10d8a177-4c04-4c0b-9b1c-1aa8965421c5" start_index="0" end="2efde688-f77a-4891-b141-bfa3c90072d2" end_index="0" portType="0" />
    <Dynamo.Models.ConnectorModel start="23fb59e9-9785-48d5-820b-969fa16a71a7" start_index="0" end="ea6c12fa-d20a-45de-92a6-131cab637406" end_index="0" portType="0" />
    <Dynamo.Models.ConnectorModel start="df8b01b8-d142-495e-b087-3f46e9f14029" start_index="0" end="aba85b99-dd8d-4fc6-b0cf-2f15a4d66357" end_index="0" portType="0" />
    <Dynamo.Models.ConnectorModel start="14959377-ef35-433b-a084-f0d30b23a3c6" start_index="0" end="48c397a9-2209-4c49-8d20-911274a88999" end_index="0" portType="0" />
    <Dynamo.Models.ConnectorModel start="aba85b99-dd8d-4fc6-b0cf-2f15a4d66357" start_index="0" end="14959377-ef35-433b-a084-f0d30b23a3c6" end_index="0" portType="0" />
    <Dynamo.Models.ConnectorModel start="48c397a9-2209-4c49-8d20-911274a88999" start_index="0" end="9f518cc1-39a5-405a-90fe-404756ce02ba" end_index="0" portType="0" />
  </Connectors>
  <Notes />
  <Annotations>
    <Dynamo.Models.AnnotationModel guid="a675d670-65b0-43c7-9530-7c760951e498" annotationText="Select all the family types" left="-44.7009250568309" top="1721.53554031638" width="114" height="137" fontSize="14" InitialTop="1765.53554031638" InitialHeight="123" TextblockHeight="34" backgrouund="#FFC1D676">
      <Models ModelGuid="717f0427-05e7-4396-ac29-1639112625c1" />
    </Dynamo.Models.AnnotationModel>
    <Dynamo.Models.AnnotationModel guid="e534cb62-f244-4b42-b2c3-8fad40d734c8" annotationText="Check if they are in-place" left="375.756532447482" top="1829.31717872266" width="144" height="137" fontSize="14" InitialTop="1873.31717872266" InitialHeight="123" TextblockHeight="34" backgrouund="#FFC1D676">
      <Models ModelGuid="08032575-1888-458f-9c54-ee37c84e330f" />
    </Dynamo.Models.AnnotationModel>
    <Dynamo.Models.AnnotationModel guid="cbfea112-1f82-46a0-b7cf-5743cb4ff695" annotationText="These are the in-place elements" left="1011.75941330609" top="1711.6442458468" width="144" height="163" fontSize="14" InitialTop="1755.6442458468" InitialHeight="149" TextblockHeight="34" backgrouund="#FFC1D676">
      <Models ModelGuid="9f518cc1-39a5-405a-90fe-404756ce02ba" />
    </Dynamo.Models.AnnotationModel>
    <Dynamo.Models.AnnotationModel guid="d46d6d6b-aa44-4bbd-bfcb-a49e6625d5c7" annotationText="Family Types in linked file" left="-16.974702224714" top="1546.77498068192" width="585.683506961538" height="123.62315633081" fontSize="14" InitialTop="1576.77498068192" InitialHeight="123.623156330808" TextblockHeight="20" backgrouund="#FF48B9FF">
      <Models ModelGuid="1063c632-3a61-4f26-8df7-7f4d0d124e59" />
      <Models ModelGuid="2efde688-f77a-4891-b141-bfa3c90072d2" />
      <Models ModelGuid="10d8a177-4c04-4c0b-9b1c-1aa8965421c5" />
    </Dynamo.Models.AnnotationModel>
  </Annotations>
  <Presets />
  <Cameras>
    <Camera Name="background_preview" eyeX="10" eyeY="15" eyeZ="10" lookX="-10" lookY="-10" lookZ="-10" />
  </Cameras>
</Workspace>