<Workspace Version="1.3.1.1736" X="60.7982189907787" Y="-503.975536751949" zoom="0.899995643787958" ScaleFactor="1" Name="Home" Description="" RunType="Manual" RunPeriod="1000" HasRunWithoutCrash="True">
  <NamespaceResolutionMap />
  <Elements>
    <PythonNodeModels.PythonNode guid="08e43efd-1b44-4a8e-aade-f689395619fd" type="PythonNodeModels.PythonNode" nickname="Python Script" x="426.94384502766" y="1246.70626548379" isVisible="true" isUpstreamVisible="true" lacing="Disabled" isSelectedInput="False" IsFrozen="false" isPinned="true" inputcount="1">
      <PortInfo index="0" default="False" />
      <Script>import clr
clr.AddReference("ProtoGeometry")
from Autodesk.DesignScript.Geometry import *
# Import RevitAPI
clr.AddReference("RevitAPI")
from Autodesk.Revit.DB import *
clr.AddReference("RevitAPIUI")
from Autodesk.Revit.UI import TaskDialog
# Import DocumentManager and TransactionManager
clr.AddReference("RevitServices")
from RevitServices.Persistence import DocumentManager
from RevitServices.Transactions import TransactionManager
# Import ToProtoType, ToRevitType geometry conversion extension methods
clr.AddReference("RevitNodes")
import Revit
clr.ImportExtensions(Revit.GeometryConversion)

doc = DocumentManager.Instance.CurrentDBDocument
uiapp = DocumentManager.Instance.CurrentUIApplication
app = uiapp.Application

list = FilteredElementCollector(doc).OfClass(FamilySymbol).ToElements()

inPlaceFamily = []

for l in list:
	if l.Family.IsInPlace == True:
		inPlaceFamily.append(l)
	
#Assign your output to the OUT variable.
OUT = inPlaceFamily</Script>
    </PythonNodeModels.PythonNode>
    <Dynamo.Graph.Nodes.ZeroTouch.DSFunction guid="68e0eb7a-fc4c-420b-9e3d-d680998b3e0d" type="Dynamo.Graph.Nodes.ZeroTouch.DSFunction" nickname="FamilyInstance.ByFamilyType" x="696.453187896578" y="1246.2626183346" isVisible="true" isUpstreamVisible="true" lacing="Shortest" isSelectedInput="False" IsFrozen="false" isPinned="true" assembly="RevitNodes.dll" function="Revit.Elements.FamilyInstance.ByFamilyType@Revit.Elements.FamilyType">
      <PortInfo index="0" default="False" />
    </Dynamo.Graph.Nodes.ZeroTouch.DSFunction>
    <PythonNodeModels.PythonNode guid="45fb0e0f-3829-4b10-9b29-58ac5d2a2227" type="PythonNodeModels.PythonNode" nickname="Python Script" x="792.774997861939" y="1523.69491054244" isVisible="true" isUpstreamVisible="true" lacing="Disabled" isSelectedInput="False" IsFrozen="false" isPinned="false" inputcount="2">
      <PortInfo index="0" default="False" />
      <PortInfo index="1" default="False" />
      <Script>import System
import clr
clr.AddReference('RevitAPI')
from Autodesk.Revit.DB import *

clr.AddReference("RevitServices")
import RevitServices
from RevitServices.Persistence import DocumentManager

doc = DocumentManager.Instance.CurrentDBDocument
famtypes = UnwrapElement(IN[0])

elementlist = list()
for ft in famtypes:
	collector = FilteredElementCollector(doc)
	bic = System.Enum.ToObject(BuiltInCategory, ft.Category.Id.IntegerValue)
	collector.OfCategory(bic)
	# This is a workaround
	# because I was to lazy to learn
	# how to implement LINQ in Python
	ftlist =  list()
	for item in collector.ToElements():
		if item.GetTypeId().IntegerValue == ft.Id.IntegerValue:
			ftlist.append(item)
	elementlist.append(ftlist)
OUT = elementlist</Script>
    </PythonNodeModels.PythonNode>
    <Dynamo.Nodes.DSModelElementsSelection guid="cf4fdf41-ce9d-42cb-a392-d002f6ec38de" type="Dynamo.Nodes.DSModelElementsSelection" nickname="Select Model Elements" x="131.853384894162" y="857.947062034554" isVisible="true" isUpstreamVisible="true" lacing="Disabled" isSelectedInput="True" IsFrozen="false" isPinned="true">
      <instance id="8b4bfdac-77bd-4722-aa18-4077fb1dd520-0021f219" />
      <instance id="8b4bfdac-77bd-4722-aa18-4077fb1dd520-0021f257" />
      <instance id="8b4bfdac-77bd-4722-aa18-4077fb1dd520-0021f274" />
      <instance id="8b4bfdac-77bd-4722-aa18-4077fb1dd520-0021f2f6" />
      <instance id="8b4bfdac-77bd-4722-aa18-4077fb1dd520-0021f331" />
      <instance id="8b4bfdac-77bd-4722-aa18-4077fb1dd520-0021f377" />
    </Dynamo.Nodes.DSModelElementsSelection>
    <Dynamo.Graph.Nodes.ZeroTouch.DSFunction guid="26af6566-0adc-43da-be2a-ba8576c3fb27" type="Dynamo.Graph.Nodes.ZeroTouch.DSFunction" nickname="FamilyInstance.IsInPlace" x="570.170601034208" y="937.230666102215" isVisible="true" isUpstreamVisible="true" lacing="Shortest" isSelectedInput="False" IsFrozen="false" isPinned="true" assembly="..\AppData\Roaming\Dynamo\Dynamo Revit\1.3\packages\WombatDynamo\bin\WombatDynamo.dll" function="WombatDynamo.FamilyInstance.IsInPlace@Revit.Elements.FamilyInstance">
      <PortInfo index="0" default="False" />
    </Dynamo.Graph.Nodes.ZeroTouch.DSFunction>
    <CoreNodeModels.HigherOrder.Map guid="f9bb5885-10ff-44dd-846f-a0c684191a49" type="CoreNodeModels.HigherOrder.Map" nickname="List.Map" x="821.223210484258" y="858.984852901384" isVisible="true" isUpstreamVisible="true" lacing="Disabled" isSelectedInput="False" IsFrozen="false" isPinned="true">
      <PortInfo index="0" default="False" />
      <PortInfo index="1" default="False" />
    </CoreNodeModels.HigherOrder.Map>
    <Dynamo.Graph.Nodes.ZeroTouch.DSFunction guid="25589c94-6b5d-41e6-bf6d-264f414b2b28" type="Dynamo.Graph.Nodes.ZeroTouch.DSFunction" nickname="List.FilterByBoolMask" x="1091.34059457807" y="664.420479009379" isVisible="true" isUpstreamVisible="true" lacing="Shortest" isSelectedInput="False" IsFrozen="false" isPinned="true" assembly="DSCoreNodes.dll" function="DSCore.List.FilterByBoolMask@var[]..[],var[]..[]">
      <PortInfo index="0" default="False" />
      <PortInfo index="1" default="False" />
    </Dynamo.Graph.Nodes.ZeroTouch.DSFunction>
  </Elements>
  <Connectors>
    <Dynamo.Graph.Connectors.ConnectorModel start="08e43efd-1b44-4a8e-aade-f689395619fd" start_index="0" end="68e0eb7a-fc4c-420b-9e3d-d680998b3e0d" end_index="0" portType="0" />
    <Dynamo.Graph.Connectors.ConnectorModel start="cf4fdf41-ce9d-42cb-a392-d002f6ec38de" start_index="0" end="f9bb5885-10ff-44dd-846f-a0c684191a49" end_index="0" portType="0" />
    <Dynamo.Graph.Connectors.ConnectorModel start="cf4fdf41-ce9d-42cb-a392-d002f6ec38de" start_index="0" end="25589c94-6b5d-41e6-bf6d-264f414b2b28" end_index="0" portType="0" />
    <Dynamo.Graph.Connectors.ConnectorModel start="26af6566-0adc-43da-be2a-ba8576c3fb27" start_index="0" end="f9bb5885-10ff-44dd-846f-a0c684191a49" end_index="1" portType="0" />
    <Dynamo.Graph.Connectors.ConnectorModel start="f9bb5885-10ff-44dd-846f-a0c684191a49" start_index="0" end="25589c94-6b5d-41e6-bf6d-264f414b2b28" end_index="1" portType="0" />
  </Connectors>
  <Notes />
  <Annotations />
  <Presets />
  <Cameras>
    <Camera Name="Background Preview" eyeX="-17" eyeY="24" eyeZ="50" lookX="12" lookY="-13" lookZ="-58" upX="0" upY="1" upZ="0" />
  </Cameras>
</Workspace>