<Workspace Version="0.7.2.2921" X="30" Y="183.771604938272" zoom="1.25514403292181" Description="get the selection from the revit UI, works for views" Category="SteamNodes.Tool" Name="Tool.GetRevitSelection" ID="809a8e44-f6b5-42be-a349-4116e81be2cf">
  <Elements>
    <DSIronPythonNode.PythonNode type="DSIronPythonNode.PythonNode" guid="128ee2a6-30a3-4eb7-8cf2-70c965a3e403" nickname="Python Script" x="176" y="12" isVisible="true" isUpstreamVisible="true" lacing="Disabled" inputcount="1">
      <Script>#python nodes in dynamo 0.7
#proposed by Julien Benoit @jbenoit44 
#http://aecuandme.wordpress.com/
import clr
clr.AddReference('ProtoGeometry')
from Autodesk.DesignScript.Geometry import *
# Import ToDSType(bool) extension method
clr.AddReference("RevitNodes")
import Revit
clr.ImportExtensions(Revit.Elements)
# Import geometry conversion extension methods
clr.ImportExtensions(Revit.GeometryConversion)
# Import DocumentManager and TransactionManager
clr.AddReference("RevitServices")
import RevitServices
from RevitServices.Persistence import DocumentManager
from RevitServices.Transactions import TransactionManager
from System.Collections.Generic import *
# Import RevitAPI
clr.AddReference("RevitAPI")
import Autodesk
from Autodesk.Revit.DB import *

doc = DocumentManager.Instance.CurrentDBDocument
uiapp = DocumentManager.Instance.CurrentUIApplication
app = uiapp.Application

uidoc=DocumentManager.Instance.CurrentUIApplication.ActiveUIDocument


OUT=uidoc.Selection.Elements</Script>
    </DSIronPythonNode.PythonNode>
    <Dynamo.Nodes.DSFunction type="Dynamo.Nodes.DSFunction" guid="53f954d9-ead7-493a-9737-e1085e5276b9" nickname="List.Empty" x="0" y="0" isVisible="true" isUpstreamVisible="true" lacing="Shortest" assembly="DSCoreNodes.dll" function="DSCore.List.Empty" />
    <Dynamo.Nodes.Output type="Dynamo.Nodes.Output" guid="ad667404-ca1e-4d22-8648-37461a436138" nickname="Output" x="400" y="12" isVisible="true" isUpstreamVisible="true" lacing="Disabled">
      <Symbol value="Internal" />
    </Dynamo.Nodes.Output>
    <DSIronPythonNode.PythonNode type="DSIronPythonNode.PythonNode" guid="bd3a9fd3-46e2-4dc8-b22d-263c912ba126" nickname="Python Script" x="176" y="96" isVisible="true" isUpstreamVisible="true" lacing="Disabled" inputcount="1">
      <Script>#python nodes in dynamo 0.7
#proposed by Julien Benoit @jbenoit44 
#http://aecuandme.wordpress.com/
import clr
clr.AddReference('ProtoGeometry')
from Autodesk.DesignScript.Geometry import *
# Import ToDSType(bool) extension method
clr.AddReference("RevitNodes")
import Revit
clr.ImportExtensions(Revit.Elements)
# Import geometry conversion extension methods
clr.ImportExtensions(Revit.GeometryConversion)
# Import DocumentManager and TransactionManager
clr.AddReference("RevitServices")
import RevitServices
from RevitServices.Persistence import DocumentManager
from RevitServices.Transactions import TransactionManager
from System.Collections.Generic import *
# Import RevitAPI
clr.AddReference("RevitAPI")
import Autodesk
from Autodesk.Revit.DB import *

doc = DocumentManager.Instance.CurrentDBDocument
uiapp = DocumentManager.Instance.CurrentUIApplication
app = uiapp.Application
uidoc=DocumentManager.Instance.CurrentUIApplication.ActiveUIDocument

sel=[]
elt=[]

sel=uidoc.Selection.Elements

for i in sel:
	elt.append(i.ToDSType(False))

OUT=elt</Script>
    </DSIronPythonNode.PythonNode>
    <Dynamo.Nodes.DSFunction type="Dynamo.Nodes.DSFunction" guid="6e075927-03f4-46de-b303-b2890d9e0767" nickname="List.Empty" x="0" y="108" isVisible="true" isUpstreamVisible="true" lacing="Shortest" assembly="DSCoreNodes.dll" function="DSCore.List.Empty" />
    <Dynamo.Nodes.Output type="Dynamo.Nodes.Output" guid="0944495c-96b7-4a2e-b97e-b04f6b3e01e4" nickname="Output" x="400" y="96" isVisible="true" isUpstreamVisible="true" lacing="Disabled">
      <Symbol value="Element" />
    </Dynamo.Nodes.Output>
  </Elements>
  <Connectors>
    <Dynamo.Models.ConnectorModel start="128ee2a6-30a3-4eb7-8cf2-70c965a3e403" start_index="0" end="ad667404-ca1e-4d22-8648-37461a436138" end_index="0" portType="0" />
    <Dynamo.Models.ConnectorModel start="53f954d9-ead7-493a-9737-e1085e5276b9" start_index="0" end="128ee2a6-30a3-4eb7-8cf2-70c965a3e403" end_index="0" portType="0" />
    <Dynamo.Models.ConnectorModel start="bd3a9fd3-46e2-4dc8-b22d-263c912ba126" start_index="0" end="0944495c-96b7-4a2e-b97e-b04f6b3e01e4" end_index="0" portType="0" />
    <Dynamo.Models.ConnectorModel start="6e075927-03f4-46de-b303-b2890d9e0767" start_index="0" end="bd3a9fd3-46e2-4dc8-b22d-263c912ba126" end_index="0" portType="0" />
  </Connectors>
  <Notes />
</Workspace>