<Workspace Version="1.3.2.2480" X="278.209852761647" Y="-215.729907706565" zoom="1.06060772236021" ScaleFactor="1" Name="Home" Description="" RunType="Manual" RunPeriod="1000" HasRunWithoutCrash="True">
  <NamespaceResolutionMap />
  <Elements>
    <Dynamo.Nodes.DSModelElementsSelection guid="ca64be2b-c808-44cf-a019-a52e00143e2d" type="Dynamo.Nodes.DSModelElementsSelection" nickname="Select Model Elements" x="-111.728577337624" y="333.985700990345" isVisible="true" isUpstreamVisible="true" lacing="Disabled" isSelectedInput="True" IsFrozen="false" isPinned="false">
      <instance id="6b153bcd-9a1c-4509-9c36-a5f869a9d4a2-00321aa3" />
      <instance id="6b153bcd-9a1c-4509-9c36-a5f869a9d4a2-00321ab3" />
      <instance id="6b153bcd-9a1c-4509-9c36-a5f869a9d4a2-00321ac1" />
      <instance id="6b153bcd-9a1c-4509-9c36-a5f869a9d4a2-00321ad1" />
      <instance id="6b153bcd-9a1c-4509-9c36-a5f869a9d4a2-00321ae0" />
      <instance id="6b153bcd-9a1c-4509-9c36-a5f869a9d4a2-00321aee" />
      <instance id="6b153bcd-9a1c-4509-9c36-a5f869a9d4a2-00321afd" />
      <instance id="6b153bcd-9a1c-4509-9c36-a5f869a9d4a2-00321b10" />
    </Dynamo.Nodes.DSModelElementsSelection>
    <PythonNodeModels.PythonNode guid="4055a909-ac0e-4591-bac3-de35445edcbb" type="PythonNodeModels.PythonNode" nickname="Py - Miter" x="492.513937080168" y="533.857216720303" isVisible="true" isUpstreamVisible="true" lacing="Disabled" isSelectedInput="False" IsFrozen="false" isPinned="true" inputcount="1">
      <PortInfo index="0" default="False" />
      <Script>#Copyright(c) 2015, Dimitar Venkov
# @5devene, dimitar.ven@gmail.com

import clr

clr.AddReference("RevitServices")
import RevitServices
from RevitServices.Persistence import DocumentManager
from RevitServices.Transactions import TransactionManager
doc = DocumentManager.Instance.CurrentDBDocument
uidoc=DocumentManager.Instance.CurrentUIApplication.ActiveUIDocument

clr.AddReference("RevitNodes")
import Revit
clr.ImportExtensions(Revit.Elements)

clr.AddReference("RevitAPI")
from Autodesk.Revit.DB import ElementId
from Autodesk.Revit.DB.Structure import StructuralFramingUtils

clr.AddReference("System")
from System.Collections.Generic import List as cList


beams = UnwrapElement(IN[0])

ExUt = []

TransactionManager.Instance.EnsureInTransaction(doc)
for b in beams:
	ExUt = b.ExtensionUtility
	ExUt.set_Extended(0, True)
	ExUt.set_Extended(1, True)
	#StructuralFramingUtils.DisallowJoinAtEnd(b,0)
	#StructuralFramingUtils.DisallowJoinAtEnd(b,1)
ids1 = [e.Id for e in beams]
ids2 = cList[ElementId](ids1)
uidoc.Selection.SetElementIds(ids2)
OUT = "%s beams corrected in Revit." %ids2.Count
TransactionManager.Instance.TransactionTaskDone()</Script>
    </PythonNodeModels.PythonNode>
    <PythonNodeModels.PythonNode guid="dd13d6f8-8dde-40d4-a8fe-fb0210c084ed" type="PythonNodeModels.PythonNode" nickname="Py-Disallow Join" x="274" y="333.171433003218" isVisible="true" isUpstreamVisible="true" lacing="Disabled" isSelectedInput="False" IsFrozen="false" isPinned="true" inputcount="1">
      <PortInfo index="0" default="False" />
      <Script>#Copyright(c) 2015, Dimitar Venkov
# @5devene, dimitar.ven@gmail.com

import clr

clr.AddReference("RevitServices")
import RevitServices
from RevitServices.Persistence import DocumentManager
from RevitServices.Transactions import TransactionManager
doc = DocumentManager.Instance.CurrentDBDocument
uidoc=DocumentManager.Instance.CurrentUIApplication.ActiveUIDocument

clr.AddReference("RevitNodes")
import Revit
clr.ImportExtensions(Revit.Elements)

clr.AddReference("RevitAPI")
from Autodesk.Revit.DB import ElementId
from Autodesk.Revit.DB.Structure import StructuralFramingUtils

clr.AddReference("System")
from System.Collections.Generic import List as cList


beams = UnwrapElement(IN[0])

ExUt = []

TransactionManager.Instance.EnsureInTransaction(doc)
for b in beams:
	StructuralFramingUtils.DisallowJoinAtEnd(b,0)
	StructuralFramingUtils.DisallowJoinAtEnd(b,1)
ids1 = [e.Id for e in beams]
ids2 = cList[ElementId](ids1)
uidoc.Selection.SetElementIds(ids2)
OUT = "%s beams corrected in Revit." %ids2.Count
TransactionManager.Instance.TransactionTaskDone()</Script>
    </PythonNodeModels.PythonNode>
    <PythonNodeModels.PythonNode guid="135b8e86-e5be-4d6b-a171-3451d3d41340" type="PythonNodeModels.PythonNode" nickname="Py-Allow Join" x="493.513937080168" y="410.857216720303" isVisible="true" isUpstreamVisible="true" lacing="Disabled" isSelectedInput="False" IsFrozen="false" isPinned="true" inputcount="1">
      <PortInfo index="0" default="False" />
      <Script>#Copyright(c) 2015, Dimitar Venkov
# @5devene, dimitar.ven@gmail.com

import clr

clr.AddReference("RevitServices")
import RevitServices
from RevitServices.Persistence import DocumentManager
from RevitServices.Transactions import TransactionManager
doc = DocumentManager.Instance.CurrentDBDocument
uidoc=DocumentManager.Instance.CurrentUIApplication.ActiveUIDocument

clr.AddReference("RevitNodes")
import Revit
clr.ImportExtensions(Revit.Elements)

clr.AddReference("RevitAPI")
from Autodesk.Revit.DB import ElementId
from Autodesk.Revit.DB.Structure import StructuralFramingUtils

clr.AddReference("System")
from System.Collections.Generic import List as cList


beams = UnwrapElement(IN[0])

ExUt = []

TransactionManager.Instance.EnsureInTransaction(doc)
for b in beams:
	StructuralFramingUtils.AllowJoinAtEnd(b,0)
	StructuralFramingUtils.AllowJoinAtEnd(b,1)
ids1 = [e.Id for e in beams]
ids2 = cList[ElementId](ids1)
uidoc.Selection.SetElementIds(ids2)
OUT = "%s beams corrected in Revit." %ids2.Count
TransactionManager.Instance.TransactionTaskDone()</Script>
    </PythonNodeModels.PythonNode>
    <Dynamo.Graph.Nodes.CustomNodes.Function guid="1e7d067d-eaf2-4a27-bf83-7f2df081aed2" type="Dynamo.Graph.Nodes.CustomNodes.Function" nickname="StructuralFraming.DisallowJoins" x="91.2591386973519" y="559.801607313697" isVisible="true" isUpstreamVisible="true" lacing="Shortest" isSelectedInput="False" IsFrozen="false" isPinned="false">
      <PortInfo index="0" default="False" />
      <PortInfo index="1" default="False" />
      <PortInfo index="2" default="False" />
      <ID value="a84d257c-f38e-4d60-839e-50413d2ebc80" />
      <Name value="StructuralFraming.DisallowJoins" />
      <Description value="Disallow joins at start and/or end of selected Strucural Framing elements" />
      <Inputs>
        <Input value="elements" />
        <Input value="DisallowAtStart" />
        <Input value="DisallowAtEnd" />
      </Inputs>
      <Outputs>
        <Output value="elements" />
      </Outputs>
    </Dynamo.Graph.Nodes.CustomNodes.Function>
  </Elements>
  <Connectors>
    <Dynamo.Graph.Connectors.ConnectorModel start="ca64be2b-c808-44cf-a019-a52e00143e2d" start_index="0" end="dd13d6f8-8dde-40d4-a8fe-fb0210c084ed" end_index="0" portType="0" />
  </Connectors>
  <Notes />
  <Annotations />
  <Presets />
  <Cameras>
    <Camera Name="Background Preview" eyeX="-17" eyeY="24" eyeZ="50" lookX="12" lookY="-13" lookZ="-58" upX="0" upY="1" upZ="0" />
  </Cameras>
</Workspace>