<Workspace Version="0.8.2.2392" X="-1210" Y="38" zoom="1" Name="Home" Description="" RunType="Manual" RunPeriod="1000" HasRunWithoutCrash="True">
  <NamespaceResolutionMap>
    <ClassMap partialName="Vector" resolvedName="Autodesk.DesignScript.Geometry.Vector" assemblyName="ProtoGeometry.dll" />
  </NamespaceResolutionMap>
  <Elements>
    <Dynamo.Nodes.Function guid="660f1700-07af-4864-a1ed-4253cf3129e1" type="Dynamo.Nodes.Function" nickname="Pick Model Elements" x="425.5" y="444.5" isVisible="true" isUpstreamVisible="true" lacing="Shortest" isSelectedInput="False">
      <PortInfo index="0" default="True" />
      <ID value="affdb898-d7fc-43f3-9a38-f018ef2c2273" />
      <Name value="Pick Model Elements" />
      <Description value="This node offers a pick method for selecting elements in Revit." />
      <Inputs>
        <Input value="refresh" />
      </Inputs>
      <Outputs>
        <Output value="Elements" />
      </Outputs>
    </Dynamo.Nodes.Function>
    <Dynamo.Nodes.DSFunction guid="e1354225-e794-43f7-bb18-38fd74dae138" type="Dynamo.Nodes.DSFunction" nickname="StructuralFraming.Location" x="698.5" y="448.5" isVisible="true" isUpstreamVisible="true" lacing="Shortest" isSelectedInput="False" assembly="RevitNodes.dll" function="Revit.Elements.StructuralFraming.Location" />
    <Dynamo.Nodes.DSFunction guid="6b759268-5da5-40e7-9975-810fbdeda302" type="Dynamo.Nodes.DSFunction" nickname="Curve.StartPoint" x="991.5" y="403.5" isVisible="true" isUpstreamVisible="true" lacing="Shortest" isSelectedInput="False" assembly="ProtoGeometry.dll" function="Autodesk.DesignScript.Geometry.Curve.StartPoint" />
    <Dynamo.Nodes.DSFunction guid="6950dff1-2a3d-4834-8a77-3b44ce74f10b" type="Dynamo.Nodes.DSFunction" nickname="Curve.EndPoint" x="994.5" y="519.5" isVisible="true" isUpstreamVisible="true" lacing="Shortest" isSelectedInput="False" assembly="ProtoGeometry.dll" function="Autodesk.DesignScript.Geometry.Curve.EndPoint" />
    <Dynamo.Nodes.DSFunction guid="82dc46a4-b093-4836-bfcf-a9ecfa4bdb60" type="Dynamo.Nodes.DSFunction" nickname="Vector.AngleBetween" x="1519.5" y="430.5" isVisible="true" isUpstreamVisible="true" lacing="Shortest" isSelectedInput="False" assembly="ProtoGeometry.dll" function="Autodesk.DesignScript.Geometry.Vector.AngleBetween@Autodesk.DesignScript.Geometry.Vector" />
    <Dynamo.Nodes.DSFunction guid="4d02ab1b-ce5b-46b9-a8de-db28da1ebc50" type="Dynamo.Nodes.DSFunction" nickname="Vector.ByTwoPoints" x="1190.5" y="437.5" isVisible="true" isUpstreamVisible="true" lacing="Shortest" isSelectedInput="False" assembly="ProtoGeometry.dll" function="Autodesk.DesignScript.Geometry.Vector.ByTwoPoints@Autodesk.DesignScript.Geometry.Point,Autodesk.DesignScript.Geometry.Point" />
    <Dynamo.Nodes.CodeBlockNodeModel guid="cbebcdba-d419-4300-b92f-bf0061178358" type="Dynamo.Nodes.CodeBlockNodeModel" nickname="Code Block" x="1293" y="325" isVisible="true" isUpstreamVisible="true" lacing="Disabled" isSelectedInput="True" CodeText="Vector.ZAxis();" ShouldFocus="false" />
    <Dynamo.Nodes.CodeBlockNodeModel guid="7adc5b6b-ed39-4204-ae2c-5bd4691a6786" type="Dynamo.Nodes.CodeBlockNodeModel" nickname="Code Block" x="1772" y="442" isVisible="true" isUpstreamVisible="true" lacing="Disabled" isSelectedInput="False" CodeText="a-90;" ShouldFocus="false" />
    <Dynamo.Nodes.CodeBlockNodeModel guid="6d80a611-34e2-49de-8e43-9486a3f93e83" type="Dynamo.Nodes.CodeBlockNodeModel" nickname="Code Block" x="153" y="483" isVisible="true" isUpstreamVisible="true" lacing="Disabled" isSelectedInput="True" CodeText="1;" ShouldFocus="false" />
  </Elements>
  <Connectors>
    <Dynamo.Models.ConnectorModel start="660f1700-07af-4864-a1ed-4253cf3129e1" start_index="0" end="e1354225-e794-43f7-bb18-38fd74dae138" end_index="0" portType="0" />
    <Dynamo.Models.ConnectorModel start="e1354225-e794-43f7-bb18-38fd74dae138" start_index="0" end="6b759268-5da5-40e7-9975-810fbdeda302" end_index="0" portType="0" />
    <Dynamo.Models.ConnectorModel start="e1354225-e794-43f7-bb18-38fd74dae138" start_index="0" end="6950dff1-2a3d-4834-8a77-3b44ce74f10b" end_index="0" portType="0" />
    <Dynamo.Models.ConnectorModel start="6b759268-5da5-40e7-9975-810fbdeda302" start_index="0" end="4d02ab1b-ce5b-46b9-a8de-db28da1ebc50" end_index="0" portType="0" />
    <Dynamo.Models.ConnectorModel start="6950dff1-2a3d-4834-8a77-3b44ce74f10b" start_index="0" end="4d02ab1b-ce5b-46b9-a8de-db28da1ebc50" end_index="1" portType="0" />
    <Dynamo.Models.ConnectorModel start="82dc46a4-b093-4836-bfcf-a9ecfa4bdb60" start_index="0" end="7adc5b6b-ed39-4204-ae2c-5bd4691a6786" end_index="0" portType="0" />
    <Dynamo.Models.ConnectorModel start="4d02ab1b-ce5b-46b9-a8de-db28da1ebc50" start_index="0" end="82dc46a4-b093-4836-bfcf-a9ecfa4bdb60" end_index="1" portType="0" />
    <Dynamo.Models.ConnectorModel start="cbebcdba-d419-4300-b92f-bf0061178358" start_index="0" end="82dc46a4-b093-4836-bfcf-a9ecfa4bdb60" end_index="0" portType="0" />
    <Dynamo.Models.ConnectorModel start="6d80a611-34e2-49de-8e43-9486a3f93e83" start_index="0" end="660f1700-07af-4864-a1ed-4253cf3129e1" end_index="0" portType="0" />
  </Connectors>
  <Notes />
  <Annotations />
  <Presets />
  <Cameras>
    <Camera Name="background_preview" eyeX="10" eyeY="15" eyeZ="10" lookX="-10" lookY="-10" lookZ="-10" />
  </Cameras>
</Workspace>