<Workspace Version="1.2.0.2514" X="209.161614744692" Y="157.449726317895" zoom="0.18801750671569" Name="Home" Description="" RunType="Manual" RunPeriod="1000" HasRunWithoutCrash="True">
  <NamespaceResolutionMap>
    <ClassMap partialName="Curves.DeconstructPolyCurve" resolvedName="Geometry.Curves" assemblyName="LunchBox.dll" />
    <ClassMap partialName="Curves" resolvedName="Geometry.Curves" assemblyName="LunchBox.dll" />
    <ClassMap partialName="NurbsCurve" resolvedName="Autodesk.DesignScript.Geometry.NurbsCurve" assemblyName="ProtoGeometry.dll" />
    <ClassMap partialName="Autodesk.Curve" resolvedName="Autodesk.DesignScript.Geometry.Curve" assemblyName="ProtoGeometry.dll" />
    <ClassMap partialName="Autodesk.DesignScript.Geometry.Curve" resolvedName="Autodesk.DesignScript.Geometry.Curve" assemblyName="ProtoGeometry.dll" />
    <ClassMap partialName="NurbsCurve.ClosestPointTo" resolvedName="Autodesk.DesignScript.Geometry.NurbsCurve" assemblyName="ProtoGeometry.dll" />
    <ClassMap partialName="PolyCurve" resolvedName="Autodesk.DesignScript.Geometry.PolyCurve" assemblyName="ProtoGeometry.dll" />
    <ClassMap partialName="Circle" resolvedName="Autodesk.DesignScript.Geometry.Circle" assemblyName="ProtoGeometry.dll" />
    <ClassMap partialName="Plane" resolvedName="Autodesk.DesignScript.Geometry.Plane" assemblyName="ProtoGeometry.dll" />
    <ClassMap partialName="Vector.YAxis" resolvedName="Autodesk.DesignScript.Geometry.Vector" assemblyName="ProtoGeometry.dll" />
    <ClassMap partialName="Vector" resolvedName="Autodesk.DesignScript.Geometry.Vector" assemblyName="ProtoGeometry.dll" />
  </NamespaceResolutionMap>
  <Elements>
    <CoreNodeModels.Input.Filename guid="c02fa007-8b67-4692-aa4c-3c060d1c36f5" type="CoreNodeModels.Input.Filename" nickname="File Path" x="-468.5" y="330.5" isVisible="true" isUpstreamVisible="true" lacing="Disabled" isSelectedInput="True" IsFrozen="false" isPinned="false">
      <System.String>.\TrussExampleSetup.3dm</System.String>
      <HintPath>C:\Users\giovanni.brogioli\Documents\Dynamo\Scripts\PythonShell\TrussExampleSetup.3dm</HintPath>
    </CoreNodeModels.Input.Filename>
    <Dynamo.Graph.Nodes.ZeroTouch.DSFunction guid="618827f6-7fea-40c0-ae0c-856031c69923" type="Dynamo.Graph.Nodes.ZeroTouch.DSFunction" nickname="OpenRhino3dmModel.Get_RhinoFile" x="-152.103521150607" y="331.507441853218" isVisible="true" isUpstreamVisible="true" lacing="Shortest" isSelectedInput="False" IsFrozen="false" isPinned="true" assembly="..\..\..\..\AppData\Roaming\Dynamo\Dynamo%20Revit\1.2\packages\Rhynamo\bin\Rhynamo.dll" function="Interoperability.ReadRhino.OpenRhino3dmModel.Get_RhinoFile@var">
      <PortInfo index="0" default="False" />
    </Dynamo.Graph.Nodes.ZeroTouch.DSFunction>
    <Dynamo.Graph.Nodes.ZeroTouch.DSFunction guid="414f5f41-9fab-44ea-9858-928d1b3f26e5" type="Dynamo.Graph.Nodes.ZeroTouch.DSFunction" nickname="RhinoObject.Get_RhinoObjects" x="149.926673265546" y="334.049390866062" isVisible="true" isUpstreamVisible="true" lacing="Shortest" isSelectedInput="False" IsFrozen="false" isPinned="false" assembly="..\..\..\..\AppData\Roaming\Dynamo\Dynamo%20Revit\1.2\packages\Rhynamo\bin\Rhynamo.dll" function="Interoperability.ReadRhino.RhinoObject.Get_RhinoObjects@var">
      <PortInfo index="0" default="False" />
    </Dynamo.Graph.Nodes.ZeroTouch.DSFunction>
    <PythonNodeModels.PythonNode guid="d54eeed8-035c-461a-942b-02f155d9a1bf" type="PythonNodeModels.PythonNode" nickname="Python Script" x="1064.31504852698" y="415.641597223874" isVisible="true" isUpstreamVisible="true" lacing="Disabled" isSelectedInput="False" IsFrozen="false" isPinned="false" inputcount="4">
      <PortInfo index="0" default="False" />
      <PortInfo index="1" default="False" />
      <PortInfo index="2" default="False" />
      <PortInfo index="3" default="False" />
      <Script>import clr
clr.AddReference('ProtoGeometry')
from Autodesk.DesignScript.Geometry import *
import math
#The inputs to this node will be stored as a list in the IN variables.

crvRoof = IN[0]

crvFloor = IN[1]

subdiv = IN[2]

minHH = IN[3]

#DEFINING THE TRUSS NODES

crvLen = crvRoof.Length #Length of the Roof Curve

divisions = math.ceil(crvLen/subdiv)

newSubDiv = crvLen/divisions

ptsTop = []


for i in range(0, int(divisions)+1):
	ran = float(i*(1.0)/int(divisions))
	ptsTop.append(Curve.PointAtParameter(crvRoof,ran))


ptsBottom = [] #bottom chord nodes

error = "False" #define a check variable

for i in range(0,len(ptsTop)): #for each node of top chord
	#distance to ground found with the closest point
	param = (NurbsCurve.ClosestPointTo(crvFloor,ptsTop[i]))
	distance = (Geometry.DistanceTo(ptsTop[i],param))
	
	if distance &lt; minHH:
		#if the profile is too close to the terrain
		distance = "Profile too close"
		error = "True" 
		break
	
	if distance - minHH &lt; newSubDiv:
		#if the truss is closer than the field length
		trussHeight = distance - minHH
	else:
		trussHeight = newSubDiv
	#bottom chord points
	newpt = Point.ByCoordinates(ptsTop[i].X,ptsTop[i].Y,ptsTop[i].Z-trussHeight)
	#append newpt to the list
	ptsBottom.append(newpt)	

topChord = []
botChord = []
verticals = []
diagonals = []
invertdiagonals = []

#GENERATE TRUSS GEOMETRY
if error == "False":
	topChord.append(PolyCurve.ByPoints(ptsTop))
	botChord.append(PolyCurve.ByPoints(ptsBottom))
	
	for i in range(0,len(ptsTop)):
	   	verticals.append(Line.ByStartPointEndPoint(ptsTop[i],ptsBottom[i]))
	   	
	   	if i &lt; len(ptsTop)-1:
	   		diagonals.append(Line.ByStartPointEndPoint(ptsTop[i],ptsBottom[i+1]))
			invertdiagonals.append(Line.ByStartPointEndPoint(ptsBottom[i],ptsTop[i+1]))
			
#Assign your output to the OUT variable.
OUT = distance,crvLen,divisions,topChord,botChord,verticals,diagonals,invertdiagonals,ptsBottom
</Script>
    </PythonNodeModels.PythonNode>
    <Dynamo.Graph.Nodes.CodeBlockNodeModel guid="045d3575-7ade-4234-8b5d-dae594824a8b" type="Dynamo.Graph.Nodes.CodeBlockNodeModel" nickname="Roof Curve" x="853.157174529344" y="283.039081691305" isVisible="true" isUpstreamVisible="true" lacing="Disabled" isSelectedInput="False" IsFrozen="false" isPinned="false" CodeText="a[0];" ShouldFocus="false">
      <PortInfo index="0" default="False" />
    </Dynamo.Graph.Nodes.CodeBlockNodeModel>
    <Dynamo.Graph.Nodes.CodeBlockNodeModel guid="5e452b4e-f956-4e79-b8d0-0b6d8befe756" type="Dynamo.Graph.Nodes.CodeBlockNodeModel" nickname="Terrain Curve" x="847.781737993339" y="385.673399254038" isVisible="true" isUpstreamVisible="true" lacing="Disabled" isSelectedInput="False" IsFrozen="false" isPinned="false" CodeText="a[1];" ShouldFocus="false">
      <PortInfo index="0" default="False" />
    </Dynamo.Graph.Nodes.CodeBlockNodeModel>
    <Dynamo.Graph.Nodes.CodeBlockNodeModel guid="61f1dda5-2b33-4797-a428-4386349e21af" type="Dynamo.Graph.Nodes.CodeBlockNodeModel" nickname="Subdivision Length" x="839.712418378838" y="491.072462760467" isVisible="true" isUpstreamVisible="true" lacing="Disabled" isSelectedInput="False" IsFrozen="false" isPinned="false" CodeText="7;" ShouldFocus="false" />
    <Dynamo.Graph.Nodes.CodeBlockNodeModel guid="274c5ff3-bb2f-4096-a8c9-a6d91e69bc64" type="Dynamo.Graph.Nodes.CodeBlockNodeModel" nickname="Minimum Height" x="837.847090388448" y="593.036667106698" isVisible="true" isUpstreamVisible="true" lacing="Disabled" isSelectedInput="False" IsFrozen="false" isPinned="false" CodeText="3;" ShouldFocus="false" />
    <Dynamo.Graph.Nodes.ZeroTouch.DSFunction guid="946ba4cd-6d4a-4275-8b62-52a988f3d330" type="Dynamo.Graph.Nodes.ZeroTouch.DSFunction" nickname="RhinoTranslationToDS.Rhino_NurbsCurvesToDS" x="447.018916316186" y="277.452769362409" isVisible="false" isUpstreamVisible="true" lacing="Shortest" isSelectedInput="False" IsFrozen="false" isPinned="false" assembly="..\..\..\..\AppData\Roaming\Dynamo\Dynamo%20Revit\1.2\packages\Rhynamo\bin\Rhynamo.dll" function="Interoperability.ReadRhino.RhinoTranslationToDS.Rhino_NurbsCurvesToDS@var[]">
      <PortInfo index="0" default="False" />
    </Dynamo.Graph.Nodes.ZeroTouch.DSFunction>
  </Elements>
  <Connectors>
    <Dynamo.Graph.Connectors.ConnectorModel start="c02fa007-8b67-4692-aa4c-3c060d1c36f5" start_index="0" end="618827f6-7fea-40c0-ae0c-856031c69923" end_index="0" portType="0" />
    <Dynamo.Graph.Connectors.ConnectorModel start="618827f6-7fea-40c0-ae0c-856031c69923" start_index="0" end="414f5f41-9fab-44ea-9858-928d1b3f26e5" end_index="0" portType="0" />
    <Dynamo.Graph.Connectors.ConnectorModel start="414f5f41-9fab-44ea-9858-928d1b3f26e5" start_index="0" end="946ba4cd-6d4a-4275-8b62-52a988f3d330" end_index="0" portType="0" />
    <Dynamo.Graph.Connectors.ConnectorModel start="045d3575-7ade-4234-8b5d-dae594824a8b" start_index="0" end="d54eeed8-035c-461a-942b-02f155d9a1bf" end_index="0" portType="0" />
    <Dynamo.Graph.Connectors.ConnectorModel start="5e452b4e-f956-4e79-b8d0-0b6d8befe756" start_index="0" end="d54eeed8-035c-461a-942b-02f155d9a1bf" end_index="1" portType="0" />
    <Dynamo.Graph.Connectors.ConnectorModel start="61f1dda5-2b33-4797-a428-4386349e21af" start_index="0" end="d54eeed8-035c-461a-942b-02f155d9a1bf" end_index="2" portType="0" />
    <Dynamo.Graph.Connectors.ConnectorModel start="274c5ff3-bb2f-4096-a8c9-a6d91e69bc64" start_index="0" end="d54eeed8-035c-461a-942b-02f155d9a1bf" end_index="3" portType="0" />
    <Dynamo.Graph.Connectors.ConnectorModel start="946ba4cd-6d4a-4275-8b62-52a988f3d330" start_index="0" end="045d3575-7ade-4234-8b5d-dae594824a8b" end_index="0" portType="0" />
    <Dynamo.Graph.Connectors.ConnectorModel start="946ba4cd-6d4a-4275-8b62-52a988f3d330" start_index="0" end="5e452b4e-f956-4e79-b8d0-0b6d8befe756" end_index="0" portType="0" />
  </Connectors>
  <Notes />
  <Annotations />
  <Presets />
  <Cameras>
    <Camera Name="Background Preview" eyeX="2.29021334648132" eyeY="17.1889057159424" eyeZ="44.7724876403809" lookX="-6.23606777191162" lookY="-13.94105052948" lookZ="-48.6085586547852" upX="-0.00776834413409233" upY="0.998134791851044" upZ="-0.0605522654950619" />
  </Cameras>
</Workspace>