<Workspace Version="1.2.0.2514" X="-398.327828280878" Y="85.1534714738017" zoom="0.745943528983032" Name="Home" Description="" RunType="Manual" RunPeriod="1000" HasRunWithoutCrash="True">
  <NamespaceResolutionMap>
    <ClassMap partialName="Curves.DeconstructPolyCurve" resolvedName="Geometry.Curves" assemblyName="LunchBox.dll" />
    <ClassMap partialName="Curves" resolvedName="Geometry.Curves" assemblyName="LunchBox.dll" />
    <ClassMap partialName="NurbsCurve" resolvedName="Autodesk.DesignScript.Geometry.NurbsCurve" assemblyName="ProtoGeometry.dll" />
    <ClassMap partialName="Autodesk.Curve" resolvedName="Autodesk.DesignScript.Geometry.Curve" assemblyName="ProtoGeometry.dll" />
    <ClassMap partialName="Autodesk.DesignScript.Geometry.Curve" resolvedName="Autodesk.DesignScript.Geometry.Curve" assemblyName="ProtoGeometry.dll" />
    <ClassMap partialName="NurbsCurve.ClosestPointTo" resolvedName="Autodesk.DesignScript.Geometry.NurbsCurve" assemblyName="ProtoGeometry.dll" />
    <ClassMap partialName="PolyCurve" resolvedName="Autodesk.DesignScript.Geometry.PolyCurve" assemblyName="ProtoGeometry.dll" />
    <ClassMap partialName="Circle" resolvedName="Autodesk.DesignScript.Geometry.Circle" assemblyName="ProtoGeometry.dll" />
    <ClassMap partialName="Plane" resolvedName="Autodesk.DesignScript.Geometry.Plane" assemblyName="ProtoGeometry.dll" />
    <ClassMap partialName="Vector.YAxis" resolvedName="Autodesk.DesignScript.Geometry.Vector" assemblyName="ProtoGeometry.dll" />
    <ClassMap partialName="Vector" resolvedName="Autodesk.DesignScript.Geometry.Vector" assemblyName="ProtoGeometry.dll" />
    <ClassMap partialName="Geometry.domain" resolvedName="Autodesk.DesignScript.Geometry.Geometry" assemblyName="ProtoGeometry.dll" />
    <ClassMap partialName="NurbsCurve.domain" resolvedName="Autodesk.DesignScript.Geometry.NurbsCurve" assemblyName="ProtoGeometry.dll" />
    <ClassMap partialName="Autodesk.Curve.domain" resolvedName="Autodesk.DesignScript.Geometry.Curve" assemblyName="ProtoGeometry.dll" />
    <ClassMap partialName="Autodesk.DesignScript.Geometry.Curve.domain" resolvedName="Autodesk.DesignScript.Geometry.Curve" assemblyName="ProtoGeometry.dll" />
    <ClassMap partialName="NurbsCurve.r" resolvedName="Autodesk.DesignScript.Geometry.NurbsCurve" assemblyName="ProtoGeometry.dll" />
  </NamespaceResolutionMap>
  <Elements>
    <CoreNodeModels.Input.Filename guid="c02fa007-8b67-4692-aa4c-3c060d1c36f5" type="CoreNodeModels.Input.Filename" nickname="File Path" x="-801.739009059964" y="445.103955334587" isVisible="true" isUpstreamVisible="true" lacing="Disabled" isSelectedInput="True" IsFrozen="false" isPinned="false">
      <System.String>.\TrussExampleSetup.3dm</System.String>
      <HintPath>C:\Users\giovanni.brogioli\Documents\Dynamo\Scripts\PythonShell\TrussExampleSetup.3dm</HintPath>
    </CoreNodeModels.Input.Filename>
    <Dynamo.Graph.Nodes.ZeroTouch.DSFunction guid="618827f6-7fea-40c0-ae0c-856031c69923" type="Dynamo.Graph.Nodes.ZeroTouch.DSFunction" nickname="OpenRhino3dmModel.Get_RhinoFile" x="-538.739009059964" y="445.103955334587" isVisible="true" isUpstreamVisible="true" lacing="Shortest" isSelectedInput="False" IsFrozen="false" isPinned="true" assembly="..\..\..\..\AppData\Roaming\Dynamo\Dynamo%20Core\1.2\packages\Rhynamo\bin\Rhynamo.dll" function="Interoperability.ReadRhino.OpenRhino3dmModel.Get_RhinoFile@var">
      <PortInfo index="0" default="False" />
    </Dynamo.Graph.Nodes.ZeroTouch.DSFunction>
    <Dynamo.Graph.Nodes.ZeroTouch.DSFunction guid="414f5f41-9fab-44ea-9858-928d1b3f26e5" type="Dynamo.Graph.Nodes.ZeroTouch.DSFunction" nickname="RhinoObject.Get_RhinoObjects" x="-193.739009059964" y="445.103955334587" isVisible="true" isUpstreamVisible="true" lacing="Shortest" isSelectedInput="False" IsFrozen="false" isPinned="false" assembly="..\..\..\..\AppData\Roaming\Dynamo\Dynamo%20Core\1.2\packages\Rhynamo\bin\Rhynamo.dll" function="Interoperability.ReadRhino.RhinoObject.Get_RhinoObjects@var">
      <PortInfo index="0" default="False" />
    </Dynamo.Graph.Nodes.ZeroTouch.DSFunction>
    <Dynamo.Graph.Nodes.CodeBlockNodeModel guid="045d3575-7ade-4234-8b5d-dae594824a8b" type="Dynamo.Graph.Nodes.CodeBlockNodeModel" nickname="Roof Curve" x="546.874452219384" y="373.236930322034" isVisible="true" isUpstreamVisible="true" lacing="Disabled" isSelectedInput="False" IsFrozen="false" isPinned="true" CodeText="a[0];" ShouldFocus="false">
      <PortInfo index="0" default="False" />
    </Dynamo.Graph.Nodes.CodeBlockNodeModel>
    <Dynamo.Graph.Nodes.ZeroTouch.DSFunction guid="946ba4cd-6d4a-4275-8b62-52a988f3d330" type="Dynamo.Graph.Nodes.ZeroTouch.DSFunction" nickname="RhinoTranslationToDS.Rhino_NurbsCurvesToDS" x="172.260990940036" y="445.103955334587" isVisible="false" isUpstreamVisible="true" lacing="Shortest" isSelectedInput="False" IsFrozen="false" isPinned="false" assembly="..\..\..\..\AppData\Roaming\Dynamo\Dynamo%20Core\1.2\packages\Rhynamo\bin\Rhynamo.dll" function="Interoperability.ReadRhino.RhinoTranslationToDS.Rhino_NurbsCurvesToDS@var[]">
      <PortInfo index="0" default="False" />
    </Dynamo.Graph.Nodes.ZeroTouch.DSFunction>
    <PythonNodeModels.PythonNode guid="b356ac58-ac9c-4e0e-a108-133a947fa0ca" type="PythonNodeModels.PythonNode" nickname="Python Script" x="771.703325478033" y="518.450665407581" isVisible="true" isUpstreamVisible="true" lacing="Disabled" isSelectedInput="False" IsFrozen="false" isPinned="true" inputcount="2">
      <PortInfo index="0" default="False" />
      <PortInfo index="1" default="False" />
      <Script>import clr
clr.AddReference('ProtoGeometry')
from Autodesk.DesignScript.Geometry import *
import math
#The inputs to this node will be stored as a list in the IN variables.

crvRoof = IN[0]

divisions = IN[1]

Pts = []


for i in range(0, int(divisions)+1):
	ran = float(i*(1.0)/int(divisions))
	Pts.append(Curve.PointAtParameter(crvRoof,ran))


#Assign your output to the OUT variable.
OUT = Pts

</Script>
    </PythonNodeModels.PythonNode>
    <Dynamo.Graph.Nodes.CodeBlockNodeModel guid="eb92a3c0-8574-4352-96e8-94a7a3e5c910" type="Dynamo.Graph.Nodes.CodeBlockNodeModel" nickname="Code Block" x="562.424934155194" y="550.139303262385" isVisible="true" isUpstreamVisible="true" lacing="Disabled" isSelectedInput="False" IsFrozen="false" isPinned="false" CodeText="11;" ShouldFocus="false" />
  </Elements>
  <Connectors>
    <Dynamo.Graph.Connectors.ConnectorModel start="c02fa007-8b67-4692-aa4c-3c060d1c36f5" start_index="0" end="618827f6-7fea-40c0-ae0c-856031c69923" end_index="0" portType="0" />
    <Dynamo.Graph.Connectors.ConnectorModel start="618827f6-7fea-40c0-ae0c-856031c69923" start_index="0" end="414f5f41-9fab-44ea-9858-928d1b3f26e5" end_index="0" portType="0" />
    <Dynamo.Graph.Connectors.ConnectorModel start="414f5f41-9fab-44ea-9858-928d1b3f26e5" start_index="0" end="946ba4cd-6d4a-4275-8b62-52a988f3d330" end_index="0" portType="0" />
    <Dynamo.Graph.Connectors.ConnectorModel start="045d3575-7ade-4234-8b5d-dae594824a8b" start_index="0" end="b356ac58-ac9c-4e0e-a108-133a947fa0ca" end_index="0" portType="0" />
    <Dynamo.Graph.Connectors.ConnectorModel start="946ba4cd-6d4a-4275-8b62-52a988f3d330" start_index="0" end="045d3575-7ade-4234-8b5d-dae594824a8b" end_index="0" portType="0" />
    <Dynamo.Graph.Connectors.ConnectorModel start="eb92a3c0-8574-4352-96e8-94a7a3e5c910" start_index="0" end="b356ac58-ac9c-4e0e-a108-133a947fa0ca" end_index="1" portType="0" />
  </Connectors>
  <Notes />
  <Annotations />
  <Presets />
  <Cameras>
    <Camera Name="Background Preview" eyeX="-8.17683617426789" eyeY="24.3106627850779" eyeZ="25.8364677722772" lookX="1.6472101088643" lookY="-21.4156062590879" lookZ="-29.560925132991" upX="0.0221848990768194" upY="0.917060077190399" upZ="-0.398131430149078" />
  </Cameras>
</Workspace>