<Workspace Version="1.3.1.1736" X="-1372.74184374703" Y="1312.92631343669" zoom="0.846840853125254" ScaleFactor="1" Name="Home" Description="" RunType="Manual" RunPeriod="1000" HasRunWithoutCrash="True">
  <NamespaceResolutionMap />
  <Elements>
    <PythonNodeModels.PythonNode guid="7d5adb8f-9037-442c-9ad6-706c3e009aed" type="PythonNodeModels.PythonNode" nickname="Assign Area Load - Python Script" x="1717.89347090284" y="-1566.70289457208" isVisible="true" isUpstreamVisible="true" lacing="Disabled" isSelectedInput="False" IsFrozen="false" isPinned="true" inputcount="1">
      <PortInfo index="0" default="False" />
      <Script>import clr
clr.AddReference('ProtoGeometry')
from Autodesk.DesignScript.Geometry import *
#Import ToDSType(bool) extension method
clr.AddReference('RevitNodes')
import Revit
clr.ImportExtensions(Revit.GeometryConversion)
#Import DocumentManager and TransactionManager
clr.AddReference('RevitServices')
import RevitServices
from RevitServices.Persistence import DocumentManager
from RevitServices.Transactions import TransactionManager
from System.Collections.Generic import *
#import RevitAPI
clr.AddReference('RevitAPI')
import Autodesk
from Autodesk.Revit.DB import *
from Autodesk.Revit.DB.Structure import *
from System.Collections.Generic import *

doc = DocumentManager.Instance.CurrentDBDocument

#The inputs to this node will be stored as a list in the IN variables.
#Host=UnwrapElement(IN[0])
areaLoad = UnwrapElement(IN[0])



	
#Assign your output to the OUT variable.
OUT = AreaLoad.GetLoops(areaLoad)</Script>
    </PythonNodeModels.PythonNode>
    <Dynamo.Nodes.DSModelElementSelection guid="1b5a6517-8a8b-461d-b83f-532bb65123f6" type="Dynamo.Nodes.DSModelElementSelection" nickname="Select Model Element" x="1740.1896367131" y="-1461.40106533556" isVisible="true" isUpstreamVisible="true" lacing="Disabled" isSelectedInput="True" IsFrozen="false" isPinned="false">
      <instance id="581fbb4d-ff48-4a85-9e48-a070aede3a1a-00202104" />
    </Dynamo.Nodes.DSModelElementSelection>
    <PythonNodeModels.PythonNode guid="9bc2fa4a-afe9-4a69-b5ec-16c75248adf8" type="PythonNodeModels.PythonNode" nickname="Curve Loop" x="1324.12239246126" y="-1236.17543577719" isVisible="true" isUpstreamVisible="true" lacing="Disabled" isSelectedInput="False" IsFrozen="false" isPinned="true" inputcount="1">
      <PortInfo index="0" default="False" />
      <Script>import clr
clr.AddReference('ProtoGeometry')
from Autodesk.DesignScript.Geometry import *
#Import ToDSType(bool) extension method
clr.AddReference('RevitNodes')
import Revit
clr.ImportExtensions(Revit.GeometryConversion)
#Import DocumentManager and TransactionManager
clr.AddReference('RevitServices')
import RevitServices
from RevitServices.Persistence import DocumentManager
from RevitServices.Transactions import TransactionManager
from System.Collections.Generic import *
#import RevitAPI
clr.AddReference('RevitAPI')
import Autodesk
from Autodesk.Revit.DB import *
from Autodesk.Revit.DB.Structure import *
from System.Collections.Generic import *

doc = DocumentManager.Instance.CurrentDBDocument

#The inputs to this node will be stored as a list in the IN variables.
#Host=UnwrapElement(IN[0])

crvs = IN[0]

loop = CurveLoop()

crvsLoop = loop.CreateViaCopy(crvs)



	
"""
loads=[]

for i in outerProfileLoop:
	#Start Transaction
	doc = DocumentManager.Instance.CurrentDBDocument
	TransactionManager.Instance.EnsureInTransaction(doc)
	a= AreaLoad.Create(doc,i,F,loadtype)
	loads.append(a)
	
#End Transaction
TransactionManager.Instance.TransactionTaskDone()
	"""
#Assign your output to the OUT variable.
OUT = outerProfileLoop</Script>
    </PythonNodeModels.PythonNode>
    <PythonNodeModels.PythonNode guid="7f89ef77-f328-42e5-94b0-2e1d9a1718e0" type="PythonNodeModels.PythonNode" nickname="Python Script" x="2452.22449594856" y="-1043.88955422873" isVisible="true" isUpstreamVisible="true" lacing="Disabled" isSelectedInput="False" IsFrozen="false" isPinned="true" inputcount="3">
      <PortInfo index="0" default="False" />
      <PortInfo index="1" default="False" />
      <PortInfo index="2" default="False" />
      <Script>import clr
clr.AddReference('ProtoGeometry')
from Autodesk.DesignScript.Geometry import *

# Import DocumentManager and TransactionManager
clr.AddReference("RevitServices")
import RevitServices
from RevitServices.Persistence import DocumentManager
from RevitServices.Transactions import TransactionManager

# Import RevitAPI
clr.AddReference("RevitAPI")
import Autodesk
from Autodesk.Revit.DB import *

doc = DocumentManager.Instance.CurrentDBDocument
uiapp = DocumentManager.Instance.CurrentUIApplication
app = uiapp.Application


regions = []
activeViewId = doc.ActiveView.Id;

TransactionManager.Instance.EnsureInTransaction(doc)

pts = UnwrapElement(IN[0])
innerPts = UnwrapElement(IN[1])

frt = UnwrapElement(IN[2])


profileLoops = []
outerProfileLoop = CurveLoop()
#innerProfileLoop = CurveLoop()

profileLoops.Add(outerProfileLoop)
#profileLoops.Add(innerProfileLoop)


#create filled region
for i in range(0,len(pts)-1):
	outerProfileLoop.Append(Autodesk.Revit.DB.Line.CreateBound(XYZ(pts[i].X,pts[i].Y,pts[i].Z),XYZ(pts[i+1].X,pts[i+1].Y,pts[i+1].Z)))

for j in range(0,len(innerPts)):
	innerProfileLoop = CurveLoop()
	profileLoops.Add(innerProfileLoop)
	for i in range(0,len(innerPts[j])-1):
		innerProfileLoop.Append(Autodesk.Revit.DB.Line.CreateBound(XYZ(innerPts[j][i].X,innerPts[j][i].Y,innerPts[j][i].Z),XYZ(innerPts[j][i+1].X,innerPts[j][i+1].Y,innerPts[j][i+1].Z)))


region = FilledRegion.Create(doc,frt[0].Id,activeViewId,profileLoops)
regions.Add(region)

TransactionManager.Instance.TransactionTaskDone()

#Assign your outputs to the OUT variable
OUT = regions
</Script>
    </PythonNodeModels.PythonNode>
    <Dynamo.Graph.Nodes.ZeroTouch.DSFunction guid="2399b948-53fe-463a-a385-965aa4a4bb71" type="Dynamo.Graph.Nodes.ZeroTouch.DSFunction" nickname="Curve.EndPoint" x="1623.6145259764" y="-957.300291839145" isVisible="true" isUpstreamVisible="true" lacing="Shortest" isSelectedInput="False" IsFrozen="false" isPinned="true" assembly="ProtoGeometry.dll" function="Autodesk.DesignScript.Geometry.Curve.EndPoint">
      <PortInfo index="0" default="False" />
    </Dynamo.Graph.Nodes.ZeroTouch.DSFunction>
    <Dynamo.Graph.Nodes.CodeBlockNodeModel guid="9938f34c-af29-4768-b442-f696c9a5884e" type="Dynamo.Graph.Nodes.CodeBlockNodeModel" nickname="Code Block" x="848.369315877767" y="-1106.99384848855" isVisible="true" isUpstreamVisible="true" lacing="Disabled" isSelectedInput="False" IsFrozen="false" isPinned="false" CodeText="A[0];" ShouldFocus="false">
      <PortInfo index="0" default="False" />
    </Dynamo.Graph.Nodes.CodeBlockNodeModel>
    <PythonNodeModels.PythonNode guid="49aa51d5-d674-4ab0-857d-ba77dd0649af" type="PythonNodeModels.PythonNode" nickname="Python Script" x="998.175878894304" y="-1098.42657265005" isVisible="true" isUpstreamVisible="true" lacing="Disabled" isSelectedInput="False" IsFrozen="false" isPinned="true" inputcount="1">
      <PortInfo index="0" default="False" />
      <Script>#Copyright(c) 2015, Konrad Sobon
# @arch_laboratory, http://archi-lab.net

import clr
clr.AddReference('ProtoGeometry')
from Autodesk.DesignScript.Geometry import *

#The inputs to this node will be stored as a list in the IN variable.
dataEnteringNode = IN

inputCurves = IN[0]

#join/group curves function
def groupCurves(Line_List): 
	ignore_distance = 0.1 # Assume points this close or closer to each other are touching 
	Grouped_Lines = [] 
	Queue = set() 
	while Line_List: 
		Shape = [] 
		Queue.add(Line_List.pop()) # Move a line from the Line_List to our queue 
		while Queue: 
			Current_Line = Queue.pop() 
			Shape.append(Current_Line) 
			for Potential_Match in Line_List: 
				Points = (Potential_Match.StartPoint, Potential_Match.EndPoint)
				for P1 in Points: 
					for P2 in (Current_Line.StartPoint, Current_Line.EndPoint): 
						distance = P1.DistanceTo(P2) 
						if distance &lt;= ignore_distance: 
							Queue.add(Potential_Match) 
			Line_List = [item for item in Line_List if item not in Queue]
		Grouped_Lines.append(Shape) 
	return Grouped_Lines

OUT = groupCurves(inputCurves)</Script>
    </PythonNodeModels.PythonNode>
    <Dynamo.Graph.Nodes.ZeroTouch.DSFunction guid="c856d12a-4878-4a5f-9312-b55774486664" type="Dynamo.Graph.Nodes.ZeroTouch.DSFunction" nickname="Room.FinishBoundary" x="596.889994910642" y="-1246.80647144404" isVisible="true" isUpstreamVisible="true" lacing="Shortest" isSelectedInput="False" IsFrozen="false" isPinned="true" assembly="RevitNodes.dll" function="Revit.Elements.Room.FinishBoundary">
      <PortInfo index="0" default="False" />
    </Dynamo.Graph.Nodes.ZeroTouch.DSFunction>
    <Dynamo.Graph.Nodes.CodeBlockNodeModel guid="10ca2474-1114-4037-a672-7adc98c2fb05" type="Dynamo.Graph.Nodes.CodeBlockNodeModel" nickname="Code Block" x="272.710042442982" y="-964.166024363941" isVisible="true" isUpstreamVisible="true" lacing="Disabled" isSelectedInput="False" IsFrozen="false" isPinned="true" CodeText="A[0];" ShouldFocus="false">
      <PortInfo index="0" default="False" />
    </Dynamo.Graph.Nodes.CodeBlockNodeModel>
    <Dynamo.Graph.Nodes.CodeBlockNodeModel guid="99a6d6cf-a13b-4e77-9527-08e5412ba5e1" type="Dynamo.Graph.Nodes.CodeBlockNodeModel" nickname="Code Block" x="-338.955110887662" y="-1036.21952116758" isVisible="true" isUpstreamVisible="true" lacing="Disabled" isSelectedInput="False" IsFrozen="false" isPinned="false" CodeText="A[0];" ShouldFocus="false">
      <PortInfo index="0" default="False" />
    </Dynamo.Graph.Nodes.CodeBlockNodeModel>
    <Dynamo.Graph.Nodes.CustomNodes.Function guid="dff0cbe5-6973-40c2-9f2a-1c123e245729" type="Dynamo.Graph.Nodes.CustomNodes.Function" nickname="Get Loaded RVT Links" x="-862.300668887561" y="-1228.89497295255" isVisible="true" isUpstreamVisible="true" lacing="Shortest" isSelectedInput="True" IsFrozen="false" isPinned="true">
      <ID value="8e3c2714-7168-4346-bbf0-aff16a267efe" />
      <Name value="Get Loaded RVT Links" />
      <Description value="" />
      <Inputs />
      <Outputs>
        <Output value="loaded Link Names" />
        <Output value="loaded Link Docs" />
        <Output value="cleaned Loaded names only" />
        <Output value="cleaned and sorted" />
      </Outputs>
    </Dynamo.Graph.Nodes.CustomNodes.Function>
    <Dynamo.Graph.Nodes.CustomNodes.Function guid="750b5e74-45ef-4b8f-9569-0ae2421f4b80" type="Dynamo.Graph.Nodes.CustomNodes.Function" nickname="Get All Elements From Linked Model" x="-154.426983178885" y="-921.126192714933" isVisible="true" isUpstreamVisible="true" lacing="Shortest" isSelectedInput="False" IsFrozen="false" isPinned="true">
      <PortInfo index="0" default="False" />
      <PortInfo index="1" default="False" />
      <ID value="ce86e653-fcd4-4809-b0c0-584a1d34e006" />
      <Name value="Get All Elements From Linked Model" />
      <Description value="This node is based on code posted by Julien Benoit. Big thanks to Julien for sharing his work. This node will retrieve all elements of a given category from a given linked model. " />
      <Inputs>
        <Input value="LinkDoc" />
        <Input value="Category" />
      </Inputs>
      <Outputs>
        <Output value="Elements" />
      </Outputs>
    </Dynamo.Graph.Nodes.CustomNodes.Function>
    <DSRevitNodesUI.Categories guid="b3363fa6-2b87-4097-b81a-366df080d99d" type="DSRevitNodesUI.Categories" nickname="Categories" x="-548.393541685352" y="-811.202412131345" isVisible="true" isUpstreamVisible="true" lacing="Disabled" isSelectedInput="True" IsFrozen="false" isPinned="true" index="403:Rooms" />
    <PythonNodeModels.PythonNode guid="28f271b3-8091-403f-9da7-526dae931dae" type="PythonNodeModels.PythonNode" nickname="Python Script" x="888.507682922983" y="575.943660611867" isVisible="true" isUpstreamVisible="true" lacing="Disabled" isSelectedInput="False" IsFrozen="false" isPinned="false" inputcount="1">
      <PortInfo index="0" default="False" />
      <Script> 
import clr
# Import RevitAPI
clr.AddReference("RevitAPI")
import Autodesk
from Autodesk.Revit.DB import *
 
# Import ToDSType(bool) extension method, not sure we need this
clr.AddReference("RevitNodes")
import Revit
clr.ImportExtensions(Revit.Elements)
# Make sure the GeometryConversion utilities are accesible see https://github.com/DynamoDS/Dynamo/issues/1946
clr.ImportExtensions(Revit.GeometryConversion) 
 
# Unwrap
rooms = []
for i in IN[0]:
	rooms.append(UnwrapElement(i)) #This kind of opens the Revit element so it can be used by Dynamo Script
# Curve array
curves = []
# Boundary options for rooms
opt = SpatialElementBoundaryOptions()
# Iterate through every room
for room in rooms:
	if room.Area &gt; 0: # Make sure it has positive Area, i.e is placed
		rvBoundary = room.GetBoundarySegments(opt) # Get room boundary
		dsBoundary = [] # A Dynamo list to hold the boundary per room, remember it can be complex, with holes		
		for rvLoop in rvBoundary: # For each loop in the room boundary
			dsLoop = [] # A list to hold each room's loop
			for rvPiece in rvLoop:	# Retrieve each segment of the loop
				dsPiece = Revit.GeometryConversion.RevitToProtoCurve.ToProtoType(rvPiece.Curve,True) # Read the segment as Curve and convert to Dynamo geometry
				dsLoop.append(dsPiece) # Add the piece to the Dynamo Loop
			dsBoundary.Add(dsLoop) # Add the Dynamo Loop to the Dynamo Boundary
		curves.append(dsBoundary) # Add the Dynamo Boundary per room to the Curves list
#Output
OUT = curves</Script>
    </PythonNodeModels.PythonNode>
    <Dynamo.Graph.Nodes.CodeBlockNodeModel guid="8e4671ca-d857-4534-8361-8603e676a43b" type="Dynamo.Graph.Nodes.CodeBlockNodeModel" nickname="Code Block" x="-289.44898823654" y="309.408508873338" isVisible="true" isUpstreamVisible="true" lacing="Disabled" isSelectedInput="False" IsFrozen="false" isPinned="false" CodeText="-4.8;" ShouldFocus="false" />
    <CoreNodeModels.Watch guid="605f0c86-c2a2-41c4-b5ba-71e49b9a858c" type="CoreNodeModels.Watch" nickname="Watch" x="285.106346710624" y="305.37391565255" isVisible="true" isUpstreamVisible="true" lacing="Disabled" isSelectedInput="False" IsFrozen="false" isPinned="false">
      <PortInfo index="0" default="False" />
    </CoreNodeModels.Watch>
    <CoreNodeModels.DynamoConvert guid="d4161f11-806b-41ff-b3f2-4e480195411b" type="CoreNodeModels.DynamoConvert" nickname="Convert Between Units" x="-185.937577768561" y="305.655307676695" isVisible="true" isUpstreamVisible="true" lacing="Disabled" isSelectedInput="False" IsFrozen="false" isPinned="false" conversionMetric="Length" conversionFrom="Feet" conversionTo="Millimeters">
      <PortInfo index="0" default="True" />
    </CoreNodeModels.DynamoConvert>
    <Dynamo.Graph.Nodes.ZeroTouch.DSFunction guid="d6723f5d-17fc-4ddd-8636-9ea5d46f1e1a" type="Dynamo.Graph.Nodes.ZeroTouch.DSFunction" nickname="Point.ByCoordinates" x="446" y="253" isVisible="true" isUpstreamVisible="true" lacing="Shortest" isSelectedInput="False" IsFrozen="false" isPinned="false" assembly="ProtoGeometry.dll" function="Autodesk.DesignScript.Geometry.Point.ByCoordinates@double,double,double">
      <PortInfo index="0" default="True" />
      <PortInfo index="1" default="True" />
      <PortInfo index="2" default="True" />
    </Dynamo.Graph.Nodes.ZeroTouch.DSFunction>
    <Dynamo.Graph.Nodes.ZeroTouch.DSFunction guid="884dbd57-db28-4efc-bd5e-9e8200f9dc5e" type="Dynamo.Graph.Nodes.ZeroTouch.DSFunction" nickname="List.FirstItem" x="522.111176905755" y="446.823936390833" isVisible="true" isUpstreamVisible="true" lacing="Shortest" isSelectedInput="False" IsFrozen="false" isPinned="false" assembly="DSCoreNodes.dll" function="DSCore.List.FirstItem@var[]..[]">
      <PortInfo index="0" default="False" />
    </Dynamo.Graph.Nodes.ZeroTouch.DSFunction>
    <DSRevitNodesUI.ElementsOfType guid="212e785f-69a4-4c1a-85a5-e8ec1ec2ebb3" type="DSRevitNodesUI.ElementsOfType" nickname="All Elements of Type" x="265.774989630859" y="447.323936390833" isVisible="true" isUpstreamVisible="true" lacing="Disabled" isSelectedInput="False" IsFrozen="false" isPinned="true">
      <PortInfo index="0" default="False" />
    </DSRevitNodesUI.ElementsOfType>
    <DSRevitNodesUI.ElementTypes guid="5cf3dbc1-2780-4e50-9c2c-3067ebe3050b" type="DSRevitNodesUI.ElementTypes" nickname="Element Types" x="98.2749896308585" y="445.823936390833" isVisible="true" isUpstreamVisible="true" lacing="Disabled" isSelectedInput="True" IsFrozen="false" isPinned="false" index="14:AreaLoadType" />
    <Dynamo.Nodes.DSModelElementSelection guid="5a9d6d11-4b56-4adf-8ef8-35d4af7b2180" type="Dynamo.Nodes.DSModelElementSelection" nickname="Select Model Element" x="257.692681390479" y="-1170.52827317944" isVisible="true" isUpstreamVisible="true" lacing="Disabled" isSelectedInput="True" IsFrozen="false" isPinned="true">
      <instance id="581fbb4d-ff48-4a85-9e48-a070aede3a1a-00202186" />
    </Dynamo.Nodes.DSModelElementSelection>
    <PythonNodeModels.PythonNode guid="a151c867-ab47-4dff-a327-a79c93e44a66" type="PythonNodeModels.PythonNode" nickname="Assign Area Load - Python Script" x="1478.83422421627" y="405.732574279249" isVisible="true" isUpstreamVisible="true" lacing="Disabled" isSelectedInput="False" IsFrozen="false" isPinned="true" inputcount="3">
      <PortInfo index="0" default="False" />
      <PortInfo index="1" default="False" />
      <PortInfo index="2" default="False" />
      <Script>import clr
clr.AddReference('ProtoGeometry')
from Autodesk.DesignScript.Geometry import *
#Import ToDSType(bool) extension method
clr.AddReference('RevitNodes')
import Revit
clr.ImportExtensions(Revit.GeometryConversion)
#Import DocumentManager and TransactionManager
clr.AddReference('RevitServices')
import RevitServices
from RevitServices.Persistence import DocumentManager
from RevitServices.Transactions import TransactionManager
from System.Collections.Generic import *
#import RevitAPI
clr.AddReference('RevitAPI')
import Autodesk
from Autodesk.Revit.DB import *
from Autodesk.Revit.DB.Structure import *
from System.Collections.Generic import *

doc = DocumentManager.Instance.CurrentDBDocument

#The inputs to this node will be stored as a list in the IN variables.
#Host=UnwrapElement(IN[0])

pts = UnwrapElement(IN[0])
F=IN[1].ToXyz(False)
loadtype=UnwrapElement(IN[2])

TransactionManager.Instance.EnsureInTransaction(doc)

profileLoops = []

outerProfileLoop = CurveLoop()

profileLoops.Add(outerProfileLoop)



#create filled region
for i in range(0,len(pts)-1):
	outerProfileLoop.Append(Autodesk.Revit.DB.Line.CreateBound(XYZ(pts[i].X,pts[i].Y,pts[i].Z),XYZ(pts[i+1].X,pts[i+1].Y,pts[i+1].Z)))

loads=[]

a= AreaLoad.Create(doc,profileLoops,F,loadtype)	
loads.append(a)

#End Transaction
TransactionManager.Instance.TransactionTaskDone()

#Assign your output to the OUT variable.
OUT = profileLoops,loads</Script>
    </PythonNodeModels.PythonNode>
    <Dynamo.Graph.Nodes.CodeBlockNodeModel guid="b1d9577b-6a1d-45d0-9afa-3df07afc1c71" type="Dynamo.Graph.Nodes.CodeBlockNodeModel" nickname="Code Block" x="1772.29210895859" y="-692.875869394337" isVisible="true" isUpstreamVisible="true" lacing="Disabled" isSelectedInput="False" IsFrozen="false" isPinned="false" CodeText="0.003281;" ShouldFocus="false" />
    <Dynamo.Graph.Nodes.ZeroTouch.DSFunction guid="d1b40fc9-39e0-4ce6-8ee3-4386e867f9cf" type="Dynamo.Graph.Nodes.ZeroTouch.DSFunction" nickname="Geometry.Scale" x="2260.40418203296" y="-835.584003349841" isVisible="true" isUpstreamVisible="true" lacing="Shortest" isSelectedInput="False" IsFrozen="false" isPinned="true" assembly="ProtoGeometry.dll" function="Autodesk.DesignScript.Geometry.Geometry.Scale@double">
      <PortInfo index="0" default="False" />
      <PortInfo index="1" default="True" />
    </Dynamo.Graph.Nodes.ZeroTouch.DSFunction>
    <Dynamo.Nodes.DSModelElementsSelection guid="ff466da0-09b8-4418-9719-431e38030f89" type="Dynamo.Nodes.DSModelElementsSelection" nickname="Select Model Elements" x="472.659180014024" y="-636.967267337023" isVisible="true" isUpstreamVisible="true" lacing="Disabled" isSelectedInput="True" IsFrozen="false" isPinned="false">
      <instance id="581fbb4d-ff48-4a85-9e48-a070aede3a1a-002024e4" />
      <instance id="581fbb4d-ff48-4a85-9e48-a070aede3a1a-002024e5" />
      <instance id="581fbb4d-ff48-4a85-9e48-a070aede3a1a-002024e6" />
      <instance id="581fbb4d-ff48-4a85-9e48-a070aede3a1a-002024e7" />
      <instance id="581fbb4d-ff48-4a85-9e48-a070aede3a1a-002024f3" />
      <instance id="581fbb4d-ff48-4a85-9e48-a070aede3a1a-002024f4" />
      <instance id="581fbb4d-ff48-4a85-9e48-a070aede3a1a-002024f5" />
      <instance id="581fbb4d-ff48-4a85-9e48-a070aede3a1a-002024f6" />
    </Dynamo.Nodes.DSModelElementsSelection>
    <Dynamo.Graph.Nodes.ZeroTouch.DSFunction guid="82f5f31a-a92d-4794-ac99-3d35efe58679" type="Dynamo.Graph.Nodes.ZeroTouch.DSFunction" nickname="Element.Curves" x="907.856027129182" y="-792.787326726723" isVisible="true" isUpstreamVisible="true" lacing="Shortest" isSelectedInput="False" IsFrozen="false" isPinned="true" assembly="RevitNodes.dll" function="Revit.Elements.Element.Curves">
      <PortInfo index="0" default="False" />
    </Dynamo.Graph.Nodes.ZeroTouch.DSFunction>
    <Dynamo.Nodes.DSModelElementsSelection guid="acad87ae-f77a-40c8-bca5-4fdf38ad7efc" type="Dynamo.Nodes.DSModelElementsSelection" nickname="Select Model Elements" x="1491.78543359351" y="-1272.22837178808" isVisible="true" isUpstreamVisible="true" lacing="Disabled" isSelectedInput="True" IsFrozen="false" isPinned="false">
      <instance id="581fbb4d-ff48-4a85-9e48-a070aede3a1a-002024e4" />
      <instance id="581fbb4d-ff48-4a85-9e48-a070aede3a1a-002024e5" />
      <instance id="581fbb4d-ff48-4a85-9e48-a070aede3a1a-002024e6" />
      <instance id="581fbb4d-ff48-4a85-9e48-a070aede3a1a-002024e7" />
      <instance id="581fbb4d-ff48-4a85-9e48-a070aede3a1a-002024f3" />
      <instance id="581fbb4d-ff48-4a85-9e48-a070aede3a1a-002024f4" />
      <instance id="581fbb4d-ff48-4a85-9e48-a070aede3a1a-002024f5" />
      <instance id="581fbb4d-ff48-4a85-9e48-a070aede3a1a-002024f6" />
    </Dynamo.Nodes.DSModelElementsSelection>
    <Dynamo.Graph.Nodes.ZeroTouch.DSFunction guid="568eb24c-a59a-491c-9586-b93bbd86ea39" type="Dynamo.Graph.Nodes.ZeroTouch.DSFunction" nickname="Element.Curves" x="1760.59839686854" y="-1333.28606900765" isVisible="true" isUpstreamVisible="true" lacing="Shortest" isSelectedInput="False" IsFrozen="false" isPinned="false" assembly="RevitNodes.dll" function="Revit.Elements.Element.Curves">
      <PortInfo index="0" default="False" />
    </Dynamo.Graph.Nodes.ZeroTouch.DSFunction>
    <PythonNodeModels.PythonNode guid="5f64eb84-28b9-4d50-b344-e56b6568c70a" type="PythonNodeModels.PythonNode" nickname="Python Script" x="2342.09548495331" y="-1411.81007094613" isVisible="true" isUpstreamVisible="true" lacing="Disabled" isSelectedInput="False" IsFrozen="false" isPinned="true" inputcount="1">
      <PortInfo index="0" default="False" />
      <Script>#Copyright(c) 2015, Konrad Sobon
# @arch_laboratory, http://archi-lab.net

import clr
clr.AddReference('ProtoGeometry')
from Autodesk.DesignScript.Geometry import *

#The inputs to this node will be stored as a list in the IN variable.
dataEnteringNode = IN

inputCurves = IN[0]

#join/group curves function
def groupCurves(Line_List): 
	ignore_distance = 0.1 # Assume points this close or closer to each other are touching 
	Grouped_Lines = [] 
	Queue = set() 
	while Line_List: 
		Shape = [] 
		Queue.add(Line_List.pop()) # Move a line from the Line_List to our queue 
		while Queue: 
			Current_Line = Queue.pop() 
			Shape.append(Current_Line) 
			for Potential_Match in Line_List: 
				Points = (Potential_Match.StartPoint, Potential_Match.EndPoint)
				for P1 in Points: 
					for P2 in (Current_Line.StartPoint, Current_Line.EndPoint): 
						distance = P1.DistanceTo(P2) 
						if distance &lt;= ignore_distance: 
							Queue.add(Potential_Match) 
			Line_List = [item for item in Line_List if item not in Queue]
		Grouped_Lines.append(Shape) 
	return Grouped_Lines

OUT = groupCurves(inputCurves)</Script>
    </PythonNodeModels.PythonNode>
    <Dynamo.Graph.Nodes.ZeroTouch.DSFunction guid="cde7a1f3-c246-4e71-968c-b9ec9d837627" type="Dynamo.Graph.Nodes.ZeroTouch.DSFunction" nickname="Flatten" x="2041.89015218581" y="-1321.39465306115" isVisible="true" isUpstreamVisible="true" lacing="Shortest" isSelectedInput="False" IsFrozen="false" isPinned="false" assembly="BuiltIn" function="Flatten@var[]..[]">
      <PortInfo index="0" default="False" />
    </Dynamo.Graph.Nodes.ZeroTouch.DSFunction>
    <PythonNodeModels.PythonNode guid="9e89a989-ba6a-4ddb-8fce-56288a20141e" type="PythonNodeModels.PythonNode" nickname="Assign Area Load - Python Script" x="3260.28834827607" y="-1414.13173551634" isVisible="true" isUpstreamVisible="true" lacing="Disabled" isSelectedInput="False" IsFrozen="false" isPinned="true" inputcount="1">
      <PortInfo index="0" default="False" />
      <Script>import clr
clr.AddReference('ProtoGeometry')
from Autodesk.DesignScript.Geometry import *
#Import ToDSType(bool) extension method
clr.AddReference('RevitNodes')
import Revit
clr.ImportExtensions(Revit.GeometryConversion)
#Import DocumentManager and TransactionManager
clr.AddReference('RevitServices')
import RevitServices
from RevitServices.Persistence import DocumentManager
from RevitServices.Transactions import TransactionManager
from System.Collections.Generic import *
#import RevitAPI
clr.AddReference('RevitAPI')
import Autodesk
from Autodesk.Revit.DB import *
from Autodesk.Revit.DB.Structure import *
from System.Collections.Generic import *

doc = DocumentManager.Instance.CurrentDBDocument

#The inputs to this node will be stored as a list in the IN variables.
#Host=UnwrapElement(IN[0])

pts = UnwrapElement(IN[0])


profileLoops = []

outerProfileLoop = CurveLoop()

profileLoops.Add(outerProfileLoop)


pl = []

#create filled region
for j in range(0,len(pts)):
	
	outerProfileLoop = CurveLoop()
	pl.Add(outerProfileLoop)
	for i in range(0,len(pts[j])-1):
		outerProfileLoop.Append(Autodesk.Revit.DB.Line.CreateBound(XYZ(pts[j][i].X,pts[j][i].Y,pts[j][i].Z),XYZ(pts[j][i+1].X,pts[j][i+1].Y,pts[j][i+1].Z)))


#Assign your output to the OUT variable.
OUT = pl</Script>
    </PythonNodeModels.PythonNode>
    <Dynamo.Graph.Nodes.CodeBlockNodeModel guid="884755f4-5f90-482c-a9e7-c2655cd615d7" type="Dynamo.Graph.Nodes.CodeBlockNodeModel" nickname="Code Block" x="-606.88269106485" y="1073.80717645858" isVisible="true" isUpstreamVisible="true" lacing="Disabled" isSelectedInput="False" IsFrozen="false" isPinned="false" CodeText="-4.8;" ShouldFocus="false" />
    <CoreNodeModels.DynamoConvert guid="78302f25-5af7-43d8-9038-b4ec7a948bf6" type="CoreNodeModels.DynamoConvert" nickname="Convert Between Units" x="-503.371280596871" y="1070.05397526194" isVisible="true" isUpstreamVisible="true" lacing="Disabled" isSelectedInput="False" IsFrozen="false" isPinned="false" conversionMetric="Length" conversionFrom="Feet" conversionTo="Millimeters">
      <PortInfo index="0" default="True" />
    </CoreNodeModels.DynamoConvert>
    <CoreNodeModels.Watch guid="685aa52c-3531-4221-aafb-aee7014048c2" type="CoreNodeModels.Watch" nickname="Watch" x="-32.3273561176854" y="1069.77258323779" isVisible="true" isUpstreamVisible="true" lacing="Disabled" isSelectedInput="False" IsFrozen="false" isPinned="false">
      <PortInfo index="0" default="False" />
    </CoreNodeModels.Watch>
    <DSRevitNodesUI.Categories guid="8ccbbeab-8af0-4973-97a7-b98201512047" type="DSRevitNodesUI.Categories" nickname="Categories" x="-106.433702828309" y="925.398667585241" isVisible="true" isUpstreamVisible="true" lacing="Disabled" isSelectedInput="True" IsFrozen="false" isPinned="false" index="24:FloorAnalytical" />
    <Dynamo.Graph.Nodes.ZeroTouch.DSFunction guid="0367fdd6-799a-4a33-bd08-4b245c4ba9b7" type="Dynamo.Graph.Nodes.ZeroTouch.DSFunction" nickname="Point.ByCoordinates" x="128.56629717169" y="1017.39866758524" isVisible="true" isUpstreamVisible="true" lacing="Shortest" isSelectedInput="False" IsFrozen="false" isPinned="false" assembly="ProtoGeometry.dll" function="Autodesk.DesignScript.Geometry.Point.ByCoordinates@double,double,double">
      <PortInfo index="0" default="True" />
      <PortInfo index="1" default="True" />
      <PortInfo index="2" default="True" />
    </Dynamo.Graph.Nodes.ZeroTouch.DSFunction>
    <DSRevitNodesUI.ElementsOfCategory guid="a7a994a8-27a7-47e6-814b-1dcdf923a87d" type="DSRevitNodesUI.ElementsOfCategory" nickname="All Elements of Category" x="93.0662971716904" y="926.898667585241" isVisible="true" isUpstreamVisible="true" lacing="Disabled" isSelectedInput="False" IsFrozen="false" isPinned="false">
      <PortInfo index="0" default="False" />
    </DSRevitNodesUI.ElementsOfCategory>
    <PythonNodeModels.PythonNode guid="82a936d3-14af-42b5-8083-938823c82a6e" type="PythonNodeModels.PythonNode" nickname="Assign Area Load - Python Script" x="499.111790508615" y="1016.95627976248" isVisible="true" isUpstreamVisible="true" lacing="Disabled" isSelectedInput="False" IsFrozen="false" isPinned="true" inputcount="3">
      <PortInfo index="0" default="False" />
      <PortInfo index="1" default="False" />
      <PortInfo index="2" default="False" />
      <Script>import clr
clr.AddReference('ProtoGeometry')
from Autodesk.DesignScript.Geometry import *
#Import ToDSType(bool) extension method
clr.AddReference('RevitNodes')
import Revit
clr.ImportExtensions(Revit.GeometryConversion)
#Import DocumentManager and TransactionManager
clr.AddReference('RevitServices')
import RevitServices
from RevitServices.Persistence import DocumentManager
from RevitServices.Transactions import TransactionManager
from System.Collections.Generic import *
#import RevitAPI
clr.AddReference('RevitAPI')
import Autodesk
from Autodesk.Revit.DB import *
from Autodesk.Revit.DB.Structure import *
from System.Collections.Generic import *

doc = DocumentManager.Instance.CurrentDBDocument

#The inputs to this node will be stored as a list in the IN variables.
Host=UnwrapElement(IN[0])
F=IN[1].ToXyz(False)
loadtype=UnwrapElement(IN[2])

loads=[]

for i in Host:
	#Start Transaction
	doc = DocumentManager.Instance.CurrentDBDocument
	TransactionManager.Instance.EnsureInTransaction(doc)
	a= AreaLoad.Create(doc,i,F,loadtype)
	loads.append(a)
	
#End Transaction
TransactionManager.Instance.TransactionTaskDone()
	
#Assign your output to the OUT variable.
OUT = loads</Script>
    </PythonNodeModels.PythonNode>
    <Dynamo.Graph.Nodes.ZeroTouch.DSFunction guid="6d8895b9-f79a-4a8d-abbc-f07a4f35a9ae" type="Dynamo.Graph.Nodes.ZeroTouch.DSFunction" nickname="List.FirstItem" x="204.677474077446" y="1211.22260397607" isVisible="true" isUpstreamVisible="true" lacing="Shortest" isSelectedInput="False" IsFrozen="false" isPinned="false" assembly="DSCoreNodes.dll" function="DSCore.List.FirstItem@var[]..[]">
      <PortInfo index="0" default="False" />
    </Dynamo.Graph.Nodes.ZeroTouch.DSFunction>
    <DSRevitNodesUI.ElementsOfType guid="5837f148-4045-4a18-b9fe-1ba5b4206d1e" type="DSRevitNodesUI.ElementsOfType" nickname="All Elements of Type" x="-51.6587131974504" y="1211.72260397607" isVisible="true" isUpstreamVisible="true" lacing="Disabled" isSelectedInput="False" IsFrozen="false" isPinned="true">
      <PortInfo index="0" default="False" />
    </DSRevitNodesUI.ElementsOfType>
    <DSRevitNodesUI.ElementTypes guid="9f4a63e9-257e-4b88-b0b2-f2a3e3c5a1ea" type="DSRevitNodesUI.ElementTypes" nickname="Element Types" x="-219.158713197451" y="1210.22260397607" isVisible="true" isUpstreamVisible="true" lacing="Disabled" isSelectedInput="True" IsFrozen="false" isPinned="false" index="14:AreaLoadType" />
    <Dynamo.Graph.Nodes.ZeroTouch.DSFunction guid="83908e74-0d95-477a-94fd-6cfdc3f0058f" type="Dynamo.Graph.Nodes.ZeroTouch.DSFunction" nickname="Curve.EndPoint" x="2619.05560445119" y="-1415.39615400741" isVisible="true" isUpstreamVisible="true" lacing="Shortest" isSelectedInput="False" IsFrozen="false" isPinned="true" assembly="ProtoGeometry.dll" function="Autodesk.DesignScript.Geometry.Curve.EndPoint">
      <PortInfo index="0" default="False" />
    </Dynamo.Graph.Nodes.ZeroTouch.DSFunction>
    <PythonNodeModels.PythonNode guid="bd7e4907-7702-400a-b106-a1170f60e633" type="PythonNodeModels.PythonNode" nickname="Python Script" x="2971.8724795175" y="-1414.93511604349" isVisible="true" isUpstreamVisible="true" lacing="Disabled" isSelectedInput="False" IsFrozen="false" isPinned="true" inputcount="1">
      <PortInfo index="0" default="False" />
      <Script>list = IN[0]

for l in list:
	l.append(l[0])



OUT = list</Script>
    </PythonNodeModels.PythonNode>
    <PythonNodeModels.PythonNode guid="0ab87f13-f78d-4d40-8fb4-aa4c339bf1af" type="PythonNodeModels.PythonNode" nickname="Assign Area Load - Python Script" x="3644.55846010833" y="-1281.84881541945" isVisible="true" isUpstreamVisible="true" lacing="Disabled" isSelectedInput="False" IsFrozen="false" isPinned="true" inputcount="3">
      <PortInfo index="0" default="False" />
      <PortInfo index="1" default="False" />
      <PortInfo index="2" default="False" />
      <Script>import clr
clr.AddReference('ProtoGeometry')
from Autodesk.DesignScript.Geometry import *
#Import ToDSType(bool) extension method
clr.AddReference('RevitNodes')
import Revit
clr.ImportExtensions(Revit.GeometryConversion)
#Import DocumentManager and TransactionManager
clr.AddReference('RevitServices')
import RevitServices
from RevitServices.Persistence import DocumentManager
from RevitServices.Transactions import TransactionManager
from System.Collections.Generic import *
#import RevitAPI
clr.AddReference('RevitAPI')
import Autodesk
from Autodesk.Revit.DB import *
from Autodesk.Revit.DB.Structure import *
from System.Collections.Generic import *

doc = DocumentManager.Instance.CurrentDBDocument

#The inputs to this node will be stored as a list in the IN variables.
#Host=UnwrapElement(IN[0])

profileLoops = IN[0]
F=IN[1].ToXyz(False)
loadtype=UnwrapElement(IN[2])



TransactionManager.Instance.EnsureInTransaction(doc)

loads=[]

error = None
	
for i in profileLoops:
	a= AreaLoad.Create(doc,profileLoops,F,loadtype)	
	loads.append(a)

		
		
#End Transaction
TransactionManager.Instance.TransactionTaskDone()

#Assign your output to the OUT variable.
OUT = loads, error</Script>
    </PythonNodeModels.PythonNode>
    <PythonNodeModels.PythonNode guid="d8f69566-e396-4579-ac3d-eebef71bea5e" type="PythonNodeModels.PythonNode" nickname="Python Script" x="1360.99629220767" y="-800.33440672858" isVisible="true" isUpstreamVisible="true" lacing="Disabled" isSelectedInput="False" IsFrozen="false" isPinned="true" inputcount="1">
      <PortInfo index="0" default="False" />
      <Script>#Copyright(c) 2015, Konrad Sobon
# @arch_laboratory, http://archi-lab.net

import clr
clr.AddReference('ProtoGeometry')
from Autodesk.DesignScript.Geometry import *

#The inputs to this node will be stored as a list in the IN variable.
dataEnteringNode = IN

inputCurves = IN[0]

#join/group curves function
def groupCurves(Line_List): 
	ignore_distance = 0.1 # Assume points this close or closer to each other are touching 
	Grouped_Lines = [] 
	Queue = set() 
	while Line_List: 
		Shape = [] 
		Queue.add(Line_List.pop()) # Move a line from the Line_List to our queue 
		while Queue: 
			Current_Line = Queue.pop() 
			Shape.append(Current_Line) 
			for Potential_Match in Line_List: 
				Points = (Potential_Match.StartPoint, Potential_Match.EndPoint)
				for P1 in Points: 
					for P2 in (Current_Line.StartPoint, Current_Line.EndPoint): 
						distance = P1.DistanceTo(P2) 
						if distance &lt;= ignore_distance: 
							Queue.add(Potential_Match) 
			Line_List = [item for item in Line_List if item not in Queue]
		Grouped_Lines.append(Shape) 
	return Grouped_Lines

OUT = groupCurves(inputCurves)</Script>
    </PythonNodeModels.PythonNode>
    <Dynamo.Graph.Nodes.ZeroTouch.DSFunction guid="77c55e31-4d28-4d41-888c-e3abde59d2d3" type="Dynamo.Graph.Nodes.ZeroTouch.DSFunction" nickname="Flatten" x="1165.8001790276" y="-860.187716019974" isVisible="true" isUpstreamVisible="true" lacing="Shortest" isSelectedInput="False" IsFrozen="false" isPinned="false" assembly="BuiltIn" function="Flatten@var[]..[]">
      <PortInfo index="0" default="False" />
    </Dynamo.Graph.Nodes.ZeroTouch.DSFunction>
    <PythonNodeModels.PythonNode guid="80bdc9c3-00ee-42ed-bfda-f95c2bd05555" type="PythonNodeModels.PythonNode" nickname="Python Script" x="1982.30862135823" y="-1014.58182412822" isVisible="true" isUpstreamVisible="true" lacing="Disabled" isSelectedInput="False" IsFrozen="false" isPinned="true" inputcount="1">
      <PortInfo index="0" default="False" />
      <Script>list = IN[0]

for l in list:
	l.append(l[0])



OUT = list</Script>
    </PythonNodeModels.PythonNode>
    <PythonNodeModels.PythonNode guid="b21d70ae-ea62-4479-bfde-275780c2e6cd" type="PythonNodeModels.PythonNode" nickname="Assign Area Load - Python Script" x="2817.64049184586" y="-762.745619916695" isVisible="true" isUpstreamVisible="true" lacing="Disabled" isSelectedInput="False" IsFrozen="false" isPinned="true" inputcount="3">
      <PortInfo index="0" default="False" />
      <PortInfo index="1" default="False" />
      <PortInfo index="2" default="False" />
      <Script>import clr
clr.AddReference('ProtoGeometry')
from Autodesk.DesignScript.Geometry import *
#Import ToDSType(bool) extension method
clr.AddReference('RevitNodes')
import Revit
clr.ImportExtensions(Revit.GeometryConversion)
#Import DocumentManager and TransactionManager
clr.AddReference('RevitServices')
import RevitServices
from RevitServices.Persistence import DocumentManager
from RevitServices.Transactions import TransactionManager
from System.Collections.Generic import *
#import RevitAPI
clr.AddReference('RevitAPI')
import Autodesk
from Autodesk.Revit.DB import *
from Autodesk.Revit.DB.Structure import *
from System.Collections.Generic import *

doc = DocumentManager.Instance.CurrentDBDocument

#The inputs to this node will be stored as a list in the IN variables.
#Host=UnwrapElement(IN[0])

pts = UnwrapElement(IN[0])
F=IN[1].ToXyz(False)
loadtype=UnwrapElement(IN[2])

TransactionManager.Instance.EnsureInTransaction(doc)

#Profile Loop Container
pl = []

#create filled region
for j in range(0,len(pts)):
	outerProfileLoop = CurveLoop()
	pl.Add([outerProfileLoop])
	for i in range(0,len(pts[j])-1):
		outerProfileLoop.Append(Autodesk.Revit.DB.Line.CreateBound(XYZ(pts[j][i].X,pts[j][i].Y,pts[j][i].Z),XYZ(pts[j][i+1].X,pts[j][i+1].Y,pts[j][i+1].Z)))


loads=[]

for p in pl:
	a= AreaLoad.Create(doc,p,F,loadtype)	
	loads.append(a)

#End Transaction

TransactionManager.Instance.TransactionTaskDone()

#Assign your output to the OUT variable.
OUT = loads</Script>
    </PythonNodeModels.PythonNode>
    <PythonNodeModels.PythonNode guid="41b9cb05-ede5-4a2b-bd10-6eb20ae187a6" type="PythonNodeModels.PythonNode" nickname="Assign Area Load - Python Script" x="2847.4934105787" y="-1037.96104225746" isVisible="true" isUpstreamVisible="true" lacing="Disabled" isSelectedInput="False" IsFrozen="false" isPinned="true" inputcount="1">
      <PortInfo index="0" default="False" />
      <Script>import clr
clr.AddReference('ProtoGeometry')
from Autodesk.DesignScript.Geometry import *
#Import ToDSType(bool) extension method
clr.AddReference('RevitNodes')
import Revit
clr.ImportExtensions(Revit.GeometryConversion)
#Import DocumentManager and TransactionManager
clr.AddReference('RevitServices')
import RevitServices
from RevitServices.Persistence import DocumentManager
from RevitServices.Transactions import TransactionManager
from System.Collections.Generic import *
#import RevitAPI
clr.AddReference('RevitAPI')
import Autodesk
from Autodesk.Revit.DB import *
from Autodesk.Revit.DB.Structure import *
from System.Collections.Generic import *

doc = DocumentManager.Instance.CurrentDBDocument

#The inputs to this node will be stored as a list in the IN variables.
#Host=UnwrapElement(IN[0])

pts = UnwrapElement(IN[0])


profileLoops = []

outerProfileLoop = CurveLoop()

profileLoops.Add(outerProfileLoop)



#create filled region
for j in range(0,len(pts)):
	for i in range(0,len(pts[j])-1):
		outerProfileLoop.Append(Autodesk.Revit.DB.Line.CreateBound(XYZ(pts[j][i].X,pts[j][i].Y,pts[j][i].Z),XYZ(pts[j][i+1].X,pts[j][i+1].Y,pts[j][i+1].Z)))


#Assign your output to the OUT variable.
OUT = profileLoops</Script>
    </PythonNodeModels.PythonNode>
    <Dynamo.Nodes.DSModelElementsSelection guid="0cba7c1a-7fcb-4b2d-b495-ebe0968491b9" type="Dynamo.Nodes.DSModelElementsSelection" nickname="Select Model Elements" x="-637.90297383533" y="7.72130904209212" isVisible="true" isUpstreamVisible="true" lacing="Disabled" isSelectedInput="True" IsFrozen="false" isPinned="false">
      <instance id="581fbb4d-ff48-4a85-9e48-a070aede3a1a-002024f3" />
      <instance id="581fbb4d-ff48-4a85-9e48-a070aede3a1a-002024f4" />
      <instance id="581fbb4d-ff48-4a85-9e48-a070aede3a1a-002024f5" />
      <instance id="581fbb4d-ff48-4a85-9e48-a070aede3a1a-002024f6" />
    </Dynamo.Nodes.DSModelElementsSelection>
    <Dynamo.Graph.Nodes.CodeBlockNodeModel guid="44b7668e-c560-45ed-9a10-13d7ce3ab234" type="Dynamo.Graph.Nodes.CodeBlockNodeModel" nickname="Code Block" x="656.676848165537" y="116.500911478494" isVisible="true" isUpstreamVisible="true" lacing="Disabled" isSelectedInput="False" IsFrozen="false" isPinned="false" CodeText="0.003281;" ShouldFocus="false" />
    <Dynamo.Graph.Nodes.ZeroTouch.DSFunction guid="82418951-f6c6-4c42-af03-2c8ad7d46de5" type="Dynamo.Graph.Nodes.ZeroTouch.DSFunction" nickname="Element.Curves" x="-327.98018866323" y="6.08471050538697" isVisible="true" isUpstreamVisible="true" lacing="Shortest" isSelectedInput="False" IsFrozen="false" isPinned="true" assembly="RevitNodes.dll" function="Revit.Elements.Element.Curves">
      <PortInfo index="0" default="False" />
    </Dynamo.Graph.Nodes.ZeroTouch.DSFunction>
    <PythonNodeModels.PythonNode guid="cf687bef-f635-446e-a3ca-7a922a9b854e" type="PythonNodeModels.PythonNode" nickname="Python Script" x="158.887708476851" y="-44.8264678613748" isVisible="true" isUpstreamVisible="true" lacing="Disabled" isSelectedInput="False" IsFrozen="false" isPinned="true" inputcount="1">
      <PortInfo index="0" default="False" />
      <Script>#Copyright(c) 2015, Konrad Sobon
# @arch_laboratory, http://archi-lab.net

import clr
clr.AddReference('ProtoGeometry')
from Autodesk.DesignScript.Geometry import *

#The inputs to this node will be stored as a list in the IN variable.
dataEnteringNode = IN

inputCurves = IN[0]

#join/group curves function
def groupCurves(Line_List): 
	ignore_distance = 0.1 # Assume points this close or closer to each other are touching 
	Grouped_Lines = [] 
	Queue = set() 
	while Line_List: 
		Shape = [] 
		Queue.add(Line_List.pop()) # Move a line from the Line_List to our queue 
		while Queue: 
			Current_Line = Queue.pop() 
			Shape.append(Current_Line) 
			for Potential_Match in Line_List: 
				Points = (Potential_Match.StartPoint, Potential_Match.EndPoint)
				for P1 in Points: 
					for P2 in (Current_Line.StartPoint, Current_Line.EndPoint): 
						distance = P1.DistanceTo(P2) 
						if distance &lt;= ignore_distance: 
							Queue.add(Potential_Match) 
			Line_List = [item for item in Line_List if item not in Queue]
		Grouped_Lines.append(Shape) 
	return Grouped_Lines

OUT = groupCurves(inputCurves)</Script>
    </PythonNodeModels.PythonNode>
    <Dynamo.Graph.Nodes.ZeroTouch.DSFunction guid="cbddac4f-624e-485e-b4fb-34977218ae43" type="Dynamo.Graph.Nodes.ZeroTouch.DSFunction" nickname="Geometry.Scale" x="1010.889914772" y="96.6490357006625" isVisible="true" isUpstreamVisible="true" lacing="Shortest" isSelectedInput="False" IsFrozen="false" isPinned="true" assembly="ProtoGeometry.dll" function="Autodesk.DesignScript.Geometry.Geometry.Scale@double">
      <PortInfo index="0" default="False" />
      <PortInfo index="1" default="True" />
    </Dynamo.Graph.Nodes.ZeroTouch.DSFunction>
    <Dynamo.Graph.Nodes.ZeroTouch.DSFunction guid="da2fd28a-1da2-4dc3-83cb-333d0bb8ccea" type="Dynamo.Graph.Nodes.ZeroTouch.DSFunction" nickname="Flatten" x="-76.4603476336869" y="-42.0427461812398" isVisible="true" isUpstreamVisible="true" lacing="Shortest" isSelectedInput="False" IsFrozen="false" isPinned="false" assembly="BuiltIn" function="Flatten@var[]..[]">
      <PortInfo index="0" default="False" />
    </Dynamo.Graph.Nodes.ZeroTouch.DSFunction>
    <Dynamo.Graph.Nodes.ZeroTouch.DSFunction guid="6862c11c-2ae3-4b8b-858f-fb3ed21583fa" type="Dynamo.Graph.Nodes.ZeroTouch.DSFunction" nickname="Curve.EndPoint" x="387.778310183988" y="-158.428254607035" isVisible="true" isUpstreamVisible="true" lacing="Shortest" isSelectedInput="False" IsFrozen="false" isPinned="true" assembly="ProtoGeometry.dll" function="Autodesk.DesignScript.Geometry.Curve.EndPoint">
      <PortInfo index="0" default="False" />
    </Dynamo.Graph.Nodes.ZeroTouch.DSFunction>
    <PythonNodeModels.PythonNode guid="22ec4a32-9532-4902-bfa9-bd89c6bd1d04" type="PythonNodeModels.PythonNode" nickname="Python Script" x="746.472405565818" y="-215.70978689611" isVisible="true" isUpstreamVisible="true" lacing="Disabled" isSelectedInput="False" IsFrozen="false" isPinned="true" inputcount="1">
      <PortInfo index="0" default="False" />
      <Script>list = IN[0]

for l in list:
	l.append(l[0])



OUT = list</Script>
    </PythonNodeModels.PythonNode>
    <Dynamo.Graph.Nodes.ZeroTouch.DSFunction guid="464bcf00-b042-49fa-aaab-029f653202e2" type="Dynamo.Graph.Nodes.ZeroTouch.DSFunction" nickname="Flatten" x="1028.79446903304" y="-18.2551967327875" isVisible="true" isUpstreamVisible="true" lacing="Shortest" isSelectedInput="False" IsFrozen="false" isPinned="false" assembly="BuiltIn" function="Flatten@var[]..[]">
      <PortInfo index="0" default="False" />
    </Dynamo.Graph.Nodes.ZeroTouch.DSFunction>
  </Elements>
  <Connectors>
    <Dynamo.Graph.Connectors.ConnectorModel start="2399b948-53fe-463a-a385-965aa4a4bb71" start_index="0" end="80bdc9c3-00ee-42ed-bfda-f95c2bd05555" end_index="0" portType="0" />
    <Dynamo.Graph.Connectors.ConnectorModel start="9938f34c-af29-4768-b442-f696c9a5884e" start_index="0" end="49aa51d5-d674-4ab0-857d-ba77dd0649af" end_index="0" portType="0" />
    <Dynamo.Graph.Connectors.ConnectorModel start="49aa51d5-d674-4ab0-857d-ba77dd0649af" start_index="0" end="9bc2fa4a-afe9-4a69-b5ec-16c75248adf8" end_index="0" portType="0" />
    <Dynamo.Graph.Connectors.ConnectorModel start="c856d12a-4878-4a5f-9312-b55774486664" start_index="0" end="9938f34c-af29-4768-b442-f696c9a5884e" end_index="0" portType="0" />
    <Dynamo.Graph.Connectors.ConnectorModel start="99a6d6cf-a13b-4e77-9527-08e5412ba5e1" start_index="0" end="750b5e74-45ef-4b8f-9569-0ae2421f4b80" end_index="0" portType="0" />
    <Dynamo.Graph.Connectors.ConnectorModel start="dff0cbe5-6973-40c2-9f2a-1c123e245729" start_index="1" end="99a6d6cf-a13b-4e77-9527-08e5412ba5e1" end_index="0" portType="0" />
    <Dynamo.Graph.Connectors.ConnectorModel start="750b5e74-45ef-4b8f-9569-0ae2421f4b80" start_index="0" end="10ca2474-1114-4037-a672-7adc98c2fb05" end_index="0" portType="0" />
    <Dynamo.Graph.Connectors.ConnectorModel start="b3363fa6-2b87-4097-b81a-366df080d99d" start_index="0" end="750b5e74-45ef-4b8f-9569-0ae2421f4b80" end_index="1" portType="0" />
    <Dynamo.Graph.Connectors.ConnectorModel start="8e4671ca-d857-4534-8361-8603e676a43b" start_index="0" end="d4161f11-806b-41ff-b3f2-4e480195411b" end_index="0" portType="0" />
    <Dynamo.Graph.Connectors.ConnectorModel start="605f0c86-c2a2-41c4-b5ba-71e49b9a858c" start_index="0" end="d6723f5d-17fc-4ddd-8636-9ea5d46f1e1a" end_index="2" portType="0" />
    <Dynamo.Graph.Connectors.ConnectorModel start="d4161f11-806b-41ff-b3f2-4e480195411b" start_index="0" end="605f0c86-c2a2-41c4-b5ba-71e49b9a858c" end_index="0" portType="0" />
    <Dynamo.Graph.Connectors.ConnectorModel start="d6723f5d-17fc-4ddd-8636-9ea5d46f1e1a" start_index="0" end="a151c867-ab47-4dff-a327-a79c93e44a66" end_index="1" portType="0" />
    <Dynamo.Graph.Connectors.ConnectorModel start="d6723f5d-17fc-4ddd-8636-9ea5d46f1e1a" start_index="0" end="0ab87f13-f78d-4d40-8fb4-aa4c339bf1af" end_index="1" portType="0" />
    <Dynamo.Graph.Connectors.ConnectorModel start="d6723f5d-17fc-4ddd-8636-9ea5d46f1e1a" start_index="0" end="b21d70ae-ea62-4479-bfde-275780c2e6cd" end_index="1" portType="0" />
    <Dynamo.Graph.Connectors.ConnectorModel start="884dbd57-db28-4efc-bd5e-9e8200f9dc5e" start_index="0" end="a151c867-ab47-4dff-a327-a79c93e44a66" end_index="2" portType="0" />
    <Dynamo.Graph.Connectors.ConnectorModel start="884dbd57-db28-4efc-bd5e-9e8200f9dc5e" start_index="0" end="0ab87f13-f78d-4d40-8fb4-aa4c339bf1af" end_index="2" portType="0" />
    <Dynamo.Graph.Connectors.ConnectorModel start="884dbd57-db28-4efc-bd5e-9e8200f9dc5e" start_index="0" end="b21d70ae-ea62-4479-bfde-275780c2e6cd" end_index="2" portType="0" />
    <Dynamo.Graph.Connectors.ConnectorModel start="212e785f-69a4-4c1a-85a5-e8ec1ec2ebb3" start_index="0" end="884dbd57-db28-4efc-bd5e-9e8200f9dc5e" end_index="0" portType="0" />
    <Dynamo.Graph.Connectors.ConnectorModel start="5cf3dbc1-2780-4e50-9c2c-3067ebe3050b" start_index="0" end="212e785f-69a4-4c1a-85a5-e8ec1ec2ebb3" end_index="0" portType="0" />
    <Dynamo.Graph.Connectors.ConnectorModel start="5a9d6d11-4b56-4adf-8ef8-35d4af7b2180" start_index="0" end="c856d12a-4878-4a5f-9312-b55774486664" end_index="0" portType="0" />
    <Dynamo.Graph.Connectors.ConnectorModel start="b1d9577b-6a1d-45d0-9afa-3df07afc1c71" start_index="0" end="d1b40fc9-39e0-4ce6-8ee3-4386e867f9cf" end_index="1" portType="0" />
    <Dynamo.Graph.Connectors.ConnectorModel start="d1b40fc9-39e0-4ce6-8ee3-4386e867f9cf" start_index="0" end="41b9cb05-ede5-4a2b-bd10-6eb20ae187a6" end_index="0" portType="0" />
    <Dynamo.Graph.Connectors.ConnectorModel start="d1b40fc9-39e0-4ce6-8ee3-4386e867f9cf" start_index="0" end="b21d70ae-ea62-4479-bfde-275780c2e6cd" end_index="0" portType="0" />
    <Dynamo.Graph.Connectors.ConnectorModel start="ff466da0-09b8-4418-9719-431e38030f89" start_index="0" end="82f5f31a-a92d-4794-ac99-3d35efe58679" end_index="0" portType="0" />
    <Dynamo.Graph.Connectors.ConnectorModel start="82f5f31a-a92d-4794-ac99-3d35efe58679" start_index="0" end="77c55e31-4d28-4d41-888c-e3abde59d2d3" end_index="0" portType="0" />
    <Dynamo.Graph.Connectors.ConnectorModel start="acad87ae-f77a-40c8-bca5-4fdf38ad7efc" start_index="0" end="7d5adb8f-9037-442c-9ad6-706c3e009aed" end_index="0" portType="0" />
    <Dynamo.Graph.Connectors.ConnectorModel start="acad87ae-f77a-40c8-bca5-4fdf38ad7efc" start_index="0" end="568eb24c-a59a-491c-9586-b93bbd86ea39" end_index="0" portType="0" />
    <Dynamo.Graph.Connectors.ConnectorModel start="568eb24c-a59a-491c-9586-b93bbd86ea39" start_index="0" end="cde7a1f3-c246-4e71-968c-b9ec9d837627" end_index="0" portType="0" />
    <Dynamo.Graph.Connectors.ConnectorModel start="5f64eb84-28b9-4d50-b344-e56b6568c70a" start_index="0" end="83908e74-0d95-477a-94fd-6cfdc3f0058f" end_index="0" portType="0" />
    <Dynamo.Graph.Connectors.ConnectorModel start="cde7a1f3-c246-4e71-968c-b9ec9d837627" start_index="0" end="5f64eb84-28b9-4d50-b344-e56b6568c70a" end_index="0" portType="0" />
    <Dynamo.Graph.Connectors.ConnectorModel start="884755f4-5f90-482c-a9e7-c2655cd615d7" start_index="0" end="78302f25-5af7-43d8-9038-b4ec7a948bf6" end_index="0" portType="0" />
    <Dynamo.Graph.Connectors.ConnectorModel start="78302f25-5af7-43d8-9038-b4ec7a948bf6" start_index="0" end="685aa52c-3531-4221-aafb-aee7014048c2" end_index="0" portType="0" />
    <Dynamo.Graph.Connectors.ConnectorModel start="685aa52c-3531-4221-aafb-aee7014048c2" start_index="0" end="0367fdd6-799a-4a33-bd08-4b245c4ba9b7" end_index="2" portType="0" />
    <Dynamo.Graph.Connectors.ConnectorModel start="8ccbbeab-8af0-4973-97a7-b98201512047" start_index="0" end="a7a994a8-27a7-47e6-814b-1dcdf923a87d" end_index="0" portType="0" />
    <Dynamo.Graph.Connectors.ConnectorModel start="0367fdd6-799a-4a33-bd08-4b245c4ba9b7" start_index="0" end="82a936d3-14af-42b5-8083-938823c82a6e" end_index="1" portType="0" />
    <Dynamo.Graph.Connectors.ConnectorModel start="6d8895b9-f79a-4a8d-abbc-f07a4f35a9ae" start_index="0" end="82a936d3-14af-42b5-8083-938823c82a6e" end_index="2" portType="0" />
    <Dynamo.Graph.Connectors.ConnectorModel start="5837f148-4045-4a18-b9fe-1ba5b4206d1e" start_index="0" end="6d8895b9-f79a-4a8d-abbc-f07a4f35a9ae" end_index="0" portType="0" />
    <Dynamo.Graph.Connectors.ConnectorModel start="9f4a63e9-257e-4b88-b0b2-f2a3e3c5a1ea" start_index="0" end="5837f148-4045-4a18-b9fe-1ba5b4206d1e" end_index="0" portType="0" />
    <Dynamo.Graph.Connectors.ConnectorModel start="83908e74-0d95-477a-94fd-6cfdc3f0058f" start_index="0" end="bd7e4907-7702-400a-b106-a1170f60e633" end_index="0" portType="0" />
    <Dynamo.Graph.Connectors.ConnectorModel start="bd7e4907-7702-400a-b106-a1170f60e633" start_index="0" end="9e89a989-ba6a-4ddb-8fce-56288a20141e" end_index="0" portType="0" />
    <Dynamo.Graph.Connectors.ConnectorModel start="d8f69566-e396-4579-ac3d-eebef71bea5e" start_index="0" end="2399b948-53fe-463a-a385-965aa4a4bb71" end_index="0" portType="0" />
    <Dynamo.Graph.Connectors.ConnectorModel start="77c55e31-4d28-4d41-888c-e3abde59d2d3" start_index="0" end="d8f69566-e396-4579-ac3d-eebef71bea5e" end_index="0" portType="0" />
    <Dynamo.Graph.Connectors.ConnectorModel start="80bdc9c3-00ee-42ed-bfda-f95c2bd05555" start_index="0" end="d1b40fc9-39e0-4ce6-8ee3-4386e867f9cf" end_index="0" portType="0" />
    <Dynamo.Graph.Connectors.ConnectorModel start="0cba7c1a-7fcb-4b2d-b495-ebe0968491b9" start_index="0" end="82418951-f6c6-4c42-af03-2c8ad7d46de5" end_index="0" portType="0" />
    <Dynamo.Graph.Connectors.ConnectorModel start="44b7668e-c560-45ed-9a10-13d7ce3ab234" start_index="0" end="cbddac4f-624e-485e-b4fb-34977218ae43" end_index="1" portType="0" />
    <Dynamo.Graph.Connectors.ConnectorModel start="82418951-f6c6-4c42-af03-2c8ad7d46de5" start_index="0" end="da2fd28a-1da2-4dc3-83cb-333d0bb8ccea" end_index="0" portType="0" />
    <Dynamo.Graph.Connectors.ConnectorModel start="cf687bef-f635-446e-a3ca-7a922a9b854e" start_index="0" end="6862c11c-2ae3-4b8b-858f-fb3ed21583fa" end_index="0" portType="0" />
    <Dynamo.Graph.Connectors.ConnectorModel start="da2fd28a-1da2-4dc3-83cb-333d0bb8ccea" start_index="0" end="cf687bef-f635-446e-a3ca-7a922a9b854e" end_index="0" portType="0" />
    <Dynamo.Graph.Connectors.ConnectorModel start="6862c11c-2ae3-4b8b-858f-fb3ed21583fa" start_index="0" end="22ec4a32-9532-4902-bfa9-bd89c6bd1d04" end_index="0" portType="0" />
    <Dynamo.Graph.Connectors.ConnectorModel start="22ec4a32-9532-4902-bfa9-bd89c6bd1d04" start_index="0" end="464bcf00-b042-49fa-aaab-029f653202e2" end_index="0" portType="0" />
    <Dynamo.Graph.Connectors.ConnectorModel start="464bcf00-b042-49fa-aaab-029f653202e2" start_index="0" end="cbddac4f-624e-485e-b4fb-34977218ae43" end_index="0" portType="0" />
  </Connectors>
  <Notes />
  <Annotations>
    <Dynamo.Graph.Annotations.AnnotationModel guid="b7550c72-79b3-42ff-a946-223a6bf680ff" annotationText="GROUP CURVES" left="988.175878894304" top="-1180.42657265005" width="144" height="175" fontSize="30" InitialTop="-1098.42657265005" InitialHeight="123" TextblockHeight="72" backgrouund="#FFC1D676">
      <Models ModelGuid="49aa51d5-d674-4ab0-857d-ba77dd0649af" />
    </Dynamo.Graph.Annotations.AnnotationModel>
    <Dynamo.Graph.Annotations.AnnotationModel guid="0a05d4f2-72cf-48d9-8185-1fcdeeecaa97" annotationText="&lt;Click here to edit the group title&gt;" left="-616.88269106485" top="879.398667585241" width="1337.99448157347" height="425.323936390829" fontSize="30" InitialTop="925.398667585241" InitialHeight="409.323936390833" TextblockHeight="36" backgrouund="#FFC1D676">
      <Models ModelGuid="884755f4-5f90-482c-a9e7-c2655cd615d7" />
      <Models ModelGuid="78302f25-5af7-43d8-9038-b4ec7a948bf6" />
      <Models ModelGuid="685aa52c-3531-4221-aafb-aee7014048c2" />
      <Models ModelGuid="8ccbbeab-8af0-4973-97a7-b98201512047" />
      <Models ModelGuid="0367fdd6-799a-4a33-bd08-4b245c4ba9b7" />
      <Models ModelGuid="a7a994a8-27a7-47e6-814b-1dcdf923a87d" />
      <Models ModelGuid="82a936d3-14af-42b5-8083-938823c82a6e" />
      <Models ModelGuid="6d8895b9-f79a-4a8d-abbc-f07a4f35a9ae" />
      <Models ModelGuid="5837f148-4045-4a18-b9fe-1ba5b4206d1e" />
      <Models ModelGuid="9f4a63e9-257e-4b88-b0b2-f2a3e3c5a1ea" />
    </Dynamo.Graph.Annotations.AnnotationModel>
    <Dynamo.Graph.Annotations.AnnotationModel guid="7f637549-554c-457b-80ae-f948e1203e41" annotationText="works for one area" left="1468.83422421627" top="323.732574279249" width="232" height="227" fontSize="30" InitialTop="405.732574279249" InitialHeight="175" TextblockHeight="72" backgrouund="#FFC1D676">
      <Models ModelGuid="a151c867-ab47-4dff-a327-a79c93e44a66" />
    </Dynamo.Graph.Annotations.AnnotationModel>
  </Annotations>
  <Presets />
  <Cameras>
    <Camera Name="Background Preview" eyeX="-41523.19140625" eyeY="126796.5546875" eyeZ="-9459.291015625" lookX="71361.8828125" lookY="-127530.5703125" lookZ="-19536.634765625" upX="0.711110234260559" upY="0.675590217113495" upZ="-0.19467955827713" />
  </Cameras>
</Workspace>