<Workspace Version="0.7.2.2921" X="18.079164120775" Y="194.890464573369" zoom="0.677842740966181" Description="Gets the owner view of a given Revit element (if possible)" Category="Clockwork.Revit.Elements.Element.Query" Name="Element.OwnerView" ID="a0fc8138-f7bc-4425-abe6-2ef1b411d447">
  <Elements>
    <Dynamo.Nodes.Function type="Dynamo.Nodes.Function" guid="d8505f77-55a9-4727-8e8c-860b73e4178c" nickname="Turn Into List" x="199" y="26" isVisible="true" isUpstreamVisible="true" lacing="Disabled">
      <ID value="cd09ad33-8c34-4850-ac26-24448d92c38f" />
      <Name value="Turn Into List" />
      <Description value="Turns an element (or a nested list) into a flat list" />
      <Inputs>
        <Input value="item" />
      </Inputs>
      <Outputs>
        <Output value="" />
      </Outputs>
    </Dynamo.Nodes.Function>
    <Dynamo.Nodes.Symbol type="Dynamo.Nodes.Symbol" guid="1da84079-f5bd-46db-92fe-331f3856ffe8" nickname="Input" x="44.1737704918032" y="-39.3540983606557" isVisible="true" isUpstreamVisible="true" lacing="Disabled">
      <Symbol value="element(s)" />
    </Dynamo.Nodes.Symbol>
    <Dynamo.Nodes.Output type="Dynamo.Nodes.Output" guid="33a866fd-53e7-4d29-b752-0e046772155c" nickname="Output" x="892.186885245902" y="-37.6295081967213" isVisible="true" isUpstreamVisible="true" lacing="Disabled">
      <Symbol value="view(s)" />
    </Dynamo.Nodes.Output>
    <Dynamo.Nodes.Function type="Dynamo.Nodes.Function" guid="891228fa-e27b-4b78-8e76-68c3e1b65d84" nickname="ReturnListOrSingleValue" x="600.186885245902" y="-37.6295081967213" isVisible="true" isUpstreamVisible="true" lacing="Disabled">
      <ID value="44ac4888-4aa4-49a9-9344-23b729c11df9" />
      <Name value="ReturnListOrSingleValue" />
      <Description value="If the item in input #1 is not a list, only the first item of the list in input #2 will be returned." />
      <Inputs>
        <Input value="item #1 (unknown)" />
        <Input value="item #2 (list)" />
      </Inputs>
      <Outputs>
        <Output value="" />
      </Outputs>
    </Dynamo.Nodes.Function>
    <DSIronPythonNode.PythonNode type="DSIronPythonNode.PythonNode" guid="e66c9e5f-ed44-4ac5-a30d-89bbf1b39d98" nickname="Python Script" x="404" y="26" isVisible="true" isUpstreamVisible="true" lacing="Disabled" inputcount="1">
      <Script>import clr
clr.AddReference('RevitAPI')
from Autodesk.Revit.DB import *

clr.AddReference("RevitNodes")
import Revit
clr.ImportExtensions(Revit.Elements)

clr.AddReference("RevitServices")
import RevitServices
from RevitServices.Persistence import DocumentManager

doc = DocumentManager.Instance.CurrentDBDocument
items = UnwrapElement(IN[0])
elementlist = list()
for item in items:
	try:
		elementlist.append(doc.GetElement(item.OwnerViewId).ToDSType(True))
	except:
		elementlist.append(list())
OUT = elementlist</Script>
    </DSIronPythonNode.PythonNode>
  </Elements>
  <Connectors>
    <Dynamo.Models.ConnectorModel start="d8505f77-55a9-4727-8e8c-860b73e4178c" start_index="0" end="e66c9e5f-ed44-4ac5-a30d-89bbf1b39d98" end_index="0" portType="0" />
    <Dynamo.Models.ConnectorModel start="1da84079-f5bd-46db-92fe-331f3856ffe8" start_index="0" end="d8505f77-55a9-4727-8e8c-860b73e4178c" end_index="0" portType="0" />
    <Dynamo.Models.ConnectorModel start="1da84079-f5bd-46db-92fe-331f3856ffe8" start_index="0" end="891228fa-e27b-4b78-8e76-68c3e1b65d84" end_index="0" portType="0" />
    <Dynamo.Models.ConnectorModel start="891228fa-e27b-4b78-8e76-68c3e1b65d84" start_index="0" end="33a866fd-53e7-4d29-b752-0e046772155c" end_index="0" portType="0" />
    <Dynamo.Models.ConnectorModel start="e66c9e5f-ed44-4ac5-a30d-89bbf1b39d98" start_index="0" end="891228fa-e27b-4b78-8e76-68c3e1b65d84" end_index="1" portType="0" />
  </Connectors>
  <Notes />
</Workspace>