<Workspace Version="0.7.2.6209" X="30" Y="208.462536023055" zoom="1.84726224783862" Description="Transform a slab shape based on a list of XYZs. PLEASE NOTE: Will reset any previous edits on the slab shape." Category="Clockwork.Revit.Elements.RoofOrFloor.Actions" Name="RoofOrFloor.SlabShapeByPoints" ID="d145e1db-d069-452f-b46d-7ad9b0fd906d">
  <Elements>
    <Dynamo.Nodes.Symbol type="Dynamo.Nodes.Symbol" guid="753cd253-79a4-4c4b-ab10-aee58856bc74" nickname="Input" x="0" y="0" isVisible="true" isUpstreamVisible="true" lacing="Disabled">
      <Symbol value="XYZs" />
    </Dynamo.Nodes.Symbol>
    <Dynamo.Nodes.Function type="Dynamo.Nodes.Function" guid="f6da18fc-3327-4d53-9baf-51ebf53e264a" nickname="Turn Into List" x="199" y="29" isVisible="true" isUpstreamVisible="true" lacing="Disabled">
      <ID value="cd09ad33-8c34-4850-ac26-24448d92c38f" />
      <Name value="Turn Into List" />
      <Description value="Turns an element (or a nested list) into a flat list" />
      <Inputs>
        <Input value="item" />
      </Inputs>
      <Outputs>
        <Output value="" />
      </Outputs>
    </Dynamo.Nodes.Function>
    <Dynamo.Nodes.Output type="Dynamo.Nodes.Output" guid="8391a372-b113-4e1a-b6ea-aa1f0875826c" nickname="Output" x="628" y="29" isVisible="true" isUpstreamVisible="true" lacing="Disabled">
      <Symbol value="Floor/Roof" />
    </Dynamo.Nodes.Output>
    <DSIronPythonNode.PythonNode type="DSIronPythonNode.PythonNode" guid="abe578e4-b2e7-4fbd-a9a7-f088f5d07c8f" nickname="Python Script" x="404" y="29" isVisible="true" isUpstreamVisible="true" lacing="Disabled" inputcount="2">
      <Script>import clr
clr.AddReference('RevitAPI')
from Autodesk.Revit.DB import *

clr.AddReference("RevitNodes")
import Revit
clr.ImportExtensions(Revit.GeometryConversion)

clr.AddReference("RevitServices")
import RevitServices
from RevitServices.Persistence import DocumentManager
from RevitServices.Transactions import TransactionManager

doc = DocumentManager.Instance.CurrentDBDocument
xyzs = IN[0]
slabshape = UnwrapElement(IN[1])
successlist = list()
faillist = list()

TransactionManager.Instance.EnsureInTransaction(doc)
slabshape.SlabShapeEditor.ResetSlabShape()
for item in xyzs:
	slabshape.SlabShapeEditor.DrawPoint(item.ToXyz())
TransactionManager.Instance.TransactionTaskDone()

OUT = slabshape</Script>
    </DSIronPythonNode.PythonNode>
    <Dynamo.Nodes.Symbol type="Dynamo.Nodes.Symbol" guid="386d7dbc-4d19-4934-b5e2-d1bfa63d2158" nickname="Input" x="0" y="84" isVisible="true" isUpstreamVisible="true" lacing="Disabled">
      <Symbol value="Floor/Roof" />
    </Dynamo.Nodes.Symbol>
  </Elements>
  <Connectors>
    <Dynamo.Models.ConnectorModel start="753cd253-79a4-4c4b-ab10-aee58856bc74" start_index="0" end="f6da18fc-3327-4d53-9baf-51ebf53e264a" end_index="0" portType="0" />
    <Dynamo.Models.ConnectorModel start="f6da18fc-3327-4d53-9baf-51ebf53e264a" start_index="0" end="abe578e4-b2e7-4fbd-a9a7-f088f5d07c8f" end_index="0" portType="0" />
    <Dynamo.Models.ConnectorModel start="abe578e4-b2e7-4fbd-a9a7-f088f5d07c8f" start_index="0" end="8391a372-b113-4e1a-b6ea-aa1f0875826c" end_index="0" portType="0" />
    <Dynamo.Models.ConnectorModel start="386d7dbc-4d19-4934-b5e2-d1bfa63d2158" start_index="0" end="abe578e4-b2e7-4fbd-a9a7-f088f5d07c8f" end_index="1" portType="0" />
  </Connectors>
  <Notes />
</Workspace>