<Workspace Version="0.7.4.3180" X="30" Y="182.586956521739" zoom="0.652173913043478" Description="Returns all vertices of a given surface" Category="Clockwork.Geometry.Surface.Query" Name="Surface.Vertices" ID="5760365c-cf13-4d72-9a45-4f22c372e287">
  <Elements>
    <Dynamo.Nodes.DSFunction type="Dynamo.Nodes.DSFunction" guid="511992a5-fda9-4e29-af4d-b8aaed7f0037" nickname="Surface.PerimeterCurves" x="386" y="26" isVisible="true" isUpstreamVisible="true" lacing="Shortest" assembly="ProtoGeometry.dll" function="Autodesk.DesignScript.Geometry.Surface.PerimeterCurves" />
    <Dynamo.Nodes.Symbol type="Dynamo.Nodes.Symbol" guid="264da024-33a3-4f78-9e9e-df4caefc7560" nickname="Input" x="26.0666666666666" y="-40.6666666666667" isVisible="true" isUpstreamVisible="true" lacing="Disabled">
      <Symbol value="Surface(s)" />
    </Dynamo.Nodes.Symbol>
    <Dynamo.Nodes.Output type="Dynamo.Nodes.Output" guid="0deaa79b-730d-40b2-b250-e6b0ce35d107" nickname="Output" x="1139.26666666667" y="-41.4" isVisible="true" isUpstreamVisible="true" lacing="Disabled">
      <Symbol value="Vertices" />
    </Dynamo.Nodes.Output>
    <Dynamo.Nodes.Function type="Dynamo.Nodes.Function" guid="3ef89b20-1a7f-44dc-86aa-b13264f54e5b" nickname="Turn Into List" x="181" y="26" isVisible="true" isUpstreamVisible="true" lacing="Disabled">
      <ID value="cd09ad33-8c34-4850-ac26-24448d92c38f" />
      <Name value="Turn Into List" />
      <Description value="Turns an element (or a nested list) into a flat list" />
      <Inputs>
        <Input value="item" />
      </Inputs>
      <Outputs>
        <Output value="" />
      </Outputs>
    </Dynamo.Nodes.Function>
    <Dynamo.Nodes.Function type="Dynamo.Nodes.Function" guid="64447c80-26eb-4503-8d7d-ec357f54437c" nickname="ReturnListOrSingleValue" x="864.133333333333" y="-39.8666666666666" isVisible="true" isUpstreamVisible="true" lacing="Disabled">
      <ID value="44ac4888-4aa4-49a9-9344-23b729c11df9" />
      <Name value="ReturnListOrSingleValue" />
      <Description value="If the item in input #1 is not a list, only the first item of the list in input #2 will be returned." />
      <Inputs>
        <Input value="item #1 (unknown)" />
        <Input value="item #2 (list)" />
      </Inputs>
      <Outputs>
        <Output value="" />
      </Outputs>
    </Dynamo.Nodes.Function>
    <Dynamo.Nodes.DSFunction type="Dynamo.Nodes.DSFunction" guid="89d6b7fd-3c39-469d-b42a-0cb7c8df911b" nickname="Curve.StartPoint" x="652" y="26" isVisible="true" isUpstreamVisible="true" lacing="Shortest" assembly="ProtoGeometry.dll" function="Autodesk.DesignScript.Geometry.Curve.StartPoint" />
  </Elements>
  <Connectors>
    <Dynamo.Models.ConnectorModel start="511992a5-fda9-4e29-af4d-b8aaed7f0037" start_index="0" end="89d6b7fd-3c39-469d-b42a-0cb7c8df911b" end_index="0" portType="0" />
    <Dynamo.Models.ConnectorModel start="264da024-33a3-4f78-9e9e-df4caefc7560" start_index="0" end="3ef89b20-1a7f-44dc-86aa-b13264f54e5b" end_index="0" portType="0" />
    <Dynamo.Models.ConnectorModel start="264da024-33a3-4f78-9e9e-df4caefc7560" start_index="0" end="64447c80-26eb-4503-8d7d-ec357f54437c" end_index="0" portType="0" />
    <Dynamo.Models.ConnectorModel start="3ef89b20-1a7f-44dc-86aa-b13264f54e5b" start_index="0" end="511992a5-fda9-4e29-af4d-b8aaed7f0037" end_index="0" portType="0" />
    <Dynamo.Models.ConnectorModel start="64447c80-26eb-4503-8d7d-ec357f54437c" start_index="0" end="0deaa79b-730d-40b2-b250-e6b0ce35d107" end_index="0" portType="0" />
    <Dynamo.Models.ConnectorModel start="89d6b7fd-3c39-469d-b42a-0cb7c8df911b" start_index="0" end="64447c80-26eb-4503-8d7d-ec357f54437c" end_index="1" portType="0" />
  </Connectors>
  <Notes />
</Workspace>