<Workspace Version="0.7.2.6209" X="30" Y="258.48132780083" zoom="2.6597510373444" Description="Returns an XYZ of 0,-1,0" Category="Clockwork.Geometry.Vector.Create.Axes" Name="Vector.YAxis (Negative)" ID="b88792f7-0b64-420d-81ca-43a08eb57bb4">
  <Elements>
    <Dynamo.Nodes.Output type="Dynamo.Nodes.Output" guid="4eadf7d8-0216-448d-98c7-271f48e71de7" nickname="Output" x="412" y="0" isVisible="true" isUpstreamVisible="true" lacing="Disabled">
      <Symbol value="0,-1,0" />
    </Dynamo.Nodes.Output>
    <Dynamo.Nodes.DSFunction type="Dynamo.Nodes.DSFunction" guid="f31545a4-6ec9-48d3-8a8f-556552228f28" nickname="Vector.Reverse" x="191" y="0" isVisible="true" isUpstreamVisible="true" lacing="Shortest" assembly="ProtoGeometry.dll" function="Autodesk.DesignScript.Geometry.Vector.Reverse" />
    <Dynamo.Nodes.DSFunction type="Dynamo.Nodes.DSFunction" guid="90f7f21b-e0ee-4259-adb4-c2c918d8346c" nickname="Vector.YAxis" x="0" y="0" isVisible="true" isUpstreamVisible="true" lacing="Shortest" assembly="ProtoGeometry.dll" function="Autodesk.DesignScript.Geometry.Vector.YAxis" />
  </Elements>
  <Connectors>
    <Dynamo.Models.ConnectorModel start="f31545a4-6ec9-48d3-8a8f-556552228f28" start_index="0" end="4eadf7d8-0216-448d-98c7-271f48e71de7" end_index="0" portType="0" />
    <Dynamo.Models.ConnectorModel start="90f7f21b-e0ee-4259-adb4-c2c918d8346c" start_index="0" end="f31545a4-6ec9-48d3-8a8f-556552228f28" end_index="0" portType="0" />
  </Connectors>
  <Notes />
</Workspace>