<Workspace Version="0.7.2.6209" X="30" Y="258.48132780083" zoom="2.6597510373444" Description="Returns an XYZ of -1,0,0" Category="Clockwork.Geometry.Vector.Create.Axes" Name="Vector.XAxis (Negative)" ID="d7173a2c-acdd-452e-acb6-3bd0e12c9037">
  <Elements>
    <Dynamo.Nodes.Output type="Dynamo.Nodes.Output" guid="736d6bae-7579-41a1-929b-c31f20703209" nickname="Output" x="412" y="0" isVisible="true" isUpstreamVisible="true" lacing="Disabled">
      <Symbol value="-1,0,0" />
    </Dynamo.Nodes.Output>
    <Dynamo.Nodes.DSFunction type="Dynamo.Nodes.DSFunction" guid="e4bc0928-de14-4509-9796-bdbfcd23fab3" nickname="Vector.XAxis" x="0" y="7.105427357601E-15" isVisible="true" isUpstreamVisible="true" lacing="Shortest" assembly="ProtoGeometry.dll" function="Autodesk.DesignScript.Geometry.Vector.XAxis" />
    <Dynamo.Nodes.DSFunction type="Dynamo.Nodes.DSFunction" guid="b9aebf8e-55ca-43c7-911d-fda62ae1150e" nickname="Vector.Reverse" x="191" y="7.105427357601E-15" isVisible="true" isUpstreamVisible="true" lacing="Shortest" assembly="ProtoGeometry.dll" function="Autodesk.DesignScript.Geometry.Vector.Reverse" />
  </Elements>
  <Connectors>
    <Dynamo.Models.ConnectorModel start="e4bc0928-de14-4509-9796-bdbfcd23fab3" start_index="0" end="b9aebf8e-55ca-43c7-911d-fda62ae1150e" end_index="0" portType="0" />
    <Dynamo.Models.ConnectorModel start="b9aebf8e-55ca-43c7-911d-fda62ae1150e" start_index="0" end="736d6bae-7579-41a1-929b-c31f20703209" end_index="0" portType="0" />
  </Connectors>
  <Notes />
</Workspace>