<Workspace Version="0.7.2.6209" X="30" Y="258.48132780083" zoom="2.6597510373444" Description="Returns an XYZ of 0,0,-1" Category="Clockwork.Geometry.Vector.Create.Axes" Name="Vector.ZAxis (Negative)" ID="4cb9a1f2-5c84-47cf-b976-28b92bd7f882">
  <Elements>
    <Dynamo.Nodes.Output type="Dynamo.Nodes.Output" guid="2ce34a04-5e34-4abb-af5e-ae8ed66a0b00" nickname="Output" x="412" y="0" isVisible="true" isUpstreamVisible="true" lacing="Disabled">
      <Symbol value="0,0,-1" />
    </Dynamo.Nodes.Output>
    <Dynamo.Nodes.DSFunction type="Dynamo.Nodes.DSFunction" guid="48c8fe29-ee4b-4868-8082-dac54d2b2565" nickname="Vector.Reverse" x="191" y="1.4210854715202E-14" isVisible="true" isUpstreamVisible="true" lacing="Shortest" assembly="ProtoGeometry.dll" function="Autodesk.DesignScript.Geometry.Vector.Reverse" />
    <Dynamo.Nodes.DSFunction type="Dynamo.Nodes.DSFunction" guid="53975328-d799-47b5-a294-0f1a0acfff62" nickname="Vector.ZAxis" x="0" y="7.105427357601E-15" isVisible="true" isUpstreamVisible="true" lacing="Shortest" assembly="ProtoGeometry.dll" function="Autodesk.DesignScript.Geometry.Vector.ZAxis" />
  </Elements>
  <Connectors>
    <Dynamo.Models.ConnectorModel start="48c8fe29-ee4b-4868-8082-dac54d2b2565" start_index="0" end="2ce34a04-5e34-4abb-af5e-ae8ed66a0b00" end_index="0" portType="0" />
    <Dynamo.Models.ConnectorModel start="53975328-d799-47b5-a294-0f1a0acfff62" start_index="0" end="48c8fe29-ee4b-4868-8082-dac54d2b2565" end_index="0" portType="0" />
  </Connectors>
  <Notes />
</Workspace>