<Workspace Version="0.8.2.2392" X="210.60411539663" Y="30.6037274464781" zoom="0.878940113562795" Name="Home" Description="" RunType="Manual" RunPeriod="1000" HasRunWithoutCrash="True">
  <NamespaceResolutionMap />
  <Elements>
    <Dynamo.Nodes.DSModelElementsSelection guid="f8724d8d-89a2-4147-b4d5-5e1f3e025d2f" type="Dynamo.Nodes.DSModelElementsSelection" nickname="Select Model Elements" x="-52.2217869764133" y="196.648252838515" isVisible="true" isUpstreamVisible="true" lacing="Disabled" isSelectedInput="True">
      <instance id="417ebf06-91e3-4c0b-b2af-c2a94e7b775a-000f98dc" />
      <instance id="417ebf06-91e3-4c0b-b2af-c2a94e7b775a-000f99ac" />
      <instance id="afd6fa78-39fd-4217-a0e6-1aed5ce215f5-000f9ac1" />
      <instance id="afd6fa78-39fd-4217-a0e6-1aed5ce215f5-000fa104" />
      <instance id="bc9c7b32-7141-41e8-a285-cd7c20132b83-000fda50" />
    </Dynamo.Nodes.DSModelElementsSelection>
    <Dynamo.Nodes.CodeBlockNodeModel guid="6c4fb897-0f68-4625-a33f-63ad6718c6a0" type="Dynamo.Nodes.CodeBlockNodeModel" nickname="Code Block" x="63.4734952640686" y="374.413201825366" isVisible="true" isUpstreamVisible="true" lacing="Disabled" isSelectedInput="True" CodeText="0;" ShouldFocus="false" />
    <Dynamo.Nodes.CodeBlockNodeModel guid="303a3d34-b9fd-4e67-a042-30428a6002a6" type="Dynamo.Nodes.CodeBlockNodeModel" nickname="Code Block" x="57.9885686237442" y="512" isVisible="true" isUpstreamVisible="true" lacing="Disabled" isSelectedInput="True" CodeText="1;" ShouldFocus="false" />
    <DSIronPythonNode.PythonNode guid="690e08c3-558d-490d-86c0-c0b5e4a57c5a" type="DSIronPythonNode.PythonNode" nickname="Python Script" x="361.232657774706" y="246.890838008998" isVisible="true" isUpstreamVisible="true" lacing="Disabled" isSelectedInput="False" inputcount="2">
      <Script>#Put view on sheet
import clr
clr.AddReference('RevitAPI')
from Autodesk.Revit.DB import *

clr.AddReference("RevitNodes")
import Revit
clr.ImportExtensions(Revit.Elements)

clr.AddReference("RevitServices")
import RevitServices
from RevitServices.Persistence import DocumentManager
from RevitServices.Transactions import TransactionManager

import clr
clr.AddReference('ProtoGeometry')

from Autodesk.DesignScript.Geometry import *

doc = DocumentManager.Instance.CurrentDBDocument
#The inputs to this node will be stored as a list in the IN variables.
grids = UnwrapElement(IN[0])

a = UnwrapElement(IN[1])

if a == "0":
	b = DatumEnds.End0
else:
	b = DatumEnds.End1

	# "Start" the transaction
TransactionManager.Instance.EnsureInTransaction(doc)

view = doc.ActiveView	

for grid in grids:
	
	grid.HideBubbleInView(DatumEnds.End0, view);
	grid.HideBubbleInView(DatumEnds.End1, view);
	grid.ShowBubbleInView(b, view);

# "End" the transaction
TransactionManager.Instance.TransactionTaskDone()


#Assign your output to the OUT variable.
OUT = 0
</Script>
    </DSIronPythonNode.PythonNode>
    <Dynamo.Nodes.Function guid="612baf06-3779-4faf-a2b2-be29c777ff68" type="Dynamo.Nodes.Function" nickname="Object.Class" x="225.842318701851" y="67.1288752063846" isVisible="true" isUpstreamVisible="true" lacing="Shortest" isSelectedInput="False">
      <ID value="e4e8406d-3b77-4822-897b-3f9c08e1cd45" />
      <Name value="Object.Class" />
      <Description value="Gets the input object's class name. Can process lists." />
      <Inputs>
        <Input value="obj" />
      </Inputs>
      <Outputs>
        <Output value="class(str)" />
        <Output value="container" />
      </Outputs>
    </Dynamo.Nodes.Function>
  </Elements>
  <Connectors>
    <Dynamo.Models.ConnectorModel start="f8724d8d-89a2-4147-b4d5-5e1f3e025d2f" start_index="0" end="612baf06-3779-4faf-a2b2-be29c777ff68" end_index="0" portType="0" />
    <Dynamo.Models.ConnectorModel start="f8724d8d-89a2-4147-b4d5-5e1f3e025d2f" start_index="0" end="690e08c3-558d-490d-86c0-c0b5e4a57c5a" end_index="0" portType="0" />
    <Dynamo.Models.ConnectorModel start="6c4fb897-0f68-4625-a33f-63ad6718c6a0" start_index="0" end="690e08c3-558d-490d-86c0-c0b5e4a57c5a" end_index="1" portType="0" />
  </Connectors>
  <Notes>
    <Dynamo.Models.NoteModel guid="9e9f3043-44dc-41f1-8e01-5fccc9a2e946" text="Grid End 0" x="61.0873744382113" y="339.375388941171" />
    <Dynamo.Models.NoteModel guid="8a852e8d-cdeb-41f3-9f15-78a2d30a4756" text="Grid End 1" x="60.4236092526241" y="470.238070090824" />
    <Dynamo.Models.NoteModel guid="1232dd88-a00f-47bb-8451-8f92ad3f1022" text="Swap Bubble Grid Ends" x="358.796917922167" y="211.457093195893" />
    <Dynamo.Models.NoteModel guid="1a742895-352b-4f26-9a5e-b062f2a9cf55" text="Select Grids" x="36.8523133081123" y="155.95600551027" />
  </Notes>
  <Annotations />
  <Presets />
  <Cameras>
    <Camera Name="background_preview" eyeX="10" eyeY="15" eyeZ="10" lookX="-10" lookY="-10" lookZ="-10" />
  </Cameras>
</Workspace>