<Workspace Version="1.3.1.1736" X="-3043.0394664023" Y="-36.9457268580235" zoom="0.597231473997687" ScaleFactor="1" Name="Home" Description="" RunType="Manual" RunPeriod="1000" HasRunWithoutCrash="False">
  <NamespaceResolutionMap>
    <ClassMap partialName="Vector" resolvedName="Autodesk.DesignScript.Geometry.Vector" assemblyName="ProtoGeometry.dll" />
  </NamespaceResolutionMap>
  <Elements>
    <Dynamo.Nodes.DSModelElementsSelection guid="0e236119-9ec6-4f86-8278-f498b08e8a7f" type="Dynamo.Nodes.DSModelElementsSelection" nickname="Select Model Elements" x="1523.85158674712" y="376.436414626635" isVisible="true" isUpstreamVisible="true" lacing="Disabled" isSelectedInput="True" IsFrozen="false" isPinned="false" />
    <PythonNodeModels.PythonNode guid="de2a8540-3d1b-4b54-8bb5-83b6ae52f950" type="PythonNodeModels.PythonNode" nickname="Python Script" x="1923.06559306325" y="343.941699803566" isVisible="true" isUpstreamVisible="true" lacing="Disabled" isSelectedInput="False" IsFrozen="false" isPinned="true" inputcount="2">
      <PortInfo index="0" default="False" />
      <PortInfo index="1" default="False" />
      <Script>import clr
clr.AddReference('ProtoGeometry')
from Autodesk.DesignScript.Geometry import *

# Import DocumentManager and TransactionManager
clr.AddReference("RevitServices")
import RevitServices
from RevitServices.Persistence import DocumentManager
from RevitServices.Transactions import TransactionManager

# Import RevitAPI
clr.AddReference("RevitAPI")
import Autodesk
from Autodesk.Revit.DB import *

clr.AddReference("RevitNodes")
import Revit
clr.ImportExtensions(Revit.GeometryConversion)


doc = DocumentManager.Instance.CurrentDBDocument
uiapp = DocumentManager.Instance.CurrentUIApplication
app = uiapp.Application


grids = UnwrapElement(IN[0])
view = UnwrapElement(IN[1])

curves = []
curvesViews = []

TransactionManager.Instance.EnsureInTransaction(doc)

for g in grids:	
	g.SetDatumExtentType(DatumEnds.End0,view,DatumExtentType.ViewSpecific)
	g.SetDatumExtentType(DatumEnds.End1,view,DatumExtentType.ViewSpecific)
	curves.append(g.GetCurvesInView(DatumExtentType.Model, view))
	curvesViews.append(g.GetCurvesInView(DatumExtentType.ViewSpecific, view))

TransactionManager.Instance.TransactionTaskDone()
	
dynaCrvs = []

for cv in curvesViews:
	dynaCrvs.append(cv[0].ToProtoType())

	
#Assign your outputs to the OUT variable
OUT = curves,curvesViews,dynaCrvs
</Script>
    </PythonNodeModels.PythonNode>
    <Dynamo.Graph.Nodes.CustomNodes.Function guid="a13ec59c-4b21-4305-a02d-718c1b5531d6" type="Dynamo.Graph.Nodes.CustomNodes.Function" nickname="Get Revit ActiveView" x="1623.60452246082" y="518.255356418353" isVisible="true" isUpstreamVisible="true" lacing="Shortest" isSelectedInput="True" IsFrozen="false" isPinned="false">
      <ID value="92960965-5bfc-41ab-9ceb-d61917dfe6c5" />
      <Name value="Get Revit ActiveView" />
      <Description value="Active View" />
      <Inputs />
      <Outputs>
        <Output value="Active.View" />
      </Outputs>
    </Dynamo.Graph.Nodes.CustomNodes.Function>
    <Dynamo.Graph.Nodes.ZeroTouch.DSFunction guid="5c6b4ad9-4bc5-41f3-9549-c0e75d7c373d" type="Dynamo.Graph.Nodes.ZeroTouch.DSFunction" nickname="Curve.Length" x="2318.78762629111" y="210.19543684885" isVisible="true" isUpstreamVisible="true" lacing="Shortest" isSelectedInput="False" IsFrozen="false" isPinned="true" assembly="ProtoGeometry.dll" function="Autodesk.DesignScript.Geometry.Curve.Length">
      <PortInfo index="0" default="False" />
    </Dynamo.Graph.Nodes.ZeroTouch.DSFunction>
    <Dynamo.Graph.Nodes.CustomNodes.Function guid="4d424b24-beee-4e85-b258-19f0ec258dc0" type="Dynamo.Graph.Nodes.CustomNodes.Function" nickname="Rhythm.RenumberGridsByCurve" x="1854.65201408345" y="129.840513839629" isVisible="true" isUpstreamVisible="true" lacing="Shortest" isSelectedInput="False" IsFrozen="false" isPinned="false">
      <PortInfo index="0" default="False" />
      <PortInfo index="1" default="False" />
      <PortInfo index="2" default="True" />
      <ID value="b789aed2-e889-4e5d-b135-b7ae59714260" />
      <Name value="Rhythm.RenumberGridsByCurve" />
      <Description value="This node will renumber grids in order of curve drawn through them. Select either letters or numbers. (Alphanumeric coming soon)" />
      <Inputs>
        <Input value="modelCurve" />
        <Input value="startCharacter" />
        <Input value="RunMe" />
      </Inputs>
      <Outputs>
        <Output value="Element" />
      </Outputs>
    </Dynamo.Graph.Nodes.CustomNodes.Function>
    <Dynamo.Graph.Nodes.ZeroTouch.DSFunction guid="5cee3acd-67c6-4103-8040-b6ede87be572" type="Dynamo.Graph.Nodes.ZeroTouch.DSFunction" nickname="Grid.Curve" x="1893.19217967367" y="663.186676362369" isVisible="true" isUpstreamVisible="true" lacing="Shortest" isSelectedInput="False" IsFrozen="false" isPinned="true" assembly="RevitNodes.dll" function="Revit.Elements.Grid.Curve">
      <PortInfo index="0" default="False" />
    </Dynamo.Graph.Nodes.ZeroTouch.DSFunction>
    <Dynamo.Graph.Nodes.ZeroTouch.DSFunction guid="501b7232-bf52-4902-b00c-8855c4cae98c" type="Dynamo.Graph.Nodes.ZeroTouch.DSFunction" nickname="Object.Type" x="2231.35105194916" y="663.186676362369" isVisible="true" isUpstreamVisible="true" lacing="Shortest" isSelectedInput="False" IsFrozen="false" isPinned="true" assembly="DSCoreNodes.dll" function="DSCore.Object.Type@var">
      <PortInfo index="0" default="False" />
    </Dynamo.Graph.Nodes.ZeroTouch.DSFunction>
    <Dynamo.Graph.Nodes.CodeBlockNodeModel guid="88f25ecc-8ae9-41b6-abef-6ff9b74d306d" type="Dynamo.Graph.Nodes.CodeBlockNodeModel" nickname="Code Block" x="2133.56679347659" y="255.919668819557" isVisible="true" isUpstreamVisible="true" lacing="Disabled" isSelectedInput="False" IsFrozen="false" isPinned="false" CodeText="a[2];" ShouldFocus="false">
      <PortInfo index="0" default="False" />
    </Dynamo.Graph.Nodes.CodeBlockNodeModel>
    <Dynamo.Graph.Nodes.CodeBlockNodeModel guid="0d3eb971-2768-415d-abce-3b3581315810" type="Dynamo.Graph.Nodes.CodeBlockNodeModel" nickname="Code Block" x="3006.49985084405" y="653.751412780402" isVisible="false" isUpstreamVisible="true" lacing="Disabled" isSelectedInput="False" IsFrozen="false" isPinned="false" CodeText="curve[0];" ShouldFocus="false">
      <PortInfo index="0" default="False" />
    </Dynamo.Graph.Nodes.CodeBlockNodeModel>
    <Dynamo.Graph.Nodes.ZeroTouch.DSFunction guid="371b8809-160d-4aa3-8257-e66c6e180506" type="Dynamo.Graph.Nodes.ZeroTouch.DSFunction" nickname="Grid.Curve" x="2687.08955123538" y="608.774778645576" isVisible="false" isUpstreamVisible="true" lacing="Shortest" isSelectedInput="False" IsFrozen="false" isPinned="true" assembly="RevitNodes.dll" function="Revit.Elements.Grid.Curve">
      <PortInfo index="0" default="False" />
    </Dynamo.Graph.Nodes.ZeroTouch.DSFunction>
    <Dynamo.Graph.Nodes.ZeroTouch.DSFunction guid="d65da04a-f780-4dc7-a2b4-3ab756a2f387" type="Dynamo.Graph.Nodes.ZeroTouch.DSFunction" nickname="Curve.StartPoint" x="3206.9523966269" y="667.824569334018" isVisible="false" isUpstreamVisible="true" lacing="Shortest" isSelectedInput="False" IsFrozen="false" isPinned="false" assembly="ProtoGeometry.dll" function="Autodesk.DesignScript.Geometry.Curve.StartPoint">
      <PortInfo index="0" default="False" />
    </Dynamo.Graph.Nodes.ZeroTouch.DSFunction>
    <Dynamo.Graph.Nodes.ZeroTouch.DSFunction guid="cbe1d41c-27ae-4b66-9ac0-9375435f346d" type="Dynamo.Graph.Nodes.ZeroTouch.DSFunction" nickname="Plane.ByOriginNormal" x="3379.51511466049" y="567.217318853296" isVisible="false" isUpstreamVisible="true" lacing="Shortest" isSelectedInput="False" IsFrozen="false" isPinned="false" assembly="ProtoGeometry.dll" function="Autodesk.DesignScript.Geometry.Plane.ByOriginNormal@Autodesk.DesignScript.Geometry.Point,Autodesk.DesignScript.Geometry.Vector">
      <PortInfo index="0" default="True" />
      <PortInfo index="1" default="True" />
    </Dynamo.Graph.Nodes.ZeroTouch.DSFunction>
    <Dynamo.Graph.Nodes.ZeroTouch.DSFunction guid="d3db30a7-0a0f-42ca-b08b-f4300a041c27" type="Dynamo.Graph.Nodes.ZeroTouch.DSFunction" nickname="Element.Geometry" x="3276.57564852407" y="467.011404823961" isVisible="false" isUpstreamVisible="true" lacing="Shortest" isSelectedInput="False" IsFrozen="false" isPinned="false" assembly="RevitNodes.dll" function="Revit.Elements.Element.Geometry">
      <PortInfo index="0" default="False" />
    </Dynamo.Graph.Nodes.ZeroTouch.DSFunction>
    <Dynamo.Graph.Nodes.ZeroTouch.DSFunction guid="69346c24-23f7-4e78-9460-fdf9a8a7debe" type="Dynamo.Graph.Nodes.ZeroTouch.DSFunction" nickname="Curve.PullOntoPlane" x="3541.10232769916" y="725.091985111878" isVisible="false" isUpstreamVisible="true" lacing="Longest" isSelectedInput="False" IsFrozen="false" isPinned="true" assembly="ProtoGeometry.dll" function="Autodesk.DesignScript.Geometry.Curve.PullOntoPlane@Autodesk.DesignScript.Geometry.Plane">
      <PortInfo index="0" default="False" useLevels="True" level="1" shouldKeepListStructure="False" />
      <PortInfo index="1" default="False" />
    </Dynamo.Graph.Nodes.ZeroTouch.DSFunction>
    <Dynamo.Graph.Nodes.ZeroTouch.DSFunction guid="bf5c9072-f784-4426-9f6a-3abc2bb34eb5" type="Dynamo.Graph.Nodes.ZeroTouch.DSFunction" nickname="Geometry.IntersectAll" x="3859.43184608653" y="422.698214046893" isVisible="true" isUpstreamVisible="true" lacing="CrossProduct" isSelectedInput="False" IsFrozen="false" isPinned="true" assembly="ProtoGeometry.dll" function="Autodesk.DesignScript.Geometry.Geometry.IntersectAll@Autodesk.DesignScript.Geometry.Geometry[]">
      <PortInfo index="0" default="False" useLevels="True" level="1" shouldKeepListStructure="False" />
      <PortInfo index="1" default="False" />
    </Dynamo.Graph.Nodes.ZeroTouch.DSFunction>
    <Dynamo.Nodes.DSModelElementSelection guid="b0204ec4-68f0-4af6-adea-b328028a6aea" type="Dynamo.Nodes.DSModelElementSelection" nickname="Select Model Element" x="3000.28372338101" y="286.000006416786" isVisible="true" isUpstreamVisible="true" lacing="Disabled" isSelectedInput="True" IsFrozen="false" isPinned="false" />
    <Dynamo.Graph.Nodes.CustomNodes.Function guid="b7fb75eb-d52a-4286-b70d-6bd445754e09" type="Dynamo.Graph.Nodes.CustomNodes.Function" nickname="Pick Model Elements" x="3020.07016816977" y="447.688852571784" isVisible="true" isUpstreamVisible="true" lacing="Shortest" isSelectedInput="False" IsFrozen="false" isPinned="true">
      <PortInfo index="0" default="True" />
      <ID value="affdb898-d7fc-43f3-9a38-f018ef2c2273" />
      <Name value="Pick Model Elements" />
      <Description value="This node offers a pick method for selecting elements in Revit." />
      <Inputs>
        <Input value="refresh" />
      </Inputs>
      <Outputs>
        <Output value="element" />
      </Outputs>
    </Dynamo.Graph.Nodes.CustomNodes.Function>
    <Dynamo.Graph.Nodes.ZeroTouch.DSFunction guid="c2ae201a-1a21-448f-92ad-5441d9f22586" type="Dynamo.Graph.Nodes.ZeroTouch.DSFunction" nickname="Flatten" x="4208.40863309506" y="423.120307326781" isVisible="true" isUpstreamVisible="true" lacing="Shortest" isSelectedInput="False" IsFrozen="false" isPinned="true" assembly="BuiltIn" function="Flatten@var[]..[]">
      <PortInfo index="0" default="False" useLevels="True" level="3" shouldKeepListStructure="False" />
    </Dynamo.Graph.Nodes.ZeroTouch.DSFunction>
    <Dynamo.Graph.Nodes.ZeroTouch.DSFunction guid="cc00b97f-35ce-4b5a-8962-2966d546cbfa" type="Dynamo.Graph.Nodes.ZeroTouch.DSFunction" nickname="Line.ByStartPointEndPoint" x="4816.7996634653" y="510.879955223447" isVisible="true" isUpstreamVisible="true" lacing="Shortest" isSelectedInput="False" IsFrozen="false" isPinned="true" assembly="ProtoGeometry.dll" function="Autodesk.DesignScript.Geometry.Line.ByStartPointEndPoint@Autodesk.DesignScript.Geometry.Point,Autodesk.DesignScript.Geometry.Point">
      <PortInfo index="0" default="False" />
      <PortInfo index="1" default="False" />
    </Dynamo.Graph.Nodes.ZeroTouch.DSFunction>
    <Dynamo.Graph.Nodes.ZeroTouch.DSFunction guid="c09d768d-9fe7-4190-8ed4-48f6212a194c" type="Dynamo.Graph.Nodes.ZeroTouch.DSFunction" nickname="List.Deconstruct" x="4480.85217357817" y="645.26333998506" isVisible="true" isUpstreamVisible="true" lacing="Shortest" isSelectedInput="False" IsFrozen="false" isPinned="true" assembly="DSCoreNodes.dll" function="DSCore.List.Deconstruct@var[]..[]">
      <PortInfo index="0" default="False" useLevels="True" level="2" shouldKeepListStructure="False" />
    </Dynamo.Graph.Nodes.ZeroTouch.DSFunction>
    <Dynamo.Graph.Nodes.ZeroTouch.DSFunction guid="87efb321-ee77-428d-96c9-bd45db62e738" type="Dynamo.Graph.Nodes.ZeroTouch.DSFunction" nickname="List.Transpose" x="4441.59449221079" y="355.409758900475" isVisible="true" isUpstreamVisible="true" lacing="Shortest" isSelectedInput="False" IsFrozen="false" isPinned="false" assembly="DSCoreNodes.dll" function="DSCore.List.Transpose@var[]..[]">
      <PortInfo index="0" default="False" />
    </Dynamo.Graph.Nodes.ZeroTouch.DSFunction>
    <PythonNodeModels.PythonNode guid="77f38df1-2245-4b69-8e56-c11e1f10e5ec" type="PythonNodeModels.PythonNode" nickname="Python Script" x="7698.81905775177" y="595.653854003897" isVisible="true" isUpstreamVisible="true" lacing="Disabled" isSelectedInput="False" IsFrozen="false" isPinned="true" inputcount="3">
      <PortInfo index="0" default="False" />
      <PortInfo index="1" default="False" />
      <PortInfo index="2" default="False" />
      <Script>import clr
clr.AddReference('ProtoGeometry')
from Autodesk.DesignScript.Geometry import *

# Import DocumentManager and TransactionManager
clr.AddReference("RevitServices")
import RevitServices
from RevitServices.Persistence import DocumentManager
from RevitServices.Transactions import TransactionManager

# Import RevitAPI
clr.AddReference("RevitAPI")
import Autodesk
from Autodesk.Revit.DB import *

clr.AddReference("RevitNodes")
import Revit
clr.ImportExtensions(Revit.GeometryConversion)


doc = DocumentManager.Instance.CurrentDBDocument
uiapp = DocumentManager.Instance.CurrentUIApplication
app = uiapp.Application


grids = UnwrapElement(IN[0])
view = UnwrapElement(IN[1])
crvs = UnwrapElement(IN[2])

curves = []
curvesViews = []

TransactionManager.Instance.EnsureInTransaction(doc)

for i in range(0,len(grids)):	
	grids[i].SetCurveInView(DatumExtentType.ViewSpecific,view,crvs[i])


TransactionManager.Instance.TransactionTaskDone()
	

	
#Assign your outputs to the OUT variable
OUT = grids
</Script>
    </PythonNodeModels.PythonNode>
    <Dynamo.Graph.Nodes.ZeroTouch.DSFunction guid="ec319121-2faf-49f7-929b-1e0cdfaa4156" type="Dynamo.Graph.Nodes.ZeroTouch.DSFunction" nickname="Flatten" x="5112.08027331443" y="531.508152973098" isVisible="true" isUpstreamVisible="true" lacing="Shortest" isSelectedInput="False" IsFrozen="false" isPinned="true" assembly="BuiltIn" function="Flatten@var[]..[]">
      <PortInfo index="0" default="False" />
    </Dynamo.Graph.Nodes.ZeroTouch.DSFunction>
    <Dynamo.Graph.Nodes.ZeroTouch.DSFunction guid="8b929e94-0405-40ba-883f-06fecabf25af" type="Dynamo.Graph.Nodes.ZeroTouch.DSFunction" nickname="Object.Type" x="5389.88523560256" y="649.634922336452" isVisible="true" isUpstreamVisible="true" lacing="Shortest" isSelectedInput="False" IsFrozen="false" isPinned="true" assembly="DSCoreNodes.dll" function="DSCore.Object.Type@var">
      <PortInfo index="0" default="False" />
    </Dynamo.Graph.Nodes.ZeroTouch.DSFunction>
    <Dynamo.Graph.Nodes.CustomNodes.Function guid="d9b106c6-f26d-40ab-8377-b0cec0fae43a" type="Dynamo.Graph.Nodes.CustomNodes.Function" nickname="Pick Model Elements" x="5002.03137892679" y="163.868286672477" isVisible="true" isUpstreamVisible="true" lacing="Shortest" isSelectedInput="False" IsFrozen="false" isPinned="true">
      <PortInfo index="0" default="True" />
      <ID value="affdb898-d7fc-43f3-9a38-f018ef2c2273" />
      <Name value="Pick Model Elements" />
      <Description value="This node offers a pick method for selecting elements in Revit." />
      <Inputs>
        <Input value="refresh" />
      </Inputs>
      <Outputs>
        <Output value="element" />
      </Outputs>
    </Dynamo.Graph.Nodes.CustomNodes.Function>
    <PythonNodeModels.PythonNode guid="a6bc5773-0965-4260-9743-014de25fafc4" type="PythonNodeModels.PythonNode" nickname="Python Script" x="5551.98029707537" y="824.927334645527" isVisible="true" isUpstreamVisible="true" lacing="Disabled" isSelectedInput="False" IsFrozen="false" isPinned="true" inputcount="1">
      <PortInfo index="0" default="False" />
      <Script>import clr
clr.AddReference('ProtoGeometry')
from Autodesk.DesignScript.Geometry import *

# Import DocumentManager and TransactionManager
clr.AddReference("RevitServices")
import RevitServices
from RevitServices.Persistence import DocumentManager
from RevitServices.Transactions import TransactionManager

# Import RevitAPI
clr.AddReference("RevitAPI")
import Autodesk
from Autodesk.Revit.DB import *

clr.AddReference("RevitNodes")
import Revit
clr.ImportExtensions(Revit.GeometryConversion)


doc = DocumentManager.Instance.CurrentDBDocument
uiapp = DocumentManager.Instance.CurrentUIApplication
app = uiapp.Application


crvs = UnwrapElement(IN[0])
revitCurves = []

for c in crvs:
	revitCurves.append(c.ToRevitType())


	
#Assign your outputs to the OUT variable
OUT = revitCurves
</Script>
    </PythonNodeModels.PythonNode>
    <Dynamo.Graph.Nodes.ZeroTouch.DSFunction guid="62b1c786-2a89-43da-ad76-3982a67cc194" type="Dynamo.Graph.Nodes.ZeroTouch.DSFunction" nickname="Curve.Offset" x="5265.20670977589" y="368.582923486946" isVisible="true" isUpstreamVisible="true" lacing="Shortest" isSelectedInput="False" IsFrozen="false" isPinned="true" assembly="ProtoGeometry.dll" function="Autodesk.DesignScript.Geometry.Curve.Offset@double">
      <PortInfo index="0" default="False" />
      <PortInfo index="1" default="True" />
    </Dynamo.Graph.Nodes.ZeroTouch.DSFunction>
    <Dynamo.Graph.Nodes.CodeBlockNodeModel guid="325722ba-6723-458a-84b0-a6e85f202bd7" type="Dynamo.Graph.Nodes.CodeBlockNodeModel" nickname="Code Block" x="5082" y="400" isVisible="true" isUpstreamVisible="true" lacing="Disabled" isSelectedInput="False" IsFrozen="false" isPinned="false" CodeText="0;" ShouldFocus="false" />
    <PythonNodeModels.PythonNode guid="a2e9629e-9c2b-4ec9-b2b6-f9b0e2973ac1" type="PythonNodeModels.PythonNode" nickname="Python Script" x="5817.18477187131" y="660.63115592253" isVisible="true" isUpstreamVisible="true" lacing="Disabled" isSelectedInput="False" IsFrozen="false" isPinned="true" inputcount="1">
      <PortInfo index="0" default="False" />
      <Script>import clr
clr.AddReference('ProtoGeometry')
from Autodesk.DesignScript.Geometry import *

# Import DocumentManager and TransactionManager
clr.AddReference("RevitServices")
import RevitServices
from RevitServices.Persistence import DocumentManager
from RevitServices.Transactions import TransactionManager

# Import RevitAPI
clr.AddReference("RevitAPI")
import Autodesk
from Autodesk.Revit.DB import *

clr.AddReference("RevitNodes")
import Revit
clr.ImportExtensions(Revit.GeometryConversion)


doc = DocumentManager.Instance.CurrentDBDocument
uiapp = DocumentManager.Instance.CurrentUIApplication
app = uiapp.Application


crvs = UnwrapElement(IN[0])
revitCurves = []

  
for c in crvs:
	start = c.GetEndPoint(0)
	end = c.GetEndPoint(1)
	newStart = start + 10 * XYZ.BasisY
	newEnd = end - 10 * XYZ.BasisY
	newLine = Line.CreateBound(newStart,newEnd)
	revitCurves.append(newLine)
    
#Assign your outputs to the OUT variable
OUT = revitCurves
</Script>
    </PythonNodeModels.PythonNode>
    <Dynamo.Graph.Nodes.ZeroTouch.DSFunction guid="2da21e6c-e890-4d39-a3f5-1249088e6134" type="Dynamo.Graph.Nodes.ZeroTouch.DSFunction" nickname="Curve.StartPoint" x="4167.64436668011" y="18.06266801195" isVisible="true" isUpstreamVisible="true" lacing="Shortest" isSelectedInput="False" IsFrozen="false" isPinned="true" assembly="ProtoGeometry.dll" function="Autodesk.DesignScript.Geometry.Curve.StartPoint">
      <PortInfo index="0" default="False" />
    </Dynamo.Graph.Nodes.ZeroTouch.DSFunction>
    <Dynamo.Graph.Nodes.CodeBlockNodeModel guid="0c183b49-256f-4605-8186-a0e25bacd88b" type="Dynamo.Graph.Nodes.CodeBlockNodeModel" nickname="Code Block" x="4272" y="225" isVisible="true" isUpstreamVisible="true" lacing="Disabled" isSelectedInput="False" IsFrozen="false" isPinned="false" CodeText="a[0];" ShouldFocus="false">
      <PortInfo index="0" default="False" />
    </Dynamo.Graph.Nodes.CodeBlockNodeModel>
    <Dynamo.Graph.Nodes.CustomNodes.Function guid="0d67b4e2-28db-41f6-9b54-5958c1f9612c" type="Dynamo.Graph.Nodes.CustomNodes.Function" nickname="Distance Between Point" x="5042.24429997863" y="1117.64155192877" isVisible="true" isUpstreamVisible="true" lacing="Shortest" isSelectedInput="False" IsFrozen="false" isPinned="true">
      <PortInfo index="0" default="False" />
      <PortInfo index="1" default="False" />
      <ID value="b1a64f35-1049-4cfa-912f-73db99de667f" />
      <Name value="Distance Between Point" />
      <Description value="Calculate the distance between 2 set of Point." />
      <Inputs>
        <Input value="Point" />
        <Input value="Point" />
      </Inputs>
      <Outputs>
        <Output value="Distance" />
      </Outputs>
    </Dynamo.Graph.Nodes.CustomNodes.Function>
    <Dynamo.Graph.Nodes.CustomNodes.Function guid="811a8bba-0a6d-4593-8314-5a13b5960045" type="Dynamo.Graph.Nodes.CustomNodes.Function" nickname="Grid.SetVerticalExtents" x="4794.6997039693" y="49.6993631265927" isVisible="true" isUpstreamVisible="true" lacing="Shortest" isSelectedInput="False" IsFrozen="false" isPinned="false">
      <PortInfo index="0" default="False" />
      <PortInfo index="1" default="False" />
      <ID value="f3dfd2d9-68d3-4bab-b7d6-ce9f0c8a02ca" />
      <Name value="Grid.SetVerticalExtents" />
      <Description value="Set the vertical extents of all project grids" />
      <Inputs>
        <Input value="Bottom extent" />
        <Input value="Top extent" />
      </Inputs>
      <Outputs>
        <Output value="OUT" />
      </Outputs>
    </Dynamo.Graph.Nodes.CustomNodes.Function>
    <PythonNodeModels.PythonNode guid="4978c60b-b7a1-409b-a6fb-965397e59891" type="PythonNodeModels.PythonNode" nickname="Python Script" x="4818.09299905867" y="-65.317910962208" isVisible="true" isUpstreamVisible="true" lacing="Disabled" isSelectedInput="False" IsFrozen="false" isPinned="true" inputcount="2">
      <PortInfo index="0" default="False" />
      <PortInfo index="1" default="False" />
      <Script>#Copyright (c) mostafa el ayoubi
#Node-mode www.data-shapes.net 2016 elayoub.mostafa@gmail.com

import clr
clr.AddReference('RevitAPI')
from Autodesk.Revit.DB import*
clr.AddReference('RevitServices')
from RevitServices.Persistence import DocumentManager
from RevitServices.Transactions import TransactionManager

doc = DocumentManager.Instance.CurrentDBDocument
UIunit = Document.GetUnits(doc).GetFormatOptions(UnitType.UT_Length).DisplayUnits

def convunit(x):
	return UnitUtils.ConvertToInternalUnits(x,UIunit)

grids = [UnwrapElement(i) for i in FilteredElementCollector(doc).OfClass(Grid)]

TransactionManager.Instance.EnsureInTransaction(doc)
for g in grids:
	g.SetVerticalExtents(convunit(IN[0]),convunit(IN[1]))
TransactionManager.Instance.TransactionTaskDone()

OUT = grids</Script>
    </PythonNodeModels.PythonNode>
    <Dynamo.Graph.Nodes.ZeroTouch.DSFunction guid="1d46e0c3-9a43-4191-80d6-f4df68dabbde" type="Dynamo.Graph.Nodes.ZeroTouch.DSFunction" nickname="Flatten" x="5604.81370795748" y="300.156915010395" isVisible="true" isUpstreamVisible="true" lacing="Shortest" isSelectedInput="False" IsFrozen="false" isPinned="true" assembly="BuiltIn" function="Flatten@var[]..[]">
      <PortInfo index="0" default="False" />
    </Dynamo.Graph.Nodes.ZeroTouch.DSFunction>
    <PythonNodeModels.PythonNode guid="fb4cc4da-beab-46a8-8c71-15513d88b61f" type="PythonNodeModels.PythonNode" nickname="Python Script" x="5500.65139680808" y="996.280035922183" isVisible="true" isUpstreamVisible="true" lacing="Disabled" isSelectedInput="False" IsFrozen="false" isPinned="true" inputcount="2">
      <PortInfo index="0" default="False" />
      <PortInfo index="1" default="False" />
      <Script>import clr
clr.AddReference('ProtoGeometry')
from Autodesk.DesignScript.Geometry import *

# Import DocumentManager and TransactionManager
clr.AddReference("RevitServices")
import RevitServices
from RevitServices.Persistence import DocumentManager
from RevitServices.Transactions import TransactionManager

# Import RevitAPI
clr.AddReference("RevitAPI")
import Autodesk
from Autodesk.Revit.DB import *

clr.AddReference("RevitNodes")
import Revit
clr.ImportExtensions(Revit.GeometryConversion)


doc = DocumentManager.Instance.CurrentDBDocument
uiapp = DocumentManager.Instance.CurrentUIApplication
app = uiapp.Application


grids = UnwrapElement(IN[0])
view = UnwrapElement(IN[1])

curves = []
gridCurves = []

TransactionManager.Instance.EnsureInTransaction(doc)

for g in grids:	
	g.SetDatumExtentType(DatumEnds.End0,view,DatumExtentType.ViewSpecific)
	g.SetDatumExtentType(DatumEnds.End1,view,DatumExtentType.ViewSpecific)
	curves.append(g.GetCurvesInView(DatumExtentType.Model, view))
	gridCurves.append(g.GetCurvesInView(DatumExtentType.ViewSpecific, view))

TransactionManager.Instance.TransactionTaskDone()
	
dynaCrvs = []
new = []

for i in range(0,len(gridCurves)):
	for c in gridCurves[i]:
		start = c.GetEndPoint(0)
		end = c.GetEndPoint(1)
		oldLine = Line.CreateBound(start,end).ToProtoType()
		newStart = start -5 * XYZ.BasisY
		newEnd = end +5 * XYZ.BasisY
		newLine = Line.CreateBound(newStart,newEnd)
		dynaCrvs.append(oldLine)
		new.append(newLine.ToProtoType())
		#grids[i].SetCurveInView(DatumExtentType.ViewSpecific, view, newLine)

	
#Assign your outputs to the OUT variable
OUT = dynaCrvs,new
</Script>
    </PythonNodeModels.PythonNode>
    <PythonNodeModels.PythonNode guid="e8e1c82e-ec37-4677-a166-72d00c59eac2" type="PythonNodeModels.PythonNode" nickname="Python Script" x="5784.47354865807" y="1140.5595228011" isVisible="true" isUpstreamVisible="true" lacing="Disabled" isSelectedInput="False" IsFrozen="false" isPinned="true" inputcount="3">
      <PortInfo index="0" default="False" />
      <PortInfo index="1" default="False" />
      <PortInfo index="2" default="False" />
      <Script>#Copyright (c) mostafa el ayoubi
#Node-mode www.data-shapes.net 2016 elayoub.mostafa@gmail.com

import clr
clr.AddReference('RevitAPI')
from Autodesk.Revit.DB import*
clr.AddReference('RevitServices')
from RevitServices.Persistence import DocumentManager
from RevitServices.Transactions import TransactionManager

doc = DocumentManager.Instance.CurrentDBDocument
UIunit = Document.GetUnits(doc).GetFormatOptions(UnitType.UT_Length).DisplayUnits

def convunit(x):
	return UnitUtils.ConvertToInternalUnits(x,UIunit)
def tolist(input):
	if isinstance(input,list):
		return UnwrapElement(input)
	else:
		return [UnwrapElement(input)]

grids = tolist(IN[0])

TransactionManager.Instance.EnsureInTransaction(doc)
for g,bottom,top in zip(grids,IN[1],IN[2]):
	g.SetVerticalExtents(convunit(bottom),convunit(top))
TransactionManager.Instance.TransactionTaskDone()

OUT = grids</Script>
    </PythonNodeModels.PythonNode>
    <Dynamo.Graph.Nodes.CodeBlockNodeModel guid="278a3778-2a76-442d-901a-ed569e6b4172" type="Dynamo.Graph.Nodes.CodeBlockNodeModel" nickname="Code Block" x="5514" y="1260" isVisible="true" isUpstreamVisible="true" lacing="Disabled" isSelectedInput="False" IsFrozen="false" isPinned="false" CodeText="{0,0};" ShouldFocus="false" />
    <Dynamo.Graph.Nodes.ZeroTouch.DSFunction guid="5f7d8100-1ac9-4208-9c8a-b2e8c40d272c" type="Dynamo.Graph.Nodes.ZeroTouch.DSFunction" nickname="Element.Curves" x="6043.79518532029" y="980.319054107814" isVisible="true" isUpstreamVisible="true" lacing="Shortest" isSelectedInput="False" IsFrozen="false" isPinned="true" assembly="RevitNodes.dll" function="Revit.Elements.Element.Curves">
      <PortInfo index="0" default="False" />
    </Dynamo.Graph.Nodes.ZeroTouch.DSFunction>
    <Dynamo.Graph.Nodes.ZeroTouch.DSFunction guid="e4a1ac80-657a-4214-95e5-83889039afc2" type="Dynamo.Graph.Nodes.ZeroTouch.DSFunction" nickname="Geometry.Translate" x="6452.56572642661" y="748.447444681075" isVisible="true" isUpstreamVisible="true" lacing="Shortest" isSelectedInput="False" IsFrozen="false" isPinned="true" assembly="ProtoGeometry.dll" function="Autodesk.DesignScript.Geometry.Geometry.Translate@Autodesk.DesignScript.Geometry.Vector,double">
      <PortInfo index="0" default="False" />
      <PortInfo index="1" default="False" />
      <PortInfo index="2" default="False" />
    </Dynamo.Graph.Nodes.ZeroTouch.DSFunction>
    <Dynamo.Graph.Nodes.CodeBlockNodeModel guid="c5c33421-4556-4545-9433-55c4aa5efa87" type="Dynamo.Graph.Nodes.CodeBlockNodeModel" nickname="Code Block" x="6220" y="800" isVisible="true" isUpstreamVisible="true" lacing="Disabled" isSelectedInput="False" IsFrozen="false" isPinned="false" CodeText="Vector.ZAxis();" ShouldFocus="false" />
    <Dynamo.Graph.Nodes.CodeBlockNodeModel guid="194b1c24-0dfb-48c6-86a0-d4f7756f7677" type="Dynamo.Graph.Nodes.CodeBlockNodeModel" nickname="Code Block" x="6348" y="907" isVisible="true" isUpstreamVisible="true" lacing="Disabled" isSelectedInput="False" IsFrozen="false" isPinned="false" CodeText="300;" ShouldFocus="false" />
    <Dynamo.Graph.Nodes.ZeroTouch.DSFunction guid="cd1c4789-c221-43c3-bca0-52f1717b189f" type="Dynamo.Graph.Nodes.ZeroTouch.DSFunction" nickname="Flatten" x="6773.10021596514" y="753.441146579334" isVisible="true" isUpstreamVisible="true" lacing="Shortest" isSelectedInput="False" IsFrozen="false" isPinned="true" assembly="BuiltIn" function="Flatten@var[]..[]">
      <PortInfo index="0" default="False" />
    </Dynamo.Graph.Nodes.ZeroTouch.DSFunction>
    <Dynamo.Graph.Nodes.ZeroTouch.DSFunction guid="c4580194-421c-482f-bba7-987fcee67f8e" type="Dynamo.Graph.Nodes.ZeroTouch.DSFunction" nickname="Curves.EndPoints" x="7025.91797308385" y="767.796759952745" isVisible="true" isUpstreamVisible="true" lacing="Shortest" isSelectedInput="False" IsFrozen="false" isPinned="true" assembly="..\AppData\Roaming\Dynamo\Dynamo Revit\1.3\packages\LunchBox for Dynamo\bin\LunchBox.dll" function="Geometry.Curves.EndPoints@Autodesk.DesignScript.Geometry.Curve">
      <PortInfo index="0" default="False" />
    </Dynamo.Graph.Nodes.ZeroTouch.DSFunction>
    <PythonNodeModels.PythonNode guid="d97465d5-f602-4041-b7b7-57338bb1bfb8" type="PythonNodeModels.PythonNode" nickname="Python Script" x="7368.49731988467" y="766.737381118" isVisible="true" isUpstreamVisible="true" lacing="Disabled" isSelectedInput="False" IsFrozen="false" isPinned="true" inputcount="2">
      <PortInfo index="0" default="False" />
      <PortInfo index="1" default="False" />
      <Script>import clr
clr.AddReference('ProtoGeometry')
from Autodesk.DesignScript.Geometry import *

# Import DocumentManager and TransactionManager
clr.AddReference("RevitServices")
import RevitServices
from RevitServices.Persistence import DocumentManager
from RevitServices.Transactions import TransactionManager

# Import RevitAPI
clr.AddReference("RevitAPI")
import Autodesk
from Autodesk.Revit.DB import *

clr.AddReference("RevitNodes")
import Revit
clr.ImportExtensions(Revit.GeometryConversion)


doc = DocumentManager.Instance.CurrentDBDocument
uiapp = DocumentManager.Instance.CurrentUIApplication
app = uiapp.Application


startPts = UnwrapElement(IN[0])
endPts = UnwrapElement(IN[1])
revitCurves = []

  
for i in range(0,len(startPts)):
	newLine = Line.CreateBound(startPts[i].ToXyz(),endPts[i].ToXyz())
	revitCurves.append(newLine)
    
#Assign your outputs to the OUT variable
OUT = revitCurves
</Script>
    </PythonNodeModels.PythonNode>
    <Dynamo.Graph.Nodes.CodeBlockNodeModel guid="8e153d0e-e04a-43aa-b864-d05ece4450c1" type="Dynamo.Graph.Nodes.CodeBlockNodeModel" nickname="Code Block" x="5382" y="983" isVisible="true" isUpstreamVisible="true" lacing="Disabled" isSelectedInput="False" IsFrozen="false" isPinned="false" CodeText="a;" ShouldFocus="false">
      <PortInfo index="0" default="False" />
    </Dynamo.Graph.Nodes.CodeBlockNodeModel>
  </Elements>
  <Connectors>
    <Dynamo.Graph.Connectors.ConnectorModel start="0e236119-9ec6-4f86-8278-f498b08e8a7f" start_index="0" end="5cee3acd-67c6-4103-8040-b6ede87be572" end_index="0" portType="0" />
    <Dynamo.Graph.Connectors.ConnectorModel start="0e236119-9ec6-4f86-8278-f498b08e8a7f" start_index="0" end="371b8809-160d-4aa3-8257-e66c6e180506" end_index="0" portType="0" />
    <Dynamo.Graph.Connectors.ConnectorModel start="0e236119-9ec6-4f86-8278-f498b08e8a7f" start_index="0" end="77f38df1-2245-4b69-8e56-c11e1f10e5ec" end_index="0" portType="0" />
    <Dynamo.Graph.Connectors.ConnectorModel start="0e236119-9ec6-4f86-8278-f498b08e8a7f" start_index="0" end="8e153d0e-e04a-43aa-b864-d05ece4450c1" end_index="0" portType="0" />
    <Dynamo.Graph.Connectors.ConnectorModel start="de2a8540-3d1b-4b54-8bb5-83b6ae52f950" start_index="0" end="88f25ecc-8ae9-41b6-abef-6ff9b74d306d" end_index="0" portType="0" />
    <Dynamo.Graph.Connectors.ConnectorModel start="a13ec59c-4b21-4305-a02d-718c1b5531d6" start_index="0" end="de2a8540-3d1b-4b54-8bb5-83b6ae52f950" end_index="1" portType="0" />
    <Dynamo.Graph.Connectors.ConnectorModel start="a13ec59c-4b21-4305-a02d-718c1b5531d6" start_index="0" end="77f38df1-2245-4b69-8e56-c11e1f10e5ec" end_index="1" portType="0" />
    <Dynamo.Graph.Connectors.ConnectorModel start="a13ec59c-4b21-4305-a02d-718c1b5531d6" start_index="0" end="fb4cc4da-beab-46a8-8c71-15513d88b61f" end_index="1" portType="0" />
    <Dynamo.Graph.Connectors.ConnectorModel start="5cee3acd-67c6-4103-8040-b6ede87be572" start_index="0" end="501b7232-bf52-4902-b00c-8855c4cae98c" end_index="0" portType="0" />
    <Dynamo.Graph.Connectors.ConnectorModel start="88f25ecc-8ae9-41b6-abef-6ff9b74d306d" start_index="0" end="5c6b4ad9-4bc5-41f3-9549-c0e75d7c373d" end_index="0" portType="0" />
    <Dynamo.Graph.Connectors.ConnectorModel start="0d3eb971-2768-415d-abce-3b3581315810" start_index="0" end="d65da04a-f780-4dc7-a2b4-3ab756a2f387" end_index="0" portType="0" />
    <Dynamo.Graph.Connectors.ConnectorModel start="371b8809-160d-4aa3-8257-e66c6e180506" start_index="0" end="0d3eb971-2768-415d-abce-3b3581315810" end_index="0" portType="0" />
    <Dynamo.Graph.Connectors.ConnectorModel start="371b8809-160d-4aa3-8257-e66c6e180506" start_index="0" end="bf5c9072-f784-4426-9f6a-3abc2bb34eb5" end_index="1" portType="0" />
    <Dynamo.Graph.Connectors.ConnectorModel start="371b8809-160d-4aa3-8257-e66c6e180506" start_index="0" end="2da21e6c-e890-4d39-a3f5-1249088e6134" end_index="0" portType="0" />
    <Dynamo.Graph.Connectors.ConnectorModel start="371b8809-160d-4aa3-8257-e66c6e180506" start_index="0" end="a6bc5773-0965-4260-9743-014de25fafc4" end_index="0" portType="0" />
    <Dynamo.Graph.Connectors.ConnectorModel start="d65da04a-f780-4dc7-a2b4-3ab756a2f387" start_index="0" end="cbe1d41c-27ae-4b66-9ac0-9375435f346d" end_index="0" portType="0" />
    <Dynamo.Graph.Connectors.ConnectorModel start="cbe1d41c-27ae-4b66-9ac0-9375435f346d" start_index="0" end="69346c24-23f7-4e78-9460-fdf9a8a7debe" end_index="1" portType="0" />
    <Dynamo.Graph.Connectors.ConnectorModel start="d3db30a7-0a0f-42ca-b08b-f4300a041c27" start_index="0" end="69346c24-23f7-4e78-9460-fdf9a8a7debe" end_index="0" portType="0" />
    <Dynamo.Graph.Connectors.ConnectorModel start="69346c24-23f7-4e78-9460-fdf9a8a7debe" start_index="0" end="bf5c9072-f784-4426-9f6a-3abc2bb34eb5" end_index="0" portType="0" />
    <Dynamo.Graph.Connectors.ConnectorModel start="bf5c9072-f784-4426-9f6a-3abc2bb34eb5" start_index="0" end="c2ae201a-1a21-448f-92ad-5441d9f22586" end_index="0" portType="0" />
    <Dynamo.Graph.Connectors.ConnectorModel start="b7fb75eb-d52a-4286-b70d-6bd445754e09" start_index="0" end="d3db30a7-0a0f-42ca-b08b-f4300a041c27" end_index="0" portType="0" />
    <Dynamo.Graph.Connectors.ConnectorModel start="c2ae201a-1a21-448f-92ad-5441d9f22586" start_index="0" end="87efb321-ee77-428d-96c9-bd45db62e738" end_index="0" portType="0" />
    <Dynamo.Graph.Connectors.ConnectorModel start="c2ae201a-1a21-448f-92ad-5441d9f22586" start_index="0" end="0c183b49-256f-4605-8186-a0e25bacd88b" end_index="0" portType="0" />
    <Dynamo.Graph.Connectors.ConnectorModel start="cc00b97f-35ce-4b5a-8962-2966d546cbfa" start_index="0" end="ec319121-2faf-49f7-929b-1e0cdfaa4156" end_index="0" portType="0" />
    <Dynamo.Graph.Connectors.ConnectorModel start="c09d768d-9fe7-4190-8ed4-48f6212a194c" start_index="0" end="cc00b97f-35ce-4b5a-8962-2966d546cbfa" end_index="0" portType="0" />
    <Dynamo.Graph.Connectors.ConnectorModel start="c09d768d-9fe7-4190-8ed4-48f6212a194c" start_index="1" end="cc00b97f-35ce-4b5a-8962-2966d546cbfa" end_index="1" portType="0" />
    <Dynamo.Graph.Connectors.ConnectorModel start="87efb321-ee77-428d-96c9-bd45db62e738" start_index="0" end="c09d768d-9fe7-4190-8ed4-48f6212a194c" end_index="0" portType="0" />
    <Dynamo.Graph.Connectors.ConnectorModel start="d9b106c6-f26d-40ab-8377-b0cec0fae43a" start_index="0" end="62b1c786-2a89-43da-ad76-3982a67cc194" end_index="0" portType="0" />
    <Dynamo.Graph.Connectors.ConnectorModel start="d9b106c6-f26d-40ab-8377-b0cec0fae43a" start_index="0" end="5f7d8100-1ac9-4208-9c8a-b2e8c40d272c" end_index="0" portType="0" />
    <Dynamo.Graph.Connectors.ConnectorModel start="a6bc5773-0965-4260-9743-014de25fafc4" start_index="0" end="a2e9629e-9c2b-4ec9-b2b6-f9b0e2973ac1" end_index="0" portType="0" />
    <Dynamo.Graph.Connectors.ConnectorModel start="325722ba-6723-458a-84b0-a6e85f202bd7" start_index="0" end="62b1c786-2a89-43da-ad76-3982a67cc194" end_index="1" portType="0" />
    <Dynamo.Graph.Connectors.ConnectorModel start="2da21e6c-e890-4d39-a3f5-1249088e6134" start_index="0" end="0d67b4e2-28db-41f6-9b54-5958c1f9612c" end_index="0" portType="0" />
    <Dynamo.Graph.Connectors.ConnectorModel start="0c183b49-256f-4605-8186-a0e25bacd88b" start_index="0" end="0d67b4e2-28db-41f6-9b54-5958c1f9612c" end_index="1" portType="0" />
    <Dynamo.Graph.Connectors.ConnectorModel start="0d67b4e2-28db-41f6-9b54-5958c1f9612c" start_index="0" end="e8e1c82e-ec37-4677-a166-72d00c59eac2" end_index="1" portType="0" />
    <Dynamo.Graph.Connectors.ConnectorModel start="5f7d8100-1ac9-4208-9c8a-b2e8c40d272c" start_index="0" end="e4a1ac80-657a-4214-95e5-83889039afc2" end_index="0" portType="0" />
    <Dynamo.Graph.Connectors.ConnectorModel start="e4a1ac80-657a-4214-95e5-83889039afc2" start_index="0" end="cd1c4789-c221-43c3-bca0-52f1717b189f" end_index="0" portType="0" />
    <Dynamo.Graph.Connectors.ConnectorModel start="c5c33421-4556-4545-9433-55c4aa5efa87" start_index="0" end="e4a1ac80-657a-4214-95e5-83889039afc2" end_index="1" portType="0" />
    <Dynamo.Graph.Connectors.ConnectorModel start="194b1c24-0dfb-48c6-86a0-d4f7756f7677" start_index="0" end="e4a1ac80-657a-4214-95e5-83889039afc2" end_index="2" portType="0" />
    <Dynamo.Graph.Connectors.ConnectorModel start="cd1c4789-c221-43c3-bca0-52f1717b189f" start_index="0" end="c4580194-421c-482f-bba7-987fcee67f8e" end_index="0" portType="0" />
    <Dynamo.Graph.Connectors.ConnectorModel start="c4580194-421c-482f-bba7-987fcee67f8e" start_index="0" end="d97465d5-f602-4041-b7b7-57338bb1bfb8" end_index="0" portType="0" />
    <Dynamo.Graph.Connectors.ConnectorModel start="c4580194-421c-482f-bba7-987fcee67f8e" start_index="1" end="d97465d5-f602-4041-b7b7-57338bb1bfb8" end_index="1" portType="0" />
    <Dynamo.Graph.Connectors.ConnectorModel start="d97465d5-f602-4041-b7b7-57338bb1bfb8" start_index="0" end="77f38df1-2245-4b69-8e56-c11e1f10e5ec" end_index="2" portType="0" />
  </Connectors>
  <Notes />
  <Annotations />
  <Presets />
  <Cameras>
    <Camera Name="Background Preview" eyeX="503402.53125" eyeY="213.646377563477" eyeZ="-6987186" lookX="151.058212280273" lookY="-163.646377563477" lookZ="-730.114685058594" upX="0" upY="1" upZ="0" />
  </Cameras>
</Workspace>