<Workspace Version="1.2.0.2514" X="-356.6657366017" Y="-112.688948066371" zoom="0.740344281263084" Name="Home" Description="" RunType="Manual" RunPeriod="1000" HasRunWithoutCrash="True">
  <NamespaceResolutionMap />
  <Elements>
    <Dynamo.Nodes.DSModelElementSelection guid="ae3af6c0-3df3-4455-be5e-97766a0e7809" type="Dynamo.Nodes.DSModelElementSelection" nickname="Select Model Element" x="223.5" y="454.5" isVisible="true" isUpstreamVisible="true" lacing="Disabled" isSelectedInput="True" IsFrozen="false" isPinned="false">
      <instance id="36792ccf-17e0-4349-a1b7-e629d58e0980-000009bc" />
    </Dynamo.Nodes.DSModelElementSelection>
    <Dynamo.Graph.Nodes.CustomNodes.Function guid="b5500a46-75be-4c51-98cd-56768c6376ce" type="Dynamo.Graph.Nodes.CustomNodes.Function" nickname="Object.Class" x="551.5" y="489.5" isVisible="true" isUpstreamVisible="true" lacing="Shortest" isSelectedInput="False" IsFrozen="false" isPinned="true">
      <PortInfo index="0" default="False" />
      <ID value="e4e8406d-3b77-4822-897b-3f9c08e1cd45" />
      <Name value="Object.Class" />
      <Description value="Gets the input object's class name. Can process lists." />
      <Inputs>
        <Input value="obj" />
      </Inputs>
      <Outputs>
        <Output value="class(str)" />
        <Output value="container" />
      </Outputs>
    </Dynamo.Graph.Nodes.CustomNodes.Function>
    <DSRevitNodesUI.Categories guid="09442ec5-4bb0-40e1-9a41-5534a4b79262" type="DSRevitNodesUI.Categories" nickname="Categories" x="509.5" y="328.5" isVisible="true" isUpstreamVisible="true" lacing="Disabled" isSelectedInput="True" IsFrozen="false" isPinned="false" index="138:DetailComponentTags" />
    <DSRevitNodesUI.ElementsOfCategory guid="4ee636e4-7d72-4da8-957e-9f43db396839" type="DSRevitNodesUI.ElementsOfCategory" nickname="All Elements of Category" x="749.5" y="332.5" isVisible="true" isUpstreamVisible="true" lacing="Disabled" isSelectedInput="False" IsFrozen="false" isPinned="false">
      <PortInfo index="0" default="False" />
    </DSRevitNodesUI.ElementsOfCategory>
    <CoreNodeModels.Watch guid="8fc28fc0-cc29-4fc3-a61d-0d6357054146" type="CoreNodeModels.Watch" nickname="Watch" x="939.159075376159" y="459.740590028488" isVisible="true" isUpstreamVisible="true" lacing="Disabled" isSelectedInput="False" IsFrozen="false" isPinned="false">
      <PortInfo index="0" default="False" />
    </CoreNodeModels.Watch>
    <Dynamo.Graph.Nodes.ZeroTouch.DSFunction guid="fbb5ab08-f4b6-4abf-a702-51b8768c5cf9" type="Dynamo.Graph.Nodes.ZeroTouch.DSFunction" nickname="Element.Parameters" x="1639.57323149368" y="-222.656346680404" isVisible="true" isUpstreamVisible="true" lacing="Shortest" isSelectedInput="False" IsFrozen="false" isPinned="true" assembly="RevitNodes.dll" function="Revit.Elements.Element.Parameters">
      <PortInfo index="0" default="False" />
    </Dynamo.Graph.Nodes.ZeroTouch.DSFunction>
    <Dynamo.Graph.Nodes.ZeroTouch.DSFunction guid="5d09fa86-ea23-496b-af0d-7b3df96fb571" type="Dynamo.Graph.Nodes.ZeroTouch.DSFunction" nickname="Element.GetParameterValueByName" x="1232.99072955038" y="-226.435706073912" isVisible="true" isUpstreamVisible="true" lacing="Shortest" isSelectedInput="False" IsFrozen="false" isPinned="true" assembly="RevitNodes.dll" function="Revit.Elements.Element.GetParameterValueByName@string">
      <PortInfo index="0" default="False" />
      <PortInfo index="1" default="False" />
    </Dynamo.Graph.Nodes.ZeroTouch.DSFunction>
    <Dynamo.Graph.Nodes.CodeBlockNodeModel guid="e85ec325-c530-48bb-8d72-44816b5ce95c" type="Dynamo.Graph.Nodes.CodeBlockNodeModel" nickname="Code Block" x="985.030456963036" y="-62.1248134030674" isVisible="true" isUpstreamVisible="true" lacing="Disabled" isSelectedInput="False" IsFrozen="false" isPinned="false" CodeText="&quot;Workset&quot;;" ShouldFocus="false" />
    <PythonNodeModels.PythonNode guid="1ce2ec91-4bcf-4130-8d89-35cadd8d1f43" type="PythonNodeModels.PythonNode" nickname="Python Script" x="1390.2938994414" y="287.676488164445" isVisible="true" isUpstreamVisible="true" lacing="Disabled" isSelectedInput="False" IsFrozen="false" isPinned="true" inputcount="1">
      <PortInfo index="0" default="False" />
      <Script>import clr
clr.AddReference('RevitAPI')
from Autodesk.Revit.DB import *

clr.AddReference("RevitNodes")
import Revit
clr.ImportExtensions(Revit.Elements)

items = UnwrapElement(IN[0])
elementlist = list()
for item in items:
	try:
		elementlist.append(item.Document.GetElement(item.OwnerViewId).ToDSType(True))
	except:
		elementlist.append(list())
OUT = elementlist</Script>
    </PythonNodeModels.PythonNode>
    <Dynamo.Graph.Nodes.CustomNodes.Function guid="59745d0b-c5c6-441f-ab5a-c3adfbae4fa2" type="Dynamo.Graph.Nodes.CustomNodes.Function" nickname="Element.OverrideProjectionLineweight" x="1611.91753592243" y="213.016812315716" isVisible="true" isUpstreamVisible="true" lacing="Shortest" isSelectedInput="False" IsFrozen="false" isPinned="false">
      <PortInfo index="0" default="False" />
      <PortInfo index="1" default="False" />
      <ID value="e7f03df3-0006-4ec9-9a48-cf8e6987c137" />
      <Name value="Element.OverrideProjectionLineweight" />
      <Description value="Overrides the line thickness of projection lines" />
      <Inputs>
        <Input value="element" />
        <Input value="number" />
      </Inputs>
      <Outputs>
        <Output value="Element" />
      </Outputs>
    </Dynamo.Graph.Nodes.CustomNodes.Function>
    <Dynamo.Graph.Nodes.ZeroTouch.DSFunction guid="b35ec0c4-aa0f-419f-94af-d54a4b9ed8c2" type="Dynamo.Graph.Nodes.ZeroTouch.DSFunction" nickname="Color.ByARGB" x="1270.60329916056" y="837.916862192421" isVisible="true" isUpstreamVisible="true" lacing="Shortest" isSelectedInput="False" IsFrozen="false" isPinned="true" assembly="DSCoreNodes.dll" function="DSCore.Color.ByARGB@int,int,int,int">
      <PortInfo index="0" default="True" />
      <PortInfo index="1" default="True" />
      <PortInfo index="2" default="True" />
      <PortInfo index="3" default="True" />
    </Dynamo.Graph.Nodes.ZeroTouch.DSFunction>
    <Dynamo.Graph.Nodes.CodeBlockNodeModel guid="3dd30da0-4fb1-4479-93ac-5071a5220356" type="Dynamo.Graph.Nodes.CodeBlockNodeModel" nickname="Code Block" x="1086" y="652" isVisible="true" isUpstreamVisible="true" lacing="Disabled" isSelectedInput="False" IsFrozen="false" isPinned="false" CodeText="128;" ShouldFocus="false" />
    <PythonNodeModels.PythonNode guid="0546ebc9-4515-42f3-ad4b-d0b89e58418d" type="PythonNodeModels.PythonNode" nickname="Python Script" x="1886.03156142873" y="427.413449668753" isVisible="true" isUpstreamVisible="true" lacing="Disabled" isSelectedInput="False" IsFrozen="false" isPinned="false" inputcount="1">
      <PortInfo index="0" default="False" />
      <Script>import clr
clr.AddReference('ProtoGeometry')
from Autodesk.DesignScript.Geometry import *

clr.AddReference('RevitAPI')
from Autodesk.Revit.DB import *

clr.AddReference("RevitNodes")
import Revit
clr.ImportExtensions(Revit.Elements)

clr.AddReference("RevitServices")
import RevitServices
from RevitServices.Persistence import DocumentManager
from RevitServices.Transactions import TransactionManager

doc = DocumentManager.Instance.CurrentDBDocument

trans = IN[0]

override = OverrideGraphicSettings()
#override.SetSurfaceTransparency(trans)
override.SetProjectionLineColor(trans)
#override.SetProjectionFillColor(pjfc)
#override.SetProjectionFillPatternId(pjfp)
#override.SetHalftone(ht)

OUT = override</Script>
    </PythonNodeModels.PythonNode>
    <Dynamo.Graph.Nodes.CustomNodes.Function guid="f8db9a84-75da-428e-836e-c555d6b69667" type="Dynamo.Graph.Nodes.CustomNodes.Function" nickname="Dynamo Color to Revit Color" x="1385.51709488123" y="576.122574996226" isVisible="true" isUpstreamVisible="true" lacing="Shortest" isSelectedInput="False" IsFrozen="false" isPinned="false">
      <PortInfo index="0" default="False" />
      <ID value="6c5233b7-a440-4235-9906-f9cf4a1ccebc" />
      <Name value="Dynamo Color to Revit Color" />
      <Description value="" />
      <Inputs>
        <Input value="Dynamo.Color" />
      </Inputs>
      <Outputs>
        <Output value="Revit.Color" />
      </Outputs>
    </Dynamo.Graph.Nodes.CustomNodes.Function>
    <Dynamo.Graph.Nodes.CodeBlockNodeModel guid="d7400d6f-2861-401b-8d11-28a63e5f54d9" type="Dynamo.Graph.Nodes.CodeBlockNodeModel" nickname="Code Block" x="2693.16787176802" y="588.471931400247" isVisible="true" isUpstreamVisible="true" lacing="Disabled" isSelectedInput="False" IsFrozen="false" isPinned="false" CodeText="Result;" ShouldFocus="false">
      <PortInfo index="0" default="False" />
    </Dynamo.Graph.Nodes.CodeBlockNodeModel>
    <PythonNodeModels.PythonNode guid="874f14ae-5254-43e0-b753-1cb424a6d686" type="PythonNodeModels.PythonNode" nickname="Python Script" x="2491.16787176802" y="560.471931400247" isVisible="true" isUpstreamVisible="true" lacing="Disabled" isSelectedInput="False" IsFrozen="false" isPinned="false" inputcount="3">
      <PortInfo index="0" default="False" />
      <PortInfo index="1" default="False" />
      <PortInfo index="2" default="False" />
      <Script>import clr
clr.AddReference('ProtoGeometry')
from Autodesk.DesignScript.Geometry import *

clr.AddReference('RevitAPI')
from Autodesk.Revit.DB import *

clr.AddReference("RevitNodes")
import Revit
clr.ImportExtensions(Revit.Elements)

clr.AddReference("RevitServices")
import RevitServices
from RevitServices.Persistence import DocumentManager
from RevitServices.Transactions import TransactionManager

doc = DocumentManager.Instance.CurrentDBDocument

view = UnwrapElement(IN[0])
element = IN[1]
override = IN[2]
result = []
count = 0

TransactionManager.Instance.EnsureInTransaction(doc)
while (count &lt; len(override)):
	for i in element:
		try:
			view.SetElementOverrides(i, override[count])
			result.append("Success")
			count
			count = count + 1
		except:
			view.SetElementOverrides(i, override[count-1])
			result.append("Success")
TransactionManager.Instance.TransactionTaskDone()


OUT = result</Script>
    </PythonNodeModels.PythonNode>
    <Dynamo.Graph.Nodes.CodeBlockNodeModel guid="5ab7b0f1-314d-40f8-a6f3-cb3ce02f2048" type="Dynamo.Graph.Nodes.CodeBlockNodeModel" nickname="Code Block" x="2237.91689859537" y="607.500745739147" isVisible="true" isUpstreamVisible="true" lacing="Disabled" isSelectedInput="False" IsFrozen="false" isPinned="false" CodeText="Flatten({list});" ShouldFocus="false">
      <PortInfo index="0" default="False" />
    </Dynamo.Graph.Nodes.CodeBlockNodeModel>
    <Dynamo.Graph.Nodes.CodeBlockNodeModel guid="ed795f6d-0362-4887-a1a6-6398a133b472" type="Dynamo.Graph.Nodes.CodeBlockNodeModel" nickname="Code Block" x="2236.87205616137" y="716.146528494817" isVisible="true" isUpstreamVisible="true" lacing="Disabled" isSelectedInput="False" IsFrozen="false" isPinned="false" CodeText="Flatten({list});" ShouldFocus="false">
      <PortInfo index="0" default="False" />
    </Dynamo.Graph.Nodes.CodeBlockNodeModel>
    <PythonNodeModels.PythonNode guid="50a2b19e-fbed-4a23-8a76-a4e75072f547" type="PythonNodeModels.PythonNode" nickname="Python Script" x="1854.31551827188" y="798.379559173648" isVisible="true" isUpstreamVisible="true" lacing="Disabled" isSelectedInput="False" IsFrozen="false" isPinned="true" inputcount="3">
      <PortInfo index="0" default="False" />
      <PortInfo index="1" default="False" />
      <PortInfo index="2" default="False" />
      <Script># Created by DPSDesign, dpsdesign.org
import clr
clr.AddReference('ProtoGeometry')
from Autodesk.DesignScript.Geometry import *

# Import ToDSType(bool) extension method
clr.AddReference("RevitNodes")
import Revit
clr.ImportExtensions(Revit.Elements)

# Import DocumentManager and TransactionManager
clr.AddReference("RevitServices")
import RevitServices
from RevitServices.Persistence import DocumentManager
from RevitServices.Transactions import TransactionManager

from System.Collections.Generic import *

# Import RevitAPI
clr.AddReference("RevitAPI")
import Autodesk

doc = DocumentManager.Instance.CurrentDBDocument
uiapp = DocumentManager.Instance.CurrentUIApplication
app = uiapp.Application

#The inputs to this node will be stored as a list in the IN variable.
dataEnteringNode = IN

#unwrap all elements to use with API
elements = []
for i in IN[0]:
	elements.append(UnwrapElement(i))

views = []
for i in IN[2]:
	views.append(UnwrapElement(i))

#create graphic overrides properties
gSettings = Autodesk.Revit.DB.OverrideGraphicSettings()
#deconstruct DS Color Object and convert to RevitAPI color
dsColor = IN[1]
colRed = dsColor.Red
colGreen = dsColor.Green
colBlue = dsColor.Blue
color = Autodesk.Revit.DB.Color(colRed, colGreen, colBlue)
#set Projection Line color
gSettings.SetProjectionLineColor(color)

# "Start" the transaction
TransactionManager.Instance.EnsureInTransaction(doc)

listId = []
#apply color override to elements in an input list
for i in elements:
	listId.append(i.Id)
	id = i.Id
	for j in range(0,len(views)):
		views[j].SetElementOverrides(id, gSettings)

# "End" the transaction
TransactionManager.Instance.TransactionTaskDone()

#Assign your output to the OUT variable
OUT = listId</Script>
    </PythonNodeModels.PythonNode>
  </Elements>
  <Connectors>
    <Dynamo.Graph.Connectors.ConnectorModel start="ae3af6c0-3df3-4455-be5e-97766a0e7809" start_index="0" end="b5500a46-75be-4c51-98cd-56768c6376ce" end_index="0" portType="0" />
    <Dynamo.Graph.Connectors.ConnectorModel start="09442ec5-4bb0-40e1-9a41-5534a4b79262" start_index="0" end="4ee636e4-7d72-4da8-957e-9f43db396839" end_index="0" portType="0" />
    <Dynamo.Graph.Connectors.ConnectorModel start="4ee636e4-7d72-4da8-957e-9f43db396839" start_index="0" end="8fc28fc0-cc29-4fc3-a61d-0d6357054146" end_index="0" portType="0" />
    <Dynamo.Graph.Connectors.ConnectorModel start="8fc28fc0-cc29-4fc3-a61d-0d6357054146" start_index="0" end="fbb5ab08-f4b6-4abf-a702-51b8768c5cf9" end_index="0" portType="0" />
    <Dynamo.Graph.Connectors.ConnectorModel start="8fc28fc0-cc29-4fc3-a61d-0d6357054146" start_index="0" end="5d09fa86-ea23-496b-af0d-7b3df96fb571" end_index="0" portType="0" />
    <Dynamo.Graph.Connectors.ConnectorModel start="8fc28fc0-cc29-4fc3-a61d-0d6357054146" start_index="0" end="1ce2ec91-4bcf-4130-8d89-35cadd8d1f43" end_index="0" portType="0" />
    <Dynamo.Graph.Connectors.ConnectorModel start="8fc28fc0-cc29-4fc3-a61d-0d6357054146" start_index="0" end="50a2b19e-fbed-4a23-8a76-a4e75072f547" end_index="0" portType="0" />
    <Dynamo.Graph.Connectors.ConnectorModel start="e85ec325-c530-48bb-8d72-44816b5ce95c" start_index="0" end="5d09fa86-ea23-496b-af0d-7b3df96fb571" end_index="1" portType="0" />
    <Dynamo.Graph.Connectors.ConnectorModel start="1ce2ec91-4bcf-4130-8d89-35cadd8d1f43" start_index="0" end="50a2b19e-fbed-4a23-8a76-a4e75072f547" end_index="2" portType="0" />
    <Dynamo.Graph.Connectors.ConnectorModel start="b35ec0c4-aa0f-419f-94af-d54a4b9ed8c2" start_index="0" end="f8db9a84-75da-428e-836e-c555d6b69667" end_index="0" portType="0" />
    <Dynamo.Graph.Connectors.ConnectorModel start="b35ec0c4-aa0f-419f-94af-d54a4b9ed8c2" start_index="0" end="50a2b19e-fbed-4a23-8a76-a4e75072f547" end_index="1" portType="0" />
    <Dynamo.Graph.Connectors.ConnectorModel start="3dd30da0-4fb1-4479-93ac-5071a5220356" start_index="0" end="b35ec0c4-aa0f-419f-94af-d54a4b9ed8c2" end_index="2" portType="0" />
    <Dynamo.Graph.Connectors.ConnectorModel start="0546ebc9-4515-42f3-ad4b-d0b89e58418d" start_index="0" end="ed795f6d-0362-4887-a1a6-6398a133b472" end_index="0" portType="0" />
    <Dynamo.Graph.Connectors.ConnectorModel start="f8db9a84-75da-428e-836e-c555d6b69667" start_index="0" end="0546ebc9-4515-42f3-ad4b-d0b89e58418d" end_index="0" portType="0" />
    <Dynamo.Graph.Connectors.ConnectorModel start="874f14ae-5254-43e0-b753-1cb424a6d686" start_index="0" end="d7400d6f-2861-401b-8d11-28a63e5f54d9" end_index="0" portType="0" />
    <Dynamo.Graph.Connectors.ConnectorModel start="5ab7b0f1-314d-40f8-a6f3-cb3ce02f2048" start_index="0" end="874f14ae-5254-43e0-b753-1cb424a6d686" end_index="1" portType="0" />
    <Dynamo.Graph.Connectors.ConnectorModel start="ed795f6d-0362-4887-a1a6-6398a133b472" start_index="0" end="874f14ae-5254-43e0-b753-1cb424a6d686" end_index="2" portType="0" />
  </Connectors>
  <Notes />
  <Annotations />
  <Presets />
  <Cameras>
    <Camera Name="Background Preview" eyeX="3490.78559330546" eyeY="4842.38156591127" eyeZ="22400.2152541017" lookX="4469.89067622579" lookY="-4842.38156591127" lookZ="-21604.471601758" upX="0" upY="1" upZ="0" />
  </Cameras>
</Workspace>