{
  "Uuid": "efa1ec2c-4621-4159-95b7-e229c7d11de4",
  "IsCustomNode": false,
  "Description": null,
  "Name": "changeElementLocation",
  "ElementResolver": {
    "ResolutionMap": {}
  },
  "Inputs": [],
  "Outputs": [],
  "Nodes": [
    {
      "ConcreteType": "PythonNodeModels.PythonNode, PythonNodeModels",
      "NodeType": "PythonScriptNode",
      "Code": "import clr\r\n\r\nclr.AddReference(\"RevitServices\")\r\nimport RevitServices\r\nfrom RevitServices.Persistence import DocumentManager\r\nfrom RevitServices.Transactions import TransactionManager\r\ndoc = DocumentManager.Instance.CurrentDBDocument\r\n\r\nclr.AddReference(\"RevitAPI\")\r\nimport Autodesk\r\nfrom Autodesk.Revit.DB import *\r\n\r\nclr.AddReference(\"RevitNodes\")\r\nimport Revit\r\nclr.ImportExtensions(Revit.Elements)\r\nclr.ImportExtensions(Revit.GeometryConversion)\r\n\r\nclr.AddReference(\"System\")\r\nfrom System.Collections.Generic import List\r\n\r\nbeamElements = UnwrapElement(IN[0])\r\npts = UnwrapElement(IN[1])\r\n\r\nbeamLocations = []\r\n\r\nfor beam in beamElements:\r\n\tbeamLocations.append(beam.Location)\r\n\r\nnewBeamLine = []\r\n\r\nTransactionManager.Instance.EnsureInTransaction(doc)\r\n\r\nfor i in range(0,len(beamLocations)):\r\n\tnewBeamLine = Line.CreateBound(pts[i][0].ToXyz(), pts[i][1].ToXyz())\r\n\t#Change the beam location line to a new line:\r\n\tbeamLocations[i].Curve = newBeamLine;\r\n\r\n            \r\n\r\nTransactionManager.Instance.TransactionTaskDone()\r\n\r\nOUT = beamElements",
      "VariableInputPorts": true,
      "Id": "c09b9dd775cc4c53a4673b4557598662",
      "Inputs": [
        {
          "Id": "4550cd13d9e74eb6b82de3759924ed8e",
          "Name": "IN[0]",
          "Description": "Input #0",
          "UsingDefaultValue": false,
          "Level": 2,
          "UseLevels": false,
          "KeepListStructure": false
        },
        {
          "Id": "1064cce1142a41e69e10c7d3e6b84a1c",
          "Name": "IN[1]",
          "Description": "Input #1",
          "UsingDefaultValue": false,
          "Level": 2,
          "UseLevels": false,
          "KeepListStructure": false
        }
      ],
      "Outputs": [
        {
          "Id": "80f3c632b0704a58a3a1886e90deeccf",
          "Name": "OUT",
          "Description": "Result of the python script",
          "UsingDefaultValue": false,
          "Level": 2,
          "UseLevels": false,
          "KeepListStructure": false
        }
      ],
      "Replication": "Disabled",
      "Description": "Runs an embedded IronPython script."
    },
    {
      "ConcreteType": "PythonNodeModels.PythonNode, PythonNodeModels",
      "NodeType": "PythonScriptNode",
      "Code": "import clr\r\nclr.AddReference('RevitAPI')\r\nfrom Autodesk.Revit.DB import *\r\n\r\nclr.AddReference(\"RevitNodes\")\r\nimport Revit\r\nclr.ImportExtensions(Revit.GeometryConversion)\r\n\r\nclr.AddReference('ProtoGeometry')\r\nfrom Autodesk.DesignScript.Geometry import *\r\n\r\nitems = UnwrapElement(IN[0])\r\n\r\nlines = []\r\n\r\nfor item in items:\r\n\tlines.append(item.Location.Curve.ToProtoType())\r\n\r\nPts = []\r\n\r\n\r\nfor line in lines:\r\n\tpt = []\r\n\tpt.append(Curve.PointAtParameter(line,1))\r\n\tpt.append(Curve.PointAtParameter(line,0))\r\n\tPts.append(pt)\r\n\r\nOUT = Pts",
      "VariableInputPorts": true,
      "Id": "90f64e5f5367409db9791a6936055e5b",
      "Inputs": [
        {
          "Id": "917fbdba44524f528f1764e0ab390c81",
          "Name": "IN[0]",
          "Description": "Input #0",
          "UsingDefaultValue": false,
          "Level": 2,
          "UseLevels": false,
          "KeepListStructure": false
        }
      ],
      "Outputs": [
        {
          "Id": "3e4a82978c0342d68a0d18a97ac186d2",
          "Name": "OUT",
          "Description": "Result of the python script",
          "UsingDefaultValue": false,
          "Level": 2,
          "UseLevels": false,
          "KeepListStructure": false
        }
      ],
      "Replication": "Disabled",
      "Description": "Runs an embedded IronPython script."
    },
    {
      "ConcreteType": "Dynamo.Nodes.DSModelElementSelection, DSRevitNodesUI",
      "NodeType": "ExtensionNode",
      "InstanceId": [
        "dbdf6fc0-3aa5-41d9-9c8a-c85aa9fe559b-0022e4c8"
      ],
      "Id": "c3fa180f86e445e5b25f5aba6f7a73d8",
      "Inputs": [],
      "Outputs": [
        {
          "Id": "47886fa80abe47ea895b8a3578296bb7",
          "Name": "Element",
          "Description": "The selected elements.",
          "UsingDefaultValue": false,
          "Level": 2,
          "UseLevels": false,
          "KeepListStructure": false
        }
      ],
      "Replication": "Disabled"
    },
    {
      "ConcreteType": "Dynamo.Nodes.DSModelElementSelection, DSRevitNodesUI",
      "NodeType": "ExtensionNode",
      "InstanceId": [
        "52395639-69d2-46f0-a305-de561047c8bc-0026d1a1"
      ],
      "Id": "38bcc9152d9043aeab7419b7cc91d71c",
      "Inputs": [],
      "Outputs": [
        {
          "Id": "73ef49f8d5cc4d74adf17078cf298f3b",
          "Name": "Element",
          "Description": "The selected elements.",
          "UsingDefaultValue": false,
          "Level": 2,
          "UseLevels": false,
          "KeepListStructure": false
        }
      ],
      "Replication": "Disabled"
    },
    {
      "ConcreteType": "Dynamo.Graph.Nodes.CodeBlockNodeModel, DynamoCore",
      "NodeType": "CodeBlockNode",
      "Code": "[a];",
      "Id": "27b2af637d7f4599844e333040450fcc",
      "Inputs": [
        {
          "Id": "0b4cb7d40e0e4adea9fea8880a8a54bb",
          "Name": "a",
          "Description": "a",
          "UsingDefaultValue": false,
          "Level": 2,
          "UseLevels": false,
          "KeepListStructure": false
        }
      ],
      "Outputs": [
        {
          "Id": "8bac3c0920344da082ba5c644c14817c",
          "Name": "",
          "Description": "Value of expression at line 1",
          "UsingDefaultValue": false,
          "Level": 2,
          "UseLevels": false,
          "KeepListStructure": false
        }
      ],
      "Replication": "Disabled",
      "Description": "Allows for DesignScript code to be authored directly"
    },
    {
      "ConcreteType": "Dynamo.Graph.Nodes.CodeBlockNodeModel, DynamoCore",
      "NodeType": "CodeBlockNode",
      "Code": "[a];",
      "Id": "f8cdc0defee445bebe99405337d62822",
      "Inputs": [
        {
          "Id": "87400808047b4dc1ac38de3ab8a6564a",
          "Name": "a",
          "Description": "a",
          "UsingDefaultValue": false,
          "Level": 2,
          "UseLevels": false,
          "KeepListStructure": false
        }
      ],
      "Outputs": [
        {
          "Id": "36cf61e18129494689e81cfe07e7c1ff",
          "Name": "",
          "Description": "Value of expression at line 1",
          "UsingDefaultValue": false,
          "Level": 2,
          "UseLevels": false,
          "KeepListStructure": false
        }
      ],
      "Replication": "Disabled",
      "Description": "Allows for DesignScript code to be authored directly"
    },
    {
      "ConcreteType": "Dynamo.Nodes.DSModelElementSelection, DSRevitNodesUI",
      "NodeType": "ExtensionNode",
      "InstanceId": [
        "4f10eac7-d022-477b-a99b-5be33d07fc8d-0026c7e8"
      ],
      "Id": "c9adc00e914a49e0b76f8f9cb0e55fff",
      "Inputs": [],
      "Outputs": [
        {
          "Id": "3a0bf107a26d41109d18a39558c49d15",
          "Name": "Element",
          "Description": "The selected elements.",
          "UsingDefaultValue": false,
          "Level": 2,
          "UseLevels": false,
          "KeepListStructure": false
        }
      ],
      "Replication": "Disabled"
    },
    {
      "ConcreteType": "Dynamo.Graph.Nodes.ZeroTouch.DSFunction, DynamoCore",
      "NodeType": "FunctionNode",
      "FunctionSignature": "Revit.Elements.Element.Curves",
      "Id": "1557a4946ef74aa9b02c7cca9ae1b461",
      "Inputs": [
        {
          "Id": "5209e493fc5146a0abf4818c1d26a5c1",
          "Name": "element",
          "Description": "Revit.Elements.Element",
          "UsingDefaultValue": false,
          "Level": 2,
          "UseLevels": false,
          "KeepListStructure": false
        }
      ],
      "Outputs": [
        {
          "Id": "de0e678de4be48fb97769fcd384c9179",
          "Name": "Curve[]",
          "Description": "Curve[]",
          "UsingDefaultValue": false,
          "Level": 2,
          "UseLevels": false,
          "KeepListStructure": false
        }
      ],
      "Replication": "Auto",
      "Description": "The Curves in this Element\n\nElement.Curves: Curve[]"
    },
    {
      "ConcreteType": "Dynamo.Graph.Nodes.ZeroTouch.DSFunction, DynamoCore",
      "NodeType": "FunctionNode",
      "FunctionSignature": "Revit.Elements.ModelCurve.ByCurve@Autodesk.DesignScript.Geometry.Curve",
      "Id": "0e91dfd7e6074c0ebe6b7ab0e5a26d3d",
      "Inputs": [
        {
          "Id": "d202d630d04d4dd1ab324924ed084e91",
          "Name": "curve",
          "Description": "Curve",
          "UsingDefaultValue": false,
          "Level": 2,
          "UseLevels": false,
          "KeepListStructure": false
        }
      ],
      "Outputs": [
        {
          "Id": "ad645ad87e584955afd8bc6851b604e1",
          "Name": "ModelCurve",
          "Description": "ModelCurve",
          "UsingDefaultValue": false,
          "Level": 2,
          "UseLevels": false,
          "KeepListStructure": false
        }
      ],
      "Replication": "Auto",
      "Description": "Construct a Revit ModelCurve element from a Curve\n\nModelCurve.ByCurve (curve: Curve): ModelCurve"
    }
  ],
  "Connectors": [
    {
      "Start": "3e4a82978c0342d68a0d18a97ac186d2",
      "End": "1064cce1142a41e69e10c7d3e6b84a1c",
      "Id": "08833e6fa3474f5ca93d0ed80517f9b5"
    },
    {
      "Start": "47886fa80abe47ea895b8a3578296bb7",
      "End": "0b4cb7d40e0e4adea9fea8880a8a54bb",
      "Id": "3f707e7d97c64c03a3d662c6a69db19c"
    },
    {
      "Start": "73ef49f8d5cc4d74adf17078cf298f3b",
      "End": "87400808047b4dc1ac38de3ab8a6564a",
      "Id": "713aca1b95a64b8785b94c7034273a3b"
    },
    {
      "Start": "8bac3c0920344da082ba5c644c14817c",
      "End": "4550cd13d9e74eb6b82de3759924ed8e",
      "Id": "6d28af63d2a24f15889db82182238e19"
    },
    {
      "Start": "36cf61e18129494689e81cfe07e7c1ff",
      "End": "917fbdba44524f528f1764e0ab390c81",
      "Id": "e196c2a44fc84a8ba2fb24707573f611"
    },
    {
      "Start": "3a0bf107a26d41109d18a39558c49d15",
      "End": "5209e493fc5146a0abf4818c1d26a5c1",
      "Id": "72ddbd486e1e4c0a826192a8f3e05208"
    },
    {
      "Start": "de0e678de4be48fb97769fcd384c9179",
      "End": "d202d630d04d4dd1ab324924ed084e91",
      "Id": "0ba99e70626f4da7a6312063cab2e4b8"
    }
  ],
  "Dependencies": [],
  "Bindings": [],
  "View": {
    "Dynamo": {
      "ScaleFactor": 1.0,
      "HasRunWithoutCrash": true,
      "IsVisibleInDynamoLibrary": true,
      "Version": "2.0.1.4955",
      "RunType": "Manual",
      "RunPeriod": "1000"
    },
    "Camera": {
      "Name": "Background Preview",
      "EyeX": -17.0,
      "EyeY": 24.0,
      "EyeZ": 50.0,
      "LookX": 12.0,
      "LookY": -13.0,
      "LookZ": -58.0,
      "UpX": 0.0,
      "UpY": 1.0,
      "UpZ": 0.0
    },
    "NodeViews": [
      {
        "ShowGeometry": true,
        "Name": "Python Script",
        "Id": "c09b9dd775cc4c53a4673b4557598662",
        "IsSetAsInput": false,
        "IsSetAsOutput": false,
        "Excluded": false,
        "X": 521.0,
        "Y": 160.0
      },
      {
        "ShowGeometry": true,
        "Name": "Python Script",
        "Id": "90f64e5f5367409db9791a6936055e5b",
        "IsSetAsInput": false,
        "IsSetAsOutput": false,
        "Excluded": false,
        "X": 124.0,
        "Y": 330.0
      },
      {
        "ShowGeometry": true,
        "Name": "Select Model Element",
        "Id": "c3fa180f86e445e5b25f5aba6f7a73d8",
        "IsSetAsInput": false,
        "IsSetAsOutput": false,
        "Excluded": false,
        "X": -195.0,
        "Y": 173.0
      },
      {
        "ShowGeometry": true,
        "Name": "Select Model Element",
        "Id": "38bcc9152d9043aeab7419b7cc91d71c",
        "IsSetAsInput": false,
        "IsSetAsOutput": false,
        "Excluded": false,
        "X": -319.0,
        "Y": 320.0
      },
      {
        "ShowGeometry": true,
        "Name": "Code Block",
        "Id": "27b2af637d7f4599844e333040450fcc",
        "IsSetAsInput": false,
        "IsSetAsOutput": false,
        "Excluded": false,
        "X": 131.0,
        "Y": 161.0
      },
      {
        "ShowGeometry": true,
        "Name": "Code Block",
        "Id": "f8cdc0defee445bebe99405337d62822",
        "IsSetAsInput": false,
        "IsSetAsOutput": false,
        "Excluded": false,
        "X": -72.0,
        "Y": 335.0
      },
      {
        "ShowGeometry": true,
        "Name": "Select Model Element",
        "Id": "c9adc00e914a49e0b76f8f9cb0e55fff",
        "IsSetAsInput": false,
        "IsSetAsOutput": false,
        "Excluded": false,
        "X": -505.0,
        "Y": 608.0
      },
      {
        "ShowGeometry": true,
        "Name": "Element.Curves",
        "Id": "1557a4946ef74aa9b02c7cca9ae1b461",
        "IsSetAsInput": false,
        "IsSetAsOutput": false,
        "Excluded": false,
        "X": -244.0,
        "Y": 613.0
      },
      {
        "ShowGeometry": true,
        "Name": "ModelCurve.ByCurve",
        "Id": "0e91dfd7e6074c0ebe6b7ab0e5a26d3d",
        "IsSetAsInput": false,
        "IsSetAsOutput": false,
        "Excluded": false,
        "X": 203.0,
        "Y": 713.0
      }
    ],
    "Annotations": [],
    "X": 558.0,
    "Y": -57.0,
    "Zoom": 1.0
  }
}