<Workspace Version="1.3.1.1736" X="-1179.22150468457" Y="-2355.32390611572" zoom="1.30291136952936" ScaleFactor="1" Name="Home" Description="" RunType="Manual" RunPeriod="1000" HasRunWithoutCrash="True">
  <NamespaceResolutionMap />
  <Elements>
    <Dynamo.Graph.Nodes.CustomNodes.Function guid="a0f61656-3ffe-4b2e-ad3c-2d4e7ec09790" type="Dynamo.Graph.Nodes.CustomNodes.Function" nickname="Get Documents" x="-8.839889087291" y="257.602397480681" isVisible="true" isUpstreamVisible="true" lacing="Shortest" isSelectedInput="True" IsFrozen="false" isPinned="true">
      <ID value="8e388824-b977-427f-81ec-e9669ae4012f" />
      <Name value="Get Documents" />
      <Description value="Queries all linked Revit files and retrieves their Name, LinkInstance and Document properties." />
      <Inputs />
      <Outputs>
        <Output value="Link Instance" />
        <Output value="Link Doc" />
        <Output value="Link Name" />
        <Output value="Link Path" />
      </Outputs>
    </Dynamo.Graph.Nodes.CustomNodes.Function>
    <PythonNodeModels.PythonNode guid="83f789f7-a4a9-408a-8bcd-8ccdb985a09e" type="PythonNodeModels.PythonNode" nickname="Python Script" x="281.665299297148" y="563.076032806014" isVisible="true" isUpstreamVisible="true" lacing="Disabled" isSelectedInput="False" IsFrozen="false" isPinned="true" inputcount="1">
      <PortInfo index="0" default="False" />
      <Script>#Copyright(c) 2015, Konrad Sobon
# @arch_laboratory, http://archi-lab.net

# This node is based on Julien Benoit's Element.GetElementFromLinkedFile 
# node. Some slight improvements were made removing unnecessary imports/references.
# Big thank you to Julien for sharing his work. 

import clr
clr.AddReference('ProtoGeometry')
from Autodesk.DesignScript.Geometry import *

# Import RevitAPI
clr.AddReference("RevitAPI")
import Autodesk
from Autodesk.Revit.DB import *

import System

import sys
pyt_path = r'C:\Program Files (x86)\IronPython 2.7\Lib'
sys.path.append(pyt_path)

#The inputs to this node will be stored as a list in the IN variable.
dataEnteringNode = IN

_linkDoc = IN[0]

try:
	errorReport = None
	result = FilteredElementCollector(_linkDoc[0]).OfCategory(BuiltInCategory.OST_Revisions).WhereElementIsNotElementType().ToElements()
	
except:
	# if error accurs anywhere in the process catch it
	import traceback
	errorReport = traceback.format_exc()

#Assign your output to the OUT variable
if errorReport == None:
	OUT = result
else:
	OUT = errorReport</Script>
    </PythonNodeModels.PythonNode>
    <Dynamo.Graph.Nodes.ZeroTouch.DSFunction guid="da98c98d-a9f7-4329-8cd7-219496fde318" type="Dynamo.Graph.Nodes.ZeroTouch.DSFunction" nickname="Element.Name" x="1138.45225918024" y="709.829720125696" isVisible="true" isUpstreamVisible="true" lacing="Shortest" isSelectedInput="False" IsFrozen="false" isPinned="true" assembly="RevitNodes.dll" function="Revit.Elements.Element.Name">
      <PortInfo index="0" default="False" />
    </Dynamo.Graph.Nodes.ZeroTouch.DSFunction>
    <PythonNodeModels.PythonNode guid="fa0963ce-3b60-4a94-894e-ca5ed4e2b67d" type="PythonNodeModels.PythonNode" nickname="Python Script" x="717.062855859856" y="832.934340403206" isVisible="true" isUpstreamVisible="true" lacing="Disabled" isSelectedInput="False" IsFrozen="false" isPinned="true" inputcount="1">
      <PortInfo index="0" default="False" />
      <Script># Copyright(c) 2015, Konrad K Sobon
# @arch_laboratory, http://archi-lab.net

import clr
# Import Element wrapper extension methods
clr.AddReference("RevitNodes")
import Revit
clr.ImportExtensions(Revit.Elements)

# Import DocumentManager and TransactionManager
clr.AddReference("RevitServices")
import RevitServices
from RevitServices.Persistence import DocumentManager
doc = DocumentManager.Instance.CurrentDBDocument

# Import RevitAPI
clr.AddReference("RevitAPI")
import Autodesk
from Autodesk.Revit.DB import *

import sys
pyt_path = r'C:\Program Files (x86)\IronPython 2.7\Lib'
sys.path.append(pyt_path)

#The inputs to this node will be stored as a list in the IN variable.
dataEnteringNode = IN
rev = IN[0]

name = []

for r in rev:
	name.append(r.Name)

OUT = name</Script>
    </PythonNodeModels.PythonNode>
    <PythonNodeModels.PythonNode guid="93772bb6-88f5-41fa-a669-a92b6f995962" type="PythonNodeModels.PythonNode" nickname="Python Script" x="862.711999852056" y="561.578285444944" isVisible="true" isUpstreamVisible="true" lacing="Disabled" isSelectedInput="False" IsFrozen="false" isPinned="true" inputcount="2">
      <PortInfo index="0" default="False" />
      <PortInfo index="1" default="False" />
      <Script>import clr

clr.AddReference("RevitServices")
import RevitServices
from RevitServices.Persistence import DocumentManager
from RevitServices.Transactions import TransactionManager
doc = DocumentManager.Instance.CurrentDBDocument

clr.AddReference("RevitAPI")
import Autodesk
from Autodesk.Revit.DB import *

clr.AddReference("RevitNodes")
import Revit
clr.ImportExtensions(Revit.Elements)
clr.ImportExtensions(Revit.GeometryConversion)

clr.AddReference("System")
from System.Collections.Generic import List

linkDoc = UnwrapElement(IN[0])
rev = UnwrapElement(IN[1])

revId = []

for r in rev:
	revId.append(r.Id)

revIds = List[ElementId](revId)

allRevisions = Revision.GetAllRevisionIds(doc)

copiedElements = []

copyIds = []

for c in copiedElements:
	copyIds.append(c.Id)

newOrder = copyIds

newOrder.Insert(0,allRevisions[0])


TransactionManager.Instance.EnsureInTransaction(doc)

copy = ElementTransformUtils.CopyElements(linkDoc[0],revIds,doc,Transform.Identity,None)

for c in copy:
		copiedElements.append(doc.GetElement(c).ToDSType(True))

#Revision.ReorderRevisionSequence(doc,newOrder)

TransactionManager.Instance.TransactionTaskDone()


OUT = copiedElements, newOrder, copyIds</Script>
    </PythonNodeModels.PythonNode>
    <Dynamo.Graph.Nodes.CustomNodes.Function guid="f1b1c1cb-fdd2-4196-8321-ba4f01bd919e" type="Dynamo.Graph.Nodes.CustomNodes.Function" nickname="Element.GetFromLinkedFile" x="543.160110912709" y="40.602397480681" isVisible="true" isUpstreamVisible="true" lacing="Shortest" isSelectedInput="False" IsFrozen="false" isPinned="true">
      <PortInfo index="0" default="False" />
      <PortInfo index="1" default="False" />
      <PortInfo index="2" default="False" />
      <ID value="8eccfa8a-771e-4be5-a92b-4fef36310e6b" />
      <Name value="Element.GetFromLinkedFile" />
      <Description value="Get elements from link document instance based on category" />
      <Inputs>
        <Input value="Link Instance" />
        <Input value="Link Document" />
        <Input value="Category" />
      </Inputs>
      <Outputs>
        <Output value="Element(s)" />
      </Outputs>
    </Dynamo.Graph.Nodes.CustomNodes.Function>
    <DSRevitNodesUI.Categories guid="6e6cb336-88ab-401f-a354-afea5c1e09cf" type="DSRevitNodesUI.Categories" nickname="Categories" x="167.160110912709" y="96.602397480681" isVisible="true" isUpstreamVisible="true" lacing="Disabled" isSelectedInput="True" IsFrozen="false" isPinned="false" index="574:Walls" />
    <PythonNodeModels.PythonNode guid="9c8db7b2-a302-4a7b-bc24-959c9c3f6a17" type="PythonNodeModels.PythonNode" nickname="Python Script" x="674.230976825348" y="291.420942490982" isVisible="true" isUpstreamVisible="true" lacing="Disabled" isSelectedInput="False" IsFrozen="false" isPinned="true" inputcount="2">
      <PortInfo index="0" default="False" />
      <PortInfo index="1" default="False" />
      <Script>import clr

clr.AddReference("RevitServices")
import RevitServices
from RevitServices.Persistence import DocumentManager
from RevitServices.Transactions import TransactionManager
doc = DocumentManager.Instance.CurrentDBDocument

clr.AddReference("RevitAPI")
import Autodesk
from Autodesk.Revit.DB import *

clr.AddReference("RevitNodes")
import Revit
clr.ImportExtensions(Revit.Elements)
clr.ImportExtensions(Revit.GeometryConversion)

clr.AddReference("System")
from System.Collections.Generic import List

linkDoc = UnwrapElement(IN[0])
rev = UnwrapElement(IN[1])

revId = []

for r in rev:
	revId.append(r.Id)

revIds = List[ElementId](revId)

copiedElements = []
#The inputs to this node will be stored as a list in the IN variable.
TransactionManager.Instance.EnsureInTransaction(doc)

copy = Autodesk.Revit.DB.ElementTransformUtils.CopyElements(linkDoc[0],revIds,doc,None,None)

for c in copy:
	#copiedElements.append(doc.GetElement(c).ToDSType(True))
	copiedElements.append(doc.GetElement(c))
TransactionManager.Instance.TransactionTaskDone()

OUT = copiedElements
</Script>
    </PythonNodeModels.PythonNode>
    <PythonNodeModels.PythonNode guid="a682794f-5f68-406d-947f-cddd8bdbf620" type="PythonNodeModels.PythonNode" nickname="Python Script" x="904.033491917103" y="710.317171297298" isVisible="true" isUpstreamVisible="true" lacing="Disabled" isSelectedInput="False" IsFrozen="true" isPinned="true" inputcount="1">
      <PortInfo index="0" default="False" />
      <Script># Copyright(c) 2015, Konrad K Sobon
# @arch_laboratory, http://archi-lab.net

import clr
# Import Element wrapper extension methods
clr.AddReference("RevitNodes")
import Revit
clr.ImportExtensions(Revit.Elements)

# Import DocumentManager and TransactionManager
clr.AddReference("RevitServices")
import RevitServices
from RevitServices.Persistence import DocumentManager
doc = DocumentManager.Instance.CurrentDBDocument

# Import RevitAPI
clr.AddReference("RevitAPI")
import Autodesk
from Autodesk.Revit.DB import *

clr.AddReference("System")
from System.Collections.Generic import List

import sys
pyt_path = r'C:\Program Files (x86)\IronPython 2.7\Lib'
sys.path.append(pyt_path)

result = FilteredElementCollector(doc).OfCategory(BuiltInCategory.OST_Revisions).WhereElementIsNotElementType().ToElements()

revId = []

for r in result:
	revId.append(r.Id)

revIds = List[ElementId](revId)



Revision.ReorderRevisionSequence(doc, revId)

OUT = result</Script>
    </PythonNodeModels.PythonNode>
    <PythonNodeModels.PythonNode guid="87ac7f36-49fd-4e74-bf7f-0ed87da6ab5f" type="PythonNodeModels.PythonNode" nickname="Python Script" x="1402.67513782555" y="837.036321300116" isVisible="true" isUpstreamVisible="true" lacing="Disabled" isSelectedInput="False" IsFrozen="false" isPinned="true" inputcount="1">
      <PortInfo index="0" default="False" />
      <Script>#Copyright(c) 2015, Konrad Sobon
# @arch_laboratory, http://archi-lab.net

# This node is based on Julien Benoit's Element.GetElementFromLinkedFile 
# node. Some slight improvements were made removing unnecessary imports/references.
# Big thank you to Julien for sharing his work. 

import clr
clr.AddReference('ProtoGeometry')
from Autodesk.DesignScript.Geometry import *

# Import RevitAPI
clr.AddReference("RevitAPI")
import Autodesk
from Autodesk.Revit.DB import *

import System

import sys
pyt_path = r'C:\Program Files (x86)\IronPython 2.7\Lib'
sys.path.append(pyt_path)

#The inputs to this node will be stored as a list in the IN variable.
dataEnteringNode = IN

_linkDoc = IN[0]

try:
	errorReport = None
	result = FilteredElementCollector(_linkDoc[0]).OfCategory(BuiltInCategory.OST_Revisions).WhereElementIsNotElementType().ToElements()
	
except:
	# if error accurs anywhere in the process catch it
	import traceback
	errorReport = traceback.format_exc()

#Assign your output to the OUT variable
if errorReport == None:
	OUT = result
else:
	OUT = errorReport</Script>
    </PythonNodeModels.PythonNode>
    <PythonNodeModels.PythonNode guid="eeb6e6c8-e45b-4973-b00b-69271e216a53" type="PythonNodeModels.PythonNode" nickname="Python Script" x="502.287359809317" y="1087.29318168022" isVisible="true" isUpstreamVisible="true" lacing="Disabled" isSelectedInput="False" IsFrozen="false" isPinned="false" inputcount="1">
      <PortInfo index="0" default="False" />
      <Script># Copyright(c) 2015, Konrad K Sobon
# @arch_laboratory, http://archi-lab.net

import clr
# Import Element wrapper extension methods
clr.AddReference("RevitNodes")
import Revit
clr.ImportExtensions(Revit.Elements)

# Import DocumentManager and TransactionManager
clr.AddReference("RevitServices")
import RevitServices
from RevitServices.Persistence import DocumentManager
doc = DocumentManager.Instance.CurrentDBDocument

# Import RevitAPI
clr.AddReference("RevitAPI")
import Autodesk
from Autodesk.Revit.DB import *

clr.AddReference("System")
from System.Collections.Generic import List

import sys
pyt_path = r'C:\Program Files (x86)\IronPython 2.7\Lib'
sys.path.append(pyt_path)

lyncDoc = IN[0]

allRevisions = Revision.GetAllRevisionIds(doc)
linkedRevisions = Revision.GetAllRevisionIds(lyncDoc[0])


newOrder = [linkedRevisions,allRevisions[0]]

#revIds = List[ElementId]()


#Revision.ReorderRevisionSequence(doc, revIds)

OUT = allRevisions, linkedRevisions, newOrder</Script>
    </PythonNodeModels.PythonNode>
    <PythonNodeModels.PythonNode guid="e2e6c2b5-bb20-4c2b-8d46-4b4400bd956f" type="PythonNodeModels.PythonNode" nickname="Python Script" x="846.289495336714" y="1119.33772542872" isVisible="true" isUpstreamVisible="true" lacing="Disabled" isSelectedInput="False" IsFrozen="false" isPinned="true" inputcount="1">
      <PortInfo index="0" default="False" />
      <Script># Copyright(c) 2015, Konrad K Sobon
# @arch_laboratory, http://archi-lab.net

import clr
# Import Element wrapper extension methods
clr.AddReference("RevitNodes")
import Revit
clr.ImportExtensions(Revit.Elements)

# Import DocumentManager and TransactionManager
clr.AddReference("RevitServices")
import RevitServices
from RevitServices.Persistence import DocumentManager
from RevitServices.Transactions import TransactionManager
doc = DocumentManager.Instance.CurrentDBDocument

# Import RevitAPI
clr.AddReference("RevitAPI")
import Autodesk
from Autodesk.Revit.DB import *

clr.AddReference("System")
from System.Collections.Generic import List

import sys
pyt_path = r'C:\Program Files (x86)\IronPython 2.7\Lib'
sys.path.append(pyt_path)


revId = IN[0]

TransactionManager.Instance.EnsureInTransaction(doc)

Revision.ReorderRevisionSequence(doc, revId)
result = FilteredElementCollector(doc).OfCategory(BuiltInCategory.OST_Revisions).WhereElementIsNotElementType().ToElements()

TransactionManager.Instance.TransactionTaskDone()

OUT = result</Script>
    </PythonNodeModels.PythonNode>
    <Dynamo.Graph.Nodes.ZeroTouch.DSFunction guid="61bffa85-6f64-4236-9813-58f7bd48b190" type="Dynamo.Graph.Nodes.ZeroTouch.DSFunction" nickname="Element.Name" x="1039.32126510485" y="1094.00744521222" isVisible="true" isUpstreamVisible="true" lacing="Shortest" isSelectedInput="False" IsFrozen="false" isPinned="true" assembly="RevitNodes.dll" function="Revit.Elements.Element.Name">
      <PortInfo index="0" default="False" />
    </Dynamo.Graph.Nodes.ZeroTouch.DSFunction>
    <Dynamo.Graph.Nodes.CodeBlockNodeModel guid="68d44933-bbd0-4985-8cae-18b082136aa2" type="Dynamo.Graph.Nodes.CodeBlockNodeModel" nickname="Code Block" x="666.189178784032" y="1092.414835681" isVisible="true" isUpstreamVisible="true" lacing="Disabled" isSelectedInput="False" IsFrozen="false" isPinned="true" CodeText="a[0];" ShouldFocus="false">
      <PortInfo index="0" default="False" />
    </Dynamo.Graph.Nodes.CodeBlockNodeModel>
    <Dynamo.Graph.Nodes.ZeroTouch.DSFunction guid="b8f3839c-d13d-4f9b-9fd9-9e5eb447c618" type="Dynamo.Graph.Nodes.ZeroTouch.DSFunction" nickname="List.RestOfItems" x="470.930955700719" y="564.335575992641" isVisible="true" isUpstreamVisible="true" lacing="Shortest" isSelectedInput="False" IsFrozen="false" isPinned="true" assembly="DSCoreNodes.dll" function="DSCore.List.RestOfItems@var[]..[]">
      <PortInfo index="0" default="False" />
    </Dynamo.Graph.Nodes.ZeroTouch.DSFunction>
    <PythonNodeModels.PythonNode guid="6a2609b5-1d59-4b53-91e2-640d6e9694fb" type="PythonNodeModels.PythonNode" nickname="Python Script" x="1718.93613488477" y="424.907014565699" isVisible="true" isUpstreamVisible="true" lacing="Disabled" isSelectedInput="False" IsFrozen="false" isPinned="true" inputcount="1">
      <PortInfo index="0" default="False" />
      <Script># Copyright(c) 2015, Konrad K Sobon
# @arch_laboratory, http://archi-lab.net

import clr
# Import Element wrapper extension methods
clr.AddReference("RevitNodes")
import Revit
clr.ImportExtensions(Revit.Elements)

# Import DocumentManager and TransactionManager
clr.AddReference("RevitServices")
import RevitServices
from RevitServices.Persistence import DocumentManager
doc = DocumentManager.Instance.CurrentDBDocument

# Import RevitAPI
clr.AddReference("RevitAPI")
import Autodesk
from Autodesk.Revit.DB import *

clr.AddReference("System")
from System.Collections.Generic import List

import sys
pyt_path = r'C:\Program Files (x86)\IronPython 2.7\Lib'
sys.path.append(pyt_path)



allRevisions = Revision.GetAllRevisionIds(doc)

#revIds = List[ElementId]()


#Revision.ReorderRevisionSequence(doc, revIds)

OUT = allRevisions</Script>
    </PythonNodeModels.PythonNode>
    <PythonNodeModels.PythonNode guid="ac337bee-446c-4dd1-b856-98e0823affa7" type="PythonNodeModels.PythonNode" nickname="Python Script" x="1370.1447550088" y="395.865265842543" isVisible="true" isUpstreamVisible="true" lacing="Disabled" isSelectedInput="False" IsFrozen="false" isPinned="true" inputcount="1">
      <PortInfo index="0" default="False" />
      <Script># Copyright(c) 2015, Konrad K Sobon
# @arch_laboratory, http://archi-lab.net

import clr
# Import Element wrapper extension methods
clr.AddReference("RevitNodes")
import Revit
clr.ImportExtensions(Revit.Elements)

# Import DocumentManager and TransactionManager
clr.AddReference("RevitServices")
import RevitServices
from RevitServices.Persistence import DocumentManager
doc = DocumentManager.Instance.CurrentDBDocument

# Import RevitAPI
clr.AddReference("RevitAPI")
import Autodesk
from Autodesk.Revit.DB import *

import sys
pyt_path = r'C:\Program Files (x86)\IronPython 2.7\Lib'
sys.path.append(pyt_path)

#The inputs to this node will be stored as a list in the IN variable.
dataEnteringNode = IN
rev = IN[0]

name = []

for r in rev:
	name.append(r.Name)

OUT = name</Script>
    </PythonNodeModels.PythonNode>
    <Dynamo.Graph.Nodes.CodeBlockNodeModel guid="6040f7ef-dc5a-4f6d-bb52-c940264f037c" type="Dynamo.Graph.Nodes.CodeBlockNodeModel" nickname="Code Block" x="1193.84144963138" y="401.133636361227" isVisible="true" isUpstreamVisible="true" lacing="Disabled" isSelectedInput="False" IsFrozen="false" isPinned="false" CodeText="a[0];" ShouldFocus="false">
      <PortInfo index="0" default="False" />
    </Dynamo.Graph.Nodes.CodeBlockNodeModel>
    <Dynamo.Graph.Nodes.ZeroTouch.DSFunction guid="d6d8bc7a-b942-4519-b756-e82c3ac2a8f4" type="Dynamo.Graph.Nodes.ZeroTouch.DSFunction" nickname="Element.Id" x="1512.46773708604" y="616.470342580337" isVisible="true" isUpstreamVisible="true" lacing="Shortest" isSelectedInput="False" IsFrozen="false" isPinned="true" assembly="RevitNodes.dll" function="Revit.Elements.Element.Id">
      <PortInfo index="0" default="False" />
    </Dynamo.Graph.Nodes.ZeroTouch.DSFunction>
    <PythonNodeModels.PythonNode guid="d12ab54b-edf1-412a-91f4-38a014cb70c1" type="PythonNodeModels.PythonNode" nickname="Python Script" x="2432.92337354443" y="510.160840663735" isVisible="true" isUpstreamVisible="true" lacing="Disabled" isSelectedInput="False" IsFrozen="false" isPinned="true" inputcount="1">
      <PortInfo index="0" default="False" />
      <Script># Copyright(c) 2015, Konrad K Sobon
# @arch_laboratory, http://archi-lab.net

import clr
# Import Element wrapper extension methods
clr.AddReference("RevitNodes")
import Revit
clr.ImportExtensions(Revit.Elements)

# Import DocumentManager and TransactionManager
clr.AddReference("RevitServices")
import RevitServices
from RevitServices.Persistence import DocumentManager
from RevitServices.Transactions import TransactionManager
doc = DocumentManager.Instance.CurrentDBDocument

# Import RevitAPI
clr.AddReference("RevitAPI")
import Autodesk
from Autodesk.Revit.DB import *

clr.AddReference("System")
from System.Collections.Generic import List

import sys
pyt_path = r'C:\Program Files (x86)\IronPython 2.7\Lib'
sys.path.append(pyt_path)


revId = IN[0]

TransactionManager.Instance.EnsureInTransaction(doc)

Revision.ReorderRevisionSequence(doc, revId)
result = FilteredElementCollector(doc).OfCategory(BuiltInCategory.OST_Revisions).WhereElementIsNotElementType().ToElements()

TransactionManager.Instance.TransactionTaskDone()

OUT = result</Script>
    </PythonNodeModels.PythonNode>
    <Dynamo.Graph.Nodes.ZeroTouch.DSFunction guid="55b58cbb-1f79-46dd-90f5-a1e946a2ab2f" type="Dynamo.Graph.Nodes.ZeroTouch.DSFunction" nickname="List.AddItemToFront" x="1927.22876905038" y="436.895035444938" isVisible="true" isUpstreamVisible="true" lacing="Shortest" isSelectedInput="False" IsFrozen="false" isPinned="true" assembly="DSCoreNodes.dll" function="DSCore.List.AddItemToFront@var[]..[],var[]..[]">
      <PortInfo index="0" default="False" />
      <PortInfo index="1" default="False" />
    </Dynamo.Graph.Nodes.ZeroTouch.DSFunction>
    <Dynamo.Graph.Nodes.ZeroTouch.DSFunction guid="7b10c236-4f31-49eb-acd8-06709b2281f8" type="Dynamo.Graph.Nodes.ZeroTouch.DSFunction" nickname="Flatten" x="2121.86523097778" y="509.883708667713" isVisible="true" isUpstreamVisible="true" lacing="Shortest" isSelectedInput="False" IsFrozen="false" isPinned="true" assembly="BuiltIn" function="Flatten@var[]..[]">
      <PortInfo index="0" default="False" />
    </Dynamo.Graph.Nodes.ZeroTouch.DSFunction>
    <PythonNodeModels.PythonNode guid="7b8ca3f0-af54-4187-a14c-9d3cdab73610" type="PythonNodeModels.PythonNode" nickname="Python Script" x="394.339943303795" y="1349.42073689629" isVisible="true" isUpstreamVisible="true" lacing="Disabled" isSelectedInput="False" IsFrozen="false" isPinned="true" inputcount="1">
      <PortInfo index="0" default="False" />
      <Script># Copyright(c) 2015, Konrad K Sobon
# @arch_laboratory, http://archi-lab.net

import clr
# Import Element wrapper extension methods
clr.AddReference("RevitNodes")
import Revit
clr.ImportExtensions(Revit.Elements)

# Import DocumentManager and TransactionManager
clr.AddReference("RevitServices")
import RevitServices
from RevitServices.Persistence import DocumentManager
doc = DocumentManager.Instance.CurrentDBDocument

# Import RevitAPI
clr.AddReference("RevitAPI")
import Autodesk
from Autodesk.Revit.DB import *

clr.AddReference("System")
from System.Collections.Generic import List

import sys
pyt_path = r'C:\Program Files (x86)\IronPython 2.7\Lib'
sys.path.append(pyt_path)

lyncDoc = IN[0]

allRevisions = Revision.GetAllRevisionIds(doc)


#revIds = List[ElementId]()


#Revision.ReorderRevisionSequence(doc, revIds)

OUT = allRevisions</Script>
    </PythonNodeModels.PythonNode>
    <PythonNodeModels.PythonNode guid="4262e6c8-f1eb-4b58-ad75-e3f5d1cabd6b" type="PythonNodeModels.PythonNode" nickname="Python Script" x="918.03575296597" y="1346.98671728836" isVisible="true" isUpstreamVisible="true" lacing="Disabled" isSelectedInput="False" IsFrozen="false" isPinned="true" inputcount="1">
      <PortInfo index="0" default="False" />
      <Script># Copyright(c) 2015, Konrad K Sobon
# @arch_laboratory, http://archi-lab.net

import clr
# Import Element wrapper extension methods
clr.AddReference("RevitNodes")
import Revit
clr.ImportExtensions(Revit.Elements)

# Import DocumentManager and TransactionManager
clr.AddReference("RevitServices")
import RevitServices
from RevitServices.Persistence import DocumentManager
from RevitServices.Transactions import TransactionManager
doc = DocumentManager.Instance.CurrentDBDocument

# Import RevitAPI
clr.AddReference("RevitAPI")
import Autodesk
from Autodesk.Revit.DB import *

clr.AddReference("System")
from System.Collections.Generic import List

import sys
pyt_path = r'C:\Program Files (x86)\IronPython 2.7\Lib'
sys.path.append(pyt_path)


rev = IN[0]

revId = []

for r in rev:
	revId.append(r.Id)

element_collection = List[ElementId](rev)
elements_to_hide = collector.WhereElementIsNotElementType().Excluding(element_collection).ToElements()


TransactionManager.Instance.EnsureInTransaction(doc)

#Revision.ReorderRevisionSequence(doc, revId)
#result = FilteredElementCollector(doc).OfCategory(BuiltInCategory.OST_Revisions).WhereElementIsNotElementType().ToElements()
#result = FilteredElementCollector(doc).OfCategory(BuiltInCategory.OST_Revisions).WhereElementIsNotElementType()
TransactionManager.Instance.TransactionTaskDone()

OUT = revId</Script>
    </PythonNodeModels.PythonNode>
    <Dynamo.Graph.Nodes.ZeroTouch.DSFunction guid="011cdd87-38bc-4b00-9176-be24e87aa677" type="Dynamo.Graph.Nodes.ZeroTouch.DSFunction" nickname="Element.Name" x="1192.75689156233" y="1352.14526570507" isVisible="true" isUpstreamVisible="true" lacing="Shortest" isSelectedInput="False" IsFrozen="false" isPinned="true" assembly="RevitNodes.dll" function="Revit.Elements.Element.Name">
      <PortInfo index="0" default="False" />
    </Dynamo.Graph.Nodes.ZeroTouch.DSFunction>
    <Dynamo.Graph.Nodes.ZeroTouch.DSFunction guid="846b9553-a648-4f08-aacf-eec882571746" type="Dynamo.Graph.Nodes.ZeroTouch.DSFunction" nickname="List.Reverse" x="739.280505546105" y="1705.77526366999" isVisible="true" isUpstreamVisible="true" lacing="Shortest" isSelectedInput="False" IsFrozen="false" isPinned="true" assembly="DSCoreNodes.dll" function="DSCore.List.Reverse@var[]..[]">
      <PortInfo index="0" default="False" />
    </Dynamo.Graph.Nodes.ZeroTouch.DSFunction>
    <Dynamo.Graph.Nodes.CodeBlockNodeModel guid="1d85c58f-2d3f-4470-89be-dc0d92dc8419" type="Dynamo.Graph.Nodes.CodeBlockNodeModel" nickname="Code Block" x="322.845136930214" y="2045.93761806893" isVisible="true" isUpstreamVisible="true" lacing="Disabled" isSelectedInput="False" IsFrozen="false" isPinned="true" CodeText="{a,2224657,2224658,2224659};" ShouldFocus="false">
      <PortInfo index="0" default="False" />
    </Dynamo.Graph.Nodes.CodeBlockNodeModel>
    <Dynamo.Graph.Nodes.ZeroTouch.DSFunction guid="cb9ffcb1-85b0-4ded-aca9-759192ca19a7" type="Dynamo.Graph.Nodes.ZeroTouch.DSFunction" nickname="Flatten" x="1041.89845482691" y="1620.85448212432" isVisible="true" isUpstreamVisible="true" lacing="Shortest" isSelectedInput="False" IsFrozen="false" isPinned="true" assembly="BuiltIn" function="Flatten@var[]..[]">
      <PortInfo index="0" default="False" />
    </Dynamo.Graph.Nodes.ZeroTouch.DSFunction>
    <Dynamo.Graph.Nodes.CodeBlockNodeModel guid="80e9d16c-40d1-41a6-90c4-41673239c33e" type="Dynamo.Graph.Nodes.CodeBlockNodeModel" nickname="Code Block" x="534" y="1590" isVisible="true" isUpstreamVisible="true" lacing="Disabled" isSelectedInput="False" IsFrozen="false" isPinned="false" CodeText="{86155,2224673,2224674};" ShouldFocus="false" />
    <Dynamo.Graph.Nodes.ZeroTouch.DSFunction guid="1d358929-9105-4134-b15e-d3b9d4e7043f" type="Dynamo.Graph.Nodes.ZeroTouch.DSFunction" nickname="Object.Type" x="953.716628940922" y="1980.08425584363" isVisible="true" isUpstreamVisible="true" lacing="Shortest" isSelectedInput="False" IsFrozen="false" isPinned="true" assembly="DSCoreNodes.dll" function="DSCore.Object.Type@var">
      <PortInfo index="0" default="False" />
    </Dynamo.Graph.Nodes.ZeroTouch.DSFunction>
    <DSRevitNodesUI.ElementsOfType guid="46269eaf-3fbb-40c5-a8bc-0301333258f9" type="DSRevitNodesUI.ElementsOfType" nickname="All Elements of Type" x="380.263954992136" y="1694.99126310079" isVisible="true" isUpstreamVisible="true" lacing="Disabled" isSelectedInput="False" IsFrozen="false" isPinned="true">
      <PortInfo index="0" default="False" />
    </DSRevitNodesUI.ElementsOfType>
    <DSRevitNodesUI.ElementTypes guid="94ebf93f-e5f6-4744-973c-7be07b46d78d" type="DSRevitNodesUI.ElementTypes" nickname="Element Types" x="123.464616936781" y="1695.95637416067" isVisible="true" isUpstreamVisible="true" lacing="Disabled" isSelectedInput="True" IsFrozen="false" isPinned="true" index="257:Revision" />
    <PythonNodeModels.PythonNode guid="754ee687-693b-4b92-8dec-ad7824b22e50" type="PythonNodeModels.PythonNode" nickname="Python Script" x="767.673743833699" y="1459.09516427943" isVisible="true" isUpstreamVisible="true" lacing="Disabled" isSelectedInput="False" IsFrozen="false" isPinned="true" inputcount="1">
      <PortInfo index="0" default="False" />
      <Script># Copyright(c) 2015, Konrad K Sobon
# @arch_laboratory, http://archi-lab.net

import clr
# Import Element wrapper extension methods
clr.AddReference("RevitNodes")
import Revit
clr.ImportExtensions(Revit.Elements)

# Import DocumentManager and TransactionManager
clr.AddReference("RevitServices")
import RevitServices
from RevitServices.Persistence import DocumentManager
from RevitServices.Transactions import TransactionManager
doc = DocumentManager.Instance.CurrentDBDocument

# Import RevitAPI
clr.AddReference("RevitAPI")
import Autodesk
from Autodesk.Revit.DB import *

clr.AddReference("System")
from System.Collections.Generic import List

import sys
pyt_path = r'C:\Program Files (x86)\IronPython 2.7\Lib'
sys.path.append(pyt_path)


rev = IN[0]

for r in rev:
    id = ElementId(r)
    element = doc.GetElement(id)
    element_set = ElementSet()
    element_set.Insert(element)

element_collection = List[ElementId](element_set)
elements_to_hide = collector.WhereElementIsNotElementType().Excluding(element_collection).ToElements()

TransactionManager.Instance.EnsureInTransaction(doc)

#Revision.ReorderRevisionSequence(doc, revId)
#result = FilteredElementCollector(doc).OfCategory(BuiltInCategory.OST_Revisions).WhereElementIsNotElementType().ToElements()
#result = FilteredElementCollector(doc).OfCategory(BuiltInCategory.OST_Revisions).WhereElementIsNotElementType()
TransactionManager.Instance.TransactionTaskDone()

OUT = rev</Script>
    </PythonNodeModels.PythonNode>
    <Dynamo.Graph.Nodes.ZeroTouch.DSFunction guid="fe70b056-049f-42bf-83c6-e829502b7898" type="Dynamo.Graph.Nodes.ZeroTouch.DSFunction" nickname="Object.Type" x="1090.30165490252" y="164.364840416774" isVisible="true" isUpstreamVisible="true" lacing="Shortest" isSelectedInput="False" IsFrozen="false" isPinned="true" assembly="DSCoreNodes.dll" function="DSCore.Object.Type@var">
      <PortInfo index="0" default="False" />
    </Dynamo.Graph.Nodes.ZeroTouch.DSFunction>
    <PythonNodeModels.PythonNode guid="91f612d4-4a07-426b-a6e0-e16d054a7eeb" type="PythonNodeModels.PythonNode" nickname="Python Script" x="1526.50913167373" y="113.679762870536" isVisible="true" isUpstreamVisible="true" lacing="Disabled" isSelectedInput="False" IsFrozen="false" isPinned="true" inputcount="1">
      <PortInfo index="0" default="False" />
      <Script># Copyright(c) 2015, Konrad K Sobon
# @arch_laboratory, http://archi-lab.net

import clr
# Import Element wrapper extension methods
clr.AddReference("RevitNodes")
import Revit
clr.ImportExtensions(Revit.Elements)

# Import DocumentManager and TransactionManager
clr.AddReference("RevitServices")
import RevitServices
from RevitServices.Persistence import DocumentManager
doc = DocumentManager.Instance.CurrentDBDocument

# Import RevitAPI
clr.AddReference("RevitAPI")
import Autodesk
from Autodesk.Revit.DB import *

import sys
pyt_path = r'C:\Program Files (x86)\IronPython 2.7\Lib'
sys.path.append(pyt_path)

#The inputs to this node will be stored as a list in the IN variable.
dataEnteringNode = IN
rev = IN[0]

name = []

for r in rev:
	name.append(r.Name)

OUT = name</Script>
    </PythonNodeModels.PythonNode>
    <PythonNodeModels.PythonNode guid="2a0ae956-4b46-40e5-8ee0-493be0637160" type="PythonNodeModels.PythonNode" nickname="Python Script" x="1432.89745013418" y="1780.71022692534" isVisible="true" isUpstreamVisible="true" lacing="Disabled" isSelectedInput="False" IsFrozen="false" isPinned="true" inputcount="1">
      <PortInfo index="0" default="False" />
      <Script># Copyright(c) 2015, Konrad K Sobon
# @arch_laboratory, http://archi-lab.net

import clr
# Import Element wrapper extension methods
clr.AddReference("RevitNodes")
import Revit
clr.ImportExtensions(Revit.Elements)

# Import DocumentManager and TransactionManager
clr.AddReference("RevitServices")
import RevitServices
from RevitServices.Persistence import DocumentManager
from RevitServices.Transactions import TransactionManager
doc = DocumentManager.Instance.CurrentDBDocument

# Import RevitAPI
clr.AddReference("RevitAPI")
import Autodesk
from Autodesk.Revit.DB import *

clr.AddReference("System")
from System.Collections.Generic import List

import sys
pyt_path = r'C:\Program Files (x86)\IronPython 2.7\Lib'
sys.path.append(pyt_path)


rev = IN[0]

revId = []

for r in rev:
	revId.append(ElementId(r.Id))

revIds = List[ElementId](revId)

OUT = revIds</Script>
    </PythonNodeModels.PythonNode>
    <Dynamo.Graph.Nodes.ZeroTouch.DSFunction guid="4d219b0e-45a4-44b0-b2c2-8346afd2017e" type="Dynamo.Graph.Nodes.ZeroTouch.DSFunction" nickname="Object.Type" x="1453.96681190584" y="975.390533914926" isVisible="true" isUpstreamVisible="true" lacing="Shortest" isSelectedInput="False" IsFrozen="false" isPinned="true" assembly="DSCoreNodes.dll" function="DSCore.Object.Type@var">
      <PortInfo index="0" default="False" />
    </Dynamo.Graph.Nodes.ZeroTouch.DSFunction>
    <Dynamo.Nodes.DSModelElementSelection guid="c27b31e7-1167-44dc-ae34-1dbeadda4a24" type="Dynamo.Nodes.DSModelElementSelection" nickname="Select Model Element" x="1210.65948622077" y="1480.57138392401" isVisible="true" isUpstreamVisible="true" lacing="Disabled" isSelectedInput="True" IsFrozen="false" isPinned="true">
      <instance id="fdde7220-6ba6-4155-8302-43b5be8e4377-0021f23b" />
    </Dynamo.Nodes.DSModelElementSelection>
    <Dynamo.Graph.Nodes.ZeroTouch.DSFunction guid="88c5d8b9-7212-4a94-871c-a46183fc0553" type="Dynamo.Graph.Nodes.ZeroTouch.DSFunction" nickname="Object.Type" x="1762.48063819017" y="1414.63336002912" isVisible="true" isUpstreamVisible="true" lacing="Shortest" isSelectedInput="False" IsFrozen="false" isPinned="true" assembly="DSCoreNodes.dll" function="DSCore.Object.Type@var">
      <PortInfo index="0" default="False" />
    </Dynamo.Graph.Nodes.ZeroTouch.DSFunction>
    <PythonNodeModels.PythonNode guid="579259a9-0f1b-40f0-88fc-6718168d6721" type="PythonNodeModels.PythonNode" nickname="Python Script" x="1212.3387788722" y="2133.68039775382" isVisible="true" isUpstreamVisible="true" lacing="Disabled" isSelectedInput="False" IsFrozen="false" isPinned="true" inputcount="1">
      <PortInfo index="0" default="False" />
      <Script># Copyright(c) 2015, Konrad K Sobon
# @arch_laboratory, http://archi-lab.net

import clr
# Import Element wrapper extension methods
clr.AddReference("RevitNodes")
import Revit
clr.ImportExtensions(Revit.Elements)

# Import DocumentManager and TransactionManager
clr.AddReference("RevitServices")
import RevitServices
from RevitServices.Persistence import DocumentManager
from RevitServices.Transactions import TransactionManager
doc = DocumentManager.Instance.CurrentDBDocument

# Import RevitAPI
clr.AddReference("RevitAPI")
import Autodesk
from Autodesk.Revit.DB import *

clr.AddReference("System")
from System.Collections.Generic import List

import sys
pyt_path = r'C:\Program Files (x86)\IronPython 2.7\Lib'
sys.path.append(pyt_path)


rev = IN[0]
ids = []
for r in rev:
	ids.append(ElementId(r.Id))

OUT = ids</Script>
    </PythonNodeModels.PythonNode>
    <PythonNodeModels.PythonNode guid="9ce72629-e497-4300-998a-6823ad121e29" type="PythonNodeModels.PythonNode" nickname="Python Script" x="1391.21958002437" y="2134.09293739586" isVisible="true" isUpstreamVisible="true" lacing="Disabled" isSelectedInput="False" IsFrozen="false" isPinned="true" inputcount="1">
      <PortInfo index="0" default="False" />
      <Script># Copyright(c) 2015, Konrad K Sobon
# @arch_laboratory, http://archi-lab.net

import clr
# Import Element wrapper extension methods
clr.AddReference("RevitNodes")
import Revit
clr.ImportExtensions(Revit.Elements)

# Import DocumentManager and TransactionManager
clr.AddReference("RevitServices")
import RevitServices
from RevitServices.Persistence import DocumentManager
from RevitServices.Transactions import TransactionManager
doc = DocumentManager.Instance.CurrentDBDocument

# Import RevitAPI
clr.AddReference("RevitAPI")
import Autodesk
from Autodesk.Revit.DB import *

clr.AddReference("System")
from System.Collections.Generic import List

import sys
pyt_path = r'C:\Program Files (x86)\IronPython 2.7\Lib'
sys.path.append(pyt_path)


revId = IN[0]

TransactionManager.Instance.EnsureInTransaction(doc)

Revision.ReorderRevisionSequence(doc, revId)
result = FilteredElementCollector(doc).OfCategory(BuiltInCategory.OST_Revisions).WhereElementIsNotElementType().ToElements()

TransactionManager.Instance.TransactionTaskDone()

OUT = result</Script>
    </PythonNodeModels.PythonNode>
    <Dynamo.Nodes.DSModelElementSelection guid="5a1f5865-44f5-4014-8768-33747a4a7c49" type="Dynamo.Nodes.DSModelElementSelection" nickname="Select Model Element" x="1694.89292200879" y="1795.60800402687" isVisible="true" isUpstreamVisible="true" lacing="Disabled" isSelectedInput="True" IsFrozen="false" isPinned="false">
      <instance id="fdde7220-6ba6-4155-8302-43b5be8e4377-0021f23b" />
    </Dynamo.Nodes.DSModelElementSelection>
    <PythonNodeModels.PythonNode guid="7d2b99f4-3b49-44fc-96d9-3f885417e6c1" type="PythonNodeModels.PythonNode" nickname="Python Script" x="1970.40648918963" y="1795.04411775435" isVisible="true" isUpstreamVisible="true" lacing="Disabled" isSelectedInput="False" IsFrozen="false" isPinned="true" inputcount="1">
      <PortInfo index="0" default="False" />
      <Script># Copyright(c) 2015, Konrad K Sobon
# @arch_laboratory, http://archi-lab.net

import clr
# Import Element wrapper extension methods
clr.AddReference("RevitNodes")
import Revit
clr.ImportExtensions(Revit.Elements)

# Import DocumentManager and TransactionManager
clr.AddReference("RevitServices")
import RevitServices
from RevitServices.Persistence import DocumentManager
from RevitServices.Transactions import TransactionManager
doc = DocumentManager.Instance.CurrentDBDocument

# Import RevitAPI
clr.AddReference("RevitAPI")
import Autodesk
from Autodesk.Revit.DB import *

clr.AddReference("System")
from System.Collections.Generic import List

import sys
pyt_path = r'C:\Program Files (x86)\IronPython 2.7\Lib'
sys.path.append(pyt_path)


selElement = UnwrapElement(IN[0])

id = selElement.Id 

OUT = id</Script>
    </PythonNodeModels.PythonNode>
    <Dynamo.Graph.Nodes.ZeroTouch.DSFunction guid="ec4efc7d-e5b9-414a-af5b-adff32c3afbc" type="Dynamo.Graph.Nodes.ZeroTouch.DSFunction" nickname="Object.Type" x="2207.21676309365" y="1792.40802625447" isVisible="true" isUpstreamVisible="true" lacing="Shortest" isSelectedInput="False" IsFrozen="false" isPinned="true" assembly="DSCoreNodes.dll" function="DSCore.Object.Type@var">
      <PortInfo index="0" default="False" />
    </Dynamo.Graph.Nodes.ZeroTouch.DSFunction>
  </Elements>
  <Connectors>
    <Dynamo.Graph.Connectors.ConnectorModel start="a0f61656-3ffe-4b2e-ad3c-2d4e7ec09790" start_index="0" end="f1b1c1cb-fdd2-4196-8321-ba4f01bd919e" end_index="0" portType="0" />
    <Dynamo.Graph.Connectors.ConnectorModel start="a0f61656-3ffe-4b2e-ad3c-2d4e7ec09790" start_index="1" end="f1b1c1cb-fdd2-4196-8321-ba4f01bd919e" end_index="1" portType="0" />
    <Dynamo.Graph.Connectors.ConnectorModel start="a0f61656-3ffe-4b2e-ad3c-2d4e7ec09790" start_index="1" end="83f789f7-a4a9-408a-8bcd-8ccdb985a09e" end_index="0" portType="0" />
    <Dynamo.Graph.Connectors.ConnectorModel start="a0f61656-3ffe-4b2e-ad3c-2d4e7ec09790" start_index="1" end="eeb6e6c8-e45b-4973-b00b-69271e216a53" end_index="0" portType="0" />
    <Dynamo.Graph.Connectors.ConnectorModel start="83f789f7-a4a9-408a-8bcd-8ccdb985a09e" start_index="0" end="b8f3839c-d13d-4f9b-9fd9-9e5eb447c618" end_index="0" portType="0" />
    <Dynamo.Graph.Connectors.ConnectorModel start="83f789f7-a4a9-408a-8bcd-8ccdb985a09e" start_index="0" end="9c8db7b2-a302-4a7b-bc24-959c9c3f6a17" end_index="1" portType="0" />
    <Dynamo.Graph.Connectors.ConnectorModel start="93772bb6-88f5-41fa-a669-a92b6f995962" start_index="0" end="6040f7ef-dc5a-4f6d-bb52-c940264f037c" end_index="0" portType="0" />
    <Dynamo.Graph.Connectors.ConnectorModel start="9c8db7b2-a302-4a7b-bc24-959c9c3f6a17" start_index="0" end="fe70b056-049f-42bf-83c6-e829502b7898" end_index="0" portType="0" />
    <Dynamo.Graph.Connectors.ConnectorModel start="9c8db7b2-a302-4a7b-bc24-959c9c3f6a17" start_index="0" end="91f612d4-4a07-426b-a6e0-e16d054a7eeb" end_index="0" portType="0" />
    <Dynamo.Graph.Connectors.ConnectorModel start="a682794f-5f68-406d-947f-cddd8bdbf620" start_index="0" end="da98c98d-a9f7-4329-8cd7-219496fde318" end_index="0" portType="0" />
    <Dynamo.Graph.Connectors.ConnectorModel start="eeb6e6c8-e45b-4973-b00b-69271e216a53" start_index="0" end="68d44933-bbd0-4985-8cae-18b082136aa2" end_index="0" portType="0" />
    <Dynamo.Graph.Connectors.ConnectorModel start="e2e6c2b5-bb20-4c2b-8d46-4b4400bd956f" start_index="0" end="61bffa85-6f64-4236-9813-58f7bd48b190" end_index="0" portType="0" />
    <Dynamo.Graph.Connectors.ConnectorModel start="68d44933-bbd0-4985-8cae-18b082136aa2" start_index="0" end="e2e6c2b5-bb20-4c2b-8d46-4b4400bd956f" end_index="0" portType="0" />
    <Dynamo.Graph.Connectors.ConnectorModel start="68d44933-bbd0-4985-8cae-18b082136aa2" start_index="0" end="4d219b0e-45a4-44b0-b2c2-8346afd2017e" end_index="0" portType="0" />
    <Dynamo.Graph.Connectors.ConnectorModel start="b8f3839c-d13d-4f9b-9fd9-9e5eb447c618" start_index="0" end="93772bb6-88f5-41fa-a669-a92b6f995962" end_index="1" portType="0" />
    <Dynamo.Graph.Connectors.ConnectorModel start="b8f3839c-d13d-4f9b-9fd9-9e5eb447c618" start_index="0" end="fa0963ce-3b60-4a94-894e-ca5ed4e2b67d" end_index="0" portType="0" />
    <Dynamo.Graph.Connectors.ConnectorModel start="6a2609b5-1d59-4b53-91e2-640d6e9694fb" start_index="0" end="55b58cbb-1f79-46dd-90f5-a1e946a2ab2f" end_index="0" portType="0" />
    <Dynamo.Graph.Connectors.ConnectorModel start="6040f7ef-dc5a-4f6d-bb52-c940264f037c" start_index="0" end="ac337bee-446c-4dd1-b856-98e0823affa7" end_index="0" portType="0" />
    <Dynamo.Graph.Connectors.ConnectorModel start="6040f7ef-dc5a-4f6d-bb52-c940264f037c" start_index="0" end="d6d8bc7a-b942-4519-b756-e82c3ac2a8f4" end_index="0" portType="0" />
    <Dynamo.Graph.Connectors.ConnectorModel start="d6d8bc7a-b942-4519-b756-e82c3ac2a8f4" start_index="0" end="55b58cbb-1f79-46dd-90f5-a1e946a2ab2f" end_index="1" portType="0" />
    <Dynamo.Graph.Connectors.ConnectorModel start="55b58cbb-1f79-46dd-90f5-a1e946a2ab2f" start_index="0" end="7b10c236-4f31-49eb-acd8-06709b2281f8" end_index="0" portType="0" />
    <Dynamo.Graph.Connectors.ConnectorModel start="7b10c236-4f31-49eb-acd8-06709b2281f8" start_index="0" end="d12ab54b-edf1-412a-91f4-38a014cb70c1" end_index="0" portType="0" />
    <Dynamo.Graph.Connectors.ConnectorModel start="7b8ca3f0-af54-4187-a14c-9d3cdab73610" start_index="0" end="754ee687-693b-4b92-8dec-ad7824b22e50" end_index="0" portType="0" />
    <Dynamo.Graph.Connectors.ConnectorModel start="7b8ca3f0-af54-4187-a14c-9d3cdab73610" start_index="0" end="4262e6c8-f1eb-4b58-ad75-e3f5d1cabd6b" end_index="0" portType="0" />
    <Dynamo.Graph.Connectors.ConnectorModel start="4262e6c8-f1eb-4b58-ad75-e3f5d1cabd6b" start_index="0" end="011cdd87-38bc-4b00-9176-be24e87aa677" end_index="0" portType="0" />
    <Dynamo.Graph.Connectors.ConnectorModel start="846b9553-a648-4f08-aacf-eec882571746" start_index="0" end="579259a9-0f1b-40f0-88fc-6718168d6721" end_index="0" portType="0" />
    <Dynamo.Graph.Connectors.ConnectorModel start="846b9553-a648-4f08-aacf-eec882571746" start_index="0" end="2a0ae956-4b46-40e5-8ee0-493be0637160" end_index="0" portType="0" />
    <Dynamo.Graph.Connectors.ConnectorModel start="80e9d16c-40d1-41a6-90c4-41673239c33e" start_index="0" end="cb9ffcb1-85b0-4ded-aca9-759192ca19a7" end_index="0" portType="0" />
    <Dynamo.Graph.Connectors.ConnectorModel start="46269eaf-3fbb-40c5-a8bc-0301333258f9" start_index="0" end="846b9553-a648-4f08-aacf-eec882571746" end_index="0" portType="0" />
    <Dynamo.Graph.Connectors.ConnectorModel start="46269eaf-3fbb-40c5-a8bc-0301333258f9" start_index="0" end="1d358929-9105-4134-b15e-d3b9d4e7043f" end_index="0" portType="0" />
    <Dynamo.Graph.Connectors.ConnectorModel start="94ebf93f-e5f6-4744-973c-7be07b46d78d" start_index="0" end="46269eaf-3fbb-40c5-a8bc-0301333258f9" end_index="0" portType="0" />
    <Dynamo.Graph.Connectors.ConnectorModel start="2a0ae956-4b46-40e5-8ee0-493be0637160" start_index="0" end="88c5d8b9-7212-4a94-871c-a46183fc0553" end_index="0" portType="0" />
    <Dynamo.Graph.Connectors.ConnectorModel start="579259a9-0f1b-40f0-88fc-6718168d6721" start_index="0" end="9ce72629-e497-4300-998a-6823ad121e29" end_index="0" portType="0" />
    <Dynamo.Graph.Connectors.ConnectorModel start="5a1f5865-44f5-4014-8768-33747a4a7c49" start_index="0" end="7d2b99f4-3b49-44fc-96d9-3f885417e6c1" end_index="0" portType="0" />
    <Dynamo.Graph.Connectors.ConnectorModel start="7d2b99f4-3b49-44fc-96d9-3f885417e6c1" start_index="0" end="ec4efc7d-e5b9-414a-af5b-adff32c3afbc" end_index="0" portType="0" />
  </Connectors>
  <Notes />
  <Annotations>
    <Dynamo.Graph.Annotations.AnnotationModel guid="c014f40d-375f-485c-9cfd-b42b2178c914" annotationText="archi-lab" left="-18.839889087291" top="211.602397480681" width="151" height="217" fontSize="30" InitialTop="257.602397480681" InitialHeight="201" TextblockHeight="36" backgrouund="#FFC1D676">
      <Models ModelGuid="a0f61656-3ffe-4b2e-ad3c-2d4e7ec09790" />
    </Dynamo.Graph.Annotations.AnnotationModel>
    <Dynamo.Graph.Annotations.AnnotationModel guid="2b7cedc3-9159-4883-ab9e-542665b3536d" annotationText="Reorder sequence" left="492.287359809317" top="1041.29318168022" width="760.033905295533" height="171.0445437485" fontSize="30" InitialTop="1087.29318168022" InitialHeight="124.887428151597" TextblockHeight="36" backgrouund="#FFC1D676">
      <Models ModelGuid="eeb6e6c8-e45b-4973-b00b-69271e216a53" />
      <Models ModelGuid="e2e6c2b5-bb20-4c2b-8d46-4b4400bd956f" />
      <Models ModelGuid="61bffa85-6f64-4236-9813-58f7bd48b190" />
    </Dynamo.Graph.Annotations.AnnotationModel>
    <Dynamo.Graph.Annotations.AnnotationModel guid="8b8d1a40-b8ae-4c46-ab44-f217b2769a56" annotationText="Reorder sequence" left="384.339943303795" top="1300.98671728836" width="1021.41694825854" height="144.15854841671" fontSize="30" InitialTop="1346.98671728836" InitialHeight="130.32630766726" TextblockHeight="36" backgrouund="#FFC1D676">
      <Models ModelGuid="7b8ca3f0-af54-4187-a14c-9d3cdab73610" />
      <Models ModelGuid="4262e6c8-f1eb-4b58-ad75-e3f5d1cabd6b" />
      <Models ModelGuid="011cdd87-38bc-4b00-9176-be24e87aa677" />
    </Dynamo.Graph.Annotations.AnnotationModel>
    <Dynamo.Graph.Annotations.AnnotationModel guid="3e97f780-5d0d-4e7a-96cd-f4d0f7e4ee93" annotationText="Select revision in linked file" left="271.665299297148" top="445.076032806014" width="144" height="211" fontSize="30" InitialTop="563.076032806014" InitialHeight="123" TextblockHeight="108" backgrouund="#FFC1D676">
      <Models ModelGuid="83f789f7-a4a9-408a-8bcd-8ccdb985a09e" />
    </Dynamo.Graph.Annotations.AnnotationModel>
    <Dynamo.Graph.Annotations.AnnotationModel guid="193e8ef0-0514-460c-bdb8-9976772dcd39" annotationText="copy revision in current doc and change order" left="852.711999852056" top="335.578285444944" width="144" height="345" fontSize="30" InitialTop="561.578285444944" InitialHeight="149" TextblockHeight="216" backgrouund="#FFC1D676">
      <Models ModelGuid="93772bb6-88f5-41fa-a669-a92b6f995962" />
    </Dynamo.Graph.Annotations.AnnotationModel>
    <Dynamo.Graph.Annotations.AnnotationModel guid="b4b83892-6591-476f-88eb-00774a341913" annotationText="copy revision" left="664.230976825348" top="209.420942490982" width="144" height="201" fontSize="30" InitialTop="291.420942490982" InitialHeight="149" TextblockHeight="72" backgrouund="#FFC1D676">
      <Models ModelGuid="9c8db7b2-a302-4a7b-bc24-959c9c3f6a17" />
    </Dynamo.Graph.Annotations.AnnotationModel>
    <Dynamo.Graph.Annotations.AnnotationModel guid="80455df9-0ed4-482a-a60d-7398da086e52" annotationText="get element name" left="707.062855859856" top="714.934340403206" width="144" height="211" fontSize="30" InitialTop="832.934340403206" InitialHeight="123" TextblockHeight="108" backgrouund="#FFC1D676">
      <Models ModelGuid="fa0963ce-3b60-4a94-894e-ca5ed4e2b67d" />
    </Dynamo.Graph.Annotations.AnnotationModel>
    <Dynamo.Graph.Annotations.AnnotationModel guid="e98a8062-1de7-42e0-b47a-40cc78460739" annotationText="get element name" left="1516.50913167373" top="-4.320237129464" width="144" height="211" fontSize="30" InitialTop="113.679762870536" InitialHeight="123" TextblockHeight="108" backgrouund="#FFC1D676">
      <Models ModelGuid="91f612d4-4a07-426b-a6e0-e16d054a7eeb" />
    </Dynamo.Graph.Annotations.AnnotationModel>
  </Annotations>
  <Presets />
  <Cameras>
    <Camera Name="Background Preview" eyeX="-17" eyeY="24" eyeZ="50" lookX="12" lookY="-13" lookZ="-58" upX="0" upY="1" upZ="0" />
  </Cameras>
</Workspace>