<Workspace Version="1.3.3.4651" X="-71.7574078626039" Y="79.6549274532315" zoom="0.779970979395824" ScaleFactor="1" Name="Home" Description="" RunType="Manual" RunPeriod="1000" HasRunWithoutCrash="False">
  <NamespaceResolutionMap />
  <Elements>
    <CoreNodeModels.Input.Filename guid="307f3971-fc36-4c1a-9f3d-75264ba2c1e8" type="CoreNodeModels.Input.Filename" nickname="File Path" x="-79.3618698814469" y="318.907775018613" isVisible="true" isUpstreamVisible="true" lacing="Disabled" isSelectedInput="True" IsFrozen="false" isPinned="false">
      <System.String>\\global.arup.com\australasia\MEL\Projects\261000\261184-00 Shipwreck Coast Master\Work\Internal\BIM_CDE\01_WORKING\10_STR\00_MODEL\261184-ARP-M3-S_R18-ASL.rvt</System.String>
      <HintPath>\\global.arup.com\australasia\MEL\Projects\261000\261184-00 Shipwreck Coast Master\Work\Internal\BIM_CDE\01_WORKING\10_STR\00_MODEL\261184-ARP-M3-S_R18-ASL.rvt</HintPath>
    </CoreNodeModels.Input.Filename>
    <PythonNodeModels.PythonNode guid="9ff0275a-8d13-4a2d-826f-8b71030548a8" type="PythonNodeModels.PythonNode" nickname="Python Script" x="1295.66346405728" y="362.680402848789" isVisible="true" isUpstreamVisible="true" lacing="Disabled" isSelectedInput="False" IsFrozen="false" isPinned="true" inputcount="1">
      <PortInfo index="0" default="False" />
      <Script>#Copyright(c) 2017, john pierson
# @60secondrevit, http://sixtysecondrevit.com
import clr
clr.AddReference('ProtoGeometry')
from Autodesk.DesignScript.Geometry import *

# Import Element wrapper extension methods
clr.AddReference("RevitNodes")
import Revit
clr.ImportExtensions(Revit.Elements)

# Import geometry conversion extension methods
clr.ImportExtensions(Revit.GeometryConversion)

# Import DocumentManager and TransactionManager
clr.AddReference("RevitServices")
import RevitServices
from RevitServices.Persistence import DocumentManager
from RevitServices.Transactions import TransactionManager

doc = DocumentManager.Instance.CurrentDBDocument
uiapp = DocumentManager.Instance.CurrentUIApplication
app = uiapp.Application

# Import RevitAPI
clr.AddReference("RevitAPI")
import Autodesk
from Autodesk.Revit.DB import *

doc = IN[0]

collector = []

for d in doc:
	collector.append(FilteredElementCollector(d).OfCategory(BuiltInCategory.OST_ProjectBasePoint).ToElements()[0])
		
OUT = collector</Script>
    </PythonNodeModels.PythonNode>
    <CoreNodeModels.Input.Filename guid="4315c2bf-05d2-4574-9bb2-e125b79da26f" type="CoreNodeModels.Input.Filename" nickname="File Path" x="-79.4309361892132" y="439.562448473741" isVisible="true" isUpstreamVisible="true" lacing="Disabled" isSelectedInput="True" IsFrozen="false" isPinned="false">
      <System.String>\\global.arup.com\australasia\MEL\Projects\261000\261184-00 Shipwreck Coast Master\Work\Internal\BIM_CDE\01_WORKING\10_STR\00_MODEL\261184-ARP-M3-S_R18-LAB.rvt</System.String>
      <HintPath>\\global.arup.com\australasia\MEL\Projects\261000\261184-00 Shipwreck Coast Master\Work\Internal\BIM_CDE\01_WORKING\10_STR\00_MODEL\261184-ARP-M3-S_R18-LAB.rvt</HintPath>
    </CoreNodeModels.Input.Filename>
    <CoreNodeModels.CreateList guid="08243eb6-fa76-46a0-aaa3-e9353677ed0c" type="CoreNodeModels.CreateList" nickname="List.Create" x="511.184033013638" y="438.304300453783" isVisible="true" isUpstreamVisible="true" lacing="Disabled" isSelectedInput="False" IsFrozen="false" isPinned="false" inputcount="2">
      <PortInfo index="0" default="False" />
      <PortInfo index="1" default="False" />
    </CoreNodeModels.CreateList>
    <Dynamo.Graph.Nodes.ZeroTouch.DSFunction guid="3277b5a3-699d-4593-9145-d62a5f58db12" type="Dynamo.Graph.Nodes.ZeroTouch.DSFunction" nickname="Element.Parameters" x="1563.32002837437" y="22.8798387915015" isVisible="true" isUpstreamVisible="true" lacing="Shortest" isSelectedInput="False" IsFrozen="false" isPinned="true" assembly="RevitNodes.dll" function="Revit.Elements.Element.Parameters">
      <PortInfo index="0" default="False" />
    </Dynamo.Graph.Nodes.ZeroTouch.DSFunction>
    <Dynamo.Graph.Nodes.ZeroTouch.DSFunction guid="96ea7cf1-7d11-4da5-93c1-8838e77e94ce" type="Dynamo.Graph.Nodes.ZeroTouch.DSFunction" nickname="Element.GetParameterValueByName" x="1644.61049051946" y="426.570474549325" isVisible="true" isUpstreamVisible="true" lacing="CrossProduct" isSelectedInput="False" IsFrozen="false" isPinned="true" assembly="RevitNodes.dll" function="Revit.Elements.Element.GetParameterValueByName@string">
      <PortInfo index="0" default="False" />
      <PortInfo index="1" default="False" />
    </Dynamo.Graph.Nodes.ZeroTouch.DSFunction>
    <Dynamo.Graph.Nodes.CodeBlockNodeModel guid="6e572094-5455-4898-ad2c-a1a7ae4484f0" type="Dynamo.Graph.Nodes.CodeBlockNodeModel" nickname="Code Block" x="1188.81872537296" y="610.833652173682" isVisible="true" isUpstreamVisible="true" lacing="Disabled" isSelectedInput="False" IsFrozen="false" isPinned="false" CodeText="{&quot;E/W&quot;,&quot;N/S&quot;, &quot;Angle to True North&quot;};" ShouldFocus="false" />
    <PythonNodeModels.PythonNode guid="3e9d0d0b-cc51-483f-b204-5f7400d9c4c4" type="PythonNodeModels.PythonNode" nickname="Python Script" x="1286.20402481579" y="819.315522799015" isVisible="true" isUpstreamVisible="true" lacing="Disabled" isSelectedInput="False" IsFrozen="false" isPinned="true" inputcount="1">
      <PortInfo index="0" default="False" />
      <Script>#Copyright(c) 2017, john pierson
# @60secondrevit, http://sixtysecondrevit.com
import clr
clr.AddReference('ProtoGeometry')
from Autodesk.DesignScript.Geometry import *

# Import Element wrapper extension methods
clr.AddReference("RevitNodes")
import Revit
clr.ImportExtensions(Revit.Elements)

# Import geometry conversion extension methods
clr.ImportExtensions(Revit.GeometryConversion)

# Import DocumentManager and TransactionManager
clr.AddReference("RevitServices")
import RevitServices
from RevitServices.Persistence import DocumentManager
from RevitServices.Transactions import TransactionManager

doc = DocumentManager.Instance.CurrentDBDocument
uiapp = DocumentManager.Instance.CurrentUIApplication
app = uiapp.Application

# Import RevitAPI
clr.AddReference("RevitAPI")
import Autodesk
from Autodesk.Revit.DB import *

doc = IN[0]

collector = []

for d in doc:
	collector.append(FilteredElementCollector(d).OfCategory(BuiltInCategory.OST_SharedBasePoint).ToElements()[0])
		
OUT = collector</Script>
    </PythonNodeModels.PythonNode>
    <Dynamo.Graph.Nodes.ZeroTouch.DSFunction guid="3e074835-ff22-4497-a067-8046a47aa61d" type="Dynamo.Graph.Nodes.ZeroTouch.DSFunction" nickname="Element.GetParameterValueByName" x="1640.68611553472" y="779.102454954353" isVisible="true" isUpstreamVisible="true" lacing="CrossProduct" isSelectedInput="False" IsFrozen="false" isPinned="true" assembly="RevitNodes.dll" function="Revit.Elements.Element.GetParameterValueByName@string">
      <PortInfo index="0" default="False" />
      <PortInfo index="1" default="False" />
    </Dynamo.Graph.Nodes.ZeroTouch.DSFunction>
    <Dynamo.Graph.Nodes.ZeroTouch.DSFunction guid="3bba9002-6f4a-4f23-b90c-34a5624bd542" type="Dynamo.Graph.Nodes.ZeroTouch.DSFunction" nickname="Element.Parameters" x="1632.48628668291" y="1072.62637026718" isVisible="true" isUpstreamVisible="true" lacing="Shortest" isSelectedInput="False" IsFrozen="false" isPinned="true" assembly="RevitNodes.dll" function="Revit.Elements.Element.Parameters">
      <PortInfo index="0" default="False" />
    </Dynamo.Graph.Nodes.ZeroTouch.DSFunction>
    <Dynamo.Graph.Nodes.CustomNodes.Function guid="b4501c4c-2b80-4228-bc84-ef616fc5e2d2" type="Dynamo.Graph.Nodes.CustomNodes.Function" nickname="Document.Close" x="1209.81985347327" y="25.2648218298905" isVisible="true" isUpstreamVisible="true" lacing="Shortest" isSelectedInput="False" IsFrozen="false" isPinned="true">
      <PortInfo index="0" default="False" />
      <PortInfo index="1" default="True" />
      <ID value="45102b65-7926-4e74-a0ec-49b7db7a2c6f" />
      <Name value="Document.Close" />
      <Description value="Close current Revit document. Use boolean switch (true / false) to save / discard any changes." />
      <Inputs>
        <Input value="Document" />
        <Input value="Save" />
      </Inputs>
      <Outputs>
        <Output value="Saved" />
      </Outputs>
    </Dynamo.Graph.Nodes.CustomNodes.Function>
    <Dynamo.Graph.Nodes.CustomNodes.Function guid="5573014a-1a0b-4a38-a77b-28d4e3a33c98" type="Dynamo.Graph.Nodes.CustomNodes.Function" nickname="Document.Open" x="771.66697625091" y="226.457469534036" isVisible="true" isUpstreamVisible="true" lacing="Shortest" isSelectedInput="False" IsFrozen="false" isPinned="false">
      <PortInfo index="0" default="False" />
      <ID value="74091d53-f02e-4dc9-a949-4c69db563ecc" />
      <Name value="Document.Open" />
      <Description value="Open document from the input File Path" />
      <Inputs>
        <Input value="FilePath" />
      </Inputs>
      <Outputs>
        <Output value="Document" />
      </Outputs>
    </Dynamo.Graph.Nodes.CustomNodes.Function>
    <Dynamo.Graph.Nodes.ZeroTouch.DSFunction guid="43f3ad05-e55d-4b10-966a-2d3fcf2da02a" type="Dynamo.Graph.Nodes.ZeroTouch.DSFunction" nickname="Application.OpenDocumentFile" x="756" y="422" isVisible="true" isUpstreamVisible="true" lacing="Shortest" isSelectedInput="False" IsFrozen="false" isPinned="true" assembly="..\AppData\Roaming\Dynamo\Dynamo Revit\1.3\packages\Rhythm\bin\Rhythm.dll" function="Rhythm.Revit.Application.Application.OpenDocumentFile@string,bool,bool">
      <PortInfo index="0" default="False" />
      <PortInfo index="1" default="True" />
      <PortInfo index="2" default="True" />
    </Dynamo.Graph.Nodes.ZeroTouch.DSFunction>
  </Elements>
  <Connectors>
    <Dynamo.Graph.Connectors.ConnectorModel start="307f3971-fc36-4c1a-9f3d-75264ba2c1e8" start_index="0" end="08243eb6-fa76-46a0-aaa3-e9353677ed0c" end_index="0" portType="0" />
    <Dynamo.Graph.Connectors.ConnectorModel start="9ff0275a-8d13-4a2d-826f-8b71030548a8" start_index="0" end="3277b5a3-699d-4593-9145-d62a5f58db12" end_index="0" portType="0" />
    <Dynamo.Graph.Connectors.ConnectorModel start="9ff0275a-8d13-4a2d-826f-8b71030548a8" start_index="0" end="96ea7cf1-7d11-4da5-93c1-8838e77e94ce" end_index="0" portType="0" />
    <Dynamo.Graph.Connectors.ConnectorModel start="4315c2bf-05d2-4574-9bb2-e125b79da26f" start_index="0" end="08243eb6-fa76-46a0-aaa3-e9353677ed0c" end_index="1" portType="0" />
    <Dynamo.Graph.Connectors.ConnectorModel start="6e572094-5455-4898-ad2c-a1a7ae4484f0" start_index="0" end="96ea7cf1-7d11-4da5-93c1-8838e77e94ce" end_index="1" portType="0" />
    <Dynamo.Graph.Connectors.ConnectorModel start="6e572094-5455-4898-ad2c-a1a7ae4484f0" start_index="0" end="3e074835-ff22-4497-a067-8046a47aa61d" end_index="1" portType="0" />
    <Dynamo.Graph.Connectors.ConnectorModel start="3e9d0d0b-cc51-483f-b204-5f7400d9c4c4" start_index="0" end="3e074835-ff22-4497-a067-8046a47aa61d" end_index="0" portType="0" />
    <Dynamo.Graph.Connectors.ConnectorModel start="3e9d0d0b-cc51-483f-b204-5f7400d9c4c4" start_index="0" end="3bba9002-6f4a-4f23-b90c-34a5624bd542" end_index="0" portType="0" />
    <Dynamo.Graph.Connectors.ConnectorModel start="43f3ad05-e55d-4b10-966a-2d3fcf2da02a" start_index="0" end="b4501c4c-2b80-4228-bc84-ef616fc5e2d2" end_index="0" portType="0" />
    <Dynamo.Graph.Connectors.ConnectorModel start="43f3ad05-e55d-4b10-966a-2d3fcf2da02a" start_index="0" end="3e9d0d0b-cc51-483f-b204-5f7400d9c4c4" end_index="0" portType="0" />
    <Dynamo.Graph.Connectors.ConnectorModel start="43f3ad05-e55d-4b10-966a-2d3fcf2da02a" start_index="0" end="9ff0275a-8d13-4a2d-826f-8b71030548a8" end_index="0" portType="0" />
  </Connectors>
  <Notes />
  <Annotations>
    <Dynamo.Graph.Annotations.AnnotationModel guid="4ac2f6ec-297d-4388-a2fa-6b9d4fba15a5" annotationText="base points" left="1285.66346405728" top="280.680402848789" width="144" height="175" fontSize="30" InitialTop="362.680402848789" InitialHeight="123" TextblockHeight="72" backgrouund="#FFC1D676">
      <Models ModelGuid="9ff0275a-8d13-4a2d-826f-8b71030548a8" />
    </Dynamo.Graph.Annotations.AnnotationModel>
    <Dynamo.Graph.Annotations.AnnotationModel guid="2ee3c4b8-94f6-458a-b1a9-1cbe9aee6ba2" annotationText="survey points" left="1276.20402481579" top="737.315522799015" width="144" height="175" fontSize="30" InitialTop="819.315522799015" InitialHeight="123" TextblockHeight="72" backgrouund="#FFC1D676">
      <Models ModelGuid="3e9d0d0b-cc51-483f-b204-5f7400d9c4c4" />
    </Dynamo.Graph.Annotations.AnnotationModel>
    <Dynamo.Graph.Annotations.AnnotationModel guid="4c189499-fe81-4131-b4b0-80e856431472" annotationText="from Rhythm package" left="746" top="376" width="319" height="191" fontSize="30" InitialTop="422" InitialHeight="175" TextblockHeight="36" backgrouund="#FFC1D676">
      <Models ModelGuid="43f3ad05-e55d-4b10-966a-2d3fcf2da02a" />
    </Dynamo.Graph.Annotations.AnnotationModel>
  </Annotations>
  <Presets />
  <Cameras>
    <Camera Name="Background Preview" eyeX="-17" eyeY="24" eyeZ="50" lookX="12" lookY="-13" lookZ="-58" upX="0" upY="1" upZ="0" />
  </Cameras>
</Workspace>