<Workspace Version="1.3.2.2480" X="136.891738356481" Y="-438.385521266032" zoom="1.40972876398001" ScaleFactor="1" Name="Home" Description="" RunType="Manual" RunPeriod="1000" HasRunWithoutCrash="True">
  <NamespaceResolutionMap />
  <Elements>
    <Dynamo.Graph.Nodes.ZeroTouch.DSFunction guid="738afc40-549e-4976-b180-00a0c8394f2d" type="Dynamo.Graph.Nodes.ZeroTouch.DSFunction" nickname="FamilyInstance.Room" x="372.251494866189" y="362.325149486619" isVisible="true" isUpstreamVisible="true" lacing="Shortest" isSelectedInput="False" IsFrozen="false" isPinned="true" assembly="..\AppData\Roaming\Dynamo\Dynamo Revit\1.3\packages\Rhythm\bin\Rhythm.dll" function="Rhythm.Revit.Elements.FamilyInstance.Room@Revit.Elements.Element[]">
      <PortInfo index="0" default="False" />
    </Dynamo.Graph.Nodes.ZeroTouch.DSFunction>
    <Dynamo.Nodes.DSModelElementSelection guid="38f87f5b-9197-4f37-b978-2760aac144f9" type="Dynamo.Nodes.DSModelElementSelection" nickname="Select Model Element" x="81.2169890653979" y="362.960851180362" isVisible="true" isUpstreamVisible="true" lacing="Disabled" isSelectedInput="True" IsFrozen="false" isPinned="false">
      <instance id="09bbf030-56f1-4335-8b29-3e46bbbb2850-00000c33" />
    </Dynamo.Nodes.DSModelElementSelection>
    <PythonNodeModels.PythonNode guid="d0dffef4-4d42-4afb-9b0f-4162228de08b" type="PythonNodeModels.PythonNode" nickname="Python Script" x="296.241540605542" y="643.118114681869" isVisible="true" isUpstreamVisible="true" lacing="Disabled" isSelectedInput="False" IsFrozen="false" isPinned="true" inputcount="1">
      <PortInfo index="0" default="False" />
      <Script>import clr
clr.AddReference('ProtoGeometry')
from Autodesk.DesignScript.Geometry import *

clr.AddReference('RevitAPI')
from Autodesk.Revit.DB import *
# Import DocumentManager and TransactionManager
clr.AddReference("RevitServices")
import RevitServices
from RevitServices.Persistence import DocumentManager


doc = DocumentManager.Instance.CurrentDBDocument


fi = IN[0]

fi_r = UnwrapElement(fi)

phase = doc.Phases

#Assign your output to the OUT variable.
OUT = fi_r.Room, phase.get_Item(1).Name</Script>
    </PythonNodeModels.PythonNode>
    <Dynamo.Graph.Nodes.CustomNodes.Function guid="100d8873-5e51-4cfe-a383-85779e562ca3" type="Dynamo.Graph.Nodes.CustomNodes.Function" nickname="Elements in Room" x="675.682483264606" y="468.749173356766" isVisible="true" isUpstreamVisible="true" lacing="Shortest" isSelectedInput="False" IsFrozen="false" isPinned="false">
      <PortInfo index="0" default="False" />
      <PortInfo index="1" default="False" />
      <ID value="29b30d46-9dd4-42d2-adf3-eda1ad145f62" />
      <Name value="Elements in Room" />
      <Description value="This node will check if any of the elements are inside any of the supplied rooms. " />
      <Inputs>
        <Input value="Elements" />
        <Input value="Rooms" />
      </Inputs>
      <Outputs>
        <Output value="Elements" />
      </Outputs>
    </Dynamo.Graph.Nodes.CustomNodes.Function>
    <PythonNodeModels.PythonNode guid="3a7c4ecd-2990-4bf4-acfb-57a3460d546a" type="PythonNodeModels.PythonNode" nickname="Python Script" x="730.546113347908" y="585.946253900867" isVisible="true" isUpstreamVisible="true" lacing="Disabled" isSelectedInput="False" IsFrozen="false" isPinned="false" inputcount="2">
      <PortInfo index="0" default="False" />
      <PortInfo index="1" default="False" />
      <Script>#Copyright(c) 2015, Konrad Sobon
# @arch_laboratory, http://archi-lab.net

# This code is based on Family.InRoom node originally created
# by Peter Kompolschek and published on Dynamo blog. Big thanks 
# to Peter for sharing his work so graciously.

import clr
import sys
clr.AddReference('ProtoGeometry')
from Autodesk.DesignScript.Geometry import *

pyt_path = r'C:\Program Files (x86)\IronPython 2.7\Lib'
sys.path.append(pyt_path)

# Import ToDSType(bool) extension method
clr.AddReference("RevitNodes")
import Revit
clr.ImportExtensions(Revit.Elements)

# Import DocumentManager and TransactionManager
clr.AddReference("RevitServices")
import RevitServices
from RevitServices.Persistence import DocumentManager
from RevitServices.Transactions import TransactionManager

# Import RevitAPI
clr.AddReference("RevitAPI")
import Autodesk
from Autodesk.Revit.DB import *

doc = DocumentManager.Instance.CurrentDBDocument
uiapp = DocumentManager.Instance.CurrentUIApplication
app = uiapp.Application

#The inputs to this node will be stored as a list in the IN variable.
dataEnteringNode = IN

def TryGetRoom(room, phase):
	try:
		inRoom = room.Room[phase]
	except:
		inRoom = None
		pass
	return inRoom

def FamiliesInRoom(_room, _families, _doc):
	outList = []
	for family in _families:
		pt = family.Location.Point
		if _room.IsPointInRoom(pt):
			outList.append(family)
		else:
			for phase in _doc.Phases:
				inRoom = TryGetRoom(family, phase)
				if inRoom != None and inRoom.ToDSType(True).Name == _room.ToDSType(True).Name:
					outList.append(family)
	return outList

try:
	errorReport = None
	families = []
	for i in IN[0]:
		families.append(UnwrapElement(i))
	
	rooms = []
	for i in IN[1]:
		if UnwrapElement(i).Area &gt; 0:
			rooms.append(UnwrapElement(i))
	
	outData = [[] for i in range(len(rooms))]
	for index, room in enumerate(rooms):
		outData[index].extend(FamiliesInRoom(room, families, doc))
except:
	# if error accurs anywhere in the process catch it
	import traceback
	errorReport = traceback.format_exc()

#Assign your output to the OUT variable
if errorReport == None:
	OUT = outData
else:
	OUT = errorReport</Script>
    </PythonNodeModels.PythonNode>
  </Elements>
  <Connectors>
    <Dynamo.Graph.Connectors.ConnectorModel start="38f87f5b-9197-4f37-b978-2760aac144f9" start_index="0" end="738afc40-549e-4976-b180-00a0c8394f2d" end_index="0" portType="0" />
    <Dynamo.Graph.Connectors.ConnectorModel start="38f87f5b-9197-4f37-b978-2760aac144f9" start_index="0" end="d0dffef4-4d42-4afb-9b0f-4162228de08b" end_index="0" portType="0" />
  </Connectors>
  <Notes />
  <Annotations>
    <Dynamo.Graph.Annotations.AnnotationModel guid="8feda039-7202-4719-bc2f-01f827c9d7af" annotationText="konrad archilab 2018.0.9" left="665.682483264606" top="386.749173356766" width="251" height="318.197080544101" fontSize="30" InitialTop="468.749173356766" InitialHeight="266.197080544101" TextblockHeight="72" backgrouund="#FFC1D676">
      <Models ModelGuid="100d8873-5e51-4cfe-a383-85779e562ca3" />
      <Models ModelGuid="3a7c4ecd-2990-4bf4-acfb-57a3460d546a" />
    </Dynamo.Graph.Annotations.AnnotationModel>
  </Annotations>
  <Presets />
  <Cameras>
    <Camera Name="Background Preview" eyeX="-17" eyeY="24" eyeZ="50" lookX="12" lookY="-13" lookZ="-58" upX="0" upY="1" upZ="0" />
  </Cameras>
</Workspace>