<Workspace Version="1.3.3.4651" X="-854" Y="-19" zoom="1" ScaleFactor="1" Name="Home" Description="" RunType="Manual" RunPeriod="1000" HasRunWithoutCrash="False">
  <NamespaceResolutionMap />
  <Elements>
    <Dynamo.Nodes.DSModelElementSelection guid="9303f847-b510-4dc3-a374-289d7192aa2c" type="Dynamo.Nodes.DSModelElementSelection" nickname="Select Model Element" x="608" y="596" isVisible="true" isUpstreamVisible="true" lacing="Disabled" isSelectedInput="True" IsFrozen="false" isPinned="false" />
    <Dynamo.Graph.Nodes.ZeroTouch.DSFunction guid="967a20a5-8e22-4476-8d3a-3edfbc5de3bd" type="Dynamo.Graph.Nodes.ZeroTouch.DSFunction" nickname="Element.Geometry" x="949" y="534" isVisible="true" isUpstreamVisible="true" lacing="Shortest" isSelectedInput="False" IsFrozen="false" isPinned="false" assembly="RevitNodes.dll" function="Revit.Elements.Element.Geometry">
      <PortInfo index="0" default="False" />
    </Dynamo.Graph.Nodes.ZeroTouch.DSFunction>
    <Dynamo.Graph.Nodes.ZeroTouch.DSFunction guid="4a461e2b-271e-4ca3-affa-eea69892055d" type="Dynamo.Graph.Nodes.ZeroTouch.DSFunction" nickname="PolyCurve.Curves" x="1459" y="502" isVisible="true" isUpstreamVisible="true" lacing="Shortest" isSelectedInput="False" IsFrozen="false" isPinned="false" assembly="ProtoGeometry.dll" function="Autodesk.DesignScript.Geometry.PolyCurve.Curves">
      <PortInfo index="0" default="False" />
    </Dynamo.Graph.Nodes.ZeroTouch.DSFunction>
    <Dynamo.Graph.Nodes.ZeroTouch.DSFunction guid="4d2bb49a-32f6-4e3d-b480-b65f69363663" type="Dynamo.Graph.Nodes.ZeroTouch.DSFunction" nickname="Curve.PlaneAtParameter" x="1501" y="656" isVisible="true" isUpstreamVisible="true" lacing="Shortest" isSelectedInput="False" IsFrozen="false" isPinned="false" assembly="ProtoGeometry.dll" function="Autodesk.DesignScript.Geometry.Curve.PlaneAtParameter@double">
      <PortInfo index="0" default="False" />
      <PortInfo index="1" default="True" />
    </Dynamo.Graph.Nodes.ZeroTouch.DSFunction>
    <Dynamo.Graph.Nodes.ZeroTouch.DSFunction guid="af980b26-aeda-4007-8cc5-9b9449a08d19" type="Dynamo.Graph.Nodes.ZeroTouch.DSFunction" nickname="Circle.ByPlaneRadius" x="1940" y="536" isVisible="true" isUpstreamVisible="true" lacing="Shortest" isSelectedInput="False" IsFrozen="false" isPinned="false" assembly="ProtoGeometry.dll" function="Autodesk.DesignScript.Geometry.Circle.ByPlaneRadius@Autodesk.DesignScript.Geometry.Plane,double">
      <PortInfo index="0" default="True" />
      <PortInfo index="1" default="True" />
    </Dynamo.Graph.Nodes.ZeroTouch.DSFunction>
    <Dynamo.Graph.Nodes.ZeroTouch.DSFunction guid="fa5d58df-17e6-4550-9991-539b3269aa51" type="Dynamo.Graph.Nodes.ZeroTouch.DSFunction" nickname="Solid.ByLoft" x="2250" y="425" isVisible="true" isUpstreamVisible="true" lacing="Shortest" isSelectedInput="False" IsFrozen="false" isPinned="false" assembly="ProtoGeometry.dll" function="Autodesk.DesignScript.Geometry.Solid.ByLoft@Autodesk.DesignScript.Geometry.Curve[],Autodesk.DesignScript.Geometry.Curve[]">
      <PortInfo index="0" default="False" />
      <PortInfo index="1" default="False" />
    </Dynamo.Graph.Nodes.ZeroTouch.DSFunction>
  </Elements>
  <Connectors>
    <Dynamo.Graph.Connectors.ConnectorModel start="9303f847-b510-4dc3-a374-289d7192aa2c" start_index="0" end="967a20a5-8e22-4476-8d3a-3edfbc5de3bd" end_index="0" portType="0" />
    <Dynamo.Graph.Connectors.ConnectorModel start="967a20a5-8e22-4476-8d3a-3edfbc5de3bd" start_index="0" end="4a461e2b-271e-4ca3-affa-eea69892055d" end_index="0" portType="0" />
    <Dynamo.Graph.Connectors.ConnectorModel start="967a20a5-8e22-4476-8d3a-3edfbc5de3bd" start_index="0" end="4d2bb49a-32f6-4e3d-b480-b65f69363663" end_index="0" portType="0" />
    <Dynamo.Graph.Connectors.ConnectorModel start="4a461e2b-271e-4ca3-affa-eea69892055d" start_index="0" end="fa5d58df-17e6-4550-9991-539b3269aa51" end_index="1" portType="0" />
    <Dynamo.Graph.Connectors.ConnectorModel start="4d2bb49a-32f6-4e3d-b480-b65f69363663" start_index="0" end="af980b26-aeda-4007-8cc5-9b9449a08d19" end_index="0" portType="0" />
    <Dynamo.Graph.Connectors.ConnectorModel start="af980b26-aeda-4007-8cc5-9b9449a08d19" start_index="0" end="fa5d58df-17e6-4550-9991-539b3269aa51" end_index="0" portType="0" />
  </Connectors>
  <Notes />
  <Annotations />
  <Presets />
  <Cameras>
    <Camera Name="Background Preview" eyeX="-17" eyeY="24" eyeZ="50" lookX="12" lookY="-13" lookZ="-58" upX="0" upY="1" upZ="0" />
  </Cameras>
</Workspace>