<Workspace Version="1.3.1.1736" X="-385.350016998189" Y="-180.246984497347" zoom="1.24844365397223" ScaleFactor="1" Name="Home" Description="" RunType="Manual" RunPeriod="1000" HasRunWithoutCrash="True">
  <NamespaceResolutionMap />
  <Elements>
    <PythonNodeModels.PythonNode guid="3ee9d142-45a0-4792-9b34-c396ec8c831c" type="PythonNodeModels.PythonNode" nickname="Python Script" x="1224.54083047545" y="537.292085239918" isVisible="true" isUpstreamVisible="true" lacing="Disabled" isSelectedInput="False" IsFrozen="false" isPinned="true" inputcount="1">
      <PortInfo index="0" default="False" />
      <Script>import clr
clr.AddReference('ProtoGeometry')
from Autodesk.DesignScript.Geometry import *

import sys
sys.path.append("C:\Program Files (x86)\IronPython 2.7\Lib")

import timeit

list = []
t = timeit.Timer("print 'main statement'", "print 'setup'")


OUT = t.timeit(3)</Script>
    </PythonNodeModels.PythonNode>
    <PythonNodeModels.PythonNode guid="28dda3a9-b0f8-4bad-bbf5-9f0908ce4170" type="PythonNodeModels.PythonNode" nickname="Python Script" x="849.991068493229" y="527.629999223632" isVisible="true" isUpstreamVisible="true" lacing="Disabled" isSelectedInput="False" IsFrozen="false" isPinned="true" inputcount="1">
      <PortInfo index="0" default="False" />
      <Script>import clr
clr.AddReference('ProtoGeometry')
from Autodesk.DesignScript.Geometry import *

import sys
sys.path.append("C:\Program Files (x86)\IronPython 2.7\Lib")

import timeit
 
# code snippet to be executed only once
mysetup = "from math import sqrt"
 
# code snippet whose execution time is to be measured
mycode = """
def example():
    mylist = []
    for x in range(100):
        mylist.append(sqrt(x))
"""
 
# timeit statement
OUT = timeit.timeit(setup = mysetup, stmt = mycode, number = 10000)</Script>
    </PythonNodeModels.PythonNode>
    <PythonNodeModels.PythonNode guid="c30cdd06-d484-456c-bd85-c669fe28f4f1" type="PythonNodeModels.PythonNode" nickname="Python Script" x="824.542740002195" y="676.953664817561" isVisible="true" isUpstreamVisible="true" lacing="Disabled" isSelectedInput="False" IsFrozen="false" isPinned="true" inputcount="1">
      <PortInfo index="0" default="False" />
      <Script>import clr
clr.AddReference('ProtoGeometry')
from Autodesk.DesignScript.Geometry import *

import sys
sys.path.append("C:\Program Files (x86)\IronPython 2.7\Lib")

import timeit
 
# code snippet to be executed only once
mysetup = "from math import sqrt"
 
# code snippet whose execution time is to be measured
mycode = """
myList = list()
"""
 
# timeit statement
OUT = timeit.timeit(setup = mysetup, stmt = mycode, number = 10000)*1000</Script>
    </PythonNodeModels.PythonNode>
    <PythonNodeModels.PythonNode guid="c99202a7-3c03-47a8-82d0-749779ac829e" type="PythonNodeModels.PythonNode" nickname="Python Script" x="1009.34373730537" y="680.082856292005" isVisible="true" isUpstreamVisible="true" lacing="Disabled" isSelectedInput="False" IsFrozen="false" isPinned="true" inputcount="1">
      <PortInfo index="0" default="False" />
      <Script>import clr
clr.AddReference('ProtoGeometry')
from Autodesk.DesignScript.Geometry import *

import sys
sys.path.append("C:\Program Files (x86)\IronPython 2.7\Lib")

import timeit
 
# code snippet to be executed only once
mysetup = "from math import sqrt"
 
# code snippet whose execution time is to be measured
mycode = """
myList = []
"""
 
# timeit statement
OUT = timeit.timeit(setup = mysetup, stmt = mycode, number = 10000)*1000</Script>
    </PythonNodeModels.PythonNode>
  </Elements>
  <Connectors />
  <Notes />
  <Annotations />
  <Presets />
  <Cameras>
    <Camera Name="Background Preview" eyeX="-17" eyeY="24" eyeZ="50" lookX="12" lookY="-13" lookZ="-58" upX="0" upY="1" upZ="0" />
  </Cameras>
</Workspace>