<Workspace Version="1.3.2.2480" X="-3339.79930729832" Y="-1890.24392154571" zoom="1.69706065739868" ScaleFactor="100" Name="Home" Description="" RunType="Manual" RunPeriod="1000" HasRunWithoutCrash="True">
  <NamespaceResolutionMap />
  <Elements>
    <PythonNodeModels.PythonNode guid="5fefd788-181d-4617-a0a1-8c636e6fc11b" type="PythonNodeModels.PythonNode" nickname="Python Script" x="376.532618380907" y="480.40772762408" isVisible="true" isUpstreamVisible="true" lacing="Disabled" isSelectedInput="False" IsFrozen="false" isPinned="false" inputcount="1">
      <PortInfo index="0" default="False" />
      <Script>import clr
clr.AddReference('RevitAPI')
from Autodesk.Revit.DB import *

clr.AddReference("RevitNodes")
import Revit
clr.ImportExtensions(Revit.GeometryConversion)

clr.AddReference('ProtoGeometry')
from Autodesk.DesignScript.Geometry import *

items = UnwrapElement(IN[0])

lines = []

for item in items:
	lines.append(item.Location.Curve.ToProtoType())

Pts = []


for line in lines:
	pt = []
	pt.append(Curve.PointAtParameter(line,0))
	stPt = Curve.PointAtParameter(line,0)
	endPt = Curve.PointAtParameter(line,1)
	pt.append(Point.ByCoordinates(stPt.X,stPt.Y,endPt.Z))
	Pts.append(pt)

OUT = Pts</Script>
    </PythonNodeModels.PythonNode>
    <PythonNodeModels.PythonNode guid="a483d394-5ea1-45d1-9499-db7ae9727abb" type="PythonNodeModels.PythonNode" nickname="Python Script" x="707.200506681801" y="342.288152835151" isVisible="true" isUpstreamVisible="true" lacing="Disabled" isSelectedInput="False" IsFrozen="false" isPinned="false" inputcount="2">
      <PortInfo index="0" default="False" />
      <PortInfo index="1" default="False" />
      <Script>import clr

clr.AddReference("RevitServices")
import RevitServices
from RevitServices.Persistence import DocumentManager
from RevitServices.Transactions import TransactionManager
doc = DocumentManager.Instance.CurrentDBDocument

clr.AddReference("RevitAPI")
import Autodesk
from Autodesk.Revit.DB import *

clr.AddReference("RevitNodes")
import Revit
clr.ImportExtensions(Revit.Elements)
clr.ImportExtensions(Revit.GeometryConversion)

clr.AddReference("System")
from System.Collections.Generic import List

beamElements = UnwrapElement(IN[0])
pts = UnwrapElement(IN[1])

beamLocations = []

for beam in beamElements:
	beamLocations.append(beam.Location)

newBeamLine = []

TransactionManager.Instance.EnsureInTransaction(doc)

for i in range(0,len(beamLocations)):
	newBeamLine = Line.CreateBound(pts[i][0].ToXyz(), pts[i][1].ToXyz())
	#Change the beam location line to a new line:
	beamLocations[i].Curve = newBeamLine;

            

TransactionManager.Instance.TransactionTaskDone()

OUT = beamElements</Script>
    </PythonNodeModels.PythonNode>
    <PythonNodeModels.PythonNode guid="65476ed0-b66d-4f9e-9ee2-58cf79e61635" type="PythonNodeModels.PythonNode" nickname="Python Script" x="1297.87450997498" y="1212.99836045876" isVisible="true" isUpstreamVisible="true" lacing="Disabled" isSelectedInput="False" IsFrozen="false" isPinned="true" inputcount="2">
      <PortInfo index="0" default="False" />
      <PortInfo index="1" default="False" />
      <Script>import clr

clr.AddReference('RevitAPI')
import Autodesk
from Autodesk.Revit.DB import *

clr.AddReference("RevitNodes")
import Revit
clr.ImportExtensions(Revit.Elements)
clr.ImportExtensions(Revit.GeometryConversion)

clr.AddReference("RevitServices")
from RevitServices.Persistence import DocumentManager
from RevitServices.Transactions import TransactionManager

doc = DocumentManager.Instance.CurrentDBDocument

getDocUnits = doc.GetUnits()
getDisplayUnits = getDocUnits.GetFormatOptions(UnitType.UT_Length).DisplayUnits


def ToInternalUnits(number):
	return UnitUtils.ConvertToInternalUnits(number, getDisplayUnits)

def translateBeamStartPoint(beam, offset):
	point = beam.Location.Curve.GetEndPoint(0)
	newPoint = XYZ(point.X, point.Y, point.Z - ToInternalUnits(offset))
	return newPoint

def translateBeamEndPoint(beam, offset):
	point = beam.Location.Curve.GetEndPoint(1)
	newPoint = XYZ(point.X, point.Y, point.Z - ToInternalUnits(offset))
	return newPoint

def beamStartPoint(beam):
	return beam.Location.Curve.GetEndPoint(0)

def beamEndPoint(beam):
	return beam.Location.Curve.GetEndPoint(1)


beams = UnwrapElement(IN[0])

offset = IN[1]


TransactionManager.Instance.EnsureInTransaction(doc)

for b in beams:
	pointStart = b.Location.Curve.GetEndPoint(0)
	newPointStart = XYZ(pointStart.X, pointStart.Y, pointStart.Z - ToInternalUnits(offset))
	pointEnd = b.Location.Curve.GetEndPoint(1)
	b.Location.Curve = Line.CreateBound(newPointStart, pointEnd)
	
TransactionManager.Instance.TransactionTaskDone()


OUT = beams</Script>
    </PythonNodeModels.PythonNode>
    <Dynamo.Nodes.DSModelElementsSelection guid="15da08a1-21ea-439b-bb4f-b0e267e6d0b0" type="Dynamo.Nodes.DSModelElementsSelection" nickname="Select Model Elements" x="1.10991250442618" y="613.538424734782" isVisible="true" isUpstreamVisible="true" lacing="Disabled" isSelectedInput="True" IsFrozen="false" isPinned="false">
      <instance id="eb3830e2-c3d7-411a-808b-78e40ac629bf-0039b73d" />
    </Dynamo.Nodes.DSModelElementsSelection>
    <Dynamo.Graph.Nodes.CodeBlockNodeModel guid="0ae722d4-a1af-484c-8343-ad78e7700ae6" type="Dynamo.Graph.Nodes.CodeBlockNodeModel" nickname="Code Block" x="65.7075340799474" y="757.027853897148" isVisible="true" isUpstreamVisible="true" lacing="Disabled" isSelectedInput="False" IsFrozen="false" isPinned="false" CodeText="700;" ShouldFocus="false" />
    <PythonNodeModels.PythonNode guid="07998f96-d875-4350-9201-181ae38ae50f" type="PythonNodeModels.PythonNode" nickname="Python Script" x="1489.27694947508" y="659.757449140337" isVisible="true" isUpstreamVisible="true" lacing="Disabled" isSelectedInput="False" IsFrozen="false" isPinned="true" inputcount="1">
      <PortInfo index="0" default="False" />
      <Script>import clr
clr.AddReference('RevitAPI')
import Autodesk
from Autodesk.Revit.DB import *

OUT = Line.CreateBound(IN[0][0], IN[0][1])</Script>
    </PythonNodeModels.PythonNode>
    <PythonNodeModels.PythonNode guid="ae26c247-2397-419b-a5f2-ac855d1c3f8c" type="PythonNodeModels.PythonNode" nickname="Python Script" x="412.184715878218" y="659.990773417777" isVisible="true" isUpstreamVisible="true" lacing="Disabled" isSelectedInput="False" IsFrozen="false" isPinned="true" inputcount="2">
      <PortInfo index="0" default="False" />
      <PortInfo index="1" default="False" />
      <Script>import clr

clr.AddReference('RevitAPI')
import Autodesk
from Autodesk.Revit.DB import *

clr.AddReference("RevitNodes")
import Revit
clr.ImportExtensions(Revit.Elements)
clr.ImportExtensions(Revit.GeometryConversion)

clr.AddReference("RevitServices")
from RevitServices.Persistence import DocumentManager
from RevitServices.Transactions import TransactionManager

doc = DocumentManager.Instance.CurrentDBDocument

getDocUnits = doc.GetUnits()
getDisplayUnits = getDocUnits.GetFormatOptions(UnitType.UT_Length).DisplayUnits


def ToInternalUnits(number):
	return UnitUtils.ConvertToInternalUnits(number, getDisplayUnits)

def translateBeamStartPoint(beam, offset):
	point = beam.Location.Curve.GetEndPoint(0)
	newPoint = XYZ(point.X, point.Y, point.Z - ToInternalUnits(offset))
	return newPoint

def translateBeamEndPoint(beam, offset):
	point = beam.Location.Curve.GetEndPoint(1)
	newPoint = XYZ(point.X, point.Y, point.Z - ToInternalUnits(offset))
	return newPoint

def beamStartPoint(beam):
	return beam.Location.Curve.GetEndPoint(0)

def beamEndPoint(beam):
	return beam.Location.Curve.GetEndPoint(1)


beams = UnwrapElement(IN[0])

offset = IN[1]


OUT = translateBeamStartPoint(beams,offset), beamEndPoint(beams)</Script>
    </PythonNodeModels.PythonNode>
    <PythonNodeModels.PythonNode guid="2142fcf6-ae4d-4336-a7b6-b5eb5445ad53" type="PythonNodeModels.PythonNode" nickname="Python Script" x="408.409198978471" y="886.048652473083" isVisible="true" isUpstreamVisible="true" lacing="Disabled" isSelectedInput="False" IsFrozen="false" isPinned="true" inputcount="2">
      <PortInfo index="0" default="False" />
      <PortInfo index="1" default="False" />
      <Script>import clr

clr.AddReference('RevitAPI')
import Autodesk
from Autodesk.Revit.DB import *

clr.AddReference("RevitNodes")
import Revit
clr.ImportExtensions(Revit.Elements)
clr.ImportExtensions(Revit.GeometryConversion)

clr.AddReference("RevitServices")
from RevitServices.Persistence import DocumentManager
from RevitServices.Transactions import TransactionManager

doc = DocumentManager.Instance.CurrentDBDocument

getDocUnits = doc.GetUnits()
getDisplayUnits = getDocUnits.GetFormatOptions(UnitType.UT_Length).DisplayUnits


def ToInternalUnits(number):
	return UnitUtils.ConvertToInternalUnits(number, getDisplayUnits)

def translateBeamStartPoint(beam, offset):
	point = beam.Location.Curve.GetEndPoint(0)
	newPoint = XYZ(point.X, point.Y, point.Z - ToInternalUnits(offset))
	return newPoint

def translateBeamEndPoint(beam, offset):
	point = beam.Location.Curve.GetEndPoint(1)
	newPoint = XYZ(point.X, point.Y, point.Z - ToInternalUnits(offset))
	return newPoint

def beamStartPoint(beam):
	return beam.Location.Curve.GetEndPoint(0)

def beamEndPoint(beam):
	return beam.Location.Curve.GetEndPoint(1)


beams = UnwrapElement(IN[0])

offset = IN[1]


OUT = translateBeamStartPoint(beams,offset), beamEndPoint(beams)</Script>
    </PythonNodeModels.PythonNode>
    <Dynamo.Nodes.DSModelElementsSelection guid="deed1f82-4589-4dd5-b83d-a244109fe115" type="Dynamo.Nodes.DSModelElementsSelection" nickname="Select Model Elements" x="30.0576394634455" y="888.778162027933" isVisible="true" isUpstreamVisible="true" lacing="Disabled" isSelectedInput="True" IsFrozen="false" isPinned="false">
      <instance id="6b153bcd-9a1c-4509-9c36-a5f869a9d4a2-00321b10" />
    </Dynamo.Nodes.DSModelElementsSelection>
    <PythonNodeModels.PythonNode guid="36eedfb0-635b-40d6-9fb2-1d6ede53233d" type="PythonNodeModels.PythonNode" nickname="Python Script" x="787.654373562983" y="875.948937445147" isVisible="true" isUpstreamVisible="true" lacing="Disabled" isSelectedInput="False" IsFrozen="false" isPinned="true" inputcount="1">
      <PortInfo index="0" default="False" />
      <Script>import clr
clr.AddReference('ProtoGeometry')
from Autodesk.DesignScript.Geometry import *
#The inputs to this node will be stored as a list in the IN variables.
import clr
clr.AddReference("RevitNodes")
import Revit
# Import ToProtoType, ToRevitType geometry conversion extension methods
clr.ImportExtensions(Revit.GeometryConversion)


pts = IN[0]



#Assign your output to the OUT variable.
OUT = [p.ToPoint() for p in pts]</Script>
    </PythonNodeModels.PythonNode>
    <PythonNodeModels.PythonNode guid="93d7855e-7f6a-490a-8bba-4df0afb42ff2" type="PythonNodeModels.PythonNode" nickname="Python Script" x="759.407655073781" y="663.169974510267" isVisible="true" isUpstreamVisible="true" lacing="Disabled" isSelectedInput="False" IsFrozen="false" isPinned="true" inputcount="1">
      <PortInfo index="0" default="False" />
      <Script>import clr
clr.AddReference('ProtoGeometry')
from Autodesk.DesignScript.Geometry import *
#The inputs to this node will be stored as a list in the IN variables.
import clr
clr.AddReference("RevitNodes")
import Revit
# Import ToProtoType, ToRevitType geometry conversion extension methods
clr.ImportExtensions(Revit.GeometryConversion)


pts = IN[0]



#Assign your output to the OUT variable.
OUT = [p.ToPoint() for p in pts]</Script>
    </PythonNodeModels.PythonNode>
    <Dynamo.Graph.Nodes.ZeroTouch.DSFunction guid="90c92de3-ec8f-4cf9-ab87-1f828afeff14" type="Dynamo.Graph.Nodes.ZeroTouch.DSFunction" nickname="Flatten" x="1193.57389702295" y="1624.20437861867" isVisible="true" isUpstreamVisible="true" lacing="Longest" isSelectedInput="False" IsFrozen="false" isPinned="true" assembly="BuiltIn" function="Flatten@var[]..[]">
      <PortInfo index="0" default="False" useLevels="True" level="3" shouldKeepListStructure="False" />
    </Dynamo.Graph.Nodes.ZeroTouch.DSFunction>
    <Dynamo.Graph.Nodes.ZeroTouch.DSFunction guid="fc4d70e3-77ff-43ca-987a-b7fdde55c00a" type="Dynamo.Graph.Nodes.ZeroTouch.DSFunction" nickname="Curve.PointAtParameter" x="871.755129580976" y="1623.95240912688" isVisible="true" isUpstreamVisible="true" lacing="CrossProduct" isSelectedInput="False" IsFrozen="false" isPinned="true" assembly="ProtoGeometry.dll" function="Autodesk.DesignScript.Geometry.Curve.PointAtParameter@double">
      <PortInfo index="0" default="False" />
      <PortInfo index="1" default="True" />
    </Dynamo.Graph.Nodes.ZeroTouch.DSFunction>
    <PythonNodeModels.PythonNode guid="bfe49398-781d-4cd3-a51f-64ec1a25099e" type="PythonNodeModels.PythonNode" nickname="Python Script" x="1605.68356722121" y="1229.35783286874" isVisible="true" isUpstreamVisible="true" lacing="Disabled" isSelectedInput="False" IsFrozen="false" isPinned="true" inputcount="2">
      <PortInfo index="0" default="False" />
      <PortInfo index="1" default="False" />
      <Script>import clr

clr.AddReference("RevitServices")
import RevitServices
from RevitServices.Persistence import DocumentManager
from RevitServices.Transactions import TransactionManager
doc = DocumentManager.Instance.CurrentDBDocument

clr.AddReference("RevitAPI")
import Autodesk
from Autodesk.Revit.DB import *

clr.AddReference("RevitNodes")
import Revit
clr.ImportExtensions(Revit.Elements)
clr.ImportExtensions(Revit.GeometryConversion)



beamElements = UnwrapElement(IN[0])
pts = UnwrapElement(IN[1])

beamLocations = []

for beam in beamElements:
	beamLocations.append(beam.Location)

newBeamLine = []

TransactionManager.Instance.EnsureInTransaction(doc)

for i in range(0,len(beamLocations)):
	newBeamLine = Line.CreateBound(pts[i][0].ToXyz(), pts[i][1].ToXyz())
	#Change the beam location line to a new line:
	beamLocations[i].Curve = newBeamLine;

            

TransactionManager.Instance.TransactionTaskDone()

OUT = beamElements
</Script>
    </PythonNodeModels.PythonNode>
    <Dynamo.Graph.Nodes.ZeroTouch.DSFunction guid="d9a14bf2-652f-4048-b648-45d6e9cdac27" type="Dynamo.Graph.Nodes.ZeroTouch.DSFunction" nickname="Element.Curves" x="523.183471980216" y="1621.55015359407" isVisible="true" isUpstreamVisible="true" lacing="Shortest" isSelectedInput="False" IsFrozen="false" isPinned="false" assembly="RevitNodes.dll" function="Revit.Elements.Element.Curves">
      <PortInfo index="0" default="False" />
    </Dynamo.Graph.Nodes.ZeroTouch.DSFunction>
    <Dynamo.Graph.Nodes.CodeBlockNodeModel guid="bcbf80d6-202b-4de5-a219-0eae244bc184" type="Dynamo.Graph.Nodes.CodeBlockNodeModel" nickname="Code Block" x="578.190026747436" y="1726.60179077904" isVisible="true" isUpstreamVisible="true" lacing="Disabled" isSelectedInput="False" IsFrozen="false" isPinned="false" CodeText="{0,1};" ShouldFocus="false" />
    <Dynamo.Nodes.DSModelElementsSelection guid="1ed4cdc6-f7d6-4d78-a9d8-963589f50bca" type="Dynamo.Nodes.DSModelElementsSelection" nickname="Select Model Elements" x="172.791137534725" y="1617.98787557677" isVisible="true" isUpstreamVisible="true" lacing="Disabled" isSelectedInput="True" IsFrozen="false" isPinned="false" />
    <Dynamo.Graph.Nodes.CodeBlockNodeModel guid="095ae04e-fb65-42f8-a14a-14c3b63ab77f" type="Dynamo.Graph.Nodes.CodeBlockNodeModel" nickname="Code Block" x="1067.35360029161" y="817.606401530964" isVisible="true" isUpstreamVisible="true" lacing="Disabled" isSelectedInput="False" IsFrozen="false" isPinned="false" CodeText="{a,b};" ShouldFocus="false">
      <PortInfo index="0" default="False" />
      <PortInfo index="1" default="False" />
    </Dynamo.Graph.Nodes.CodeBlockNodeModel>
    <PythonNodeModels.PythonNode guid="d87787e8-56b7-490f-91f0-f14f8b0f482f" type="PythonNodeModels.PythonNode" nickname="Python Script" x="475.144608372617" y="1178.82447957103" isVisible="true" isUpstreamVisible="true" lacing="Disabled" isSelectedInput="False" IsFrozen="false" isPinned="true" inputcount="2">
      <PortInfo index="0" default="False" />
      <PortInfo index="1" default="False" />
      <Script>import clr

clr.AddReference('RevitAPI')
import Autodesk
from Autodesk.Revit.DB import *

clr.AddReference("RevitNodes")
import Revit
clr.ImportExtensions(Revit.Elements)
clr.ImportExtensions(Revit.GeometryConversion)

clr.AddReference("RevitServices")
from RevitServices.Persistence import DocumentManager
from RevitServices.Transactions import TransactionManager

doc = DocumentManager.Instance.CurrentDBDocument

getDocUnits = doc.GetUnits()
getDisplayUnits = getDocUnits.GetFormatOptions(UnitType.UT_Length).DisplayUnits


def ToInternalUnits(number):
	return UnitUtils.ConvertToInternalUnits(number, getDisplayUnits)

def translateBeamStartPoint(beam, offset):
	point = beam.Location.Curve.GetEndPoint(0)
	newPoint = XYZ(point.X, point.Y, point.Z - ToInternalUnits(offset))
	return newPoint

def translateBeamEndPoint(beam, offset):
	point = beam.Location.Curve.GetEndPoint(1)
	newPoint = XYZ(point.X, point.Y, point.Z - ToInternalUnits(offset))
	return newPoint

def beamStartPoint(beam):
	return beam.Location.Curve.GetEndPoint(0)

def beamEndPoint(beam):
	return beam.Location.Curve.GetEndPoint(1)


beams = UnwrapElement(IN[0])

offset = IN[1]


OUT = [[translateBeamStartPoint(b,offset), beamEndPoint(b)] for b in beams]</Script>
    </PythonNodeModels.PythonNode>
    <Dynamo.Nodes.DSModelElementsSelection guid="97bbb8fc-22ed-4b72-932e-694c0edd9b42" type="Dynamo.Nodes.DSModelElementsSelection" nickname="Select Model Elements" x="87.2008266699604" y="1174.52945622942" isVisible="true" isUpstreamVisible="true" lacing="Disabled" isSelectedInput="True" IsFrozen="false" isPinned="false">
      <instance id="6b153bcd-9a1c-4509-9c36-a5f869a9d4a2-00321b10" />
      <instance id="eb3830e2-c3d7-411a-808b-78e40ac629bf-0039b73d" />
    </Dynamo.Nodes.DSModelElementsSelection>
    <PythonNodeModels.PythonNode guid="c90a00ab-e1c8-4405-881a-093fd148a7ea" type="PythonNodeModels.PythonNode" nickname="Python Script" x="714.167060481061" y="1352.59976312784" isVisible="true" isUpstreamVisible="true" lacing="Disabled" isSelectedInput="False" IsFrozen="false" isPinned="true" inputcount="1">
      <PortInfo index="0" default="False" />
      <Script>import clr
clr.AddReference('ProtoGeometry')
from Autodesk.DesignScript.Geometry import *
#The inputs to this node will be stored as a list in the IN variables.
import clr
clr.AddReference("RevitNodes")
import Revit
# Import ToProtoType, ToRevitType geometry conversion extension methods
clr.ImportExtensions(Revit.GeometryConversion)


def toPt(point):
	newPts = []
	for p in point:
		newPts.append(p.ToPoint())
	return newPts

pts = IN[0]

		
#Assign your output to the OUT variable.
OUT = [toPt(p) for p in pts]</Script>
    </PythonNodeModels.PythonNode>
    <Dynamo.Graph.Nodes.ZeroTouch.DSFunction guid="6e30cbf1-0731-4454-9046-67e96f508771" type="Dynamo.Graph.Nodes.ZeroTouch.DSFunction" nickname="Element.SetLocation" x="1618.03312972835" y="1094.63318199767" isVisible="true" isUpstreamVisible="true" lacing="Shortest" isSelectedInput="False" IsFrozen="false" isPinned="false" assembly="RevitNodes.dll" function="Revit.Elements.Element.SetLocation@Autodesk.DesignScript.Geometry.Geometry">
      <PortInfo index="0" default="False" />
      <PortInfo index="1" default="False" />
    </Dynamo.Graph.Nodes.ZeroTouch.DSFunction>
    <Dynamo.Graph.Nodes.CodeBlockNodeModel guid="bea0c2b2-5e96-407a-b9f4-ac4336952d8c" type="Dynamo.Graph.Nodes.CodeBlockNodeModel" nickname="Code Block" x="1072.01921039391" y="1288.42077764644" isVisible="true" isUpstreamVisible="true" lacing="Disabled" isSelectedInput="False" IsFrozen="false" isPinned="false" CodeText="336;" ShouldFocus="false" />
    <Dynamo.Graph.Nodes.CodeBlockNodeModel guid="0652e5d8-5d65-439b-b312-33636d2cd174" type="Dynamo.Graph.Nodes.CodeBlockNodeModel" nickname="Code Block" x="765.097811230848" y="1153.08669446155" isVisible="true" isUpstreamVisible="true" lacing="Disabled" isSelectedInput="False" IsFrozen="false" isPinned="false" CodeText="{A};" ShouldFocus="false">
      <PortInfo index="0" default="False" />
    </Dynamo.Graph.Nodes.CodeBlockNodeModel>
    <Dynamo.Nodes.DSModelElementSelection guid="7062eb15-432c-4ed3-bd5a-b5ef4f68037a" type="Dynamo.Nodes.DSModelElementSelection" nickname="Select Model Element" x="554.490642210715" y="1148.07923996246" isVisible="true" isUpstreamVisible="true" lacing="Disabled" isSelectedInput="True" IsFrozen="false" isPinned="false">
      <instance id="eb3830e2-c3d7-411a-808b-78e40ac629bf-0039b739" />
    </Dynamo.Nodes.DSModelElementSelection>
    <Dynamo.Nodes.DSModelElementsSelection guid="6ab2abd8-fe6d-4e6c-87ff-6077ce232dc1" type="Dynamo.Nodes.DSModelElementsSelection" nickname="Select Model Elements" x="969.05567842042" y="1122.81544931841" isVisible="true" isUpstreamVisible="true" lacing="Disabled" isSelectedInput="True" IsFrozen="false" isPinned="false">
      <instance id="6b153bcd-9a1c-4509-9c36-a5f869a9d4a2-00321ab3" />
      <instance id="6b153bcd-9a1c-4509-9c36-a5f869a9d4a2-00321ac1" />
      <instance id="6b153bcd-9a1c-4509-9c36-a5f869a9d4a2-00321ad1" />
      <instance id="eb3830e2-c3d7-411a-808b-78e40ac629bf-0039b731" />
      <instance id="eb3830e2-c3d7-411a-808b-78e40ac629bf-0039b733" />
      <instance id="eb3830e2-c3d7-411a-808b-78e40ac629bf-0039b735" />
    </Dynamo.Nodes.DSModelElementsSelection>
    <Dynamo.Nodes.DSModelElementsSelection guid="23e4451a-52e2-4764-93a3-f23adc429188" type="Dynamo.Nodes.DSModelElementsSelection" nickname="Select Model Elements" x="2120.11917937106" y="1293.06856623484" isVisible="true" isUpstreamVisible="true" lacing="Disabled" isSelectedInput="True" IsFrozen="false" isPinned="false">
      <instance id="6b153bcd-9a1c-4509-9c36-a5f869a9d4a2-00321ab3" />
      <instance id="6b153bcd-9a1c-4509-9c36-a5f869a9d4a2-00321ac1" />
      <instance id="6b153bcd-9a1c-4509-9c36-a5f869a9d4a2-00321ad1" />
      <instance id="6b153bcd-9a1c-4509-9c36-a5f869a9d4a2-00321ae0" />
      <instance id="eb3830e2-c3d7-411a-808b-78e40ac629bf-0039b731" />
      <instance id="eb3830e2-c3d7-411a-808b-78e40ac629bf-0039b733" />
      <instance id="eb3830e2-c3d7-411a-808b-78e40ac629bf-0039b735" />
      <instance id="eb3830e2-c3d7-411a-808b-78e40ac629bf-0039b737" />
    </Dynamo.Nodes.DSModelElementsSelection>
    <Dynamo.Graph.Nodes.CodeBlockNodeModel guid="c087ef7b-ef02-415b-9249-db06af67b1c9" type="Dynamo.Graph.Nodes.CodeBlockNodeModel" nickname="Code Block" x="2223.08271134455" y="1458.67389456287" isVisible="true" isUpstreamVisible="true" lacing="Disabled" isSelectedInput="False" IsFrozen="false" isPinned="false" CodeText="336;" ShouldFocus="false" />
    <PythonNodeModels.PythonNode guid="bc25ebe2-2416-4e35-9b10-c8d1b8d29819" type="PythonNodeModels.PythonNode" nickname="Python Script" x="2448.93801092562" y="1383.25147737519" isVisible="true" isUpstreamVisible="true" lacing="Disabled" isSelectedInput="False" IsFrozen="false" isPinned="true" inputcount="2">
      <PortInfo index="0" default="False" />
      <PortInfo index="1" default="False" />
      <Script>import clr

clr.AddReference('RevitAPI')
import Autodesk
from Autodesk.Revit.DB import *

clr.AddReference("RevitNodes")
import Revit
clr.ImportExtensions(Revit.Elements)
clr.ImportExtensions(Revit.GeometryConversion)

clr.AddReference("RevitServices")
from RevitServices.Persistence import DocumentManager
from RevitServices.Transactions import TransactionManager

doc = DocumentManager.Instance.CurrentDBDocument

getDocUnits = doc.GetUnits()
getDisplayUnits = getDocUnits.GetFormatOptions(UnitType.UT_Length).DisplayUnits


def ToInternalUnits(number):
	return UnitUtils.ConvertToInternalUnits(number, getDisplayUnits)

def translateBeamStartPoint(beam, offset):
	point = beam.Location.Curve.GetEndPoint(0)
	newPoint = XYZ(point.X, point.Y, point.Z - ToInternalUnits(offset))
	return newPoint

def translateBeamEndPoint(beam, offset):
	point = beam.Location.Curve.GetEndPoint(1)
	newPoint = XYZ(point.X, point.Y, point.Z - ToInternalUnits(offset))
	return newPoint

def beamStartPoint(beam):
	return beam.Location.Curve.GetEndPoint(0)

def beamEndPoint(beam):
	return beam.Location.Curve.GetEndPoint(1)


beams = UnwrapElement(IN[0])

offset = IN[1]


TransactionManager.Instance.EnsureInTransaction(doc)

for b in beams:
	b.Location.Curve = Line.CreateBound(beamStartPoint(b), translateBeamEndPoint(b,offset))
	
TransactionManager.Instance.TransactionTaskDone()


OUT = beams</Script>
    </PythonNodeModels.PythonNode>
  </Elements>
  <Connectors>
    <Dynamo.Graph.Connectors.ConnectorModel start="15da08a1-21ea-439b-bb4f-b0e267e6d0b0" start_index="0" end="ae26c247-2397-419b-a5f2-ac855d1c3f8c" end_index="0" portType="0" />
    <Dynamo.Graph.Connectors.ConnectorModel start="0ae722d4-a1af-484c-8343-ad78e7700ae6" start_index="0" end="ae26c247-2397-419b-a5f2-ac855d1c3f8c" end_index="1" portType="0" />
    <Dynamo.Graph.Connectors.ConnectorModel start="0ae722d4-a1af-484c-8343-ad78e7700ae6" start_index="0" end="2142fcf6-ae4d-4336-a7b6-b5eb5445ad53" end_index="1" portType="0" />
    <Dynamo.Graph.Connectors.ConnectorModel start="0ae722d4-a1af-484c-8343-ad78e7700ae6" start_index="0" end="d87787e8-56b7-490f-91f0-f14f8b0f482f" end_index="1" portType="0" />
    <Dynamo.Graph.Connectors.ConnectorModel start="ae26c247-2397-419b-a5f2-ac855d1c3f8c" start_index="0" end="93d7855e-7f6a-490a-8bba-4df0afb42ff2" end_index="0" portType="0" />
    <Dynamo.Graph.Connectors.ConnectorModel start="2142fcf6-ae4d-4336-a7b6-b5eb5445ad53" start_index="0" end="36eedfb0-635b-40d6-9fb2-1d6ede53233d" end_index="0" portType="0" />
    <Dynamo.Graph.Connectors.ConnectorModel start="deed1f82-4589-4dd5-b83d-a244109fe115" start_index="0" end="2142fcf6-ae4d-4336-a7b6-b5eb5445ad53" end_index="0" portType="0" />
    <Dynamo.Graph.Connectors.ConnectorModel start="36eedfb0-635b-40d6-9fb2-1d6ede53233d" start_index="0" end="095ae04e-fb65-42f8-a14a-14c3b63ab77f" end_index="1" portType="0" />
    <Dynamo.Graph.Connectors.ConnectorModel start="93d7855e-7f6a-490a-8bba-4df0afb42ff2" start_index="0" end="095ae04e-fb65-42f8-a14a-14c3b63ab77f" end_index="0" portType="0" />
    <Dynamo.Graph.Connectors.ConnectorModel start="fc4d70e3-77ff-43ca-987a-b7fdde55c00a" start_index="0" end="90c92de3-ec8f-4cf9-ab87-1f828afeff14" end_index="0" portType="0" />
    <Dynamo.Graph.Connectors.ConnectorModel start="d9a14bf2-652f-4048-b648-45d6e9cdac27" start_index="0" end="fc4d70e3-77ff-43ca-987a-b7fdde55c00a" end_index="0" portType="0" />
    <Dynamo.Graph.Connectors.ConnectorModel start="bcbf80d6-202b-4de5-a219-0eae244bc184" start_index="0" end="fc4d70e3-77ff-43ca-987a-b7fdde55c00a" end_index="1" portType="0" />
    <Dynamo.Graph.Connectors.ConnectorModel start="1ed4cdc6-f7d6-4d78-a9d8-963589f50bca" start_index="0" end="d9a14bf2-652f-4048-b648-45d6e9cdac27" end_index="0" portType="0" />
    <Dynamo.Graph.Connectors.ConnectorModel start="d87787e8-56b7-490f-91f0-f14f8b0f482f" start_index="0" end="c90a00ab-e1c8-4405-881a-093fd148a7ea" end_index="0" portType="0" />
    <Dynamo.Graph.Connectors.ConnectorModel start="97bbb8fc-22ed-4b72-932e-694c0edd9b42" start_index="0" end="d87787e8-56b7-490f-91f0-f14f8b0f482f" end_index="0" portType="0" />
    <Dynamo.Graph.Connectors.ConnectorModel start="7062eb15-432c-4ed3-bd5a-b5ef4f68037a" start_index="0" end="0652e5d8-5d65-439b-b312-33636d2cd174" end_index="0" portType="0" />
    <Dynamo.Graph.Connectors.ConnectorModel start="23e4451a-52e2-4764-93a3-f23adc429188" start_index="0" end="bc25ebe2-2416-4e35-9b10-c8d1b8d29819" end_index="0" portType="0" />
    <Dynamo.Graph.Connectors.ConnectorModel start="c087ef7b-ef02-415b-9249-db06af67b1c9" start_index="0" end="bc25ebe2-2416-4e35-9b10-c8d1b8d29819" end_index="1" portType="0" />
  </Connectors>
  <Notes />
  <Annotations>
    <Dynamo.Graph.Annotations.AnnotationModel guid="589e158a-6edc-4b8a-979e-653681d960e8" annotationText="This works" left="959.05567842042" top="1076.81544931841" width="472.81883155456" height="304.605328328038" fontSize="30" InitialTop="1122.81544931841" InitialHeight="288.605328328038" TextblockHeight="36" backgrouund="#FFC1D676">
      <Models ModelGuid="65476ed0-b66d-4f9e-9ee2-58cf79e61635" />
      <Models ModelGuid="bea0c2b2-5e96-407a-b9f4-ac4336952d8c" />
      <Models ModelGuid="6ab2abd8-fe6d-4e6c-87ff-6077ce232dc1" />
    </Dynamo.Graph.Annotations.AnnotationModel>
    <Dynamo.Graph.Annotations.AnnotationModel guid="4e287ddc-86b7-48fd-ae2e-03c46835d99b" annotationText="This works" left="2110.11917937106" top="1247.06856623484" width="472.81883155456" height="304.60532832803" fontSize="30" InitialTop="1293.06856623484" InitialHeight="288.60532832803" TextblockHeight="36" backgrouund="#FFC1D676">
      <Models ModelGuid="bc25ebe2-2416-4e35-9b10-c8d1b8d29819" />
      <Models ModelGuid="c087ef7b-ef02-415b-9249-db06af67b1c9" />
      <Models ModelGuid="23e4451a-52e2-4764-93a3-f23adc429188" />
    </Dynamo.Graph.Annotations.AnnotationModel>
  </Annotations>
  <Presets />
  <Cameras>
    <Camera Name="Background Preview" eyeX="-17" eyeY="24" eyeZ="50" lookX="12" lookY="-13" lookZ="-58" upX="0" upY="1" upZ="0" />
  </Cameras>
</Workspace>