<Workspace Version="1.3.2.2480" X="0" Y="0" zoom="1" ScaleFactor="1" Name="Home" Description="" RunType="Manual" RunPeriod="1000" HasRunWithoutCrash="True">
  <NamespaceResolutionMap />
  <Elements>
    <Dynamo.Graph.Nodes.CodeBlockNodeModel guid="62f1cdb5-a177-4a41-ae2e-2a6f814f09d1" type="Dynamo.Graph.Nodes.CodeBlockNodeModel" nickname="Code Block" x="176" y="206" isVisible="true" isUpstreamVisible="true" lacing="Disabled" isSelectedInput="False" IsFrozen="false" isPinned="true" CodeText="1..10;" ShouldFocus="false" />
    <PythonNodeModels.PythonNode guid="4b892361-afe9-49fc-bc87-0a36e9bcac41" type="PythonNodeModels.PythonNode" nickname="Python Script" x="350" y="90" isVisible="true" isUpstreamVisible="true" lacing="Disabled" isSelectedInput="False" IsFrozen="false" isPinned="true" inputcount="1">
      <PortInfo index="0" default="False" />
      <Script>import clr
clr.AddReference('ProtoGeometry')
from Autodesk.DesignScript.Geometry import *

clr.AddReference('DSCoreNodes')
from DSCore import *


#The inputs to this node will be stored as a list in the IN variables.
dataEnteringNode = IN

inputList = IN[0]

#Assign your output to the OUT variable.
OUT = List.RestOfItems(inputList)</Script>
    </PythonNodeModels.PythonNode>
    <PythonNodeModels.PythonNode guid="d0f5bc94-75cd-4c13-9f94-bf8f9071b40b" type="PythonNodeModels.PythonNode" nickname="Python Script" x="387" y="491" isVisible="true" isUpstreamVisible="true" lacing="Disabled" isSelectedInput="False" IsFrozen="false" isPinned="true" inputcount="1">
      <PortInfo index="0" default="False" />
      <Script>import clr
clr.AddReference('ProtoGeometry')
from Autodesk.DesignScript.Geometry import *

clr.AddReference('DSCoreNodes')
from DSCore import *


#The inputs to this node will be stored as a list in the IN variables.
dataEnteringNode = IN

inputList = IN[0]

newList = del inputList[0]
#Assign your output to the OUT variable.
OUT = newList</Script>
    </PythonNodeModels.PythonNode>
    <Dynamo.Graph.Nodes.ZeroTouch.DSFunction guid="d867ac4a-0fa5-47a7-b581-6aeae353f1e0" type="Dynamo.Graph.Nodes.ZeroTouch.DSFunction" nickname="Counter.Step" x="806.5" y="394" isVisible="true" isUpstreamVisible="true" lacing="Shortest" isSelectedInput="False" IsFrozen="false" isPinned="false" assembly="..\Downloads\Danimo.dll" function="Core.Counter.Step@bool,double">
      <PortInfo index="0" default="False" />
      <PortInfo index="1" default="False" />
    </Dynamo.Graph.Nodes.ZeroTouch.DSFunction>
  </Elements>
  <Connectors>
    <Dynamo.Graph.Connectors.ConnectorModel start="62f1cdb5-a177-4a41-ae2e-2a6f814f09d1" start_index="0" end="4b892361-afe9-49fc-bc87-0a36e9bcac41" end_index="0" portType="0" />
    <Dynamo.Graph.Connectors.ConnectorModel start="62f1cdb5-a177-4a41-ae2e-2a6f814f09d1" start_index="0" end="d0f5bc94-75cd-4c13-9f94-bf8f9071b40b" end_index="0" portType="0" />
  </Connectors>
  <Notes />
  <Annotations />
  <Presets />
  <Cameras>
    <Camera Name="Background Preview" eyeX="-17" eyeY="24" eyeZ="50" lookX="12" lookY="-13" lookZ="-58" upX="0" upY="1" upZ="0" />
  </Cameras>
</Workspace>