<Workspace Version="1.3.2.2480" X="-467.812136455668" Y="-177.049048842499" zoom="1.07974991258409" ScaleFactor="1" Name="Home" Description="" RunType="Manual" RunPeriod="1000" HasRunWithoutCrash="True">
  <NamespaceResolutionMap />
  <Elements>
    <PythonNodeModels.PythonNode guid="b5b14d6a-7f29-47c1-ba2d-a65439c8aa0b" type="PythonNodeModels.PythonNode" nickname="Python Script" x="1253.14605351823" y="342.181653458175" isVisible="true" isUpstreamVisible="true" lacing="Disabled" isSelectedInput="False" IsFrozen="false" isPinned="true" inputcount="1">
      <PortInfo index="0" default="False" />
      <Script>import clr
clr.AddReference("ProtoGeometry")
from Autodesk.DesignScript.Geometry import *

# Import RevitAPI
clr.AddReference("RevitAPI")
from Autodesk.Revit.DB import *
from Autodesk.Revit.DB import Parameter

clr.AddReference("RevitAPIUI")
from Autodesk.Revit.UI import TaskDialog
# Import DocumentManager and TransactionManager
clr.AddReference("RevitServices")
from RevitServices.Persistence import DocumentManager
from RevitServices.Transactions import TransactionManager
# Import ToProtoType, ToRevitType geometry conversion extension methods
clr.AddReference("RevitNodes")
import Revit
clr.ImportExtensions(Revit.GeometryConversion)

import math

doc = DocumentManager.Instance.CurrentDBDocument
uiapp = DocumentManager.Instance.CurrentUIApplication
app = uiapp.Application


ele = UnwrapElement(IN[0])

newId = ElementId(1234567)

TransactionManager.Instance.EnsureInTransaction(doc)

#ele.Set(ElementId(newId));

TransactionManager.Instance.TransactionTaskDone()

OUT = ele.Value
</Script>
    </PythonNodeModels.PythonNode>
    <Dynamo.Nodes.DSModelElementSelection guid="2deb937d-d714-4fff-8974-ceafe5d75b04" type="Dynamo.Nodes.DSModelElementSelection" nickname="Select Model Element" x="407.298601432124" y="414.16487790972" isVisible="true" isUpstreamVisible="true" lacing="Disabled" isSelectedInput="True" IsFrozen="false" isPinned="false">
      <instance id="2d13e50b-a911-4909-857a-18eb661d3d24-000029e7" />
    </Dynamo.Nodes.DSModelElementSelection>
    <Dynamo.Graph.Nodes.CustomNodes.Function guid="a1b1a508-1fe1-42ac-9cc2-c3d70d2a8df3" type="Dynamo.Graph.Nodes.CustomNodes.Function" nickname="bv IDs to Elements" x="882.159657598997" y="682.082712978117" isVisible="true" isUpstreamVisible="true" lacing="Shortest" isSelectedInput="False" IsFrozen="false" isPinned="true">
      <PortInfo index="0" default="False" />
      <ID value="b2a2941e-7151-4158-81ce-522d451de0ff" />
      <Name value="bv IDs to Elements" />
      <Description value="forked from CAAD_RWTH" />
      <Inputs>
        <Input value="IDs" />
      </Inputs>
      <Outputs>
        <Output value="Element(s)" />
      </Outputs>
    </Dynamo.Graph.Nodes.CustomNodes.Function>
    <Dynamo.Graph.Nodes.CustomNodes.Function guid="70cff20f-be6c-4960-91f0-7b3bf1ee6578" type="Dynamo.Graph.Nodes.CustomNodes.Function" nickname="Duct Clash Check" x="452.419998473309" y="216.387580607635" isVisible="true" isUpstreamVisible="true" lacing="Shortest" isSelectedInput="False" IsFrozen="false" isPinned="false">
      <PortInfo index="0" default="False" />
      <PortInfo index="1" default="False" />
      <ID value="0b22c6e1-1550-4023-8180-bec2378903cf" />
      <Name value="Duct Clash Check" />
      <Description value="Check Clash" />
      <Inputs>
        <Input value="Beams" />
        <Input value="Ducts" />
      </Inputs>
      <Outputs>
        <Output value="OUT" />
      </Outputs>
    </Dynamo.Graph.Nodes.CustomNodes.Function>
    <Dynamo.Graph.Nodes.ZeroTouch.DSFunction guid="44b55745-1c5d-49b2-a21a-e367e0dadca4" type="Dynamo.Graph.Nodes.ZeroTouch.DSFunction" nickname="Element.Parameters" x="639.445085631438" y="241.629153644482" isVisible="true" isUpstreamVisible="true" lacing="Shortest" isSelectedInput="False" IsFrozen="false" isPinned="true" assembly="RevitNodes.dll" function="Revit.Elements.Element.Parameters">
      <PortInfo index="0" default="False" />
    </Dynamo.Graph.Nodes.ZeroTouch.DSFunction>
    <Dynamo.Graph.Nodes.ZeroTouch.DSFunction guid="0c7784f5-b280-4657-92b6-9f465cb972df" type="Dynamo.Graph.Nodes.ZeroTouch.DSFunction" nickname="Parameter.Id" x="938.932362614769" y="144.523326210824" isVisible="true" isUpstreamVisible="true" lacing="Shortest" isSelectedInput="False" IsFrozen="false" isPinned="true" assembly="RevitNodes.dll" function="Revit.Elements.Parameter.Id">
      <PortInfo index="0" default="False" />
    </Dynamo.Graph.Nodes.ZeroTouch.DSFunction>
    <Dynamo.Graph.Nodes.CodeBlockNodeModel guid="6fbacb13-0fc1-47e8-bea2-2728582f3dcf" type="Dynamo.Graph.Nodes.CodeBlockNodeModel" nickname="Code Block" x="655" y="585" isVisible="true" isUpstreamVisible="true" lacing="Disabled" isSelectedInput="False" IsFrozen="false" isPinned="true" CodeText="a[4];" ShouldFocus="false">
      <PortInfo index="0" default="False" />
    </Dynamo.Graph.Nodes.CodeBlockNodeModel>
  </Elements>
  <Connectors>
    <Dynamo.Graph.Connectors.ConnectorModel start="2deb937d-d714-4fff-8974-ceafe5d75b04" start_index="0" end="44b55745-1c5d-49b2-a21a-e367e0dadca4" end_index="0" portType="0" />
    <Dynamo.Graph.Connectors.ConnectorModel start="44b55745-1c5d-49b2-a21a-e367e0dadca4" start_index="0" end="0c7784f5-b280-4657-92b6-9f465cb972df" end_index="0" portType="0" />
    <Dynamo.Graph.Connectors.ConnectorModel start="44b55745-1c5d-49b2-a21a-e367e0dadca4" start_index="0" end="6fbacb13-0fc1-47e8-bea2-2728582f3dcf" end_index="0" portType="0" />
    <Dynamo.Graph.Connectors.ConnectorModel start="6fbacb13-0fc1-47e8-bea2-2728582f3dcf" start_index="0" end="b5b14d6a-7f29-47c1-ba2d-a65439c8aa0b" end_index="0" portType="0" />
  </Connectors>
  <Notes />
  <Annotations />
  <Presets />
  <Cameras>
    <Camera Name="Background Preview" eyeX="-17" eyeY="24" eyeZ="50" lookX="12" lookY="-13" lookZ="-58" upX="0" upY="1" upZ="0" />
  </Cameras>
</Workspace>