<Workspace Version="1.3.3.4651" X="796.933831213076" Y="-160.744052879105" zoom="0.590352561493107" ScaleFactor="1" Name="Home" Description="" RunType="Manual" RunPeriod="1000" HasRunWithoutCrash="True">
  <NamespaceResolutionMap />
  <Elements>
    <Dynamo.Nodes.DSModelElementsSelection guid="ef9a7392-a6f7-4ea0-be75-70f7254f7c91" type="Dynamo.Nodes.DSModelElementsSelection" nickname="Select Model Elements" x="161" y="157" isVisible="true" isUpstreamVisible="true" lacing="Disabled" isSelectedInput="True" IsFrozen="false" isPinned="false">
      <instance id="364c43ce-fda9-4f4b-b139-6b99bfc01d97-00679cc6" />
      <instance id="364c43ce-fda9-4f4b-b139-6b99bfc01d97-00679ccb" />
      <instance id="364c43ce-fda9-4f4b-b139-6b99bfc01d97-00679ccc" />
      <instance id="364c43ce-fda9-4f4b-b139-6b99bfc01d97-00679cd5" />
      <instance id="364c43ce-fda9-4f4b-b139-6b99bfc01d97-00679d1a" />
      <instance id="2ee201bd-7312-4659-bf4b-ac4fda17a30d-00679d73" />
      <instance id="32305f76-13d3-4dc1-9471-0457eebc3fc4-0067cf30" />
      <instance id="32305f76-13d3-4dc1-9471-0457eebc3fc4-0067cf38" />
      <instance id="a349d538-df5a-4da4-96b8-27915a38f11f-0068908f" />
      <instance id="a349d538-df5a-4da4-96b8-27915a38f11f-00689090" />
      <instance id="a349d538-df5a-4da4-96b8-27915a38f11f-00689091" />
      <instance id="a349d538-df5a-4da4-96b8-27915a38f11f-00689092" />
      <instance id="228f1859-ad5c-4d07-9fef-45535b83f832-006a3fe4" />
    </Dynamo.Nodes.DSModelElementsSelection>
    <PythonNodeModels.PythonNode guid="54072ec1-9bd4-427c-8c21-1308a40b8b94" type="PythonNodeModels.PythonNode" nickname="Python Script" x="367.926127046786" y="737.574795456928" isVisible="true" isUpstreamVisible="true" lacing="Disabled" isSelectedInput="False" IsFrozen="false" isPinned="false" inputcount="2">
      <PortInfo index="0" default="False" />
      <PortInfo index="1" default="False" />
      <Script># Copyright(c) 2017, Konrad K Sobon
# @arch_laboratory, http://archi-lab.net

import clr
import sys

pyt_path = r'C:\Program Files (x86)\IronPython 2.7\Lib'
sys.path.append(pyt_path)

clr.AddReference('ProtoGeometry')
from Autodesk.DesignScript.Geometry import *

clr.AddReference("RevitNodes")
import Revit

clr.ImportExtensions(Revit.Elements)
clr.ImportExtensions(Revit.GeometryConversion)

clr.AddReference("RevitServices")
from RevitServices.Persistence import DocumentManager
from RevitServices.Transactions import TransactionManager

doc = DocumentManager.Instance.CurrentDBDocument

clr.AddReference("RevitAPI")
import Autodesk
from Autodesk.Revit.DB import *

schedules = UnwrapElement(IN[0])
points = UnwrapElement(IN[1])

output = []

TransactionManager.Instance.EnsureInTransaction(doc)

for s,p in zip(schedules,points):
	s.Point = p
	output.append(s)

TransactionManager.Instance.TransactionTaskDone()

OUT = output</Script>
    </PythonNodeModels.PythonNode>
    <Dynamo.Nodes.DSModelElementsSelection guid="ff0a5d87-8314-46bd-8875-f1950498adae" type="Dynamo.Nodes.DSModelElementsSelection" nickname="Select Model Elements" x="-301.714302420811" y="833.614822298653" isVisible="true" isUpstreamVisible="true" lacing="Disabled" isSelectedInput="True" IsFrozen="false" isPinned="true">
      <instance id="364c43ce-fda9-4f4b-b139-6b99bfc01d97-00679cd5" />
      <instance id="364c43ce-fda9-4f4b-b139-6b99bfc01d97-00679d1a" />
    </Dynamo.Nodes.DSModelElementsSelection>
    <PythonNodeModels.PythonNode guid="c8bc71f8-6f63-4d22-b427-96b93a0712e8" type="PythonNodeModels.PythonNode" nickname="Python Script" x="159.535355656193" y="830.428933630012" isVisible="true" isUpstreamVisible="true" lacing="Disabled" isSelectedInput="False" IsFrozen="false" isPinned="true" inputcount="1">
      <PortInfo index="0" default="False" />
      <Script># Copyright(c) 2017, Konrad K Sobon
# @arch_laboratory, http://archi-lab.net

import clr
import sys

pyt_path = r'C:\Program Files (x86)\IronPython 2.7\Lib'
sys.path.append(pyt_path)

clr.AddReference('ProtoGeometry')
from Autodesk.DesignScript.Geometry import *

clr.AddReference("RevitNodes")
import Revit

clr.ImportExtensions(Revit.Elements)
clr.ImportExtensions(Revit.GeometryConversion)

clr.AddReference("RevitServices")
from RevitServices.Persistence import DocumentManager
from RevitServices.Transactions import TransactionManager

doc = DocumentManager.Instance.CurrentDBDocument

clr.AddReference("RevitAPI")
import Autodesk
from Autodesk.Revit.DB import *

schedules = UnwrapElement(IN[0])

OUT = [s.Point for s in schedules]</Script>
    </PythonNodeModels.PythonNode>
    <Dynamo.Nodes.DSModelElementsSelection guid="12fbb78f-b35c-474e-8589-12d2f115fe40" type="Dynamo.Nodes.DSModelElementsSelection" nickname="Select Model Elements" x="-49.8649127610551" y="544.188772579663" isVisible="true" isUpstreamVisible="true" lacing="Disabled" isSelectedInput="True" IsFrozen="false" isPinned="true">
      <instance id="3f404538-da29-478a-afe2-25c45884882e-006e6b4e" />
      <instance id="3f404538-da29-478a-afe2-25c45884882e-006e6b4f" />
    </Dynamo.Nodes.DSModelElementsSelection>
    <Dynamo.Nodes.DSModelElementsSelection guid="f1bb20e2-b636-4b8c-8673-8feb18dbb644" type="Dynamo.Nodes.DSModelElementsSelection" nickname="Select Model Elements" x="-296.80415280017" y="1468.81403674907" isVisible="true" isUpstreamVisible="true" lacing="Disabled" isSelectedInput="True" IsFrozen="false" isPinned="true">
      <instance id="364c43ce-fda9-4f4b-b139-6b99bfc01d97-00679cd5" />
      <instance id="364c43ce-fda9-4f4b-b139-6b99bfc01d97-00679d1a" />
    </Dynamo.Nodes.DSModelElementsSelection>
    <Dynamo.Nodes.DSModelElementsSelection guid="e9852c96-1328-41f3-ad9e-ed93151cb63f" type="Dynamo.Nodes.DSModelElementsSelection" nickname="Select Model Elements" x="-44.9547631404145" y="1179.38798703008" isVisible="true" isUpstreamVisible="true" lacing="Disabled" isSelectedInput="True" IsFrozen="false" isPinned="true">
      <instance id="3f404538-da29-478a-afe2-25c45884882e-006e6b4e" />
      <instance id="3f404538-da29-478a-afe2-25c45884882e-006e6b4f" />
    </Dynamo.Nodes.DSModelElementsSelection>
    <PythonNodeModels.PythonNode guid="02588b68-032d-44fb-9d69-662366fefa70" type="PythonNodeModels.PythonNode" nickname="Python Script" x="164.445505276834" y="1465.62814808043" isVisible="true" isUpstreamVisible="true" lacing="Disabled" isSelectedInput="False" IsFrozen="false" isPinned="true" inputcount="1">
      <PortInfo index="0" default="False" />
      <Script># Copyright(c) 2017, Konrad K Sobon
# @arch_laboratory, http://archi-lab.net

import clr
import sys

pyt_path = r'C:\Program Files (x86)\IronPython 2.7\Lib'
sys.path.append(pyt_path)

clr.AddReference('ProtoGeometry')
from Autodesk.DesignScript.Geometry import *

clr.AddReference("RevitNodes")
import Revit

clr.ImportExtensions(Revit.Elements)
clr.ImportExtensions(Revit.GeometryConversion)

clr.AddReference("RevitServices")
from RevitServices.Persistence import DocumentManager
from RevitServices.Transactions import TransactionManager

doc = DocumentManager.Instance.CurrentDBDocument

clr.AddReference("RevitAPI")
import Autodesk
from Autodesk.Revit.DB import *

schedules = UnwrapElement(IN[0])

OUT = [s.GetBoxCenter() for s in schedules]</Script>
    </PythonNodeModels.PythonNode>
    <PythonNodeModels.PythonNode guid="85224a2a-154e-4fbb-9cc9-220a242ac00c" type="PythonNodeModels.PythonNode" nickname="Python Script" x="372.836276667427" y="1372.77400990734" isVisible="true" isUpstreamVisible="true" lacing="Disabled" isSelectedInput="False" IsFrozen="false" isPinned="false" inputcount="2">
      <PortInfo index="0" default="False" />
      <PortInfo index="1" default="False" />
      <Script># Copyright(c) 2017, Konrad K Sobon
# @arch_laboratory, http://archi-lab.net

import clr
import sys

pyt_path = r'C:\Program Files (x86)\IronPython 2.7\Lib'
sys.path.append(pyt_path)

clr.AddReference('ProtoGeometry')
from Autodesk.DesignScript.Geometry import *

clr.AddReference("RevitNodes")
import Revit

clr.ImportExtensions(Revit.Elements)
clr.ImportExtensions(Revit.GeometryConversion)

clr.AddReference("RevitServices")
from RevitServices.Persistence import DocumentManager
from RevitServices.Transactions import TransactionManager

doc = DocumentManager.Instance.CurrentDBDocument

clr.AddReference("RevitAPI")
import Autodesk
from Autodesk.Revit.DB import *

schedules = UnwrapElement(IN[0])
points = UnwrapElement(IN[1])

output = []

TransactionManager.Instance.EnsureInTransaction(doc)

for s,p in zip(schedules,points):
	s.SetBoxCenter(p)
	output.append(s)

TransactionManager.Instance.TransactionTaskDone()

OUT = output</Script>
    </PythonNodeModels.PythonNode>
    <Dynamo.Nodes.DSModelElementsSelection guid="908eb55c-fc7f-4d04-91c7-e121e5a20e01" type="Dynamo.Nodes.DSModelElementsSelection" nickname="Select Model Elements" x="-371.259791201878" y="2048.09597718593" isVisible="true" isUpstreamVisible="true" lacing="Disabled" isSelectedInput="True" IsFrozen="false" isPinned="true">
      <instance id="364c43ce-fda9-4f4b-b139-6b99bfc01d97-00679d1b" />
    </Dynamo.Nodes.DSModelElementsSelection>
    <PythonNodeModels.PythonNode guid="6ff49109-3772-4b76-8c71-06087879c8dc" type="PythonNodeModels.PythonNode" nickname="Python Script" x="-43.0414445942801" y="2049.48431408967" isVisible="true" isUpstreamVisible="true" lacing="Disabled" isSelectedInput="False" IsFrozen="false" isPinned="true" inputcount="1">
      <PortInfo index="0" default="False" />
      <Script># Copyright(c) 2017, Konrad K Sobon
# @arch_laboratory, http://archi-lab.net

import clr
import sys

pyt_path = r'C:\Program Files (x86)\IronPython 2.7\Lib'
sys.path.append(pyt_path)

clr.AddReference('ProtoGeometry')
from Autodesk.DesignScript.Geometry import *

clr.AddReference("RevitNodes")
import Revit

clr.ImportExtensions(Revit.Elements)
clr.ImportExtensions(Revit.GeometryConversion)

clr.AddReference("RevitServices")
from RevitServices.Persistence import DocumentManager
from RevitServices.Transactions import TransactionManager

doc = DocumentManager.Instance.CurrentDBDocument

clr.AddReference("RevitAPI")
import Autodesk
from Autodesk.Revit.DB import *

schedules = UnwrapElement(IN[0])

OUT = [doc.GetElement(schedules.ViewId)]</Script>
    </PythonNodeModels.PythonNode>
    <Dynamo.Graph.Nodes.CustomNodes.Function guid="8d9f07da-10a2-4ea3-807f-57efe9da9b97" type="Dynamo.Graph.Nodes.CustomNodes.Function" nickname="Tool.PlaceViewsOnSheets" x="454.520670595371" y="1887.49021981408" isVisible="true" isUpstreamVisible="true" lacing="Shortest" isSelectedInput="False" IsFrozen="false" isPinned="false">
      <PortInfo index="0" default="False" />
      <PortInfo index="1" default="False" />
      <PortInfo index="2" default="False" />
      <ID value="98d38af8-1268-475a-8bd9-00ecbfa264b4" />
      <Name value="Tool.PlaceViewsOnSheets" />
      <Description value="Places existing views on existing sheets" />
      <Inputs>
        <Input value="Sheet List" />
        <Input value="Views List" />
        <Input value="Points List" />
      </Inputs>
      <Outputs>
        <Output value="Viewports" />
      </Outputs>
    </Dynamo.Graph.Nodes.CustomNodes.Function>
    <PythonNodeModels.PythonNode guid="39f42cfd-cdc9-46e9-bf1e-7e1ecb0d970f" type="PythonNodeModels.PythonNode" nickname="Python Script" x="323.928915340663" y="2104.84499054623" isVisible="true" isUpstreamVisible="true" lacing="Disabled" isSelectedInput="False" IsFrozen="false" isPinned="true" inputcount="3">
      <PortInfo index="0" default="False" />
      <PortInfo index="1" default="False" />
      <PortInfo index="2" default="False" />
      <Script>#python nodes in dynamo 1.2
#proposed by Julien Benoit @jbenoit44 
#http://aecuandme.wordpress.com/
import clr
clr.AddReference('ProtoGeometry')
from Autodesk.DesignScript.Geometry import *
# Import ToDSType(bool) extension method
clr.AddReference("RevitNodes")
import Revit
clr.ImportExtensions(Revit.Elements)
# Import geometry conversion extension methods
clr.ImportExtensions(Revit.GeometryConversion)
# Import DocumentManager and TransactionManager
clr.AddReference("RevitServices")
import RevitServices
from RevitServices.Persistence import DocumentManager
from RevitServices.Transactions import TransactionManager
from System.Collections.Generic import *
# Import RevitAPI
clr.AddReference("RevitAPI")
import Autodesk
from Autodesk.Revit.DB import *

doc = DocumentManager.Instance.CurrentDBDocument
uiapp = DocumentManager.Instance.CurrentUIApplication
app = uiapp.Application
uidoc=DocumentManager.Instance.CurrentUIApplication.ActiveUIDocument

sheets = []
for i in [IN[0]]:
	sheets.append(UnwrapElement(i))
views=[]	
for i in IN[1]:
	views.append(UnwrapElement(i))
points=[]	
for i in IN[2]:
	points.append(UnwrapElement(i))

# Start Transaction
TransactionManager.Instance.EnsureInTransaction(doc)
viewp=[]
for s,v,p in zip(sheets,views,points):
	a=Viewport.Create(doc, s.Id,v.Id, p)
	viewp.append(a)

# End Transaction
TransactionManager.Instance.TransactionTaskDone()

OUT=viewp</Script>
    </PythonNodeModels.PythonNode>
    <RhythmUI.Sheets guid="06ea173a-58d1-4864-bc15-a4f845d28721" type="RhythmUI.Sheets" nickname="Sheets" x="-261.945055151348" y="1913.42967804961" isVisible="true" isUpstreamVisible="true" lacing="Disabled" isSelectedInput="True" IsFrozen="false" isPinned="false" index="39:25-1-G01B : Bottom Beam Ligs - Building 1 (Superfloor) - Ground Floor - Zone 1" />
    <PythonNodeModels.PythonNode guid="275dea8c-00a6-412b-bfbb-8ffe6187cf45" type="PythonNodeModels.PythonNode" nickname="Python Script" x="-36.4584057505855" y="2215.28195865486" isVisible="true" isUpstreamVisible="true" lacing="Disabled" isSelectedInput="False" IsFrozen="false" isPinned="true" inputcount="1">
      <PortInfo index="0" default="False" />
      <Script># Copyright(c) 2017, Konrad K Sobon
# @arch_laboratory, http://archi-lab.net

import clr
import sys

pyt_path = r'C:\Program Files (x86)\IronPython 2.7\Lib'
sys.path.append(pyt_path)

clr.AddReference('ProtoGeometry')
from Autodesk.DesignScript.Geometry import *

clr.AddReference("RevitNodes")
import Revit

clr.ImportExtensions(Revit.Elements)
clr.ImportExtensions(Revit.GeometryConversion)

clr.AddReference("RevitServices")
from RevitServices.Persistence import DocumentManager
from RevitServices.Transactions import TransactionManager

doc = DocumentManager.Instance.CurrentDBDocument

clr.AddReference("RevitAPI")
import Autodesk
from Autodesk.Revit.DB import *

schedules = UnwrapElement(IN[0])

OUT = [schedules.GetBoxCenter()]</Script>
    </PythonNodeModels.PythonNode>
  </Elements>
  <Connectors>
    <Dynamo.Graph.Connectors.ConnectorModel start="ff0a5d87-8314-46bd-8875-f1950498adae" start_index="0" end="c8bc71f8-6f63-4d22-b427-96b93a0712e8" end_index="0" portType="0" />
    <Dynamo.Graph.Connectors.ConnectorModel start="c8bc71f8-6f63-4d22-b427-96b93a0712e8" start_index="0" end="54072ec1-9bd4-427c-8c21-1308a40b8b94" end_index="1" portType="0" />
    <Dynamo.Graph.Connectors.ConnectorModel start="12fbb78f-b35c-474e-8589-12d2f115fe40" start_index="0" end="54072ec1-9bd4-427c-8c21-1308a40b8b94" end_index="0" portType="0" />
    <Dynamo.Graph.Connectors.ConnectorModel start="f1bb20e2-b636-4b8c-8673-8feb18dbb644" start_index="0" end="02588b68-032d-44fb-9d69-662366fefa70" end_index="0" portType="0" />
    <Dynamo.Graph.Connectors.ConnectorModel start="e9852c96-1328-41f3-ad9e-ed93151cb63f" start_index="0" end="85224a2a-154e-4fbb-9cc9-220a242ac00c" end_index="0" portType="0" />
    <Dynamo.Graph.Connectors.ConnectorModel start="02588b68-032d-44fb-9d69-662366fefa70" start_index="0" end="85224a2a-154e-4fbb-9cc9-220a242ac00c" end_index="1" portType="0" />
    <Dynamo.Graph.Connectors.ConnectorModel start="908eb55c-fc7f-4d04-91c7-e121e5a20e01" start_index="0" end="6ff49109-3772-4b76-8c71-06087879c8dc" end_index="0" portType="0" />
    <Dynamo.Graph.Connectors.ConnectorModel start="908eb55c-fc7f-4d04-91c7-e121e5a20e01" start_index="0" end="275dea8c-00a6-412b-bfbb-8ffe6187cf45" end_index="0" portType="0" />
    <Dynamo.Graph.Connectors.ConnectorModel start="6ff49109-3772-4b76-8c71-06087879c8dc" start_index="0" end="39f42cfd-cdc9-46e9-bf1e-7e1ecb0d970f" end_index="1" portType="0" />
    <Dynamo.Graph.Connectors.ConnectorModel start="06ea173a-58d1-4864-bc15-a4f845d28721" start_index="0" end="39f42cfd-cdc9-46e9-bf1e-7e1ecb0d970f" end_index="0" portType="0" />
    <Dynamo.Graph.Connectors.ConnectorModel start="275dea8c-00a6-412b-bfbb-8ffe6187cf45" start_index="0" end="39f42cfd-cdc9-46e9-bf1e-7e1ecb0d970f" end_index="2" portType="0" />
  </Connectors>
  <Notes />
  <Annotations>
    <Dynamo.Graph.Annotations.AnnotationModel guid="149d687d-899e-4488-a604-9a4b672d9243" annotationText="Set schedules position" left="-311.714302420811" top="498.188772579663" width="813.640429467597" height="454.42604971899" fontSize="30" InitialTop="544.188772579663" InitialHeight="438.42604971899" TextblockHeight="36" backgrouund="#FFC1D676">
      <Models ModelGuid="54072ec1-9bd4-427c-8c21-1308a40b8b94" />
      <Models ModelGuid="ff0a5d87-8314-46bd-8875-f1950498adae" />
      <Models ModelGuid="c8bc71f8-6f63-4d22-b427-96b93a0712e8" />
      <Models ModelGuid="12fbb78f-b35c-474e-8589-12d2f115fe40" />
    </Dynamo.Graph.Annotations.AnnotationModel>
    <Dynamo.Graph.Annotations.AnnotationModel guid="283bf65a-f145-4ca6-86fa-d26a45c55ced" annotationText="Set viewport position" left="-306.80415280017" top="1133.38798703008" width="813.640429467597" height="454.42604971899" fontSize="30" InitialTop="1179.38798703008" InitialHeight="438.42604971899" TextblockHeight="36" backgrouund="#FFC1D676">
      <Models ModelGuid="85224a2a-154e-4fbb-9cc9-220a242ac00c" />
      <Models ModelGuid="f1bb20e2-b636-4b8c-8673-8feb18dbb644" />
      <Models ModelGuid="02588b68-032d-44fb-9d69-662366fefa70" />
      <Models ModelGuid="e9852c96-1328-41f3-ad9e-ed93151cb63f" />
    </Dynamo.Graph.Annotations.AnnotationModel>
  </Annotations>
  <Presets />
  <Cameras>
    <Camera Name="Background Preview" eyeX="-17" eyeY="24" eyeZ="50" lookX="12" lookY="-13" lookZ="-58" upX="0" upY="1" upZ="0" />
  </Cameras>
</Workspace>