<Workspace Version="0.8.2.2392" X="-576.467108214368" Y="-1074.95013378645" zoom="0.85515777690599" Name="Home" Description="" RunType="Manual" RunPeriod="1000" HasRunWithoutCrash="True">
  <NamespaceResolutionMap>
    <ClassMap partialName="Vector.ZAxis" resolvedName="Autodesk.DesignScript.Geometry.Vector" assemblyName="ProtoGeometry.dll" />
    <ClassMap partialName="Vector" resolvedName="Autodesk.DesignScript.Geometry.Vector" assemblyName="ProtoGeometry.dll" />
  </NamespaceResolutionMap>
  <Elements>
    <DSIronPythonNode.PythonNode guid="4fdf6f44-cb77-4b88-b2e6-111faa4d596c" type="DSIronPythonNode.PythonNode" nickname="Python Script" x="2020.21983662741" y="716.920045439136" isVisible="true" isUpstreamVisible="true" lacing="Disabled" isSelectedInput="False" inputcount="2">
      <Script>import clr

clr.AddReference("RevitServices")
import RevitServices
from RevitServices.Persistence import DocumentManager
from RevitServices.Transactions import TransactionManager
doc = DocumentManager.Instance.CurrentDBDocument

clr.AddReference("RevitAPI")
import Autodesk
from Autodesk.Revit.DB import *

clr.AddReference("RevitNodes")
import Revit
clr.ImportExtensions(Revit.Elements)
clr.ImportExtensions(Revit.GeometryConversion)

clr.AddReference("System")
from System.Collections.Generic import List

beamElements = UnwrapElement(IN[0])
pts = UnwrapElement(IN[1])

beamLocations = []

for beam in beamElements:
	beamLocations.append(beam.Location)

newBeamLine = []

TransactionManager.Instance.EnsureInTransaction(doc)

for i in range(0,len(beamLocations)):
	newBeamLine = Line.CreateBound(pts[i][0].ToXyz(), pts[i][1].ToXyz())
	#Change the beam location line to a new line:
	beamLocations[i].Curve = newBeamLine;

            

TransactionManager.Instance.TransactionTaskDone()

OUT = beamElements
</Script>
    </DSIronPythonNode.PythonNode>
    <Dynamo.Nodes.DSModelElementSelection guid="2688073d-e077-49f5-9e05-1b8f6c29509d" type="Dynamo.Nodes.DSModelElementSelection" nickname="Select Model Element" x="50.1733521902942" y="135.435586694563" isVisible="true" isUpstreamVisible="true" lacing="Disabled" isSelectedInput="True" />
    <Dynamo.Nodes.CodeBlockNodeModel guid="752ed20c-aa31-4575-9afe-c460ab8cf59d" type="Dynamo.Nodes.CodeBlockNodeModel" nickname="Code Block" x="654.372588637582" y="243.433181074597" isVisible="true" isUpstreamVisible="true" lacing="Disabled" isSelectedInput="False" CodeText="a[0];" ShouldFocus="false" />
    <DSIronPythonNode.PythonNode guid="737979e8-96b3-4c02-9fe2-12b7f874491b" type="DSIronPythonNode.PythonNode" nickname="Python Script" x="372.001715856097" y="246.063868033687" isVisible="true" isUpstreamVisible="true" lacing="Disabled" isSelectedInput="False" inputcount="1">
      <Script>#Copyright 2017. All rights reserved. Bimorph Consultancy LTD, 5 St Johns Lane, London EC1M 4BH www.bimorph.co.uk
#Written by Thomas Mahon @Thomas__Mahon info@bimorph.co.uk Package: bimorphNodes
#GitHub: https://github.com/ThomasMahon/bimorphNodes/
#Follow: facebook.com/bimorphBIM | linkedin.com/company/bimorph-bim | @bimorphBIM

import clr

# Import RevitAPI
clr.AddReference("RevitAPI")
import Autodesk
from Autodesk.Revit.DB import *

dwgImport = IN[0]

if isinstance(dwgImport, list):
	singleton = False
else:
	singleton = True
	dwgImport = [dwgImport]

layerList = []
for dwg in dwgImport:
	dwgAPI = UnwrapElement(dwg)
	catSub = dwgAPI.Category.SubCategories
	enum = catSub.GetEnumerator()
	
	subList = []
	while enum.MoveNext():
		layerName = enum.Current.Name
		subList.Add( layerName )
		
	layerList.append(subList)
		
OUT = layerList[0] if singleton else layerList  #Preserve behaviour of node prior to v2.1</Script>
    </DSIronPythonNode.PythonNode>
    <DSCoreNodesUI.BoolSelector guid="780a338f-3338-438b-a79b-d7a014fa13be" type="DSCoreNodesUI.BoolSelector" nickname="Boolean" x="685.507595886599" y="396.248611581254" isVisible="true" isUpstreamVisible="true" lacing="Disabled" isSelectedInput="True">
      <System.Boolean>False</System.Boolean>
    </DSCoreNodesUI.BoolSelector>
    <DSRevitNodesUI.Levels guid="7314a9ab-6059-40fe-aa51-e8368aaa31da" type="DSRevitNodesUI.Levels" nickname="Levels" x="654.372588637582" y="523.858950738027" isVisible="true" isUpstreamVisible="true" lacing="Disabled" isSelectedInput="True" index="-1" />
    <DSIronPythonNode.PythonNode guid="9727b79f-8b52-4859-865d-48a7410b7b46" type="DSIronPythonNode.PythonNode" nickname="Python Script" x="1183.55095223376" y="130.906078873327" isVisible="true" isUpstreamVisible="true" lacing="Disabled" isSelectedInput="False" inputcount="4">
      <Script>#Copyright 2016. All rights reserved. Bimorph Consultancy LTD, 5 St Johns Lane, London EC1M 4BH www.bimorph.co.uk
#Written by Thomas Mahon @Thomas__Mahon info@bimorph.co.uk package: bimorphNodes
#GitHub: https://github.com/ThomasMahon/bimorphNodes/

import clr

# Import DocumentManager and TransactionManager
clr.AddReference("RevitServices")
import RevitServices
from RevitServices.Persistence import DocumentManager
from RevitServices.Transactions import TransactionManager
from System.Collections.Generic import *

clr.AddReference("RevitNodes")
import Revit
# Import ToProtoType, ToRevitType geometry conversion extension methods
clr.ImportExtensions(Revit.GeometryConversion)

# Import RevitAPI
clr.AddReference("RevitAPI")
import Autodesk
from Autodesk.Revit.DB import *

doc = DocumentManager.Instance.CurrentDBDocument
uiapp = DocumentManager.Instance.CurrentUIApplication
app = uiapp.Application

importDWG = UnwrapElement(IN[0])
nameOfLayersToImport = IN[1]
revitModelLines = IN[2]

if nameOfLayersToImport == None or nameOfLayersToImport == []: 
	catSub = importDWG.Category.SubCategories
	enum = catSub.GetEnumerator()
	
	nameOfLayersToImport = []
	while enum.MoveNext():
		layerName = enum.Current.Name
		nameOfLayersToImport.Add( layerName )

if isinstance(nameOfLayersToImport, list):
	layerList = nameOfLayersToImport
else:
	layerList = [nameOfLayersToImport]

def storageDictionary(crvListDict, eleGraphicStyleName, e):
	if eleGraphicStyleName in crvListDict.keys(): 
		crvListDict[eleGraphicStyleName].append( e )
	else:
		crvListDict[eleGraphicStyleName] = []
		crvListDict[eleGraphicStyleName].append( e )
		
	
def curveConversion (crv, revitModelLines, crvObject, refPlane):
	if revitModelLines == True:
		crv.Add( doc.Create.NewModelCurve( crvObject, refPlane) )
	else:
		crv.Add( crvObject.ToProtoType() )
	
TransactionManager.Instance.EnsureInTransaction(doc)

geomEnum = importDWG.Geometry[ Options() ].GetEnumerator()

crvListDict = dict()
failedFilter = []
while geomEnum.MoveNext(): 
	instGeom = geomEnum.Current.GetInstanceGeometry()
	
	instGeomEnum = instGeom.GetEnumerator()
	while instGeomEnum.MoveNext():
		e = instGeomEnum.Current
		try:
			graphicStyleId = e.GraphicsStyleId
					
			eleGraphicStyle = doc.GetElement(graphicStyleId)
			eleGraphicStyleName = eleGraphicStyle.GraphicsStyleCategory.Name
			
			
			if eleGraphicStyleName in layerList: 
				storageDictionary(crvListDict, eleGraphicStyleName, e)

		except:
			try: 
				vol = e.Volume
				
				if vol == 0.0: 
					edgesList = e.Edges
					edgesEnum = edgesList.GetEnumerator()

					while edgesEnum.MoveNext():
						edge = edgesEnum.Current
						eleGraphicStyle = doc.GetElement(edge.GraphicsStyleId)
						eleGraphicStyleName = eleGraphicStyle.GraphicsStyleCategory.Name
						
						if eleGraphicStyleName in layerList:
							storageDictionary(crvListDict, eleGraphicStyleName, edge.AsCurve() )
							
			except: 
				failedFilter.Add(e)

if "2015" in app.VersionName:
	levelParam = "Base Level"
else:
	levelParam = BuiltInParameter.IMPORT_BASE_LEVEL

levelId = UnwrapElement(IN[3]).Id

pln = SketchPlane.Create(doc, levelId )
	
crvList = [ crv for crv in crvListDict.values() ] 

failedConversion = []
modelLines =  []
for subList in crvList: 
	crv = []
	for i in subList: 
		try:
			crvType = i.GetType()
			if crvType != Autodesk.Revit.DB.PolyLine:
				curveConversion(crv, revitModelLines, i, pln)
			else: 
				pt = i.GetCoordinates()
				count = i.NumberOfCoordinates
					
				for j in range(count-1): 
					ln = Line.CreateBound(pt[j], pt[j+1])
					curveConversion(crv, revitModelLines, ln, pln)
						
		except: 
			failedConversion.Add( i )
				
	modelLines.Add(crv)

TransactionManager.Instance.TransactionTaskDone()

OUT = modelLines, crvListDict.keys()</Script>
    </DSIronPythonNode.PythonNode>
    <Dynamo.Nodes.DSFunction guid="0dccd603-4f09-45e8-bdde-4e160dc3c5fd" type="Dynamo.Nodes.DSFunction" nickname="ModelCurve.ByCurve" x="1827.06520909476" y="109.019936117486" isVisible="true" isUpstreamVisible="true" lacing="Shortest" isSelectedInput="False" assembly="RevitNodes.dll" function="Revit.Elements.ModelCurve.ByCurve@Autodesk.DesignScript.Geometry.Curve" />
    <Dynamo.Nodes.CodeBlockNodeModel guid="e157f474-4dae-4c79-877e-5c21d18c2d7d" type="Dynamo.Nodes.CodeBlockNodeModel" nickname="Code Block" x="1513.84472533109" y="157.630321223577" isVisible="true" isUpstreamVisible="true" lacing="Disabled" isSelectedInput="False" CodeText="a[0][0];" ShouldFocus="false" />
    <Dynamo.Nodes.DSModelElementSelection guid="acf629a4-74fa-4fcc-aa17-ff11c908dc4c" type="Dynamo.Nodes.DSModelElementSelection" nickname="Select Model Element" x="1105.44650804347" y="687.109845143387" isVisible="true" isUpstreamVisible="true" lacing="Disabled" isSelectedInput="True" />
    <Dynamo.Nodes.DSModelElementSelection guid="42d73ffa-5535-4dbd-bc8d-969b35ad80fd" type="Dynamo.Nodes.DSModelElementSelection" nickname="Select Model Element" x="1016.54099071421" y="879.044415809702" isVisible="true" isUpstreamVisible="true" lacing="Disabled" isSelectedInput="True" />
    <Dynamo.Nodes.DSFunction guid="7d820da3-b53a-461e-852f-2526e1cad8b4" type="Dynamo.Nodes.DSFunction" nickname="Element.Curves" x="1320.52247085105" y="880.439901089887" isVisible="true" isUpstreamVisible="true" lacing="Shortest" isSelectedInput="False" assembly="RevitNodes.dll" function="Revit.Elements.Element.Curves" />
    <Dynamo.Nodes.DSFunction guid="feaa5197-d02f-4c77-b7f4-e14a25c9fa02" type="Dynamo.Nodes.DSFunction" nickname="Curve.PointAtParameter" x="1656.2254221351" y="922.289883981965" isVisible="true" isUpstreamVisible="true" lacing="Longest" isSelectedInput="False" assembly="ProtoGeometry.dll" function="Autodesk.DesignScript.Geometry.Curve.PointAtParameter@double">
      <PortInfo index="1" default="True" />
    </Dynamo.Nodes.DSFunction>
    <Dynamo.Nodes.CodeBlockNodeModel guid="16a27ed9-4fa8-48a1-bfa6-9110acf1b6ae" type="Dynamo.Nodes.CodeBlockNodeModel" nickname="Code Block" x="1495.68479769935" y="1031.73613679314" isVisible="true" isUpstreamVisible="true" lacing="Disabled" isSelectedInput="True" CodeText="{0,1};" ShouldFocus="false" />
    <Dynamo.Nodes.CodeBlockNodeModel guid="4ccb3297-a8e2-4c79-9456-4efd84f217f7" type="Dynamo.Nodes.CodeBlockNodeModel" nickname="Code Block" x="1653.32406568389" y="720.797195084525" isVisible="true" isUpstreamVisible="true" lacing="Disabled" isSelectedInput="False" CodeText="{a};" ShouldFocus="false" />
    <Dynamo.Nodes.CodeBlockNodeModel guid="31d25358-0c1c-486a-9a9c-fdfa31d3f456" type="Dynamo.Nodes.CodeBlockNodeModel" nickname="Code Block" x="1910.5590833995" y="891.955862225771" isVisible="true" isUpstreamVisible="true" lacing="Disabled" isSelectedInput="False" CodeText="{a};" ShouldFocus="false" />
    <DSIronPythonNode.PythonNode guid="df97c136-2705-4f77-8875-f7e528c24456" type="DSIronPythonNode.PythonNode" nickname="Python Script" x="1111.04489980577" y="1587.23218452872" isVisible="true" isUpstreamVisible="true" lacing="Disabled" isSelectedInput="False" inputcount="1">
      <Script>#Copyright(c) 2017, john pierson
# @60secondrevit, http://sixtysecondrevit.com
#Based on a node from Dimitar Venkov
#adapted by john pierson for rhythm
import clr

clr.AddReference("RevitAPIUI")
from  Autodesk.Revit.UI import *

clr.AddReference("RevitServices")
import RevitServices
from RevitServices.Persistence import DocumentManager
doc = DocumentManager.Instance.CurrentDBDocument
uidoc=DocumentManager.Instance.CurrentUIApplication.ActiveUIDocument

clr.AddReference("RevitNodes")
import Revit
clr.ImportExtensions(Revit.Elements)

sel1 = uidoc.Selection
ot1 = Selection.ObjectType.Element
el_ref = sel1.PickObjects(ot1, "Select model elements")
typelist = list()
idlist = list()
for i in el_ref:
	
	try:
		typelist.append(doc.GetElement(i.ElementId))
	except:
		typelist.append(list())
		

OUT = typelist</Script>
    </DSIronPythonNode.PythonNode>
    <DSIronPythonNode.PythonNode guid="736c288e-5f0a-4730-8cc6-8aa2d3c6e542" type="DSIronPythonNode.PythonNode" nickname="Python Script" x="1919.98963157223" y="1319.52271715477" isVisible="true" isUpstreamVisible="true" lacing="Disabled" isSelectedInput="False" inputcount="1">
      <Script>#Copyright(c) 2017, john pierson
# @60secondrevit, http://sixtysecondrevit.com
#Based on a node from Dimitar Venkov
#adapted by john pierson for rhythm
import clr

clr.AddReference("RevitAPIUI")
from  Autodesk.Revit.UI import *

clr.AddReference("RevitServices")
import RevitServices
from RevitServices.Persistence import DocumentManager
doc = DocumentManager.Instance.CurrentDBDocument
uidoc=DocumentManager.Instance.CurrentUIApplication.ActiveUIDocument

clr.AddReference("RevitNodes")
import Revit
clr.ImportExtensions(Revit.Elements)

sel1 = uidoc.Selection
ot1 = Selection.ObjectType.Element
el_ref = sel1.PickObjects(ot1, "Select model elements")
typelist = list()
idlist = list()
for i in el_ref:
	
	try:
		typelist.append(doc.GetElement(i.ElementId))
	except:
		typelist.append(list())
		

OUT = typelist</Script>
    </DSIronPythonNode.PythonNode>
    <Dynamo.Nodes.DSFunction guid="59e59a0d-c950-467d-8335-30e266604372" type="Dynamo.Nodes.DSFunction" nickname="Element.Curves" x="1397.20964110922" y="1590.80970178222" isVisible="true" isUpstreamVisible="true" lacing="Shortest" isSelectedInput="False" assembly="RevitNodes.dll" function="Revit.Elements.Element.Curves" />
    <Dynamo.Nodes.CodeBlockNodeModel guid="552c6d2d-e1d8-461b-bfd5-c2228ff39bda" type="Dynamo.Nodes.CodeBlockNodeModel" nickname="Code Block" x="1743.02916166571" y="1718.73089517526" isVisible="true" isUpstreamVisible="true" lacing="Disabled" isSelectedInput="True" CodeText="{0,1};" ShouldFocus="false" />
    <Dynamo.Nodes.DSFunction guid="7e1aa6d5-c7dd-4b11-bd99-65c606eab972" type="Dynamo.Nodes.DSFunction" nickname="Curve.PointAtParameter" x="1955.4787971654" y="1577.50361518209" isVisible="true" isUpstreamVisible="true" lacing="CrossProduct" isSelectedInput="False" assembly="ProtoGeometry.dll" function="Autodesk.DesignScript.Geometry.Curve.PointAtParameter@double">
      <PortInfo index="1" default="True" />
    </Dynamo.Nodes.DSFunction>
    <Dynamo.Nodes.DSFunction guid="b84885d6-1962-425a-9b61-33389a69e958" type="Dynamo.Nodes.DSFunction" nickname="List.Flatten" x="1719.38536710211" y="1573.98780450042" isVisible="true" isUpstreamVisible="true" lacing="Shortest" isSelectedInput="False" assembly="DSCoreNodes.dll" function="DSCore.List.Flatten@var[]..[],int" />
    <Dynamo.Nodes.CodeBlockNodeModel guid="9d339760-421a-466c-b6b2-a8f124ef7e6b" type="Dynamo.Nodes.CodeBlockNodeModel" nickname="Code Block" x="1605.66229203654" y="1665.30608660014" isVisible="true" isUpstreamVisible="true" lacing="Disabled" isSelectedInput="True" CodeText="1;" ShouldFocus="false" />
    <DSIronPythonNode.PythonNode guid="7d767524-8b53-4fd4-817d-f76e9405b41e" type="DSIronPythonNode.PythonNode" nickname="Python Script" x="2360.58835502089" y="1362.70738674479" isVisible="true" isUpstreamVisible="true" lacing="Disabled" isSelectedInput="False" inputcount="2">
      <Script>import clr

clr.AddReference("RevitServices")
import RevitServices
from RevitServices.Persistence import DocumentManager
from RevitServices.Transactions import TransactionManager
doc = DocumentManager.Instance.CurrentDBDocument

clr.AddReference("RevitAPI")
import Autodesk
from Autodesk.Revit.DB import *

clr.AddReference("RevitNodes")
import Revit
clr.ImportExtensions(Revit.Elements)
clr.ImportExtensions(Revit.GeometryConversion)

clr.AddReference("System")
from System.Collections.Generic import List

beamElements = UnwrapElement(IN[0])
pts = UnwrapElement(IN[1])

beamLocations = []

for beam in beamElements:
	beamLocations.append(beam.Location)

newBeamLine = []

TransactionManager.Instance.EnsureInTransaction(doc)

for i in range(0,len(beamLocations)):
	newBeamLine = Line.CreateBound(pts[i][0].ToXyz(), pts[i][1].ToXyz())
	#Change the beam location line to a new line:
	beamLocations[i].Curve = newBeamLine;

            

TransactionManager.Instance.TransactionTaskDone()

OUT = beamElements
</Script>
    </DSIronPythonNode.PythonNode>
    <Dynamo.Nodes.DSModelElementsSelection guid="47bf5dc6-5241-4e38-9d50-722aded0414e" type="Dynamo.Nodes.DSModelElementsSelection" nickname="Select Model Elements" x="147.122991694116" y="1340.70958152487" isVisible="true" isUpstreamVisible="true" lacing="Disabled" isSelectedInput="True" />
    <Dynamo.Nodes.DSFunction guid="f82028bb-7fe5-4ee8-93fc-2441899f7980" type="Dynamo.Nodes.DSFunction" nickname="FamilyInstance.Location" x="627.857200980348" y="1372.65512732653" isVisible="true" isUpstreamVisible="true" lacing="Shortest" isSelectedInput="False" assembly="RevitNodes.dll" function="Revit.Elements.FamilyInstance.Location" />
    <Dynamo.Nodes.Function guid="86e1357d-35b6-40e0-ad20-c840ffbc3de9" type="Dynamo.Nodes.Function" nickname="Element.Location" x="529.817092279143" y="1596.52716445243" isVisible="true" isUpstreamVisible="true" lacing="Shortest" isSelectedInput="False">
      <ID value="0b59c4d8-afe4-4063-bf7e-2195fa33e8a9" />
      <Name value="Element.Location" />
      <Description value="Returns the location of an element as an XYZ (or if it's line-based the start and end point of the line), along with some booleans to help filtering the results. Use this for some element types (e.g. walls or lines) that do not work with the built-in Get Family Instance Location node. " />
      <Inputs>
        <Input value="element" />
      </Inputs>
      <Outputs>
        <Output value="points" />
        <Output value="curveEndpoints" />
        <Output value="curves" />
        <Output value="isPoint" />
        <Output value="isCurve" />
        <Output value="hasLocation" />
      </Outputs>
    </Dynamo.Nodes.Function>
    <Dynamo.Nodes.CodeBlockNodeModel guid="19a88fad-8763-470e-a70a-91768b965c91" type="Dynamo.Nodes.CodeBlockNodeModel" nickname="Code Block" x="1074.62815156867" y="1768.46125006386" isVisible="true" isUpstreamVisible="true" lacing="Disabled" isSelectedInput="False" CodeText="a;" ShouldFocus="false" />
    <Dynamo.Nodes.DSFunction guid="328d7463-8aea-4d11-b0ab-bee77ef36690" type="Dynamo.Nodes.DSFunction" nickname="Element.GetParameterValueByName" x="443.09551250512" y="2181.72444018707" isVisible="true" isUpstreamVisible="true" lacing="CrossProduct" isSelectedInput="False" assembly="RevitNodes.dll" function="Revit.Elements.Element.GetParameterValueByName@string" />
    <Dynamo.Nodes.CodeBlockNodeModel guid="2411efa4-4735-4d4f-8be1-18df9ebc833b" type="Dynamo.Nodes.CodeBlockNodeModel" nickname="Code Block" x="107.749083753852" y="2226.61837282915" isVisible="true" isUpstreamVisible="true" lacing="Disabled" isSelectedInput="True" CodeText="{&quot;Top Offset&quot;, &quot;Base Offset&quot;};" ShouldFocus="false" />
    <DSIronPythonNode.PythonNode guid="bc972e63-6116-44b1-acb6-09b4ef1d3162" type="DSIronPythonNode.PythonNode" nickname="Python Script" x="833.265362484436" y="2184.36734326477" isVisible="true" isUpstreamVisible="true" lacing="Disabled" isSelectedInput="False" inputcount="1">
      <Script>import clr
clr.AddReference('ProtoGeometry')
from Autodesk.DesignScript.Geometry import *
#The inputs to this node will be stored as a list in the IN variables.
values = IN[0]
height = []

for i in range(0,len(values)):
	height.append(values[i][0]-values[i][1])

#Assign your output to the OUT variable.
OUT = height</Script>
    </DSIronPythonNode.PythonNode>
    <Dynamo.Nodes.DSFunction guid="9c935a8f-bf73-4344-9527-11cfe5fe81ed" type="Dynamo.Nodes.DSFunction" nickname="Geometry.Translate" x="1359.87834605166" y="2148.55213312834" isVisible="true" isUpstreamVisible="true" lacing="Shortest" isSelectedInput="False" assembly="ProtoGeometry.dll" function="Autodesk.DesignScript.Geometry.Geometry.Translate@Autodesk.DesignScript.Geometry.Vector,double" />
    <Dynamo.Nodes.CodeBlockNodeModel guid="c9490e8f-5036-4727-9cea-e8aa09c469be" type="Dynamo.Nodes.CodeBlockNodeModel" nickname="Code Block" x="1092.62063339298" y="2158.00282482181" isVisible="true" isUpstreamVisible="true" lacing="Disabled" isSelectedInput="True" CodeText="Vector.ZAxis();" ShouldFocus="false" />
    <Dynamo.Nodes.DSFunction guid="5aac123b-b872-46df-87c2-467315cd6f94" type="Dynamo.Nodes.DSFunction" nickname="Line.ByStartPointEndPoint" x="1751.21370872797" y="2071.40050580736" isVisible="true" isUpstreamVisible="true" lacing="Shortest" isSelectedInput="False" assembly="ProtoGeometry.dll" function="Autodesk.DesignScript.Geometry.Line.ByStartPointEndPoint@Autodesk.DesignScript.Geometry.Point,Autodesk.DesignScript.Geometry.Point" />
    <DSIronPythonNode.PythonNode guid="8a0cfb8a-7494-4a13-860c-d4b1537ce703" type="DSIronPythonNode.PythonNode" nickname="Python Script" x="2621.96034982583" y="1896.14759572842" isVisible="true" isUpstreamVisible="true" lacing="Disabled" isSelectedInput="False" inputcount="2">
      <Script>import clr

clr.AddReference("RevitServices")
import RevitServices
from RevitServices.Persistence import DocumentManager
from RevitServices.Transactions import TransactionManager
doc = DocumentManager.Instance.CurrentDBDocument

clr.AddReference("RevitAPI")
import Autodesk
from Autodesk.Revit.DB import *

clr.AddReference("RevitNodes")
import Revit
clr.ImportExtensions(Revit.Elements)
clr.ImportExtensions(Revit.GeometryConversion)

clr.AddReference("System")
from System.Collections.Generic import List

beamElements = UnwrapElement(IN[0])
pts = UnwrapElement(IN[1])

beamLocations = []

for beam in beamElements:
	beamLocations.append(beam.Location)

newBeamLine = []

TransactionManager.Instance.EnsureInTransaction(doc)

for i in range(0,len(beamLocations)):
	newBeamLine = Line.CreateBound(pts[i][0].ToXyz(), pts[i][1].ToXyz())
	#Change the beam location line to a new line:
	beamLocations[i].Curve = newBeamLine;

            

TransactionManager.Instance.TransactionTaskDone()

OUT = beamElements
</Script>
    </DSIronPythonNode.PythonNode>
    <Dynamo.Nodes.DSModelElementsSelection guid="b9b0bfdf-d944-4a0a-a6e4-ccb0620b478d" type="Dynamo.Nodes.DSModelElementsSelection" nickname="Select Model Elements" x="1783.0920346617" y="1902.74935802437" isVisible="true" isUpstreamVisible="true" lacing="Disabled" isSelectedInput="True" />
    <Dynamo.Nodes.DSFunction guid="b2e47ccf-ffe3-406a-a8f4-8d18f671dae8" type="Dynamo.Nodes.DSFunction" nickname="Curve.PointAtParameter" x="2239.04259624556" y="2132.10966927494" isVisible="true" isUpstreamVisible="true" lacing="CrossProduct" isSelectedInput="False" assembly="ProtoGeometry.dll" function="Autodesk.DesignScript.Geometry.Curve.PointAtParameter@double">
      <PortInfo index="1" default="True" />
    </Dynamo.Nodes.DSFunction>
    <Dynamo.Nodes.CodeBlockNodeModel guid="b7499b1d-febf-496f-b0f4-2150206d4233" type="Dynamo.Nodes.CodeBlockNodeModel" nickname="Code Block" x="2048.09822562151" y="2212.32155075122" isVisible="true" isUpstreamVisible="true" lacing="Disabled" isSelectedInput="True" CodeText="{0,1};" ShouldFocus="false" />
  </Elements>
  <Connectors>
    <Dynamo.Models.ConnectorModel start="2688073d-e077-49f5-9e05-1b8f6c29509d" start_index="0" end="9727b79f-8b52-4859-865d-48a7410b7b46" end_index="0" portType="0" />
    <Dynamo.Models.ConnectorModel start="2688073d-e077-49f5-9e05-1b8f6c29509d" start_index="0" end="737979e8-96b3-4c02-9fe2-12b7f874491b" end_index="0" portType="0" />
    <Dynamo.Models.ConnectorModel start="752ed20c-aa31-4575-9afe-c460ab8cf59d" start_index="0" end="9727b79f-8b52-4859-865d-48a7410b7b46" end_index="1" portType="0" />
    <Dynamo.Models.ConnectorModel start="737979e8-96b3-4c02-9fe2-12b7f874491b" start_index="0" end="752ed20c-aa31-4575-9afe-c460ab8cf59d" end_index="0" portType="0" />
    <Dynamo.Models.ConnectorModel start="780a338f-3338-438b-a79b-d7a014fa13be" start_index="0" end="9727b79f-8b52-4859-865d-48a7410b7b46" end_index="2" portType="0" />
    <Dynamo.Models.ConnectorModel start="7314a9ab-6059-40fe-aa51-e8368aaa31da" start_index="0" end="9727b79f-8b52-4859-865d-48a7410b7b46" end_index="3" portType="0" />
    <Dynamo.Models.ConnectorModel start="9727b79f-8b52-4859-865d-48a7410b7b46" start_index="0" end="e157f474-4dae-4c79-877e-5c21d18c2d7d" end_index="0" portType="0" />
    <Dynamo.Models.ConnectorModel start="e157f474-4dae-4c79-877e-5c21d18c2d7d" start_index="0" end="0dccd603-4f09-45e8-bdde-4e160dc3c5fd" end_index="0" portType="0" />
    <Dynamo.Models.ConnectorModel start="acf629a4-74fa-4fcc-aa17-ff11c908dc4c" start_index="0" end="4ccb3297-a8e2-4c79-9456-4efd84f217f7" end_index="0" portType="0" />
    <Dynamo.Models.ConnectorModel start="42d73ffa-5535-4dbd-bc8d-969b35ad80fd" start_index="0" end="7d820da3-b53a-461e-852f-2526e1cad8b4" end_index="0" portType="0" />
    <Dynamo.Models.ConnectorModel start="7d820da3-b53a-461e-852f-2526e1cad8b4" start_index="0" end="feaa5197-d02f-4c77-b7f4-e14a25c9fa02" end_index="0" portType="0" />
    <Dynamo.Models.ConnectorModel start="feaa5197-d02f-4c77-b7f4-e14a25c9fa02" start_index="0" end="31d25358-0c1c-486a-9a9c-fdfa31d3f456" end_index="0" portType="0" />
    <Dynamo.Models.ConnectorModel start="16a27ed9-4fa8-48a1-bfa6-9110acf1b6ae" start_index="0" end="feaa5197-d02f-4c77-b7f4-e14a25c9fa02" end_index="1" portType="0" />
    <Dynamo.Models.ConnectorModel start="4ccb3297-a8e2-4c79-9456-4efd84f217f7" start_index="0" end="4fdf6f44-cb77-4b88-b2e6-111faa4d596c" end_index="0" portType="0" />
    <Dynamo.Models.ConnectorModel start="31d25358-0c1c-486a-9a9c-fdfa31d3f456" start_index="0" end="4fdf6f44-cb77-4b88-b2e6-111faa4d596c" end_index="1" portType="0" />
    <Dynamo.Models.ConnectorModel start="df97c136-2705-4f77-8875-f7e528c24456" start_index="0" end="59e59a0d-c950-467d-8335-30e266604372" end_index="0" portType="0" />
    <Dynamo.Models.ConnectorModel start="59e59a0d-c950-467d-8335-30e266604372" start_index="0" end="b84885d6-1962-425a-9b61-33389a69e958" end_index="0" portType="0" />
    <Dynamo.Models.ConnectorModel start="552c6d2d-e1d8-461b-bfd5-c2228ff39bda" start_index="0" end="7e1aa6d5-c7dd-4b11-bd99-65c606eab972" end_index="1" portType="0" />
    <Dynamo.Models.ConnectorModel start="7e1aa6d5-c7dd-4b11-bd99-65c606eab972" start_index="0" end="7d767524-8b53-4fd4-817d-f76e9405b41e" end_index="1" portType="0" />
    <Dynamo.Models.ConnectorModel start="b84885d6-1962-425a-9b61-33389a69e958" start_index="0" end="7e1aa6d5-c7dd-4b11-bd99-65c606eab972" end_index="0" portType="0" />
    <Dynamo.Models.ConnectorModel start="9d339760-421a-466c-b6b2-a8f124ef7e6b" start_index="0" end="b84885d6-1962-425a-9b61-33389a69e958" end_index="1" portType="0" />
    <Dynamo.Models.ConnectorModel start="47bf5dc6-5241-4e38-9d50-722aded0414e" start_index="0" end="86e1357d-35b6-40e0-ad20-c840ffbc3de9" end_index="0" portType="0" />
    <Dynamo.Models.ConnectorModel start="47bf5dc6-5241-4e38-9d50-722aded0414e" start_index="0" end="328d7463-8aea-4d11-b0ab-bee77ef36690" end_index="0" portType="0" />
    <Dynamo.Models.ConnectorModel start="86e1357d-35b6-40e0-ad20-c840ffbc3de9" start_index="0" end="19a88fad-8763-470e-a70a-91768b965c91" end_index="0" portType="0" />
    <Dynamo.Models.ConnectorModel start="19a88fad-8763-470e-a70a-91768b965c91" start_index="0" end="9c935a8f-bf73-4344-9527-11cfe5fe81ed" end_index="0" portType="0" />
    <Dynamo.Models.ConnectorModel start="19a88fad-8763-470e-a70a-91768b965c91" start_index="0" end="5aac123b-b872-46df-87c2-467315cd6f94" end_index="0" portType="0" />
    <Dynamo.Models.ConnectorModel start="328d7463-8aea-4d11-b0ab-bee77ef36690" start_index="0" end="bc972e63-6116-44b1-acb6-09b4ef1d3162" end_index="0" portType="0" />
    <Dynamo.Models.ConnectorModel start="2411efa4-4735-4d4f-8be1-18df9ebc833b" start_index="0" end="328d7463-8aea-4d11-b0ab-bee77ef36690" end_index="1" portType="0" />
    <Dynamo.Models.ConnectorModel start="bc972e63-6116-44b1-acb6-09b4ef1d3162" start_index="0" end="9c935a8f-bf73-4344-9527-11cfe5fe81ed" end_index="2" portType="0" />
    <Dynamo.Models.ConnectorModel start="9c935a8f-bf73-4344-9527-11cfe5fe81ed" start_index="0" end="5aac123b-b872-46df-87c2-467315cd6f94" end_index="1" portType="0" />
    <Dynamo.Models.ConnectorModel start="c9490e8f-5036-4727-9cea-e8aa09c469be" start_index="0" end="9c935a8f-bf73-4344-9527-11cfe5fe81ed" end_index="1" portType="0" />
    <Dynamo.Models.ConnectorModel start="5aac123b-b872-46df-87c2-467315cd6f94" start_index="0" end="b2e47ccf-ffe3-406a-a8f4-8d18f671dae8" end_index="0" portType="0" />
    <Dynamo.Models.ConnectorModel start="b9b0bfdf-d944-4a0a-a6e4-ccb0620b478d" start_index="0" end="8a0cfb8a-7494-4a13-860c-d4b1537ce703" end_index="0" portType="0" />
    <Dynamo.Models.ConnectorModel start="b2e47ccf-ffe3-406a-a8f4-8d18f671dae8" start_index="0" end="8a0cfb8a-7494-4a13-860c-d4b1537ce703" end_index="1" portType="0" />
    <Dynamo.Models.ConnectorModel start="b7499b1d-febf-496f-b0f4-2150206d4233" start_index="0" end="b2e47ccf-ffe3-406a-a8f4-8d18f671dae8" end_index="1" portType="0" />
  </Connectors>
  <Notes />
  <Annotations>
    <Dynamo.Models.AnnotationModel guid="4063e930-e44b-4e46-a01d-164382101e57" annotationText="SELECT DWG AND CREATE MODEL LINES" left="40.1733521902942" top="56.019936117486" width="2114.04648443712" height="1068.71620067565" fontSize="36" InitialTop="109.019936117486" InitialHeight="1621.09921172349" TextblockHeight="43" backgrouund="#FFD4B6DB">
      <Models ModelGuid="4fdf6f44-cb77-4b88-b2e6-111faa4d596c" />
      <Models ModelGuid="2688073d-e077-49f5-9e05-1b8f6c29509d" />
      <Models ModelGuid="752ed20c-aa31-4575-9afe-c460ab8cf59d" />
      <Models ModelGuid="737979e8-96b3-4c02-9fe2-12b7f874491b" />
      <Models ModelGuid="780a338f-3338-438b-a79b-d7a014fa13be" />
      <Models ModelGuid="7314a9ab-6059-40fe-aa51-e8368aaa31da" />
      <Models ModelGuid="9727b79f-8b52-4859-865d-48a7410b7b46" />
      <Models ModelGuid="0dccd603-4f09-45e8-bdde-4e160dc3c5fd" />
      <Models ModelGuid="e157f474-4dae-4c79-877e-5c21d18c2d7d" />
      <Models ModelGuid="42d73ffa-5535-4dbd-bc8d-969b35ad80fd" />
      <Models ModelGuid="7d820da3-b53a-461e-852f-2526e1cad8b4" />
      <Models ModelGuid="feaa5197-d02f-4c77-b7f4-e14a25c9fa02" />
      <Models ModelGuid="16a27ed9-4fa8-48a1-bfa6-9110acf1b6ae" />
      <Models ModelGuid="4ccb3297-a8e2-4c79-9456-4efd84f217f7" />
      <Models ModelGuid="31d25358-0c1c-486a-9a9c-fdfa31d3f456" />
    </Dynamo.Models.AnnotationModel>
    <Dynamo.Models.AnnotationModel guid="87978437-a64a-42a2-8435-433aa9c0ae29" annotationText="select beam" left="1095.44650804347" top="657.109845143387" width="189" height="124" fontSize="14" InitialTop="687.109845143387" InitialHeight="124" TextblockHeight="20" backgrouund="#FFC1D676">
      <Models ModelGuid="acf629a4-74fa-4fcc-aa17-ff11c908dc4c" />
    </Dynamo.Models.AnnotationModel>
  </Annotations>
  <Presets />
  <Cameras>
    <Camera Name="background_preview" eyeX="317.152692199911" eyeY="319.652192163624" eyeZ="317.152692199911" lookX="-317.152692199911" lookY="-317.152692199911" lookZ="-317.152692199911" />
  </Cameras>
</Workspace>